### ISSUE TITLE
Define a minimal FxA client API for oauth apps

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#10]
In our meeting last week, @eoger @vladikoff and I kicked around some ideas for what API to expose the FxA client apps such as lockbox.  It will hopefully be different from (and simpler than) the FxA Client API used by Firefox Desktop, because it's based on OAuth rather than our bespoke login protocol.

Here's some more detailed thoughts on what it might look like.

At a high level, we need the following functionality:
* The ability to serialize state for storage by the application, and to restore from serialized state.
* The ability for the application to request an OAuth `access_token` (and any corresponding keys) for a given set of scopes.  This could fail for the following reasons:
    * The user hasn't signed in at all yet.
    * The user has signed in, but didn't grant that particular scope.
    * The user has signed in, but our tokens have expired or been revoked
        * This could happen due to explicit revokation, or password reset.
* The ability for the application, in response to one of the above errors, to launch an OAuth flow and provide back updated credentials.

We could also provide some additional helpers on top of this basic functionality, e.g. ability to fetch and cache profile data.  But the above is the core OAuth functionality on which the rest would be based.

The FxA client's internal state would need to contain:

* The app's OAuth client_id, and OAuth issuer URL ("https://accounts.firefox.com" in production).
* Basic info about the user who has logged in, e.g. their `uid`.
* The list of scopes on that refresh_token
* The JWKs for any corresponding keys for the above scopes

A client attempting to access, say, sync data, would begin by loading the FxAClient from serialized state:

```
fxaClient = FxAClient::from_seralized_state(APP_CLIENT_ID, "....")
```

It could then ask for an `access_token` and keys with which to talk to the sync service:

```
token, keys = fxaClient.get_access_token_and_keys(scope=["https://identity.mozilla.com/apps/oldsync"])
```

Unfortunately the user hasn't signed in yet, so it will return an error to the app, and the app will need to prompt the user for authorization.  It calls into the client to initiate an OAuth flow:

```
url = fxaClient.begin_oauth_flow(
    scope=["https://identity.mozilla.com/apps/oldsync"]
    redirect_uri=APP_REGISTERED_REDIRECT_URI
)
```

The client would set up some internal state for an in-progress OAuth flow, such as a `keys_jwk` and an OAuth `state` token, and would return a URL for the app to load for the user.  When the OAuth dance completes, the app would capture the result from the redirect and pass it back to the client:

```
fxaClient.complete_oauth_flow(code="ABCD", state="XYZ")
```

The client would do all the tricky oauth bits, like validating `state`, exchanging the `code` for some OAuth tokens, decrypting the `keys_jwe`, etc.  It would store the results into its internal state, so that when the client asks again for tokens to talk to sync:

```
token, keys = fxaClient.get_access_token_and_keys(scope=["https://identity.mozilla.com/apps/oldsync"])
```

It can return them successfully, possibly by using its `refresh_token` to mint a new `access_token`.

I think that's almost everything that would be required for a minimal client - the `token` and `keys` from the above can be passed downstream to a sync client library for actual fetching of sync data.

@eoger @vladikoff does that make sense?  How well does the above map onto your "sandwich" model prototype?

**Comment by eoger** [comment]
This spec is very close to what we are currently implementing, no questions so far :)

**Comment by eoger** [comment]
I think this is more or less what we have now, can we close this?

**Comment by rfk** [comment]
👍
