### ISSUE TITLE
fenix-megazord .aar contains liblockbox.so

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1000]
```
$ ls fenix-megazord-0.25.2-SNAPSHOT2/jni/x86
libfenix.so    libnspr4.so    libnssutil3.so  libsmime3.so
libfreebl3.so  libnss3.so     libplc4.so      libsoftokn3.so
liblockbox.so  libnssckbi.so  libplds4.so
```

Something seems to remove this from fenix later down the line[0], but it's still bad.

[0]: I'm judging this solely by it not turning up before when @rfk unpacked the .apks and looked inside.

**Comment by vladikoff** [comment]
@thomcc fixed by https://github.com/mozilla/application-services/pull/1021 ?

**Comment by rfk** [comment]
Closing as fixed by https://github.com/mozilla/application-services/pull/1021, please re-open if this persists.
