### ISSUE TITLE
Make sure build-all.sh is run from libs/

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1013]
From https://github.com/mozilla/application-services/issues/1012#issuecomment-484170081 people may be confused and run it directly from the root directory.

**Comment by vladikoff** [comment]
Extra confusing, because other scripts say the opposite  `ERROR: verify-android-environment.sh should be run from the root directory of the repo`

**Comment by hardik25** [comment]
Hi @eoger, 

I would like to take a look. Could you please assign it to me?

**Comment by eoger** [comment]
Hi @hardik25, our policy is to assign issues once a patch has been submitted. Feel free to post a PR :)
