### ISSUE TITLE
Document verify-android-environment.sh in setup-android-build-environment.md

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1014]
Surprisingly there's no mention of the script anywhere, it could avoid headaches like https://github.com/mozilla/application-services/issues/1012 which was provoked by a missing environment variable.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-723)

**Comment by MukulMaheshwari** [comment]
I would like to work on this issue. can u please elaborate the task as i am very new to this. And please tell how can i access JIRA for this. Thanks

**Comment by eoger** [comment]
Hi @MukulMaheshwari, thanks for your interest!
I ended up fixing this bug in #2412 but did not realized it closed this issue, thanks for reminding me 😛
