### ISSUE TITLE
API to import bookmarks from legacy Firefox for iOS browser.db

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#1017]
We will need an API to bulk import existing bookmarks from the legacy Firefox for iOS database. Ideally, we could simply pass a path to the browser.db SQLite database file.

**Comment by thomcc** [comment]
The indication we were given in the meeting between myself @linacambridge, @justindarc, and @garvankeeley was that this was a fairly hard requirement of using bookmarks on iOS, and needs to be in by 5/3 or bookmarks will slip to the next iOS release

**Comment by thomcc** [comment]
As discussed in slack, I took this (forgot to change the flag immediately)
