### ISSUE TITLE
Link against NSS on iOS

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1041]
In #1038 we added a quick fix for using Ring on iOS instead of NSS. There are a lot of reasons we don't want to do this, and we won't enumerate them here.

This was done because it's unclear how to integrate NSS's `dylib`s into the build on iOS.  The specific error is:

> Invalid Bundle Structure - The binary file 'Client.app/Frameworks/Storage.framework/Frameworks/libnssckbi.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

This indicates to me that we need our build of NSS to produce a .framework and not a pile of dylibs. Alternatively, #956 would eliminate the issue. Alternatively, it's possible this is simply a misconfiguration of one or more .xcodeproj files.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-60)
┆Sprint: SYNC - 2019-07-19
┆Epic: Trusted Crypto

**Comment by eoger** [comment]
For the record, we believe that XCode 10.2 alongside with Swift 5 (https://github.com/mozilla-mobile/firefox-ios/issues/4755) would solve this problem as it lets the user add dylibs to the set of embedded libraries.

**Comment by rfk** [comment]
> we believe that XCode 10.2 alongside 

IIUC this is now available as of https://github.com/mozilla/application-services/pull/1088 landing. Does that put us in a position to try again re: linking to NSS on iOS, to do we also need to wait for consuming apps to update to Swift 5?

/cc @eoger @garvankeeley

**Comment by garvankeeley** [comment]
I am not aware of the change for Swift 5 that allows for dylib inclusion (https://www.google.com/search?q=%22swift+5%22+dylib didn't yield anything obvious). I think we could find the bandwidth to update to Swift 5 if needed. Typically it is our dependencies that slow our migration to new versions.
