### ISSUE TITLE
Rename LoginsStoreError enum variants in swift code

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1042]
Most of these are `UpperCamelCase`, but they should be `lowerCamelCase` to fit common swift style, and better meet the convention set by the rest of our libs.

This will need a changelog entry.

**Comment by hardik25** [comment]
Hi @thomcc 

I would like to take up this issue. Could you please assign it to me? Thanks!

**Comment by thomcc** [comment]
I think I can only assign members of the repo, but if you want it feel free.
