### ISSUE TITLE
Separate HTTP init from megazord init

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1066]
From slack:

> whawkins another option is for us to move the http init into its own thing (it initially was going to be, but grisha and some others thought that the current way is a nicer API, which I agree with). this would make megazord init very cheap. you'd then need to init the logger and networking at some point before they're actually needed
> but that's probably not *too* bad, although it could be a little tricky

This is essentially to reduce (well, delay) the cost of initializing the megazord / JNA.

Edit: Sorry unrelated people I just notified!

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-63)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-19

**Comment by jdragojevic** [comment]
https://github.com/mozilla/application-services/pull/1103 is the in-progress PR for this issue.
