### ISSUE TITLE
[logins] Ensure that a single Sync 1.5 "flow" results in a single Mentat transaction

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#107]
Right now, the [initial landing branch](https://github.com/ncalexan/application-services/tree/logins) produces a lot of "empty" Mentat transactions (i.e., ones which only have a `:db/txInstant`) as part of the Sync 1.5 flow.  This ticket tracks the narrow outcome of ensuring that a single "sync" results in a single Mentat transaction.

However, those empty transactions are a sign of a larger problem: it's not natural to build large transactions in Rust, because the transaction datatype (`Entities`) is awkward to manipulate.  In Clojure, the transaction datatype is built of Clojure-native things (vectors, lists, maps) so it's very natural to grow a single structure for transaction.  This ticket might point to larger changes in the input structures that Mentat can process.

**Comment by ncalexan** [comment]
This isn't critical for the initial Lockbox for Android prototype: it's a hygiene issue.

**Comment by rfk** [comment]
Will revisit this for the sqlite backend
