### ISSUE TITLE
License boilerplate of rc_crypto component is wrong

### ISSUE THREAD

**Issue by briansmith** [mozilla/application-services#1074]
The Rust code in *ring* is licensed under the ISC license. In this repo, the code copied from *ring* has been given put in files that have the MPL license header, but *ring* has never been licensed under MPL. Please fix the license headers of these files and strip the repo of the versions with the wrong license. Thanks!

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-66)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-05
┆Epic: Trusted Crypto

**Comment by thomcc** [comment]
It's probably not a big deal for us to relicense under ISC, but IIUC it's only the API that's the same, and according to [Oracle v. Google](https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.), those aren't copyrightable. (Not that I'm a lawyer, of course)

**Comment by thomcc** [comment]
@briansmith We just landed the changes for this (we were waiting to hear your approval).

Let us know if you'd like changes on any of the points I listed in https://github.com/mozilla/application-services/pull/1075#issue-273202999.

I'll close this issue if there's no update in the next week.

**Comment by rfk** [comment]
> strip the repo of the versions with the wrong license

IIUC, this is a request to alter the git history of the repo to remove previous versions in which the code was incorrectly licensed.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

done in the nss PR

**Comment by rfk** [comment]
This code was backed out, and is re-landing in a new implementation with corrected license headers and `ring` attribution notes. Thank you for bringing this to our attention and working through this with us @briansmith.
