### ISSUE TITLE
Expose FFI to reset collections in Places

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#1084]
I'm not sure how important this is, but we used to have the ability to "reset" the Bookmarks collection:

https://github.com/mozilla-mobile/firefox-ios/blob/master/Providers/Profile.swift#L943

**Comment by justindarc** [comment]
It looks like this functionality is already implemented, just not exposed via FFI?:

Bookmarks:
https://github.com/mozilla/application-services/blob/master/components/places/src/bookmark_sync/store.rs#L595

History:
https://github.com/mozilla/application-services/blob/master/components/places/src/history_sync/store.rs#L214

**Comment by thomcc** [comment]
Sounds reasonable.

**Comment by mhammond** [comment]
It looks like this is only used when the DB is recreated, so I'm not sure it applies in this world? (Note that I have no objection to exposing this, but I am trying to work out the use-cases for this and whether they should be better abstracted for/by the "sync manager")

**Comment by justindarc** [comment]
Hmm... good point... it does look like that's the only time we call this and since DB re-creation is out of our hands now, we shouldn't need to manually call this ourselves.

**Comment by justindarc** [comment]
One thing though, we do need to probably call `reset()` manually if the user signs out of their Sync account.

**Comment by thomcc** [comment]
iOS might still need to call this when signing out of sync, or if bookmark sync is disabled. Worth noting that iOS has it's own sync manager that's separate from ours.

**Comment by bug-mirror** [comment]
from mtg: probably need this to ship bookmarks on iOS

**Comment by bug-mirror** [comment]
from mtg: needs to be done by May 3 or earlier
