### ISSUE TITLE
History sync visit timestamp handling is wrong

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1090]
We shouldn't return EARLIEST_TIMESTAMP here, we should discard the visit -- It cannot possibly be valid if it's before this date. https://github.com/mozilla/application-services/blob/da88ddb8109172510bd42a1c08e3f36470d6e43e/components/places/src/history_sync/plan.rs#L40

In all likelihood, the code as-is changes records that have 0 to have a random (to the user) date in 1993.

I think desktop had this right, but was being [rather clever](https://github.com/mozilla/application-services/blob/da88ddb8109172510bd42a1c08e3f36470d6e43e/components/places/src/history_sync/plan.rs#L40) about it, and so when porting it got changed.

**Comment by lyuyuan92** [comment]
I would like to have a try on this one :)

**Comment by lyuyuan92** [comment]
We can close this issue now.

**Comment by thomcc** [comment]
Thanks. BTW if you put `fixes #<issue number>` in the commit message, github should close it for you when it lands. (That said, I don't mind closing them manually).

**Comment by lyuyuan92** [comment]
Ah, thanks for the note! Will do for my PRs in the future.
