### ISSUE TITLE
Add ability to run "live tests" of push code against a local server

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#1094]
It can be useful to run tests against a "live" server, e.g. a version of autopush running either locally or in a docker instance. This would build off the push communications module code that has a "live test" included.

**Comment by jrconlin** [comment]
There's a PR pending https://github.com/mozilla/rust-ece/pull/26.

**Comment by vladikoff** [comment]
(?) related https://github.com/mozilla/application-services/issues/1051

**Comment by jrconlin** [comment]
Huh, didn't know about that one, but yes, they could be. The trick would be setting up the various supporting servers.
