### ISSUE TITLE
Deprecate and remove `org.mozilla.appservices` gradle plugin

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1097]
As discussed in https://github.com/mozilla/application-services/pull/921, the costs of maintaining a custom gradle plugin to manage megazord builds and not outweighing the benefits it provides in practice.  Our plugin is currently locked to an old version of gradle, is preventing use of local substitution builds for development, and we want to [entirely stop supporting non-megazord builds](https://github.com/mozilla/application-services/issues/876) anyway.

Let's push the work that's done by this plugin out to the edges, requiring each consuming project to specify appropriate dependency-substitution rules if it wants to consume a megazord build. This will temporarily increase complexity and code duplication for consumers, but will allow them to manage their own gradle workflows without blocking on updates to our plugin, and will provide a clearer path forward for the work in https://github.com/mozilla/application-services/issues/876.

Thanks to @ncalexan and @vladikoff we have the following PRs to consuming apps already:

* https://github.com/mozilla-mobile/fenix/pull/1787
* https://github.com/mozilla-mobile/reference-browser/pull/733
* https://github.com/mozilla-lockbox/lockbox-android/pull/640

Are there any other places where we need to update our android consumers?

We'll need to do the following in this repo:

* [ ] Delete the plugin code and remove it from publishing config
* [ ] Update documentation to describe the new way to consume megazord builds

Are there other things we need to do in our own repo here before removing it?

**Comment by rfk** [comment]
Assigning myself, I'm working on this as an opportunity to understand substitution build workflows more deeply.

**Comment by thomcc** [comment]
I do this in my WIP in #1103, FWIW.

**Comment by rfk** [comment]
> I do this in my WIP in #1103

Awesome. While investigating this I found myself needing *at least* the "nss-android-libs" sub-package from that PR in order to get things working cleanly with composite builds.

**Comment by rfk** [comment]
@thomcc how much work remains on #1103? Our original plan here was to remove the existing uses of the megazording plugin independently of landing #1103, but given things like nss dependency management, I'm wondering if we should just push through with #1103 and then make a single PR to update each of our consumers to the new world. Thoughts?

**Comment by thomcc** [comment]
It doesn't bother me at all to remove the plugin separately from #1103. There's probably about a week left of work to go, probably less.
