### ISSUE TITLE
Consider "dependabot" for keeping rust dependencies up to date?

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1105]
https://dependabot.com/rust/

This is mentioned in https://github.com/mozilla-services/websec-check/blob/master/rust.md, is it worth trying out?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-68)
┆Story Points: 3

**Comment by thomcc** [comment]
Cautiously, I'm in favor of this for Rust code.

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/57658446-f793e400-75ac-11e9-899c-0d70455ccd24.png)

Ran the thing!

**Comment by vladikoff** [comment]
@thomcc so i enabled it for a bit and it made these: https://github.com/mozilla/application-services/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+bump+from

TaskCluster didn't run for it, but we can keep an eye on what failed or passed

**Comment by rfk** [comment]
I'm impressed that it seems to have done the right thing for the various components within the workspace. It's also generating signed commits, so we can merge at the click of a button. 👍

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

We use it now!
