### ISSUE TITLE
Add support for entrypoint_experiment and entrypoint_variation params

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1106]
Documentation for these was introduced in https://github.com/mozilla/application-services/pull/1009, and they may be required for proper metrics tracking of any experiments related the onboarding, membership, etc.  We should add support for easily passing these through from the application into the various FxA entrypoint URLs.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-69)

**Comment by vladikoff** [comment]
Closing until this is needed
