### ISSUE TITLE
Fenix megazord .so contains debug symbols

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1107]
It doesn't look like our published `.so` files are successfully getting stripped:

```
> VERSION="0.27.1" 
> wget -q https://maven.mozilla.org/maven2/org/mozilla/appservices/fenix-megazord/$VERSION/fenix-megazord-$VERSION.aar > /dev/null
> unzip -q ./fenix-megazord-$VERSION.aar
> du -hs ./jni/arm64-v8a/libfenix.so
39M     ./jni/arm64-v8a/libfenix.so
> 
> ~/.opt/ndk-standalone-toolchains/arm64-21/bin/aarch64-linux-android-strip ./jni/arm64-v8a/libfenix.so
> du -hs ./jni/arm64-v8a/libfenix.so
6.4M    ./jni/arm64-v8a/libfenix.so
```

**Comment by rfk** [comment]
Ref https://github.com/mozilla/application-services/pull/915 where we intended to strip them by default.

**Comment by thomcc** [comment]
Local publishing does strip them for me, so this must be something wrong in CI somehow.

**Comment by thomcc** [comment]
Again, it's worth noting that the intended place to strip these is in fenix, IIRC. It might be worth fixing it there as well as a stopgap.

**Comment by rfk** [comment]
There's a note in a recent Fenix update slidedeck that attributes unacceptable apk size increase to the app-services components:

  https://docs.google.com/presentation/d/1WfVBWleZbHSClx9DPS_ueTnuvyCGnTzdOO1tBp3FJiY/edit?ts=5cd08659#slide=id.g551ea1d6d0_0_80

It also says "app services team confirmed it should shrink over time", so we should make sure it actually does so before the feature-freeze :-)

**Comment by rfk** [comment]
> Local publishing does strip them for me

This is not the case for me FWIW, doing this:

```
> rm -rf ~/.m2/ ; ./gradlew clean ; ./gradlew fenix-megazord:publishToMavenLocal
```

Produces an unstripped .apk:

```
> unzip -q ~/.m2/repository/org/mozilla/appservices/fenix-megazord/0.27.1/fenix-megazord-0.27.1.aar
> file jni/x86/libfenix.so 
jni/x86/libfenix.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, with debug_info, not stripped
> du -hs jni/x86/libfenix.so
33M     jni/x86/libfenix.so
```

**Comment by thomcc** [comment]
I just double-checked and it's definitely stripped for me, so this might be platform (or local configuration) specific?

```
$ unzip -q ~/.m2/repository/org/mozilla/appservices/fenix-megazord/0.27.1-thom00/fenix-megazord-0.27.1-thom00.aar
$ file jni/x86/libfenix.so
jni/x86/libfenix.so: ELF 32-bit LSB shared object Intel 80386, version 1 (SYSV), dynamically linked, stripped
$ du -hs jni/x86/libfenix.so
6.9M	jni/x86/libfenix.so
```

Genuinely unsure of why it wouldn't be stripped everywhere too.

**Comment by thomcc** [comment]
https://issuetracker.google.com/issues/72752164 indicates that this might be a bug in some versions of gradle. I'm on 4.10.2, but I do remember going through some process to update it at one point.

**Comment by rfk** [comment]
Thanks to some collaborative debugging in slack, this appears to be caused by missing `$ANDROID_NDK_HOME` environment variable. Doing `export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT` produces stripped builds for me.  I'll see about updating our docs and scripts to set this automatically.
