### ISSUE TITLE
Server error when checking for sent tabs with an invalid oauth token

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1126]
Ref https://github.com/mozilla/fxa/issues/1060

**Comment by rfk** [comment]
Ref https://github.com/mozilla/fxa-private/issues/18

**Comment by jdragojevic** [comment]
needs verification.

**Comment by rfk** [comment]
AFAICT this has been fixed with the latest FxA deploy, @grigoryk please confirm from your side whenever you have a chance (I know you're super busy this week so no rush)
