### ISSUE TITLE
Add Places API to get 'Recently Bookmarked'

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#1129]
In the "Library > Bookmarks" on desktop, there's a list of "Recently Bookmarked". We would like to have an API to get an equivalent of this list on iOS.

**Comment by jdragojevic** [comment]
@justindarc what is your priority level on this? Putting in backlog until we hear back.

**Comment by justindarc** [comment]
This is planned now for v18. So, we'll need it probably by the end of June at the latest. Thanks!
