### ISSUE TITLE
Investigate using Fretboard for switching features on and off in Fenix

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1130]
## Fretboard: An Android framework for segmenting users in order to run A/B tests and rollout features gradually.

Ref: https://github.com/mozilla-mobile/android-components/blob/master/components/service/fretboard/README.md

Example: https://github.com/mozilla-mobile/focus-android/blob/30d8a20ff21bc1341a8ac9023e74bcc54b567dc8/app/src/main/java/org/mozilla/focus/utils/Experiments.kt#L23-L24

https://github.com/mozilla-mobile/focus-android/blob/3d7ef67115632378cf9f2115e2812eaed4237323/app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt#L25

Existing settings collection: https://bugzilla.mozilla.org/show_bug.cgi?id=1523395

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-52)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

This was investigated and implemented to enable us to pref off sync in Fenix if needed.  Closing.

**Comment by cse-test-sync** [comment]
Transition made by Unito

**Comment by vladikoff** [comment]
oof
