### ISSUE TITLE
Add a method for signing out, which destroys the refresh token

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1139]
In #746 we added `fxa_device_destroy(device_id)` which can be used to delete a device record.  In order to use this, the consuming app needs to know about devices and to know its own device id.  That's overkill for some of our consumers, like Lockwise, which just want a simple "I'm signing out now, destroy my auth tokens" call.

Let's add a method like `signout()` or similar, that doesn't require the caller to know anything about devices, for Lockwise to call when the user signs out of the app.  Internally it can call `device_destroy` if it has a device record or just destroy the refresh token if it does not.

/cc @linuxwolf @sashei

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-50)
┆Story Points: 5
┆Sprint: SYNC - 2019-07-19
┆Epic: Lockwise Support

**Comment by rfk** [comment]
IIUC, to sign out properly right now, Lockwise would have to do something like:

```
for device in fxa.getDevices():
    if device.isCurrentDevice:
        fxa.destroyDevice(device.id)
        break
```

Which feels like way too much work for such an operation.

**Comment by linuxwolf** [comment]
I would be ideal (and probably safer on Lockwise's side) to have a single call (e.g., `signout()`).  However, this might be at least approachable.  Would invalidating the `refresh_token` also invalidate the `access_token`(s)?

**Comment by rfk** [comment]
> Would invalidating the refresh_token also invalidate the access_token(s)?

Currently not, no, but we should fix that: https://github.com/mozilla/fxa/issues/1249

**Comment by rfk** [comment]
> Let's add a method like `signout()` or similar

I'm currently liking the name `disconnect()` for this sort of thing, but I tend to go in phases and have never really settled on one I really like. So let's not block on picking a perfect name here.

@linacambridge in broad strokes, this method will need to:

* Use `get_current_device()` to determine whether the `FirefoxAccount` instance has a device record.
* If so, call `destroy_device()` with its own device id.
* If not, call `destroy_oauth_token()` with its current refresh token (obtained via `get_refresh_token()`)

Then of course we have the usual dance of exposing the new method over the FFI to Kotlin and Swift.

It would be nice if we could just call `destroy_oauth_token()` and have the server clean up the device record automatically, but we don't have that right now, and branching to handle that on the client doesn't seem too bad.
