### ISSUE TITLE
Handle invalid login timestamps

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#1140]
https://bugzilla.mozilla.org/show_bug.cgi?id=1551880 has an example of a login record with a timestamp of `18446732429235952000`, which is outside the range of an `i64`, so Serde is failing with an error.

@thomcc worked around this for Android in https://bugzilla.mozilla.org/show_bug.cgi?id=1404044, by patching the parser to treat oversize dates as doubles. I guess we could do the same here, and treat them as `f64`? Though we should probably ensure we clamp them either way, when we store them.

We've seen that suspicious number in https://bugzilla.mozilla.org/show_bug.cgi?id=1240278. It's likely those logins come from Chrome, which uses an [interesting](https://searchfox.org/mozilla-central/rev/11cfa0462a6b5d8c5e2111b8cfddcf78098f0141/browser/components/migration/ChromeMigrationUtils.jsm#277-288) format for timestamps.

**Comment by thomcc** [comment]
Probably just treating it as a u64 coming in would be better, since the value fits in that.
