### ISSUE TITLE
Add info about dependency license text to our consumer docs

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1141]
@thomcc did some work to generate a list of license info for our various dependencies, so that it can be included in the "about:license" equivalent on Firefox for iOS. We should write this down and put it somewhere prominent so that other consumers of our library know that it's a thing they can and should do in their own product.  @thomcc thoughts? Could you please link to the work you did for iOS as a starting point?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-49)
┆Story Points: 3
┆Sprint: SYNC - 2019-08-16
┆Epic: [Q3 2.4] Fenix 2.0 Support

**Comment by rfk** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1548663

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

waiting for other PRs to be rebased
