### ISSUE TITLE
Rename gradle projects to play nice with composite builds

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1142]
According to [the docs on composite builds](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions), when you include a build via the default syntax like this:

```
includeBuild('../application-services')
```

Then gradle will automatically inspect the projects in the build and set up dependency substitutions for any dependencies matching `${project.group}:${project.name}`.

This doesn't work well for the application-services repo, because our gradle project names don't map to the names of our published artifacts.  Instead, consumers who want to use us in a composite build need to explicitly declare each dependency substitution, [like this](https://github.com/mozilla-mobile/android-components/blob/master/settings.gradle#L67):

```
includeBuild(appServicesLocalPath) {
    dependencySubstitution {
        substitute module('org.mozilla.appservices:fxaclient') with project(':fxa-client-library')
        substitute module('org.mozilla.appservices:logins') with project(':logins-library')
        substitute module('org.mozilla.appservices:places') with project(':places-library')
        substitute module('org.mozilla.appservices:rustlog') with project(':rustlog-library')
    }
}
```

Naively, this seems like an unnecessary maintenance burden on our consumers. I wonder if we could simplify this by renaming our projects to let gradle's default substitution behaviour do the right thing.

This shouldn't be done until after https://github.com/mozilla/application-services/issues/876 and may interact with https://github.com/mozilla/application-services/issues/562, but I wanted to get it on file based on my explorations so far.

Something for us to consider when we next revisit doing composite builds with fenix, a-c and a-s. /cc @grigoryk, who has tried out composite builds in the past from the consumer side.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-48)
┆Story Points: 8

**Comment by eoger** [comment]
@thomcc is this bug still relevant with the new megazord work?

**Comment by rfk** [comment]
Thom did this as part of the megazord work, and AFAICT it's working as intended. Closing.
