### ISSUE TITLE
[Meta] Pairing UX Improvements from UR Observations

### ISSUE THREAD

**Issue by davismtl** [mozilla/application-services#1143]
We just completed interviews with 11 users who have all gone through our device pairing flow. Unfortunately only 3/11 completed the pairing flow without any help. The good news is that the changes we need to make are really minor.

1) On Fenix, nobody selects pairing to sign in. Everyone goes to Sign In by default because it's what we instinctively look for to sign in. Pairing should be an option after selecting Sign In. (and maybe we can explain it with an image)

2) Users quickly click to open the camera without reading to open the URL on desktop. They just look at the QR scanner confused. If we can indicate in the QR scanner where they are suppose to scan, that would resolve 90% of problems.

3) (not as frequent) Users are confused by the camera permission since they don't know why it's needed. Perhaps we can prime them on the previous screen. Some would normally not give permission.

4) Users try to align the QR code within the box in the scanner but often, it's too close to the screen. Make the box in the scanner smaller so that it gets people to be about 30 cm away from the screen. https://github.com/mozilla-mobile/fenix/issues/2565

5) Many users are confused by which device they need to confirm first after they scanned the code. They are scared to make a wrong choice. Maybe we create a false order? Do we still believe we need double confirmation?

@ryanfeeley

Slides 67-72 are results of the UR around device pairing (moco confidential):
https://docs.google.com/presentation/d/10PVQzp5Fwxt5MN3Z6hEHbqVbp7M7dI6awFBlYB_-01A/edit#slide=id.g5acdebc2b9_0_17

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-47)
┆Epic: Fenix 2.0 Support

**Comment by jdragojevic** [comment]
@davismtl  - should we attempt to address some or all of this prior to MVP code freeze (June 14), would love to have a sense or priority.

**Comment by davismtl** [comment]
6. On the desktop, we have a big blue button to manage devices after pairing. Users are clicking on it thinking it's another step and then are confused when they get to device management. Perhaps we get them to start browsing.

**Comment by davismtl** [comment]
@jdragojevic I think that 1,2,4 are things we should try to address before MVP.

Those were frequently blockers. The others were not particularly blockers.

**Comment by vladikoff** [comment]
> Users try to align the QR code within the box

We can look at # 4 with the a-c team,  does everything else need new UX?

**Comment by davismtl** [comment]
@vladikoff 
#1 would likely need some UX. 
#2 can probably be done without UX. Something there is better than nothing. Perhaps we can just make the URL SUPER OBVIOUS before they open the QR code scanner.

**Comment by ryanfeeley** [comment]
> On Fenix, nobody selects pairing to sign in. Everyone goes to Sign In by default because it's what we instinctively look for to sign in. Pairing should be an option after selecting Sign In. (and maybe we can explain it with an image)

But pairing is an option after selecting sign in (now Turn on Sync)

<img width="399" alt="image" src="https://user-images.githubusercontent.com/68213/58124555-840d5a80-7bdc-11e9-8afb-e868b5992470.png">

Are you proposing adding an extra step after here?

<img width="398" alt="image" src="https://user-images.githubusercontent.com/68213/58124579-98e9ee00-7bdc-11e9-97aa-6c1cc8a13cd0.png">

Something like:
1. Enter login manually
2. Scan pairing code in Firefox desktop

**Comment by ryanfeeley** [comment]
> Users quickly click to open the camera without reading to open the URL on desktop. They just look at the QR scanner confused. If we can indicate in the QR scanner where they are suppose to scan, that would resolve 90% of problems.

We should redesign this as a full screen interstitial and not as a dialog. Agreed this is a tough one (but typically in a pairing situation users would start from desktop, not mobile).

**Comment by ryanfeeley** [comment]
> (not as frequent) Users are confused by the camera permission since they don't know why it's needed. Perhaps we can prime them on the previous screen.

Button on previous step says *Open Camera*. It could say *Allow Camera* to better prime them, but the main thing we want them to do on this screen is go to firefox.com/pair, so I wouldn't want to detract. Will have to think about it.

**Comment by ryanfeeley** [comment]
> Users try to align the QR code within the box in the scanner but a majority of the time, it's too close to the screen. Make the box in the scanner smaller so that it gets people to be about 30 cm away from the screen. mozilla-mobile/fenix#2565

I don't understand why this is happening hence I finally filed the bug.

**Comment by ryanfeeley** [comment]
> Users are confused by which device they need to confirm first after they scanned the code. They are scared to make a wrong choice. Maybe we create a false order? Do we still believe we need double confirmation?

I still question that we need to approve on mobile at all as the user has initiated the QR Code scanning from there. Were the screens auto-advancing properly?

**Comment by davismtl** [comment]
> But pairing is an option after selecting sign in (now Turn on Sync)

After clicking on that, folks have 2 options:
- Scan pairing code in desktop Firefox
- Sign in

Everyone picks `Sign in`. I think it's because nobody understands `Scan pairing code...`. They pick what is familiar to them. When we get them to use pairing, they are delighted and love it. They just would have never picked it on their own. How do we get them to pick it or how do adjust our flow to keep in account that most will pick `Sign in` first?

**Comment by rfk** [comment]
> Everyone picks `Sign in`.

They might be more hesitant about it if we describe it as "Enter password manually" or similar.

**Comment by ryanfeeley** [comment]
> Everyone picks `Sign in`. I think it's because nobody understands `Scan pairing code...`. They pick what is familiar to them. When we get them to use pairing, they are delighted and love it.

We do put it first, and we do have a great QR code icon on it. Users move in the way that appears to be most efficient to them, and that includes avoiding cognitive obstacles.

I think that in the right context, like if they are signing in on desktop and we show them a QR code when they verify, they would adopt this feature.

That said, if we wanted to get more aggressive for them to try this on mobile, we could try this…

From **Turn on Sync** simply show:
* Sign in
* Create account

And then **Sign in** we offer pairing as the primary with "Log in manually" as the second option. I can mock something up.

**Comment by davismtl** [comment]
> We do put it first, and we do have a great QR code icon on it.

Most people we met in UR didn't know what a QR code was (or called it a bar code or a CVS code). So.. a good QR icon won't mean that much to them.

> I think that in the right context, like if they are signing in on desktop and we show them a QR code when they verify, they would adopt this feature.

I totally agree with this.

> I can mock something up.

Thanks. Let's see what you come up with.

**Comment by davismtl** [comment]
I edited the first post to include a link to slides with a summary of user research around device pairing. (moco confidential)

**Comment by vladikoff** [comment]
@ryanfeeley could we file bugs on what's left to do here ? (we merged the updated design in Fenix, but there might be FxA issues?)
