### ISSUE TITLE
Drop support for non-batching storage servers

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1144]
There's a fair bit of complexity in sync15/src/request.rs to do with handling a storage server that doesn't support batching. While that complexity is local to that file, it does make it difficult to rationalize about - eg, we even try to handle the fact a server might change its mind mid-batch about whether it supports batching and that code path, along with the code paths for non-batching servers are almost certainly never hit for real.

Support for batching is key to data integrity for bookmarks, so we should consider simplifying this file to only support servers that offer the batching responses.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-735)
┆Epic: Sync Ecosystem
┆Sprint: Backlog

**Comment by rfk** [comment]
Big 👍 FWIW
