### ISSUE TITLE
Device is registered with type=DESKTOP, even though type=MOBILE is specified

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1163]
`Mobile` device type is passed into `initializeDevice`, but the current device record I see afterwards say that device is DESKTOP.

cc @eoger @vladikoff

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-43)
┆Story Points: 3
┆Sprint: SYNC - 2019-07-05
┆Epic: Fenix 2.0 Support

**Comment by jdragojevic** [comment]
@grigoryk - is this blocking any current work?

**Comment by grigoryk** [comment]
@jdragojevic it's not, I don't think - but I'm not sure of all the places where we display a device type icon. We probably need to fix this before Fenix gets wider adoption, otherwise we'll create a lot of device instances with a wrong device type. It's likely much easier to fix this bug now than to try and fix existing device records after the fact.

**Comment by grigoryk** [comment]
We display device type icons in Fenix's share dialog.

**Comment by vladikoff** [comment]
@rfk, Hm I looked at this while running FxA `"1.139.1",` and it seems like the problem is still there, even with https://github.com/mozilla/fxa/pull/1552 included. 

![image](https://user-images.githubusercontent.com/128755/60055933-3f7a5080-96ad-11e9-8454-9b84dc0a6e63.png)

It seems like something sets the field to `desktop` no matter what.

**Comment by rfk** [comment]
Vlad and I found this in the client code which seems pretty suspicious:

  https://github.com/mozilla/application-services/blob/26645bca929c82b635653950eee2f368d8171e3a/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/Device.kt#L45

It may be always converting to "DESKTOP" when passing over the FFI boundary.

**Comment by vladikoff** [comment]
<img src=https://user-images.githubusercontent.com/128755/60057092-4905b780-96b1-11e9-8bf5-e9ddb872a60d.jpg width=150 />

**Comment by cse-test-sync** [comment]
Transition made by Unito
