### ISSUE TITLE
Document how to create a "dot release"

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1164]
As products using our components are released, we are almost certainly going to be faced with needing to create a "dot release" from an older version - ie, a release which is not created from current master. We don't want to learn how to do that the first time we are asked, as making the release likely to be somewhat time-critical.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-42)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-05
┆Epic: Fenix 2.0 Support

**Comment by linacambridge** [comment]
Documented in #1348!
