### ISSUE TITLE
Consider optimal sqlite checkpoint strategies

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1172]
We currently set a page size of 32kb, and don't touch the "auto checkpoint" param, meaning sqlite will checkpoint after there are 1000 pages in the WAL. Thus, it seems the WAL may grow to ~32MB before being checkpointed, which could be slow and locks the database.

This doesn't seem ideal. From a slack convo:

* We use the same page size as desktop places (32kb).
* Desktop arranges for the WAL to never exceed 2048000 bytes, meaning it says sqlite should checkpoint after 16 pages ([where this is done](https://searchfox.org/mozilla-central/rev/952521e6164ddffa3f34bc8cfa5a81afc5b859c4/toolkit/components/places/Database.cpp#291-294))

We kinda agreed that we should:

* Arrange for the max pages to match desktop.
* Perform an explicit "PASSIVE" checkpoint after a sync
* Possibly do some kind of checkpoint (either PASSIVE or FULL) when we do db maintenance.

**Comment by thomcc** [comment]
I think whoever does the FULL checkpoint needs to hold the coop_tx_lock, I think, in order to prevent BUSYs on whatever other writer may or may not be around at the time.

(micronit: 2048000 is not 16 times 32768 -- it's 62, since 2048 is 64 times 32)
