### ISSUE TITLE
Generic Sync: Investigate solutions and effort

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1175]
# Generic Sync Storage Schema to support additional synced items

## Description
Ahead of finalizing our Q3 OKRs - we want to have a reasonable understanding of the
1. Technical challenges / Risk
2. The value we are providing to our end-users
3. Agreement from other teams we need to collaborate with to deliver value
4. Very rough estimate of the timeline to deliver to production.

## Acceptance Criteria

- [ ] Peer-reviewed [engineering discovery document](https://docs.google.com/document/d/1CpfoO7fUkK3U9ED2OPZZ9wyZpo7UXPXcC-30oB5sZNE/edit#heading=h.ie9lyqf2sea7) describing technical considerations / challenges 

- [ ] Completed [section on Generic Sync](https://docs.google.com/document/d/1kiwUEZciypbL_MCn0KZ1gBw5VWuYhS9FmincRCo1h08/edit#bookmark=id.wjl32j33pacl) in Roadmap doc.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-86)

**Comment by rfk** [comment]
We're doing remerge, I thinks we can declare this "spike" over.
