### ISSUE TITLE
Push support for PWA in Firefox Preview: investigate solutions and effort

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1176]
# Push support for PWA in Firefox Preview

## Description
Ahead of finalizing our Q3 OKRs - we want to have a reasonable understanding of the
1. Technical challenges / Risk
2. The value we are providing to our end-users
3. Agreement from other teams we need to collaborate with to deliver value
4. Rough estimate of the timeline to deliver to production.

## Acceptance Criteria

- [ ] Peer-reviewed engineering discovery document describing technical considerations / challenges 

- [ ] Completed [section on Push Support for PWA in Firefox Preview](https://docs.google.com/document/d/1kiwUEZciypbL_MCn0KZ1gBw5VWuYhS9FmincRCo1h08/edit#bookmark=id.gfah2b9dbhqo) in Roadmap doc.

_Note: Good examples of engineering discovery docs are [Sync Manager RFC](https://github.com/mozilla/application-services/blob/sync-manager-rfc/docs/rfcs/sync-manager.md) and [trusted networking doc](https://gist.github.com/thomcc/7b0ffe9010a0e29a2fc014bb60d032ea)_

┆Issue is synchronized with this [Jira Spike](https://jira.allizom.org/browse/SYNC-37)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-19
┆Epic: Planning

**Comment by jrconlin** [comment]
See https://docs.google.com/document/d/1arPAzNzH3FPdC6AWIR9tuCaNm8tS4GeGg4CcsemQf-g/edit?usp=sharing as an initial working document.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

Moving to next sprint!

**Comment by linacambridge** [comment]
See the [GeckoView Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1343678), too.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

from mtg: not on our team. 

Vlad to close this out

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

Other teams working on this

**Comment by linacambridge** [comment]
Here's the [GeckoView Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1343678).
