### ISSUE TITLE
Device Pairing for FireTv: Investigate solutions and effort

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1178]
# Device Pairing for FireTV
## Description
Ahead of finalizing our Q3 OKRs - we want to have a reasonable understanding of the

1. Technical challenges / Risk
1. The value we are providing to our end-users
1. Agreement from other teams we need to collaborate with to deliver value
1. Very rough estimate of the timeline to deliver to production.

## Acceptance Criteria
* [ ] Peer-reviewed engineering discovery document describing technical considerations / challenges.  [Coordination of Device Pairing](https://docs.google.com/document/d/19nejHg0asUEJGTfeBMCw1onfCn_QV3AsgKA7hlnY7os/edit) captures a number of use cases and open questions.  It should either be updated with more details pertaining to FireTV as a specific use case or linked out to a new document.
* [ ] Completed [section on Device Pairing for FireTV](https://docs.google.com/document/d/1kiwUEZciypbL_MCn0KZ1gBw5VWuYhS9FmincRCo1h08/edit#bookmark=id.z9c4pk5ea07e) in Roadmap doc.

┆Issue is synchronized with this [Jira Request](https://jira.mozilla.com/browse/SACI-31)

**Comment by rfk** [comment]
We've deprioritized this project, no need for this spike.
