### ISSUE TITLE
Import some user-data from Fennec to Fenix: Investigate solutions and effort

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1179]
# Import some user-data from Fennec to Fenix
_limited to data that are supported by Application Services Rust Components that are integrated into Fenix_

## Description
Ahead of finalizing our Q3 OKRs - we want to have a reasonable understanding of the
1. Technical challenges / Risk
2. The value we are providing to our end-users
3. Agreement from other teams we need to collaborate with to deliver value
4. Very rough estimate of the timeline to deliver to production.

## Acceptance Criteria

- [ ] Peer-reviewed engineering discovery document describing technical considerations / challenges.  Grisha's original engineering discovery on [Sharing account information](https://docs.google.com/document/d/1BtmeH2X_5G_oNG9bde8PUJKiyC8EC7-18XyeCXZgRL4/edit#) and the application services draft [project plan](https://docs.google.com/document/d/1C9Q8ZGWeFw7iK8lKmL_nd72NlvZpG6NsWSuD3rj0C0w/edit#heading=h.9qtbe4mxitxr) should be updated to detail the work required. 

Other questions to answer include:
 - Should logins data be imported (currently no logins component in Fenix)?
 - Should this be limited to history and bookmarks only?
 - Other types of user-data to consider?

- [ ] Completed [section on Import some user-data from Fennec to Fenix](https://docs.google.com/document/d/1kiwUEZciypbL_MCn0KZ1gBw5VWuYhS9FmincRCo1h08/edit#bookmark=id.xn0n8obvb8ie) in Roadmap doc.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-34)
┆Story Points: 5
┆Sprint: SYNC - 2019-07-19
┆Epic: Planning

**Comment by vladikoff** [comment]
Need to land https://github.com/mozilla/application-services/pull/1018
