### ISSUE TITLE
Push GCP migration (+rust re-write): Investigate solutions and effort

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1182]
# Push GCP migration (+rust re-write of remaining python parts)

## Description
Ahead of finalizing our Q3 OKRs - we want to have a reasonable understanding of the
1. Technical challenges / Risk
2. The value we are providing to our end-users
3. Agreement from other teams we need to collaborate with to deliver value
4. Very rough estimate of the timeline to deliver to production.

## Acceptance Criteria

- [ ] Peer-reviewed engineering discovery document describing technical considerations / challenges 

- [ ] Completed [section on Push GCP migration including rust re-write of remaining python parts](https://docs.google.com/document/d/1kiwUEZciypbL_MCn0KZ1gBw5VWuYhS9FmincRCo1h08/edit#bookmark=id.8uteow7i9vs3) in Roadmap doc.

_Note: Good examples of engineering discovery docs are [Sync Manager RFC](https://github.com/mozilla/application-services/blob/sync-manager-rfc/docs/rfcs/sync-manager.md) and [trusted networking doc](https://gist.github.com/thomcc/7b0ffe9010a0e29a2fc014bb60d032ea)_

**Comment by pjenvey** [comment]
We'll track this elsewhere, currently here: https://github.com/mozilla/application-services/issues/1182
