### ISSUE TITLE
Prevent releases to be retriggered by editing their fields.

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1186]
We didn't hit that bug yet but it'll be good to mirror what android-components has done in https://github.com/mozilla-mobile/android-components/pull/2885.

**Comment by hardik25** [comment]
Hi @eoger, 

I would like to take up this issue. Could you please assign it to me?

**Comment by eoger** [comment]
Hi @hardik25, our policy is to assign issues once a patch has been submitted. Feel free to post a PR :)

**Comment by hardik25** [comment]
@eoger, Have the changes for this PR been merged? If not, I could submit a signed commit now. Sorry it took time for me to set up GPG key. Please let me know. Thanks!

**Comment by eoger** [comment]
Apologies it looks like Mihai beat you to it in https://github.com/mozilla/application-services/commit/ba62704cf61d167ff5cab96e551c337a96551f9d. I'll review your other PR asap!
