### ISSUE TITLE
[fxa-client] add support for 'force_auth'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1196]
see https://github.com/mozilla-mobile/fenix/issues/2833

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-31)
┆Story Points: 5
┆Sprint: SYNC - 2019-07-19
┆Epic: Fenix 2.0 Support

**Comment by jdragojevic** [comment]
@vladikoff Fenix team just downgraded this feature ref:  https://mozilla.slack.com/archives/CG2FGG1ST/p1559248118038300  

Unsure if we should keep same priority or drop back since #3111 Add "force re-auth" option for FxA error state is now a post-MVP change.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

blocked by SYNC-16 , AS-1248
