### ISSUE TITLE
Handle invalid URLs in `bookmarks_get_all_with_url`

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#1198]
See mozilla/firefox-preview-bughunting-campaign#130. Typing `192.168.1.1:1234` into the address bar logs this:

> 05-24 17:16:16.635 30159 30213 E places::ffi: Unexpected sync error: Error(
> 05-24 17:16:16.635 30159 30213 E places::ffi: 
> 05-24 17:16:16.635 30159 30213 E places::ffi: Error synchronizing: URL parse error: relative URL without a base)

And [here's the crash](https://sentry.prod.mozaws.net/operations/fenix/issues/5740155/).  (I think the "error synchronizing" message is because `parse_url` [returns a `sync15::Result`](https://github.com/mozilla/application-services/blob/94ad2d9b387970e921f1f4c87649b275e073539d/components/places/ffi/src/lib.rs#L27-L29). The stack in Sentry points to `getBookmarksWithUrl`).

Could we give `bookmarks_get_all_with_url` the same treatment as `places_get_visited` in #554?

Should we also consider swallowing URL parse errors for `places_delete_{place, visit}`, too? We shouldn't record invalid URLs, but if one somehow sneaks into the database, it would be unfortunate if you couldn't delete it. Desktop is finding this out [the hard way for bookmarks with invalid URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1401401).

**Comment by thomcc** [comment]
We should probably do more work to clean up URLs that are recorded as history too.
