### ISSUE TITLE
Formalize push key serialization format

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1199]
The push component currently stores local private keys to disk using a simple custom serialization format:

  https://github.com/mozilla/application-services/blob/master/components/push/src/crypto.rs#L75

Unfortunately this seems to depend on some specific implementation details of the rust-ece openssl crypto backend, such as the way it exports private keys as just the `d` component. Based on my experiments so far in producing an rc_crypto-backed version of rust-ece, I'm not confident that we'll be able to work with this format easily (or perhaps, at all).

I propose that we:

* Have rust-ece grow a public trait method for serializing/deserializing the (keypair, auth_secret) pairs that consuming applications will need to store to disk.
    * Preferably, have this use a existing standard format for doing such things.
    * Even more preferably if possible, have this be interoperable with the way such things are stored in Firefox desktop.
* Ensure that we can implement this atop NSS as well as OpenSSL before commiting to anything concrete.

**Comment by rfk** [comment]
Putting ship-ready on this for now, because we should have a story for how we'll handle forward migration of this data before it goes to general release.

**Comment by rfk** [comment]
AFAICT Firefox serializes the public key as raw bytes and the private key as a JWK:

  https://dxr.mozilla.org/mozilla-central/source/dom/push/PushCrypto.jsm#579

We have all the bits to do that already in `rc_crypto`, so it seems like a good path forward. Unless we have a specific need for a more compact format, @jrconlin?

**Comment by linacambridge** [comment]
> AFAICT Firefox serializes the public key as raw bytes and the private key as a JWK...

Ironically, we use JWK to work around [limitations](https://bugzilla.mozilla.org/show_bug.cgi?id=1048931) [in](https://bugzilla.mozilla.org/show_bug.cgi?id=1159216) [NSS](https://bugzilla.mozilla.org/show_bug.cgi?id=1245252), which, IIUC, can't import or export raw private keys, and can't compute a public key from a private key. OpenSSL can do both.

**Comment by rfk** [comment]
> IIUC, can't import or export raw private keys, and can't compute a public key from a private key.

Thanks, that would explain why I wasn't able to figure out how to do it :-)

**Comment by rfk** [comment]
> can't compute a public key from just a private key

This is the real blocker; I wouldn't be too sad to have to do a bit of format conversion, but I'll draw the line at doing raw elliptic curve operations! 😱

**Comment by rfk** [comment]
@eoger has been digging into the details of this, assigning to him.

**Comment by jrconlin** [comment]
From what I've been able to work out with DER key storage, the full private key consists as the `d` private, along with the `x`,`y` key-pair using delightfully annoying DER formatting. As @linacambridge points out, OpenSSL is better about derivation than NSS is and thus can just use the `d` value. 

I'm absolutely fine with having a better version of key storage in whatever format. That's why there's a version iterator built into the storage sequence. I'd probably prefer using something a bit more terse than JSON, or at least not base64 it needlessly, (Protobuf?) but I'm perfectly fine being overridden as well.

**Comment by rfk** [comment]
Martin suggests we take a look at https://dxr.mozilla.org/mozilla-central/rev/5cc220ddf028de011a922042ee9ba691b94d055d/security/nss/lib/pk11wrap/pk11akey.c#1792
