### ISSUE TITLE
[logins] Expose local metadata directly to consumers

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#120]
The initial logins landing goes to a great deal of effort to splice local metadata into Sync 1.5 password records uploaded to the service.  However, because [Bug 555755](https://bugzilla.mozilla.org/show_bug.cgi?id=555755) is still open, uploading local metadata changes to the service might actually be _bad_ for a client that really wants to use the metadata changes!  With logins based on Mentat, however, we're explicitly modeling the local metadata as local usage events.  We already expose metadata about individual records: see https://github.com/mozilla/application-services/blob/e36a772b46ab13d4ba72c879a7823ac921b478e4/logins/src/credentials.rs#L20.  This ticket tracks exposing local metadata about the collection as a whole directly to consumers -- say, finding the 10 most recent locally-used credentials; or the most frequently locally-used credential.

**Comment by rfk** [comment]
From meeting: we're happy with the current API for now, let's re-open as a new issue if lockbox have a concrete ask
