### ISSUE TITLE
Add integration test to the Pull Request requirements list

### ISSUE THREAD

**Issue by lyuyuan92** [mozilla/application-services#1200]
Provide basic introduction on how to run sync integration test (install Node and run with `cargo run -p sync-test`). Add integration test in [this list](https://github.com/mozilla/application-services/blob/master/docs/contributing.md#sending-pull-requests).

**Comment by thomcc** [comment]
Good idea. Might be worth mentioning the android and swift tests as well, but just covering the integration tests would be a good start.

**Comment by lyuyuan92** [comment]
Cool, I will add this today.
