### ISSUE TITLE
Sign artifacts and send detached signatures to Maven

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/application-services#1203]
[Parent bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1548545)

* Enable staging releases for testing
* When sending artifacts to Maven, create a detached signature (`.asc`) for each artifact (`.pom`, `.aar`, `.jar`) and upload these files together

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-29)

**Comment by mitchhentges** [comment]
I'll be working on this, feel free to assign it to me

**Comment by eoger** [comment]
Thanks for mirroring this ticke Mitchell, let me know if I can assist you in any way.
