### ISSUE TITLE
Allow deleting places/visits/bookmarks with invalid URLs

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1206]
From https://github.com/mozilla/application-services/issues/1198

> Should we also consider swallowing URL parse errors for `places_delete_{place, visit}`, too? We shouldn't record invalid URLs, but if one somehow sneaks into the database, it would be unfortunate if you couldn't delete it. Desktop is finding this out the hard way for bookmarks with invalid URLs.

**Comment by lyuyuan92** [comment]
I will have a try on this one.

**Comment by lyuyuan92** [comment]
I guess this issue can be closed now.

**Comment by thomcc** [comment]
Thanks!
