### ISSUE TITLE
Question: Do we dependency lock clippy and fmt versions?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1210]
Looking at the CI script, do we always install the most recent version of fmt and clippy?

Comparing to ESLint or w/e in JS world this is a bit strange and leads to failing PRs. Should we lock it or leave it like that?

**Comment by thomcc** [comment]
We do, but those are bumped in lock-step with the rustc version (And I'm not sure if running an older clippy with a newer rustc is even supported). We'd probably want to freeze rustc version at the same time if we want to do this.

**Comment by rfk** [comment]
> We'd probably want to freeze rustc version at the same time if we want to do this.

To achieve this, would it suffice for us to set an explicit version number in these two files?

* https://github.com/mozilla/application-services/blob/master/.circleci/config.yml#L64
* https://github.com/mozilla/application-services/blob/master/automation/taskcluster/decision_task.py#L278

**Comment by thomcc** [comment]
Yes. I don't really think we should, though.

Worth noting that we currently test against both stable and beta.
