### ISSUE TITLE
Implement throttling of apps which request very frequent syncs.

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1216]
The sync manager needs to honor backoff requests from any of the servers, and also to throttle apps which requests very frequent syncing

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-91)

**Comment by thomcc** [comment]
We honor backoff and retry-after now (which is the important part of this), but don't implement throttling on our end. It's unclear what the desired rate for that would be, but it would be relatively easy to add if we can come up with one. Marking as backlog and changing the title to indicate this.
