### ISSUE TITLE
Implement the high-level sync manager

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1217]
We need a single entry-point which is called by apps and which syncs all engines known by that app

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-26)
┆Story Points: 13
┆Sprint: SYNC - 2019-07-19
┆Epic: Sync Manager // CWTS

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

adding Thom, Lina?
