### ISSUE TITLE
More lenient treatment of invalid URLs in places

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1222]
This seems like a common theme.

Relevant Sentry reports via Fenix:
- `InternalPanic - Invalid URL in Places: InvalidPort` https://sentry.prod.mozaws.net/operations/fenix/issues/5499719/?query=is:unresolved%20places
- `InternalPanic - Malformed suggested URL: EmptyHost` - https://sentry.prod.mozaws.net/operations/fenix/issues/5831528/?query=is:unresolved%20places
- `UrlParseFailed - Error parsing URL: invalid international domain name` - https://sentry.prod.mozaws.net/operations/fenix/issues/5861739/?query=is:unresolved%20places
- `PlacesException - Error synchronizing: URL parse error: invalid IPv6 address` - https://sentry.prod.mozaws.net/operations/fenix/issues/5762369/?query=is:unresolved%20places
  - this one is weird, stacktrace indicates that we're failing at `getBookmarksWithURL`, so why "error synchronizing"?
- `PlacesException - Error synchronizing: URL parse error: invalid port number` - https://sentry.prod.mozaws.net/operations/fenix/issues/5768250/?query=is:unresolved%20places
  - same as above; we're hitting this via `getBookmarksWithURL`.

**Comment by grigoryk** [comment]
Some of these (originating from `noteObservation` calls) will be handled at the a-c level: https://github.com/mozilla-mobile/android-components/issues/3195

cc @thomcc to look into `InternalPanic`s.

**Comment by grigoryk** [comment]
Update: mozilla-mobile/android-components#3195 landed, so we should not be crashing with UrlParseFailed anymore once that makes its way into Fenix.

**Comment by thomcc** [comment]
We've also landed #1227 and (probably) soon will land #1232, which should help us be more robust here in the next release.

**Comment by linacambridge** [comment]
#1205 also fixes `getBookmarksWithURL`. The "error synchronizing" message is because we return a `sync15::Result` (see #1198).

**Comment by mhammond** [comment]
> closed this in [ #1232 ](/mozilla/application-services/pull/1232) [4 hours ago](#event-2389924565)

Oops - it wasn't my intent that this would be automagically closed, but I think that ended up OK and it really should be closed - but please reopen if that's not true.
