### ISSUE TITLE
PlacesConnectionBusy crash

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1230]
https://sentry.prod.mozaws.net/operations/fenix/issues/5815037/?query=is:unresolved%20ac.as.build_version:0.29.0%20PlacesConnectionBusy

possible fixed in a-s 0.30.0

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-23)
┆Story Points: 5
┆Epic: [Q3 2.4] Fenix 2.0 Support

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

upgrading estimate to 5

**Comment by kbrosnan** [comment]
Looks like this can be closed. The crash has been resolved.

**Comment by jdragojevic** [comment]
closing based on above comment.
