### ISSUE TITLE
Consider publishing through the Apple Swift Package Manager

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1233]
Looks like it supports iOS now: https://github.com/apple/swift-package-manager/commit/24ab169de5be5743c083b4ea0593f14cebbc6024.
Let's see if our upstream projects such as firefox-ios and lockbox-ios are interested first before making a decision.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-21)

**Comment by garvankeeley** [comment]
Not interested yet on Firefox iOS, because I don't see the advantages over Carthage (yet).

**Comment by sashei** [comment]
Low interest on lockwise as well. We're happy with Carthage.

**Comment by cse-test-sync** [comment]
➤ Edouard Oger commented:

Won't do for now as it doesn't provide us much.
