### ISSUE TITLE
[swift] Surface `getDevices` on Swift `FirefoxAccount` implementation

### ISSUE THREAD

**Issue by sashei** [mozilla/application-services#1234]
Currently, there is no `getDevices` method on the Swift `a-s` implementation. We would like to use this method to unregister disconnecting devices in the meantime while https://github.com/mozilla/application-services/issues/1139 is being completed.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-20)
┆Epic: Lockwise Support

**Comment by thomcc** [comment]
This is desired on android as well.

**Comment by sashei** [comment]
@thomcc I believe it's not present in a-c, but is in the Kotlin FFI on a-s

**Comment by thomcc** [comment]
It's present, just on the `FxaDeviceConstellation` type, so it's a bit indirect. You can access it via `fxa.deviceConstellation().fetchAllDevicesAsync()`.

This is a bit strange, but does bottom out to the getDevices call: https://github.com/mozilla-mobile/android-components/blob/53323b694be6625461ac2464584be149bf3bcdb1/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt#L126

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

Needs SYNC-50

**Comment by eoger** [comment]
`disconnect` added in https://github.com/mozilla/application-services/pull/1414.
