### ISSUE TITLE
Cached OAuth tokens can caues Auth errors even after signing back in

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1236]
If the application gets disconnected from Sync and does a re-authentication flow, it might still end up using cached OAuth access tokens that have been revoked on the server. From @grigoryk and @eoger on slack:

```
grisha [07:26]
i'm updating fenix accounts ui, and going through different flows right now
i'm seeing 401s while fetching a profile _after_ re-authenticating (after changing the password)
(sync etc works)
hmmm, but the problem goes away on restart. interesting

right after `fxa_complete_oauth_flow`, seeing this:
Untitled 

   fxa_client::oauth W Error while getting previous device information: Error(
             W Remote server error: '401' '110' 'Unauthorized' 'Invalid authentication token in request signature' 'https://github.co
              m/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format')
             W Refresh token destruction failure: Error(
             W Remote server error: '400' '108' 'Bad Request' 'Invalid token' 'https://github.com/mozilla/fxa-oauth-server/blob/maste

@eoger what appears to happen is that when going through re-authentication flow, at some point an old token is being used, which triggers a 401 and gets the a-c state machine back into a "need to re-auth" state
i don't see this while logging in normally
...
...
eoger [08:03]
So I believe the OAuth memory cache is at fault here
Thinking about this more I can see a lot more cases where it might be returning bad tokens, and the app in-correctly re-triggering a flow without any possibility to "clear" these cached tokens
Getting rid of the OAuth token cache completely would make this simpler, as a 401 would definitely mean "you need to reconnect, your refresh token is faulty"
```

There are a couple of problems with the management of this cache:

* Anything that changes the login state should clear the cache (specifically `complete_oauth_flow` in this case).
* There's no way for the app to clear tokens from the cache if it knows they're bad, so IIUC things like this can happen:
  * The app calls `getAccessToken` to get an access token
  * We return a token from the cache
  * The app tries to use the token, gets a 401, and calls `getAccessToken` to get a new one
  * We return the same token from the cache again
  * And so on...

There are a couple of ways to fix the later. We could add an "ignore cache" argument or `getFreshAccessToken` method that allows the app to flag that the cached one was bad. Or we could have an explicit `onInvalidAccessToken` method that the app can call when it discovers an access token has expired.  @grigoryk we'll probably need guidance from you on what approach would work best with the consuming application and its state-machine.

**Comment by rfk** [comment]
Higher-level, I think we need to clarify in the consumer docs:

* What the app should do if it gets an Authorization error when using a token returned by `getAccessToken`.  (Some sort of "request a fresh access token and try again", details TDB).
* What the app should do if it gets an Authorization error when taking the above action (enter your "needs re-auth state").

> We could add an "ignore cache" argument or getFreshAccessToken method that allows the app
> to flag that the cached one was bad.

Alternately, we could have the app pass in the previous token it was using with that scope, as a signal that said token has gone bad and we should investigate.

@eoger I've tried to capture my understanding from the slack conversation, but are there other concerns around the behavior of this cache that aren't represented above?

**Comment by rfk** [comment]
From slack conversation, I think we have a couple of short-term fixes we can do to improve the situation here:

1. Clear the cache when beginning a new auth flow, and again when completing it, to be doubly sure.
2. Provide a mechanism for [the a-c onAuthError callback](https://github.com/mozilla-mobile/android-components/blob/master/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt#L52-L60) to clear cached OAuth tokens
3. Try to ensure that auth errors during sync propagate up to the above callback (perhaps even at the cost of some false-positives due to other sync-related errors).

Seems like (1) is on us here in this repo, (2) is a joint effort with @grigoryk, and (3) is largely on the a-c side.

Does the above seem like it will get us into a good place as a first step?

**Comment by rfk** [comment]
Furthering my role as slack scribe, here's the plan in more detail.

On the a-s side:

* Clear the cache when starting or completing an auth flow.
* Add a method `FirefoxAccount.onAccessTokenError()` that can be called when the app tries to use an access token but fails. For bonus points this could take optional `token` and `error` arguments, but I don't think it matters short term and we wouldn't do anything different based on those arguments at this stage.
  * Internally, this method clears the token cache.
  * I wonder it there are any threading issue to be aware of here, we probably don't want to end up with the app trying to call this reentrantly while doing something else on the account...
* In places where we use access tokens for our own purposes, add more considered handling of auth errors:
  * Call the `onAccessTokenError` method ourselves if we discover one
  * Automatically retry once in the face of auth errors

On the a-c side:

* Plumb the existing `onAuthError` notification into the `onAccessTokenError` method.
* Investigate what it would take to call the above in some cases cases on sync failure.

**Comment by rfk** [comment]
/cc @sashei, I wonder if this could be contributing to the mysterious sync errors on Lockwise, such as https://github.com/mozilla/application-services/issues/1235.  The app getting into a loop of requesting the same invalid access token over and over again seems like it could certain appear to the user as a sync that never ends.

Do you have any comment on the proposed API changes above from Lockwise perspective?

**Comment by linuxwolf** [comment]
(Responding obo Lockwise)

I think the overall plan makes sense, but the details (e.g., API names) are confusing to me.  It clearly makes sense to everyone in the discussion, to me a `onAccessTokenError()` strongly implies a callback.  Would a `clearCache()` or `resetCache()` or something be sufficient?

**Comment by rfk** [comment]
> Would a clearCache() or resetCache() or something be sufficient?

It would, I think the motivation of the current naming is basically about not leaking the internal implementation details.

I see what you mean about it sounding like a callback; happy to bikeshed other names here such as `reportInvalidAccessToken` if that would make it clearer?

**Comment by eoger** [comment]
I agree leaking the internal details isn't great, however `clearCache` gives a clear indication that you can retry whereas `reportInvalidAccessToken` might sound like some telemetry probe that you could probably ignore. I can't seem to find an "actionable while not revealing the implementation" name either, so unless we can come up with something better I'd vote for `*Cache()`.

**Comment by rfk** [comment]
Based on consumer feedback, here's what I propose we do:

* Rename the new method to the very explicit `clearAccessTokenCache`.
* File a followup bug to more explicitly expose a "check whether the user needs to re-auth" operation of the kind suggested in https://github.com/mozilla/application-services/pull/1244/files#r291740678

**Comment by rfk** [comment]
> * File a followup bug to more explicitly expose a "check whether the user needs to re-auth" operation
>  of the kind suggested in https://github.com/mozilla/application-services/pull/1244/files#r291740678

I filed https://github.com/mozilla/application-services/issues/1263 to discuss that in more detail.
