### ISSUE TITLE
Enforce that all our service URLs either use TLS, or are localhost

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1242]
As an extra check against config errors, especially in future self-hosting setups.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-18)
┆Story Points: 2
┆Sprint: SYNC - 2019-07-19

**Comment by jdragojevic** [comment]
do via viaduct

**Comment by thomcc** [comment]
@tinoism messaged me in slack and said she'd like to take this.
