### ISSUE TITLE
Store UID, email from getProfile in persisted state profile object

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1248]
## Store UID, email from getProfile in persisted StateV3(?) profile object

We need to create an optional profile object on the persisted state that stores uid, email, (other profile data?).

Blocks: https://github.com/mozilla/application-services/pull/1204
Also see: https://github.com/mozilla/application-services/issues/483

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-16)
┆Story Points: 5
┆Sprint: SYNC - 2019-07-19
┆Epic: Fenix 2.0 Support

**Comment by vladikoff** [comment]
Draft thoughts: We can later use the uid to call something like `force_auth?uid=blah`, if the `uid` is not available (getProfile was not called by the application) then we throw an error. And expect the app to recover from there

**Comment by rfk** [comment]
It will also allow to prevent the app from accidentally doing silly things, like starting another oauth flow to reauthenticate and coming back as a different user without an intervening `logout()` of some kind.

**Comment by vladikoff** [comment]
Also related: https://github.com/mozilla/application-services/issues/36

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

[~eoger@mozilla.com] could we take a look at this together?

**Comment by eoger** [comment]
I guess we could store a "last seen profile", even if it might be wrong in some cases (e.g. email changed) it would still be useful.
