### ISSUE TITLE
Add "client instance metadata" APIs and expose over FFI

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#125]
We want to add capabilities for:
- Commands / Send Tab
- Display Name
- Push registration and notifications handling

This requires to implement the /device API, however we should learn from our Desktop implementation and try to come up with something that doesn't look like it's been "bolted on".

This issue is to discuss how do we shape that client API to look natural for users, and how do we track all that state inside the crate.

Requires https://github.com/mozilla/application-services/issues/390

**Comment by rfk** [comment]
Discussing plans in this google doc: https://docs.google.com/document/d/1rQrAYuphn_LwTOvSXtLvP6QBZzQEqwgClN8Qf2Zw5CM/

**Comment by rfk** [comment]
This doc describes our plans in more detail: https://docs.google.com/document/d/1pbyOOySw76R-OTPJiX4gW3Izlp-plA7T7Jlt-wOAKwQ/

**Comment by rfk** [comment]
Sharing a bit of progress here, we have basic "client instance" registration working in a dev environment:

  https://github.com/mozilla/fxa-auth-server/pull/2715#issuecomment-437771470

I think we now know enough about how we want this to work, that we can file some finer-grained bugs and deal with them in the upcoming planning meeting.  I'll aim to get them filed tomorrow before the meeting.

**Comment by rfk** [comment]
Closing this in favour of new approach using existing devices api.
