### ISSUE TITLE
Error synchronizing: OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1251]
Android Logs: https://gist.githubusercontent.com/vladikoff/79b55705f4cc94c68cceb93ebbb75192/raw/76848fbbb2cf3cc8208590deddd3dd81d8dc9f95/gistfile1.txt

Desktop logs: https://gist.githubusercontent.com/vladikoff/0315fb3a8995cc692944e2f44c3ae196/raw/8a1df7ca56c9c871164815db79e17ed62852387b/gistfile1.txt

**Comment by vladikoff** [comment]
STR

Login to fenix with one account, sync
sign out, login with another one after that, keep an eye on logcat

**Comment by rfk** [comment]
From slack conversation, we believe this to be related to a cache invalidation issue with the storage node credentials issued by tokenserver.
