### ISSUE TITLE
Lockwise shows "no logins" when there's an unparseable login on the server

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1253]
Based on slack conversation, we *think* this was happening to Ryan Gaddis.  He was able to sign in to the Lockwise app and it would *claim* to sync his logins, but would display "no logins" in the UI even though he actually had plenty of logins stored in his account, and other Firefoxes could see and sync then just fine.

He then deleted his synced logins, and uploaded some fresh ones, and Lockwise is now able to sync and display them.

So IIUC the theory is, there was a corrupt or otherwise unexpected login record on the server somewhere, that existing Firefoxes could parse just fine but that our rust component couldn't. This caused us to fail to sync any logins down locally.

@thomcc does this seem accurate based on slack conversation?

If so, some scoping questions:

* Is it expected that we would fail to sync anything in the face of a single badly-formed record in the collection?
* Would this show up as a "sync failed" erorr that the Lockwise app should be catching and showing special UI for?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-15)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-05
┆Epic: Lockwise Support

**Comment by thomcc** [comment]
> Is it expected that we would fail to sync anything in the face of a single badly-formed record in the collection?

No, but it's possible that code has a bug. There's no test coverage to ensure we behave appropriately here.

> Is it expected that we would fail to sync anything in the face of a single badly-formed record in the collection?

I believe so, but could be mistaken.

**Comment by rfk** [comment]
I think you may have accidentally replied to the same question twice, once with a "no" and once with a "yes" :-)

**Comment by thomcc** [comment]
Uh, fixed 😅

**Comment by cse-test-sync** [comment]
Transition made by Unito
