### ISSUE TITLE
Investigate token-server token caching in Fenix

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1257]
Ive captured logs from my emulator which shows us not caching the token from the token server and fetching it for each sync. However, I can't reproduce it with a hack to places-utils to sync multiple times with the same state.

But I *hope* it does work sometimes, as otherwise we'd have no good answer for #1251

Sadly you need a custom build of Fenix with the following patch to determine this from the logs.

```
+++ app/src/main/java/org/mozilla/fenix/FenixApplication.kt
@@ -124,6 +124,7 @@ open class FenixApplication : Application() {
             // This has to happen after initializing the megazord, and
             // it's only worth doing in the case that we are a megazord.
             RustLog.enable()
+            RustLog.setMaxLevel(Log.Priority.DEBUG, includePII = true)
         }
     }
```

**Comment by rfk** [comment]
From slack conversation, we think we tracked this down to a bad interaction between the FxA access-token cache and the android-components sync work manager:

* The fxa-client keeps a cache of access tokens in memory, with the intention of re-using them for multiple syncs
* But the sync work manager instantiates a new copy of the fxa-client object for every sync, meaning it starts with an empty cache
* So every sync generates a new OAuth access token, which leads us to request a new tokenserver token.

**Comment by jdragojevic** [comment]
This issue has been investigated by our team, FxA, Ops and Fenix. A [plan for mitigation is in-progress](https://docs.google.com/document/d/1faoytIqJTkrmlQyplLVafRV0zvvm5oKsGeRyOqOn_AA/edit#bookmark=id.mtb3kz9c55wn) as well as a long-term fix by Grisha.
