### ISSUE TITLE
hmac mismatches causes sync to report it was a NetworkError

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1258]
via #1251 we see in the logs:

```
   OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:537:)
06-06 16:24:10.126 9158-14612/org.mozilla.fenix.debug D/sync15::sync_multiple: sync was successful, final status=NetworkError
```

That will be [here](https://searchfox.org/mozilla-mobile/rev/205a4764f2d518219855e7bc1e189db0165b2f95/application-services/components/sync15/src/status.rs#52). That's my fault. @thomcc, that error is never going to really mean network error here is it?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-14)

**Comment by thomcc** [comment]
That really should be fixed by https://github.com/mozilla/application-services/pull/1252, we weren't actually performing HMAC verification.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

[~tchiovoloni@mozilla.com] can this be closed?

**Comment by thomcc** [comment]
Yep!

**Comment by cse-test-sync** [comment]
Transition made by Unito

**Comment by vladikoff** [comment]
oof
