### ISSUE TITLE
Add a method for checking whether we're properly connected to the user's account

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1263]
This is a followup to https://github.com/mozilla/application-services/pull/1244, based on feedback in https://github.com/mozilla/application-services/pull/1244#issuecomment-500062262.

In the android-components account manager, there is logic for detecting auth failures in other parts of the app and having them drive the accountmanager to its "need to reauthenticate" state. This currently feels badly abstracted. In order to determine whether the user needs to re-authenticate, it has to call `getAccessToken` and see whether that fails, but the accountmanager otherwise has no need to care about access tokens.

Let's help clean this up by exposing a method that can be called explicitly to check whether we're still connected to the user's account.  My strawman proposal is:

* Add a method called `checkAuthorizationStatus()`. It takes no arguments and always hits the network to perform the check, specifically by calling the [token introspection endpoint](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/lib/routes/introspect.js#L24).
* If it succeeds, this method returns an object describing what we're authorized to do on the user's account, such as the list of scopes that are currently associated with our refresh_token.
* If it fails, this method will:
  * Throw an auth error to indicate that our token is invalid
  * Throw other sorts of errors as appropriate, e.g. network errors.

This feels like a sufficiently big change that we should do it as a followup rather than blocking https://github.com/mozilla/application-services/issues/1236, although it should be a rapid followup to avoid baking in bad abstractions into a-c longer term.  @grigoryk thoughts?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-94)

**Comment by grigoryk** [comment]
That sounds good to me, definitely inline with my comments in #1244. Thanks for filing this, Ryan!

I'm not sure we need to scope detail at the moment - or will be able to meaningfully recover from having partial access - but this seems like a good starting point to future-proof that story.

**Comment by rfk** [comment]
Mostly I just don't want to return a boolean because I'm almost positive it will outgrow a boolean at some point in the future.

**Comment by rfk** [comment]
Some notes on the various moving parts involved here:

* Start by adding a `http_client` method that can take a `refresh_token`, POST it to https://oauth.accounts.firefox.com/v1/introspect, and return the result. The existing [`oauth_token_with_refresh_token`](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/src/oauth.rs#L31) may be a good starting point.
* Add a `check_authorization_status()` method in [`oauth.rs`](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/src/oauth.rs#L31) that calls this using the current `refresh_token`. The existing `get_access_token` is probably a good starting point, if you ignore all the caching stuff.
* Expose that over the FFI as `fxa_check_authorization_status` by following the example of [`fxa_get_access_token`](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/ffi/src/lib.rs#L280).
* Expose *that* to Kotlin via [`LibFxAFFI.kt`](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/rust/LibFxAFFI.kt#L78).
* Expose *that* via a friendlier API in [`FirefoxAccount.kt`](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt#L231)
* Ideally, also expose it to iOS consumers in a similar fashion via the [Swift FFI wrapper](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/ios/FxAClient/RustFxAFFI.h#L56) and [higher-level API](https://github.com/mozilla/application-services/blob/11a315c74846ead58cdf99f61291dc416532a5de/components/fxa-client/ios/FxAClient/FirefoxAccount.swift#L241).
