### ISSUE TITLE
Better tests for sync_multiple

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1266]
sync_multiple has exactly zero tests. The main problem is that to get any reasonable coverage, we need either http mocks or new traits setup specifically to help with testing.

Our sync manager is going to strike the exact same issue, but anything we do here will be able to be used by that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-679)
┆Epic: a-s live (e2e) integration tests
┆Sprint: Backlog

**Comment by thomcc** [comment]
> sync_multiple has exactly zero tests

Unit tests, yeah. The integration tests exist in part for this purpose, but I agree that it's not an ideal situation.
