### ISSUE TITLE
Is having the website in this repository worthwhile?

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1267]
I'm all for monorepos, but it's a very low-churn area of the repo (I even have it excluded from view in vscode locally).

The main reason I mention it is because the JS deps used in the website get a lot of security advisories. And almost none of them apply to us, but each one of them takes investigating and thinking about, which we probably all do when we see them -- usually a few times before we end up deciding to dismiss it since it doesn't apply.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-11)
┆Story Points: 2

**Comment by thomcc** [comment]
After investigating, the three alerts we had were all only problematic in the case of running the libraries on hostile input. They're run on input we write by hand (our website's content) and so they aren't relevant.

Additionally, none of them could be fixed by simply updating `docusaurus`.

And so I dismissed with "Risk is tolerable to this project".

**Comment by vladikoff** [comment]
Moving to https://github.com/mozilla/ecosystem-platform i think

**Comment by rfk** [comment]
That sounds right; I think we can close the issue here.
