### ISSUE TITLE
Store access tokens in the persisted account state

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1272]
Per discussion in slack, this would be helpful to the a-c intregration and AFAICT doesn't come with any downsides apart from taking up extra space in the JSON (and maybe some transient 401s if the device's clock does anything weird in between runs of the app?)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-10)
┆Story Points: 5

**Comment by eoger** [comment]
@rfk do you think we can close this? I believe a-c went another route to solve that sync access token problem.

**Comment by rfk** [comment]
Yeah, let's close it, it's trivial to bring back if we need it again later.
