### ISSUE TITLE
Native crash in libfenix.so at PKCS8_set0_pbe

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1281]
Example report: https://crash-stats.mozilla.com/report/index/a356be8a-f61c-4441-b09c-843370190526

I suspect something weird's going on with our symbolication, since those stacks seem... Wrong.

That said, this is worrysome and worth investigating.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-8)
┆Epic: Fenix 2.0 Support

**Comment by eoger** [comment]
This only [happened twice](https://crash-stats.mozilla.com/signature/?signature=PKCS8_set0_pbe&date=%3E%3D2019-04-17T15%3A10%3A00.000Z&date=%3C2019-07-17T15%3A10%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports) back when we were linking NSS dynamically. Let's close this for now and re-open if it happens again.
