### ISSUE TITLE
Warnings in AccountEvent.kt

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1282]
There are two warnings in the [AccountEvent](https://github.com/mozilla/application-services/blob/a14a91b1ebdfb33e4a49daae52ef045ea8492d43/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/AccountEvent.kt#L22-L32) kotlin code. Neither of them matter, but they'd be nice to fix.

```
w: components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/AccountEvent.kt: (22, 19): Enum argument can be null in Java, but exhaustive when contains no null branch
w: components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/AccountEvent.kt: (32, 15): Unreachable code
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-7)
┆Story Points: 1

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this
Thanks

**Comment by vladikoff** [comment]
@suhailsinghbains give it a try!
