### ISSUE TITLE
Change taskcluster to run for `pullRequests:public`

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1299]
I talked to @djmitche in #taskcluster, and apparently theres no risk here the way our roles are set up in taskcluster. PRs could try to exfiltrate secrets but they would not be allowed to.

We should do this.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-6)
┆Story Points: 5
┆Sprint: SYNC - 2019-08-02

**Comment by eoger** [comment]
This is being tracked in [bug 1560147](https://bugzilla.mozilla.org/show_bug.cgi?id=1560147), part of the work should be done by @mitchhentges in https://github.com/mozilla/application-services/issues/1203 (segregation of workers). cc @MihaiTabara

**Comment by vladikoff** [comment]
👍
