### ISSUE TITLE
Relicense ffi_support to `Apache 2.0 / MIT`

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1300]
From the licensing runbook: 

> For example, if they are intended to: ... exist as a stand-alone component that can be reused outside Mozilla products they should be licensed under either Apache 2.0, or a dual license that includes Apache 2.0. For example, Rust crates that Firefox depends on are published under an Apache 2.0 / MIT dual license.

I mentioned this a while ago in slack and @rfk said he'd support it. It's probably worth doing this sooner if we want to do so, since it's probably not worth the effort it would take to relicense if it had the work of any external contributors in it.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-5)

**Comment by rfk** [comment]
+1; looks like it's all Thom and Ed in the authors list so far so now is a good time. We'll need to remember to update the top-level license file to describe the exception.
