### ISSUE TITLE
Need ability to "unregister" device capabilities

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1308]
In order to fully supported flipping "send tab" feature in Fenix on/off, we need to have ability to unregister SEND_TAB capability. Current APIs are one-way only, afaik.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-4)
┆Story Points: 2
┆Sprint: SYNC - 2019-08-02
┆Epic: Fenix 2.0 Support

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

need to discuss this

**Comment by eoger** [comment]
@grigoryk how bad do you want this? I'm concerned it might not get much use in practice.
