### ISSUE TITLE
 Move .buildconfig.yml data into gradle files

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/application-services#1310]
The type of user that most commonly updates the list of `application-services` modules (and per-module configuration) are `application-services` devs.
Rather than having them learn and memorize a new config format, we should move config into `gradle`, where the rest of the project build configuration happens

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-96)

**Comment by thomcc** [comment]
Lets defer this until after #1103 lands. I also am not really sold that moving this to gradle would make anything better, TBH.

**Comment by mitchhentges** [comment]
Gotcha - we had a brief discussion yesterday (releng team + mobile team) and mildly agreed to move config back into `gradle` for [`android-components`](https://github.com/mozilla-mobile/android-components/issues/3503).

My rationale is:
1. The config has to exist somewhere: either in-gradle, or in-YAML
2. Either way, there's an cost to learning how to edit the config
    * Note: when the config is in `gradle,` it's more clear how to follow how the config is used, and what each parameter is for (e.g.: when config used to be in `gradle` [with the `setupProject` function](https://github.com/mozilla-mobile/android-components/blob/0c18ed0598b37523b4d5a3a7263392c6a9260255/settings.gradle#L31), you could just jump to the functions implementation)
3. When new options/properties are needed for the config:
    * If all config is in `gradle`, then just `gradle` code needs to be updated
    * If config is in a separate file, then new options/properties need to be made in `gradle` code **and** mirrored in the YAML-parsing logic
4. (not relevant atm): config in `gradle` is more flexible - if a key:value kind of representation doesn't make sense for an option, `gradle` allows you to represent that config in as whatever Groovy abstraction is most ergonomic.

@thomcc what do you think?
