### ISSUE TITLE
AS -1316 Choose What to Sync functionality for Fenix

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1316]
1. Integrate the Sync Manager into Fenix to enable CWTS native selections.
 2. Implement support for Webchannels to enable web CWTS selections.

See [meeting notes](https://docs.google.com/document/d/1apxOwfFwQN0i7C7PDCTfTa8ykbYIhzBeWwAQMAiYjmo/edit#heading=h.rb8c2r97h55h) for updates and milestones

┆Issue is synchronized with this [Jira Epic](https://jira.allizom.org/browse/SYNC-162)

**Comment by liuche** [comment]
FYI Jira isn't something that I (and probably others) have access to - no need to copy everything but important updates or timelines would be appreciated!

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

* CWTS FxA changes to support WebChannels shipped to production.
  * CWTS web extension is integrated into a-c and fenix.
  * Sync Manager implementation is in review and able to be tested in Fenix/A-C in a more end-to-end manner.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

from retro meeting: leaving this challenged, will update after 9/17 for latest status, still working on patches.

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

09/26: Stuff is going well, nothing that we need to do from out end. Known blockers have been resolved from our side. Our end is not challenged, but won't speak for A-C components side.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 4: All work completed.  CWTS is landed in the Fenix nightly builds and scheduled for production release Oct 15th.  We'll continue to monitor and resolve any issues that come in during the nightly cycle and will mark the complete when it lands on production.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 10: Marking as Done.  CWTS / Sync Manager has been on nightly and is scheduled for production on Tuesday Oct 15th.  All follow-up work will be captured in https://jira.allizom.org/browse/SYNC-460.
