### ISSUE TITLE
Tab Syncing component

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1318]
[ ]  Component provides the basic functionality as requested by PM partner for initial implementation

* [https://docs.google.com/document/d/1uqtPncH4BpRII9YgWBqh_TMM7QPIfGCfR2L03ETTaKI/edit#](https://docs.google.com/document/d/1uqtPncH4BpRII9YgWBqh_TMM7QPIfGCfR2L03ETTaKI/edit#)

[ ] Sufficient* rust unit-test coverage of the component

[ ] Features of the component are documented in the [application-services/components/<component>/readme.md](https://github.com/mozilla/application-services/tree/master/components/logins)

[ ] Entry for the component exists in the ecosystem-platform documentation-hub and links to the component readme for:

* [ ] feature documentation
* [ ] api documentation
* [ ] success metrics
* [ ] success dashboard links
* [ ] quality metrics
* [ ] quality dashboard links

[ ] Kotlin APIs are complete and demonstrated through an a-c sample app or integration with the reference browser

[ ] Kotlin integration tests coverage is sufficient and run as part of CI

[ ] Kotlin documentation in a-c repository is up-to-date and complete

~~[ ]  Swift APIs are complete and demonstrated through ... (integration tests in a~~s?)-

~~[ ] Swift API integration tests coverage is sufficient and run as part of CI~~

~~[ ]  Swift documentation for iOS exists in ```application~~services/``` ?-

[ ] Success metrics for the key features supported by the component have dashboards that are linked to the [application-services/components/<component>/readme.md](https://github.com/mozilla/application-services/tree/master/components/logins)

[ ] Success metrics for the key features supported by the component are defined in the [application-services/components/<component>/readme.md](https://github.com/mozilla/application-services/tree/master/components/logins) 

*sufficient as agreed to by the engineering team

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-98)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Implementation plan document review is in-progress.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Planning is going well.  Lina and Edouard were able to connect and make a rough plan for the breakdown of work.  Next steps are getting the issues into Jira and estimated so we can then commit to some milestones.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 28: On track. Project kicked off last week.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Dec 4: On track.  Project is ~50% complete, with planned work (tab syncing integrated into an android sample browser) expected to be completed for Dec 20th.

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Jan 6: All underlying tasks are done, this is ready for integration in Fenix browser.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Jan 14: Final revisions on last PR for landing tab syncing into the reference browser are in-progress.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Feb 3: Tab syncing functionality is implemented into the android reference browser and is available for Fenix team to implement when they are ready to add the feature.
