### ISSUE TITLE
Use lowerCamelCase for FirefoxAccountsError enum variants in swift code

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1324]
These should be renamed to fit common swift style: https://github.com/mozilla/application-services/blob/97b99e38b8104e559c1316f7fbdce32112278cde/components/fxa-client/ios/FxAClient/Errors/FxAError.swift#L11-L14

This is the equivalent of https://github.com/mozilla/application-services/issues/1042 for the fxa-client code.

It will need a changelog entry (If a contributor does this, flag me for review and I'll tell you what to put).

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-169)

**Comment by eoger** [comment]
Closed by https://github.com/mozilla/application-services/pull/1354.
