### ISSUE TITLE
Unexpected error: SqlError(InvalidColumnType(3, Null)) in firefox-ios

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1325]
A pretty common new error in sentry: https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-18/issues/114745/events/847a83c0788c4776817d1d82e28699fc/. Apparently the rate of this is high enough to worry them a good amount.

Unfortunately, not very actionable as-is. @garvankeeley has added code so we should be able to know what rust function is called, I've made the following PR to rusqlite to include the column name as well in the error message, which should help even if the swift backtrace does not contain useful info https://github.com/jgallagher/rusqlite/pull/541

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-170)

**Comment by garvankeeley** [comment]
For tracking this is where more logging was added on Firefox iOS side to send the stacktrace: https://github.com/mozilla-mobile/firefox-ios/pull/5179#issuecomment-505568071. We still have yet to successfully symbolicate, but this is a tractable problem.

**Comment by grigoryk** [comment]
Also seeing this in Fenix. https://github.com/mozilla-mobile/fenix/issues/3774#issuecomment-506878567
