### ISSUE TITLE
Ensure that system deps are compiled for ARM the same way we compile the rust code

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1331]
This was discussed in #gv on slack, and I think there may be some follow-up issue on our side so I wanted to capture it. I do not understand the technical details so please correct me as necessary!

Running Fenix under an ARM32 emulator on Android 5.0 crashes in `libfenix.so`. After some back-and-forth in slack we observed two things:

* Code for system dependencies (notably openssl) appears to be compiled for ARM, whereas the rest of our library is compiled for [thumb](https://en.wikipedia.org/wiki/ARM_architecture#Thumb).
* Our code is compiled to require NEON, which maybe the emulator doesn't properly support..?

@thomcc suggested setting the [`__ARM_MAX_ARCH__`](https://github.com/openssl/openssl/blob/30478c97837a026ba56718f98d490adf7bce2760/Configurations/15-android.conf#L191) flag when compiling openssl, and there may be other things we want to do to ensure things all get compiled in a consistent manner w.r.t. ARM-v-thumb.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-714)

**Comment by thomcc** [comment]
I think this was more about the use of NEON instructions than about the use of Thumb.

For `__ARM_MAX_ARCH__` We should check that this actually fixes the issue in 5.0 ARM32 emulators before doing it. The docs there are sparse, and I suspect if this were actually a problem in practice we'd have more bug reports.
