### ISSUE TITLE
Develop a plan for crash reporting

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#134]
Mozilla has infrastructure for submitting crash reports and geckoview has code in place to format and submit them.

In a gecko-view world we might be able to leverage some of this infrastructure, and while geckoview will have some rust bits that might help, it's unlikely we'll get everything for free. In a non-gecko-view world (eg, lockbox), we will get nothing for free, but longer term we are likely going to want to be able to handle crash reports for those apps too.

This is all a bit vague, but in discussions with @pocmo and @rfk we decided to get it on file.

FWIW, geckoview has a  [CrashReporterActivity](https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/CrashReporterActivity.java) and a [CrashReporterService](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/CrashReporterService.java), and best I can tell, custom code for generating stack traces.

**Comment by pocmo** [comment]
@snorp might have some insights here

**Comment by ncalexan** [comment]
What does Focus do?  Fire TV?  Do we not care about capturing native code crashes on these platforms?

The real thing that `crash-stats.mozilla.com` brings is the potential for uploading symbols for our native code.  That's really nice, and becomes more and more important as we get multiple versions of GeckoView into the wild, outside of the friendly confines of Firefox for Android.  Services like Sentry must do _something_ for Apps that use native code libraries though; maybe this is a solved problem?

**Comment by snorp** [comment]
My preference for GeckoView apps is to at least use Gecko's crash reporting for native code crashes. There are a few reasons for this:

1) It's difficult to analyze Gecko crash reports outside of Socorro. Sentry can accept Breakpad minidumps[1] and symbols, but it's not clear how apps would get symbols into their Sentry instances. Maybe we could publish the symbols with the GV AAR? Anyway, Socorro gives us all of this for free and GeckoView supports reporting there OOTB.

2) We don't want to raise additional barriers for core platform folks fixing issues on Android.

3) We want to have an overall view of Gecko[View] quality across all apps. Socorro/Bugzilla is core to this effort right now.

**Comment by pocmo** [comment]
> What does Focus do? Fire TV? Do we not care about capturing native code crashes on these platforms?

* Everything in the JVM world goes to Sentry.
* Fire-TV uses WebView (and Focus release currently too) and we do not care much about those crashes because they are not really actionable. We are only interested in how often it crashes there.
* Overall we came to the conclusion that the app team do not really need the native crashes - only as a metric to make decisions for shipping etc.

**Comment by rfk** [comment]
I'm doing a bit of triage on our outstanding infrastructural issues, and it's not clear to me how to make this actionable from the app-services side.

What's the current state of the world for Fenix, if there's a panic or other bad behaviour in the app-services rust code that it's using?  Does the app just crash out with nothing reported anywhere?  What about if there's a crash in GeckoView?

Do we consider this work blocking for Fenix MVP Beta or Release?

**Comment by rfk** [comment]
@pocmo can you help me understand the current behaviour of Fenix if there's a crash in the rust components, or redirect me to someone who can?

**Comment by rfk** [comment]
Nominating this for April, but I'm kind of hopeful there's not much left to do on our side apart from confirm it works as expected.

**Comment by rfk** [comment]
From mtg, @eoger you've been working on this, does crash reporting work as expected or is there more work to do here?

**Comment by eoger** [comment]
At this point I think we are doing what we are supposed to do: upload our symbols to Socorro and let the hosting app deal with crashes, so I'd say we are done.
