### ISSUE TITLE
Prep a v0.31.3 with any critical uplifts for Fenix

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1344]
Fenix will be making a point-release for some high-value/low-risk fixes, and android-components will be doing similarly. We should join the party!

Let's use this bug to track candidate issues, and aim to make the tag by EOD Tuesday this week, so it's got time to percolate through upstream consumers.  IIUC, so far we are considering:

* Something about connection-busy handling, ref #1260
* Fix for handling invalid URLs in places, ref https://github.com/mozilla/application-services/issues/1325
* Fix for registering correct device type, https://github.com/mozilla/application-services/pull/1314

Do we have anything else on our "cant wait for the next nightly" list? /cc @thomcc @linacambridge @mhammond @grigoryk

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-174)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-05
┆Epic: Fenix 2.0 Support

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

1. Find out whether each of those are ready to be merged.
  2. Find out from Stefan if they are OK to put in next Fenix release
  3. make a pt release.
  4. document it.

**Comment by rfk** [comment]
This is prepped and proposed for uplift to a-c over here: https://github.com/mozilla-mobile/android-components/issues/3630

I deliberately haven't sent a broader release announcement email since a-c is really the only intended consumer of this release.
