### ISSUE TITLE
Expand existing fxa-client build step in .taskcluster.yml to produce Desktop OpenSSL libraries

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#138]
Right now, https://github.com/mozilla-mobile/android-components/blob/79c917f05be971ba8387cc4d83c205b27c27c3d0/.taskcluster.yml builds and packages up OpenSSL for Android.  I'd like to expand that to include packaging the `include` directory (if we don't already) and to build and package Desktop OpenSSL libraries as well.

That would allow us to do better for #113.  Developers would fetch the produced package, unpack it into a well-known location, and then we could get the Cargo build (and Gradle build) to know about the well-known locations for all the different targets we care about.  That would avoid a good deal of futzing around with `OPENSSL_*` environment variables, some of which depend on the target toolchain.

**Comment by ncalexan** [comment]
@eoger do you see any issue with doing this?

**Comment by eoger** [comment]
No objection there!

**Comment by ncalexan** [comment]
I'm going to use this to track a larger issue: shipping an `@jar` version of our Rust components so that local unit testers can run JVM tests.  This is the equivalent of what JNA does, shipping an `@jar` and an `@aar` version of their artifacts.

**Comment by thomcc** [comment]
I don't think we need to do anything to openssl (or sqlcipher) here. Every lib on all platforms should be building it statically.

So this probably just running `./build-all.sh desktop` and creating a jar in addition to an aar?

**Comment by eoger** [comment]
@ncalexan is this issue still relevant?

**Comment by ncalexan** [comment]
> @ncalexan is this issue still relevant?

No: this was done as part of #262 and friends.
