### ISSUE TITLE
Use release version of NSPR

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1388]
Depends on [bug 1561953](https://bugzilla.mozilla.org/show_bug.cgi?id=1561953) getting resolved and a new release is made (probably 4.23).

An intermediary step would be to get off my own repository once the bug is resolved on the upstream repo:
https://github.com/mozilla/application-services/blob/270b0ea2a03c1af8e1f229b0c984b83e73cfe5df/libs/build-all.sh#L69

Note that currently this patch might mean that NSS also needs a patch (to pass that new `--without-pr-version` on static builds).

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-184)
┆Story Points: 3
┆Sprint: SYNC - 2019-07-19
┆Epic: Trusted Crypto

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

🚩 Flag added

Waiting on feedback from NSS team

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Removing impediment flag - Edouard and Thom had a productive meeting with Mike and identified next steps for 2 changes that need to be made to get this merged in.  Edouard is filing follow-up issues.
