### ISSUE TITLE
SearchResult should be better exposed over the FFI

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1393]
This is a couple closely related issues:

1. SearchResults are passed over the FFI as JSON, and we should pass the info as protobufs
2. The data passed over the FFI isn't the minimally useful set of data.

We might want to add some protobuf functions like this:

```
// Protobuf allows nesting these, but prost behaves weirdly if we do.
enum SearchResultReason {
    // Never used in practice. Maybe remove this from here and from the rust enum?
    KEYWORD = 0,
    ORIGIN = 1,
    URL = 2,
    PREVIOUS_USE = 3,
    BOOKMARK = 4,
    // If we get real tag support, just add `optional string tags` to SearchResult below, but
    // for now expose that it was because of tags.
    TAG = 5,
}

message SearchResult {
    required string url = 1;
    required string title = 2;
    required int64 frecency = 3;
    repeated SearchResultReason reasons = 4 [packed = true];
}

message SearchResultList {
    repeated SearchResult results = 1;
}
```

And clean up SearchResult to roughly match. I also think we should expose Reason over the FFI at the same time. This needs a little more thought though.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-108)

**Comment by Vishal19111999** [comment]
I have just searched about protobufs and with little guidance, I may be able to solve this. Can I solve this as my first issue?

**Comment by thomcc** [comment]
This is likely a fairly difficult first issue, as it involves the rust search code the rust FFI code, and the Kotlin FFI bindings. If you'd like to take it, you can, but it's probably not the best choice for a first issue when you're unfamiliar with the codebase.

**Comment by Vishal19111999** [comment]
OK, can you please suggest me a good first issue? I have experience in Django & Nodejs.

**Comment by lyuyuan** [comment]
I will try this 🚀

**Comment by lyuyuan** [comment]
>     2. The data passed over the FFI isn't the minimally useful set of data.
> 
Hi @thomcc ! Should I remove fields, `iconUrl` and `searchString` from the data class `SearchResult` since the Protobuf message does not contain the information anymore?
