### ISSUE TITLE
Use `sync-guid` in `sync15` and `logins`

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1395]
`logins` is an easy case, `sync15` is harder. `sync15` has a lot of places where we use sync ids:

- `id` field of a BsoRecord, Payload, ...
- `ids` in CollectionRequest
- lots of places talk about `failed_ids` and `successful_ids`
- sync_id in MetaGlobalRecord, MetaGlobalEngine
- `id` in CryptoKeysRecord (although it's always the string "keys")
- `records_synced` passed to `Store::sync_finished`
- both fields of `CollSyncIds`
- definitely more, I just skimmed.

However we also have things that are called an id, but are unrelated. Some rules of thumb for telling the cases apart:

- The tokenserver token, and related code has a few fields like id or uid... but that have nothing to do with sync ids.

- key_id/kid is a JWT thing and has nothing to do with sync ids.

- any place where we use the output of `random_guid` is definitely a sync id (in fact, that function should just be replaced with `Guid::random()` from #1394).

- Any place where we use a string to talk about a record is probably a guid. the exception is for cases where it's a JSON-serialized record, which it will be in a couple cases.

- If in doubt, either ask, or add logging statements into the sync15 crate and run the integration tests. If it's a 12-character base64url encoded string, it's almost certainly a sync id.

- If you really can't tell, err on the side of leaving it a string, as that's less potentially confusing in the future.

CC @lyuyuan92. It would be great if you took this if you're interested, but it's not a problem if you don't have time or would rather not.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-188)

**Comment by lyuyuan92** [comment]
Sure! This will be my next PR :)
Thanks for writing up detailed instructions!
