### ISSUE TITLE
Add TV and VR headset device types

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1407]
Breakdown:

- [x] A-S PR: https://github.com/mozilla/application-services/pull/1417.
- [ ] Design bug: https://github.com/FirefoxUX/photon-icons/issues/54.
- [ ] Fenix bug: https://github.com/mozilla-mobile/fenix/issues/4037.
- [ ] Firefox TV bug: https://github.com/mozilla-mobile/firefox-tv/issues/2567
- [ ] Firefox for iOS bug: https://github.com/mozilla-mobile/firefox-ios/issues/5278.
- [x] Desktop bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1567569.
- [x] FxA bug: https://github.com/mozilla/fxa/issues/1856.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-110)

**Comment by rfk** [comment]
> FxA clients that show icons next to send tab targets such as Desktop.

How will these clients behave currently, will they default to showing e.g. a "desktop" icon?

**Comment by rfk** [comment]
We should also update the FxA docs to list the supported types, e.g. https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/device_registration.md

**Comment by eoger** [comment]
> > FxA clients that show icons next to send tab targets such as Desktop.
> 
> How will these clients behave currently, will they default to showing e.g. a "desktop" icon?

- Defaults to `phone` on [Desktop](https://searchfox.org/mozilla-central/rev/96403eac4ff6f96f89a0b120b29bd46540d5705e/browser/base/content/browser-sync.js#792).
- Default to `desktop` on [iOS](https://github.com/mozilla-mobile/firefox-ios/blob/24fac8a92d7b1184ddafb14b6b0242adf854cbbf/Client/Frontend/Extensions/DevicePickerViewController.swift#L142).

![heh](https://media.giphy.com/media/jCcgSFERzf4hW/giphy.gif)

**Comment by mcomella** [comment]
FYI: we're hoping to ship Send Tab this quarter on FFTV and this will help us. https://github.com/mozilla-mobile/firefox-tv/issues/2567

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Turning this into an EPIC in Jira for tracking.

**Comment by eoger** [comment]
I believe we've done everything we could on our side now, closing.
