### ISSUE TITLE
Handle account push events

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1418]
We should handle the following Push events and generate AccountEvents for them:

```
DEVICE_CONNECTED: 'fxaccounts:device_connected',
DEVICE_DISCONNECTED: 'fxaccounts:device_disconnected',
PROFILE_UPDATED: 'fxaccounts:profile_updated',
PASSWORD_CHANGED: 'fxaccounts:password_changed',
PASSWORD_RESET: 'fxaccounts:password_reset',
ACCOUNT_DESTROYED: 'fxaccounts:account_destroyed',
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-111)
┆Story Points: 5
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-02-14

**Comment by eoger** [comment]
We should also figure out which Push Events make sense in the OAuth world: 
does `password changed/destroyed and account destroyed` provide any value or should we just let the app fail on 401s anyway?

**Comment by rfk** [comment]
In retrospect I would have preferred a generic "your token has been revoked somehow" message over the highly-specific "password changed" and "password reset" messages. Maybe we can add such a thing for OAuth clients?

> or should we just let the app fail on 401s anyway?

I think there's value in using push messages for this, especially if it might help the app more quickly discard other cached auth state that doesn't stop working automatically (such as JWT access tokens).
