### ISSUE TITLE
Change failing to load the megazord to be a hard error at load time instead of at call time

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1426]
E.g. https://github.com/mozilla/application-services/blob/3f618a194d4d3984ecb428ef8b33335fe86fcdfd/components/support/android/src/main/java/mozilla/appservices/support/native/Helpers.kt#L181

I didn't do this as part of #1103 as it was unclear if use cases for this still exist.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-716)
┆Story Points: 3
┆Epic: Integration testing for a-s
┆Sprint: SYNC - end 2020-03-13

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Let's do this as part of tightening up our local-build-and-test workflow, since it looks small and increases the chance of discovering errors early.
