### ISSUE TITLE
Use reqwest w/ rusttls on Linux

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1432]
Here's how our SSL stacks look like currently:

| Platform                     | SSL stack                  |
|----|----|
| Android (phones)           | viaduct -> GeckoView/NSS              |
| Android (unit tests)           | viaduct (broken since not initialized?)              |
| iOS (phones + simulator)     | native~~tls~~ > Secure Transport (OS)               |
| Desktop (Win32) | native~~tls~~ > Schannel (OS)         |
| Desktop (macOS) | native~~tls~~ > Secure Transport (OS) |
| Desktop (Linux) | native~~tls~~ > OpenSSL               |

In order to get rid of OpenSSL completely, I'd like use to move `Android (Unit tests - Linux)` from `native-tls` which pulls OpenSSL to `rustls` (SSL stack written in Rust).

My plan was to add to viaduct's `Cargo.toml` something like this:

```toml
[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
# reqwest w/ rustls feature
[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "ios"))'.dependencies]
# Regular reqwest
```

But because of https://github.com/rust-lang/cargo/issues/2524 we can't do that :slightly_frowning_face:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-696)

**Comment by rfk** [comment]
As a kind scoping question...how necessary is it for our unit tests to actually hit the network? Would an alternate approach here be to rework our unittests to use mocked-out network calls rather than depending on a live network connection?  (I'm sure that would be a much *bigger* task, just want to understand the alternatives).

**Comment by eoger** [comment]
Turns out our unit tests actually don't hit the network at all, I discovered that they are compiled with Viaduct support which doesn't get initialized in unit tests and still pass :)

**Comment by rfk** [comment]
Alternately, we could consider [making an iOS backend for viaduct](https://github.com/mozilla/application-services/issues/1326), and then switch to using reqwest-with-rusttls on all desktop platforms (where it's only used for testing).

**Comment by eoger** [comment]
We did what we wanted to do here, and the reqwest/native-tls-vendored feature allowed us to remove OpenSSL from our `libs/` directory.
Furthermore `viaduct-reqwest` must be imported explicitely to use the reqwest backend of viaduct now, so there's no confusion possible.
