### ISSUE TITLE
Consider including logins into the Fenix megazord

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1462]
There's no UI built for it so it won't change anything for end users, however it might make the Fennec logins migration story easier as we can simply populate the database instead of relying on a 3rd party temporary storage to hold migrated Fennec passwords till we get that UI. WDYT @rfk @thomcc?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-210)

**Comment by thomcc** [comment]
Maybe, but at that point we should consider if the Fenix megazord is still useful. the only reason it exists separate from the full (then reference-browser) megazord is so that Fenix doesn't have to have logins.

Removing a megazord will improve build times substantially.

**Comment by vladikoff** [comment]
Let's do it! 

<img src=https://user-images.githubusercontent.com/128755/61971394-f7509580-afac-11e9-8324-d820217f5061.png width=250 />
