### ISSUE TITLE
Consider merging the fenix megazord with the "full" one

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1466]
From @thomcc:

> It would reduce build times a great deal, simplify our configuration, and they would be identical after this time.

Reason for not doing it would be the Fenix team is uncomfortable not having an easy way to opt out of new components.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-695)
┆Story Points: 3
┆Epic: important not urgent

**Comment by thomcc** [comment]
CC @grigoryk

**Comment by rfk** [comment]
I wonder if there's a way for us to do this while continuing to publish a dedicated `fenix-megazord` AAR (that just contains the same code as the default megazord) in order to reduce churn for the Fenix team.

**Comment by rfk** [comment]
From mtg: lots of agreement that we should do this, removing "discuss" label.
