### ISSUE TITLE
Use system allocator for FxA

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#147]
FxA is not performance critical and doesn't allocate much either, we could gain a little bit of space by switching from rust's default jemalloc allocator to the platform-specific ones.

**Comment by thomcc** [comment]
If the gains are more substantial than I remember (I remember them being only around 50k or so) we likely will want to do this for the sync logins ffi too.

**Comment by thomcc** [comment]
Worth noting this would make megazording harder (we would need to either duplicate a lot, enable it everywhere, or disable it everywhere).

**Comment by thomcc** [comment]
Rust solved this for us in 1.31.0 by using the default allocator everywhere. Someday we may want to test including jemalloc (and ideally hooking it into sqlite the way desktop does) to see if the perf boost we get is worth it, but for now.
