### ISSUE TITLE
Review read/write permissions for this repo

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1476]
Now that we have started to run Taskcluster jobs on every PR, there's no need to add specific permissions to contributors. I suggest we:

* Review special permissions granted to contributors on this repository.
* Remove special permissions granted to members that are superseded by team permissions they are in.
* Lastly, ensure our team members are up-to-date.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-724)

**Comment by vladikoff** [comment]
fixed
