### ISSUE TITLE
Use protobufs instead of JSON in push component

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1491]
I see that the `push_subscribe` and `push_dispatch_for_chid` methods in our Push FFI both return their results in form of a JSON string instead of the standard Protobuf that we use everywhere else.
This is a good issue to work on for anyone curious about how our protobuf serialization approach work.

Roughly the work to do is:
- Introduce a `push_msg_types.proto` protobuf schema definition file in `components/push/src/` that describe `PushSubscription` and `DispatchInfo` messages.
- Add a compilation step for the push crate that does the auto-generation of Rust structs from these .proto files at build time. Example [here](https://github.com/mozilla/application-services/blob/3c96e9dbfed0545de542bb4943b71368231d5ec7/components/places/build.rs).
- Do the same for the Kotlin side, which means more or less copying anything related to protobuf from [here](https://github.com/mozilla/application-services/blob/3c96e9dbfed0545de542bb4943b71368231d5ec7/components/viaduct/android/build.gradle) and adding it to push's `build.gradle` file.
- On the Rust side, in `components/push/ffi/src/lib.rs`, use the auto-generated types that we generated previously to return a `ByteBuffer` (see what other crates are doing!). Don't forget to define the bytebuffer destructor also.
- On the Kotlin side, parse these byte buffers into the classes we auto generated. See what [we do for FxA](https://github.com/mozilla/application-services/blob/master/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt). This part is tad less obvious, so do not hesitate to message me to figure out what to do.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-218)
┆Story Points: 5

**Comment by lyuyuan** [comment]
I'd like to have a try on this one!
