### ISSUE TITLE
XCode 11 Build

### ISSUE THREAD

**Issue by joeyg** [mozilla/application-services#1493]
As iOS 13 comes closer to release (September) Lockwise iOS and Firefox iOS will need to be tested on the new OS. The easiest way to test, debug, and resolve issues is with the iOS13 simulator that comes with Xcode11. While Xcode11 will be in pre-relase until iOS13 is will reach relative stability soon. Lockwise iOS already has [bug reports](https://github.com/mozilla-lockwise/lockwise-ios/issues/1089) coming in.

It would be helpful to have a build of application-services built with Xcode11 and Swift 5.1 that could be used for testing and debugging ahead of the public iOS13 release.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-220)

**Comment by thomcc** [comment]
CC @garvankeeley

**Comment by garvankeeley** [comment]
I am using Xcode11 beta, and when running carthage it sees that the Megazord was built with and older xcode, and then builds it locally instead.

**Comment by joeyg** [comment]
Ahh ok. I guess I haven’t set up the rust tooling on this laptop yet.

**Comment by garvankeeley** [comment]
I have to use this command to get the right toolchain 
`carthage update --toolchain com.apple.dt.toolchain.XcodeDefault --platform iOS application-services`

**Comment by garvankeeley** [comment]
I think it is time we should build master against Xcode beta. Lots of people pinging me with build problems trying to do this themselves. It *does* work, but the build can be tricky to do locally.
