### ISSUE TITLE
Strategy for v0.34.1

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1498]
Our release pipeline changed recently, so we can't really just cut a release based on the 0.34.0 tag.
My plan is roughly to cherry-pick the recent release pipeline changes on top of 0.34.0. (1433, 1448, 1450)
I'll try and make a branch to test that strategy.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-223)

**Comment by rfk** [comment]
Thanks for writing this down @eoger; we closed this in triage but it's good to have for reference if we need it.
