### ISSUE TITLE
[meta] Decouple "Signing in to Firefox" from "Enabling Firefox Sync"

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1509]
Currently, signing in to Firefox with your Firefox Account [1] is synonymous with activating Firefox Sync -- all of the onboarding messaging is specific to Sync, and the very presence of an active signin session held by the browser is taken as a signal that it should sync its data to the associated account.

We're adding more Account-related features and services to the browser, such as a the Firefox Monitor protection report card (Bug 1559422). These features should be able to use the browser's sign-in state even if the user doesn't have (or doesn't want) Firefox Sync.

For more on the rationale, you can check out this [motivational slide deck](https://docs.google.com/presentation/d/1QOO3hVKzg3tSAKwLLfYZNhI_uB0JmhZqCBnIckCvzXc/) (but on the very explicit understanding that the proposed UX changes therein are for illustrative purposes only, and final UX is still in development).

This will be a significant refactor with lots of UI touchpoints potentially affected, so I'm filing a meta-bug to track all the moving parts. Broadly, we'll know that we've succeeded when:

* The "Join Firefox" flow from about:welcome allows users to set up their Firefox Account without enabling Sync
* The "Sign up to Monitor" button on about:protections can sign users in to Firefox and display their Monitor report without enabling Sync
* Users can easily enable Sync after the fact when they sign in via one of those flows.

[1] Note that "Signing in to Firefox" refers to credentials held by the Browser itself for its own use; it's entirely different from signing in to accounts.firefox.com on the Web, and we are not planning to conflate the two.

---
🐞 Issue is synchronized with Bugzilla [Bug 1570565](https://bugzilla.mozilla.org/show_bug.cgi?id=1570565)

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-124)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

2019-09-13 Update: 50% of the estimated work is completed.  We have clear UX designs and the project is now well-scoped.

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

As of 9/16, we are still on track and over 50% of the work done

**Comment by cse-test-sync** [comment]
➤ Mark Hammond commented:

Sept-17 Update: On track, ~70% of work done, should be starting review process at the end of this week.

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

09/26: About:welcome, opt in to choose what to sync. Targeted for Fxa 147 and FF 71. Hopefully server bits merged next week. Mark stuff seems on track.

Metrics stuff not in a good spot: 

  * moving devices to top level is blocked on FxA server bug.
  * making weave more reliable, slow but next break should resolve other one.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 4: On track ~70% of the work is completed and changes are available in the Fx71 nightly. PI team has produced a test plan https://docs.google.com/document/d/1PoXvcLiUQb9fkuSaScACSpsi1xFyV5XEVAmZiOSygts/edit ( https://docs.google.com/document/d/1PoXvcLiUQb9fkuSaScACSpsi1xFyV5XEVAmZiOSygts/edit ) and high-level test cases document https://docs.google.com/spreadsheets/d/1xgx3Jj8hD4FKWZCd61khzYp4sasEE_2l4wXMu-53U3M/edit#gid=1648005644 for our review. FxA changes (about:welcome, support for opting out of sync and metrics updates) are slated for the Fxa 147 release.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 10: On track.  We're holding at about 70% done.  We've completed all the major feature work.  Desktop changes are in nightly and required FxA server changes are on production.  We are finishing the telemetry changes and the PI team made a first pass on the nightly build and uncovered a few bugs that have been added to the upcoming sprint.   Expectation is that we'll be completed with the planned work by the end of this upcoming iteration (2019-10-24).

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 18: On track.  We're now at 85% complete with the remaining telemetry work in review and all the issues found by the PI pass of nightly addressed.  We're on-track to finish the work by the end of this iteration and even the Jira epic report agrees.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 29: On track for Firefox 71.  Still about 85% complete overall with 4 issues identified for uplift to Beta.  2 are complete with uplift request, 2 remain.  Remaining issues are server-side changes. All work is currently planned for the ongoing sprint with completion planned for Nov 8th.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Nov 14: On track for Firefox 71.  Continuing to complete the remaining 10% or work.  Last regression SYNC-317 was surfaced by the PI validation last week is in-progress and expected to land next week.  Monitoring issue SYNC-220 dependency is scheduled for Fxa train 151.  SYNC-303 a late arrival for additional metrics on FxA side is planned for this iteration.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Dec 4th: Complete.  Sign in to Firefox feature shipped to production with Firefox 71!
