### ISSUE TITLE
Update about:preferences#sync to reflect the decoupling of FxA and Sync

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1510]
Per Bug 1570565, we aim to decouple "Signing in to Firefox" from "Enabling Firefox Sync".  The sync preferences page will need to be updated to reflect three main potential states:

* The user is not signed in to Firefox
* The user is signed in to Firefox, but has not enabled Firefox Sync
* The user is signed in to Firefox and is syncing their data

:rfeeley has some initial designs for this but they're not final, I believe the next action here is to get to finalized designs.

---
🐞 Issue is synchronized with Bugzilla [Bug 1570567](https://bugzilla.mozilla.org/show_bug.cgi?id=1570567)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-233)
┆Story Points: 5
┆Sprint: SYNC - 2019-09-26
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
