### ISSUE TITLE
Device Type needs to include tablets

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#1547]
For: https://github.com/mozilla-mobile/fenix/issues/4569
Related: https://github.com/mozilla-mobile/firefox-ios/issues/5299

We need the [`Device.kt`](https://github.com/mozilla/application-services/blob/master/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/Device.kt#L30-L32) types to include tablets.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-245)

**Comment by eoger** [comment]
Related: https://github.com/mozilla/application-services/issues/1407

We used to store `tablet` under `formfactor` in the client engine, but this is going away. So we could indeed add `tablet` to FxA Device types. Wdyt @rfk ?

**Comment by rfk** [comment]
Sounds fine to me, esp since we're busily adding new entries anyway 👍

**Comment by eoger** [comment]
Fixed by d5fdafa3f89b7274460b6436f9343d08aee108b0.
