### ISSUE TITLE
Sync logins FFI duplicates FxaResult from the Fxa android component

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#155]
But probably doesn't need to? Not clear (to me). CC @eoger, @carolkng, @csadilek

**Comment by eoger** [comment]
@csadilek I think we have talked in the past of putting that class in a separate android-component package?

**Comment by thomcc** [comment]
That would be really nice. The only difference between the version I have and the version in fxa is the name -- it seems perfect for separating out.

**Comment by csadilek** [comment]
I am going over issues to link them to relevant r-b and a-c issues. I think this one can be closed now that we switched to `Deferred`.

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla/application-services/pull/383
