### ISSUE TITLE
Including :service-fxa Android dependency increases APK size by ~15.3 MB

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1559]
From @mcomella over in https://github.com/mozilla/fxa/issues/2115:

The FFTV APK size increased from 5.43 MB to 21.1 MB between our v4.0 app release and v4.1-LAT1 beta release. We investigated [in this issue](https://github.com/mozilla-mobile/firefox-tv/issues/2647) and discovered there are four copies of `lib/*/libfxaclient_ffi.so` included across four architectures, each one ~3.5+ MB in size:

![Screen Shot 2019-08-07 at 17 09 11](https://user-images.githubusercontent.com/759372/62666062-b0f92000-b936-11e9-971d-5f80285bb7c2.png)

Thus, we suspect this to be the root cause of size increase. This is a non-trivial increase in our app size that we'd prefer to avoid. Thoughts:

* afaik, Fire TV only works on one architecture: can we ship only one copy of this library?
* ~3.5 MB seems like a lot for the FxA libraries: why is it so large? Is there any way to trim that down?

Note: I haven't created a minimal test case to verify that just adding the `:service-fxa` dependency increases our app size to that magnitude – I'm inferring from what we discovered.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-677)

**Comment by rfk** [comment]
> Note: I haven't created a minimal test case to verify that just adding the :service-fxa
> dependency increases our app size to that magnitude – I'm inferring from what we discovered.

Thanks; I don't think trying to reduce any further would be a good use of your time, these numbers are within the range we observe for other projects and is almost certainly the root cause of your issue.

> afaik, Fire TV only works on one architecture: can we ship only one copy of this library?

I believe Fenix has some logic to strip down their final distribution bundles to only have libs for a specific architecture, but it may be specific to the play store. If it's possible for you to remove them at build time, it should be perfectly safe to do so.

The way these shared libs are built is going to change in the next android-components release, and will result in an *even bigger* `.so` by default.  We should make a [custom megazord](https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html) for FFTV that only builds for the architecture you need and only the components you need.

You're currently only using the FxA component and its send-tab functionality, right?

Unfortunately I would still expect this custom artifact to have size measured in MB rather than KB due to the overheads from Rust runtime. Figuring out how to reduce this over time is an ongoing topic for our team but we don't have any obvious low-hanging fruit at this stage.

**Comment by rfk** [comment]
>  We should make a custom megazord for FFTV

I spun this out into a separate issue: https://github.com/mozilla/application-services/issues/1560

@mcomella if you could please weigh in there with the details of what architecture to build for that would be helpful.

**Comment by rfk** [comment]
> We should make a custom megazord for FFTV that only builds for the architecture you need 

This turns out to be more complicated than I hoped. On chatting with the team in slack, it will probably be simpler overall if you're able to exclude the unneeded architectures as part of your build on the FFTV side.

@thomcc you had a suggestion for how this might look in `build.gradle`, could you please weigh in here?

>  and only the components you need.

We can still explore this part though, it saves about 2M from the size of each `.so`.

@mcomella it would be useful to have concrete requirements from your perspective here if possible. What size threshold would you consider a blocker for release? What size would you consider a reasonable target if we could free up a bunch of time to explore optimizing things down further?

**Comment by mcomella** [comment]
> You're currently only using the FxA component and its send-tab functionality, right?

Yes.

> @mcomella it would be useful to have concrete requirements from your perspective here if possible. What size threshold would you consider a blocker for release? What size would you consider a reasonable target if we could free up a bunch of time to explore optimizing things down further?

@athomasmoz Do you have an opinion? How large is too-large for our APK? fwiw, we were at 5.43 MB before this change and, if we later include GeckoView, it'll non-trivially increase our APK size (+45MB?). Presumably, our APK size will continue to slowly increase as we continue to develop the app.

As for my opinion, I don't have good baselines for native code but tbh perhaps ~3.5 MB (by removing the other architectures) is good enough, especially compared to GV. It's frustrating that our app will increase in size by 65% for one feature (send tab) though. fwiw, to benchmark against other Android libraries, the Kotlin stdlib is ~1 MB, most libraries are smaller than that, and we can take advantage of dead code elimination.

fwiw, one surprising thing I'm concerned about is that a larger APK means slower installation times, both from transferring (we're forced to install builds over wifi) and the actual installation (they're low powered devices with slow & small-sized disks). Though I haven't measured, I believe the difference from 5 to 20 MB has been noticeable.

FYI: we're actually shipping this code right now but it's pref'd off so users are already affected by the library size.

**Comment by thomcc** [comment]
AH! I just realized that the sizes shown in that panel are the compressed sizes.

This is from reference-browser, libmegazord.so is 8MB-9MB uncompressed, but is 3.4MB in that window.

<img width="1029" alt="Screen Shot 2019-08-09 at 10 34 53 PM" src="https://user-images.githubusercontent.com/860665/62818054-23fcc500-baf6-11e9-9fbe-7411e61d48ce.png">

This is good because getting things down to 3.4MB uncompressed would have been... essentially outside the realm of possibility.

I actually had a fairly long writeup defending why our code is so big, and things we'd like to do to mitigate it, but it seems much less important now.

(In our vague defense, while you're correct that native code libraries are larger than bytecode ones, if your user doesn't already have the VM for that bytecode on their machine, you'd have to count the size of the VM too :p)

I left a description of what to do about the .so files for architectures you don't care about https://github.com/mozilla/application-services/issues/1560#issuecomment-520117001.

**Comment by rfk** [comment]
> It's frustrating that our app will increase in size by 65% for one feature (send tab) though.

Aye, I hear you. It's a large upfront cost that amortizes well across multiple app-services features, but can be a big surprise if you're only using one. It's definitely something we need to keep chipping away at.

**Comment by rfk** [comment]
I don't think we're realistically going to do anything about this that makes it worth keeping this issue open.
