### ISSUE TITLE
Make a custom megazord for FFTV

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1560]
Ref https://github.com/mozilla/application-services/issues/1559

FFTV only needs the FxA component and only on a single architecture, they shouldn't need to pull in the whole megazord on four different architectures.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-256)

**Comment by rfk** [comment]
I'm going to experiment with building one in the background while I hack on some other stuff, will post any interesting notes here.

**Comment by rfk** [comment]
> FFTV only needs the FxA componen

Actually I expect it will also need Push, for send-tab.

**Comment by rfk** [comment]
My first attempt at this produces the following:

```
rfk@pomelo:tmp$ unzip ../fftv-megazord-0.36.0.aar
Archive:  ../fftv-megazord-0.36.0.aar
inflating: proguard.txt
inflating: R.txt
inflating: AndroidManifest.xml
inflating: classes.jar
creating: jni/
creating: jni/arm64-v8a/
inflating: jni/arm64-v8a/libfftv.so
creating: arm64-v8a/
rfk@pomelo:tmp$ du -hs ./jni/arm64-v8a/libfftv.so
6.0M    ./jni/arm64-v8a/libfftv.so
```

Which is larger than the existing `libfxaclient_ffi.so` from #1559, likely because it's bundling more stuff from the megazord.

Looking at the [list of dependencies](https://github.com/mozilla/application-services/blob/fftv-megazord/megazords/fftv/DEPENDENCIES.md) pulled in by this custom megazord, there isn't a lot on there that is obviously unnecessary. The main one is OpenSSL, which we're close to getting rid of.  Other largish things that you may be surprised to find us pulling in include:

* NSS; we use this for various cryptographic routines in FxA and Push.
* NSPR; this is unfortunately a dependency of NSS, despite us not really needing the bits of NSS that depend on it
* SQLite; this is used by the push component for storage of active push subscriptions

Anyway, it's a start.

**Comment by mcomella** [comment]
> SQLite; this is used by the push component for storage of active push subscriptions

afaik, Android ships with a SQLite implementation. I wonder if it'd be possible to replace the one shipped in the library with the one shipped on device. Of course, there are some trade-offs such as different versions of SQLite across Android API levels, maintaining a DB in multiple versions of SQLite, and unit tests that don't run on the same version of SQLite as they do on device.

**Comment by mcomella** [comment]
> @mcomella if you could please weigh in there with the details of what architecture to build for that would be helpful.

afaik, current Fire TV devices only support arm (so the `armeabi-v7a` direcotry).

**Comment by mcomella** [comment]
Context:
- Amazon's [official device reference](https://developer.amazon.com/docs/fire-tv/device-specifications.html) does not specify and I tried searching for "x86 fire tv" and "arm fire tv" and nothing promising comes up.
- We've installed arm GeckoView builds on several Fire TV devices, which works.
- When we started on Echo Show, it was notable that it was x86, unlike Fire TV

I'm not sure the whole line of devices is arm but I don't see any reason not to assume so.

**Comment by thomcc** [comment]
> afaik, Android ships with a SQLite implementation. I wonder if it'd be possible to replace the one shipped in the library with the one shipped on device.

We statically link to SQLite it so it would not be possible for you to swap it out after the fact.

For push, using the system library would be fine in principal (if this were places it would not be without rewriting a huge number of queries and redesigning our tables, as we use a very modern SQLite and depend on its features heavily).

That said, while it's doable in theory for push, I think it would be quite tricky in practice. I can think of many ways it could go wrong.

> I'm not sure the whole line of devices is arm but I don't see any reason not to assume so.

The x86 builds are mainly for use inside the simulator during local development (e.g. inside android studio). I assume this is important to you, as using an ARM simulator is quite slow, and it's hard for me to imagine y'all are uploading your changes to actual TVs to test things locally.

In either case, you should fix this on your end. There are two related methods of doing so, both documented here https://developer.android.com/ndk/guides/abis, abiFilters and splits. Either of them should work for your case. If you need us to help you with this we probably can -- It's easier to do this on yours than on ours.

You can also look at either [Fenix](https://github.com/mozilla-mobile/fenix/blob/634ee184a6637dd0e2444a102231f4b396b08af3/app/build.gradle#L82-L110), who uses abiFilters, or [reference-browser](https://github.com/mozilla-mobile/reference-browser/blob/a52eb05dd01808f40f848d6fcc37d6466efef1d3/app/build.gradle#L74-L82), who uses splits. Both techniques allow those apps to avoid shipping code for unrelated architectures in their apk files.

**Comment by rfk** [comment]
> Which is larger than the existing libfxaclient_ffi.so from #1559, likely because it's bundling more stuff from the megazord.

As Thom points out in https://github.com/mozilla/application-services/issues/1559#issuecomment-520120507, my comment above is not accurate, because issue #1559 was reporting compressed on-disk sizes. The new megazord architecture has not produced a significant increase in size of the `.so` file versus the standalone fxa component.

**Comment by rfk** [comment]
Closing this until we have a clear ask for it.
