### ISSUE TITLE
Start using rustfmt.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#157]
There's no reason we aren't doing this beyond that we haven't done it. We also should use it in CI.

**Comment by ncalexan** [comment]
Just for context: we *want* to use `rustfmt`, but in general the output is so poor that we haven't done so.  It's possible things have gotten better (Mentat evaluated more than a year ago!) but I think other Mozilla projects aren't using `rustfmt` either :(

**Comment by thomcc** [comment]
It seems fine in https://github.com/linacambridge/vellum, and in https://github.com/mozilla-services/syncstorage-rs. The style in much of mentat is also more idiosyncratic than in a-s.

I'd also be willing to accept slightly worse formatting for guaranteed consistency and to not have to think about it ever.

**Comment by thomcc** [comment]
From #422:

> I remember on @linacambridge's repo we had a problem where rustfmt was never happy with the changes, if this is fixed we should probably enforce rustfmt.

I think this is mostly avoided if you use the default settings, but I could be wrong. There's still the issue that things will change with different versions of rustfmt, though...

@pjenvey / @philbooth / @bbangert y'all are using it in syncstorage-rs, any thoughts on it?

**Comment by philbooth** [comment]
> any thoughts on it?

Fwiw I love it, even though I sometimes disagree internally with the results it generates. It's just one less thing to worry about in PRs etc and, in practice, any formatting changes from version updates have been rare enough not to become annoying. Plus running `cargo fmt --check` in CI means you catch them pretty much straight away anyway.

**Comment by bbangert** [comment]
I agree with @philbooth on this. I wish all languages had one, love or hate the results, at least its always consistent. There's been one or two times when rustfmt snuck in a change between versions, so it is good to ensure everyone uses the same rustfmt as the rust used on the project. ie, don't have some folks using the nightly rustfmt vs. stable.

**Comment by ncalexan** [comment]
> It seems fine in https://github.com/linacambridge/vellum, and in https://github.com/mozilla-services/syncstorage-rs. The style in much of mentat is also more idiosyncratic than in a-s.

Truth.

> I'd also be willing to accept slightly worse formatting for guaranteed consistency and to not have to think about it ever.

I'm 100% behind this.  Can we do this directory by directory, see how it feels?
