### ISSUE TITLE
Put Synced Tabs sidebar toggle into toolbar

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1575]
For the new Skyline FxA toolbar menu, we removed the button Sync Sidebar. Let's add it back to the Sync Tabs menu.

Ref https://github.com/mozilla/fxa/issues/2101.

---
🐞 Issue is synchronized with Bugzilla [Bug 1572212](https://bugzilla.mozilla.org/show_bug.cgi?id=1572212)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-268)
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
