### ISSUE TITLE
Crash in [@ nsUrlClassifierDBService::AsyncClassifyLocalWithFeatures]

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1580]
---
🐞 Issue is synchronized with Bugzilla [Bug 1572954](https://bugzilla.mozilla.org/show_bug.cgi?id=1572954)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-263)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: INVALID.
