### ISSUE TITLE
[Synced Tabs Sidebar] Firefox Nightly Fresh Profile cuts off icons from Synced Tabs sidebar

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1589]
Created attachment 9084011
Fresh profile synced tabs sidebar

On a Firefox Nightly fresh profile 

Steps to reproduce:
1. Create Fresh Profile 
2. Show Sidebar
3. Synced Tabs

This happens for both when the user has no account set up, and when the user has an unverified account. 

Results in: 

The Synced Tabs sidebar cuts of the icons. To see the full icon you'd have to expand the sidebar manually. I've added screen shots in the attachments section

---
🐞 Issue is synchronized with Bugzilla [Bug 1572439](https://bugzilla.mozilla.org/show_bug.cgi?id=1572439)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-275)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
