### ISSUE TITLE
Synced Tabs Sidebar buttons often lose their labels

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1592]
Created attachment 9084913
Screen Shot 2019-08-12 at 16.47.52.png

During a demo today, I observed that the button on the synced tabs sidebar was cut and unreadable.

See attached screenshots.

(note, I have not had time to replicate)

---
🐞 Issue is synchronized with Bugzilla [Bug 1573326](https://bugzilla.mozilla.org/show_bug.cgi?id=1573326)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-272)
┆Story Points: 3
┆Sprint: SYNC - 2019-09-13

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: DUPLICATE.
