### ISSUE TITLE
sync not working: Sign in button doesn't activate

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1599]
Created attachment 9085187
SignInSync.jpg

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

Steps to reproduce:

I uninstalled and reinstalled Firefox on my machine. 
I synced up the versions of Firefox on the two machines I am trying to share bookmarks from.
I have tried several different pathways to logging on. 

Actual results:

clicking the Sign in to Sync button, on page with 'Sign - in' button, no matter how many times I click, it does not work. Create an account also does not work. 

When I reinstalled and got a different login page, when I enter my credentials it gets stuck on loading and never finishes. 

Expected results:

It should log me in to my Firefox account so that I can sync my bookmarks from one machine to another.

The 'Sign-in' button should re-direct me to where I can enter my credentials.

---
🐞 Issue is synchronized with Bugzilla [Bug 1573618](https://bugzilla.mozilla.org/show_bug.cgi?id=1573618)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-140)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: INCOMPLETE.
