### ISSUE TITLE
Intermittent [TV] TEST-UNEXPECTED-TIMEOUT | services/sync/tests/unit/test_bookmark_engine.js | Test timed out

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1602]
**Filed by:** csabou [at] mozilla.com
**Parsed log:** https://treeherder.mozilla.org/logviewer.html#?job_id=261485001&repo=autoland
**Full log:** https://queue.taskcluster.net/v1/task/Fo2p-f0pSsGgATXLRygpMg/runs/0/artifacts/public/logs/live_backing.log
**Reftest URL:** https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://queue.taskcluster.net/v1/task/Fo2p-f0pSsGgATXLRygpMg/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1

---

[task 2019-08-14T01:41:18.746Z] 01:41:18     INFO -  TEST-START | services/sync/tests/unit/test_bookmark_engine.js
[task 2019-08-14T01:46:18.749Z] 01:46:18  WARNING -  TEST-UNEXPECTED-TIMEOUT | services/sync/tests/unit/test_bookmark_engine.js | Test timed out
[task 2019-08-14T01:46:18.753Z] 01:46:18     INFO -  TEST-INFO took 300000ms
[task 2019-08-14T01:46:18.754Z] 01:46:18     INFO -  >>>>>>>
[task 2019-08-14T01:46:18.755Z] 01:46:18     INFO -  PID 1021 | [1021, Main Thread] WARNING: Couldn't get the user appdata directory. Crash events may not be produced.: file /builds/worker/workspace/build/src/toolkit/crashreporter/nsExceptionHandler.cpp, line 2632
[task 2019-08-14T01:46:18.755Z] 01:46:18     INFO -  PID 1021 | [1021, Main Thread] WARNING: NS_ENSURE_SUCCESS(rv, kKnownEsrVersion) failed with result 0x80004002: file /builds/worker/workspace/build/src/toolkit/components/resistfingerprinting/nsRFPService.cpp, line 662
[task 2019-08-14T01:46:18.759Z] 01:46:18     INFO -  PID 1021 | [1021, Main Thread] WARNING: NS_ENSURE_SUCCESS(rv, rv) failed with result 0x80520012: file /builds/worker/workspace/build/src/extensions/permissions/nsPermissionManager.cpp, line 2901
[task 2019-08-14T01:46:18.760Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 3482: ReferenceError: reference to undefined property "process"
[task 2019-08-14T01:46:18.760Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 11041: ReferenceError: reference to undefined property "Object"
[task 2019-08-14T01:46:18.761Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 12088: ReferenceError: reference to undefined property "Buffer"
[task 2019-08-14T01:46:18.761Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 16620: TypeError: Symbol.toStringTag is read-only
[task 2019-08-14T01:46:18.761Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 16620: TypeError: Symbol.toStringTag is read-only
[task 2019-08-14T01:46:18.762Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 16620: TypeError: Symbol.toStringTag is read-only
[task 2019-08-14T01:46:18.762Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 16620: TypeError: Symbol.toStringTag is read-only
[task 2019-08-14T01:46:18.762Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 16620: TypeError: Symbol.toStringTag is read-only
[task 2019-08-14T01:46:18.762Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://testing-common/sinon-7.2.7.js, line 6247: ReferenceError: reference to undefined property "iso-8859-8-i"
[task 2019-08-14T01:46:18.763Z] 01:46:18     INFO -  PID 1021 | [1021, Main Thread] WARNING: No active window: file /builds/worker/workspace/build/src/js/xpconnect/src/XPCJSContext.cpp, line 664
[task 2019-08-14T01:46:18.763Z] 01:46:18     INFO -  PID 1021 | JavaScript strict warning: resource://services-sync/policies.js, line 183: ReferenceError: reference to undefined property "_globalScore"
[task 2019-08-14T01:46:18.763Z] 01:46:18     INFO -  (xpcshell/head.js) | test MAIN run_test pending (1)
[task 2019-08-14T01:46:18.764Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 0 pending (2)
[task 2019-08-14T01:46:18.764Z] 01:46:18     INFO -  (xpcshell/head.js) | test MAIN run_test finished (2)
[task 2019-08-14T01:46:18.764Z] 01:46:18     INFO -  running event loop
[task 2019-08-14T01:46:18.765Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "ReferenceError: reference to undefined property "process"" {file: "resource://testing-common/sinon-7.2.7.js" line: 3482}]"
[task 2019-08-14T01:46:18.765Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "ReferenceError: reference to undefined property "Object"" {file: "resource://testing-common/sinon-7.2.7.js" line: 11041}]"
[task 2019-08-14T01:46:18.766Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "ReferenceError: reference to undefined property "Buffer"" {file: "resource://testing-common/sinon-7.2.7.js" line: 12088}]"
[task 2019-08-14T01:46:18.766Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "TypeError: Symbol.toStringTag is read-only" {file: "resource://testing-common/sinon-7.2.7.js" line: 16620}]"
[task 2019-08-14T01:46:18.766Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "TypeError: Symbol.toStringTag is read-only" {file: "resource://testing-common/sinon-7.2.7.js" line: 16620}]"
[task 2019-08-14T01:46:18.767Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "TypeError: Symbol.toStringTag is read-only" {file: "resource://testing-common/sinon-7.2.7.js" line: 16620}]"
[task 2019-08-14T01:46:18.767Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "TypeError: Symbol.toStringTag is read-only" {file: "resource://testing-common/sinon-7.2.7.js" line: 16620}]"
[task 2019-08-14T01:46:18.767Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "TypeError: Symbol.toStringTag is read-only" {file: "resource://testing-common/sinon-7.2.7.js" line: 16620}]"
[task 2019-08-14T01:46:18.768Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "ReferenceError: reference to undefined property "iso-8859-8-i"" {file: "resource://testing-common/sinon-7.2.7.js" line: 6247}]"
[task 2019-08-14T01:46:18.768Z] 01:46:18     INFO -  "CONSOLE_MESSAGE: (warn) [JavaScript Warning: "ReferenceError: reference to undefined property "_globalScore"" {file: "resource://services-sync/policies.js" line: 183}]"
[task 2019-08-14T01:46:18.769Z] 01:46:18     INFO -  services/sync/tests/unit/test_bookmark_engine.js | Starting head_setup
[task 2019-08-14T01:46:18.769Z] 01:46:18     INFO -  (xpcshell/head.js) | test head_setup pending (2)
[task 2019-08-14T01:46:18.770Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 0 finished (2)
[task 2019-08-14T01:46:18.770Z] 01:46:18     INFO -  PID 1021 | 1565746891887	Sync.Engine.Addons	DEBUG	SyncEngine initialized: addons
[task 2019-08-14T01:46:18.775Z] 01:46:18     INFO -  PID 1021 | 1565746891888	Sync.AddonsReconciler	TRACE	Loading json from disk: addonsreconciler
[task 2019-08-14T01:46:18.776Z] 01:46:18     INFO -  PID 1021 | 1565746891889	Sync.AddonsReconciler	DEBUG	No data seen in loaded file: addonsreconciler
[task 2019-08-14T01:46:18.777Z] 01:46:18     INFO -  PID 1021 | 1565746891893	Sync.Engine.Forms	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.778Z] 01:46:18     INFO -  PID 1021 | 1565746891896	Sync.Engine.Forms	DEBUG	SyncEngine initialized: forms
[task 2019-08-14T01:46:18.780Z] 01:46:18     INFO -  PID 1021 | 1565746891903	Sync.Engine.History	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.782Z] 01:46:18     INFO -  PID 1021 | 1565746891905	Sync.Engine.History	DEBUG	SyncEngine initialized: history
[task 2019-08-14T01:46:18.783Z] 01:46:18     INFO -  PID 1021 | 1565746891910	Sync.Engine.Passwords	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.785Z] 01:46:18     INFO -  PID 1021 | 1565746891912	Sync.Engine.Passwords	DEBUG	SyncEngine initialized: passwords
[task 2019-08-14T01:46:18.787Z] 01:46:18     INFO -  PID 1021 | 1565746891916	Sync.Engine.Prefs	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.789Z] 01:46:18     INFO -  PID 1021 | 1565746891919	Sync.Engine.Prefs	DEBUG	SyncEngine initialized: prefs
[task 2019-08-14T01:46:18.790Z] 01:46:18     INFO -  PID 1021 | 1565746891923	Sync.Engine.Tabs	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.791Z] 01:46:18     INFO -  PID 1021 | 1565746891926	Sync.Engine.Tabs	DEBUG	SyncEngine initialized: tabs
[task 2019-08-14T01:46:18.792Z] 01:46:18     INFO -  PID 1021 | 1565746891927	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
[task 2019-08-14T01:46:18.794Z] 01:46:18     INFO -  PID 1021 | 1565746891930	Sync.Engine.Extension-Storage	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.795Z] 01:46:18     INFO -  PID 1021 | 1565746891932	Sync.Engine.Extension-Storage	DEBUG	SyncEngine initialized: extension-storage
[task 2019-08-14T01:46:18.797Z] 01:46:18     INFO -  PID 1021 | 1565746891934	Sync.Engine.Bookmarks	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.798Z] 01:46:18     INFO -  PID 1021 | 1565746891936	Sync.Engine.Bookmarks	DEBUG	SyncEngine initialized: bookmarks
[task 2019-08-14T01:46:18.800Z] 01:46:18     INFO -  PID 1021 | 1565746891936	Sync.Service	INFO	Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 /70.0a1
[task 2019-08-14T01:46:18.802Z] 01:46:18     INFO -  PID 1021 | 1565746899854	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
[task 2019-08-14T01:46:18.803Z] 01:46:18     INFO -  PID 1021 | 1565746899854	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
[task 2019-08-14T01:46:18.804Z] 01:46:18     INFO -  PID 1021 | 1565746899855	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
[task 2019-08-14T01:46:18.804Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 1 pending (2)
[task 2019-08-14T01:46:18.804Z] 01:46:18     INFO -  (xpcshell/head.js) | test head_setup finished (2)
[task 2019-08-14T01:46:18.804Z] 01:46:18     INFO -  PID 1021 | 1565746899860	Sync.SyncScheduler	TRACE	Handling weave:service:ready
[task 2019-08-14T01:46:18.804Z] 01:46:18     INFO -  services/sync/tests/unit/test_bookmark_engine.js | Starting setup
[task 2019-08-14T01:46:18.805Z] 01:46:18     INFO -  (xpcshell/head.js) | test setup pending (2)
[task 2019-08-14T01:46:18.806Z] 01:46:18     INFO -  PID 1021 | 1565746899862	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for [default]
[task 2019-08-14T01:46:18.815Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 1 finished (2)
[task 2019-08-14T01:46:18.816Z] 01:46:18     INFO -  PID 1021 | 1565746899872	Sync.CollectionKeyManager	INFO	Setting collection keys contents. Our last modified: 0, input modified: 1565746899.87.
[task 2019-08-14T01:46:18.817Z] 01:46:18     INFO -  PID 1021 | 1565746899872	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for [default]
[task 2019-08-14T01:46:18.818Z] 01:46:18     INFO -  PID 1021 | 1565746899873	Sync.CollectionKeyManager	INFO	Processing downloaded per-collection keys.
[task 2019-08-14T01:46:18.819Z] 01:46:18     INFO -  PID 1021 | 1565746899873	Sync.CollectionKeyManager	INFO	Clearing collection keys...
[task 2019-08-14T01:46:18.820Z] 01:46:18     INFO -  PID 1021 | 1565746899873	Sync.CollectionKeyManager	INFO	Saving downloaded keys.
[task 2019-08-14T01:46:18.822Z] 01:46:18     INFO -  PID 1021 | 1565746899874	Sync.CollectionKeyManager	INFO	Bumping last modified to 1565746899.87
[task 2019-08-14T01:46:18.822Z] 01:46:18     INFO -  PID 1021 | 1565746899874	Sync.Engine.Bookmarks.Tracker	TRACE	stop().
[task 2019-08-14T01:46:18.823Z] 01:46:18     INFO -  PID 1021 | 1565746899874	Sync.Engine.Bookmarks.Tracker	DEBUG	Not saving changedIDs.
[task 2019-08-14T01:46:18.824Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 2 pending (2)
[task 2019-08-14T01:46:18.825Z] 01:46:18     INFO -  (xpcshell/head.js) | test setup finished (2)
[task 2019-08-14T01:46:18.825Z] 01:46:18     INFO -  services/sync/tests/unit/test_bookmark_engine.js | Starting test_buffer_timeout
[task 2019-08-14T01:46:18.826Z] 01:46:18     INFO -  (xpcshell/head.js) | test test_buffer_timeout pending (2)
[task 2019-08-14T01:46:18.826Z] 01:46:18     INFO -  (xpcshell/head.js) | test run_next_test 2 finished (2)
[task 2019-08-14T01:46:18.827Z] 01:46:18     INFO -  PID 1021 | 1565746912528	Sqlite.ConnectionWrapper	INFO	Wrapping database: places.sqlite#0
[task 2019-08-14T01:46:18.828Z] 01:46:18     INFO -  PID 1021 | 1565746912529	Sqlite.Connection	INFO	places.sqlite#0: Opened
[task 2019-08-14T01:46:18.829Z] 01:46:18     INFO -  PID 1021 | 1565746912539	Sqlite.ConnectionCloner	INFO	Cloning database: /tmp/xpc-profile-FLWes7/places.sqlite (places.sqlite#1)
[task 2019-08-14T01:46:18.830Z] 01:46:18     INFO -  PID 1021 | 1565746912542	Sqlite.ConnectionCloner	INFO	Connection cloned
[task 2019-08-14T01:46:18.831Z] 01:46:18     INFO -  PID 1021 | 1565746912542	Sqlite.Connection	INFO	places.sqlite#1: Opened
[task 2019-08-14T01:46:18.832Z] 01:46:18     INFO -  PID 1021 | 1565746912550	Sync.Engine.Bookmarks	DEBUG	Engine constructed
[task 2019-08-14T01:46:18.832Z] 01:46:18     INFO -  PID 1021 | 1565746912552	Sync.Engine.Bookmarks	DEBUG	SyncEngine initialized: bookmarks
[task 2019-08-14T01:46:18.834Z] 01:46:18     INFO -  PID 1021 | 1565746912553	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for [default]
[task 2019-08-14T01:46:18.834Z] 01:46:18     INFO -  PID 1021 | 1565746912555	Sync.CollectionKeyManager	INFO	Setting collection keys contents. Our last modified: 1565746899.87, input modified: 1565746912.56.
[task 2019-08-14T01:46:18.836Z] 01:46:18     INFO -  PID 1021 | 1565746912555	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for [default]
[task 2019-08-14T01:46:18.838Z] 01:46:18     INFO -  PID 1021 | 1565746912555	Sync.CollectionKeyManager	INFO	Processing downloaded per-collection keys.
[task 2019-08-14T01:46:18.839Z] 01:46:18     INFO -  PID 1021 | 1565746912555	Sync.CollectionKeyManager	INFO	Clearing collection keys...
[task 2019-08-14T01:46:18.841Z] 01:46:18     INFO -  PID 1021 | 1565746912555	Sync.CollectionKeyManager	INFO	Saving downloaded keys.
[task 2019-08-14T01:46:18.842Z] 01:46:18     INFO -  PID 1021 | 1565746912556	Sync.CollectionKeyManager	INFO	Bumping last modified to 1565746912.56
[task 2019-08-14T01:46:18.844Z] 01:46:18     INFO -  PID 1021 | 1565746912557	Sync.Engine.Clients	DEBUG	Engine syncIDs: pfNbZxn9i00r,
[task 2019-08-14T01:46:18.845Z] 01:46:18     INFO -  PID 1021 | 1565746912564	Sync.Engine.Bookmarks	DEBUG	Assigned new sync ID 2XXOMgNf34gZ
[task 2019-08-14T01:46:18.846Z] 01:46:18     INFO -  PID 1021 | 1565746912564	Sync.Engine.Bookmarks	DEBUG	Engine syncIDs: 2XXOMgNf34gZ,
[task 2019-08-14T01:46:18.847Z] 01:46:18     INFO -  PID 1021 | [1021, Main Thread] WARNING: Workers don't support the 'mem.mem.' preference!: file /builds/worker/workspace/build/src/dom/workers/RuntimeService.cpp, line 544
[task 2019-08-14T01:46:18.847Z] 01:46:18     INFO -  PID 1021 | 1565746916273	Sync.Engine.Bookmarks.Mirror	INFO	Sync ID changed from  to 2XXOMgNf34gZ; resetting mirror
[task 2019-08-14T01:46:18.848Z] 01:46:18     INFO -  PID 1021 | 1565746919493	Sync.BrowserIDManager	INFO	Username changed. Removing stored credentials.
[task 2019-08-14T01:46:18.850Z] 01:46:18     INFO -  PID 1021 | 1565746919494	Sync.BrowserIDManager	INFO	Getting keys
[task 2019-08-14T01:46:18.851Z] 01:46:18     INFO -  PID 1021 | 1565746919495	Sync.BrowserIDManager	INFO	Getting an assertion from: http://token-server
[task 2019-08-14T01:46:18.852Z] 01:46:18     INFO -  PID 1021 | 1565746919495	Sync.BrowserIDManager	DEBUG	Getting a token
[task 2019-08-14T01:46:18.853Z] 01:46:18     INFO -  TEST-PASS | services/sync/tests/unit/test_bookmark_engine.js | test_buffer_timeout - [test_buffer_timeout : 214] "http://token-server" == "http://token-server"

---
🐞 Issue is synchronized with Bugzilla [Bug 1573739](https://bugzilla.mozilla.org/show_bug.cgi?id=1573739)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-281)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: INCOMPLETE.
