### ISSUE TITLE
The logins crate should use protobufs

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1605]
The following methods return their results as JSON because we `implement_into_ffi_by_json!(Login);`
https://github.com/mozilla/application-services/blob/fe9c866787898d40fae1294d218a211c0b8c0c15/components/logins/ffi/src/lib.rs#L166-L201

The work to do is [the same as what we've done on the Push crate](https://github.com/mozilla/application-services/issues/1491#issue-474206810), plus:

* Swift support ([example](https://github.com/mozilla/application-services/blob/4885cd11fcbacebaa707f7d78878ca15918b7c38/components/places/ios/Places/Places.swift#L331-L345))
* (Optional/Good follow-up) `sync15_passwords_add` also takes JSON as input! What if we could take protobuf as an input instead? We do this for the places crate in [Kotlin](https://github.com/mozilla/application-services/blob/4885cd11fcbacebaa707f7d78878ca15918b7c38/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L488-L495) and [Swift](https://github.com/mozilla/application-services/blob/4885cd11fcbacebaa707f7d78878ca15918b7c38/components/places/ios/Places/Places.swift#L777-L787).
* Finally `implement_into_ffi_by_json!(Login);` can be deleted.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-743)

**Comment by lyuyuan** [comment]
@linacambridge May I take this? I had a branch almost work but didn't pull request cuz I saw this was being used as a boarding issue. Is it still the case?

**Comment by vladikoff** [comment]
@lyuyuan I think there were a few attempts but no PR has been merged just yet
