### ISSUE TITLE
SyncTelemetryPing should cross the FFI as a protobuf

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1606]
It is currently returned as a JSON object string by the following methods:

* https://github.com/mozilla/application-services/blob/3f618a194d4d3984ecb428ef8b33335fe86fcdfd/components/places/ffi/src/lib.rs#L418
* https://github.com/mozilla/application-services/blob/3f618a194d4d3984ecb428ef8b33335fe86fcdfd/components/places/ffi/src/lib.rs#L441
* https://github.com/mozilla/application-services/blob/3f618a194d4d3984ecb428ef8b33335fe86fcdfd/components/logins/ffi/src/lib.rs#L91

Once it's done we can remove `implement_into_ffi_by_json!(SyncTelemetryPing);`. The work to do is more or less https://github.com/mozilla/application-services/issues/1491#issue-474206810.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-740)

**Comment by glasserc** [comment]
> On iOS they want this as a JSON string, which is why we did it this way. I don't think we should change.

Should this issue be closed?
