### ISSUE TITLE
[logins-api] Write and publish documentation for using Logins API

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#161]
I'm breaking this out of #113.  This includes providing the sample application (mostly done), writing onboarding documentation (not done, AFAIK), and then publishing the documentation as part of the build process the sub-tickets of #113 are tracking.  I don't think the Android Components folks have worked out the publication details yet, but they have set a precedent for [using the standard Dokka tool](https://github.com/Kotlin/dokka) -- see their repository.  Mentat is [publishing Javadoc](https://mozilla.github.io/mentat/apis/latest/java/index.html).

**Comment by thomcc** [comment]
I'm not sure we want to come up with our own solution for publishing documentation separately from android-components anymore. As such, it's not clear to me what we should do about this -- I'd be tempted to at least partially say we punt on it until we completely figure out the broader story around application-services vs android-components.

**Comment by rfk** [comment]
> I'm not sure we want to come up with our own solution for publishing documentation
> separately from android-components anymore.

That's fair; part of the rationale for moving the higher-level API into the android-components repo was to have all the docs in one place.

Where will be point the lockbox team to tell them out to install and use this API?  Perhaps we need to land some simple docs in the android-components repo alongside the wrapper API.

**Comment by ncalexan** [comment]
> Where will be point the lockbox team to tell them out to install and use this API? Perhaps we need to land some simple docs in the android-components repo alongside the wrapper API.

That makes sense to me.  The `a-c` team wants to maintain API uniformity and be that one-stop shop, so if we can sketch the outlines they can iterate on it there.

**Comment by thomcc** [comment]
https://github.com/mozilla-mobile/android-components/pull/798

**Comment by mhammond** [comment]
Thom's docs will do for now.
