### ISSUE TITLE
Synchronization makes Chaos

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1613]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Firefox for Android

Steps to reproduce:

Sorry about my english, im german!
I sorted all Bookmarks in many Folder. All Folder are in my Bookmark-Toolbar.
I use Firefox on Win 10, Linux Mint, iPhone and iPad.
Many Weeks without Problems

Actual results:

Since today i have all Folder in my Toolbar, and EACH Bookmark from all the Folder too. So i have hundreds of Bookmarks in my Toolbar.

Expected results:

Just my Folder without Bookmarks

---
🐞 Issue is synchronized with Bugzilla [Bug 1573982](https://bugzilla.mozilla.org/show_bug.cgi?id=1573982)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-144)

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1573982#a16497179_481559
