### ISSUE TITLE
Refactor session/account status handling

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1619]
We have strangeness around the "public" function `hasLocalSession()` and `sessionStatus()`. In particular, we want to end up in a place where:

* `sessionStatus()` is no longer a public function - the fact external callers might want this means our API is wrong. For example, if we see a 401 fetching an oauth token or (say) signing an assertion/certificate/whatever, then we should probably check the session status at that time.

* FxAccountsPush.jsm calls `sessionStatus()`, then drops some credentials and notifies observers of the account state change. This should be done whenever we notice the session is invalid, not just when push gets a password change notice.

* `hasLocalSession()` probably can remain as a public function, but with a new name - it's the canonical "are we in a 'needs reauth' state?" function.

---
🐞 Issue is synchronized with Bugzilla [Bug 1574051](https://bugzilla.mozilla.org/show_bug.cgi?id=1574051)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-298)
┆Story Points: 3

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
