### ISSUE TITLE
Consolidate "user account data" and "user profile data"

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1620]
Our current public FxA API exposes all low-level account data via `getSignedInUser()` and also profile information via `getSignedInUserProfile()`. We should consolidate these such that there's 1 function, and it (a) only returns data external consumers should see and (b) doesn't make a distinction between "account data" and "profile data")

---
🐞 Issue is synchronized with Bugzilla [Bug 1574052](https://bugzilla.mozilla.org/show_bug.cgi?id=1574052)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-297)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
