### ISSUE TITLE
Generate sphinx docs for the FxA public API.

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1621]
Once we have a better FxA API (bug 1565960) we should make sure it appears on https://firefox-source-docs.mozilla.org/

See also bug 1232403, making it difficult to solve this on windows, and markh also failed to get `./mach docs` working on Linux...

---
🐞 Issue is synchronized with Bugzilla [Bug 1574055](https://bugzilla.mozilla.org/show_bug.cgi?id=1574055)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-145)

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: WONTFIX.
