### ISSUE TITLE
[Meta] New bookmark sync

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1626]
This bug covers remaining work to flip the `services.sync.engine.bookmarks.buffer` pref to true, and have it ride to Release.

---
🐞 Issue is synchronized with Bugzilla [Bug 1433177](https://bugzilla.mozilla.org/show_bug.cgi?id=1433177)

┆Issue is synchronized with this [Jira Epic](https://jira.allizom.org/browse/SYNC-303)

**Comment by cse-test-sync** [comment]
➤ Lina Cambridge commented:

Weekly status for 9-13 September: working on SYNC-371 to make deletions more efficient (riding the 71 train), writing up a SHIELD pref flip study for Release 70. We'll keep an eye on telemetry and shutdown hangs, but don't anticipate any more uplifts.
