### ISSUE TITLE
[fxa-client] FxA Rust native libraries are being built against Android API 26

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#163]
As far as I can tell, the FxA rust native libraries that are being built for the `android-components` FxA client library are being built against Android API 26.  I've never been 100% clear on what the "NDK API version" really means, but I don't think we can expect these native libraries to run on Android API <26 devices.  `a-c` is setting `minSdkVersion` Android 21, AFAICT: https://github.com/mozilla-mobile/android-components/blob/c874c343cab18fe64f45ba8eb9a726f829fe06b9/build.gradle#L24.

In theory it's easy to change the Android NDK version -- we're taking the `ANDROID_NDK_API_VERSION` from the generic Rust + Android NDK Docker image defined at https://github.com/mozilla/mentat/blob/f8478835a2052a0857f1052105676747fdd2cc6e/automation/docker/generic/Dockerfile#L36, and we can change that.   (Or we can override it in our scripts, and ensure the requisite standalone toolchains are in place rather than getting them from the Docker image.)  But I'm having trouble building the native libraries against Android API 21 -- I get problems with `clang` and `--sysroot` arguments at link time.

**Comment by ncalexan** [comment]
@eoger can you explain why we're targeting API 26 with our standalone toolchains?  (This predates my changes to the toolchain installation; I kept the existing versions.)  Am I misunderstanding what the NDK version means, and it's not the minimum supported API?

**Comment by eoger** [comment]
I think this looks wrong to me:
https://github.com/mozilla/application-services/blob/04ee093657c89912549dd6f70462df869240ab96/libs/build-openssl-android.sh#L33
We should pass the desired API version instead of sending the NDK one.
I'm guessing we should also set that CFLAG around here:
https://github.com/mozilla/application-services/blob/04ee093657c89912549dd6f70462df869240ab96/scripts/taskcluster-android.sh#L39

**Comment by ncalexan** [comment]
> Am I misunderstanding what the NDK version means, and it's not the minimum supported API?

@snorp confirms that the version here is the minimum supported version.

**Comment by pocmo** [comment]
> a-c is setting minSdkVersion Android 21, AFAICT

That's correct. That's the lowest version we have to support in order to support Focus and Rocket. I'll push very hard for not going lower than that in every new app we are going to build (Currently 21+ covers [~86% of the Android market](https://developer.android.com/about/dashboards/)).

**Comment by ncalexan** [comment]
This was fixed by #170.
