### ISSUE TITLE
Carthage-compatible FxaClient.Framework build with Swift 4.2

### ISSUE THREAD

**Issue by sashei** [mozilla/application-services#164]
The current binary is compiled with Swift 4.1.2, which is fine for the most recent version of Xcode (9) but breaks when used with the Xcode 10 beta. Can we kick off a travis build with the newer version of Swift, both to get ahead of Xcode requirements and enable development in Lockbox against iOS 12?

**Comment by eoger** [comment]
Depends on https://github.com/travis-ci/travis-ci/issues/9730.
I can build manually on my laptop if you need it?

**Comment by sashei** [comment]
I think this is a good excuse to get this environment running on my machine! Might be back in slack with questions...

**Comment by eoger** [comment]
An xcode-10 version of the SDK [has been released](https://github.com/mozilla/application-services/releases/tag/0.2.1-xcode10).
Let's keep this issue open to remind us to add a XCode 10 target once travis provides images for it.
