### ISSUE TITLE
Provide a way to get a session token from an OAuth code exchange

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1669]
Doc for details: https://docs.google.com/document/d/1Q7xinEA3uXnUVobT5yaU7gXHcKK2Zj49nBrkUwHZVbg/edit

┆Issue is synchronized with this [Jira Epic](https://jira.allizom.org/browse/SYNC-326)
┆Story Points: 8
┆Sprint: SYNC - 2019-09-26
┆Attachments: <a href="https://jira.allizom.org/secure/attachment/10800/581c88c772877.jpg">581c88c772877.jpg</a>

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

2019-09-13: Work completed!
