### ISSUE TITLE
Browser support for opting out of sync during the Firefox signin flow

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1690]
As part of Bug 1570565, we will be adding signin flows to Firefox that result in the user being signed in to the browser, but do not enable sync. The current Firefox signin flow is triggered from the following URL:

  https://accounts.firefox.com/?service=sync&context=fx_desktop_v3

Which is, pretty clearly, specific to Sync. We will need to adjust the FxA authentication broker to allow signing in to the browser and enabling other services without enabling Sync and without requiring sync-specific messaging in the flow.

We're still working out some of the details, but I wanted to get this on file for the purposes of tracking the work. Next steps here are to confirm the designed UX for:

* The about:welcome signin flow, in which sync should be optional
* The about:protections signin flow, in which sync should not be mentioned at all

Once we understand the scope of the UX we'll be able to fill in the details of the underlying protocol. I'm pretty hopeful that it won't be a significant change, but don't want to get too far ahead of the UX here.

---
🐞 Issue is synchronized with Bugzilla [Bug 1577690](https://bugzilla.mozilla.org/show_bug.cgi?id=1577690)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-344)
┆Story Points: 5
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

waiting on https://github.com/mozilla/fxa/pull/2534 ( https://github.com/mozilla/fxa/pull/2534 )

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
