### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1699]
Created attachment 9089680
Index of file _C _Users_Wes_AppData_Roaming_Mozilla_Firefox_Profiles_zdskl5t6.default_weave_logs_.html

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

Actual results:

I have to manually sync Firefox every time I start it up. So, I sign my password in & wait for the link in my email. I have to request it to resend several times. When it finally appears in my inbox, I have to click within about 3 seconds before it disappears, or else I have to keep asking it to resend. Why does it disappear from my inbox? Where does it go? It's not in trash or spam.

Expected results:

Firefox ought to stay synced once and for all once I sign in.
The sync message in my email inbox ought to sit in there until I click on it. It should not just disappear within a couple of seconds.

---
🐞 Issue is synchronized with Bugzilla [Bug 1578034](https://bugzilla.mozilla.org/show_bug.cgi?id=1578034)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-165)

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1578034#a15021274_481559
