### ISSUE TITLE
Fix RUSTSEC-2019-0017

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1714]
See https://circleci.com/gh/mozilla/application-services/28982?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-357)

**Comment by eoger** [comment]
Already fixed by https://github.com/mozilla/application-services/pull/1713.

**Comment by vladikoff** [comment]
Yay!
