### ISSUE TITLE
[fxa-client] Statically link OpenSSL dependencies to avoid versioned SONAME entries

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#172]
This is the `a-s` version of https://github.com/mozilla-mobile/android-components/issues/569.

Right now, the `libfxa_client.so` produced in automation has ELF `DT_NEEDED` entries like
```
 0x00000001 (NEEDED)                     Shared library: [libssl.so.1.0.0]
```
That's the ELF `SONAME` from `libssl.so`.  Recent changes to the Android linker means that the `SONAME` and `NEEDED` entries must be correct for linking; locally, these all fail to work on Android 21 and 22.

It's not easy to change the `SONAME` with OpenSSL 1.0.2.  (It is easy as of OpenSSL 1.1.1, which isn't yet released.)  So this ticket tracks statically linking OpenSSL into `libfxa_client.so`, following Thom's model in #168.

**Comment by thomcc** [comment]
On top of #168 I think this would just be setting FxA to build with `OPENSSL_STATIC=1`
