### ISSUE TITLE
[fxa-client] Set `libfxa_client.so` SONAME

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#174]
Sigh.  [Rust doesn't set the ELF `SONAME`](https://github.com/rust-lang/cargo/issues/5045).  [Android's linker requires the SONAME be set](https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html).  I don't know how to address this yet.

**Comment by ncalexan** [comment]
This will be follow up to #170 and #172, after which the FxA client library should work on Android 21+.  Whew!

**Comment by thomcc** [comment]
I just checked and a `patchelf` built from https://github.com/NixOS/patchelf master can modify the soname (with `--set-soname`) and still be stripped afterwards. It's also a pretty simple build, since patchelf is just a single c++ file.
