### ISSUE TITLE
Add `action` param to non-webchannel pairing flow

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1740]
Currently it's present in every other kind of sign-in flow. Adding it in for pairing would help keep things consistent, and to ease the lives of consuming clients relying on `action`.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-374)
┆Story Points: 2
┆Sprint: SYNC - 2019-09-13

**Comment by grigoryk** [comment]
cc @vladikoff

**Comment by rfk** [comment]
I recall some discussion about whether it should be `action=pair` in this case, or one of the existing `action=signup|signin` values; what was the final conclusion on that front?

**Comment by grigoryk** [comment]
In a-c, we're expecting this to be `pairing`.

**Comment by vladikoff** [comment]
it ended up being `pairing`
