### ISSUE TITLE
[logins] Ability to sort by recently used and track usage

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1741]
![image](https://user-images.githubusercontent.com/128755/64568444-cc39bf80-d328-11e9-921a-06e99b05de66.png)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-177)

**Comment by vladikoff** [comment]
this is a "nice to have" for Fenix, if it is too hard to do then we should discuss

**Comment by rfk** [comment]
From mtg: "last used" will be inaccurate for synced records, because we don't sync it. But otherwise this should be OK to push the sorting logic down into the db.

I wonder if the hardest part here will be exposing an appropriate API surface.
