### ISSUE TITLE
Add Session Tokens to Fenix code exchange

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1742]
┆Issue is synchronized with this [Jira Task](https://jira.allizom.org/browse/SYNC-376)
┆Story Points: 3
┆Sprint: SYNC - 2019-10-11
┆Epic: Session Token OAuth Scope

**Comment by vladikoff** [comment]
this needs https://github.com/mozilla/application-services/issues/1669

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/application-services/pull/1759
