### ISSUE TITLE
Let users opt-out of sync when signin in to Firefox

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1743]
This is a mirror issue for https://github.com/mozilla/fxa/issues/2396 so that we can track it in our Jira board; please go to the above link for any discussion etc.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-377)
┆Story Points: 5
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by rfk** [comment]
> please go to the above link for any discussion etc.

As an experiment, I am locking conversation on this issue to help prevent fragmenting the discussion.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

this is now in review https://github.com/mozilla/fxa/pull/2534 ( https://github.com/mozilla/fxa/pull/2534 )

**Comment by vladikoff** [comment]
landed in https://github.com/mozilla/fxa/issues/2396
