### ISSUE TITLE
Define, instrument and measure Success Metrics for the logins component

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1749]
We want to understand whether users are achieving their goals around login management in the wild. Let's identify a small number of core success metrics that will help us understand that, figure out how to measure them, and then get them on a dashboard somewhere for review.

How is this different from the "Quality Metrics" requested in https://github.com/mozilla/application-services/issues/1748? The "Success Metrics" here should be more about whether users are getting value out of the Logins data type in our consuming apps. Are they saving and retrieving logins? Are they using them across devices? Things like that.

We may find that we can't track this effectively at the component level, or that it's better left to each individual consuming application. But let's give it a try.

We will probably need to work closely with the Lockwise team on this one...

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-182)
┆Story Points: 8
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-11-22

**Comment by rfk** [comment]
I figure the metrics we care about here will be almost entirely a subset of the metrics that Lockwise cares about from an app perspective. One place we could start here, is looking at the [telemetry events from Lockwise](https://github.com/mozilla-lockwise/lockwise-android/blob/f062807a5d1b8fdbb8b4c4f1ae6e7e1009820bf5/docs/metrics.md) for inspiration.

@eliserichards is there a top one or two metrics that Lockwise looks at to tell whether the application is being used successfully?

Most of the things I can think of here seem like vanity metrics, e.g. "number of passwords stored" or similar.

**Comment by eliserichards** [comment]
We aren't doing much analysis of the metrics that we have yet. Things I would _like_ to look at would be: 
- the number of autofill requests coming from each user per day/week/month
- the number of times a user opens Lockwise per day/week/month (e.g. to find/copy a password)

I'm not sure how hard it would be with our current metrics to match our telemetry events to a single user (guessing the UID work that landed recently would help with this).

**Comment by eliserichards** [comment]
Sandy's [Personal Data Protection Weekly Times](https://docs.google.com/document/d/1aGhBsh8ruMAuA1v6QtB-V4jMKThBBCS-j0lTcCN0YD0/edit) doc has some rough data in it: 

> Personal Data Protection Weekly Times: Lockwise & Monitor - Issue #12
> ...
> The Data (Measure)
> - Lockwise iOS # of credentials accessed: Last week we saw 35,433 credentials accessed on iOS; you can view the trend over time in our iOS credentials accessed dashboard(1).
> - Lockwise Android # of credentials accessed: Last week we saw 68,422 credentials accessed on Android. You can view the trend over time in our Android credentials accessed dashboard(2).

(1): https://sql.telemetry.mozilla.org/queries/60421#156010
(2): https://sql.telemetry.mozilla.org/queries/60796#156840

**Comment by rfk** [comment]
Some more graphs sourced from the Data Protection Weekly Times:

* [Count of Clients Taking Action (Desktop)](https://sql.telemetry.mozilla.org/queries/65125#165845)
* ["PWMGR 2019" Top-level Dashboard](https://sql.telemetry.mozilla.org/dashboard/pwmgr-2019), including things like:
  * saved passwords per client per week over time
  * % of clients with at least N logins saved

I'm quite liking the combination of three core usage metrics for a first attempt at this:

* count of saved logins
* distribution of timeLastUsed of saved logins
* number of reads of saved logins per time period
* number of writes of saved logins per time period

These seem to line up OK with metrics we already have on Desktop, which would make for a nice comparison. Next step here should be to try to make a "Logins Success Dashboard" from the data submitted by desktop, perhaps based on some of the queries linked above. That will give us a reference point for what we want the logins component dashboard to look like.

**Comment by rfk** [comment]
There are two different kinds of metric here, which might affect the details of how we gather them.

The read/write metrics are "event based" which I think we understand how to track in an abstract sense, by calling some `increment` function. But `count` and `timeLastUsed` are "snapshot" metrics that we would need to probe for explicitly. AFAICT desktop achieves this by [listening for a `gather-telemetry` notification](https://dxr.mozilla.org/mozilla-central/rev/9b2ebbf56577ec44c8c2304564bd003e1ccf0231/toolkit/components/passwordmgr/LoginManager.jsm#141), so perhaps we'll need to expose a `gather_telemetry` function of some sort that the application can call periodically.

**Comment by rfk** [comment]
> AFAICT desktop achieves this by listening for a gather-telemetry notification,

Looks like this mechanism is considered legacy and unreliable, ref https://bugzilla.mozilla.org/show_bug.cgi?id=1546443

**Comment by linacambridge** [comment]
Closing this bug because we've split it up into multiple sub-issues.
