### ISSUE TITLE
CWTS selection without any supported engines is just an empty screen

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1762]
Possibly related is #1761 (allowing application to disable CWTS selection entirely).

![image](https://user-images.githubusercontent.com/465422/64658790-91e62600-d3ed-11e9-914c-8c5d56e042a9.png)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-185)

**Comment by vladikoff** [comment]
What should it be? should we skip the screen in this case?

**Comment by jdragojevic** [comment]
@vladikoff @grigoryk  - is this something we want to worry about still?

**Comment by vladikoff** [comment]
We have since provided a way to send in a list of engines that an app supports. This can be deprioritized or closed

**Comment by vladikoff** [comment]
we have also added a `choose_what_to_sync: true` option for this, if it is set to `false` then the screen is skipped.
