### ISSUE TITLE
Form History Basic API/FFI

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1768]
Should support create/delete/touch/list/get by id/update/etc. Doesn't include querying, as that will have it's own issue. Much of this will just be the FFI work, as we'll probably do at some of the rust side of it when setting up storage.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-188)
┆Epic: Form Syncing Component

**Comment by thomcc** [comment]
See also: #1321
