### ISSUE TITLE
Form History Query support

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1769]
The API should offer relatively rich queries, as that's more or less the whole point of it.

A sketch of what this probably will look like is [https://github.com/mozilla/application-services/blob/ad379313ce652a3fe29f5825befc8457ad8582cb/components/forms/src/forms_msg_types.proto](https://github.com/mozilla/application-services/blob/ad379313ce652a3fe29f5825befc8457ad8582cb/components/forms/src/forms_msg_types.proto) -- It's heavily based on desktops, but it's also quite feature-complete, and unlikely to be missing anything other teams would want, unless new fields are needed.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-189)
┆Epic: Form Syncing Component

**Comment by thomcc** [comment]
See also: #1321
