### ISSUE TITLE
Form History Expiration

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1770]
Form history records must be periodically expired. More work investigating desktop's expiration algorithm needs to be done to know what's needed here. Additionally, probably should sync up with [~amedinac@mozilla.com] to figure out what product requirements there are here.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-190)
┆Epic: Form Syncing Component

**Comment by thomcc** [comment]
See also: #1321
