### ISSUE TITLE
Logins Component 1.0

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1773]
Reference: [Towards 1.0...](https://docs.google.com/document/d/1yAqztBjRnqQ6h9PdTVkYLqHxd9-h7MsgmmMPVXgVAPs/edit#heading=h.z4rq8bq8ims1) for a overview of why we want to do this work.

Logins component is already in production use providing user/pass storage and syncing for lockwise on mobile.  During Q4 2019 Fenix will also be implementing it for password management.  We want to set the bar for quality with this initial 1.0 versioning pass.

:white_check_mark: Component provides the basic functionality as requested by PM partner for initial implementation

:white_check_mark: Sufficient* rust unit-test coverage of the component

`(/) Features of the component are documented in the [application-services/components/logins/readme.md|https://github.com/mozilla/application-services/tree/master/components/logins]`

[ ] Entry for the component exists in the ecosystem-platform documentation-hub and links to the component readme for:

* [ ] feature documentation
* [ ] api documentation
* [ ] success metrics
* [ ] success dashboard links
* [ ] quality metrics
* [ ] quality dashboard links

:white_check_mark: Kotlin APIs are complete and demonstrated through an a-c sample app or integration with the reference browser

:white_check_mark: Kotlin integration tests coverage is sufficient and run as part of CI

:white_check_mark: Kotlin documentation in a-c repository is up-to-date and complete

:white_check_mark: Swift APIs are complete and demonstrated through ... (integration tests in a-s?)

[ ] Swift API integration tests coverage is sufficient and run as part of CI

[ ]  Swift documentation for iOS exists in ```application-services/``` ?

`[] Success metrics for the key features supported by the component have *dashboards* that are linked to the [application-services/components/logins/readme.md|https://github.com/mozilla/application-services/tree/master/components/logins]`

`[] Success metrics for the key features supported by the component *are defined* in the [application-services/components/logins/readme.md|https://github.com/mozilla/application-services/tree/master/components/logins]`

*sufficient as agreed to by the engineering team

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-191)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Initial entry for documentation hub and logins component readme are completed.  Next steps are to dive into the metrics for quality and success and decide what we want to be monitoring on the telemetry dashboards.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 18: On track.  Lina and Lougenia are going to work through the logins component as an onboarding project for Lougenia.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Oct 18: On track. Lina and Lougenia are going to work through the logins component as an onboarding project for Lougenia.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Dec 4: On track. Work on this is being folded into the validation of Migration quality for Fennec to Fenix migration.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Jan 6: Marking this complete as there are not open issues in the epic.  This was part of the 1.0 KR and we didn't complete everything as listed in the orginal description, and instead put it aside in favor of the Fenix migration work.  Intending to close since we are not likely to complete this in it's original form.
