### ISSUE TITLE
Stop using BrowserID for OAuth requests (to help the server emit accurate sync activity metrics)

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1795]
As described in Bug 1577690 Comment 7, we'd like to signal to the FxA backend whether or not the browser is using Sync.  The initial proposal was to send a `?service=sync` query param in requests to `/certificate/sign`, but from ensuing slack conversation I think there's a better way.

We eventually want to move away from BrowserID assertions, but can't boil that ocean all at once. What we can do is make it so that they're only used for sync.  Then the server can safely assume that any call to `/certificate/sign` is in service of something that's connected to sync  -- either an older browser for which being signed in means you're always syncing, or a new browser where the user has deliberately opted in to sync.  That will give us enough info on the backend to continue emitting appropriate metrics in the short term.

AFAICT there are only two other places in the browser where we make BrowserID assertions, and both of them can be changed not to do that:

* [This code](https://dxr.mozilla.org/mozilla-central/rev/d09edbe2abfec5298b39ab5b30d45bf20b8bbe33/services/fxaccounts/FxAccounts.jsm#1599) currently calls  [oauth.accounts.firefox.com/v1/authorization](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/api.md#post-v1authorization), but should instead call [api.accounts.firefox.com/v1/oauth/token](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#post-oauthtoken) using `grant_type=fxa-credentials`.
* [This code](https://dxr.mozilla.org/mozilla-central/rev/d09edbe2abfec5298b39ab5b30d45bf20b8bbe33/services/fxaccounts/FxAccounts.jsm#466) currently calls  [oauth.accounts.firefox.com/v1/authorization](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/api.md#post-v1authorization), but should instead call [api.accounts.firefox.com/v1/oauth/authorization](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#post-oauthauthorization).

We should do this as part of the decoupling work, to help FxA emit accurate sync activity metrics.

Shane, could you please gut-check whether this proposal makes sense?

---
🐞 Issue is synchronized with Bugzilla [Bug 1581709](https://bugzilla.mozilla.org/show_bug.cgi?id=1581709)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-418)
┆Story Points: 5
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

Waiting for FxA train 147 to be cut and released  https://github.com/mozilla/fxa/pull/2566 ( https://github.com/mozilla/fxa/pull/2566 )

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
