### ISSUE TITLE
Make places optional for the sync manager.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1798]
This will allow lockwise to use it. This wasn't done mainly because it very difficult to make the lifetimes work without copying the entire sync_manager::sync function, and lockwise is a ways off from being able to use the sync manager anyway (they need to migrate to the account manager first, which is a massive effort as it requires rewriting a lot of their code).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2399)
┆Epic: Important backlog

**Comment by rfk** [comment]
>  it very difficult to make the lifetimes work without copying the entire sync_manager::sync function,

I'd love to hear more about this, if you have the bandwidth to write a more detailed explainer in this issue for future reference.

**Comment by mhammond** [comment]
I think this is now the case in practice via our usage of `Arc<>`
