### ISSUE TITLE
Rethink how sync adapter exposes batch errors / failed records.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#18]
At the moment it's largely taken straight from desktop, but this seems error prone and less than ideal.

See https://github.com/mozilla/application-services/pull/12#discussion_r185409467 for some more context.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-201)

**Comment by mhammond** [comment]
I think the tl;dr of this is that posting a batch either works or it doesn't. Allowing some records to fail but have the batch succeed seems too vague to be useful without much tighter semantics (which can be added later if they actually appear in practice)

**Comment by jdragojevic** [comment]
Closing - sounds like not something we committed to doing.
