### ISSUE TITLE
[fxa-client] fxa_client_android.zip file contains unneeded files

### ISSUE THREAD

**Issue by csadilek** [mozilla/application-services#180]
Since 0.2.2, the fxa_client_android.zip file contains additional files and directories, which are not needed:

```
Cargo.toml
sdk
ffi
src
```

It used to only contain the .so files in the supported architectures dirs. Is there a reason these files were added? Can we remove them again? On the consuming side (android-components) we're not applying any specific filters (but could, of course).

**Comment by eoger** [comment]
We are building the Android libraries in a `fxa-client` folder, but since https://github.com/mozilla/application-services/commit/c23022ab966b3c23645cffdc544fa6def3d9d5b2 our source directory is also named `fxa-client`. Sorry about that, fix incoming :)
