### ISSUE TITLE
Figure out how to handle unsupported client commands

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#1800]
The clients engine currently writes any incoming commands that it doesn't understand back into our client record. @rfk pointed out in https://github.com/mozilla/application-services/pull/1504#issuecomment-531063811 that this sounds risky, and dropping those commands might be more prudent than applying them later.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2401)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864949

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
