### ISSUE TITLE
Many Sync notifications should be reworded to avoid the term "sync"

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1802]
As you verify an account, we show a notification with title "Sync Enabled" and body "Firefox will begin syncing momentarily." Because this is sent whenever the account is verified, talking about "sync" isn't going to be accurate once decoupling lands.

Ryan said he would try and get new copy.

---
🐞 Issue is synchronized with Bugzilla [Bug 1581980](https://bugzilla.mozilla.org/show_bug.cgi?id=1581980)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-425)
┆Story Points: 2
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

Updated both bugs with the new copy for the notifications: https://docs.google.com/document/d/1bU2SF1hrGxiaeyMD3pRJAiEfdZ8T4LIW3ZdZriM_WCw/edit?usp=sharing. ( https://docs.google.com/document/d/1bU2SF1hrGxiaeyMD3pRJAiEfdZ8T4LIW3ZdZriM_WCw/edit?usp=sharing )

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
