### ISSUE TITLE
"Device Connected" notification sent as another device connects should be reworded to avoid the term "sync"

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1805]
As another device connects to your account, all *other* devices already connected get a push notification with title "Firefox Sync" and body either "This computer is now syncing with {new-device-name}" (if the new device name is known) or "This computer is now syncing with a new device." (if no name is known). Because this is sent whenever a new device connects to the account, but not necessarily for sync, talking about "sync" isn't going to be accurate once decoupling lands.

Ryan said he would try and get new copy.

(similar, but subtly different to bug 1581980)

---
🐞 Issue is synchronized with Bugzilla [Bug 1581982](https://bugzilla.mozilla.org/show_bug.cgi?id=1581982)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-426)
┆Story Points: 1
┆Sprint: SYNC - 2019-10-11
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

Updated both bugs with the new copy for the notifications: https://docs.google.com/document/d/1bU2SF1hrGxiaeyMD3pRJAiEfdZ8T4LIW3ZdZriM_WCw/edit?usp=sharing. ( https://docs.google.com/document/d/1bU2SF1hrGxiaeyMD3pRJAiEfdZ8T4LIW3ZdZriM_WCw/edit?usp=sharing )

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: DUPLICATE.
