### ISSUE TITLE
Make sync optional in the about:welcome signin flow

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1810]
This is a spinoff from Bug 1577690, which is about landing changes to the Firefox sign-in flow that allow users to opt-out of syncing their data.

This new bug here, is specifically about changing about:welcome to use that new technology, so that users who sign in through our generic "join firefox" messaging have the option to do so without having to upload their (encrypted) browser data to our servers. 

We infer that users will find value in this option, because we currently observe a significant number of users who disable all sync engines when signing in to Firefox, which we take a a signal that they wanted to account but not the syncing.

The required change is pretty small from a code perspective, basically removing `service=sync` from the signin URL that is opened by about:welcome when we ask the user to sign in.  There's a WIP PR for it already here:

  https://github.com/mozilla/activity-stream/pull/5314/

But we should discuss the most appropriate way to roll this out.  :rfeeley suggested the possibility of an A/B test to confirm whether this changes user behavior during the onboarding flow, e.g. if we observe users opting out of sync instead of manually disabling all sync engines.

---
🐞 Issue is synchronized with Bugzilla [Bug 1582002](https://bugzilla.mozilla.org/show_bug.cgi?id=1582002)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-429)
┆Story Points: 3
┆Sprint: SYNC - 2019-10-24
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

waiting for review in https://github.com/mozilla/activity-stream/pull/5314 ( https://github.com/mozilla/activity-stream/pull/5314 )
