### ISSUE TITLE
Move WEAVE_CONFIGURED and FXA_CONFIGURED into the telemetry environment

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1817]
The fact these probes are recorded only once per session means it's not recorded in sub-sessions. See bug 1232050 comment 10 and bug 1236383 comment 11 for more context.

---
🐞 Issue is synchronized with Bugzilla [Bug 1238810](https://bugzilla.mozilla.org/show_bug.cgi?id=1238810)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-434)
┆Story Points: 3
┆Sprint: SYNC - 2019-11-08
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

10/21: Waiting on data review, person who can do it is on PTO till tomorrow.

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
