### ISSUE TITLE
Move 'devices' to the top-level of the sync ping

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1818]
Move the list of "Other devices" which the user is connected to from sync telemetry to the top (to become global), to be able to populate "Send Tab" telemetry. This is to make sure that once the decouple work is complete we are able to track send tab telemetry even when the user is not syncing.

---
🐞 Issue is synchronized with Bugzilla [Bug 1582263](https://bugzilla.mozilla.org/show_bug.cgi?id=1582263)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-437)
┆Story Points: 3
┆Sprint: SYNC - ends 2019-11-08
┆Epic: [Q3 2.3] Desktop Sync Decouple

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

10/21: Getting ready to land, and has one more fix.
