### ISSUE TITLE
8.51% build times (windows2012-32-shippable) regression on push 7438ce6ba80cc644ce4d6dd77c59d6c844b75e05 (Tue August 27 2019)

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1824]
We have detected a build metrics regression from push:

https://hg.mozilla.org/integration/autoland/pushloghtml?changeset=7438ce6ba80cc644ce4d6dd77c59d6c844b75e05

As author of one of the patches included in that push, we need your help to address this regression.

Regressions:

   9%  build times windows2012-32-shippable opt instrumented taskcluster-c5.4xlarge     1,618.83 -> 1,756.57

You can find links to graphs and comparison views for each of the above tests at: https://treeherder.mozilla.org/perf.html#/alerts?id=23132

On the page above you can see an alert for each affected platform as well as a link to a graph showing the history of scores for this test. There is also a link to a treeherder page showing the jobs in a pushlog format.

To learn more about the regressing test(s), please see: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Automated_Performance_Testing_and_Sheriffing/Build_Metrics

*** Please let us know your plans within 3 business days, or the offending patch(es) will be backed out! ***

---
🐞 Issue is synchronized with Bugzilla [Bug 1582399](https://bugzilla.mozilla.org/show_bug.cgi?id=1582399)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-442)

**Comment by eoger** [comment]
Turns out we didn't cause the regression.
