### ISSUE TITLE
`nss_sys` doesn't build on Linux

### ISSUE THREAD

**Issue by lyuyuan** [mozilla/application-services#1828]
Build command used:
`source libs/bootstrap-desktop.sh`
`cargo build`

OS:
Ubuntu 19.04
Linux kubuntu 5.0.0-27-generic

Error:
error: could not find native static library `intel-gcm-wrap_c_lib`, perhaps an -L flag is missing?
error: aborting due to previous error
error: Could not compile `nss_sys`.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-446)

**Comment by eoger** [comment]
Do you mind deleting `libs/desktop` and trying it again? If it still fails I'll try to reproduce tomorrow.

**Comment by lyuyuan** [comment]
> Do you mind deleting `libs/desktop` and trying it again?

This works. Thanks!
