### ISSUE TITLE
RustSyncManager doesn't appear to update m/g declined list

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1830]
After toggling engine states in my Fenix integration, it doesn't appear that `meta/global` is being updated with the new list. Other clients do not see this change. Sync Manager _does_ wipe the disabled collection, however.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-448)

**Comment by thomcc** [comment]
Further debugging showed that it actually does, can this be closed?

**Comment by grigoryk** [comment]
Or renamed, at least.

So after checking m/g record in about:sync, I see that we are updating the m/g, but changes aren't being merged correctly.

Here's me disabling "bookmarks" in Fenix, and then syncing in Desktop with disabled history:
```
1568968713105    Sync.Declined    DEBUG    Handling remote declined: ["forms","bookmarks"]
1568968713105    Sync.Declined    DEBUG    Handling local declined: ["history","forms"]
1568968713106    Sync.Declined    DEBUG    Declined changed? true
1568968713106    Sync.Service    DEBUG    Uploading meta/global: {"id":"global","payload":"{... stuff .... \"declined\":[\"history\",\"forms\"]}","modified":1568968660.43}
```

The final merged state seems to ignore the incoming disabled "bookmarks" engine.

Currently Fenix isn't mapping history engine to two collections ("history", "forms"), and _always_ passes in `enabledChanges` as not-null, so perhaps that's muddying up the waters here... I'll try fixing that first, and will report back.

**Comment by grigoryk** [comment]
Good news, with correctly behaving `enabledChanges`, I'm seeing a much better behaviour. Will close this issue, and will re-file if things don't get better once I map history to history+forms in Fenix.
