### ISSUE TITLE
RustSyncManager: does not generate an engine record in meta/global after enabling an engine

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1831]
Disabling engines in my current Fenix integration now works correctly - the missing bit of "magic" was making sure to map "history" to ["history", "forms"].

However, enabling them does not work correctly. A `declined` list is being uploaded correctly, but that's not enough - it seems like after enabling an engine, RustSyncManager does not generate a new syncID for the enabled engine, or at the very least it doesn't seem to update `meta/global` with it.

After enabling, say, bookmarks in Fenix, I don't see `bookmarks` in my `meta/global`.

Desktop and Fennec do not handle this behaviour well, and ignore Fenix's changes to `declined`, overwriting it with their own.

For example, here's desktop ignoring Fenix's attempt at enabling history engine by changing declined from `["history","forms"]` to `[]`, but not updating the `engines` list:
```
1568978424307	Sync.Declined	DEBUG	Handling remote declined: []
1568978424307	Sync.Declined	DEBUG	Handling local declined: ["history","forms"]
1568978424307	Sync.Declined	DEBUG	Declined changed? true
1568978424308	Sync.Service	DEBUG	Uploading meta/global: {"id":"global","payload":"{ ...., \"declined\":[\"history\",\"forms\"]}","modified":1568978324.42}
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-449)
┆Sprint: SYNC - 2019-09-26
┆Epic: [Q3 1.1] Sync Manager / CWTS

**Comment by thomcc** [comment]
This is fixed now.
