### ISSUE TITLE
Better manage multiple engines being behind one "choose what to sync" preference

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1832]
The current API does not handle History engine in the way our other clients treat it. Elsewhere, a History checkbox is sync prefs is treated as a combination of two collections: "history" and "forms", and both are affected when history sync pref is changed.

SyncManager currently doesn't handle this internally, and in a-c I needed to perform the mapping manually, which appears to work well (barring https://github.com/mozilla/application-services/issues/1831). It's not a lot of extra work, but this is exactly the kind of internal complexity that can be well-encapsulated behind SyncManager's API boundary.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2404)
┆Epic: Important backlog

**Comment by mhammond** [comment]
This seems likely to come up again with addons on mobile.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864950

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
