### ISSUE TITLE
New Bookmark popover keeps advertising/pushing Firefox Sync, again and again and again

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1841]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

Steps to reproduce:

Bookmark pages, close the intrusive and unwanted Firefox Sync advert ("synchronise your bookmarks everywhere" again and again.

Checked browser.syncPromoViewsLeftMap in about config. - its value is: {"addons":0,"bookmarks":0,"passwords":0}

Actual results:

It keeps coming back.

Expected results:

* There should be a global pref for "Disable Firefox Sync", that removes it from the main menu and context menus, and disables advertising for it entirely.
* Even without the above, if I close the advert, it should never appear again.

---
🐞 Issue is synchronized with Bugzilla [Bug 1583024](https://bugzilla.mozilla.org/show_bug.cgi?id=1583024)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-457)

**Comment by rfk** [comment]
This bug is for the Firefox Messaging System, not us; Lina moved it to the correct component in bugzilla but IIRC that won't close it here by default, so closing it here.
