### ISSUE TITLE
Unable to create a Firefox account with an email previously used as secondary email

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1845]
I tried to create a new Firefox account with an email that was used as secondary email in other Firefox account. I always get the error : "Primary account email required for sign-in". Removing the secondary email from that previous account does not change anything.

---
🐞 Issue is synchronized with Bugzilla [Bug 1583302](https://bugzilla.mozilla.org/show_bug.cgi?id=1583302)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-461)

**Comment by rfk** [comment]
Moved to FxA server component
