### ISSUE TITLE
Document versioning strategy in application-services repository

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1868]
Based on the discussion in [https://docs.google.com/document/d/1yAqztBjRnqQ6h9PdTVkYLqHxd9-h7MsgmmMPVXgVAPs/edit#heading=h.z4rq8bq8ims1](https://docs.google.com/document/d/1yAqztBjRnqQ6h9PdTVkYLqHxd9-h7MsgmmMPVXgVAPs/edit#heading=h.z4rq8bq8ims1) we need to capture our decision on the version strategy in the application-services repository readme.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-720)
┆Epic: Sync Maintainability Focus
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

I'm going to close this one.  We'll address with "better builds".
