### ISSUE TITLE
Refactor automation to use taskgraph

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/application-services#1874]
Releng has been rolling out `taskgraph` for other products already:
* Fenix
* reference-browser
* FFTV
* (in-progress) android-components

This ticket represents `taskgraph`-ing this project, too

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-227)

**Comment by rfk** [comment]
Just triaging some old bugs; @mitchhentges or @eoger is this still something we want to pursue?

**Comment by eoger** [comment]
This was done!
