### ISSUE TITLE
FFTV: user must explicitly click "Continue" for sign in success during email validation

### ISSUE THREAD

**Issue by mcomella** [mozilla/application-services#1875]
## Steps to reproduce
- Click FxA sign in
- Begin sign into an account **that requires email validation**. Complete email validation on another device then stop, taking no action on the Fire TV.

### Expected behavior
Device displays, "Login success" onboarding and internally saves the login success state.

### Actual behavior
User must manually click "Continue" before the device displays "Login success" onboarding and internally saves the login success state.

It seems unnecessary to me that the user is forced to click "Continue" because the UI updates when email validation completes on the remote device so the FFTV should be able to know the state on the server and avoid this unnecessary, additional step.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

---

Tracking downstream: https://github.com/mozilla-mobile/firefox-tv/issues/2899

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-228)

**Comment by vladikoff** [comment]
See response in https://github.com/mozilla-mobile/firefox-tv/issues/2899#issuecomment-535550535

**Comment by mcomella** [comment]
@vladikoff Is it possible to fix this based off the sign in client ID or user agent sniffing? If not, is this a WONTFIX?

**Comment by vladikoff** [comment]
@mcomella hm we can debug this with a custom user agent (send it Gecko for example) and see if will log you in. On phones with Chrome (as the default engine) we had to debug this and add a continue button.

**Comment by mcomella** [comment]
> @mcomella hm we can debug this with a custom user agent (send it Gecko for example) and see if will log you in. On phones with Chrome (as the default engine) we had to debug this and add a continue button.

Oh, I see – the issue here is that we're using Chromium and not Gecko.

I switched to the Firefox for Android user agent, `Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0` and login worked successfully without the "Continue" button.

@vladikoff Can we match against the FFTV client ID or user agent to remove this intermediate step?

**Comment by vladikoff** [comment]
> @vladikoff Can we match against the FFTV client ID or user agent to remove this intermediate step?

Hm sorry forgot to respond. Hm we could possibly do that. 
@shane-tomlinson what do you think about that?

**Comment by shane-tomlinson** [comment]
> > Hm sorry forgot to respond. Hm we could possibly do that.
> @shane-tomlinson what do you think about that?

Do we do this for all Chromium based UAs or just to ones that redirect to apps? I wonder if we could keep the current behavior by default but allow RPs to opt into skipping the cancel button via a query param, at least that'd avoid us needing to grow additional configuration.

**Comment by vladikoff** [comment]
query param works for me! 👍

**Comment by rfk** [comment]
I don't believe we're doing further work on the FireTV integration at this point, so I'm going to close this out. Please don't hesitate to re-open if it seems like something we should still address for other consumers.
