### ISSUE TITLE
Think about telemetry in the context of sync15-adapter

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#19]
This is still a large open question! It's not clear if we should implement part/all of the sync ping, or leave it to callers, possibly providing them with some data that they may want to include in telemetry.

**Comment by mhammond** [comment]
This is likely to involve more coupling between FxA and Sync than we'd like. While the tokenserver might give us a UID, we will want a device ID - and I can't believe telemetry is the only case where sync will want this kind of FxA state.

**Comment by mhammond** [comment]
fwiw, https://github.com/mhammond/application-services/tree/telem has some work towards this (although still no story for the deviceid :)

**Comment by mhammond** [comment]
https://docs.google.com/document/d/1k0VWVLk2Ao_MMoPgCDXyZR2pLj74SvHgSmo5yuUBJCo/edit#heading=h.7shvseu9mo2p has some details for how geckoview intends integrating with the containing app for telemetry. As much as possible, we should strive some something shaped similarly.

Also for completeness, see https://github.com/mozilla-mobile/android-components/tree/master/components/service/telemetry - which currently doesn't know about the sync ping, but it probably could and should.

**Comment by mhammond** [comment]
I think #490 and #524 both address the concerns here.
