### ISSUE TITLE
FxA thinks an out of office response is a returned email

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1907]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

Steps to reproduce:

I attempted to create a new account and put in my email address. As soon as the verification email was sent, the new account creation flagged the email address as being invalid because I had an out-of-office auto-reply turned on.  The account creation would not allow me to use that address.

Actual results:

I could not create a sync account.

Expected results:

It should have not assumed that the email was rejected and waited for the verification.

---
🐞 Issue is synchronized with Bugzilla [Bug 1585375](https://bugzilla.mozilla.org/show_bug.cgi?id=1585375)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-239)

**Comment by vladikoff** [comment]
This is a server issue for FxA
