### ISSUE TITLE
Attempt to upgrade to latest Android NDK

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1912]
We are using some sketchy version of the NDK right now , it puts our future at risk

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-505)
┆Story Points: 5
┆Sprint: SYNC - 2019-10-11

**Comment by thomcc** [comment]
https://github.com/mozilla/rust-android-gradle/pull/17/files
