### ISSUE TITLE
[Meta] New bookmark sync

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1914]
This bug covers remaining work to flip the `services.sync.engine.bookmarks.buffer` pref to true, and have it ride to Release.

---
🐞 Issue is synchronized with Bugzilla [Bug 1433177](https://bugzilla.mozilla.org/show_bug.cgi?id=1433177)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-240)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 10: A release process exception request has been submitted to enable a gradual rollout, both to keep an eye on telemetry, and reduce load on the Sync servers.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 18: On-track.  Gradual rollout is planned for the Fx70 release cycle.

**Comment by cse-test-sync** [comment]
➤ Lina Cambridge commented:

Rolled out to 50% of Release 70 users. Dashboard has queries specifically for release: https://sql.telemetry.mozilla.org/dashboard/new-bookmark-sync-desktop-
