### ISSUE TITLE
[meta] Sign-in to Firefox (follow-up)

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1921]
Follow-up work from https://bugzilla.mozilla.org/show_bug.cgi?id=1570565.  Ana M to elaborate.

---
🐞 Issue is synchronized with Bugzilla [Bug 1585724](https://bugzilla.mozilla.org/show_bug.cgi?id=1585724)

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-89)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

We're wrapping up the initial phase of work and will then finalize the scope of this effort for changes required in Fx72.

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 18: In planning, as planned.  Mark has some PRs (in review) that will continue on improvements of the Desktop FxA api that will enable relying parties to have a better time improving the sign-in integration.
