### ISSUE TITLE
Update OpenSSL dependency to 1.0.2p

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#193]
Noticed that we're not up to date today, 1.0.2p fixes two low severity issues, which AFAICT don't effect us, but it's probably worth staying on top of these https://www.openssl.org/news/vulnerabilities-1.0.2.html

**Comment by ncalexan** [comment]
I'd gently push to upgrade to 1.1.*, with the hope being that we could get off of Android NDK r15c (and the `--disabled-headers` noise that entails).

**Comment by thomcc** [comment]
This is now somewhat more important due to the version of OpenSSL we use being vulnerable to portsmash (fixed in 1.0.2q / 1.1.0h).

IIUC ARM chips (our main target) don't do any SMT/hyperthreading so we should be mostly fine, but we should probably update this.
