### ISSUE TITLE
Bookmarks checkbox is highlighted in sync preferences dialog

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1948]
Created attachment 9099835
Bookmarks highlighted.jpg

[Affected versions]:
Firefox 71.0a1 (2019-10-08)

[Affected platforms]:
MAC OS X 10.14.6

[Steps to reproduce]:
1.Launch Firefox and login using a Firefox Account.
2.Navigate to about:preferences#sync
3.Click on “Change...” button from sync preferences list.

[Expected Results]:
All preferences checkboxes look the same.

[Actual Results]:
Bookmarks checkbox is highlighted. The blue square doesn't disappear when the checkbox is unchecked or the focus is moved to another sync preference. 

[Additional Notes]:
- This issue is not reproducible on Windows 10 x64.
- I am attaching a screenshot.

---
🐞 Issue is synchronized with Bugzilla [Bug 1587363](https://bugzilla.mozilla.org/show_bug.cgi?id=1587363)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-535)
┆Story Points: 3

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Removing this from the Fx71 version and sync decouple epic.  I added a video to the bugzilla bug that shows the same behavior on other preferences tabs.

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: INVALID.
