### ISSUE TITLE
Investigate the size of Logins AAR

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#195]
![image](https://user-images.githubusercontent.com/128755/44862362-898ad500-ac48-11e8-9070-d418935039c5.png)

From Slack:

```
tcsc: this has to be compiling bitcode or something
after unzipping each arch's so file is over 100MB
```

**Comment by ncalexan** [comment]
They're so large because they include debug symbols.  Per https://github.com/mozilla/application-services/blob/d14c42787849d407c3e12c9d5af5d1c8bff43763/logins-api/android/library/build.gradle#L26-L31, it's my belief that consumers (samples, Notes, etc) should be the ones to strip the symbols.

**Comment by thomcc** [comment]
Ah, yeah, we already determined this but didn't get around to closing the issue, whoops!
