### ISSUE TITLE
Support for secure proxy sign-in on mobile

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1956]
# OKR
**What?** Help mobile integrate Secure Proxy such that it works with FxA
**Why?** Ensure users can use Secure Proxy with their FxA
**When?** Q4

# Background
Android components has a requirement to require an account in order to use secure proxy on Fenix.  [https://github.com/mozilla-mobile/fenix/issues/5750](https://github.com/mozilla-mobile/fenix/issues/5750)

Similar to the ongoing work to improve the sign-in to firefox experience we want to make necessary changes to enable a smooth flow for mobile proxy users on android.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-61)

**Comment by cse-test-sync** [comment]
➤ Janet Dragojevic commented:

Oct 10: Vlad is going to connect with PMs for Fenix and Proxy to make sure there's a good understanding of the 'decouple' work that's been done on desktop so far and get to a shared understanding of how the proxy mobile sign-in requirement should work to assure a good user experience and consistency with desktop.

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

Nov 14: We are in a bit of a blocker for deploying the required session scope functionality for FPN. We are blocked on the firefox 71 to be released in December 4th. This blocker doesn't affect any deadlines or schedules, mostly just testing in Firefox Desktop "Release". Otherwise no work required from a-s at this time.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

2019-12-16: Completed! Last change required for the Fenix team is done.  We're collaborating with the Secure Proxy PM to identify and future follow-up work for 2020.
