### ISSUE TITLE
This is not a bug but a request to merge my two Firefox accounts.

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1962]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

Steps to reproduce:

Send an email to Kiki and asked her to merge my two Firefox accounts  -  one of them I haven't used since  April 2018.

Actual results:

Kiki  told me to file a bug report ....

Expected results:

I was hoping that an administrator could have merged the two accounts without me having to file a bug report.

---
🐞 Issue is synchronized with Bugzilla [Bug 1586850](https://bugzilla.mozilla.org/show_bug.cgi?id=1586850)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-547)

**Comment by rfk** [comment]
Moved to a non-FxA bugzilla component, so closing here.
