### ISSUE TITLE
API to delete all bookmarks

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1968]
Currently there's no convenient API exposed to remove all bookmarks, without affecting history.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-551)

**Comment by linacambridge** [comment]
We added [`stroage::bookmarks::erase_everything`](https://github.com/mozilla/application-services/blob/f0f06955ba20a1210cfbab258fb82fd8703c9afe/components/places/src/storage/bookmarks.rs#L1074) for the sync manager, but didn't expose it over FFI.
