### ISSUE TITLE
API to generate scoped refresh tokens

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1981]
For upcoming integrations with services that want to manage lifecycle of their own access tokens (e.g. Secure Proxy), we need an API to issue scoped refresh tokens.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-558)

**Comment by rfk** [comment]
With apologies for chiming in late, I have a bad feeling about this plan - it goes against the grain of OAuth's data model in a kind of ad-hoc way, which I think will make the resulting system hard to reason about.

Could we achieve a similar affect by adding the ability to grant OAuth codes, similar to [this method in desktop's FxA code](https://dxr.mozilla.org/mozilla-central/rev/f2644bf19c9ff6acb2182f2ac44b0df46c967cda/services/fxaccounts/FxAccounts.jsm#481)?

**Comment by vladikoff** [comment]
closed in favour of https://github.com/mozilla/application-services/issues/2001
