### ISSUE TITLE
logins: Provide an API to know if a given login will duplicate an existing stored one

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/application-services#1983]
Lockwise would like to update UI live as the user types in a create/edit form to indicate if the resulting login would be a duplicate of one already saved and therefore saving should be prevented (see #617).

This is similar to how the Fx desktop password manager doorhanger works. With every edit to the username field it decides whether the primary action should be to Save or Update depending on what is already in storage and the username field in the doorhanger.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-56)
┆Story Points: 0
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-11-22

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

PR: https://github.com/mozilla/application-services/pull/2101
