### ISSUE TITLE
logins: Make username property not nullable

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/application-services#1985]
There isn't currently a meaningful distinction between `null` and `""` usernames but toolkit has always had the username as a non-null string and that simplifies working with the property as you don't have to handle the null case (Elise confirmed this is annoying for Lockwise on Android). I have also seen `null` usernames propagate to the sync server even though IIUC that isn't supposed to happen, and at least desktop doesn't handle it properly.

Until we need a distinction between `null` and `""`, I think we're just causing more problems for ourselves by exposing `null` (though I'm mostly using JS so maybe that's not so clear with Swift or Kotlin?).

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-54)

**Comment by glasserc** [comment]
Could I please have some guidance about how to approach this issue?

1. What exactly are the `null` usernames at issue here? It seems like the `Login` struct's `username` is not nullable. I'm guessing this is about the `username` column in `loginL` and `loginM` in `schema.rs`?
2. I guess I will have to write a migration to add a `NOT NULL` constraint? It seems like the way to do that is the 12-step process in https://www.sqlite.org/lang_altertable.html ?

**Comment by mnoorenberghe** [comment]
@thomcc or @rfk can help with that. https://bugzilla.mozilla.org/show_bug.cgi?id=1588948 is the bug on the Firefox side to workaround records with no username. Maybe the problem is that records can be serialized without a username?

**Comment by thomcc** [comment]
@glasserc It's actually about the serialization, e.g. https://github.com/mozilla/application-services/blob/master/components/logins/src/login.rs#L31

It might be enough to just remove that, but we should make sure nothing else has problems as a result. Additionally, that qualifier is in several places, and we should check to see if the others need removing as well.

**Comment by glasserc** [comment]
@thomcc On the subject of "nothing else has problems", I see that the `ServerPassword` type in Kotlin has these fields as nullable. Should I try to carry through the same change at this layer? Would this be an API-breaking change, and is that OK?

**Comment by rfk** [comment]
> Should I try to carry through the same change at this layer?

If you're happy to, please do!

> Would this be an API-breaking change, and is that OK?

Yes, but it's OK, we have plenty of those and it's manageable with a small number of consumers. Please make sure to note it as such in the changelog entry.
