### ISSUE TITLE
Figure out how FPN can work with fxa-client component and Fenix

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1986]
Do we need to use prompt=none for that client or something else? 

A combination of the session token scope, webchannels and more?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-563)
┆Story Points: 5
┆Sprint: SYNC - 2019-10-24
┆Epic: Support Secure Proxy for Mobile

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

10/21: Almost done, finishing up the prototype w/ A-C

**Comment by colintheshots** [comment]
We have a plan documented here for this integration: https://docs.google.com/document/d/1E35Tz0fH2bCr8DBK1dLJEkTV8SAVY5-tF2WdVm1ml7M/edit?pli=1#heading=h.ssp0l1kcaqmt
