### ISSUE TITLE
[logins] API to rekey the database

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1988]
There's a good chance Fenix will ship logins storage with keys that we'd want to change once secure storage story is figured out, and we'd need to rekey the database file. This issue is about exposing a method that will call `pragma rekey=newkey`.

https://www.zetetic.net/sqlcipher/sqlcipher-api/#Changing_Key

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-53)
┆Story Points: 3
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-12-20

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

PR for review is in: https://github.com/mozilla/application-services/pull/2228 ( https://github.com/mozilla/application-services/pull/2228 )
