### ISSUE TITLE
Consider migration strategies for "pinned" sites

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1989]
In Fennec, we have a notion of "pinned" sites, that are displayed in front of any auto-generated Top Sites. We store these as bookmarks, children of a "special" folder with guid="pinned" and _id=-3.

We have couple of options for migrating these:
- drop them on the floor (this appears to be the current behaviour)
- return them from the `importFromFennec` function, letting Fenix migration code deal with them in whatever way is appropriate
- retain them in a "Pinned" folder

I think if we do nothing else, retaining "pinned" sites in a folder is bare minimum. It won't be a great experience, but at least pinned sites will still be accessible to users via Fenix's bookmarks UI.

If migration code returns pinned sites, we can generate a "Pinned sites" collection to be displayed on the home page, which is sort of similar to how Fennec's pinned sites behaved.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-566)
┆Story Points: 3
┆Epic: Places Component version 1.0

**Comment by jdragojevic** [comment]
@grigoryk  - is there a relationship between migrating pinned Fennec sites and the future idea of syncing _pinned tabs_ from Desktop into containers as described here: https://github.com/mozilla-mobile/fenix/issues/4446 and would it make sense to have product consider some consistent behavior?

**Comment by grigoryk** [comment]
No relationship. This ticket is about avoiding data loss (retaining "pinned" sites from Fennec in some form) during the migration. What David filed is about making desktop's "pinned" tabs somehow accessible in Fenix, which is a different but related concept.
