### ISSUE TITLE
Add fxa-rust-client

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2]
@eoger could we pull in the fxa-rust-client into here?

**Comment by vladikoff** [comment]
See example https://github.com/mozilla/application-services/pull/1

**Comment by eoger** [comment]
The repo is still at the point where I `git push --force` on a regular basis and has no tests yet.
I'd like the project to mature a little bit before moving it here.

**Comment by vladikoff** [comment]
> The repo is still at the point where I git push --force on a regular basis and has no tests yet.
I'd like the project to mature a little bit before moving it here.


Okay I will take it as a decline to collab / review at this time, which is fine. We can revisit it later...
