### ISSUE TITLE
Sync adapter needs to save it's state

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#20]
At the moment it is entirely in-memory. We probably want to leave actually persisting the state to the library user, but give them a JSON string to save (More granular updates may be necessary in the future but ATM it doesn't seem worth it).

At a minimum it should be saving: syncID (and version?) for each collection (this comes from meta/global), lastSync timestamp for each collection (which is a remote timestamp), and probably more?

Is there anything from the token we need to save? (I think the answer is no?)

**Comment by rfk** [comment]
> Is there anything from the token we need to save? 

You'll need to remember the uid and/or api_endpoint, because if these change then the other state must be discarded.  But I don't think the actual token credentials need to be persisted.

**Comment by mhammond** [comment]
I don't think desktop saves any of this state and relies on the storage syncIds to know to throw stuff away
