### ISSUE TITLE
Firefox Sync advertisement keeps coming back

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2004]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

In various parts of its UI (in particular the "add bookmark" menu, but also at least once the hamburger menu), Firefox likes to show advertisement for it Sync feature. Informing me about that feature once is okay, of course, but I have now had to click the "x" button in that advertisement at least 3 times -- I am just not interested in Sync, and the application should respect my choice.

Steps:
- Firefox showed Sync advertisement somewhere ("new version installed" information or "new bookmark" menu or hamburger menu, possibly other places).
- I discarded that advertisement with the "x".

Actual results:

Some time later, Firefox showed that (or a similar) advertisement again.

Expected results:

Firefox should respect my choice to not use Sync, and stop bothering me with it. In particular there is no excuse for showing the advertisement in the "new bookmark" menu at least 3 times, after I removed it with an "x" twice (and just ignored it by not interacting with it on a few more occasions).

---
🐞 Issue is synchronized with Bugzilla [Bug 1588768](https://bugzilla.mozilla.org/show_bug.cgi?id=1588768)

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-576)

**Comment by linacambridge** [comment]
Moved over to the Messaging System component on Bugzilla.
