### ISSUE TITLE
Provide a way for the tabs engine to access the client list

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2006]
The `tabs` collection uses `clients` IDs to identify records, and show the device name and type in the UI. Currently, the clients engine keeps this list in memory during a clients sync, and doesn't expose it at all. However, we'll need to expose this for synced tabs, so that we can match tabs to devices.

Our `sync_multiple` function manages the clients engine when it syncs the list of stores. We can add a method to `Store` that takes a `clients::Engine` (or a list of clients), so that tabs can access it. We'll also need to expose the list on the engine itself.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-46)
┆Story Points: 3
┆Epic: Syncing Tabs
┆Sprint: SYNC - end 2019-11-22

**Comment by eoger** [comment]
Note that we could also simply fetch the clients collection from the sync15 crate, since it's guaranteed that it'll be synced when we start syncing.

**Comment by linacambridge** [comment]
Yep, that's what this bug is about! We fetch the `clients` collection [here](https://github.com/mozilla/application-services/blob/08ec3d4e5b660e4ec4055f194f335a7dc344303b/components/sync15/src/clients/engine.rs#L218), but it's not exposed to anyone—we don't store it on `self.engine` or anything, it's only available in that function. So we'll want to expose that list.

But then, there's no `Weave.Service.clientsEngine` or anything that our tabs component can use to get a reference to that list. (We could use the sync manager for that, but the way it's integrated is convoluted—`sync_manager` depends on `sync15`, `logins`, and `places`; our `tabs` component couldn't depend on it). That's why I was thinking we could pass the clients engine as an argument when we sync a store, maybe to the [`apply_incoming` method](https://github.com/mozilla/application-services/blob/433e00ae8d477d9de85182b979a90ff6f8baa703/components/sync15/src/sync.rs#L24).

Originally, I was thinking that not every store would need an extra `engine: &clients::Engine` argument. But, thinking more about it, maybe it _does_ make sense. The tabs engine would use it to get the clients list, so it could map devices. Bookmarks, history, and logins could use it to handle `Wipe` and `Reset` commands—those are currently handled in the Sync Manager, but there's no reason we can't push this logic down into Places and the logins component.

So maybe we change `apply_incoming` to take a [`clients::Engine`](https://github.com/mozilla/application-services/blob/08ec3d4e5b660e4ec4055f194f335a7dc344303b/components/sync15/src/sync_multiple.rs#L223-L229), after all.

WDYT?
