### ISSUE TITLE
Implement a synced tabs store

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2007]
The store:

* Is purely in-memory; we won't persist synced tabs. (But we _can_ cache them, so that Fenix can show the last synced list of tabs, while it refreshes them in the background. We can follow the same pattern that we use for FxA devices).
* Will take a full list of all open tabs. (No deltas or "tab open"/"tab closed" events. We can do that in a follow-up).
* Will provide a method to fetch all tabs open on other devices.
* Will sync with the `tabs` collection, using the client IDs.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-579)
┆Story Points: 5
┆Sprint: SYNC - 2019-11-08
┆Epic: Syncing Tabs

**Comment by eoger** [comment]
Fixed by https://github.com/mozilla/application-services/commit/19e4cef424e1a28deb72d02b3465f2b3b23c6eaa.
