### ISSUE TITLE
Mirror bugs with [SACI] whiteboard tag into Jira

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2010]
We should use `SACI` in the whiteboard field for mirroring - since it corresponds to the Jira project id.

Acceptance criteria:

1. Update sync_bugzilla_to_github.py to include issues with SACI in the whiteboard field
2. Update team mana page to indicate it's part of the bugzilla mirroring criteria.

[original description edited by janet 2020-03-23]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-725)
┆Sprint: Backlog

**Comment by jdragojevic** [comment]
This is resolved - evidenced by https://jira.mozilla.com/browse/SYNC-962 and mana page has been updated.
