### ISSUE TITLE
Remove `service=sync` from account management links in the browser

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2025]
When the browser wants to link out to FxA management pages on the web, it currently includes `?service=sync&context=fx_desktop_v3` query parameters, like so:

  https://accounts.firefox.com/settings?service=sync&context=fx_desktop_v3

The presence of these query parameters causes accounts.firefox.com to send an `fxa_status` webchannel message to the browser to interrogate its login state, and the browser can choose whether to reply with the credentials of the signed-in user.

Now that it's possible to sign in to the browser without enabling sync, it doesn't really make sense to include `service=sync` in those links, and its presence there risks muddying FxA server-side metrics. Let's update these links to just include `context`, like so:

  https://accounts.firefox.com/settings?context=fx_desktop_v3

This will involve:

* Changing FxA web content to include `context` in the `fxa_status` webchannel message, alongside `service` and `isPairing`.
* Ensuring that this `context` value is properly accounted for when the browser decides whether to respond to the `fxa_status` message.
* Removing `sync` from the list of default params appended to outgoing FxA links.

---
🐞 Issue is synchronized with Bugzilla [Bug 1590946](https://bugzilla.mozilla.org/show_bug.cgi?id=1590946)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-35)

**Comment by vladikoff** [comment]
This will be blocked by https://github.com/mozilla/fxa/pull/4179 going into production

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
