### ISSUE TITLE
Implement extension storage and sync on top of generic sync

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#2034]
Once we have a generic sync system, we need to replace the existing chrome.storage.sync implementation with a version that uses the generic sync system. This should be relatively straightforward, with the most difficult part likely being migration of the existing data.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-27)
┆Story Points: 3
┆Epic: Firefox nightly extension storage

**Comment by jdragojevic** [comment]
closing - will add a more detailed ticket in jira.
