### ISSUE TITLE
Implement sync with 1.5 crate

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#2036]
Remerge component syncing with sync15 crate.

* Implementing the algorithm/algorithms for sync and conflict resolution described in the remerge spec.

Acceptance criteria:

* remerge syncs collections between devices

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-25)
┆Story Points: 5
┆Epic: chrome.sync.storage (Generic Sync) prototype
┆Sprint: SYNC - end 2020-03-13

**Comment by linacambridge** [comment]
Rolling PR here: https://github.com/mozilla/application-services/pull/2475

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Algorithms for sync and conflict resolution were implemented in the [remerge sync|https://github.com/mozilla/application-services/tree/remerge-sync) ( https://github.com/mozilla/application-services/tree/remerge-sync) ) branch.  We've decided to hold back on merging the entire body of work into a-s repo for now and instead intend to take only the subset of work required to support extension preference syncing.  That is capture in Sync-903.  Marking this a done.
