### ISSUE TITLE
In Push Component, return `scope` as part of the decrypt() JSON response

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#2045]
According to 
<img width="632" alt="Screen Shot 2019-10-25 at 1 19 27 PM" src="https://user-images.githubusercontent.com/35755/67591521-796a6a80-f712-11e9-9789-c32841dae3a9.png">

It's my understanding that since Scope is an identifier for service worker, (and since Push Component is not doing Delivery), decrypt should include the previously registered `scope` string as part of the response JSON. (Scope is a parameter of `subscribe`. 

@jonalmeida can provide additional details if needed.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-17)

**Comment by jrconlin** [comment]
A CHID is basically how to determine the recipient of a push message on a given device. If you're fine with one recipient for *all* GeckoView push messages and use some other mechanism (e.g. an identifier in the body of the push message) then you shouldn't need scopes. Complicating things is that "scope" isn't contained in the received Push Message, since it's not provided to the Push server and encoded into the endpoint, nor is the endpoint provided to the `decrypt` function. 

So possible solutions might include:

1) GeckoView creating a new subscription (new channelid + scope) per scope, in which case scope can be returned as part of the decrypt (this bug would cover a future PR to return a scope associated with a ChannelID as part of the `decrypt` response, who's return would also change.

2) GeckoView providing scope as part of the subscription info block to the subscription provider which would encode scope in the push message content

3) scope is incorporated into the endpoint information which may violate some privacy considerations and require work on the autopush server and push component.

**Comment by jrconlin** [comment]
Digging around the code for `PushManager`, I found `PushManager.dispatchInfoForChid` which returns `DispatchInfo{ uaid: String, scope: String}`

This might be what you're looking for.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

endofyear cleanup: is this still an issue that needs to be addressed?

**Comment by jonalmeida** [comment]
No, I think we have what we need. Thanks Janet!
