### ISSUE TITLE
Push Component missing `appServerKey` field

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#2046]
The [`appServerKey`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebPushSubscription.html#appServerKey) is an `Option<String>` that should be passed as part of the new subscription request (via `Connection.subscribe()` as part of the JSON body as field `key`.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-16)

**Comment by jrconlin** [comment]
Updated description to indicate field name should be `key`.

**Comment by jonalmeida** [comment]
Fixed with https://github.com/mozilla/application-services/pull/2080.

**Comment by vladikoff** [comment]
Thanks!
