### ISSUE TITLE
[push] SubscriptionResponse needed when decrypting message

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#2047]
For WebPush, we need to provide the `WebSubscription` along with the decrypted data to GeckoView.

Right now, our hack for this is so call subscribe every time before a decrypt and then send those results together to the browser. It would be nice if we could get those together or be able to reconstruct them together.

The only missing information I can see that we need to construction a subscription is the `scope`, `endpoint` and `appServerKey`.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-15)

**Comment by jrconlin** [comment]
I forgot that there's `PushManager.dispatchInfoForChid(chid)` which currently returns scope and uaid. This function could be expanded to return those fields.
