### ISSUE TITLE
[push] Update verify_connection to return SubscriptionResponse

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#2049]
Previously, the `verify_connection` API would return a `Map<String, String>` of chid to endpoint which wasn't as useful in the current state since we didn't have a mapping of who owned which chid. We turned that into returning just a bool, and notifying all subscribers in the short run.

What would be better, is if verify_connection could return a full [`SubscriptionResponse`](https://github.com/mozilla/application-services/blob/master/components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt#L242) so that we can notify that specific subscriber on those changes with the full info.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-13)

**Comment by jonalmeida** [comment]
@vladikoff this can be closed since the requirements for it was done when #2046 was fixed.

**Comment by vladikoff** [comment]
👍 thank you!

**Comment by jonalmeida** [comment]
@vladikoff ah, I'm sorry, I was wrong, this was not the issue that needed to be closed. 🤦‍♂ 

This was the one I had originally meant a while back: https://github.com/mozilla/application-services/issues/2045

**Comment by jonalmeida** [comment]
I might try to work on this myself since I'm familiar with it.
