### ISSUE TITLE
Implement Rust crate connecting Rust `log!` to android-components `Log`/`Logger`

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#205]
Rust has a nice `log!` macro and associated facilities: the [log facade](https://github.com/rust-lang-nursery/log).  @pocmo added a Timber-like `Log` and `Logger` interface to `android-components` in https://github.com/mozilla-mobile/android-components/commit/aaa320c60c0c180754910e25633c96fb27dc4c3d#diff-af1c54a13a31c0d4b5fe393e8f197850.  This ticket tracks connecting the two.

The way I see this working is that we define an `log-android-components` crate that implements the Rust `log` interface, just like https://github.com/Nercury/android_logger-rs does.  But instead of invoking the Android `liblog.so` functions like `__android_log_write`, it uses the JNI to invoke the `android-components` `Log` and `Logger` functions as appropriate.

We can than either:
- have Rust libraries intended for use in Android components (or in Android components-consuming applications) configure the `log-android-components` connection(s) themselves; or
- have an Android component that provides an Android interface itself for "connecting Rust to Android components".

This is a lot of boilerplate for a straightforward outcome, but I think it's the price of admission.

**Comment by rfk** [comment]
> have Rust libraries intended for use in Android components (or in Android
> components-consuming applications) configure the log-android-components connection(s)
> themselves;

Naively, this sounds like the better option to me.  As a consumer of the ultimate "fxa client" and "logins storage" Android Components, I shouldn't need to know or care that they contain some rust bits under the hood.  Those components should just do the right thing and log to the same place as all the other Android Components do.

So...perhaps this plumbing in of the `log-android-components` piece is part of the job of the high-level Kotlin layer of each of our exported components?  (and hence lives in the android-components repo).

**Comment by rfk** [comment]
@ncalexan I recall you having some WIP code for this, could you please link it from the issue here for visibility?
