### ISSUE TITLE
Headers not found on iOS catalina

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2065]
Copy pasting the errors I've seen so far so it's easy to search on the repo/outside this repo:
```
'errno.h' file not found
...
Failed to run custom build command for `libloading v0.5.2`
        'pthread.h' file not found
```

I've filed an issue upstream at https://github.com/alexcrichton/cc-rs/issues/452 where you can find more details.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-628)
┆Story Points: 3

**Comment by thomcc** [comment]
Hopefully there are actually only 2 r's in errno!
