### ISSUE TITLE
`regenerate_dependency_summaries.sh` confused by github repo ownership changes

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2103]
The `rust-base64` crate has moved from `alicemaz` to `marshallpierce` on [GitHub](https://github.com/alicemaz/rust-base64/).
I'm seeing two licenses being listed in `dependency-licenses.xml`:
```
  <license>
    <name>Apache License 2.0: base64</name>
    <url>https://github.com/marshallpierce/rust-base64/blob/master/LICENSE-APACHE</url>
  </license>
  <license>
    <name>Apache License 2.0: base64</name>
    <url>https://github.com/alicemaz/rust-base64/blob/master/LICENSE-APACHE</url>
  </license>
```

It seems that the order of these licenses is nondeterministic, so CI will complain from time to time that the dependency summary files have changed.

I believe this URL change might have happened between `base64`'s `v0.10.1` and `v0.11.0` (using `cargo tree` it can be determined that we depend on both).

@rfk thoughts? It's not a big deal as I believe every dependent crate will eventually move towards base64 `v0.11.0`, but it might happen in the future again.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-312)

**Comment by rfk** [comment]
Ugh, thanks for digging into this. We can probably resolve it in the short term by adding more explicit ordering to the output of that script, I'll take a quick look...
