### ISSUE TITLE
Prototype emitting glean metrics from a rust component

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2107]
One of the big open questions for our "logins 1.0" project is the gathering of metrics to support https://github.com/mozilla/application-services/issues/1748 and https://github.com/mozilla/application-services/issues/1749; ref [this google doc](https://docs.google.com/document/d/1N0URC2C2p8ZghTpozimpkaispbUl3LKWC1QkvjYgmSk/) for a lot of background info.

After a bit of investigation and prototyping, I believe that it will be tractable to approach this as follows:

* Build a Rust API that wraps `libglean_ffi.so`, the style of the existing [Kotlin](https://github.com/mozilla/glean/tree/master/glean-core/android) and [Swift](https://github.com/mozilla/glean/tree/master/glean-core/ios) bindings.
* Add a new backend to [glean_parser](https://github.com/mozilla/glean_parser/) that can take a yaml file with metrics declarations, and emit Rust code for generating them via the above wrapper.
* Add a couple of hooks in android-components so that the application can configure the rust components with appropriate global state, similar to e.g. the [rustlog](https://github.com/mozilla-mobile/android-components/tree/master/components/support/rustlog) component.
* Instrument our rust components to directly emit metrics via the generated glean code, and have the accumulated in the global glean object managed by the application.

That sounds like a lot, but I think it should be OK to build it piecemeal, as we need it.

Next step is to make a concrete prototype that can flesh out all the details of the proposal, and to loop in the Glean team on whether this will all work out from their perspective.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-314)
┆Story Points: 5
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-11-22

**Comment by rfk** [comment]
Here is some extremely early-stage prototype code I made while hacking around on this:

* A badly-named [`rc_glean` rust component](https://github.com/mozilla/application-services/compare/the-great-glean-experiment#diff-fdb44bad6aab3f0abfcc841031c57317), which wraps `lib_gleanffi.so` so it can be called from rust code.
* A demo [`metrics_thing` rust component](https://github.com/mozilla/application-services/compare/the-great-glean-experiment#diff-8a4de37715d4629617c271c7de81d451), essentially a do-nothing function that emits a telemetry event every time you do it.
* A [`support.rustglean` android component](https://github.com/mozilla-mobile/android-components/compare/master...rfk:rc-glean-prototype#diff-350e70f0a8f77b69c6ce5d8ab323118d) that lets the application plumb its global glean state into the appservices megazord.
  * And [a bit of a hack to the glean kotlin bindings](https://github.com/mozilla/glean/compare/master...rfk:rc-glean-prototype) to expose the necessary state
* A [modified glean sample app](https://github.com/mozilla-mobile/android-components/compare/master...rfk:rc-glean-prototype#diff-62ce104c85136358e321f95a004f8296) which uses the `metrics_thing` rust component.
* A screenshot of the `metrics_thing` events being incorporated into the sample app's ping:
![Capture](https://user-images.githubusercontent.com/34695/68337686-255d7e00-0135-11ea-9830-61a8a34b4144.PNG)


I had also hacked together a rust backend for glean_parser, but foolishly didn't commit it to version control, and it got clobbered by an over-zealous `./gradlew clean`; I will attempt to reconstruct it from memory, as I don't think it was too involved...

**Comment by mdboom** [comment]
Thanks for looking at this and keeping us in the loop!

@rfk wrote:
> Build a Rust API that wraps libglean_ffi.so, the style of the existing Kotlin and Swift bindings.
> Add a new backend to glean_parser that can take a yaml file with metrics declarations, and emit Rust code for generating them via the above wrapper.

We already have this on our roadmap, because we'll need it for Desktop.  I don't think the plan is to get to that at all this quarter.  @chutten can probably provide more context on timing.

> Add a couple of hooks in android-components so that the application can configure the rust components with appropriate global state, similar to e.g. the rustlog component.
> Instrument our rust components to directly emit metrics via the generated glean code, and have the accumulated in the global glean object managed by the application.

Right.  Everything will have to go through the "one true Glean singleton" managed by the application, but that should be doable given the appropriate hooks.

One sticking point we ran into earlier is how we build a "megazord" package so that a-s rust and glean rust can link together, but also provide their outward facing Android APIs.  That seemed like a technical problem without a bottom, which is why we ultimately decided to "not megazord" and pay the (modest) binary size penalty for doing so.  But maybe with what you're suggesting and having the Rust wrapper talk to Glean over the CFFI, we wouldn't have to statically link together after all.  (I'll admit I don't understand these issues in great detail, but wanted to raise them since they've been raised before)...

**Comment by rfk** [comment]
@thomcc if you have a few moments, I'd be interested in your early impressions of the  badly-named [`rc_glean` rust component](https://github.com/mozilla/application-services/compare/the-great-glean-experiment#diff-fdb44bad6aab3f0abfcc841031c57317) and all the exciting ways that kind of direct FFI access might cause us trouble.  (For example, it seems like we'd want to do a similar thing to NSS and add an explicit version check, but I'm sure there are other things to consider).

**Comment by rfk** [comment]
> But maybe with what you're suggesting and having the Rust wrapper talk to Glean over 
> the CFFI, we wouldn't have to statically link together after all.

Right, that's my hope here - treat `libglean_ffi.so` as an external dependency and avoid the need to megazord.

**Comment by Dexterp37** [comment]
This is a great experiment @rfk !

Thank you for testing this and keeping us in the loop. We have [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1579146) for tracking adding a Rust API to the Glean SDK.

As @mdboom pointed out, our main concern is the ability to accumulate data to the *one and only Glean SDK singleton* across all languages: metrics accumulated by non A-S components in Android Components (think of `engine-gecko-*`, from Kotlin) should go to the same Glean instance used by the Rust crate in A-S.

The other thing we deeply care about is developer ergonomics for the Rust API: we really want to design an API that is easy to use and prevents potential footguns :)

With that said, what do you think about having a meeting about this, @rfk ? This is a great start and maybe we could discuss how to help each other to make it happen :)

**Comment by rfk** [comment]
I also made a little video walkthrough of prototype here: https://youtu.be/7P64jnl6jns

**Comment by Dexterp37** [comment]
> 
> 
> I also made a little video walkthrough of prototype here: https://youtu.be/7P64jnl6jns

This is great! Thanks for doing that!

**Comment by rfk** [comment]
This prototype work served its purpose and I think it's clear how we plan to more forward:

* Short-term, we'll emit metric on the Kotlin side, adjusting our Rust APIs as necessary to expose the relevant information to Kotlin for submission to Glean.
* Mid- to long-term, we'll work with the Glean team on officially-supported Rust bindings for glean.
  * From early discussion, it sounds like the shape of this might end up being fairly similar to what was prototyped here, except with `rc_glean` and the glean-parser backend being maintained in the main glean repo, and the public API being only the rust code generated from the metrics.yaml file.

So, I'm going to close this issue out. Thanks all, this was fun and interesting to work through!

**Comment by rfk** [comment]
We'll coordinate the ongoing work in the Bugzilla bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1579146
