### ISSUE TITLE
Create an a-c feature for showing the list of synced tabs

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2115]
This will provide calls for (synchronously) fetching the current tab list, and refreshing the list. It'll drive the synced tabs UI. It requires a configured sync manager.

It would be great to have your help with this, @jonalmeida and @rocketsroger! I'm super vague on the details here: will we need a concept for the backend (it seems like we already have concepts for awesomebar suggestion providers and session store backends; do we need another one for providing the synced tabs list itself?) and a feature and a browser component? 🤷‍♀

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-322)
┆Story Points: 5
┆Epic: Syncing Tabs
┆Sprint: SYNC - end 2019-12-06

**Comment by jonalmeida** [comment]
Hi @linacambridge !

> will we need a concept for the backend (it seems like we already have concepts for awesomebar suggestion providers and session store backends; do we need another one for providing the synced tabs list itself?) and a feature and a browser component?

The short answer.. yes! 😅 

I tried to break up the work needed on the sync tabs board to make it a bit easier to organize the things we need to build, dependencies and stories. Feel free to check out the board: https://github.com/orgs/mozilla-mobile/projects/11

**Comment by linacambridge** [comment]
This looks perfect! Thanks @jonalmeida!
