### ISSUE TITLE
Integrate the tab sync component into the a-c reference browser

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2117]
Once we have components for showing tabs from other clients (#2115) and a store for uploading our own tabs (#2116), we can integrate our feature into the reference browser. This would make for a wonderful end-to-end demo.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-320)
┆Story Points: 5
┆Epic: Syncing Tabs
┆Sprint: SYNC - end 2020-01-31

**Comment by eoger** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/pull/5223.

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

PR opened https://github.com/mozilla-mobile/reference-browser/pull/980
