### ISSUE TITLE
Extend the Rust synced tabs engine with an autocomplete API

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2119]
We'll want an API similar to our history autocomplete matcher, but for synced tabs, and exposed over the FFI so that Kotlin can use it.

The [Desktop autocomplete provider](https://searchfox.org/mozilla-central/rev/b2b0077c2e6a516a76bf8077d6f0237c58f5959a/toolkit/components/places/PlacesRemoteTabsAutocompleteProvider.jsm) might be good inspiration.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2420)

**Comment by rfk** [comment]
I reckon this could potentially be a good-second-issue, if we're able to provide appropriate pointers to how it's done in the history component. @linacambridge what do you think?

**Comment by jdragojevic** [comment]
It's not clear what behavior or product request is driving this change.  I'm going to close as as wontfix.  We can reopen if there is demand for this.

**Comment by mhammond** [comment]
> It's not clear what behavior or product request is driving this change.

FTR, I believe the desired change is that remote tabs are matched as you start typing in the URL bar.
