### ISSUE TITLE
Figure out how to stop Android from removing debug symbols in .so symbols

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#212]
There is a question on https://stackoverflow.com/questions/38051860/android-native-crash-debug-symbols but it's still not clear

the sizes of .so from the AAR is huge:

![image](https://user-images.githubusercontent.com/128755/45124713-59a46b80-b139-11e8-9a1e-25cf67d0e0c4.png)

but no matter what we try the APK is still tiny.

There is also https://developer.android.com/ndk/guides/ndk-stack

But I cannot get debug symbols in the form of the `/obj` directory

**Comment by ncalexan** [comment]
> but no matter what we try the APK is still tiny.

All applications of the Android-Gradle plugin want to strip symbols; ensure you're using the `doNotStrip` stanza.

I don't understand what you're saying about the `/obj` directory -- presumably there's some support for symbolicating stacks as dumped to logcat that pulls symbols from the build files?  I can try to investigate that.

**Comment by vladikoff** [comment]
@ncalexan  the article in https://developer.android.com/ndk/guides/ndk-stack talks about 'obj' dirs. So far the 'doNotStrip' did nothing for me in any of the apps, maybe using the AAR has something to do with it

**Comment by ncalexan** [comment]
We definitely know how this works now, and we did it, and now we've stopped doing it -- so we're not going to do it for this ticket.
