### ISSUE TITLE
Write some queries for Desktop password manager telemetry

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2121]
Desktop has some telemetry for its password manager backend, which are available in these main ping histograms and would be really useful for our dashboard:

* `PWMGR_NUM_SAVED_PASSWORDS` (total number of saved website
* `PWMGR_LOGIN_LAST_USED_DAYS` (days since each saved login was used, bucketed by the number of days)
* `PWMGR_SAVING_ENABLED` (whether or not Firefox asks to save passwords at all)

These are also interesting:

* `PWMGR_NUM_HTTPAUTH_PASSWORDS` (number of HTTP auth passwords, using the Firefox auth dialog. Uncommon)
* `PWMGR_BLOCKLIST_NUM_SITES` (number of sites for which the user said "never save logins for this site")
* `PWMGR_USERNAME_PRESENT` (number of saved logins with a username. It would be interesting to plot this against PWMGR_NUM_SAVED_PASSWORDS)
* `PWMGR_NUM_PASSWORDS_PER_HOSTNAME` (number of saved logins per origin...for example, you might have multiple passwords saved for Gmail, one for home and one for work)

@rfk also asked about this yesterday: Desktop's password manager uses a JSON file for storage (not SQLite), so we don't have slow SQL telemetry for it. I don't think we measure read, write, or query performance for passwords.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-329)
┆Story Points: 3
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-11-22

**Comment by lougeniaC64** [comment]
[Rough draft dashboard](https://sql.telemetry.mozilla.org/dashboard/desktop-password-manager-telemetry#167509)
