### ISSUE TITLE
Build infrastructure for collecting logins component

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2122]
We'll want to emit similar metrics as Desktop (#2121), but for our Rust component. This issue involves figuring out what we're reporting, and finding the right places to report them. To start with, we could try on every database write (add, update, delete, sync), or whenever we fetch all logins—since we're already reading them.

Desktop _also_ has a `gather-telemetry` notification that's emitted periodically, but it's not reliable: https://github.com/mozilla/application-services/issues/1749#issuecomment-547758197

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-328)
┆Story Points: 3
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-12-06

**Comment by linacambridge** [comment]
https://github.com/mozilla/application-services/issues/1749#issuecomment-547725195 is a great place to start. The dashboards look like they're for UI events, a few layers above, but we can still implement those four core metrics as probes in our component.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Issue split into:

SYNC-367Collect login metricsSYNC-368Get data steward approval for logins component metrics

**Comment by rfk** [comment]
We have logins metrics now, I think we can close this issue.
