### ISSUE TITLE
Send logins component metrics in Glean

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2123]
Once we're emitting logins metrics (#2122), we'll want to send them up. How we do this is still TBD...I'd love it if we could build on @rfk's prototype (#2107) to send them directly from our component. If that's not practical or realistic to do in the short term, we can plumb them through to Kotlin, and send them from a-c.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-330)
┆Epic: Logins Component 1.0

**Comment by linacambridge** [comment]
Depends on #2107, #2122, and #2127.

**Comment by rfk** [comment]
>  we can plumb them through to Kotlin

We ended up doing it from Kotlin, and I think we can safely close this issue.
