### ISSUE TITLE
Collect SQL statement timings in Rust logins

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2124]
This will let us measure the query performance for all our logins queries. We'll use the same mechanism as #2123 to send these timings via Glean. This would also help us figure out a more generic way to collect slow SQL telemetry (#1688).

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-327)
┆Epic: Logins Component 1.0

**Comment by linacambridge** [comment]
These would fall under the quality metrics described in #1748.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

We're doing some basic timing measurements as part of SYNC-334, let's not grapple with SQL-statmement timing in the first version.
