### ISSUE TITLE
Monitor logins component exceptions

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2129]
`LoginsStorageException`s caused by database corruption, I/O errors, and SQL constraint violations show up in Sentry. This seems fine for tracking some of the quality metrics described in #1748, but we'll need to make sure we're tracking them. We'll also want to think about how we'll report these on Desktop eventually, where we don't have Sentry.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-646)

**Comment by linacambridge** [comment]
Desktop does have a (Nightly-only) way to capture stacks [outside of crash reports](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/collection/stack-capture.html), but it has limitations, and I get the feeling reading through the [original bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1209131) that it's not really meant for this kind of thing.

**Comment by rfk** [comment]
We've got some graphs of errors, I don't think there's much remaining in this bug that is actionable.
