### ISSUE TITLE
Fix rust warnings in fxa-client

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#214]
These show up on a lot of builds and we should fix (or disable the specific ones we can't if there are any of those).

**Comment by thomcc** [comment]
This causes my editor to pop up with these warnings fairly frequently, so I tried to fix it just now, and it's a bit hairy. It's mostly about figuring out where to put the `#[cfg(feature = "browserid")]` to make everything shut up, but I'm not sure anybody other than @eoger knows exactly which of these functions should be that way.

Because this is trickier than expected, I'm removing the good-first-issue label.

**Comment by eoger** [comment]
I think we have to put them everywhere, both in callers and callers (have to remove the whole call tree basically). It's a bit annoying and verbose so I went with the solution that allowed me to put the least `cfgs` around, but feel free to change that.

**Comment by thomcc** [comment]
The other option is to drop `#![allow(unused_imports, dead_code)]` in `fxa-client/{src,ffi/src}/lib.rs`.
