### ISSUE TITLE
sync check email never received

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2148]
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0
Build ID: 20140924083558

Steps to reproduce:

Created a sync account, but I never receive the email for checking/validating the mail address. I reasked, saw the message "mail resent", ,but still won't receive.
I deleted the account and recreated it, still same issue. I checked filters/antispam etc...
Maybe there is a delay in sendind? the address is @laposte.net . I think I had old still account with this address.

---
🐞 Issue is synchronized with Bugzilla [Bug 1096899](https://bugzilla.mozilla.org/show_bug.cgi?id=1096899)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-348)

**Comment by rfk** [comment]
moved to fxa component
