### ISSUE TITLE
CI on master is busted

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2150]
It looks like we are having a bad time cross-compiling libbacktrace for windows.
I wonder if it's related to https://github.com/rust-lang/backtrace-rs/issues/130.

https://firefox-ci-tc.services.mozilla.com/tasks/groups/SNh1AyfBQPePaleBDlWImA

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-349)

**Comment by eoger** [comment]
Looks like this was caused by the rust upgrade to 1.39.0, 1.38.0 compiles OK. (see run: https://firefox-ci-tc.services.mozilla.com/tasks/groups/BX5IbQV7Qcmd3gWH9nzTOA)

**Comment by vladikoff** [comment]
Good news!

**Comment by eoger** [comment]
Filed https://github.com/rust-lang/backtrace-rs/issues/264 while I investigate.
