### ISSUE TITLE
Repair or omit invalid `formSubmitURL` and `hostname` values when querying the logins store

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2157]
This is a spinoff from https://github.com/mozilla/application-services/issues/695.

For legacy reasons, various logins clients (including us!) have allowed invalid login data to be stored and synced. We need to get to a place where such invalid data is hidden from consuming applications, so that they don't get confused and make bad choices about what login data to autofill where.

This issue is to ensure that any invalid values already in the db or in sync, are not surfaced to the consuming application. When reading logins records from the db, we may need to:

* Validate that `hostname` is an origin.
* Validate that `formSubmitURL` is an origin, if present.
* Probably some other stuff here, depending on the output of https://github.com/mozilla/application-services/issues/2155

Note that this work may be redundant in the face of https://github.com/mozilla/application-services/issues/695, which is about *fixing up* invalid records in the db. But it seems like it could be independently useful until we're sure that's working correctly in all cases.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-355)
┆Epic: important not urgent

**Comment by rfk** [comment]
One open question, also raised in #695, is what to do with records that contain invalid data, ref https://github.com/mozilla/application-services/issues/695#issuecomment-465871301.

**Comment by rfk** [comment]
As of a recent refactor, we now have a [`Login::validate_and_fixup`](https://github.com/mozilla/application-services/blob/5381ec8514a01d0d6d45089b6111cd18f7806f2b/components/logins/src/login.rs#L368) method that I think will provide a decent framework for tackling this bug. It basically boils down to doing some of the TODOs in the API docs for [hostname](https://github.com/mozilla/application-services/blob/5381ec8514a01d0d6d45089b6111cd18f7806f2b/components/logins/src/login.rs#L49) and [formSubmitURL](https://github.com/mozilla/application-services/blob/5381ec8514a01d0d6d45089b6111cd18f7806f2b/components/logins/src/login.rs#L94) inside of this function.

For `hostname`:

* Attempt to parse the `hostname` field as a [URL](https://docs.rs/url/2.1.0/url/struct.Url.html).
  * If we can't, then report an error
  * Check the resulting URL's [origin](https://docs.rs/url/2.1.0/url/struct.Url.html#method.origin):
      * If it [not an opaque origin](https://docs.rs/url/2.1.0/url/enum.Origin.html#method.is_tuple) then ensure that the hostname is equal to the stringified origin, fixing up if necessary

For `formSubmitURL`:

* If it is the empty string, leave it be.
* If it is the single character ".", fix it up to be the empty string.
* Otherwise, attempt to parse the `formSubmitURL` field as a  [URL](https://docs.rs/url/2.1.0/url/struct.Url.html).
  * If we can't, then:
      * If the Login also has a `httpRealm` field, fix it up to be the empty string
      * Otherwise report an error
   * Check the resulting URL's [origin](https://docs.rs/url/2.1.0/url/struct.Url.html#method.origin):
      * If it [not an opaque origin](https://docs.rs/url/2.1.0/url/enum.Origin.html#method.is_tuple) then ensure that the formSubmitURL is equal to the stringified origin, fixing up if necessary.

And of course, adding a bunch of tests that we do the right thing in various cases here. The linked TODOs above have some suggestions for testcases that should be added.

**Comment by rfk** [comment]
There's a suggestion in https://github.com/mozilla/application-services/pull/2380#issuecomment-566862589 that maybe we can close this issue now, given that #2380 included many of the fixes mentioned here. @mhammond what do you think, should we just close this? It's currently marked as a good second issue.

**Comment by bendk** [comment]
As far as I can tell, these have been addressed by [`validate_and_fixup()`](https://github.com/mozilla/application-services/blob/main/components/logins/src/login.rs#L388) which makes use of [`validate_and_fixup_origin()`](https://github.com/mozilla/application-services/blob/main/components/logins/src/login.rs#L339).  Are there any cases left to cover?

**Comment by rfk** [comment]
I agree, the TODOs around handling this fields seem to be resolved in the latest `main`, so I think we can close this bug.
