### ISSUE TITLE
Add an API to fetch history pages for top sites

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2163]
The Fenix team would like to fetch a list of top frecent pages for their Top Sites view (mozilla-mobile/fenix#6190). We currently have APIs for fetching visits by time range, and paging through visits, but (IIUC) nothing that orders by frecency and returns pages, not individual visits.

The API would probably look something like `fun getTopFrecentUrlsExcluding(excluded: List<String>, limit: Int): List<String>`, and the query feels like it would be similar to what [New Tab on Desktop](https://searchfox.org/mozilla-central/rev/e7c61f4a68b974d5fecd216dc7407b631a24eb8f/toolkit/modules/NewTabUtils.jsm#1200-1346) does today. We'd exclude pages below a certain threshold, and hidden pages.

We could probably just return the URL strings, especially if we're planning to let users customize titles. However, if we also need the page title, we may need to make a `data class PageInfo` with `url` and `title` properties (and maybe the frecency, too?). `VisitInfo` doesn't feel like quite the right fit here.

CC @vesta0 and @boek for product and engineering guidance about how we define top sites.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-359)
┆Story Points: 0
┆Epic: Fenix Migration

**Comment by linacambridge** [comment]
For exclusions...we could either have a-c store (in shared preferences) a list of pages that should never appear in Top Sites, and pass them via the API. Or we could add a `can_be_top_site` column to `moz_places`, and manage the blocklist ourselves.

I think I'd prefer the first one of those options—we can always lift Top Sites into a-s later, maybe when we're ready to unify with Desktop.

**Comment by boek** [comment]
@linacambridge personally I would rather have an A-C store and pass a list via the API. I don’t mind doing the glue code myself and it makes the code a little easier to follow :)

**Comment by linacambridge** [comment]
Perfect, that simplifies things for a-s, too! 😁

**Comment by linacambridge** [comment]
@gabrielluong is working on this now. A question that came up in Slack today was storing additional bits of metadata:

* The exclusion list; i.e., this page should never appear in Top Sites.
* The pinned list—this page should always appear in Top Sites.

We could either store these on the a-s side, or in a-c. So which one do we pick?

The benefit of storing it in a-s is, we can tie it to the page URL in `moz_places`, either via a separate `moz_top_sites` table, or a `top_site_status` column in `moz_places`. Doing this in a-s now also means we have a path for syncing these (which we don't currently do) sooner, should we want that someday. However, it does make the code harder to follow, and means that any changes we want to make to the Top Sites API have to also be made in a-s, then bubbled up to a-c. Additionally, a-c would still have to transform the list to add icons, since we don't currently have favicon storage in Places.

The alternative is to store those bits of metadata in a-c (in `SharedPreferences` or `Room`), and pass the exclusion list to the a-s method. The pinned list wouldn't need to be passed explicitly, since we'd store the URL in Room, and could show that in the UI directly. This is the approach that this issue is suggesting, and, IIUC, what @boek suggested in https://github.com/mozilla/application-services/issues/2163#issuecomment-561257020. It's simpler to develop and iterate, especially for a UI-driven feature like this. It might also make it easier to fetch favicons for those top sites, since everything except the query to fetch top frecent URLs happens in a-c.

/cc @pocmo @grigoryk

**Comment by gabrielluong** [comment]
We added a Top Sites Storage component utilizing `Room` in [#5315](https://github.com/mozilla-mobile/android-components/issues/5315). The consensus between `SharedPreferences` vs `Room` was that Fenix preferred only holding preferences in `SharedPreferences`. We already utilized `Room` in `TabCollections` so this naturally fit in with the existing storage and observer pattern used in Fenix.

**Comment by jdragojevic** [comment]
@gabrielluong or @linacambridge  - it sounds like this was all handled on the a-c side.  Can you confirm there are no further changes required in a-s?

**Comment by linacambridge** [comment]
@jdragojevic No, IIUC, we still need the API to fetch frecent top sites in a-s. The a-c side implements the component itself, and storing the list of sites that the user manually pins and unpins. What’s missing is a way to automatically show top sites based on a user’s history, which is what this API covers.

@gabrielluong Is that still the plan?

**Comment by gabrielluong** [comment]
> @jdragojevic No, IIUC, we still need the API to fetch frecent top sites in a-s. The a-c side implements the component itself, and storing the list of sites that the user manually pins and unpins. What’s missing is a way to automatically show top sites based on a user’s history, which is what this API covers.
> 

Yes, this is completely correct regarding what has happened in a-c.

> @gabrielluong Is that still the plan?

Yes, we still want to implement the API to fetch frecent top sites in a-s. I am looking to still implement it.

**Comment by linacambridge** [comment]
Awesome, thanks so much @gabrielluong! 🎊

**Comment by jdragojevic** [comment]
@gabrielluong - for tracking purposes, can you please link to here the Fenix issue where you intend to do the remaining changes, please?
