### ISSUE TITLE
Get data steward approval for logins component metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2173]
We'll want to emit similar metrics as Desktop (#2121), but for our Rust component. This issue involves figuring out what we're reporting, and finding the right places to report them. To start with, we could try on every database write (add, update, delete, sync), or whenever we fetch all logins—since we're already reading them.

Desktop _also_ has a `gather-telemetry` notification that's emitted periodically, but it's not reliable: https://github.com/mozilla/application-services/issues/1749#issuecomment-547758197

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-368)
┆Story Points: 2
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-12-06

**Comment by rfk** [comment]
I've tried to sketch out our `metrics.yaml` file in order to make the conversation more concrete, ref https://github.com/mozilla/application-services/pull/2225

**Comment by rfk** [comment]
I filed the data review request in bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1597895

**Comment by rfk** [comment]
I haven't had any feedback in the bug yet, so I've emailed the data-stewards list.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I ended up doing some subset of this as part of the work of SYNC-368, since I had to do the metrics.yaml file anyway. Not sure how much remains but we can take a fresh look when this issues comes back up for triage.
