### ISSUE TITLE
Sync Dashboarding

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2186]
As a product team, we want to be able to visualize and communicate how our products are functioning though a data dashboard.

1. Executive summary for high-level success metrics

2. Health summary for day-to-day understanding of errors and performance

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-583)
┆Epic: Sync client dashboarding
┆Sprint: SYNC - end 2020-01-17

**Comment by jdragojevic** [comment]
test comment
