### ISSUE TITLE
Document practices for rust debugging

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2188]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-709)
┆Sprint: Backlog

**Comment by rfk** [comment]
@eoger do you feel like you have any special insight on this topic that would be worth capturing as part of our docs/maintainability work?

**Comment by eoger** [comment]
On this specific subject, I would say not really, I `dbg!` stuff to debug.
