### ISSUE TITLE
Include LICENSE file in repository

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#220]
As part of publishing #199, I'm saying that the Logins API is Apache 2.  Is this whole repo Apache 2?  MPL?

**Comment by vladikoff** [comment]
We should MPL-2.0 unless we cannot MPL-2.0 for some reason

**Comment by rfk** [comment]
From mtg: copy what the android-components repo is doing == MPL

Also need to grep for Apache-licence headers to ensure consistency.
