### ISSUE TITLE
Find a way to come back on Rust stable

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2201]
We're [pinned](https://github.com/mozilla/application-services/pull/2171) on Rust 1.38.0 until we figure out why `cc` is failing cross-compilation on Windows with Rust 1.39.0.
Bad run example:
https://firefox-ci-tc.services.mozilla.com/tasks/groups/SNh1AyfBQPePaleBDlWImA

Removing `backtrace` does not help because `cc` is used by other crates.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-394)
┆Story Points: 5
┆Epic: important not urgent
┆Sprint: SYNC - end 2020-01-03

**Comment by vladikoff** [comment]
Ref: https://github.com/rust-lang/backtrace-rs/issues/264
