### ISSUE TITLE
fxaclient's getSessionToken should not throw in case of a missing sessionToken

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2202]
From the method's docs:

`@throws FxaException Will send you an exception if there is no session token set`.

However, since this method is simply reading some data from in-memory state, simply returning `String?` will suffice here, and will make dealing with this method much easier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2429)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by grigoryk** [comment]
Same for `getCurrentDeviceId`.

**Comment by kwabam** [comment]
I'm not sure `get_current_device_id` can be treated the same way. In `PushPayload::DeviceDisconnected`, using `state.current_device_id?` would throw an error which is undesirable. In other use cases, we simply cannot access state.

**Comment by mhammond** [comment]
@bendk can you please see if this remains relevant in your current work?

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865150

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
