### ISSUE TITLE
RemergeDb Storage operations return somewhat vague errors if record validation fails

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2232]
Follow up from #2226.

E.g. if you try and insert a record which does not match the schema, it might return an error tangentially related but not really correct.

For example, if you try to insert "http://foo.com/bar/baz" to a `Url { is_origin: true }` field, it will give you a `NotAUrl` error (when really it is a url, it's just not an origin). There are a few places like this and they're mostly marked in the code.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-414)
┆Story Points: 3
┆Epic: chrome.sync.storage (Generic Sync) prototype
┆Sprint: SYNC - end 2020-01-17

**Comment by glasserc** [comment]
Just to clarify, the example given above `http://foo.com/bar/baz` will get silently truncated to `http://foo.com`, in accordance with the [spec](https://github.com/mozilla/application-services/pull/658/files#diff-71bb41c1e10b65f11202f8a2ea4f6278R187). I think a better example is e.g. `mailto:ethan@example.com`. This URL has an opaque origin and so it will be rejected with the above-mentioned error.
