### ISSUE TITLE
Remerge: add sanity checks around changes in schema/version

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2233]
Follow up from #2226.

E.g. if you load a db with a schema version 0.1.0 and then 0.0.1 (or whatever), we'll accept it and replace the schema. We probably should either return an error, or perhaps open using the newer schema? Not clear, but whatever we decide to do is probably not going to be hard to implement.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-413)
┆Story Points: 3
┆Epic: Remerge production readiness
┆Sprint: SYNC - end 2020-03-13

**Comment by glasserc** [comment]
Per discussion with Thom on Zoom, we can make this issue broader -- not only should we verify that versions don't go backwards, but we should also ensure that if a schema version is the same, that its contents are the same too.
