### ISSUE TITLE
RemergeDb storage initialization should migrate records when version increases

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2234]
Follow up from #2226

Right now we treat migration as a no-op. The steps for how to proceed here are detailed in the RFC (See the section on migration, and in particular the "Algorithm for increasing
`dedupe_on`
strictness").

see the gh issues for comments, the link was unintentionally broken.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-412)
┆Story Points: 5
┆Epic: Update Firefox extension preference syncing to use Sync15

**Comment by lougeniaC64** [comment]
@thomcc A few newb sanity check questions:

1. I'm assuming on a high level the work required to complete this ticket is populating [the storage schema upgrade function](https://github.com/mozilla/application-services/blob/d153dd383eecd0852980b98f4aa17edd908122df/components/remerge/src/storage/schema.rs#L29), is that correct?

2. Is 2.1.x of the [Algorithm for increasing dedupe_on strictness](https://github.com/mozilla/application-services/blob/master/docs/design/remerge/rfc.md#algorithm-for-increasing-dedupe_on-strictness) section in the remerge RFC still an open question? You mention not being sure what else should be done after the tombstone records are uploaded. Is sorting or anything else required here? If sorting is required, is the modification date the only field that should be sorted on?

3. Regarding 2.2.x, is front-to-back merging via two-way merge the preferred approach? If so, where is two-way merge implemented?

**Comment by thomcc** [comment]
Ack, we should can that, the deduping stuff in logins has proven to me that my assumptions here all need to be revisited. You shoudl return an error if they change dedupe_on for now.

**Comment by thomcc** [comment]
Sorry, that's just points 2 and 3. For point 1, no, that's for the overall database change. What you're looking for is https://github.com/mozilla/application-services/blob/d153dd383eecd0852980b98f4aa17edd908122df/components/remerge/src/storage/bootstrap.rs#L38

**Comment by lougeniaC64** [comment]
@thomcc Does this seem about right? Apologies for being so explicit, just want to make sure I understand.

- Check if the `dedupe_on` fields for the old and new schemas match. If they don't, throw an error.
- Get existing records from `rec_mirror`.
  - Apply defaults from the new schema where applicable.
  - Apply field restrictions from the new schema where applicable (min, max, etc. via the `field.validate` function).
- Insert updated records into `rec_local` with the new schema version number in the `remerge_schema_version` field.
- Set the mirror records `is_overridden` field to 1.

Also assuming this would be done in a function in db.rs with a transaction that's called in the load_or_boostrap function.

**Comment by thomcc** [comment]
That looks great!

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

We've decided to not use remerge for extension preference syncing. Closing these issues.
