### ISSUE TITLE
Expose `places_api_reset_bookmarks` to Swift/Kotlin, and make sure a-c calls it on sign out

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2250]
If I'm reading the code right, we don't currently expose `places_api_reset_bookmarks` as an API call, so it's unclear to me if `reset` ever gets called when the user signs out. That means we'll keep all sync metadata around (including the sync ID, last sync time, and tombstones) until the user reconnects. As a consequence, we'll also write tombstones for any synced bookmarks that get deleted.

If they reconnect with a _different_ account, we'll reset all sync state, and they'll start over as if on a first sync. However, if they reconnect with the _same_ account (assuming no node reassignments or remote wipes have happened since), it'll behave as a merge.

That leads to cases like the ones described in [this Slack message](https://mozilla.slack.com/archives/C4DCECLGJ/p1574332009079200), where bookmarks deleted from Fenix while the user was signed out will get deleted on other devices when they sign back in.

@grigoryk @thomcc, do you know if we do anything special on sign-out in a-c? Does the new sync manager change this at all?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-429)
┆Story Points: 3
┆Sprint: SYNC - end 2020-01-31

**Comment by keianhzo** [comment]
This affect the syncing in three fronts:
