### ISSUE TITLE
Assure quality of Fenix migration of FxA, bookmarks, history and logins

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2254]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/SYNC-430)

**Comment by linacambridge** [comment]
Depends on #2255, #2257, and #2258.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

On-track for 10-Jan completion for Fenix nightly migration.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Jan 22: On-track.  Fennec to Fenix migration rollout started this week and we're monitoring the telemetry.  We've prioritized resolving any issues that surface through the migration process.
