### ISSUE TITLE
Disqualify invalid items in the bookmarks mirror from deduping

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2260]
[`fetch_new_remote_contents`](https://searchfox.org/mozilla-central/rev/153172de0c5bfca31ef861bd8fc0995f44cada6a/toolkit/components/places/bookmark_sync/src/store.rs#300) currently considers all new items, even ones that aren't valid. Including them isn't very useful—they don't have valid URLs, so we can't do content matching!

---
🐞 Issue is synchronized with Bugzilla [Bug 1557551](https://bugzilla.mozilla.org/show_bug.cgi?id=1557551)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-436)

**Comment by AdaephonBen** [comment]
Hi, I wanted to work with Mozilla as part of Gsoc 2020 and thought this would be a good first issue. Can I please be assigned to this issue?

**Comment by mhammond** [comment]
> Hi, I wanted to work with Mozilla as part of Gsoc 2020 and thought this would be a good first issue. Can I please be assigned to this issue?

Thanks for your interest! It's probably best to put a pull-request up, and we'll assign it to you once that's done.

**Comment by appsvc-moz** [comment]
Upstream bug has been closed with the following resolution: FIXED.
