### ISSUE TITLE
The "Back" navigation button does not go back to the Mozilla page after clicking the "Get a Firefox Account" button from that page

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2263]
Created attachment 9110874
sync form back.gif

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
- Firefox Beta 71.0b11, Build ID 20191118154140
- Firefox Nightly 72.0a1, Build ID 20191122091512

**[Steps to reproduce]:**
1. Open the browser.
2. Navigate to "www.mozilla.org" website.
3. Click the "Get a Firefox Account" button from the top right side of the page.
4. Click the "Back" navigation button from the left side of the toolbar.
5. Observe the behavior.

**[Expected result]:**
- The "www.mozilla.org" website is displayed again.

**[Actual result]:**
- The "Firefox Sync" form remains displayed.

**[Notes]:**
- The navigation history shows that a Firefox Account URL is displayed just before the navigation to the Sync form: https://drive.google.com/file/d/1excEQN2OTu7REmlPyxWjAxIBtcy-v7cg/view
- This issue is not reproducible on the following Firefox product pages:
	- https://monitor.firefox.com/
	- https://send.firefox.com/
	- https://screenshots.firefox.com/
- I have attached a screen recording of the issue.

---
🐞 Issue is synchronized with Bugzilla [Bug 1598678](https://bugzilla.mozilla.org/show_bug.cgi?id=1598678)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-438)

**Comment by rfk** [comment]
Moved to FxA component
