### ISSUE TITLE
"Host your own" documentation link

### ISSUE THREAD

**Issue by jespersh** [mozilla/application-services#2277]
I was looking into how to run my own Sync server and ended here:
https://mozilla.github.io/application-services/docs/accounts/faq.html#is-it-possible-to-host-your-own-firefox-accounts-service-like-with-firefox-sync
links to
https://docs.services.mozilla.com/howtos/run-fxa.html which 404s.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-444)

**Comment by 6a68-mozilla-owner** [comment]
Moving to the application-services repo, since the fix belongs there.
