### ISSUE TITLE
Fennec history migration: PlacesException: Error executing SQL: non-punycode host provided to reverse_host!

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2280]
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6712650/?query=is:unresolved

```
mozilla.appservices.places.PlacesException: Error executing SQL: non-punycode host provided to reverse_host!
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importVisitsFromFennec(PlacesConnection.kt:8)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.importFromFennec(PlacesHistoryStorage.kt:3)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:19)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-446)
┆Story Points: 2
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-06

**Comment by rfk** [comment]
Hrm, I'm no sentry expert, and the linked query seems to show issues with description 'unable to open database' rather than the thing about punycode. Where can we find the full details of this error?

**Comment by rfk** [comment]
IIUC, `reverse_host` is something that we define as a user-defined function in SQLite, which is then called from a trigger when we insert data into the `moz_places` table.

Fennec history import slurps items directly from the fennec db into `moz_places`, but it filters out what it believes to be invalid URLs by using is own `is_valid_url` user-defined function.  So, perhaps this `is_valid_url` function is allowing some characters through that are not accepted by `reverse_host`.

And indeed, I don't see anything in `is_valid_url` that insists on the string being punycode. @grigoryk is there documentation on whether the Fennec history db expects to store URLs as punycode?

**Comment by rfk** [comment]
Also to check my own understanding: everything in the a-s places database *must* be punycode, because attempts to insert non-punycode values would trigger this same error. Does that sound right @thomcc @linacambridge?  I wasn't able to find any docs that would answer this one way or the other.

**Comment by thomcc** [comment]
FWIW `reverse_host` could easily be made to handle this case, however it would mean our uniqueness constraints in the database would be incorrect, which is one of the reasons we keep this error. We should be passing each URL through `Url::parse(u)?.into_string()` to ensure punycoded origins, and hex-encoded paths/fragments/etc. Presumably that's not happening, if things are going directly into the DB.

**Comment by mhammond** [comment]
I can repro this; I'll put a PR up soon
