### ISSUE TITLE
Propose metrics artifacts to use for monitoring success of the migration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2281]
We intend to have a "migration dashboard" where we can tell how the migration is going, and to detect any problems while on nightly/beta. That will require non-trivial metrics work. This issue is for the definition and scoping of such work.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-447)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-06

**Comment by rfk** [comment]
I made a first attempt at getting my head around metrics artifacts here:

  https://docs.google.com/document/d/13s7My4GkKyQ56hXP2vJdUrZdR_CTIkXBg4EbRtnC3l4/

All feedback welcome; I'll try to have some targetted conversations about it with folks next week.
