### ISSUE TITLE
Hide the "Do not sync" button in Fenix flow

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2283]
Currently we have it show on service != sync, 

we can limit it using multiService true or fx_desktop_v3

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-449)
┆Story Points: 2
┆Sprint: SYNC - end 2019-12-20

**Comment by rfk** [comment]
I filed a mirror issue over in FxA, where the fix will have to take place:

  https://github.com/mozilla/fxa/issues/3553

But let's keep this one open for tracking purposes.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Shane fixed this for us over in FxA, closing the tracking issue here.
