### ISSUE TITLE
Desktop: 'attachedClients' can be called with an undefined sessionToken

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2288]
![image](https://user-images.githubusercontent.com/128755/69741596-55cb8300-1109-11ea-928e-2613e275c5f2.png)

This causes a hexToString to call `str is null` and throws an error in the browser toolbox, see stack trace

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-451)

**Comment by jdragojevic** [comment]
Mark is going to open some desktop bugs in bugzilla to address.

**Comment by mhammond** [comment]
Tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1601180
