### ISSUE TITLE
Link to instructions for self-hosters?

### ISSUE THREAD

**Issue by philbooth** [mozilla/application-services#229]
I've been helping someone try to get their self-hosted Sync set-up working, via email. They mentioned that they'd followed these instructions:

https://github.com/michielbdejong/fxa-self-hosting

I was like "whoa, those instructions are great!". Should we link to them from somewhere, either here or maybe in the main FxA repo?

**Comment by rfk** [comment]
They're already linked to from https://mozilla-services.readthedocs.io/en/latest/howtos/run-fxa.html, but it may be we should link to *that* page from additional locations.
