### ISSUE TITLE
Report success/failure/timing metrics for logins import

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2298]
To support the Fennec->Fenix migration, we will need to report some basic success/failure metrics from the logins-importing function, so that Fenix can include them in its migration ping and we can send them to logstream.

For each migration phase
 1. How many total starting
 2. How many successfully migrated
 3. Specific error reasons (sanitized of any personal data)
 4. Total duration

Summary metrics
 1. Error reasons (or nothing, implying success)
 2. Total time

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-461)
┆Story Points: 2
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-03

**Comment by rfk** [comment]
From meeting, I'm thinking that this needs to look fairly similar to what we currently do for the sync ping - rather than just suceeding or failing, the logins-import method should return some sort of `LoginsMigrationMetrics` struct that encapsulates the above data.
