### ISSUE TITLE
Ensure that we can analyze sync ping data by android version, device type, etc

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2301]
For analyzing the Fenix migration rollout, we will likely need to analyze sync ping metrics segmented by Android version, device type, or other factors. For example, we may find that users on a certain Android API level have an unusually high rate of sync failures.

Let's double-check whether this information is available in the sync ping, and add any that might be missing.

We'll know we've succeeded at this bug if we can produce a graph of the sync error rate broken down by Fennec version, Android version, etc.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-464)
┆Story Points: 2
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
AFAICT Glean is giving us this already; here's a screenshot of the available segementation data, and me doing a quick analysis of the number of syncs by device manufacter:

![Capture](https://user-images.githubusercontent.com/34695/71703478-ceb8ab80-2e28-11ea-8aa4-2a10c09eac6e.PNG)

So I'm going to go ahead and close this out.
