### ISSUE TITLE
Login import: can't pass `guid` to ServerPassword; optional `id` field

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2303]
API as it's currently exposed can't actually be used correctly: `ServerPassword` doesn't accept a `guid` field, which is needed for the migration. Perhaps it will actually work out if we just generate new GUIDs for all the records, but I would imagine sync's de-duping logic is then bound to trip over itself...

Also, `ServerPassword` has a required `id` field, which currently needs to just be faked out (migration logic itself doesn't use it). Can the `id` field be optional?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-466)
┆Story Points: 1
┆Epic: Fenix Migration

**Comment by eoger** [comment]
As noted on slack, `id` is actually `guid` renamed: https://github.com/mozilla/application-services/blob/e1a0f6bbbf17b01db305ca739e0ea55b9cccebd6/components/logins/src/login.rs#L16-L17

Let us know if you need more work on our side!

**Comment by grigoryk** [comment]
Passing `guid` via the `id` field works. Thanks, @eoger .
