### ISSUE TITLE
Unexpected error on login to FFA

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2304]
Created attachment 9112753
Screenshot.png

Very strange thing. FFA account eugene.savitsky@gmail.com

1. Windows 10 desktop, FF, I had FFA enabled, then it just stopped syncing.
I manually logged from FFA out.
FF cannot login to FFA anymore. I may enter any email (my own, some random test324234@gmail.com etc) and I get "Unexpected error".
Cannot create a new user as well - "Unexpected error".

1a. Same PC. FF Developer edition.
Sync shows as connected, but not syncing.
Opening https://accounts.firefox.com shows a white page.

2. Freshly installed Ubuntu 19.10 on a notebook.
After fist FF opening ever. Cannot log with any e-mail - "Unexpected error".
Cannot make a new user.

3. Firefox Preview (Android).
Cannot log with my main e-mail - "Unexpected error".
Could enter my second account email and password.
Got a confirmation mail.
Clicking on "Confirming Sign-In" got "Unexpected error" on page https://accounts.firefox.com/complete_s ... 9cd........

3a. On same Android phone, FF Beta (the old and actual mainstream version).
All works fine.

4. On same home network my other PC and home notebook are syncing fine.
https://accounts.firefox.com/settings shows my settings

5. Brought from the car my "in-car" notebook.
Logged in, but not syncing. https://accounts.firefox.com/settings shows a white page.
After updating Windows and restart I could sync... :-/

6. Two office PC's are syncing fine.

7. Tried to connect on a Linux virtual machine - Unexpected Error...

I even cannot login to support.mozilla.org - it uses FFA account as a user login, but I cannot login to FFA...

---
🐞 Issue is synchronized with Bugzilla [Bug 1600513](https://bugzilla.mozilla.org/show_bug.cgi?id=1600513)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-467)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Moved to FxA.
