### ISSUE TITLE
Get rid of `MemoryLoginsStorage.kt`

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2310]
Ref this comment thread: https://github.com/mozilla/application-services/pull/2262/files#r351552656

We have an entirely separate implementation of the `LoginsStorage` API, implemented in Kotlin and backed by simple in-memory storage. It's a maintenance burden and IMHO is at substantial risk of diverging in behaviour from the canonical sqlite-backed version.

As far as I can tell, the only consumer of this implementation is Lockwise for Android, which uses it in tests. I recall some trouble with Lockwise using our rust-components in their tests at some point, but I can no longer find an open issue about it.

What would it take for us to replace this custom implementation with the rust one, perhaps backed by a `:memory:` sqlite database rather than a file on disk?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-471)

**Comment by eoger** [comment]
Mockito should be able to mock out the Rust layer anyway (which is what they do on Android Components), I think Lockwise should follow suit.

**Comment by jhugman** [comment]
Lockwise-android is using it for UI and integration testing purposes, without touching sync and fxa. Moving to a `:memory:` sqlite database backed implementation is an excellent idea.

> Mockito should be able to mock out the Rust layer anyway (which is what they do on Android Components), I think Lockwise should follow suit.

Yep, we're mocking `mozilla.appservices.logins.LoginsStorage`.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Let's mark this as deprecated and please file a bug in the lockwise repository.

**Comment by rfk** [comment]
> Let's mark this as deprecated

Here we go: https://github.com/mozilla/application-services/pull/2389

>  please file a bug in the lockwise repository.

Said bug already exists: https://github.com/mozilla-lockwise/lockwise-android/issues/1103

We can leave this bug open but bump it down the backlog, to revisit actually removing the code.
