### ISSUE TITLE
Emit logins quality/performance metrics in Lockwise for Android

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2327]
It looks like the logins-component metrics from [https://github.com/mozilla/application-services/pull/2225](https://github.com/mozilla/application-services/pull/2225) will need to be opted-in to on an application-by-application basis. Let's drive the necessary data review and enablement code to get them enabled in Lockwise for Android.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-647)
┆Epic: Sync client dashboarding

**Comment by rfk** [comment]
The lockwise app has been updated to use a version of a-s that includes the logins quality metrics, so I think we might get this for free, modulo a bit of pipeline work.
