### ISSUE TITLE
Docs: Building on iOS

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#2330]
Starting a bug to document my building steps, to be turned into a md file.

- Install ninja and gyp, following https://github.com/mozilla/application-services/blob/v0.44.0/.circleci/config.yml#L105
- install rust (`rustup update stable`)
- setup rust cross-compilation: https://github.com/mozilla/application-services/blob/v0.44.0/.circleci/config.yml#L359
- `cd libs; build-all.sh ios; cd ..`
- `carthage build --no-skip-current --platform iOS --verbose --configuration Release --cache-builds`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-728)

**Comment by eoger** [comment]
Shall we close now that https://github.com/mozilla/application-services/pull/2412 is merged?

**Comment by garvankeeley** [comment]
sgtm

**Comment by rfk** [comment]
@data-sync-user didn't leave any details about why this got re-opened, so I fee like it can probably be closed? If we have improvements we want to make let's do them in new issues.
