### ISSUE TITLE
Let callers configure oauth token TTL

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2334]
It can be useful for applications to be able to create shorter-lived access tokens, e.g. in order to test handling of expired tokens. For a concrete use-case see https://github.com/mozilla/application-services/issues/2279#issuecomment-561861087.

Let's add the ability for apps to request a specific TTL on their tokens.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-486)
┆Epic: papercuts

**Comment by rfk** [comment]
Concretely, the [`get_access_token` method](https://github.com/mozilla/application-services/blob/6e5b47322edc9c1d6573d6b3fe9154102465c245/components/fxa-client/src/oauth.rs#L36) needs to grow an optional `ttl` argument, giving the time in seconds for which the token should be valid. We then need to expose that through [the FFI layer](https://github.com/mozilla/application-services/blob/6e5b47322edc9c1d6573d6b3fe9154102465c245/components/fxa-client/ffi/src/lib.rs#L315) and make it available from the [Kotlin](https://github.com/mozilla/application-services/blob/6e5b47322edc9c1d6573d6b3fe9154102465c245/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt#L249) and [Swift](https://github.com/mozilla/application-services/blob/6e5b47322edc9c1d6573d6b3fe9154102465c245/components/fxa-client/ios/FxAClient/FirefoxAccount.swift#L64) bindings.

Optional arguments are a bit awkward in the FFI, and it may turn out to be easier to have e.g. `ttl <= 0` indicate that we should use the default ttl, rather than having the rust code take an `Option<u32>` and then trying to set that over the FFI.

I'm marking this as a good-first-issue because I think it's pretty self-contained, but it's also a very broad introduction to the various moving parts of our shared-components approach, and requires writing code in Rust, Kotlin, and Swift.

**Comment by jhugman** [comment]
I'd like to work on this.

**Comment by vladikoff** [comment]
@jhugman sounds good! ping me if you have any questions!
