### ISSUE TITLE
SetupStorageClient::put_meta_global() does not appear to be sending a BSO

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#2335]
From fenix, we're seeing PUT requests to `/storage/meta/global` that do not have a body associated with it. This is causing client sync to fail. We see this with the new Durable Sync server, although we suspect that the older server sees the problem as well. 

I've confirmed this by modifying the `components/sync15/src/client.rs` SyncStorageClient::exec_request` function to display the request body. (See https://paste.mozilla.org/u9Rseyag for a diff).

On the server side, we've patched for this by special casing the PUT `/storage/meta/global`, but as I understand, this is not a normal behavior.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-487)
┆Story Points: 3
┆Sprint: SYNC - end 2019-12-06

**Comment by rfk** [comment]
Taking this as I'm trying to repro, although I have not successfully reproed yet.

> On the server side, we've patched for this by special casing the PUT /storage/meta/global,

What does the patched server do in this case? I think rejecting such a request is the right thing to do, but maybe we need to try to process it temporarily for debugging.

**Comment by jrconlin** [comment]
Repro: Odd, I pulled the latest master and was able to reproduce it pretty easily. Hopefully, it's just something messed up with my local install, but looking at the adb logs shows the `../storage/meta/global` call being rejected with a bad BSO. We did push the fix to stage earlier today. You might want to use Prod servers since the patch has not rolled out to those boxes yet.

Server: We specifically treat any call to `../storage/meta/global` that has a `Content-Size` of 0 as an empty BSO. This generally gets us past the JSON parser failing to decipher nothing as valid JSON and lets processing continue to set the meta timestamp. We're using it as a band-aid for now since it block fenix from syncing anything, since the error stops the sync flow.

**Comment by rfk** [comment]
> but looking at the adb logs shows the ../storage/meta/global call being rejected with a bad BSO

I also see this request being rejected (hitting prod servers) but the outgoing request appears to have a well-formed body. Currently waiting on a rust-and-kotlin recompile cycle to try further.

Were you trying with an existing account, or a brand new account?

**Comment by rfk** [comment]
Here's what I see during my failed sync on Fenix, using a lightly-modified version of the logging diff you posted (basically using `String::from_utf8_lossy` in order to see the JSON rather than the raw bytes):
```
12-05 17:43:53.590  9154  9447 D sync15::state: compute_engine_states: output EngineStateOutput { declined: {"addresses"}, changes_needed: EngineChangesNeeded { local_resets: {"addresses"}, remote_wipes: {} } }
12-05 17:43:53.593  9154  9447 D sync15::state: SyncID for engine "creditcards" was missing
12-05 17:43:53.593  9154  9447 I sync15::state: Uploading corrected meta/global with timestamp ServerTimestamp(1574720772440)
12-05 17:43:53.595  9154  9447 I sync15::client: request: PUT /1.5/131779961/storage/meta/global q(None) b(Some("{\"id\":\"global\",\"collection\":\"meta\",\"payload\":\"{\\\"syncID\\\":\\\"JBlr2MFEnsyp\\\",\\\"storageVersion\\\":5,\\\"engines\\\":{\\\"prefs\\\":{\\\"version\\\":2,\\\"syncID\\\":\\\"myxK_rXbJanX\\\"},\\\"history\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"Rjbyq80H2rtj\\\"},\\\"passwords\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"E48pWVC3thKq\\\"},\\\"addons\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"G_3BnXd-ZdKt\\\"},\\\"creditcards\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"wMeyiTgHsn0a\\\"},\\\"bookmarks\\\":{\\\"version\\\":2,\\\"syncID\\\":\\\"ceAQLe8hP4Ep\\\"},\\\"clients\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"0lr8qNig9efd\\\"},\\\"tabs\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"VWWx5oJzDhrj\\\"},\\\"forms\\\":{\\\"version\\\":1,\\\"syncID\\\":\\\"n244KNHNQvaT\\\"}},\\\"declined\\\":[\\\"addresses\\\"]}\"}"))
12-05 17:43:53.897  9154  9447 I sync15::client: Request "/1.5/131779961/storage/meta/global" was an error!
12-05 17:43:53.897  9154  9447 W sync15::client: ### Request failed: PUT /1.5/131779961/storage/meta/global :: 400 "8"
12-05 17:43:53.897  9154  9447 D sync15::sync_multiple: Declined engines list after state machine set to: Some(["addresses"])
12-05 17:43:53.898  9154  9447 W sync15::sync_multiple: sync failed: HTTP storage error: RequestFailed { route: "/1.5/131779961/storage/meta/global", status: 400 }, final status=ServiceError                                                                          
```

IIUC the response body of `"8"` means [Invalid WBO](https://github.com/mozilla-services/syncstorage-rs/blob/f9acd8bd46b0dd5414c8332b2c388a9f5f4a5d88/src/error.rs#L34). I can't see anything obviously wrong with the payload here, but I'll dig a little deeper.

(Obviously, it's possible that my account is not in a state that triggers the empty-upload bug, and I may be triggering a different bug).

**Comment by rfk** [comment]
Decoded, the BSO my Fenix is trying to upload is:

```
{u'id': u'global', u'collection': u'meta', u'payload': u'{"syncID":"JBlr2MFEnsyp","storageVersion":5,"engines":{"prefs":{"version":2,"syncID":"myxK_rXbJanX"},"history":{"version":1,"syncID":"Rjbyq80H2rtj"},"passwords":{"version":1,"syncID":"E48pWVC3thKq"},"addons":{"version":1,"syncID":"G_3BnXd-ZdKt"},"creditcards":{"version":1,"syncID":"wMeyiTgHsn0a"},"bookmarks":{"version":2,"syncID":"ceAQLe8hP4Ep"},"clients":{"version":1,"syncID":"0lr8qNig9efd"},"tabs":{"version":1,"syncID":"VWWx5oJzDhrj"},"forms":{"version":1,"syncID":"n244KNHNQvaT"}},"declined":["addresses"]}'}                                        
```

I wonder if the rust server is rejecting it because of the `"collection"` key, which is [not defined in this serde schema](https://github.com/mozilla-services/syncstorage-rs/blob/f9acd8bd46b0dd5414c8332b2c388a9f5f4a5d88/src/web/extractors.rs#L307).  The python server [does allow](https://github.com/mozilla-services/server-syncstorage/blob/e0f738ad1862ecdf9ffc57839beb85ac4f6f4171/syncstorage/bso.py#L11) a `"collection"` key, although I think it basically ignores it, and a quick grep of the functional tests suggests that we don't test for this behaviour explicitly on the server.

**Comment by rfk** [comment]
For completeness, I pushed the branch with my logging tweaks here: [rfk/zero-length-put-debugging](https://github.com/mozilla/application-services/compare/rfk/zero-length-put-debugging?expand=1).

**Comment by jrconlin** [comment]
Ok, that's really strange. This was the first sync on a device with an existing account. I'll definitely verify that "deny_unknown_fields" both does and continues to do what we think it should. I'm also hoping that perhaps the lack of body I was seeing was just due to when and how I was dumping it, since you're definitely producing a valid body. 

Thanks!

**Comment by jrconlin** [comment]
Going to close this issue for now since the problem may be with the server.

Will also remove the empty body handler from the server.
