### ISSUE TITLE
Allow logins-sql to be built without requiring sqlcipher.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#234]
Follow up for #221 because we don't need it for the milestone.

This is trickier than expected to make it work without it silently ignoring your requests for sqlcipher/non-sqlcipher without letting you know.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-715)
┆Epic: a-s storage components (backlog)
┆Sprint: Backlog

**Comment by thomcc** [comment]
I did this in the past, here's a branch with the patch for it https://github.com/mozilla/application-services/tree/no-sqlcipher-logins-sql. It does part of the work -- having it as a default-on feature for logins-sql/ffi means the situation is basically the same as current.

We could make it non-default, but there's no way for the gradle plugin to request that it build sqlcipher, which IIUC requires we exten https://github.com/ncalexan/rust-android-gradle/ to support `features` (and possibly disabling default features if we want to enable bundled).

**Comment by thomcc** [comment]
https://github.com/ncalexan/rust-android-gradle/pull/3 adds support for specifying this in the gradle, which solves that issue.

**Comment by thomcc** [comment]
https://github.com/mozilla/application-services/tree/sqlcipher-optional basically it, but it's DONOTLAND until the rust-android-gradle patch lands.

**Comment by rfk** [comment]
> https://github.com/mozilla/application-services/tree/sqlcipher-optional basically it,
> but it's DONOTLAND until the rust-android-gradle patch lands.

The rust-android-gradle patch landed; do we want to push forward with this, or WONTFIX?
