### ISSUE TITLE
Dodgy use of SyncStatus::New in Logins

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2342]
I did a review of the logins code around migration, and the biggest concern is the sync status getting set to new. This in general, makes us assume that the record has never been on the server, which means. As with all assumptions, it's completely wrong. We set it to new on both import and reset. Doing this in reset has been broken here for a while (#648 was intended to fix it), but import being broken is probably more easily hit.

While I was incorrect about this being a problem for deduping, it will cause us to fail to upload tombstones in `delete` and `wipe` (aka wipe_remote, e.g. the one that *is* supposed to upload tombstones). The case where a user hits this is probably pretty rare, as they'd have to delete records between import and first sync, but it also seems like fixing it is pretty easy as well.

In particular, I think it mostly takes just deleting a few parts of the existing functions:

1. Here https://github.com/mozilla/application-services/blob/5381ec8514a01d0d6d45089b6111cd18f7806f2b/components/logins/src/db.rs#L673-L682

2. And here https://github.com/mozilla/application-services/blob/5381ec8514a01d0d6d45089b6111cd18f7806f2b/components/logins/src/db.rs#L781-L787

The rest of the code should handle the non-New records automatically then. This could cause us to upload a few tombstones for records deleted locally that never made it to the server, but this is probably a rare case.

Beyond that I think it's worth thinking about whether or not SyncStatus is a good way to do things (remerge adopted it, but it's probably just... bad), but I don't see any issues.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-492)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-20

**Comment by thomcc** [comment]
This is part of the work for #2255, but I don't think I have the bandwidth for the rest of it (e.g. performing these fixes, adding tests).

**Comment by lougeniaC64** [comment]
@thomcc I took a pretty exact approach to completing this work and I don't want the necessity for the SyncStatus assessment to be lost when my PR closes so let me know if I should create a follow-on ticket for that.
