### ISSUE TITLE
Figure how to get a share Fennec databases for testing.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2344]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-493)
┆Epic: Fenix Migration

**Comment by eoger** [comment]
@st3fan just told me the QA team has a tool to backup and import database from Fennec that is not finalized quite yet!

**Comment by rfk** [comment]
From @grigoryk on slack:

"""
so, there will be, with the profile management tool SV is building
https://github.com/mozilla-mobile/fennec-profile-manager
https://github.com/mozilla-mobile/fennec-profile-manager/issues/1
it seems like they've made some good progress
"""
