### ISSUE TITLE
Confirm whether Firefox for iOS rust-components can use custom tokenserver

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2347]
Firefox for iOS supports using the default FxA servers with a custom tokenserver URL. When we recently tried to use this for testing a new sync storage node, it didn't seem like the rust-backed datatypes in Firefox for iOS were syncing correctly. Let's confirm whether Firefox for iOS successfully passes its custom tokenserver URL through to the rust components, and fix things up so that it does so if not.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-496)

**Comment by thomcc** [comment]
Also worth checking for Fenix. I'm pretty sure I've at least nagged @grigoryk about this, who filed a bug at one point, but IDK what ever happened there if anything.

**Comment by jdragojevic** [comment]
@tublitzed - is this really an issue or have you confirmed it works?

**Comment by tublitzed** [comment]
@jdragojevic last I checked it was still an issue; we ran into it in October, where it looked as though only specific Sync engines worked correctly (History worked but Bookmarks did not, which is why we suspected rust components might not be passing along server info).

I'd need to confirm this one again though since a lot has happened between now and Oct. I'll get this onto my TODO list and comment back here once confirmed.

**Comment by tublitzed** [comment]
Just tested iOS and Desktop(against MySQL in staging, not Spanner yet), and it looks like we're in much better shape than we were ~2 months ago. Not sure what changed, but it does look like things like bookmarks are now syncing against staging when they were not previously.

Specifically, I confirmed once pointed at staging for a non-spanner account:

* I can sync bookmarks, tabs, and history from Desktop to iOS.
* I can sync tabs and history from iOS to Desktop.


Minor issue found:

* It seems that bookmarks added on iOS are not synced back over to desktop.

I'll be prioritizing [this issue](https://github.com/mozilla-services/services-engineering/issues/25) for getting the testing process here over into Dochub for early in Q1; I plan to test while I move over specific docs, which will hopefully shake out any remaining issues. If I find any, I'll note them here. That bit of testing will also include testing against spanner backed staging, so hopefully 🤞 no differences spotted there.

**Comment by rfk** [comment]
I think we can close this out, it sounds like the custom tokenserver support is working correctly, and we have an explicit item on our list for the current iOS refactor to ensure that it continues to work.
