### ISSUE TITLE
Convert .taskcluster.yml to json-e

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#235]
This is the application-services equivalent of https://github.com/mozilla-mobile/android-components/issues/763.  If it's important for the build and deploy pipeline out of a-s, it's probably important for the pipeline out of a-c.

/cc @MihaiTabara, @JohanLorenzo

**Comment by JohanLorenzo** [comment]
Thanks for the CC! From what I see in the current taskcluster graphs, application-services only relies on the workerType `github-worker`. Therefore, there is no extra-security added if `.taskcluster.yml` is converted to json-e (unlike android-components once [bug 1486090](https://bugzilla.mozilla.org/show_bug.cgi?id=1486090) is done).

**Comment by rfk** [comment]
@ncalexan we're backlogging based on above comment, but maybe we should just close it?

**Comment by ncalexan** [comment]
> @ncalexan we're backlogging based on above comment, but maybe we should just close it?

Yeah, looks like we don't need this.  (Yet.)
