### ISSUE TITLE
Firefox Accounts sign-in assumes mistyped domain

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#2357]
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

Steps to reproduce:

Boot an Xubuntu 19.10 live USB image.
Initiate a Sync sign-in process by clicking the icon in the Firefox toolbar.
Type in my email address which is on the "zao.se" domain.
Hit enter to attempt to go to the next step of the sign-in process to enter password.

Actual results:

The form shows a red error-like balloon asking "did you mean aol.se".

Expected results:

I expected to be on the next page of the sign-in process as I had intentionally typed an e-mail address which has a Sync account since forever.

If there must be such suggestions, please have them out-of-line and don't make them interfere with the task at hand. I'm no UX person, but error-red might not be appropriate for an unprompted suggestion by the UI, especially as the information typed is legitimate.

The suggestion is especially amusing as approximately no-one uses AOL here.

---
🐞 Issue is synchronized with Bugzilla [Bug 1602224](https://bugzilla.mozilla.org/show_bug.cgi?id=1602224)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-502)

**Comment by rfk** [comment]
Moved to FxA component in bugzilla
