### ISSUE TITLE
Need help adding a new sql query to history storage

### ISSUE THREAD

**Issue by ravjit-cliqz** [mozilla/application-services#2370]
Here is what I've done: https://github.com/ravjit-cliqz/application-services/commit/4a7cd6e7ffe34dae39fd44d85ee4b0fbc0651b7f

The problem I am facing - Whenever I try to call `places_get_top_sites_infos` in `lib.rs` I get the error `Unknown coloumn visit_type` Even though I didn't request to read that coloumn.
Funny part - Even if I dont do any sql call at all, I still get the same error. (Basically i remove the call to `storage::history::get_top_sites_infos` and directly return some arbitrary value)

What am I doing wrong? Would be nice if could point me to some documentations regarding this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-515)

**Comment by mhammond** [comment]
When you call it from where? I imagine the error might be coming from setting up the triggers as the DB is opened, and maybe your DB is strange? I think visit_type is from a very very early format of the database and probably predates us doing a schema upgrade.

**Comment by ravjit-cliqz** [comment]
I am using the v44 of application service and call it from the storage-sync module(v24.0) from android-components. And the schema has visit_type coloumn in the moz_historyvisits table. 

Other calls are working fine(ex `places_get_visit_infos`), only when I try to call the `places_get_top_sites_infos` it throws the error.
Is there a way to get more detailed log? So i can know which exact sql query is failing?

**Comment by ravjit-cliqz** [comment]
Hi can anyone have a look, please?

**Comment by mhammond** [comment]
Sorry for the delay. I wonder if you have an incompatible places.db hanging around? Do the rust tests work? I'd recommend starting with that, and adding a test for your new functionality. Regarding using it via Android, I'd expect to see some log info send to logcat - what do you see there?

**Comment by jdragojevic** [comment]
@ravjit-cliqz  - is this still an issue or should this be closed?

**Comment by rfk** [comment]
I'm going to close this as inactive.
