### ISSUE TITLE
Fenix unexpectedly disabled password syncing on my account

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2372]
I've had passwords syncing on my account for ages, and during a recent run of Fenix I happened to capture some logcat output. An initial few sync attempts seem to show that "passwords" is enabled in my metaglobal:

```
12-11 08:32:58.119 13465 13491 I sync15::client: Request "/1.5/131779961/storage/meta/global" has incoming x-last-modified ServerTimestamp(1576013552360)
12-11 08:32:58.120 13465 13491 D sync15::client: Got meta global with modified = 1576013552.36; last-modified = 1576013552.36
12-11 08:32:58.120 13465 13491 I sync15::state: Have info/collections and meta/global. Computing new engine states
12-11 08:32:58.120 13465 13491 D sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"addresses"}, remote: Some(RemoteEngineState { info_collections: {"addons", "history", "prefs", "passwords", "crypto", "tabs", "clients", "meta", "bookmarks", "forms"}, declined: {"addresses"} }), user_changes: {} }
12-11 08:32:58.121 13465 13491 D sync15::state: compute_engine_states: output EngineStateOutput { declined: {"addresses"}, changes_needed: EngineChangesNeeded { local_resets: {}, remote_wipes: {} } }
12-11 08:32:58.127  5220  5297 D DnsProxyListener: DNSDBG::dns addrinfo af 2
12-11 08:32:58.128  5458  5883 D ConnectivityService: filterNetworkStateForUid() uid: 10283, pid: 13465
12-11 08:32:58.128  5458  5883 D ConnectivityService: filterNetworkStateForUid() uid: 10283, pid: 13465, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
12-11 08:32:58.366 13465 13491 I sync15::client: Request "/1.5/131779961/storage/crypto/keys" has incoming x-last-modified ServerTimestamp(1575599709030)
12-11 08:32:58.367 13465 13491 D sync15::sync_multiple: Declined engines list after state machine set to: Some(["addresses"])
12-11 08:32:58.367 13465 13491 I sync15::sync_multiple: Synchronizing clients engine
```

That sync failed, for reasons that I don't yet understand, possibly because I'm on the new spanner backend:

```
12-11 08:32:59.027 13465 13491 I sync15::client: Request "/1.5/131779961/storage/clients" has incoming x-last-modified ServerTimestamp(1576013579530)
12-11 08:32:59.028 13465 13491 D sync15::request: Committed batch NoBatch
12-11 08:32:59.029 13465 13491 W sync15::sync_multiple: sync failed: Not all records were successfully uploaded, final status=OtherError
12-11 08:32:59.029 13465 13491 W sync15::sync_multiple: Backtrace: Some()
12-11 08:32:59.029 13465 13491 I sync_manager::manager: Sync finished with status OtherError
12-11 08:32:59.059 13465 13491 E SyncWorker: 'Other' error :(
```

But on the next sync, Fenix somehow seems to think that I should opt out of password syncing:

```
12-11 08:33:19.491 13465 13600 I sync15::client: Request "/1.5/131779961/storage/meta/global" has incoming x-last-modified ServerTimestamp(1576013552360)
12-11 08:33:19.491 13465 13600 D sync15::client: Got meta global with modified = 1576013552.36; last-modified = 1576013552.36
12-11 08:33:19.492 13465 13600 I sync15::state: Have info/collections and meta/global. Computing new engine states
12-11 08:33:19.492 13465 13600 D sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"addresses"}, remote: Some(RemoteEngineState { info_collections: {"bookmarks", "prefs", "clients", "forms", "tabs", "meta", "addons", "crypto", "passwords", "history"}, declined: {"addresses"} }), user_changes: {"addresses": false, "passwords": false, "bookmarks": true, "history": true, "forms": true} }
12-11 08:33:19.493 13465 13600 D sync15::state: compute_engine_states: output EngineStateOutput { declined: {"passwords", "addresses"}, changes_needed: EngineChangesNeeded { local_resets: {"passwords"}, remote_wipes: 
{"passwords"} } }
12-11 08:33:19.493 13465 13600 I sync15::state: Uploading new declined ["passwords", "addresses"] to meta/global with timestamp ServerTimestamp(1576013552360)
12-11 08:33:19.494 13465 13600 D sync15::state: SyncID for engine "passwords" was present, but shouldn't be
12-11 08:33:19.494 13465 13600 I sync15::state: Uploading corrected meta/global with timestamp ServerTimestamp(1576013552360)
```

I'm pretty sure I didn't go in and mess around with my data choices.  I did have the "account settings" screen sitting open so that I could periodically it "sync now", so I guess it's possible that there was an accidental press on the checkbox for syncing logins. But I want to dig in a bit and see if there's any reason why Fenix might try to send `user_changes` in to the sync process without my input, because this was really surprising.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-517)

**Comment by mhammond** [comment]
This *appears* to be working as expected:

> 13600 D sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"addresses"}, remote: Some(RemoteEngineState { info_collections: {"bookmarks", "prefs", "clients", "forms", "tabs", "meta", "addons", "crypto", "passwords", "history"}, declined: {"addresses"} }), user_changes: {"addresses": false, "passwords": false, "bookmarks": true, "history": true, "forms": true} }
12-11 08:33:19.493 13465 

This includes:

> user_changes: {"addresses": false, "passwords": false, "bookmarks": true, "history": true, "forms": true}

So according to this function, there was an explicit change of passwords becoming false - ie, as if you toggled the password engine.

Obviously this might not be true, but it *looks* as though any problem here might be external to the rust sync manager - it was explicitly told to disable that engine.

**Comment by grigoryk** [comment]
On the Fenix side (or a-c, more specifically), we'll pass `SyncParams.enabledChanges` (I'm assuming this is what gets logged as `user_changes`) as a non-empty map only if SyncReason was either `EngineChange` or `FirstSync`.

`EngineChange` would happen if you toggle state of an engine, and `FirstSync` would happen after either a signin or signup - but in reality, only if we are after a signup and user was presented with CWTS dialog will there actually be locally saved engine choices.

So this should really only be a non-empty map after an `EngineChange` or a sign-up.

**Option 1**: how is `user_changes` determined above? Is that just from the passed-in `SyncParams.enabledChanges`? Persisted state doesn't play into it at all? What about other parts of `SyncParams` (reason, engines, etc)? Perhaps there's a problem in deriving this list within the library.

**Option 2**: perhaps SyncReason is incorrect in some cases? E.g. it's erroneously either `EngineChange` or `FirstSync`. But, at the same time, something must have persisted state of "passwords" as disabled in the local storage (that wasn't the UI, if we're assuming no user error)

Engine states are changed in Fenix in the following cases
- after a sync, as follows:
```
        // Process any changes to the list of declined/accepted engines.
        // NB: We may have received engine state information about an engine we're unfamiliar with.
        // `SyncEngine.Other(string)` stands in for unknown engines.
        val declinedEngines = syncResult.declined?.map { it.toSyncEngine() }?.toSet() ?: emptySet()
        // We synthesize the 'accepted' list ourselves: engines we know about - declined engines.
        // This assumes that "engines we know about" is a subset of engines RustSyncManager knows about.
        // RustSyncManager will handle this, eventually.
        // See: https://github.com/mozilla/application-services/issues/1685
        val acceptedEngines = syncableStores.keys.filter { !declinedEngines.contains(it) }

        // Persist engine state changes.
        with(SyncEnginesStorage(context)) {
            declinedEngines.forEach { setStatus(it, status = false) }
            acceptedEngines.forEach { setStatus(it, status = true) }
        }
```

- after authentication, if `declinedEngines` was provided (derived from CWTS, received over WebChannel)
- whenever user interacts with the checkboxes in Account Settings

So in theory, and assuming there are no hidden bugs here - at least from a-c/fenix point of view, this all points to a user error. E.g. two things had to happen - EngineChanged/FirstSync must have been the sync reason, and SyncEnginesStorage must have had passwords=off, and they'll both happen during an Account Settings interaction.

**Comment by rfk** [comment]
Thanks for digging in here! Without any way to prove otherwise, let's chalk this one up to "user error" as the most likely explanation.
