### ISSUE TITLE
Graceful handling of the offline case during a sessionToken migration

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2396]
Device could fail to perform a session token migration due to network issue; as discussed with @rfk, we should be fine to just "pretend it succeeded" at the api level, store the sessionToken internally in the account state, and attempt to recover organically over time.

Looking through A-C code, it seems like this approach will "just work".

cc @vladikoff

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-534)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-31

**Comment by rfk** [comment]
>  attempt to recover organically over time.

Specifically, if the application makes a call into fxa-client that requires a refresh_token, and we find that we don't have a refresh_token but do have a sessionToken, then we could use the sessionToken to create a refresh_token at that point.

**Comment by eoger** [comment]
@vladikoff:

```
migrate_from_session_token:
  call helper_migration_network_calls()
  if fail:
    state.in_flight_migration = (ksync, kxcs, session_tok)



get_profile:
  get_refresh_token:
    try_see_if_need_migration:
      if state.in_flight_migration != None
        call helper_migration_network_calls()
        state.in_flight_migration = None
```

**Comment by rfk** [comment]
In my head I imagined this working like:

```
migrate_from_session_token:
    store sessionToken into local state
    try:
      helper_migration_network_calls()
    except:
      // ignore errors, we'll fix it up later

get_profile:
    get_refresh_token:
        if no refresh token:
            if have session token:
                fix up our internal state using the session token to make a refresh token
```

**Comment by vladikoff** [comment]
>   fix up our internal state using the session token to make a refresh token

Yeah the challenges are that we need to provide a scope for the refresh token created in that step. This is why it is using the specific `in_flight_migration` flag, because we know the migration scopes.
