### ISSUE TITLE
Disable "non-empty database" limitation for login import

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2397]
In order to support master-password import during a migration (or rather, sometime after) we need to be able to import logins after the user may have populated their logins storage (either via sync, or by storing some new records, or...). MP import is still TBD, but since it requires a password entry, it will most likely happen via a persistent notification that we'll display after the migration completed. In theory, user will be able to interact with it at any point (after a sync, etc).

This will also need to ensure that we're deduping records correctly during the import, I imagine (and whatever else that needs to happen during a regular record insert).

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-533)
┆Epic: Fenix Migration

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

I'm going to go ahead and close this as won't fix.  If the decision to not migrate master-password users is changed, then we can reopen.  

ref slack conversation: https://mozilla.slack.com/archives/CLBMZNR0A/p1578525333004400
