### ISSUE TITLE
Relax history database version requirement during migration

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2401]
Currently we require that `browser.db` is at 39 for the history migration.

Going back through the changes to the `browser.db`, I see that last time we made changes to history tables, was at version 34 (added LOCAL_VISITS, REMOTE_VISITS, LOCAL_DATE_LAST_VISITED, REMOTE_DATE_LAST_VISITED to history). `visits` table was added in 32.

v34 was released in Fennec 49, and v32 in Fennec 48.

I think restricting history migration to 34+ should be fine - that won't require any extra work.

We _could_ support 32+ as well, with a bit more manual work - counts and timestamps added in 34 would need to be calculated from the visits data during a migration.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-540)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by jdragojevic** [comment]
Discussed this with Stefan and looked at the version distribution of potential fennec upgrades (https://sql.telemetry.mozilla.org/queries/67323/source#170470) we agree that we are fine with requiring browser.db 39 which corresponds to Fennec version 57.  Closing.

**Comment by grigoryk** [comment]
Re-opening this. We've reconsidered the user impact here, let's make this change since it's low-cost and helps out lots of folks.

**Comment by jdragojevic** [comment]
Done during migration, just not closed.
