### ISSUE TITLE
Relax bookmarks database version requirement during migration

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2402]
Currently we require v39 as the db version for the bookmarks migration. In 39, bookmarks schema received two new fields: LOCAL_VERSION and SYNC_VERSION, none of which should be relevant for the migration.

Before that, I kind of loose the thread of the migrations, doesn't seem like bookmarks schema changed since v17 (https://bugzilla.mozilla.org/show_bug.cgi?id=961238), and likely even sometime before that.

v17 came out in Fennec 30. Let's see if we relax our migration requirement to db version 17. 

Similar issue for history: https://github.com/mozilla/application-services/issues/2401

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-541)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
Seems reasonable to me. Is there any way for us to QA whether this works, or should we just go ahead with the change and keep an eye out for sentry errors if it fails in the wild? (I guess those users would already have been getting an error, so we can't do much harm here, right?)

**Comment by grigoryk** [comment]
I'll add in some older db versions into our migration test suite in A-C. We can also manually QA this with old Fennec builds.

**Comment by jdragojevic** [comment]
Discussed this with Stefan and looked at the version distribution of potential fennec upgrades (https://sql.telemetry.mozilla.org/queries/67323/source#170470) we agree that we are fine with requiring browser.db 39 which corresponds to Fennec version 57.  Closing.

**Comment by grigoryk** [comment]
Re-opening this. We've reconsidered the user impact here, let's make this change since it's low-cost and helps out lots of folks.

**Comment by jdragojevic** [comment]
closing this is done.
