### ISSUE TITLE
Fenix is generating a *lot* of device-registration traffic

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2415]
Fenix (and other a-c using browsers) are currently a very small percentage of our FxA DAU and FxA signin traffic, but they represent an outsize percentage of requests to the `/v1/account/device` endpoint on the FxA servers.

I can't link raw numbers here, but I can share the [bigquery query](https://console.cloud.google.com/bigquery?sq=77205064629:edd61a4fa0174889a8542f461909d9e1) from which I'm getting these numbers if you have the right permissions; ask me in slack. My high-level summary is:

* For both Desktop and Fennec, only a small percentage of daily-active FxA users will call the device-registration endpoint on any particular day.
* For Fenix, it looks like almost every daily-active FxA user will call the device-registration endpoint multiple times per day.

This leads me to believe that Fenix is sending lots of spurious device-record updates to the FxA servers. Perhaps it's e.g. doing one on every startup. @eoger does this sound possible to you?

It's not problematic while the Fenix userbase is small, but as Fenix gets more users it could start to be a problem. At Desktop or Fennec scale we cannot afford to have all active FxA users sending spurious write traffic to the FxA servers on a daily basis.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-551)
┆Story Points: 5
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-14

**Comment by rfk** [comment]
I'm going to put this in the "migration" bucket because it represents an operational risk to a successful migration.

**Comment by jdragojevic** [comment]
This is duplicated in the fenix repository: https://github.com/mozilla-mobile/fenix/issues/7524.

**Comment by vladikoff** [comment]
@grigoryk do we call the device endpoint on every app wake? as part of ensureCapabilities?

**Comment by vladikoff** [comment]
Ah see the other post here too https://github.com/mozilla-mobile/fenix/issues/7524#issuecomment-572685955

**Comment by rfk** [comment]
> This is duplicated in the fenix repository: mozilla-mobile/fenix#7524.

That issue is slightly different, and is about how frequently we check for new device commands (in other words, read queries).

This issue is specifically about calls to update device registration info (i.e. write queries) which seem to be happening way more than I would expect.

**Comment by vladikoff** [comment]
Locally I am getting a loop of 

```
  SyncWorker  D  Starting sync... Tagged as: [mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common]
        fxa_client::ffi  W  Unexpected error: Error(
                         W  Remote server error: '500' '203' 'Internal Server Error' 'A backend service request failed.' 'https://git
                            hub.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format')
 FxaDeviceConstellation  E  Error while running: polling for device events
                         E  mozilla.appservices.fxaclient.FxaException$Unspecified: Remote server error: '500' '203' 'Internal Server
                             Error' 'A backend service request failed.' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth
                            -server/docs/api.md#response-format'
                         E      at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
                         E      at mozilla.appservices.fxaclient.FirefoxAccount.pollDeviceCommands(FirefoxAccount.kt:883)
                         E      at mozilla.components.service.fxa.FxaDeviceConstellation$pollForEventsAsync$1$events$2.invokeSuspend(
                            FxaDeviceConstellation.kt:121)
                         E      at mozilla.components.service.fxa.FxaDeviceConstellation$pollForEventsAsync$1$events$2.invoke(Unknown
                             Source:10)
                         E      at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
                         E      at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
                         E      at mozilla.components.service.fxa.FxaDeviceConstellation$pollForEventsAsync$1.invokeSuspend(FxaDevice
                            Constellation.kt:120)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
efoxAccountStateMachine  I  Ran 'RecoveredFromAuthenticationProblem' side-effects for state AuthenticatedNoProfile, got successive ev
                            ent FetchProfile

```

And the following `Unexpected error: Handle is invalid: Tried to use a null handle (this object has probably been closed)` keeps happening in the loop, while the UI is not affected. This makes me worry that the 2 device endpoints are being hit here.

**Comment by vladikoff** [comment]
* Handle issue filed in https://github.com/mozilla-mobile/android-components/issues/5715
* Also on sync error states, the Fenix app always calls the device init functions when recovering. The bug filed in https://github.com/mozilla-mobile/android-components/issues/5716

**Comment by rfk** [comment]
> Also on sync error states, the Fenix app always calls the device init functions when recovering.
> The bug filed in mozilla-mobile/android-components#5716

I don't think this is enough to explain the volume we're seeing here. I instrumented a local Fenix build to log each request made by the GeckoViewFetchClient, and it seems to generate a device `POST` as part of its normal error-free syncing behaviour. For example here's a trace of things that happened when I put the app into the background just now:

```
02-11 14:24:00.156  9677 11014 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/baseline/1/cff4d3eb-2d02-476e-9f54-77555447f648
02-11 14:24:14.056  9677  9927 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/baseline/1/41c56d44-5a4c-4af8-8462-bfbff56f0f97
02-11 14:24:15.966 11200 11232 W GeckoViewFetchClient: GV FETCH POST https://api.accounts.firefox.com/v1/account/device
02-11 14:24:18.296 11200 11230 W GeckoViewFetchClient: GV FETCH GET https://api.accounts.firefox.com/v1/account/devices
02-11 14:24:18.586 11200 11230 W GeckoViewFetchClient: GV FETCH GET https://api.accounts.firefox.com/v1/account/device/commands?index=1
02-11 14:24:18.926 11200 11230 W GeckoViewFetchClient: GV FETCH GET https://profile.accounts.firefox.com/v1/profile
02-11 14:24:23.976 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://token.services.mozilla.com/1.0/sync/1.5
02-11 14:24:24.616 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/info/configuration
02-11 14:24:25.456 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/info/collections
02-11 14:24:25.766 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/meta/global
02-11 14:24:26.146 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/crypto/keys
02-11 14:24:26.506 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/clients?full=1
02-11 14:24:26.876 11200 11231 W GeckoViewFetchClient: GV FETCH POST https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/clients?batch=true&commit=true
02-11 14:24:27.426 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/history?full=1&limit=5000&newer=1581391389.18
02-11 14:24:27.906 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/bookmarks?full=1&newer=1581390826.74
02-11 14:24:28.396 11200 11231 W GeckoViewFetchClient: GV FETCH GET https://sync-743-us-west-2.sync.services.mozilla.com/1.5/130981380/storage/passwords?full=1&newer=1579638859.42
02-11 14:24:44.086 11200 11483 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/baseline/1/41c56d44-5a4c-4af8-8462-bfbff56f0f97
02-11 14:24:44.896 11200 11483 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/bookmarks-sync/1/477647ac-28d0-4a45-b621-038b830d8c37
02-11 14:24:45.226 11200 11483 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/history-sync/1/33acc6eb-3594-4f38-ab15-a12cad1dcd36
02-11 14:24:45.606 11200 11483 W GeckoViewFetchClient: GV FETCH POST https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/logins-sync/1/f2cf9fc0-72c5-4b5e-8e42-bda5b20494ec
```

The activity here includes:

* Submitting various telemetry pings
* Re-registering its FxA device record
* Fetching the list of FxA devices
* Checking for any FxA device commands
* Updating FxA profile information
* Fetching a new tokenserver token
* Checking whether it needs to sync
* Syncing each collection
* Submitting more telemetry about the sync

It should not be necessary to do many of these on each sync. I'll see if I can get more details from logcat about exactly what's triggering them.

**Comment by rfk** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/7524#issuecomment-584480888, I think what we're seeing here is the logic for responding to the `AccountRestored` event, which fires when we need to rehydrate the applicaiton's FxA state from storage.

The app's setup behaviour includes making a call to `ensureCapabilities` during startup, which AFAICT will always hit the network even if the capabilities have not changed since the last registration.

I think the right move here is for `ensureCapabilities` to avoid hitting the server if it doesn't need to. I'll file a separate bug to dig into the details.

**Comment by rfk** [comment]
From discussion with @vladikoff, I think we've investigated this sufficiently and we should close it in favour of the specific actionable fixes that we've identified.
