### ISSUE TITLE
Expose session token migration methods to Swift FxAccountManager

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2435]
[Firefox for iOS issue](https://github.com/mozilla-mobile/firefox-ios/issues/5993)

This more or less will be creating bindings for
`migrate_from_session_token`
in Swift and calling it from the account manager.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-565)
┆Story Points: 5
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-02-28

**Comment by eoger** [comment]
@lougeniaC64 if you are interested in doing a bit of Rust + Swift this could be a good first bug, let me know and I'll post more detailed instructions.

**Comment by lougeniaC64** [comment]
@eoger I'm definitely interested, but I'll probably be picking up some remerge tickets before I get to this FYI. Thanks!

**Comment by eoger** [comment]
The work to do for whoever takes this:

- Grow in [`FxAccountManager`](https://github.com/mozilla/application-services/blob/47a84bc47e77f5b6b12144e5fe6374e540f8c4db/components/fxa-client/ios/FxAClient/FxAccountManager.swift#L118) a `migrateFromSessionToken` method (feel free to find a better name).
- This method should takes `sessionToken`, `kSync` and `kXCS` as arguments and calls `fxa_migrate_from_session_token`.
- Note that we will **not** *copy* the session token.
- An event `migrationComplete` should be added to the `Event` enum, and a transition `.NotAuthenticated ->  .AuthenticatedNoProfile via migrationComplete` should be implemented that does more or less [what android components does](https://github.com/mozilla-mobile/android-components/blob/f1550bb3af22d332141c2ab8562f4af96cd2de24/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt#L713-L737).
We should also do whatever https://github.com/mozilla/application-services/pull/2492 ends up doing because we might end-up with the same offline problem.
