### ISSUE TITLE
Create a fxa aar containing the compiled binaries

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#244]
We're not moving the Kotlin code away from android-components, however it would be nice to pack the .so files into an aar in order to make a-c FxA module local development easier (no more copy/pasting so files).

**Comment by ncalexan** [comment]
Yeah, I spent some time thinking about this and am happy to push on this.  The way I see this working is that we build the "layer cake", like we're doing for `org.mozilla.sync15.logins` (and will do for `.history` and `.bookmarks` or whatever they end up being called).

That means we'll have a Gradle project in `a-s` that uses the [rust-android-gradle plugin](https://github.com/ncalexan/rust-android-gradle) to compile the Rust bits and create some kind of JVM-friendly API.  Then `a-c` can consume that.

The plugin makes local development pretty straight-forward, although it can certainly be improved.

**Comment by ncalexan** [comment]
This is addressed by #248.
