### ISSUE TITLE
Clear the megazord cache in`android/build` directories during local Maven publishing

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2453]
During development, if you bump version numbers in a-s and run `./gradlew publishToMavenLocal`, the previous megazords builds might be cached and not packaged properly for the Maven build. This will result in errors such as: 

> library "viaduct" was compiled expecting app-services version "0.48.0-testlocal1", but the megazord "megazord" provides version "0.44.0-vladThur1"

Possible workarounds: 
```
rm -rf /Users/vladikoff4/mozilla/application-services/megazords/full/android/build
rm -rf /Users/vladikoff4/mozilla/application-services/megazords/fenix/android/build
```

or

```
find . -type d -name build -exec rm -rf '{}' ';'
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-577)
┆Epic: important not urgent
┆Sprint: SYNC - end 2020-02-14

**Comment by eoger** [comment]
I think you can probably just do `./gradlew :clean publishToMavenLocal`, in any case we should put it in the substitution docs we have.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Theory: we need to add `cargo:rerun-if-env-changed=MEGAZORD_VERSION` to build.rs for the full megazord; the value of this environment variable gets embedded in the compiled rust code, but I don't see anything that tells gradle or cargo to rebuild when the environment variable changes.  I'm going to try this out real quick and see if it makes a difference.

**Comment by rfk** [comment]
Heh, so I guess github interpreted my "May or may not help resolve #2453" as an indication that the PR would in fact resolve the issue. Should we re-open this further further investigation, or keep it closed and see if we still have problems?
