### ISSUE TITLE
iOS Beta: Weird Firefox Sync "DEBUG: Not delivered" notification

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2483]
Logged from a contributor. Issue details here https://github.com/mozilla-mobile/firefox-ios/issues/5890

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-600)

**Comment by data-sync-user** [comment]
➤ Isabel Rios commented:

Adding same comment as in Github issue #5890:

As commented during fx-iOS triage, I'm seeing similar message: DEBUG: Error not Decrypted on my iPhone 6s.
 This is happening when I sign in in Lockwise (android) having my firefox-iOS signed in with my account.

Please let me know if there are any logs or info that could also be helpful. Thanks!

**Comment by rfk** [comment]
I'm not sure how helpful the a-s team can be here, that message seems to originate inside Firefox for iOS as part of its push-notification handling:

  https://github.com/mozilla-mobile/firefox-ios/blob/ec9b1c1da0b2b5da3fccfd25fc22ea657f1282dd/Extensions/NotificationService/NotificationService.swift#L65

Something is going wrong inside the bowels of the push infra, but that's all iOS specific code AFAIK, which I don't think we have a lot of experience with (with the possible exception of @linacambridge).
