### ISSUE TITLE
Include detailed SQLITE error codes in migration exceptions

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#2493]
Example exception: https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963673/?query=is:unresolved

`mozilla.appservices.places.PlacesException: Error executing SQL: unable to open database: file:///data/user/0/org.mozilla.fennec_aurora/files/mozilla/eio1wa5f.default/browser.db`

It'll be helpful to know exactly which error SQLITE encountered.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-614)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by grigoryk** [comment]
Also, perhaps we should remove remove the exact db path from the exception message, replacing it with a SQLITE error code. That would make grouping these errors in Sentry much easier. Otherwise, for each path we'd get an individual Sentry entry, it seems.

**Comment by mhammond** [comment]
I believe this is SQLITE_CANTOPEN, which is as specific as sqlite gets - from https://www.sqlite.org/c3ref/c_abort.html

`#define SQLITE_CANTOPEN    14   /* Unable to open the database file */`

That's not particularly helpful, and google isn't helping much more - we might need to dig into the sqlite sources to discover exactly what conditions causes this, although I suspect it's going to be something very broad like '_[f]open failed'

I'm not sure who is appending the filename, but I suspect that's sqlite too.

**Comment by thomcc** [comment]
Note that SQLite has extended error codes as well: https://www.sqlite.org/rescode.html

(I'm not sure if there are any that elaborate on CANTOPEN, or if these are exposed in rusqlite, but can investigate tomorrow)

**Comment by mhammond** [comment]
Also worth mentioning that even though sqlite has `SQLITE_NOTFOUND`, that's *not* related to the file not existing - it seems likely that "file not found" is covered by `SQLITE_CANTOPEN`

**Comment by grigoryk** [comment]
I think a good next step would be to not call the import functions if the path doesn't actually exists.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

If we're going to actually do this, we'll need to do it soon; bumping for triage and sprint-planning (but we may decide it's not worth doing after all).

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

wontfix.
