### ISSUE TITLE
Handling multiple/implied scopes

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#25]
Case 1:
If a token with the scope `"profile https://identity.mozilla.com/apps/oldsync"` is cached in `FirefoxAccount` and if I call `get_oauth_token` with only `profile`, I should get the cached token instead of requesting a new one.

Case 2:
If a token with the scope `profile` is cached in `FirefoxAccount` and I call `get_oauth_token` with `profile:write`, I should get the `profile` token since it supersedes `profile:write`.

See related PR: https://github.com/mozilla/fxa-shared/pull/21/files

**Comment by rfk** [comment]
> I should get the profile token since it supersedes profile:write.

It doesn't; `profile:write` is more powerful than `profile`, which gives read-only access by default.  If that wasn't clear from the linked PR, I've got more work to do over there :-)
