### ISSUE TITLE
Refactor iOS "rust" engines to use the key data directly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2518]
We don't need to call the keyinfo endpoint anymore, we can get it directly from the account manager just like Fenix does.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-638)
┆Epic: FxA for Firefox iOS

**Comment by eoger** [comment]
I think the iOS team might be able to do that one, here's the work to do:

Re-implement [`FirefoxAccount::syncUnlockInfo`](https://github.com/mozilla-mobile/firefox-ios/blob/2c1653704dbc9e8de02529ddfddba925d34a4d25/Account/FirefoxAccount.swift#L351-L372):

- We can fetch `kid`, `token` and `kSync` by calling [`FxAccountManager.getAccessToken(OAuthScope.oldSync)`](https://github.com/mozilla/application-services/blob/47a84bc47e77f5b6b12144e5fe6374e540f8c4db/components/fxa-client/ios/FxAClient/FxAccountManager.swift#L153)
- `tokenServerURL` can be obtained once #2563 lands.

cc @garvankeeley, I don't really know how to transfer github issues but it probably should belong on your repo.

**Comment by garvankeeley** [comment]
I would file this issue in FxiOS repo, but don't know how to write this up into an actionable bug. 
I don't think iOS team has the requisite knowledge to implement this. I'll grab you to chat about this and see if I grok.

**Comment by eoger** [comment]
This has been implemented on the iOS side, thanks @garvankeeley.

**Comment by garvankeeley** [comment]
Link to the code in the PR: https://github.com/mozilla-mobile/firefox-ios/pull/6077/files#diff-e7993812e8ded083c5d2b13f1f46dc18R291

**Comment by data-sync-user** [comment]
➤ Julien Chaupitre commented:

[~eoger@mozilla.com], if applicable, could you please update the story points with the effort that you delivered on this task, as to make sure your effort is accounted for in our release burndown. Thanks!
