### ISSUE TITLE
Publish artifacts from TaskCluster to maven.mozilla.org

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#252]
This is so that releng can process them and publish to maven.mozilla.org.  An overview can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1491314.  This is the a-s equivalent of https://github.com/mozilla-mobile/android-components/issues/795.

/cc @MihaiTabara

**Comment by ncalexan** [comment]
@rfk asked for an overview of how we progress here.  I see two paths:

1.  This is an analogue of the work that Johan, Mihai, and Mitch have done for a-c.  The best outcome would be for one of them to bring a-s into the a-c fold, sharing the implementation as much as possible.  Some pieces of this might be extracted to a [shared Gradle plugin](https://github.com/mozilla-mobile/android-automation-tools).

2.  Somebody else can copy the work done for a-c.  There are only a few places where one needs "releng superpowers" here; most everything else is public and requires most of all a willingness to push on it.

As a stepping stone to 1., I wonder if we should make a new private bintray account for appservices and transition all the packages away from my bintray account.  That way we could share signing keys with multiple people more easily, and we could finally get the bintray -> jcenter mirroring configured so that new packages mirror automatically.  This stepping stone would get me out of the publishing loop entirely.

**Comment by rfk** [comment]
Thanks @ncalexan!

> This is an analogue of the work that Johan, Mihai, and Mitch have done for a-c.
> The best outcome would be for one of them to bring a-s into the a-c fold

From slack conversation, it sounds like @eoger and @MihaiTabara are going to sync up about next steps on moving us in that direction \o/.
