### ISSUE TITLE
Ensure `delete_place_by_guid` does not delete URLs with foreign count references

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2520]
@keianhzo reported this issue on Slack: deleting a history entry (using `PlacesHistoryStorage#deleteVisitsFor`) for a URL that's also bookmarked throws a SQLite foreign key constraint violation.

This is due to our [`ON DELETE RESTRICT` constraint](https://github.com/mozilla/application-services/blob/67d4036aa815e0495aaded5ce074846b7187f76b/components/places/sql/create_shared_schema.sql#L118) on `moz_bookmarks.fk`. a-c's [`PlacesHistoryStorage#deleteVisitsFor`](https://github.com/mozilla-mobile/android-components/blob/cc1f6e6d211c6cd54c790b97ad7a5a0662c9ad32/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L152-L159) method calls our [`PlacesConnection#deletePlace`](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L500-L509), which, after going through the [FFI](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/ffi/src/lib.rs#L279-L296), calls [`storage::history::delete_place_by_guid`](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/src/storage/history.rs#L228-L234). `delete_place_by_guid` deletes the row from `moz_places` [unconditionally](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/src/storage/history.rs#L222-L223), without checking the `foreign_count`. (Incidentally, if the URL was not bookmarked, but had tags, we’d also silently delete those tags; if it was synced, we'd silently set it to `NULL` and lose its keyword, if it had one).

I think the fix here is going to be changing `delete_place_by_guid` to work more like [`delete_place_visit_at_time`](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/src/storage/history.rs#L362-L388) or [`delete_visits_between`](https://github.com/mozilla/application-services/blob/a6e4e1f7058f5fecf31cb2c371dc5ec3975c1b98/components/places/src/storage/history.rs#L429-L461). Specifically:

* If `foreign_count > 0`, insert tombstones into `moz_historyvisit_tombstones`, and delete all visits for that Place from `moz_historyvisits`—but do _not_ delete the Place from `moz_places`.
* If `foreign_count = 0`, do what we do now: insert a tombstone for the Place into `moz_places_tombstones`, and delete the place from `moz_places`. (That should automatically delete all its visits, too).

This is a subtle difference in behavior, and might also warrant renaming `delete_place_by_guid` to something like `delete_all_visits_for_guid`, because we might no longer delete the Place from `moz_places`. If we do decide to do this, I don't believe we need to expose the current `delete_place_by_guid` functionality, but let's discuss that, too—my thinking is, the fact that we store all URLs in `moz_places`, and reference them for history visits, bookmarks, keywords, and tags is an implementation detail, and "delete this URL and also all the things that point to it" is never going to be something a consumer wants. Indeed, that's why we have `ON DELETE RESTRICT` for bookmarks.

While we're here, let's also change the constraints on `moz_tags_relation` and `moz_bookmarks_synced` to `ON DELETE RESTRICT`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-639)
┆Story Points: 5
┆Epic: Important issues (for team or advanced contributers)
┆Sprint: SYNC - end 2020-03-13

**Comment by keianhzo** [comment]
@linacambridge Any idea when this is going to be triaged?

**Comment by linacambridge** [comment]
Hi @keianhzo, sorry for the delay! 😅

@mhammond, what do you think about the changes?

* Rename `delete_place_by_guid` to `delete_all_visits_for_guid`.
* Change `delete_all_visits_for_guid` to check the `foreign_count` before deleting the place.
* If `foreign_count > 0`, tombstone the visits, but not the Place itself.
* If `foreign_count = 0`, tombstone the Place, and delete it from `moz_places`.

**Comment by linacambridge** [comment]
> While we're here, let's also change the constraints on `moz_tags_relation` and `moz_bookmarks_synced` to `ON DELETE RESTRICT`.

I moved this part into #2790.
