### ISSUE TITLE
Add a TokenServer token fetching method in Swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2525]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-643)
┆Story Points: 3
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-02-14

**Comment by eoger** [comment]
We need to grow a swift method in Firefox iOS that fetches a token server token [just like we do in Rust](https://github.com/mozilla/application-services/blob/d09d29daccb45e615055467c4d474d5e8246e4b8/components/sync15/src/token.rs#L97-L133). There already one that takes an[ `assertion` as a parameter](https://github.com/mozilla-mobile/firefox-ios/blob/b861f7d78f70fe658d80be8cb1e08f5459e582c4/Account/TokenServerClient.swift#L139-L178), we could do a sister method that takes a `access_token` and a `kid` as params.

**Comment by eoger** [comment]
I have done this in https://github.com/mozilla-mobile/firefox-ios/commit/c201e350fbad6b88b9c322b5fe9fd26139d6431a.
