### ISSUE TITLE
Fold `logins-sql` and `logins-api` into a uniform directory structure

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#253]
`fxa_client` uses a pattern (set by Mentat, I think) that, after #244, will look like:

```
fxa-client
  ffi
  src
  sdks
    android
      library
    swift
```
I'd like to make `logins-sql` and `logins-api` fit the same directory structure, and to follow that pattern for the Places work as well (#227).

I think this will help #213 a little as well.

**Comment by vladikoff** [comment]
and maybe put all components into a `components/` dir

**Comment by ncalexan** [comment]
@tcsc are you okay with this?  #244 is already going to rework the Logins Gradle structure, so I was thinking I would do this at the same time, so you have only to refresh your Gradle/Android Studio configuration once.

**Comment by ncalexan** [comment]
> and maybe put all components into a `components/` dir

If you'd like that, I'm fine with that.  Follows `a-c`, right?  That would mean we'd have:
```
components
  fxa-client
  logins
  places
```

**Comment by vladikoff** [comment]
> Follows a-c, right?

Exactly!

**Comment by thomcc** [comment]
One issue with this structure is around swift code. IIUC Carthage doesn't have the ability to export more than one library from a repo. We can punt on this for now but it's worth considering (although in the megazord world it may not matter)

**Comment by ncalexan** [comment]
> One issue with this structure is around swift code. IIUC Carthage doesn't have the ability to export more than one library from a repo. We can punt on this for now but it's worth considering (although in the megazord world it may not matter)

That really surprises me, because that means Carthage is sniffing your VCS!  (Does Carthage *require* git?  That surprises me even more!)

I could imagine Carthage only will export one library per directory root... but that would be fine, 'cuz then we'd have Carthage roots at `components/{fxa-client,logins}/sdks/swift`.  Do we have more details?

**Comment by rfk** [comment]
> I could imagine Carthage only will export one library per directory root... but that would be fine,
> 'cuz then we'd have Carthage roots at components/{fxa-client,logins}/sdks/swift.
> Do we have more details?

I did a bit of reading up on Carthage, including [different ways to specify dependencies](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md) and a nice summary of its [build-target-discovery algorithm](https://github.com/Carthage/Carthage/issues/210#issuecomment-67049037).

It does indeed only support one XCode Project per git repo, and it will build all the targets specified in that project.  So IIUC we could have a setup where someone specifies this in their Cartfile:

```
github "mozilla/application-services"
```

And carthage would *build all the things* and make every component in this repo available to the application for linking.  The developer could then choose to link against just the ones that they want. That seems likely to be a gigantic PITA for the developer...

Carthage does also seem to support [pre-built binary distributions](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification) which, similar to our composite-build setup for Android, may help us provide a better "happy path" developer experience.

**Comment by eoger** [comment]
cc @garvankeeley as this is exactly what we have talked about this afternoon.
We also talked about having external Github repositories that would build/release only part of the tree, but concluded that the "build all and choose what you want" scheme sucks but is probably the most realistic option in the medium to short term.

**Comment by rfk** [comment]
I'm about to file a new top-level issue to centralize discussion on this topic, stay tuned :-)

**Comment by rfk** [comment]
Let's zoom out the carthage discussion to this top-level issue: https://github.com/mozilla/application-services/issues/417
