### ISSUE TITLE
Consider switching the megazords to thinlto

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2531]
Surprised there's not an issue on file for this already. It should be a 1 line patch (change https://github.com/mozilla/application-services/blob/72bbb67ee0111b4b599e27152239e96c433d34f3/Cargo.toml#L40 to `lto = "thin"`), but requires testing on all supported platforms, to ensure we don't regress things WRT https://github.com/rust-lang/rust/issues/50007 (It might be a good thing to do after we have semi-robust CI for them? Or could test manually).

Should speed up android builds a decent amount, among others.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-747)
┆Epic: Integration testing for a-s

**Comment by rfk** [comment]
> (It might be a good thing to do after we have semi-robust CI for them? Or could test manually)

To ensure I understand what you mean here, since we have a KR about test coverage for Q1 - do you mean that our current tests run in CI are likely not sufficient to catch the kinds of missing-symbols errors that were seen with rust-lang/rust#50007?

**Comment by thomcc** [comment]
Right, since it causes a failure to load some (all) subparts of the
megazord, but only on some OSes. I actually expect that our current android
unit tests would catch it if it were obviously broken (e.g. if we deleted
the lto=true line, or if thinlto didnt work for us at all), but given that
its a platform dependent issue, it seems like we should check the platforms
we care about
