### ISSUE TITLE
Tolerate NULL parents when importing bookmarks from Fennec

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2536]
Fennec's `BrowserDB` has a [`FOREIGN KEY` constraint](https://searchfox.org/mozilla-esr68/rev/1f90a88b90290e330fc0fef8291f469e42712367/mobile/android/base/java/org/mozilla/gecko/db/BrowserDatabaseHelper.java#133,141,148-149) on `bookmarks.parent`, so all rows should reference existing parent. However, there's no `NOT NULL` constraint on that column, so Places roots and the [old mobile root](https://searchfox.org/mozilla-esr68/rev/1f90a88b90290e330fc0fef8291f469e42712367/mobile/android/base/java/org/mozilla/gecko/db/BrowserDatabaseHelper.java#1284-1287) might have `NULL` parents. But our [primary key on `moz_bookmarks_synced_structure`](https://github.com/mozilla/application-services/blob/master/components/places/sql/create_shared_schema.sql#L207-L210) doesn't allow this, since it implies `NOT NULL`.

We should handle these gracefully—in the case of the Places root, we make the parent be itself, in the case of other roots (including mobile), make the parent the Places root; for others, maybe move to unfiled?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-748)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by linacambridge** [comment]
@grigoryk linked to [this Sentry report](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/?query=is:unresolved).

**Comment by mhammond** [comment]
I believe the correct sentry report is https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963672
