### ISSUE TITLE
Deduping should only consider visible fields

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2538]
This means we should remove formSubmitURL/formActionOrigin from duplicate checks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-751)

**Comment by lyuyuan** [comment]
Hi @thomcc , I am working on this one. Should we also remove httpRealm from the check as well? Thanks

**Comment by mhammond** [comment]
> Hi @thomcc , I am working on this one. Should we also remove httpRealm from the check as well? Thanks

Sorry to screw you around, but it's not quite clear that we should even do this, so I don't think it's actionable quite yet. It's on me to work this out.

**Comment by lyuyuan** [comment]
OK. No worries!

**Comment by jdragojevic** [comment]
closing for non-action.
