### ISSUE TITLE
Support passing a 'raw' sqlcipher key into the logins store

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#255]
At the moment we only support the variant of `PRAGMA key` that gets run through pbkdf2 internally. There's a version that doesn't (passing it in as hex), but if we wanted to support running on iOS it would be important that we allow the raw key to be specified.

**Comment by mhammond** [comment]
Thom says we probably don't need to do this.

**Comment by thomcc** [comment]
Hm, unless I'm mistaken, using the raw key syntax isn't really what you want probably, since it bypasses PDKDF2, and so keys from another version of lockbox are not compatible. (This is more of an issue for the iOS version).

I mean, if you definitely do want a version that bypasses key derivation we can give you that, but it also would have more restrictions, like requiring 64 bytes, etc.

For the grossness in the linked issue, we'd probably just prefer to move hex encoding the string it into our library (or something).

**Comment by linuxwolf** [comment]
> Hm, unless I'm mistaken, using the raw key syntax isn't really what you want probably, since it bypasses PDKDF2, and so keys from another version of lockbox are not compatible. (This is more of an issue for the iOS version).

I want something that takes bytes obtained from a cryptographically-secure source without requiring special encoding.  This is also going to be true for our iOS version.  The foreseeable plans for Lockbox don't require this key to be shared across platforms, so that kind of interoperability isn't necessary.

> I mean, if you definitely do want a version that bypasses key derivation we can give you that, but it also would have more restrictions, like requiring exactly 32 or 48 bytes, etc.

Enforcing a key length is perfectly reasonable.  This is already the case for other software dealing with keys (unless the assumption a human being is directly entering the input).  Other restrictions should not exist, though.

**Comment by thomcc** [comment]
> The foreseeable plans for Lockbox don't require this key to be shared across platforms, so that kind of interoperability isn't necessary

The interoperability is with databases on the same platform created with the version that performs a key derivation. This is also required if we're integrating into firefox-ios (short of some tricky migration logic), which we plan on doing eventually.

**Comment by thomcc** [comment]
Basically, we can't move to exclusively raw-key without adding complex code to handle opening databases written by e.g. the current firefox-ios or lockbox-ios code (which I don't think is worth it).

And so I'd prefer to solve this just basically doing the same thing you're doing at the moment, but moving it into the library. E.g. the library would take the ByteArray, hex encode it, and pass it to PRAGMA key without using raw key syntax. The only real downside here is running PBDKF2 when we don't have to which probably doesn't matter.

**Comment by linuxwolf** [comment]
> Basically, we can't move to exclusively raw-key without adding complex code to handle opening databases written by e.g. the current firefox-ios or lockbox-ios code (which I don't think is worth it).

These are fair points, and further justifies #449 being a preferred path forward.

Thanks for talking through it with me (-:
