### ISSUE TITLE
Update licensing (ios)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2551]
【 highlighted #707070 】Update the iOS licensing. 【 end highlighted 】

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2439)

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Later. In Q2 iOS is focusing on feature work. This work needs more detail what it would include.

**Comment by ddurst** [comment]
This was cancelled on the other end and has no actionable information here.
