### ISSUE TITLE
[meta] addresses rust component for desktop

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2553]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-765)
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Later. Dependent on company strategy, and whether the addresses feature on desktop is being worked on by a designated team.

**Comment by jdragojevic** [comment]
tracking as a story in jira - will add tasks once we break it out.
