### ISSUE TITLE
[meta] sync manager in desktop

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2558]
**TL;DR Why:** Integrate the Sync Manager rust component to desktop to update the current code base with more up to date, reliable, and easier to maintain code. The rust upgrade can also help us build on top of places at a quicker rate. 

The sync manager will be implemented last, once we have upgraded all other sync engines with the rust component. We are following this timeline and order for iOS rust upgrade as well.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-768)
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Later. Migrate to sync manager once all components have been upgraded to rust.

**Comment by jdragojevic** [comment]
Tracking as a jira story until we're ready to commit and break down the work.
