### ISSUE TITLE
Expose URL methods to FxAccount manager

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2563]
We should grow `getTokenServerEndpointURL` and `getManageAccountURL` methods on the manager or on an associated object.

They would call respectively the `fxa_get_token_server_endpoint_url` and `fxa_get_manage_account_url` rust functions.

The first URL is used for syncing, the 2nd by the app itself to show a link to "manage account".

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-772)
┆Story Points: 3
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-02-28

**Comment by vladikoff** [comment]
The URL might need to include the `service=sync` param to properly open webchannel communication , see this FxA test for an example: https://github.com/mozilla/fxa/blob/f67c79cffcaa9abe47898258f0b79e80b381f6b1/packages/fxa-content-server/tests/functional/fx_desktop_handshake.js#L29

**Comment by eoger** [comment]
Did we need to do the same thing for Fenix? I'm wondering if we could do the detection server-side (assuming that's how it works on Fenix) so we don't have to add yet another url method on our side.

**Comment by rfk** [comment]
> The URL might need to include the service=sync param to properly open webchannel communication

FWIW I would prefer we used the `context=` parameter to enable this behaviour rather than the `service=` parameter, although that might require some changes on the FxA side. The special behaviors we want to trigger are because of the client that's opening the page, not because of the service it's trying to connect to.

**Comment by eoger** [comment]
Wouldn't the following take care of opening the WebChannel communication?
https://github.com/mozilla/application-services/blob/b20fc14648779d75a1e2d195f0e2c4bbbd29b51e/components/fxa-client/src/oauth.rs#L205

Firefox iOS [does use the correct redirect URI](https://github.com/mozilla-mobile/firefox-ios/blob/5869811c5dfc78064fb41245aae87edeeac41e4a/RustFxA/RustFirefoxAccounts.swift#L7) that should add this context param.

**Comment by eoger** [comment]
> Did we need to do the same thing for Fenix? I'm wondering if we could do the detection server-side (assuming that's how it works on Fenix) so we don't have to add yet another url method on our side.

So Fenix doesn't have this link. I guess we could modify the `getManageAccountURL` method and add a 2nd `context` parameter maybe?

**Comment by rfk** [comment]
> So Fenix doesn't have this link. I guess we could modify the getManageAccountURL method
> and add a 2nd context parameter maybe?

We could make this decision internally, in the same way that `oauth_flow` currently decides how to add the `context` parameter.

**Comment by eoger** [comment]
@vladikoff should we open a bug on the FxA side?

**Comment by eoger** [comment]
I found https://github.com/mozilla/fxa/issues/3116, let me know if we should wait for this to be done or if we should just add a short/medium-term hack that appends `service=sync`.

**Comment by vladikoff** [comment]
> or if we should just add a short/medium-term hack that appends service=sync.

in @garvankeeley 's patch we also had to add the context. so the added URL was `service=sync&context=oauth_webchannel_v1` 

>  in the same way that oauth_flow currently decides how to add the context parameter.

This is done by looking at the redirect uri of the oauth client, which I don't think we save into the state?

**Comment by vladikoff** [comment]
Looking into this for the management url...

**Comment by vladikoff** [comment]
in my testing, this is enough: https://accounts.firefox.com/settings?&context=oauth_webchannel_v1
