### ISSUE TITLE
Monitor rollout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2580]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-784)
┆Epic: FxA for Firefox iOS

**Comment by rfk** [comment]
Heh, these really don't map well into clear and actionable github issues without all the extra context from Jira :-)

**Comment by jchaupitre** [comment]
I went ahead and deleted these tasks from JIRA and will be using the User Story to capture the effort (story points) as we wait to decompose this story into real tasks. That way Github will not get these tasks, and yet the effort estimate will be reported in our JIRA burndown.

**Comment by jchaupitre** [comment]
Feel free to close this issue (again), I don't seem to be able to >.>
