### ISSUE TITLE
[logins] Temporarily disable "default" rust-android-gradle target

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#259]
After #254, we started requiring Desktop libraries for OpenSSL and SQLcipher, and we started requiring Cargo to build for non-Android architectures.  That's fine, but we need to get these things in place in automation to avoid failures like https://tools.taskcluster.net/groups/FoNU4ti4Qja4RGLwWwAdng/tasks/FoNU4ti4Qja4RGLwWwAdng/runs/0/logs/public%2Flogs%2Flive.log.  Temporarily we're going to disable the Gradle "default" target to `rust-android-gradle` while we address these automation changes.

This fits into the ecosystem that #138 envisions.

**Comment by thomcc** [comment]
I said this in slack but for posterity, it would be nice to re-enable this and run tests against the kotlin/rust integration on PRs and such.

**Comment by mhammond** [comment]
This has been reenabled.
