### ISSUE TITLE
Write a remerge schema for extension-storage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2596]
Part of desktop integration work. Can be done in parallel with most other things.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-795)
┆Story Points: 2
┆Epic: Update Firefox extension preference syncing to use Sync15

**Comment by glasserc** [comment]
```json
{
    "version": "1.0.0",
    "name": "storage-sync",
    "fields": [
        {
            "name": "id",
            "type": "own_guid",
        },
        {
            "name": "extension_id",
            "type": "text",
        },
        {
            "name": "payload",
            "type": "untyped_map"
        }
    ],
    "dedupe_on": ["extension_id"],
}
```

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

We've decided to not use remerge for extension preference syncing. Closing these issues.
