### ISSUE TITLE
PlacesException: Error executing SQL: Conversion error from type Text at index: 4

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2607]
```
[INFO] mozilla.appservices.places.PlacesException: Error executing SQL: Conversion error from type Text at index: 4, invalid utf-8 sequence of 1 bytes from index 28
```

See https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963672/ for details

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-804)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by rfk** [comment]
From slack: "it’s an unexpected exception coming out of the bookmark migration, so in this particular case we would have failed to migrate any bookmarks. Can ya’ll look into what happened here, or at the very least make sure issues like this are handled on per-record basis?".

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Actually this is referring to the same sentry error as SYNC-748 where it appears @lina has a good understanding of what's going on.  Closing this as a duplicate.

**Comment by mhammond** [comment]
It's actually a different issue
