### ISSUE TITLE
FxA.ensure_capabilities should not write to the server if nothing has changed

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2614]
As noted in https://github.com/mozilla/application-services/issues/2415#issuecomment-584465271, every time the application calls `FxA.ensureCapabilities` it results in a write to the FxA server to update the device record.

I expect that in the majority of cases this write will be entirely spurious, since nothing will have changed since the device record was originally created. Worse, because of the way we re-encrypt the send-tab command data every time we update the device record, there is no way for the server to *tell* that the writes are spurious - every write looks like we're changing the send-tab keys, even though we're usually just re-encrypting the same keys and re-uploading them, and the server must write out the update to storage.

The result is unnecessary network activity for the client, and unnecessary write load for the FxA database. I expect the write load might end up being troublesome at the scale of the Fennec release population, and it will *definitely* be unsustainable when we eventually go to land this code in desktop.

Let's rejigger the device-registration logic so that it avoids sending spurious writes to the server. This may mean that we'll need to keep more of the registration state inside our client-side local state, but I think the overall health of the system will be worth it.

@eoger @vladikoff what do you think?

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-809)
┆Story Points: 5
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by rfk** [comment]
What I'd *like* to do here, is to have the client keep a copy of its current device record in the persisted account state, and track whether or not that needs to be flushed to the server. But I expect that would require a `StateV3` migration in order to do cleanly, and I'm not sure the the risk/benefit tradeoffs are worthwhile at this point in the release cycle.

Instead, what I think I will do is have `ensure_capabilities` store the current set of capabilities in the persisted account state as a new field. Subsequent calls to `ensure_capabilities` can check against this set and only write to the server if there is a change. There may be some edge-cases around managing the send-tab keys here (e.g. we need to re-upload them if `kSync` changes) but hopefully that will be manageable.

I hope to work on this over the next couple of days, just wanted to post a quick update so that @eoger can intervene early if this sounds like a bad plan...

**Comment by eoger** [comment]
> What I'd _like_ to do here, is to have the client keep a copy of its current device record in the persisted account state, and track whether or not that needs to be flushed to the server. But I expect that would require a `StateV3` migration in order to do cleanly, and I'm not sure the the risk/benefit tradeoffs are worthwhile at this point in the release cycle.

If that's needed, I'm not too worried about a state migration as we benefit from the amazing Rust typing system here. It sounds like the most robust solution. We could also consider asking the FxA server to keep device records in cache and update only if necessary? (do these commands endpoint calls also trigger the "spurious updates" mechanism?)

> Instead, what I think I will do is have `ensure_capabilities` store the current set of capabilities in the persisted account state as a new field. Subsequent calls to `ensure_capabilities` can check against this set and only write to the server if there is a change. There may be some edge-cases around managing the send-tab keys here (e.g. we need to re-upload them if `kSync` changes) but hopefully that will be manageable.

That's fine too, you could probably also hack your way around changing the JSON state using `self.state.commands_data`, however I don't recommend it as it will be very unclear what is the intent of that piece of state here.

**Comment by rfk** [comment]
> We could also consider asking the FxA server to keep device records in a memcache
> and update only if necessary?

This would solve the write-load problem (and we're doing it for some other things) but it's still unnecessary battery-draining network activity for the user, so I think it'd be better to address the issue on the client.

> (also do these commands endpoint calls also trigger the "spurious updates" mechanism?)

I'm not entirely sure I understand your question, but the FxA server does try to check whether the incoming set of commands is different from the set it currently has on disk, and only write out the change if it's different. But in our case the commands will always be different because we re-encrypt the send-tab keys with a fresh IV on every upload.

**Comment by rfk** [comment]
> Instead, what I think I will do is have ensure_capabilities store the current set of capabilities
> in the persisted account state as a new field

So, looks like we actually do this already, in the `device_capabilities` field. I think a quick fix here would be to update [`ensure_capabilities`](https://github.com/mozilla/application-services/blob/d9bcd9391d06b4b782f51e35d108aa5fdd20690a/components/fxa-client/src/device.rs#L88) so that is compares the passed-in `capabilities` set with the set stored in `self.state.device_capabilities`. If they're the same, then it can exit early rather than uploading the same set of device commands data all over again.

There's a warning on `ensure_capabilities` to make sure you call it when the sync keys change, so I guess in theory this check should also confirm whether the sync keys have changed since we last write out an update to the server. But I don't think we'll ever actually hit that case in practice right now, because the only way to obtain the new sync keys is to sign back in, which would generate a fresh `FirefoxAccount` state on the client anyway.

@lougeniaC64, as discussed on slack, let me know if you'd like to take this on this week (and if so, whether the above makes sense as an approach).

**Comment by rfk** [comment]
In terms of "knowing when we're done", a suitable testcase for this issue would be something like:

* Create a `FirefoxAccount`, sign it in, and make an initial call to `ensure_capabilities()`.
* Serialize it to a string, deserialize to a fresh instance, then call `ensure_capabilities()` call again.
    * If the args to the second call are the same as the args to the first, it should not make any network requests.
    * If the args to the second call are different than the args to the first, it should make a network request to update the device record.

I think we already have the necessary bits to do those tests in this component, thanks to the nicely-mockable `FxAClient` trait.

**Comment by rfk** [comment]
This was fixed in https://github.com/mozilla/application-services/pull/2681
