### ISSUE TITLE
Delete databases detected as corrupt at open time

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#2628]
All of our sqlite using components suffer from database corruption. In some cases the corruption is detected at the time of opening the database, in which case recovery of the data is not feasible programmatically. In other cases the corruption is reported/detected as the database is being used, which is #4639 - this issue is only about failure to initially open the database.

The general process should be that the [code which opens most of our databases](https://github.com/mozilla/application-services/blob/main/components/support/sql/src/open_database.rs#L110) should, iff `SQLITE_OPEN_CREATE` is in the flags (ie, so that this open would create the database if it didn't already exist) handle *just* the 2 error codes `SQLITE_CORRUPT` and `SQLITE_NOTADB`, and in that scenario, rename the database (to, say, the base-name plus ".corrupt"), then retry the operation with the exact same flags we before.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2445)
┆Epic: Important backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

[~amedinac@mozilla.com] - this issue would need a product decision (between you and Vesta) for the preferred way to resolve the issue and then we'd want to clone this or all Fenix synced data types.

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

I assume deleting the corrupt database would mean loss of user data?

**Comment by mhammond** [comment]
> I assume deleting the corrupt database would mean loss of user data?

We should consider that the data loss happened at the time the database become corrupt. Worse, the user has lost their data - but will also be unable to save new data (eg, they will have lost all their bookmarks, and will be unable to create new ones). 

While the corrupt database remains in place, the app will be completely broken for the user. While deleting the database will not recover their lost data, it will make the app usable for them again.

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Thanks for the thorough response Mark! I think deleting the corrupt databases makes sense. The risks are offset by the broken user experience.

**Comment by rfk** [comment]
I think this could be a good-first- or good-second-issue if we provide a bit more detail. Specifically things like:

* Do we want to restrict this to errors when opening the file, or to more general schema-related errors that might be encountered at runtime?
* Do we want to keep a backup of the database file just in case, for future recovery/debugging?

**Comment by XaurDesu** [comment]
Is this issue being worked on? I might want to take a look at this.

**Comment by mhammond** [comment]
> Is this issue being worked on? I might want to take a look at this.

Sorry for the delay and thanks for your interest! It's not being worked on and I updated the description to better reflect what needs to happen.

**Comment by mhammond** [comment]
Done in #4444
