### ISSUE TITLE
Make sure CWTS is on the same page in Rust FxiOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2630]
This is the new experiment in FxA that puts CWTS on the same page.

See 
https://mozilla.slack.com/archives/C4D36CAJW/p1581460669175200?thread_ts=1581457529.172900&cid=C4D36CAJW for details.

When we get the Rust FxiOS component working, then we should make sure we use the new design

<img src=https://user-images.githubusercontent.com/128755/74283975-e66d3480-4cf0-11ea-97b9-25afc0a0b526.png width=300 />

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-818)
┆Story Points: 3
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-03-27

**Comment by vladikoff** [comment]
This is blocked on https://github.com/mozilla/fxa/issues/4159, I looked at the fxa bit of this and it will a bit of refactoring on the FxA side. We can block on that for now.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

:triangular_flag_on_post: Flag added

Blocked on some ios work, and not a blocker for the whole epic.
