### ISSUE TITLE
Hook up FxA iOS migration data

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2639]
We output some migration details after migration completes. We need to coordinate with iOS engineering to report that data to metrics.

Read [https://github.com/mozilla/application-services/pull/2637#discussion_r378371681](https://github.com/mozilla/application-services/pull/2637#discussion_r378371681) for details.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-822)
┆Story Points: 3
┆Epic: Work required to support operationalizing and shipping the iOS / FxA-client integration
┆Sprint: SYNC - end 2020-03-27

**Comment by data-sync-user** [comment]
➤ Julien Chaupitre commented:

[~vfilippov@mozilla.com] could you please formulate an estimate (in story points field) for this task so that our release burndown reflects this effort. Thanks!

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Small change from SACI team and require coordination with iOS team.

**Comment by vladikoff** [comment]
Ref: https://mozilla.slack.com/archives/CKL0LGV9B/p1584646568123500?thread_ts=1584645920.123000&cid=CKL0LGV9B
