### ISSUE TITLE
Interrupting Places autocomplete queries

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#265]
On Desktop, we cancel pending searches when the user types more text into the awesomebar, to avoid running unnecessary queries and returning stale results. Desktop runs all autocomplete queries asynchronously, on the connection's storage thread, and interrupts all statements on the connection when a search is cancelled.

I'm not sure if we can, or want to, do this in Rust, though. Our Rust Places library runs its statements synchronously, and expects consumers to handle threading.

We _could_ use something like a cancellation token, with an atomic `cancelled` property that our search function could check and stop running additional queries. However, I think any pending queries would still need to run to completion, blocking the thread until they're done. rusqlite doesn't support `sqlite3_interrupt`, since it needs to be called from a different thread, and rusqlite connections aren't thread-safe.

With those restrictions, I'm not sure if implementing cancellation is worth it...but it's some food for thought. 🌭 🤔 WDYT, @thomcc and @mhammond?

**Comment by ncalexan** [comment]
Richard and I assumed that we'd launch a separate thread and kill it for this type of support in Mentat: https://github.com/mozilla/mentat/issues/297.

**Comment by thomcc** [comment]
Rust apparently doesn't offer a way to kill a hung thread. Cool.

**Comment by thomcc** [comment]
> Rust apparently doesn't offer a way to kill a hung thread. Cool.

It does give us access to the `pthread_t` on unix though, so we could always call `pthread_cancel` on that (very unsure what level of 'dodgy things unsafe code can do' this is at).

On windows we can get the `HANDLE` but calling `TerminateThread` outside of shutdown is... probably a mistake. For some reason I thought there was another win32 function for this but it looks like I'm just wrong.

Anyway, I thought I linked this, but I did not; the rusqlite bug for this is https://github.com/jgallagher/rusqlite/issues/407.

**Comment by thomcc** [comment]
Adding support to this to rusqlite directly was easier than I expected (barring issues brought up by review / problems in my code), so it's likely we won't need to figure out ways of killing threads: https://github.com/jgallagher/rusqlite/pull/408

**Comment by thomcc** [comment]
This is done.
