### ISSUE TITLE
Choose What To Sync is not displayed when creating a new account on Fenix Nightly

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2650]
As noted in https://github.com/mozilla-mobile/fenix/issues/6737#issuecomment-565011047, it seems that FxA is not showing the "Choose What To Sync" page when creating a new account through Fenix Nightly. I just tried it myself this morning and was able to reproduce - I see marketing opt-in checkboxes rather than the CWTS checkboxes.

STR:

* Install Fenix Nightly.
* Settings -> Turn on Sync -> Use email instead
* Sign in by creating a new Firefox Account

Expected result:

I should be shown the "choose what to sync" options during the signup flow.

Actual result:

I am not shown any "choose what to sync" options, am instead and automatically defaulted into syncing all available datatypes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-830)
┆Story Points: 5
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by rfk** [comment]
> the if check probably needs to removed or needs to configurable on the client / app

Digging into the code here, I think the linked line about `fxaCapabilities` looks OK as-is; it comes in via [the arguments to `FxaWebChannelFeature`](https://github.com/mozilla-mobile/android-components/blob/82c84b3b8170239442d687216f91ed5387b8fde9/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FxaWebChannelFeature.kt#L56), and Fenix does seem to be [including CHOOSE_WHAT_TO_SYNC](https://github.com/mozilla-mobile/fenix/blob/9bac7ef47bcf8ecb9825b38275fe00a6a88239e5/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L458) in the provided set.

So I'm not sure what's going on here, will try to debug with a local build and some extra logging.

**Comment by rfk** [comment]
I see the following in my logcat, which seems to indicate that the app is correctly sending the `choose_what_to_sync` capability:

```
02-18 12:15:20.335 23576 23653 E GeckoConsole: [JavaScript Error: "account_updates error message. No Such Channel" {file: "resource://gre/actors/WebChannelParent.jsm" line: 94}]
02-18 12:15:20.335 23576 23653 E GeckoConsole: _sendErrorEventToContent@resource://gre/actors/WebChannelParent.jsm:94:8
02-18 12:15:20.335 23576 23653 E GeckoConsole: receiveMessage@resource://gre/actors/WebChannelParent.jsm:50:16
02-18 12:15:20.335 23576 23576 D mozac-fxawebchannel: Processing WebChannel command: FXA_STATUS
02-18 12:15:20.345 23576 23653 D GeckoViewConsole: onEvent GeckoView:WebExtension:PortMessageFromApp {"portId":137438953474,"message":{"id":"account_updates","message":{"messageId":"15819885203321","data":{"capabilities":{"engines":["history","bookmarks","passwords"],"choose_what_to_sync":true},"signedInUser":null},"command":"fxaccounts:fxa_status"}}}
02-18 12:15:20.345 23576 23653 D GeckoViewConsole: onEvent GeckoView:WebExtension:PortMessageFromApp {"portId":137438953474,"message":{"id":"account_updates","message":{"messageId":"15819885203321","data":{"capabilities":{"engines":["history","bookmarks","passwords"],"choose_what_to_sync":true},"signedInUser":null},"command":"fxaccounts:fxa_status"}}}
```

I am slightly concerned about the lines from geckoview saying that there is no such channel and it is sending an error to the web content, and I wonder if the (hidden from Fenix) native WebChannel support inside GeckoView is interfering with the messages from the app.

**Comment by rfk** [comment]
> I am slightly concerned about the lines from geckoview saying that there is no such channel and it
> is sending an error to the web content, and I wonder if the (hidden from Fenix) native
> WebChannel support inside GeckoView is interfering with the messages from the app.

So yeah, if I connect to Fenix via remote debugging and view the console log for the FxA signin page, it says:

```
WebChannel error: No Such Channel
```

**Comment by rfk** [comment]
I've reached the limits of what I can productively dig in to here, and have filed https://github.com/mozilla-mobile/android-components/issues/5969 to escalate this to the experts over in a-c.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Based on the above, this appears to be far more complex than we hoped. I'm changing it from a "2" to a "5".

**Comment by vladikoff** [comment]
We did notice this first in Nightly, rather than Release, so there could be some regression in Geckoview related to this.

**Comment by vladikoff** [comment]
@rfk commenting out this bit: https://github.com/mozilla/fxa/blob/25f33db4437b980f479911eea36ace35728c00df/packages/fxa-content-server/app/scripts/lib/channels/web.js#L107

makes the CWTS work again.

**Comment by rfk** [comment]
Interesting! I guess that commenting out that line, means FxA continues listening for additional responses and receives the correct response from Fenix. I guess we could use that as an opportunity to hack around the problem if it proves hard to resolve this in GeckoView?

**Comment by vladikoff** [comment]
>  I guess we could use that as an opportunity to hack around the problem if it proves hard to resolve this in GeckoView?

Yeap! Gonna think through a fix

**Comment by rfk** [comment]
> fix

To be clear, I would consider anything we do on the FxA side here to be a workaround for bad client behaviour rather than a fundamental fix for this issue. (Which doesn't mean we shouldn't do it)

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

PR in https://github.com/mozilla/fxa/pull/4188
