### ISSUE TITLE
[Fenix] Add menu to use custom FxA/Sync server

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/application-services#2651]
Build:
Stage [Train 1.157.0]

Affected platforms:
Android 9

**Steps to reproduce:**
1. Launch Fenix Nightly and navigate to about:config.
2. Change the following prefs:

    - Identity.fxaccounts.auth.uri - https://api-accounts.stage.mozaws.net/v1
    - Identity.fxaccounts.remote.oauth.uri - https://oauth.stage.mozaws.net/v1
    - Identity.fxaccounts.remote.profile.uri - https://profile.stage.mozaws.net/v1
    - Identity.fxaccounts.remote.webchannel.uri - https://accounts.stage.mozaws.net
    - Identity.sync.tokenserver.uri - https://token.stage.mozaws.net/1.0/sync/1.5

3. Restart the app
4. Login using a stage Firefox account.

**Expected results:**
Firefox account is successfully logged in.

**Actual Results:**
The FxA signup/login urls point to FxA production. E.g  https://accounts.firefox.com/oauth/signin?action=email&response_type=code&client_id=a2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=K2zoypeBsIHiSbcVE-f78w&code_challenge_method=S256&code_challenge=hLMQM9ek090I1dUClvWV2qJqavtxl5i8nsNa2NfjZDE&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6Ikl2ZU5wVmktbTVKQ0lqTERrTk9DNS1pSjlEN0JtZ1JONmJWY2owMFNfeWciLCJ5IjoiY192bEdPZGN3a2xqLUtUR05ITDRwS1dMeVgwQ25tdWdkOG96VXNPc2l4cyJ9&context=oauth_webchannel_v1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-928)
┆Story Points: 5
┆Epic: Allow QA testers to set a different FxA server (stage, stable etc) and a custom Sync storage backend.
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I'm tentatively suggesting that we take a look at this for the "integration testing of a-s" epic, since being able to use a custom server deploy is definitely part of a smooth end-to-end integration testing experience.

**Comment by rfk** [comment]
I believe this has landed or is very close to doing so, @eoger should we close this out here in github?

**Comment by eoger** [comment]
Not yet, it's still not reviewed yet (but the dependant pieces indeed have landed), let's keep this here to track the work of mozilla-mobile/fenix#8916.

**Comment by eoger** [comment]
Fixed by  mozilla-mobile/fenix#8916.
