### ISSUE TITLE
Remove / combine trivial utility dependencies from remerge

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2652]
Part of vendoring remerge dependencies:

Remove our trivial internal utility dependencies

* `error-support` (maybe no longer useful)
* move `interrupt-support` into `sync15_traits

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-832)
┆Story Points: 2
┆Sprint: SYNC - end 2020-03-13

**Comment by glasserc** [comment]
We use `error-support` in https://github.com/mozilla/application-services/blob/master/components/remerge/src/error.rs#L55 to define a bunch of conversion machinery. It's easy to write this machinery once by hand but I'm intrigued by your statement that `error-support` might no longer be useful. Could you elaborate on that? It sounds like you want to change the way error handling in this crate works but I'm not exactly clear how. Indeed I'm not really even sure I understand the strategy in play right now. I read https://boats.gitlab.io/failure/error-errorkind.html but it seems like we work a little differently here -- we don't call `.context()` on errors to "tag" them with our `ErrorKind`, instead we wrap them in our `ErrorKind` directly.

**Comment by glasserc** [comment]
We don't use `interrupt` in the Remerge component (not listed in `Cargo.toml`). We *do* use it in `sync15`. Does this issue also cover `sync15` (which also uses `error-support`)?

**Comment by thomcc** [comment]
Interrupt is used in sql-support which is used in remerge. It will also be directly used in remerge after the sync code lands but you can punt on that for now.

Error-support is the bigger dependency anyway.

**Comment by thomcc** [comment]
It might be worth leaving interrupt alone for now, since it's in so many things which don't share any other common dependencies...

**Comment by glasserc** [comment]
Discussed this on Slack briefly. Thom says that `error-support` is a "pretty hacky macro" and that there are other crates that do similar things, for example `thiserror`. He said he would flesh out this issue a bit more tomorrow.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Closing since we're not moving forward with remerge to desktop at the moment.
