### ISSUE TITLE
Cleanly rebuild the aar when rust code changes

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2659]
I am not a gradle expert so I'm not sure if this is how things are intended to work, but our build system regularly violates my expectations of how it *should* work, because it fails to include changes to rust code when doing `publishToMavenLocal`.

An example of what I mean:

**STR:**

First, some setup:

* Set `rust.targets=arm` in `local.properties`, to shorten your compile cycle.
* Add the line `log::warn!("\n\nUNIQUE STRING NUMBER 1\n\n.")` somewhere in the FxA component rust code.
* Build and publish the Lockbox megazord via `./gradlew lockbox:publishToMavenLocal`
* Confirm that the unique string is present in the resulting `.aar` file:

```
rfk@pomelo:~$ unzip -c ~/.m2/repository/org/mozilla/appservices/lockbox-megazord/0.51.1/lockbox-megazord-0.51.1.aar jni/armeabi-v7a/liblockbox.so | grep --text "UNIQUE STRING"
UNIQUE STRING NUMBER 1
```

Now, pretend you're hacking on the rust code and want to try out your changes:

* Alter your log line to be `log::warn!("\n\nUNIQUE STRING NUMBER 2\n\n.")`.
* Re-build and publish the Lockbox megazord via `./gradlew lockbox:publishToMavenLocal`
  * Observe that it runs cargo to rebuild the rust code, as expected.
* Look for the unique string in the updated `.aar` file.

**Expected result:**

* Grepping for the unique string should produce `UNIQUE STRING NUMBER 2`.

**Actual result:**

* Grepping for the unique string still produces `UNIQUE STRING NUMBER 1`.
* In fact the `.aar` does not seem to have been updated at all (timestamps etc are all the same as they previously were).

----

I can only presume that we're somehow failing to tell gradle about the dependency relationship between the results of `cargo build` and the resulting `.aar`. Looking at the last-modified timestamps on various files named `liblockbox.so` shows:

```
rfk@pomelo:application-services(master *$)$ find . -name "*lockbox*.so" | xargs ls -l
-rwxrwxrwx 1 rfk rfk  3846316 Feb 17 14:04 ./megazords/lockbox/android/build/intermediates/library_and_local_jars_jni/release/armeabi-v7a/liblockbox.so
-rwxrwxrwx 1 rfk rfk 24814932 Feb 17 14:04 ./megazords/lockbox/android/build/intermediates/merged_jni_libs/release/out/armeabi-v7a/liblockbox.so
-rwxrwxrwx 1 rfk rfk 24814932 Feb 17 14:04 ./megazords/lockbox/android/build/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/liblockbox.so  
-rwxrwxrwx 1 rfk rfk  3846316 Feb 17 14:04 ./megazords/lockbox/android/build/intermediates/stripped_native_libs/release/out/lib/armeabi-v7a/liblockbox.so
-rwxrwxrwx 1 rfk rfk 24814912 Feb 17 14:15 ./megazords/lockbox/android/build/rustJniLibs/android/armeabi-v7a/liblockbox.so
-rwxrwxrwx 2 rfk rfk 24814912 Feb 17 14:15 ./target/armv7-linux-androideabi/release/deps/liblockbox.so
-rwxrwxrwx 2 rfk rfk 24814912 Feb 17 14:15 ./target/armv7-linux-androideabi/release/liblockbox.so
```

Which tells me that the files under gradle's control in `./megazords/lockbox/android/build/intermediates/` have not been updated since the original build, while the ones cargo's control have been updated.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-840)
┆Story Points: 3
┆Epic: Integration testing for a-s
┆Sprint: SYNC - end 2020-03-13

**Comment by rfk** [comment]
I made a [gradle build scan](https://scans.gradle.com/s/yvhsjw4rb2qem/timeline) which IIUC confirms this to be a dependecy-tracking issue, as it shows the various jni-lib-related packaging tasks reporting that they are `UP-TO-DATE` despite cargo-build being re-run and changing the underlying libs.

**Comment by rfk** [comment]
I can't spend any more time on this, but have posted #2663 with a workaround that seems to do the job on my machine. I'll see if I can repro on a sample project and file an issue upstream on the rust-android-gradle project, since AFAICT this is either a code issue (not automatically configuring dependencies property) or a docs issue (not telling us how to configure dependencies properly in our project).

**Comment by rfk** [comment]
> I'll see if I can repro on a sample project 

This issue does *not* reproduce on the sample app in the rust-android-gradle project.

**Comment by rfk** [comment]
This was closed by landing this above work-around, but it's pretty gross and we should figure out what the underlying issue was. I'm going to re-title this issue to be about finding a proper fix, and we can triage it into some important-not-urgent category.

**Comment by ncalexan** [comment]
> /cc @ncalexan, I know you're not really working on the rust/gradle stuff anymore, but adding you just in case the issue description here rings any bells for you about something we might be missing.

I spent the hour of the MoCo meeting trying to track this down.  I think that as the Android-Gradle plugin has evolved, the details around stripping the native libraries has changed, and somehow updating a `.so` in a `srcDir` no longer gets recognized as a change.  This sure looks like a bug in the plugin itself, but reading the source I can't see how other things (like, say, the NDK build support in the plugin) does this differently.

Sorry that I also can't improve this right now.
