### ISSUE TITLE
Cannot sync bookmarks on Firefox iOS

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2667]
When using the "Rust FxA" branch of Firefox iOS, I'm getting the following when trying to sync:

```
[RUST][ffi_support::handle_map] HandleMap access with handle having wrong map id: Handle { map_id: 39227, version: 2, index: 0 } (our map id is 39228)
```

After some investigation I've concluded that `resetBookmarkSyncMetadata` should not take an `API` handle but a `Connection` one.
What's very strange about this is that the `master` branch of Firefox iOS does not show this behaviour, despite calling the same FFI function with the same wrong handle (and the presumed bug has been present for month).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-845)
┆Story Points: 5
┆Sprint: SYNC - end 2020-02-28

**Comment by eoger** [comment]
More investigation:

It looks like https://github.com/mozilla/application-services/commit/c2fdfc85e61aeb4c96be10e2f27afcf6d6f35c8d#diff-1d157ec195946881dc83a97db5fb09bf caused the regression: we went from an `API` handle to a `Connection` one, but we didn't make the change on the Swift side. The change is fairly recent, so I'm guessing that's why Firefox for iOS isn't affected yet.

**Comment by eoger** [comment]
> The change is fairly recent, so I'm guessing that's why Firefox for iOS isn't affected yet.

Confirmed. Upgrading to `v0.48.3` breaks Sync on iOS:

```
2020-02-18 11:41:55.315 [Debug] [Profile.swift:1077] takeActionsOnEngineStateChanges(_:) > Already resetting clients (and tabs); not bothering to also reset tabs again.
2020-02-18 11:41:55.315 [Info] [Profile.swift:273] init(localName:syncDelegate:clear:) > [RUST][ffi_support::handle_map] HandleMap access with handle having wrong map id: Handle { map_id: 21356, version: 2, index: 0 } (our map id is 21357)
```

@garvankeeley heads up, do not upgrade to `> v0.48.2`.

**Comment by garvankeeley** [comment]
ok cool, fx-ios master is on v48.0 so it is safe from that bug
