### ISSUE TITLE
getTokenServerEndpointURL() is missing /1.0/sync/1.5

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2670]
report from @garvankeeley , the `getTokenServerEndpointURL()` is currently missing the path `/1.0/sync/1.5` 

it just returns `https://token.services.mozilla.com/`

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-847)
┆Story Points: 3
┆Epic: FxA for Firefox iOS
┆Sprint: SYNC - end 2020-02-28

**Comment by eoger** [comment]
Looks like this was the case before https://github.com/mozilla/application-services/commit/e8ba271a62ab8945b89949d831cbff7cd11c6b65.

**Comment by eoger** [comment]
I'm OK with adding the `/1.0/sync/1.5` part in Swift.

**Comment by garvankeeley** [comment]
Firefox-iOS side swift or a-s side swift?

**Comment by vladikoff** [comment]
> Firefox-iOS side swift or a-s side swift?

We are gonna add it on the a-s swift side 👍
