### ISSUE TITLE
Adjust our Taskcluster provisionner settings

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2671]
Our [Taskcluster configuration](https://firefox-ci-tc.services.mozilla.com/worker-manager/app-services-1%2Fb-linux) seems sub-optimal:

- We provision **c5d.4xlarge** machines for our runs that come with 32GiB of memory and 16 vCPUs. We could switch to **c5d.2xlarge** machines which come up with 16GiB of memory (more than enough to avoid Out Of Memory errors) and 8 vCPUs. They cost half as much, $0.38/hour versus $0.76/hour, and we believe just doing this small change would divide our costs by two. We would need to check if that CPU change affects the build times significantly.
- Our minimal capacity is set to 2 machines, which means at any time of the day we have at least 2 machines potentially idling waiting for runs. Our CI runs take between 3 (pull-requests) to 15 (master merge) machines to run. So this means these 2 machines idling are not even enough to cover the basic case and new machines are started in response (scale-up) anyway. We recommend to set the minimal capacity to 0 as this type of machine can start up pretty fast.
- After scaling-up, machines take 15 minutes (shutdown.afterIdleSeconds = 900) to be shut-down. We believe in with a 40min average run you'd be very lucky to end up re-using a machine that was previously used to run another task. We recommend shutting down the machines right after they are done running their tasks.

We believe these kind of low-hanging fruit changes could reduce the cost of our runs from 50% to 80%.

@MihaiTabara what do you think about these adjustments?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-848)
┆Sprint: Backlog

**Comment by eoger** [comment]
See also https://github.com/mozilla/application-services/issues/1502 for more cost savings.

**Comment by MihaiTabara** [comment]
Sorry, this slippsed my radar somehow, just found it in triaging in my Github inbox. Adding it to my todo list, will come back with an answer, hopefully by EOW.

**Comment by MihaiTabara** [comment]
Found in my todo list, touching base on this, I've started working on moving this repo to `taskgraph` so I'll be looking closer to this issue too this week, please accept my apologies for the delays.

**Comment by vladikoff** [comment]
👍

**Comment by eoger** [comment]
I believe this was done.
