### ISSUE TITLE
Build the Carthage MozillaAppServices binary for distribution

### ISSUE THREAD

**Issue by michaeleisel** [mozilla/application-services#2673]
As of https://github.com/Carthage/Carthage/pull/2902 , Carthage now takes advantage of Swift 5.1's module stability. This means that MozillaAppServices can be downloaded and used, rather than compiling from scratch, as long as the user has 5.1 or higher. The only issue right now is that MozillaAppServices appears to have `BUILD_LIBRARY_FOR_DISTRIBUTION` off. Would it be possible to change this?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-849)

**Comment by eoger** [comment]
@garvankeeley does this seem sensible to you?

**Comment by garvankeeley** [comment]
Thanks for making me aware of this! More info is here: https://swift.org/blog/library-evolution

A thousand yes to this.

**Comment by garvankeeley** [comment]
https://github.com/mozilla/application-services/pull/2675

**Comment by garvankeeley** [comment]
Now we are getting this warning, not sure of the implications since SwiftProtobuf is not shipped with a-s binary
```FxAClient/RustFxAccount.swift:6:8: Module 'SwiftProtobuf' was not compiled with library evolution support; using it means binary compatibility for 'MozillaAppServices' can't be guaranteed```

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

not actionable right now.
