### ISSUE TITLE
Add a Guid type to sync15-adapter

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#268]
There's a good one in [dogear](https://github.com/linacambridge/dogear/blob/master/src/guid.rs) which is optimized for places-style guids (e.g. 12 base64url-encoded characters). It would be better to use this than the one in `places`. 

I think the path to this would be to move it into a shared crate which is depended on (and it's types reexported by) sync15-adapter and dogear. sync15-adapter would then change to use it for the ids in various places.

I'm preemptively backlogging this since it's not really important, just would be a 'nice to have' thing.

CC @linacambridge

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-75)

**Comment by thomcc** [comment]
I did most of this in https://github.com/mozilla/application-services/tree/guid-support, which is based off of #276 (and I'll wait for that to land before PRing it).

**Comment by lyuyuan** [comment]
I was looking for a next issue and find this one still open. Are there things need to be done for this issue still?

**Comment by thomcc** [comment]
Not that I know of!
