### ISSUE TITLE
JIRA quotes are not replicated on Github

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2682]
See this comment https://github.com/mozilla/application-services/issues/2649#issuecomment-589229070 where a bunch of `{quote}` blocks make the whole formatting messed up.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-852)
┆Epic: JIRA Meta issues
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

+ [~vdoan@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Vien Doan commented:

Hi [~eoger@mozilla.com] - I've raised this issue with Unito also. Will keep you updated. Thanks.

**Comment by data-sync-user** [comment]
➤ Vien Doan commented:

Testing this to see if the change they suggested works.
{quote}This is a quoted message.
{quote}

**Comment by data-sync-user** [comment]
➤ Vien Doan commented:

Ok that did not work. Let me follow up with them again.
{quote}Did not work.
{quote}
