### ISSUE TITLE
Streamline the appservices+fenix local development workflow

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2691]
Our docs currently recommend two ways of building consuming apps against local changes to this repo: an automated-but-perpetually-buggy composite build workflow, and a reliable-but-tedious manual workflow of publishing to a local maven repo.  It's my understanding that we all currently use them manual local publication workflow because at least it works reliably.

It should not be so painful to make a local build of Fenix using a locally-modified copy of appservices. This issue tracks improving that situation. We can close it when there is a reliable way to make a local build of Fenix+appservices+android-components with a single build command.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-857)
┆Story Points: 5
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-03-13

**Comment by rfk** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/8680 for any Fenix-specific notes.

**Comment by rfk** [comment]
@eoger I wonder if you'd be willing to try out this branch while you're working on e.g. the Fenix self-hosting thing?

**Comment by eoger** [comment]
Sure! We don't have any required changes on our side to accomplish it but I'll try anyway :)

**Comment by rfk** [comment]
Waiting on the downstream consumer PRs to merge, but this is looking good on the a-s side. Ref:

* https://github.com/mozilla-mobile/android-components/pull/6218
* https://github.com/mozilla-mobile/fenix/pull/8681
