### ISSUE TITLE
[Push] Accept appServerKey in Kotlin layer as a ByteArray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#2704]
Our APIs in the GV and internal rust component handle the appServerKey as bytes. At the Kotlin layer however, the APIs there expect the key as a `String?`. It would be nicer to avoid the unnecessary conversion (`ByteArray` -> `String` ~~> `ByteArray`~~ > bytes).

This would require changes at this surface level:

* [`PushAPI.subscribe`](https://github.com/mozilla/application-services/blob/master/components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt#L346)
* [`DispatchInfo`](https://github.com/mozilla/application-services/blob/master/components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt#L261)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2450)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865161

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
