### ISSUE TITLE
[Push] Throw exceptions on invalid push subscriptions created

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#2705]
Might be a nice-to-have or require more thought: having the component catch invalid data passed to it would help us better know when a invalid keys or data are used to generate a push subscription.

Throwing an exception would be one way to handle it, which is [similar to what GV also does on their end](https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebPushSubscription.java#94-110).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2451)
┆Epic: Important backlog

**Comment by jonalmeida** [comment]
Checks for encoding/formats as well on keys would be great.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
