### ISSUE TITLE
Pass Login input struct using protobuf in Logins crate

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2713]
#2689 took care of the `logins` FFI returning the `Login` struct through JSON.
However we still pass `Login` as input using JSON, namely in `add` (see [1](https://github.com/mozilla/application-services/blob/80dd8964baafcd3a2dc2ba0251c1a01b7b5b6a26/components/logins/android/src/main/java/mozilla/appservices/logins/DatabaseLoginsStorage.kt#L239) and [2](https://github.com/mozilla/application-services/blob/80dd8964baafcd3a2dc2ba0251c1a01b7b5b6a26/components/logins/ios/Logins/LoginsStorage.swift#L315)), `update`, `ensureValid` and `importLogins`.

There are a few examples of how to pass an input as protobuf in the codebase, you can look at how `bookmarks_insert` is called from the Swift/Kotlin side to get a complete example. We also [have documentation](https://github.com/mozilla/application-services/blob/master/docs/howtos/passing-protobuf-data-over-ffi.md#using-protobuf-to-pass-data-into-rust-code) on how to do this.

This work involves playing with Swift, Kotlin, Rust and you'll get a full tour of how we communicate between all of these using FFI and protobufs.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-870)
┆Story Points: 3

**Comment by lyuyuan** [comment]
Sorry I put a typo "fixes 2773" in my PR and it failed to auto close this case :(
