### ISSUE TITLE
Automate cutting of a new release

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2716]
Our current release-cutting procedure is an [elaborate manual process](https://github.com/mozilla/application-services/blob/master/docs/howtos/cut-a-new-release.md) that contains plenty of room for human error, and some steps that are open to human judgement (such as "manually test the changes versus the samples in android-components").

Let's automate this. We might not speed it up, but we can make it more reliable.

Here's what I'd like to be able to do when cutting a release:

1. I run `./automation/prepare-release.sh [major|minor|patch]`
    1. It does various coherency checks (e.g. no uncommitted changes, commit exists remotely).
    2. It does all the mechanical changes to the changelog, build-version, etc (or errors out and tells me to fix things if they're not as expected)
    3. It commits the changes on an appropriately-named branch, pushes to github, and opens a PR for review.
        1. CI kicks off with our even-more-thorough-than-usual test runs for the release candidate.
2. I may run some local manual tests on the resulting commit, e.g. building Fenix and smoketesting it. I'd like to automate this as well, but let's automate one thing at a time...
3. I wait for the release commit to be approved
4. I run `./automation/tag-release.sh #pr-number`
    * It checks CI and review status
    * It creates the new release (and corresponding tag) on github
    * It merges the PR

I think this would be a marked quality-of-life improvement over the current process. There are ways we could improve it further from there, such as having step (4) run by a bot like bors, and adding more tests into step (1.iii.a), but they can be for followup work.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-876)
┆Story Points: 5
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-04-10

**Comment by eoger** [comment]
Note for 4. we will want to make sure `master` hasn't changed since we created the cut release PR so changes don't sneak in.

**Comment by eoger** [comment]
We are happy with what we got so far (implemented 1., 2. in another PR), let's close this.
