### ISSUE TITLE
Blog RSS feed has 404 URLs

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/application-services#272]
There are two issues with the RSS feed on https://mozilla.github.io/application-services/blog/.
1. The atom and RSS URL in `<link>` are https://mozilla.github.io/application-services/application-services/blog/feed.xml, with duplicated `application-services` in the path.
1. If I open the correct URL https://mozilla.github.io/application-services/blog/feed.xml, the links to posts contain `application-services` duplicated again.

**Comment by shane-tomlinson** [comment]
Thanks @MikkCZ - I think I fixed the problem, mind giving it a try again?

**Comment by MikkCZ** [comment]
Thanks Shane. It works correctly for me now.

**Comment by shane-tomlinson** [comment]
Thanks for checking @MikkCZ, closing this as fixed!
