### ISSUE TITLE
Scope out what exactly we want to accomplish for the automated smoke tests.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2724]
Scope out automated smoke tests.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-883)
┆Story Points: 3
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-03-13

**Comment by rfk** [comment]
Summarizing various discussions:

* We want to have a repeatable procedure for doing basic "does everything seem to be working happily?" tests in our major consumers (android-components, fenix, firefox-ios)
* We do not want to encourage consumers to do broad functionality testing of our components; they should be able to assume that our code works as advertised!
* We do not want to take on a bunch of extra work for our team maintaining tests across several downstream repos.

To try to set the right scope here, I've made 6 delierately-busted branches of the application-services repo:

* Simulate a type mismatch in sync-manager FFI layer. [#2804]
* Simulate a missing symbol in the fxa-client build. [#2802]
* Simulate a problem with reading a bookmarks tree. [#2805]
* Simulate a problem with consumer integration of viaduct. [#2806]
* Simulate a problem with writing logins to disk. [#2807]
* Simulate architecture-specific missing symbols. [#2808]

Some are designed to loosely simulate real integration-level bustage that we've seen in the past. Some are designed to simulate bustage in the "happy path" of using our components, that might result from e.g. a bad refactor on either side of the integration boundary. Taken together, I think that if we have a testsuite that could be used to detect all 6 of these hypothetical busted a-s releases, we'd be in a substantially better place than we are right now.

Suggestions for additional testcases, or modifications to the above, are most welcome!

(To be clear: our own CI catches some of these already, although not all of them. I want to treat them as stand-ins for the sort of bustage we might expect to catch when smoketesting downstream consumers, not necessarily as actual bugs we're at risk of shipping.)

So, the goal of issues #2718, #2719, #2720 will be to see if we can have a single test command for each of android-components, fenix, and firefox-ios that, if run against each of the above busted PRs, would detect the bustage.

**Comment by mhammond** [comment]
> Suggestions for additional testcases,

I wonder if we can leverage logs somehow? They've been necessary to identify and verify fixes for various regressions. A trivial example: "It's bad if  'fetching token from ...' appears more than once". "It's bad if any logs at ERROR level appear", etc. No idea how to make something this vague into something that would work, but it might be worthwhile thinking about...

**Comment by mhammond** [comment]
(oops - just realized I commented after seeing the *closed* notification 🤣 )
