### ISSUE TITLE
Investigate potential benefits/costs/process of publishing snapshot builds from feature branches

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2726]
┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-886)
┆Epic: Integration testing for a-s

**Comment by rfk** [comment]
From discussion, we decided we're likely to get much of the benefit of this from nightly builds of master, so we're going to close this issue for now. We can pick it up again at some later time if we find ourselves doing work that would obviously benefit from this.
