### ISSUE TITLE
Expose FxA China stack urls in FxA's configs, like the release/stable/dev ones

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/application-services#2735]
This was very briefly mentioned by @garvankeeley & @rfk in slack.

I have no idea whether this should live in Kotlin/Swift or Rust, or maybe both. But I think it'll make it easier to add China FxA support in Firefox for iOS, Fenix, Lockwise for Android/iOS and other future applications.

Thanks!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-892)
┆Story Points: 1
┆Epic: iOS Fxa-client integration productionizing
┆Sprint: SYNC - end 2020-03-13

**Comment by data-sync-user** [comment]
➤ Julien Chaupitre commented:

[~rkelly@mozilla.com] shared the following details in meeting doc:


* Looks like it may be as simple as setting your current locale to zh_CN:[ https://github.com/mozilla-mobile/firefox-ios/blob/bf118e4b97c620e804e89e149b9ca85d7a8dce9e/Providers/Profile.swift#L569|https://github.com/mozilla-mobile/firefox-ios/blob/bf118e4b97c620e804e89e149b9ca85d7a8dce9e/Providers/Profile.swift#L569]
* (And then signing up for an account on the Mozilla China FxA server and syncing some test data)

**Comment by jchaupitre** [comment]
@l-hedgehog, can you help answer question on https://github.com/mozilla-mobile/firefox-ios/issues/6182 with regards to the status of China's server. Specifically:

> Unknown if the China servers are up-to-date with the main servers to support our current setup.

**Comment by l-hedgehog** [comment]
Hi @jchaupitre, I commented in the linked issue.
