### ISSUE TITLE
Firefox iOS: investigate Sentry reports

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#2748]
90% of our Sentry reporting is from a-s, it would be helpful if a team member reviewed these errors. 
https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-beta-231-rustfxa/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-899)
┆Epic: Work required to support operationalizing and shipping the iOS / FxA-client integration
┆Sprint: SYNC - end 2020-03-27

**Comment by garvankeeley** [comment]
Here is a sample of what it looks like:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/5495083/75893446-cff25e80-5e00-11ea-94c4-ea4ada650461.png">

**Comment by mhammond** [comment]
*sob* - fenix sentry reports go to https://sentry.prod.mozaws.net and I have a login there - but this points at https://sentry-fm.prod.mozaws.net - where I don't, so can't see these reports. There are a number of iOS projects on the former, but not this.

Does anyone happen to know (a) what's going on with the different domains and/or (b) how I get a login on this fancy new one?

**Comment by linacambridge** [comment]
(I'm in the same boat, and have the same question! 😁)

**Comment by garvankeeley** [comment]
I don't know the backstory on the sentry instance, but regardless you both should have invites in your inboxes to it

**Comment by jchaupitre** [comment]
@garvankeeley could I get an invite too? :)

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

I chatted with [~jeevans@mozilla.com] about this.  It appears that a very large % of the issues are present in the current iOS production version and not introduced by the recent FxA work.  Going to close this - if there are any high-volume new issues that present in sentry - please open a new bug for the specific issue.
