### ISSUE TITLE
Unique constraint failed for tags

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2749]
This is the [2nd top error](https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-beta-231-rustfxa/issues/221298/?query=release%3A%22org.mozilla.ios.FirefoxBeta-23.1%22) for Firefox iOS beta:

`UNIQUE constraint failed: moz_tags_relation.tag_id, moz_tags_relation.place_id`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-900)

**Comment by garvankeeley** [comment]
I don't see it in the release (a-s v0.48.0, https://github.com/mozilla-mobile/firefox-ios/blob/v23.x/Cartfile.resolved#L18), so it is likely a new error.
Release Sentry, showing not matches for that error: https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-230/?query=is%3Aunresolved+constraint
