### ISSUE TITLE
Fix the Origin Mismatch test when running with BACKTRACE

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#278]
@vbudhram This is a good first bug:

![](http://v14d.com/i/39af06c9068912b1243331cb104957cfdd822093e98134ccafb73fb6969e9391.jpg)

**Comment by rfk** [comment]
@vbudhram do you plan to work on this in the coming sprint cycle?

**Comment by vbudhram** [comment]
@rfk Yea I still plan on getting this completed this sprint cycle.
