### ISSUE TITLE
Add a way to override the token server URL

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2794]
We need to be able to override the token server returned by `.well-known/fxa-client-configuration`. This will allow Sync-only self-hosters to use a different storage backend while still using the production FxA servers for authentication purposes.

https://github.com/mozilla/application-services/blob/04fd44f00cdb6b5bab29ffbd10d1764304a0b365/components/fxa-client/src/config.rs#L140

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-927)
┆Story Points: 3
┆Epic: Allow QA testers to set a different FxA server (stage, stable etc) and a custom Sync storage backend.
┆Sprint: SYNC - end 2020-03-13

**Comment by eoger** [comment]
Issues that also depends on this work:
https://github.com/mozilla-lockwise/lockwise-android/issues/1129
https://github.com/mozilla-lockwise/lockwise-android/issues/542
https://github.com/mozilla-lockwise/lockwise-ios/issues/1175

**Comment by rfk** [comment]
Adding some notes for my later reference. The sync client code currently receives this URL as part of the `SyncAuthInfo` object, which combines the sync key, the oauth access token, and the tokenserver URL.

On the Android side, we don't appear to provide any direct way of constructing a `SyncAuthInfo` in application-services code.  Instead, android-components provides an extension method `AccessTokeninfo.asSyncAuthInfo` which takes the oauth access token info from FxA, adds a tokenserver URL, and converts it into a `SyncAuthInfo`. The `FxaAccountManager` then maintains an internal cache of a `SyncAuthInfo` object annotated with the result of `getTokenServerEndpointURL()`.

So, there are a couple of approaches we could take. We could allow setting the custom tokenserver URL at a very low level, as part of the fxa-client config object. Or we could do it at a very high level, as an extra configuration option on the account manager (and perhaps eventually refactor it to be part of the sync manager).

I think I have a light preference for doing it a high-level, but wouldn't push too strongly against a low-level approach.
