### ISSUE TITLE
Add support for PRs to run consumer smoketests in CI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2797]
Once we have the ability to run local smoketests in consumer apps with a single command (SYNC-877, SYNC-878, SYNC-879) we should work on getting that running in CI. We don't need to run it on every PR, but we should be able to opt-in to having those tests run in CI, perhaps by adding `[ci smoketest]` or similar in the commit message.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-931)
┆Story Points: 5
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-04-24

**Comment by eoger** [comment]
I've opened a prototype PR here: https://github.com/mozilla/application-services/pull/2833

**Comment by rfk** [comment]
Android equivalent in https://github.com/mozilla/application-services/pull/2923

**Comment by rfk** [comment]
Calling this done by the above PRs
