### ISSUE TITLE
Generic history capture hooked up to our component

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#283]
Connect the history from https://github.com/mozilla/application-services/issues/282 to the history component.

*Acceptance criteria*
[ ] ...

**Comment by grigoryk** [comment]
a-c side of things tracking in https://github.com/mozilla-mobile/android-components/pull/1164

**Comment by linacambridge** [comment]
And the reference browser work is in mozilla-mobile/reference-browser#40.

**Comment by rfk** [comment]
Final piece of this is https://github.com/mozilla-mobile/android-components/pull/1238/
