### ISSUE TITLE
Fix migration json leak in Swift

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2835]
Ref: https://github.com/mozilla/application-services/pull/2823#discussion_r395296492

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-946)
┆Sprint: Backlog

**Comment by eoger** [comment]
What needs to be done is to sprinkle
```
if let json = json {
  fxa_str_free(json)
}
```
in [these methods](https://github.com/mozilla/application-services/blob/341422961f58fd1dc3bab9ed5fa345028339a774/components/fxa-client/ios/FxAClient/RustFxAccount.swift#L262-L275) to free the allocated string.
