### ISSUE TITLE
Storage.Sync Storage API Compliance

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2838]
We deal with JSON in and out - there are many variations possible. This doesn’t affect the “concrete” API, just the shape of the JS objects.

We need to ensure we comply with not only the vague spec, but also the existing implementations.

There are some tests in [test_ext_storage.js](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/test/xpcshell/test_ext_storage.js), all of which pass in [bug 1623245](https://bugzilla.mozilla.org/show_bug.cgi?id=1623245), but we probably need more (eg, there aren’t tests for “strange” inputs, such as non-string values, etc.) - but all in all, this is looking OK!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-951)
┆Story Points: 3
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-04-24

**Comment by data-sync-user** [comment]
➤ Ethan Glasser-Camp commented:

I don't really understand what this issue means. In particular, if the tests in `ext_storage_sync.js` pass, then that means we are handling several kinds of strange inputs: functions, dates, `undefined`, `window`, regular expressions, etc. What other types of objects should we be testing?

**Comment by mhammond** [comment]
I actually wrote this before I examined that test in detail, but I once I did look I still didn't think it particularly thorough - int keys, nested objects, nested arrays, objects with a custom toString()/toJson() etc. I think there's a significant risk that there will be subtle behaviour changes if we rely solely on that test - it might be that we don't care about those edge-cases, which is fine, but not really our team's call.

**Comment by mhammond** [comment]
> I still didn't think it particularly thorough

To clarify - it is "thorough" in terms of test coverage of the implementation - just not particularly thorough in ensuring that all possible inputs and what they output are tested. I don't mean to imply it's a bad test!

**Comment by glasserc** [comment]
I spoke with @mhammond about this on Slack. Some notes:

- It's impossible to have an int key in JS so we don't have to be concerned about that case.
- Probably this task will be complete when more tests are added to `mozilla-central` exercising these odd cases.
- The [Chrome documentation](https://developer.chrome.com/extensions/storage) seems to imply that storing ANY object in a value stores it as an empty object `{}`. We don't have tests that verify this -- our only test stores an empty object and confirms it remains empty. (But see [this Stackoverflow](https://stackoverflow.com/questions/49398723/calling-objects-in-chrome-storage-api) for someone who seems to be storing an object as a value.)

We should probably investigate what Chrome does in practice. My personal intuition is that nested objects will serialize the same way as regular objects (probably replaced with an empty object), nested arrays should work as you would expect, custom `toString` implementations would not be invoked, and `toJSON` methods would not be invoked.
