### ISSUE TITLE
Audit/Implement security requirements

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2842]
How do we map an addon ID to a GUID? Do we need to ensure that once an addon is removed, it’s impossible to tell from inspecting the local profile that it once existed?

In general, what are the required security properties of this, and are we meeting them?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-955)
┆Story Points: 2
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-05-08

**Comment by rfk** [comment]
> Do we need to ensure that once an addon is removed, it’s impossible to tell from
> inspecting the local profile that it once existed?

FWIW this seems like a reasonable privacy expectation from the user's perspective, but I suspect we're asking this because feel it might be hard to provide in practice..?

**Comment by mhammond** [comment]
> FWIW this seems like a reasonable privacy expectation from the user's perspective, but I suspect we're asking this because feel it might be hard to provide in practice..?

Yes. The current plan is that we will use the extension ID in the local sql database, and that data will not be removed when the addon is uninstalled (which is also true now - the addon IDs are stored locally and not removed in the existing implementation too) - so we will not be changing anything from that perspective.

FTR, and while I am here, our current plan for chrome.storage.sync is that we will generate random guids for sync. The extension ID will be stored on the server, but only in the encrypted payload. The local sql database will also store this mapping.

So I think this should be easy to rationalize as us keeping, roughly, the status-quo:

* For extensions which use chrome.storage.sync, the extension IDs will persist in the local profile after an extension is removed, both in the existing and new implementations.

* The extension IDs are not stored on a remote server in plain-text.

**Comment by rfk** [comment]
>  and that data will not be removed when the addon is uninstalled

Are we deliberately keeping it around in case the user re-installs the add-on?

**Comment by mhammond** [comment]
> Are we deliberately keeping it around in case the user re-installs the add-on?

Currently, yes. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1618860

**Comment by mhammond** [comment]
(although syncing is a can of worms in general here. We can't know if other profiles still have the addon and whether we should also remove it from the server - but even then there's tombstones to consider etc. It's worth nothing that once the data is synced, this profile will also hold synced data for extensions which have never been installed on this device)

**Comment by rfk** [comment]
Looping back to this, I think "don't regress the current security/privacy properties" should be our explicit goal, and that it will be worth our time to prep a short secreview-style document to assure ourselves that we meet it. Next action here is for me to sketch out said doc and ni? folks for the details in places where I'm fuzzy on the details.

**Comment by rfk** [comment]
Cross-linking an older bug on this topic for reference: https://github.com/mozilla/application-services/issues/2745

**Comment by rfk** [comment]
I took a stab a filling in the secreview template doc here:

  https://docs.google.com/document/d/1VcYJ4eGE5OinuPZvwo3N4v_-5LXH3sAdE23rI-Py5N0/

@mhammond at your convenience could you please take a look, before we distribute this more widely? (And anyone else who's interested, of course!)

**Comment by rfk** [comment]
Once we're happy with this doc, we should email it to secreview@mozilla.com and see if anyone's interested in taking a look. (I think it's valuable homework to have done even if we don't get a formal secreview on it in the timeframe we're looking at here).

**Comment by mhammond** [comment]
That doc looks great, thanks! I left a couple of comments but they are only small nits.

**Comment by rfk** [comment]
Feedback incorporated, and email sent to the secreview list. Let's leave this issue in the "review" column to track outcomes of any resulting conversation.

**Comment by rfk** [comment]
Mark and I met with Dan and Thyla to go over some of the crypto and privacy concerns mentioned in the doc. They didn't highlight any major concerns (and most of the crypto things that came up boiled down to "sync's crypto was designed many years ago") and offered to provide a short summary of their thoughts in the doc.
