### ISSUE TITLE
Configuring Fenix with an invalid content URL should produce a hard error

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2845]
STR:

* Accidentally mis-configure Fenix with an FxA content-server URL that doesn't work (in my case, I made a build that uses "http://127.0.0.1:3030" but I didn't set up port forwarding on the device).
* Sign in to Fenix.

Expected Result:

* Some sort of error telling me that my browser is misconfigured.

Actual result:

* Fenix opens "https://accounts.firefox.com/signin" without any URL parameters.
    * The login form is displayed, but says "Enter your email to continue to Account Settings" rather than "to continue to Firefox Sync".
    * Signing in results in the account settings page being shown.
* There's no indication that anything went wrong.
* I do not successfully get signed in to Fenix.

I'm not entirely sure where the problem is here, but I assume something is swallowing a network error and incorrectly falling back to some default URL.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-958)
┆Sprint: Backlog

**Comment by eoger** [comment]
> I'm not entirely sure where the problem is here, but I assume something is swallowing a network error and incorrectly falling back to some default URL.

[You are correct](https://github.com/mozilla-mobile/android-components/blob/5e8732653b076ac8c262e2034e42a43275c9f266/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L49-L51), I have also experienced this behavior while working on the Fenix "debug" menu.

**Comment by rfk** [comment]
Thanks @eoger! I'm going to close this in favour of https://github.com/mozilla-mobile/android-components/issues/2496
