### ISSUE TITLE
Vendor the fxa crate into mozilla-central

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2850]
There's a bunch of question we have to answer:

- Networking: do we want to vendor _viaduct_? How?
- _rc_crypto_: how do we link against the desktop NSS? We have the required configuration options through environment variables: how do we set them at gecko build time?
- In tree A-S dependencies, such as _sync15_ or _rc_crypto_: how do we vendor them when they are declared with relative paths?
- Other dependencies: any dependencies that are deemed non-vendorable by mozilla-central standards?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-968)
┆Story Points: 5
┆Epic: FxA crate in desktop
┆Sprint: SYNC - end 2020-04-24

**Comment by thomcc** [comment]
I can answer a few of these.

>     * Networking: do we want to vendor _viaduct_? How?

It's not possible to avoid (note: optional dependencies are still vendored). We need to remove the direct dependency on reqwest, and move it to a separate crate, and move everything to pull that in and initialize it in tests. This is a pain but doable.

>     * In tree A-S dependencies, such as _sync15_ or _rc_crypto_: how do we vendor them when they are declared with relative paths?

This isn't a problem, it should just work with cargo vendor if we point them at a git dependency.

>     * Other dependencies: any dependencies that are deemed non-vendorable by mozilla-central standards?

I believe we aren't supposed to vendor the rust HTTP stack (reqwest and friends).
