### ISSUE TITLE
Implement a JS<>XPCom<>Rust bridge for the fxa crate

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2851]
The hardest part here is what do we want to call it? Overpass? Link? Catwalk?

More seriously, the bridge is a low-level module that talks to the `FxAccount` rust struct, converting back and forth the data structures. Nothing business-smart should happen here.

We also have amazing prior work from @linacambridge on this, and even examples/resources:

https://phabricator.services.mozilla.com/D67728
https://phabricator.services.mozilla.com/D65268 
https://docs.google.com/presentation/d/1qkPwISU1BvsTVyqLuVhisSMuIS_DiXb8X09-boszcu0/edit?usp=sharing 

More from convo with her:

> 1) add the rust crate as a dependency to toolkit/library/rust/shared/Cargo.toml
> 2) (OPTIONAL) if you want to gate it behind a build flag (so that it's nightly-only, for example), add a feature to toolkit/library/rust/gkrust-features.mozbuild, toolkit/library/rust/Cargo.toml, and toolkit/library/gtest/rust/Cargo.toml
> 3) link it into libxul! toolkit/library/rust/shared/lib.rs
> 4) add your IDL, browser/extensions/formautofill/components/nsIFormAutofillStorage.idl in that case
> 5) add your crate! browser/extensions/formautofill/components/formautofill_storage/Cargo.toml you'll want to pull in xpcom, nsstring, nserror, and libc as deps for sure. i also recommend moz_task for working with background threads
> 6) check out InitStore in browser/extensions/formautofill/components/formautofill_storage/src/lib.rs. that has the #[derive(xpcom}] magic

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-967)
┆Story Points: 5
┆Epic: FxA crate in desktop
┆Sprint: SYNC - end 2020-04-24

**Comment by data-sync-user** [comment]
➤ Julien Chaupitre commented:

Create subtask - Figure out to integrate protobuff into m-c build system.

**Comment by eoger** [comment]
Work is happening in [bug 1631630](https://bugzilla.mozilla.org/show_bug.cgi?id=1631630).

**Comment by eoger** [comment]
We're going to use Uniffi for this!
