### ISSUE TITLE
Implement a JS API to talk to the FxA crate

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2852]
From the tech document I'm currently writing:

- Either keep the FxAccounts.jsm API, and try to bolt the Rust crate to back it up:
  - Pros: less integration points to touch as the API surface hasn’t changed
  - Cons: might be hard as some concepts might not map properly and could end up being more work than expected.

- Or implement a “FxAccountManager” that mirrors what has been done on Android and iOS.
  - Pros: Easier for us to maintain since it shares the same architecture as mobile. Easier to consume for consumers since it has the same API surface.
  - Cons: It’s work!

I would be in favor of the later option because it seems more viable for the future. There’s a very high chance that if we don’t overhaul the API now, we never will (or make a P3 bug).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-966)
┆Epic: FxA crate in desktop
┆Sprint: Backlog

**Comment by mhammond** [comment]
> I would be in favor of the later option because it seems more viable for the future.

I'm in favor of that, but I'm a little skeptical it's "just do that" :) A reasonable first-start might be to use searchfox to identify all consumers of fxaccounts in the tree and a rough sketch of (a) what fxaccounts in a-s is missing and (b) what it will take to change the existing consumers to what's exposed via rust.

I suspect we are going to end up needing to make a few compromises and to work out how to do this in a gradual way - landing a single patch that changes every single use of fxa in mozilla-central doesn't sound viable.

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Let's close this as this is superseded by SYNC-1106.
