### ISSUE TITLE
Allow Desktop OAuth flow on FxA content server

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2853]
This only tracks the work that has to be done on the mozilla/fxa project.

I'm not sure what's required here, but we should find out.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-970)
┆Epic: Integrate FxA rust component into desktop
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

The work to do here is covered by the SYNC-1083 epic, let's close this.
