### ISSUE TITLE
Use the new `TimingDistribution.measure` helper from glean.

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2871]
Some of our Kotlin code currently defines a custom helper method on glean's `TimingDistribution` metric to make to make it easier to measure the execution of a closure, e.g. [this definition](https://github.com/mozilla/application-services/blob/28a58972754daceda9e96382898880f1a5e9be85/components/logins/android/src/main/java/mozilla/appservices/logins/DatabaseLoginsStorage.kt#L404) in this logins component.

As of [Bug 1598993](https://bugzilla.mozilla.org/show_bug.cgi?id=1598993) glean now supports such a method natively. We should use it instead of our own artisanal version.  In practice this looks like:

1. Wait until the new method is in a released version of glean and android-components
2. Find places where we implement our own `TimingDistributionMetricType.measure` method and delete them.
3. Make sure the Kotlin tests all still pass, fixing up for any compilation problems that might have been introduced by subtle API differences.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1010)
┆Sprint: Backlog

**Comment by vladikoff** [comment]
The PR to add the version of glean that supports this is in https://github.com/mozilla-mobile/android-components/pull/6455
