### ISSUE TITLE
Add support for "listAttachedOAuthClients” in Rust

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2898]
Currently we seem to be missing the following "listAttachedOAuthClients" method https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccounts.jsm#453 that a lot of Desktop component use in various places

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1049)
┆Story Points: 3
┆Epic: FxA crate in desktop
┆Sprint: SYNC - end 2020-05-08

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

This list probably should also be debounced just like https://jira.mozilla.com/browse/SYNC-815

**Comment by lougeniaC64** [comment]
Also adding support for `POST /account/attached_client/destroy`
