### ISSUE TITLE
Determine strategy for WebChannel pages like /accounts/ in FxA Rust Desktop

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2899]
Once Desktop migrates to OAuth login we need to determine what changes the external pages have to make to support the new flow. 

IIRC these pages have WebChannel support, so one possibility is to use that to make the flow happen.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1048)
┆Story Points: 5
┆Epic: FxA crate in desktop
┆Sprint: SYNC - end 2020-05-08

**Comment by rfk** [comment]
Full link to the page in question, for easy reference:

    https://www.mozilla.org/en-US/firefox/accounts/

My opinion is that we should change those pages so that they trigger in-browser signin UI rather than doing a bunch of special privileged stuff in web content, ref https://bugzilla.mozilla.org/show_bug.cgi?id=1538024

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

We had a meeting about it and have a strategy for this. See these bugs for details: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1635219 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1635219 )

https://bugzilla.mozilla.org/show_bug.cgi?id=1635213 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1635213 )
