### ISSUE TITLE
Allow FxA profile to refresh even when there exists a profile

### ISSUE THREAD

**Issue by nbhasin2** [mozilla/application-services#2902]
**Context:** 
Allow the iOS Firefox app to get notified via `.accountProfileUpdate` when we call the `refreshProfile()` in rust components. 

User opens iOS Firefox app and goes to change their picture. 
In the app we call `refreshProfile()` from rust components

**Expectation:** 
we get notified via `.accountProfileUpdate` notificaiton in iOS Firefox 

**Reality:** 
No notification is sent from FxA Rust components 

Ref issue: https://github.com/mozilla-mobile/firefox-ios/issues/6190

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1051)
┆Sprint: Backlog

**Comment by eoger** [comment]
I think what we need to do is add a `.fetchProfile` event handling in `case .authenticatedWithProfile`, [we only do it for `case .authenticatedWithoutProfile`](https://github.com/mozilla/application-services/blob/0ff8d6b46432798fffcbd04c44c93f5bd33d1698/components/fxa-client/ios/FxAClient/FxAccountState.swift#L80) and more-or-less copy paste [the transition](https://github.com/mozilla/application-services/blob/0ff8d6b46432798fffcbd04c44c93f5bd33d1698/components/fxa-client/ios/FxAClient/FxAccountManager.swift#L493-L504) in `case .authenticatedWithProfile: do {`

**Comment by linacambridge** [comment]
This was fixed!
