### ISSUE TITLE
Figure out the Desktop logging story

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2904]
From the brainstorming: 

we currently have several levels of logging, such as  "FATAL", "ERROR", "WARN", "INFO", "CONFIG", "DEBUG", "TRACE" or "ALL" logs and prefs that control them. In addition there's `about:sync-log`   and identity.fxaccounts.loglevel . We need to figure out how the logging levels interact with the rust component and if the component can pipe logs into about:sync-log.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-1052)
┆Story Points: 8
┆Epic: FxA crate in desktop
┆Sprint: SYNC - end 2020-06-05

**Comment by rfk** [comment]
To add to this, framing as a concrete end goal: I think it will be very important that logging from the rust component respects the existing logging structure for FxA and Sync code in the browser, or we're going to set ourselves up for debugging nightmares:

* Logs from the rust code should end up in the files in `about:sync-log`
* Log output from rust code should respect the configuration in `identity.fxaccounts.loglevel`
* We should respect the PII-handling policy of the existing code, which I think is broadly "don't log PII unless you're at `TRACE` level, and never log secrets".

If we find we can't achieve those things, we'll need to come up with a considered Plan B.

**Comment by mhammond** [comment]
To weigh in:

> * Logs from the rust code should end up in the files in `about:sync-log`

I personally consider this non-negiotiable (but IIUC, should be easy - dogear has paved that path for us)

> * Log output from rust code should respect the configuration in `identity.fxaccounts.loglevel`

I agree with this in general, but I'm open to rationalizing some things here where it makes sense - in particular...

> * We should respect the PII-handling policy of the existing code, which I think is broadly "don't log PII unless you're at `TRACE` level, and never log secrets".

Sadly, FxA ended up with a confusing addition to this - there's a [separate pref](https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsCommon.js#31) to indicate if you want to enable PII, but it's only used sparingly and (eg) sync doesn't honor it. Further, it sometimes means "log secrets" - eg, [here](https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsKeys.jsm#134) we will log a key-fetch-token if the pref is set.

I don't recall ever needing the actual keys etc for debugging, so it probably makes sense to drop some of that logging entirely, kill the pref entirely, and generally move to what Ryan said (trace == PII, no secrets). But I'm open to anything here.

**Comment by linacambridge** [comment]
I wrote a bit more about hooking in to Desktop Sync's logging infrastructure [here](https://phabricator.services.mozilla.com/D65268?id=251640#inline-406790). 😊 The TL;DR is, we might have to make a `log_support` crate with our own logging macros and a facade that logs to a `dyn Log` (which would use the Sync logging bridge in Desktop, and the global `log::logger()` from the `log` crate everywhere else), but it's totally doable.

**Comment by rfk** [comment]
> it probably makes sense to drop some of that logging entirely, kill the pref entirely

+1 FWIW

**Comment by linacambridge** [comment]
I filed a Bugzilla ticket with more implementation details: https://bugzilla.mozilla.org/show_bug.cgi?id=1635487

**Comment by lougeniaC64** [comment]
Going to push a very rough PR to represent these ideas shortly, but in short this is what I propose. This is a derivative of what Lina proposed above with some details. Please let me know if any of this is infeasible. cc @linacambridge @vladikoff @eoger 

- Create an XPCOM Rust service that registers a [mozIServiceLogger](https://searchfox.org/mozilla-central/source/services/interfaces/mozIServicesLogger.idl) for a target
    - Has a map property which references a [LogSink](https://searchfox.org/mozilla-central/source/services/sync/golden_gate/src/log.rs) instance, keyed by a target
    - Has a `register` function with parameters `max_level`, `target`, and `logger`
- Extend `mozIServiceLogger.idl` to handle the INFO, CONFIG, FATAL, and ALL log levels
- Extend `LogSink` to make it usable for FxA
    - Add handling of additional FxA log levels (see the note below about the log crate references)
    - Make any target references generic
    - Make the default log level variable
        - At present, extension storage’s default log level is ‘Off’ and FxA’s default is `Debug`.
- Update GeckoLogger
    - Add functionality in the `log` function to handle a-s messages

Concerns
- The __android_log_write function in GeckoLogger doesn’t handle the `CONFIG` log level. This doesn’t seem like a showstopper but it may break parity with Desktop.
- Both log::Level and log::LevelFilter)don’t have representations for `CONFIG`, `FATAL`, and `ALL`.  We would have to augment or replace those types.

**Comment by linacambridge** [comment]
Thanks for the thorough write-up, @lougeniaC64! This looks like a good plan, and I like your breakdown of the work!

I'll spend some time before next week writing up some more detailed docs about implementing Rust XPCOM components in Firefox; except for that slide deck and Oxidation wiki, the process is a bit (OK, a lot, lol :sob:) sparse on the docs! If you'd like, we can Zoom or Slack about this next week, or pair in VS Code!

> Extend `mozIServiceLogger.idl` to handle the INFO, CONFIG, FATAL, and ALL log levels

Oh, you mentioned `CONFIG` earlier! I'm probably missing something, but I'm wondering why `GeckoLogger` or `mozIServicesLogger` needs to know about `CONFIG`, `FATAL`, or `ALL`?

IIUC, `mozIServicesLogger` is a bridge for Rust to send logs to JS...so we only need it to handle the log levels that Rust outputs (`log::Level`). Since there's no `log::LogLevel::Config` in Rust, how come `mozIServicesLogger` need to support it?

**Comment by lougeniaC64** [comment]
> Oh, you mentioned `CONFIG` earlier! I'm probably missing something, but I'm wondering why `GeckoLogger` or `mozIServicesLogger` needs to know about `CONFIG`, `FATAL`, or `ALL`?
> 
> IIUC, `mozIServicesLogger` is a bridge for Rust to send logs to JS...so we only need it to handle the log levels that Rust outputs (`log::Level`). Since there's no `log::LogLevel::Config` in Rust, how come `mozIServicesLogger` need to support it?

OMG, yes! Sorry, you are missing nothing. This would not be a concern. This also means my Android "concern" is invalid because the android function in Gecko logger wouldn't know about `CONFIG`.

**Comment by linacambridge** [comment]
Ahhh, no worries, thanks for clarifying!
