### ISSUE TITLE
Update mozilla-central copy of protobufs

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2906]
The `map<T, T>` type does not work with the version mozilla-central has (3.4).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1054)
┆Story Points: 3
┆Epic: Integrate FxA rust component into desktop
┆Sprint: SYNC - end 2020-04-10

**Comment by eoger** [comment]
Work in progress in [bug 1627444](https://bugzilla.mozilla.org/show_bug.cgi?id=1627444).

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Landed on central!
