### ISSUE TITLE
--all-features and default features tests not run in CI

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2907]
I just was looking up the precise incantation to run --no-default-features tests in a workspace (https://github.com/mozilla/application-services/blob/master/automation/all_rust_tests.sh#L30) and noticed that the default features tests and all-features tests are not run.

If we can only do one of these, for CI cost reasons, the no-default-features test is probably not the one we should be choosing!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1055)
┆Sprint: Backlog

**Comment by eoger** [comment]
Work to do is to un-comment these lines:

https://github.com/mozilla/application-services/blob/bab712262340583b80aff21b29eea806f104b220/automation/all_rust_tests.sh#L22-L24

And replace `${EXTRA_ARGS[@]}` by `${EXTRA_ARGS[@]:+"${EXTRA_ARGS[@]}"}` so nothing gets appended if `EXTRA_ARGS` is empty.

**Comment by theoniko** [comment]
Hello @eoger 
I would like to contribute to this project and i apply the changes you suggested to #3151.
Could you please review if everything is fine?
