### ISSUE TITLE
Replace uses of json! with OAuthTokenRequest when calling make_oauth_token_request.

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#2918]
As part of #2896, a new `struct` `OAuthTokenRequest` was introduced. 

This _should_ used for multiple other places in `http_client.rs`— callers of `make_oauth_token_request`— which currently using a raw `json!` macro.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1066)
┆Sprint: Backlog

**Comment by yabirgb** [comment]
Hi! I want to make my first contribution. Can I work on this issue?

**Comment by vladikoff** [comment]
@yabirgb sure!

**Comment by eoger** [comment]
@yabirgb you will have to wait till https://github.com/mozilla/application-services/pull/2896 lands first (or you can work on their branch then rebase later)

**Comment by yabirgb** [comment]
@jhugman When you mention `OAuthTokenRequest`, do you mean `OAuthTokenResponse`? Is the only one I see in the commits and in a quick rgrep of the code

**Comment by yabirgb** [comment]
@jhugman Hi! I've found that there is only one more call to the function make_oauth_token_request in that case to refresh the token using code. 

There fields required are different to the ones in `OAuthTokenRequest` (for example the `code` and `code_verifier` fields are requiered and there are no `refresh_token`...). 

Relative to other places where this `OAuthTokenRequest` also have different requirements in what respect to the needed fields. 

Would be a good idea to make the non-common fields optional in the struct?

**Comment by eoger** [comment]
Yup you put your finger on it, depending on the request some fields are irrelevant, see the [API docs](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#post-oauthtoken) around "grand_types". I would suggest using an `enum` to prevent mis-use of the API. Maybe we can take advantage of the serde [untagged enum](https://serde.rs/enum-representations.html#untagged) representation?

**Comment by yabirgb** [comment]
I have a question about the API. I've found this line using `response_type: code` https://github.com/mozilla/application-services/blob/master/components/fxa-client/src/http_client.rs#L217 but seems it is ignored in the documentation https://github.com/mozilla/fxa/blob/8ae0e6876a50c7f386a9ec5b6df9ebb54ccdf1b5/packages/fxa-auth-server/lib/oauth/routes/token.js#L159

Could it still be used somewhere else?

**Comment by eoger** [comment]
In the case you mention we call a different route `v1/oauth/authorization`, which doesn't use the `make_oauth_token_request` helper anyway
