### ISSUE TITLE
Add a GitHub Action(?) signed commits check

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#2939]
Add a GitHub Action(?) to explain to contributors that they need to sign commits with their patch (and maybe how to do it)

The action should fail if the commit is not signed, therefore failing the CI check thingy...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1085)
┆Sprint: Backlog

**Comment by vladikoff** [comment]
I am not sure if an external contributor can see this message either: 

![image](https://user-images.githubusercontent.com/128755/78939602-7a097a00-7a82-11ea-8377-222e03101e2d.png)

**Comment by thomcc** [comment]
This repo isn't allowed to use github actions :(.

Pretty sure that's not needed for this though, we could use just use a bot no?

**Comment by vladikoff** [comment]
This was resolved with Mergify
