### ISSUE TITLE
sync15-adapter shouldn't use an `error!` log for the meta/global 404

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#294]
This is expected if we're the first ones there. It would be nice to make this a `info!` level log for just this specific case, but if that's too much of a pain moving it to a `warn!` in all cases would also be fine.

**Comment by thomcc** [comment]
Not really, since we might not be on the client that PUTs it, the "first time through" might happen on another device. (Also, `&self` isn't `&mut self` there, so you'd have to set it on a `Cell<bool>`, but that's neither here nor there).

Thinking about it more, everything besides changing https://github.com/mozilla/application-services/blob/master/sync15-adapter/src/client.rs#L174 to be a warning is probably more trouble than it's worth.

**Comment by leethomas** [comment]
Wow that was a really fast response, appreciate that. I didn't think you'd seen my comment yet so I had deleted it after exploring the code a little further and realizing that another client might set it. Thanks again for your responsiveness

**Comment by thomcc** [comment]
No problem. I've quoted it to make the comments clearer, though.
