### ISSUE TITLE
Expand and identify all the concrete pieces of telemetry needed for webext-storage.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2944]
Over the past few days I've filed a number broad bugs that suggest the places we will need telemetry and the sort of things we might want to measure there. (I probably have one or two more to file today, neither here nor there).

These also generally came with a few examples, but on their own they may be insufficient, and even if they're ideal, it's too many things to do in one bug. They need some degree of further research, which I punted on until I had more of the scope of this in sight. (It seemed better to start at a high level and drill down rather than getting side tracked many times as I investigated each component in-depth).

This investigation is focused on what's needed to ensure we have enough telemetry to land the new webext-storage with confidence, but many things will likely impact e.g. FxA and other future rust component work as well. (That said, this isn't prioritization, just splitting the issues up and investigating to understand which parts are and are not necessary)

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-1093)
┆Story Points: 3
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-05-08

**Comment by thomcc** [comment]
I think this is essentially done. There's a very small amount of work to follow up on a couple things but I don't think there's much value in keeping the issue open.
