### ISSUE TITLE
Add iOS FxA sample project

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#2958]
I found it very useful to have the `sandvich` sample when hooking up iOS FxA code. I could imagine others would feel the same. Rather than building a full application that implements FxA for debugging/development, just building a sample app is a very efficient way to work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2482)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865169

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
