### ISSUE TITLE
Make sure the metric pipeline can handle the OAuth token volume

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2966]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1112)
┆Story Points: 3
┆Epic: Migrate Desktop from assertions
┆Sprint: Backlog

**Comment by rfk** [comment]
Cross-linking for context, this pipeline issue was resolve by this work: https://bugzilla.mozilla.org/show_bug.cgi?id=1632635
