### ISSUE TITLE
Move golden_gate into app-services

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2967]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1113)
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

Related https://jira.mozilla.com/browse/SYNC-954

**Comment by data-sync-user** [comment]
➤ Lina Cambridge commented:

Hmmm, what's this ticket covering? https://bugzilla.mozilla.org/show_bug.cgi?id=1626128 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1626128 ) (SYNC-1033) is for moving the trait into a-c, and SYNC-954 is for unifying `golden_gate::Store` and `sync15_traits::Store`. We can't have all of `golden_gate` live in a-s, because it depends on Gecko-only types.

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

Yeah, I'm not sure why Vlad opened this, but it's a dupe of 1033.

**Comment by vladikoff** [comment]
@mhammond Sorry, I could not find https://jira.mozilla.com/browse/SYNC-1033 👓 !
