### ISSUE TITLE
Duplicated code in in CI setup

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2986]
I've noticed that `taskcluster/app_services_taskgraph/transforms/out_of_docker_setup.py` and `taskcluster/scripts/toolchain/cross-compile-setup.sh` have a lot of duplicated logic, we should figure out what goes where.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1129)
┆Sprint: Backlog

**Comment by MihaiTabara** [comment]
Solved by https://github.com/mozilla/application-services/pull/3113
