### ISSUE TITLE
RemoteConfig should not be persisted

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2998]
I lied in https://github.com/mozilla/application-services/blob/536a7f8c77430d9daeb68ad79568c048aca7b8bf/components/fxa-client/src/config.rs#L31-L32

I think we should still do what it says, so clients can always pick up the newest config (and it's a very cheap network call, both for the server and the clients).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1141)
┆Sprint: Backlog

**Comment by rfk** [comment]
+1; I think we also have a bug on file somewhere called "discuss whether RemoteConfig should be persisted" that can also be closed by this.
