### ISSUE TITLE
Prototype Android Sandvich Example App that uses fxa-rust-client

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#30]
Based on our roadmap we need to create a simple prototype Android version of an app that imports the fxa-rust-client

We have an ios example already: https://github.com/mozilla/application-services/tree/master/sandvich-ios

@csadilek what was your plan for this? Did you still want to use JNI?

**Comment by csadilek** [comment]
@vladikoff Yes, was thinking following an approach as described here: https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html

My suggestion would be to host the Android version over at https://github.com/mozilla-mobile/android-components, which is a collection or re-usable components for all our Android products.
