### ISSUE TITLE
Consider using a connection pool for e.g. places/logins

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#300]
A connection pool for rusqlite already exists via https://github.com/sfackler/r2d2 + https://github.com/ivanceras/r2d2-sqlite.

We probably can handle `PRAGMA key` via the `r2d2::CustomizeConnection` trait. This would require that we hold the key around in memory, but TBH I don't know that we care about this – SQLCipher keeps the key in memory, just it does 64k PBKDF2 iterations first. If we *do* care, we could do the same, and pass the key in as a raw/hex value using the `PRAGMA key "x'...'"` "raw key data" hexadecimal syntax (https://www.zetetic.net/sqlcipher/sqlcipher-api/#key).

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-76)

**Comment by mhammond** [comment]
Quite similar to #395

**Comment by rfk** [comment]
From the meeting today, it sounded like we weren't going to do this. I'm going to go ahead and close it out but please re-open if I misunderstood.
