### ISSUE TITLE
Uh oh! Looks like an error!

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3004]
Error is "Bad credentials":

https://github.com/mozilla/application-services/commit/93268b4617190989c7323168cf96e047e10ccf7b

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1142)
┆Sprint: Backlog

**Comment by MihaiTabara** [comment]
I've been fighting all morning with some scope issues in https://github.com/mozilla/glean/ but this is something that I've never seen before. I'll dig, thanks for raising this.

**Comment by eoger** [comment]
Seems like we're not the only ones affected here: [Bug 1631099](https://bugzilla.mozilla.org/show_bug.cgi?id=1631099)

**Comment by eoger** [comment]
Upstream issue was fixed.
