### ISSUE TITLE
Sentry reporting malformed push messages

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#3006]
[This sentry issue](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7432677/) looks like something we should try and get on top of: 467 events from 138 users in the last 2 months on just Fenix Nightly.

Specific error: parsing encrypted message failed: java.util.NoSuchElementException: Key body is missing in the map.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1143)
┆Epic: Send Tab (& Devices) Improvements
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Checking in sentry - the reports of this error seem to have tapered off in nightly and I can't find anything similar in sentry for fenix-beta.  closing.
