### ISSUE TITLE
Investigate Send Tab Telemetry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3010]
Based on this dashboard: [https://sql.telemetry.mozilla.org/dashboard/send-tab-new-version---bigquery-](https://sql.telemetry.mozilla.org/dashboard/send-tab-new-version---bigquery-) 
 Although this dashboard doesn't include all the data (missing iOS and Fenix data) it seems like the Send Tab functionality is not performing at its best, since only around ~50% of the time the tab is sent and received on the new version. Despite the data showing these numbers, we haven't received many user complaints that Send Tab doesn't work.

I've created this ticket to investigate if the metrics are accurate and if we should add more telemetry to have a better understanding of how the feature is performing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1148)
┆Story Points: 13
┆Epic: Send Tab (& Devices) Improvements
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

I filed this bug, but in hindsight it seems a little bit too broad to be actionable. [~mhammond@mozilla.com] do you have any suggestions on where to start with exploration?

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

I think a good first start is to verify the figures in that dashboard via other mechanisms. Specifically, each sent tab should have a corresponding post to (I think) `https://accounts.firefox.com/account/devices/invoke_command ( https://accounts.firefox.com/account/devices/invoke_command )`, and every received tab will result in the tab being delivered either via push, or when the client is checking for "missed commands" and does a GET to (again, I think 😀 `https://accounts.firefox.com/account/device/commands ( https://accounts.firefox.com/account/device/commands )` - although we expect most GETs for missed commands to find nothing - ie, we will need to only count those GET requests where we actually found something.

(Note that desktop thinks it is recording missed commands in a scalar ( https://searchfox.org/mozilla-central/rev/54f965e51e4f77866bec42737978d40d4c1fdfc5/services/fxaccounts/FxAccountsCommands.js#102 ), but that expired in Firefox 68 ( https://searchfox.org/mozilla-central/rev/54f965e51e4f77866bec42737978d40d4c1fdfc5/toolkit/components/telemetry/Scalars.yaml#641 ) 🙁 We could consider reinstating that, but we might be able to get good enough metrics from the server side of the world - especially given we aren't quite trusting the client collected data yet.)

Then we should try and reconcile the dashboard above with these new counts - either they will be very close to each other, or way off. If the former, then we probably need to conclude the feature really is that broken and start brainstorming ideas for why and what else we should capture to work that out. If they are way off, hopefully at least one of them shows ~90% success rates for sent tabs - in which case we probably need to understand why the client collected telemetry is letting us down. It's probably not worth speculating too much here - let's see what the data says.

I'm not sure how you would get the fxa counts - maybe [~loines@mozilla.com], [~wclouser@mozilla.com] or [~rkelly@mozilla.com] will have some insights there.

**Comment by rfk** [comment]
> I'm not sure how you would get the fxa counts 

I'll see what I can do. Given this is a public issue, I won't put raw metrics numbers into it, but I'll jot notes in a shared google doc [here](https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM/).

**Comment by rfk** [comment]
An initial look shows FxA server metrics reporting around twice as many tab-sending operations from Desktop, as those reported in the sync-ping dashboard.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

There also appears to be a large discrepancy when correlating between "tab sent" and "tab received" events. The sync ping telemetry shows that many "tab sent" events do not have a corresponding "tab received" event, but it also shows that many "tab received" events do not have a corresponding "tab sent" event:

https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM/edit#heading=h.hzf8if47w70 ( https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM/edit#heading=h.hzf8if47w70 )

So, I'm at a point where I don't really trust those graphs to be telling us anything useful right now.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

The FxA server logs suggest a surprisingly high failure rate when delivering send-tab push notifications, ref https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM/edit#heading=h.lsh1ooublr1l

I filed SYNC-1293 to investigate further on that front.
