### ISSUE TITLE
[automation] Use TC's docker image support to move Docker definitions in-tree

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#302]
TC has first-class docker image generation support built-in.  There's a nice example of its use in https://github.com/servo/servo/tree/master/etc/taskcluster.  `a-s` should migrate to this pattern, since right now the Docker definitions live in @ncalexan's _Mentat_ repository in temporary branches, and that's clearly not sustainable!

**Comment by mhammond** [comment]
We want to do #313 now
