### ISSUE TITLE
Produce Swift test coverage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3026]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1167)
┆Sprint: Backlog

**Comment by thomcc** [comment]
See https://jira.mozilla.com/browse/SYNC-861?focusedCommentId=143305#comment-143305 for some discussion about possible avenues here.

See https://github.com/mozilla/application-services/issues/3027 for the kotlin equivalent to this issue.
