### ISSUE TITLE
Consolidate the "remote" Config and the local one

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#303]
See 1st bullet in @csadilek's message in https://github.com/mozilla-mobile/android-components/issues/1085#issue-371135396.
Makes sense to you @mozilla/fxa-devs ? @vbudhram want to take that one?

**Comment by vbudhram** [comment]
@eoger The linked proposal makes sense to me, I'll take this one on!

**Comment by mhammond** [comment]
#311 should land before this is started (or just talk to Thom first!)

**Comment by rfk** [comment]
We're bout to land some API refactorings in #388, and since we're making breaking API changes anyway, it might be a good opportunity to land this as well.  @vbudhram are you will interested in taking this one on?

**Comment by vbudhram** [comment]
@rfk Sounds good to me, I'll have some more cycles this train to work on it.
