### ISSUE TITLE
Send Tab from iOS to Nightly didn't deliver

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3039]
I tried sending a tab from iOS version 24.1 to Firefox Nightly version 77.0a1. On iOS it said it Sent but I never received it on Nightly.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-1180)
┆Epic: Send Tab (& Devices) Improvements
┆Sprint: Backlog

**Comment by garvankeeley** [comment]
Does this work on the v25 beta? How reproducible is this?

**Comment by AnaMedinac** [comment]
@garvankeeley It's the same on v25 beta. It's been fairly consistent so far. It took a couple of days to deliver the tab I sent before filing this bug. I tried it today and when I click Sync Now on desktop I receive all of them instantly.

**Comment by eoger** [comment]
This might mean there's an issue on Desktop Push instead, since you're getting a tab after pressing "sync now", we should probably open this bug on bugzilla instead.

**Comment by AnaMedinac** [comment]
Filed it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1633892
