### ISSUE TITLE
Sending tab from Desktop Nightly to Fennix Nightly requires me to manual Sync in Fennix to get my tabs received notification

### ISSUE THREAD

**Issue by jchaupitre** [mozilla/application-services#3048]
Able to consistently reproduce this issue. Please provide instructions for me to extract logs from Fennix on my Android Essential PH-1.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1193)
┆Epic: Send Tab (& Devices) Improvements
┆Sprint: Backlog

**Comment by rfk** [comment]
Getting some adb logs would be very help, I found this guide which explains how to install logcat without setting up a whole android dev environment:

  https://support.citrix.com/article/CTX232375

If you're able to get `adb logcat` up and running, try capturing the logs across the whole process of:

* Close and re-open Fenix (this might log some info about setting up the push connection)
* Send yourself a tab from Nightly
* Wait a bit for the tab to not appear
* Manually sync and receive the tab

Hopefully we can find some clues in there.

**Comment by jchaupitre** [comment]
[logcat.txt](https://github.com/mozilla/application-services/files/4552822/logcat.txt)

Thanks for the detailed instructions. See the log attached.

**Comment by mhammond** [comment]
The log appears to show that push did see the message, but there's no evidence the app actually saw it. `push_ffi: push_dispatch_info_for_chid` and a subsequent log saying it's being decrypted is seen, this crickets, until the "sync now.

```
<snip lots of stuff, Fenix is starting>
Push service initializes...
04-29 08:58:21.713 19934 19934 D PushConfig: Creating push configuration for autopush.
04-29 08:58:21.721 19934 19934 I App     : AutoPushFeature is configured, initializing it...
04-29 08:58:21.722 19934 19977 D AutoPushFeature: Initializing native component with the cached token.
04-29 08:58:21.722 19934 19934 I AutoPushFeature: Checking validity of push subscriptions.

<snip lots of gecko starting up, rust components initializing, first sync, etc>

04-29 08:58:40.824 19934 19988 I sync_manager::manager: Sync finished with status Ok
04-29 08:58:40.824 19934 19988 I sync_manager::manager: engine "passwords" status: Ok(())
04-29 08:58:40.824 19934 19988 I sync_manager::manager: engine "history" status: Ok(())
04-29 08:58:40.826 19934 19988 I sync_manager::manager: engine "bookmarks" status: Ok(())
<snip lots of glean submitting pings, etc>
Now push sees something...

04-29 08:59:06.806 19934 19980 D SyncWorker: Starting sync... Tagged as: [mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common]
04-29 08:59:07.800 19934 19977 I AutoPushFeature: New push message decrypted.
04-29 08:59:07.802 19934 19977 D push_ffi: push_dispatch_info_for_chid
04-29 08:59:07.811 19934 19977 D push_ffi: push_decrypt

< and that's the last we see about it - after 20 seconds a sync starts - probably the "sync now"?>
04-29 08:59:27.215 19934 19980 I FirefoxAccount: Executing: get access token
...
04-29 08:59:27.409 19934 19988 I FxaDeviceConstellation: Executing: polling for device commands
04-29 08:59:27.409 19934 19988 D fxaclient_ffi: fxa_poll_device_commands
04-29 08:59:27.455 19934 19981 I sync15::client: Successful request to "/1.5/138263079/info/collections", incoming x-last-modified=ServerTimestamp(1588175921190)
...
04-29 08:59:27.587 19934 19988 I FxaDeviceConstellation: Successfully executed: polling for device commands
04-29 08:59:27.589 19934 19934 I AccountEventsIntegration: Received events, notifying listeners
04-29 08:59:27.589 19934 19934 D EventsObserver: Showing 1 tab(s) received from deviceID=7cb47ac64fa5ea268c52994ce958dfc1
04-29 08:59:27.590 19934 19981 D sql_support::conn_ext: Transaction commited after 15.605366ms
04-29 08:59:27.590 19934 19934 D NotificationManager: Showing 1 tab(s) received from deviceID=7cb47ac64fa5ea268c52994ce958dfc1

<and there it is>
But later, the gecko push service initializes.
But I *think* we don't rely on that?

04-29 08:59:30.683 20255 20281 D GeckoPushService: Registered Gecko event listener.
04-29 08:59:30.684 20255 20281 I GeckoPushService: Starting up.
04-29 08:59:30.684 20255 20255 W GeckoEventDispatcher: No listener for AudioFocusAgent:Ready
04-29 08:59:30.684 20255 20281 I GeckoPushManager: Startup: requesting GCM token.
04-29 08:59:30.688 20255 20281 I GeckoPushGCM: Cached GCM token exists.
```

**Comment by rfk** [comment]
> But later, the gecko push service initializes.
> But I *think* we don't rely on that?

We don't rely on it, but I am lightly suspicious that maybe it somehow interferes with the native push handling in the application.

This feels like the push component is failing to route the message to the FxA component, possibly because something has gotten out of sync with the subscription. Notably ***missing*** from the logs is a line like:

```
04-29 08:59:07.811 19934 19977 D fxaclient_ffi: fxa_handle_push_message
```

Which would indicate the send-tab push message being routed to the FxA client code.

**Comment by rfk** [comment]
@jonalmeida or @eoger I wonder if either of you can suggest additional debugging we could do here? @jchaupitre has a device where the push state seems to be not correctly connected to the FxA client code but we don't have any clues as to why. He could probably try some things to restore it to a good state (e.g. sign out and sign back in) but it seems like a good opportunity to try to figure out what the bad state is.

**Comment by jonalmeida** [comment]
@jchaupitre when did you first log into sync? What version of Fenix are you running (release or nightly)?

This looks similar to https://github.com/mozilla-mobile/fenix/issues/9120 which was fixed but may have left nightly (and maybe some fenix release) users in a broken state until a fresh install.

> Notably _**missing**_ from the logs is a line like:
> 
> ```
> 04-29 08:59:07.811 19934 19977 D fxaclient_ffi: fxa_handle_push_message
> ```
> 
> Which would indicate the send-tab push message being routed to the FxA client code.

This strongly suggests that it's similar to the bug above where we were receiving and decrypting push messages, but not delivering it to FxA at the final step.

I can look at it again with fresh eyes in the morning to verify, but if you're no longer able to reproduce this after clearing app data (as a final resort) I would suspect the issue should go away.

**Comment by jonalmeida** [comment]
I can't see any other changes that occurred in push that would have caused this, so I'm more confident the above linked issue is the cause.

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

[~jchaupitre@mozilla.com] It might be fixed now, would you be able to see if you can reproduce the behaviour?

**Comment by jchaupitre** [comment]
I have applied the resolution steps from mozilla-mobile/fenix#9120, i.e. sign-out and sign back in on my mobile Nightly, and now am getting the send tabs immediately. I'm closing this.

Thanks all!
