### ISSUE TITLE
Protobuf crashes in v0.58.1

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3053]
See https://github.com/mozilla-mobile/fenix/issues/10277 for context.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1200)
┆Sprint: Backlog

**Comment by liuche** [comment]
Sounds like we'll need an AS and AC dot release to get this into Fenix 5.0? (this bug was filed during 5.0 QA)
