### ISSUE TITLE
[iOS] processAccountEvents should drive the manager state to disconnected

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3056]
We should:

* Stop trying to be smart and `disconnect` [from the Rust side](https://github.com/mozilla/application-services/blob/99c9e87de0805408ca13324143916737a831d3cb/components/fxa-client/src/push.rs#L46-L48) if our own device was disconnected from a Push message.
* `DeviceConstellation` should somehow call `logout` on `FxAccountManager` (it's an async method, so we'd need to make sure we're not doing anything bad here)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2492)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865171

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
