### ISSUE TITLE
Investigate switching from `failure`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3081]
failure ([https://github.com/rust-lang-nursery/failure](https://github.com/rust-lang-nursery/failure)) has been deprecated. We should take a look at [https://github.com/dtolnay/thiserror](https://github.com/dtolnay/thiserror) or some other thing to switch to. 

This is a Jira Spike. Discussion is welcome :grinning:

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-1232)
┆Story Points: 5
┆Sprint: SYNC - end 2020-06-05

**Comment by vladikoff** [comment]
from @thomcc 

> the way we use errors is a little more app-like in some cases -- i think we should use thiserror for cases where we just do the derive and then in cases where we use failure::Error use anyhow

**Comment by thomcc** [comment]
I've used several crates for error handling in the past.

- `anyhow`: really clever and cool library. Replaces `failure::Error` but not the failure proc-macro. 
	- If you have some free time and are interested in tricky rust code, I highly recommend reading [this](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md) which talks about the design a little, and the way it handles vtables in https://github.com/dtolnay/anyhow/blob/master/src/error.rs to get "do-what-i-mean" downcasting is extremely cool.

	- Note that it has no support for backtraces on stable rust, and is waiting for that to stabilize rather than using the `backtrace` crate the way `failure` does. 

        - I've heard https://github.com/yaahc/stable-eyre is essentially a drop-in replacement for `anyhow` that supports backtraces on stable rust but haven't used it. I trust the author based on their other work in the rust ecosystem, but this (nor the library it's based on) isn't (yet) vendored into m-c (although that probably wouldn't be a problem?). I also don't know how stable it is in general.

    	- That said, we don't actually ship backtraces in most places (backtrace-rs had android segfaults, and may still), so maybe this doesn't matter?

- `thiserror`: Essentially replaces `failure`'s proc macro and over 50% of our `error-support` crate.
	- Not exactly the fastest to compile, but nothing based on proc macros is. Shouldn't be any worse than failure in this respect.
    - We'd still need to use some sort of type-erased error type for cases like   `sync15_traits::Store`. Either `anyhow` or, honestly, at this point even `Box<dyn std::error::Error + Send + Sync + 'static>` would probably be fine...
	- I think we should definitely use this.

- `snafu`: I like the design of this library but found it pretty tricky to use, and not worth the trouble. 

- Another option would just be extending error-support to just implement what we need. I don't think this would be that much work, but it probably would end up with the worst ergonomics, unless we took the time to do a good job.

See also https://blog.yoshuawuyts.com/error-handling-survey/
