### ISSUE TITLE
fxa-client: Obtain ecosystem_user_id via scoped-keys login flow

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3088]
Account Ecosystem Telemetry involves two identifiers, as described in #3085: `ecosystem_user_id` and `ecosystem_anon_id`. As a an FxA client app, we can learn the value of `ecosystem_anon_id` from the user's profile data at any time, but `ecosystem_user_id` is derived from the user's master key, so we only get one chance to learn it: during signin.

In theory, learning `ecosystem_user_id` should look the same as requesting any other key-bearing OAuth scope: we include a special scope string like "https://identity.mozilla.org/tokens/telemetry" in our auth request, we receive back a key corresponding to that scope, and we use it at the value of `ecosystem_user_id`

Precise details TBD as the FxA side of things shapes up, but filing this here for our tracking purposes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1248)
┆Epic: AET Later
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

We're no longer pursuing this approach for AET, closing out the remaining bugs.
