### ISSUE TITLE
Implement client-side iOS send tab metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3094]
Implement Send Tab events on the iOS client side, if I understand correctly, once we implement this then we can see it in Amplitude and redash as well. {color:#d1d2d3}
 {color}

The goal here is to have parity with Desktop send-tab telemetry events.  Additionally we should also measure the fxa-client [recovery mechanism](https://github.com/mozilla/application-services/blob/b95215f21b3b2755c662af5aeca7d7de34fa5073/components/fxa-client/src/send_tab.rs#L72-L80) to understand how often it is required and why.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1253)
┆Story Points: 8
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-09-11

**Comment by rfk** [comment]
+1 to this, but also flagging that it's a non-trivial amount of work, since IIUC firefox-ios does not yet implement any of the sync-ping in which these metrics get sent. I I'm not sure how big a pile of dependencies there may be underneath getting at these metrics.

**Comment by garvankeeley** [comment]
Possibly non-trivial on iOS client side as send tab runs in an app extension, and in extension context we can't always access core app libraries (Glean is currently having that problem for instance). Solvable stuff though.

**Comment by linacambridge** [comment]
Using https://github.com/mozilla-mobile/firefox-ios/pull/6825 for the PR.

**Comment by data-sync-user** [comment]
➤ Lina Cambridge commented:

The PR is in (final 🤞) review, we'll get it landed this week! \o/
