### ISSUE TITLE
Investigate tabs never arriving in iOS devices

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3097]
This bug is to figure out what's causing a tab sent from another device to never arrive on iOS with no notification at all (not even "Tap to begin").
It seems the problem is pretty prevalent, as I can reproduce reliably when sending a bunch of tabs in short intervals to my iPhone.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-1256)
┆Story Points: 5
┆Epic: Send Tab (& Devices) Improvements
┆Sprint: SYNC - end 2020-05-22

**Comment by eoger** [comment]
Update:

From investigation with @jbuck, the autopush servers are returning with a `Received unexpected response code` [error](https://github.com/mozilla/fxa/blob/d458e4b3977a2ef9e5f25d5942b3d1f5effe179f/packages/fxa-auth-server/lib/push.js#L445). However we don't log the response code we're using the default JS's `toString` that doesn't include [extra properties](https://github.com/web-push-libs/web-push/blob/d7839a84c282ab3fd3c50e8051bcac73665fad80/src/web-push-error.js#L8-L11).

**Comment by eoger** [comment]
Filed https://github.com/mozilla-services/autopush/issues/1383 for further investigation on the Push side.

**Comment by eoger** [comment]
cc @Anamedinac as this is relevant to your product interests :)

**Comment by rfk** [comment]
I have to imagine this is some sort of rate-limiting being enforced by the apple push servers, as a first guess :-/

Given that push is so central to how we expect send-tab to work, do you think it would be worth having the FxA server fail the `invoke_command` request if it's not able to send the push notification? IIRC it's currently fire-and-forget.

**Comment by eoger** [comment]
> Given that push is so central to how we expect send-tab to work, do you think it would be worth having the FxA server fail the `invoke_command` request if it's not able to send the push notification? IIRC it's currently fire-and-forget.

It might be worth doing if we hit a 100% failure rate (N devices to notify, N failures) in [push.js](https://github.com/mozilla/fxa/blob/7484c12f9eb163c6f4ff01306afee3eb8e287570/packages/fxa-auth-server/lib/push.js#L370). However if we throw here we most likely want to try-catch in the other methods (`notifyDeviceConnected)` since their callers are not expecting them to throw.

**Comment by eoger** [comment]
I'm going to close this since upgrading autopush "seems" to have fixed the problem and open some relevant bugs.

**Comment by rfk** [comment]
> upgrading autopush "seems" to have fixed the problem

For completeness, by "upgrading autopush" do you mean the fix in https://github.com/mozilla-services/autopush/pull/1385 ?

**Comment by eoger** [comment]
Yes that's correct, I still don't understand how it fixed the problem though...

**Comment by eoger** [comment]
Actually, while retrying this for a last time when closing the issue, I've been able to reproduce both with my phone and my node "helper app":

```
Error sending push notification WebPushError: Received unexpected response code
    at IncomingMessage.<anonymous> (/Users/eoger/pushiostest/node_modules/web-push/src/web-push-lib.js:341:20)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 502,
  headers: {
    'access-control-allow-headers': 'content-encoding,encryption,crypto-key,ttl,encryption-key,content-type,authorization',
    'access-control-allow-methods': 'POST',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'location,www-authenticate',
    'content-type': 'application/json',
    date: 'Fri, 15 May 2020 14:38:41 GMT',
    server: 'nginx',
    'strict-transport-security': 'max-age=31536000;includeSubDomains',
    'content-length': '175',
    connection: 'Close'
  },
  body: '{"code": 502, "errno": 999, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "APNS returned an error processing request"}',
  endpoint: '<redacted, ask on Slack>'
}
```

**Comment by eoger** [comment]
From [Slack discussion](https://mozilla.slack.com/archives/C4E35LBBR/p1589553633240600) with @jrconlin, we have identified a few things:
- Autopush does not log APNS status codes.
- We think that, because the delivery issues came back ~7 days after the last deployment, we might be having problems with long-lived HTTP2 connections with the APNS servers (or certs/tokens/whatever are expiring somehow). Logging the APNS errors is crucial to determine what's happening.

In the meantime, JR proposed to add timeouts to kill inactive APNS connections (https://github.com/mozilla-services/autopush/issues/1393) and add logging.

**Comment by vladikoff** [comment]
QA filed a new bug for this https://github.com/mozilla-mobile/firefox-ios/issues/6637
