### ISSUE TITLE
Add descriptions for all fields in Android ServerPassword

### ISSUE THREAD

**Issue by eliserichards** [mozilla/application-services#3115]
Some of the Android [ServerPassword](https://github.com/mozilla/application-services/blob/main/components/logins/android/src/main/java/mozilla/appservices/logins/ServerPassword.kt) fields are missing descriptions. Example: 

```
val usernameField: String,
val passwordField: String
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2499)
┆Epic: Important backlog

**Comment by lougeniaC64** [comment]
FYI: Descriptions for both fields can be found [here](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/logins/src/login.rs#L103) and [here](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/logins/src/login.rs#L113).

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
