### ISSUE TITLE
Send Tab UIs should display "Failed" if the FxA server errors out sending the tab

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3121]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2500)
┆Epic: Important backlog

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

One nuance is that there can be partial failures here. There's "the sent tab was not enqueued at all" and there's "the sent tab was enqueued, but we failed to send a push notification". Is it useful for the client to be able to distinguish (and maybe show different UI for) these two kinds of failure?

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865175

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
