### ISSUE TITLE
authorize_code_using_session_token missing fields

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3122]
I've noticed this method, despite having bindings on Android, is not being used at all (I believe it was added for FPN).
We will definitely use it for [pairing on desktop](https://searchfox.org/mozilla-central/rev/9f074fab9bf905fad62e7cc32faf121195f4ba46/services/fxaccounts/FxAccountsPairing.jsm#315), however the HTTP request it makes is missing a few fields, namely [code_challenge, code_challenge_method and keys_jwe](https://searchfox.org/mozilla-central/rev/9f074fab9bf905fad62e7cc32faf121195f4ba46/services/fxaccounts/FxAccountsClient.jsm#274-285).

One difficulty here is the `keys_jwe` parameter: we'd like the method to accept a `keys_jwk` and handle the encryption to a `jwe` itself. We have some [prior art on mozilla-central](https://searchfox.org/mozilla-central/rev/9f074fab9bf905fad62e7cc32faf121195f4ba46/services/fxaccounts/FxAccounts.jsm#1669) but in any case it's not trivial. I'm not sure if it helps but we have the inverse operation [implemented in Rust](https://github.com/mozilla/application-services/blob/76ee86e38cbe15727a4333755b58e34722ca2aa0/components/fxa-client/src/scoped_keys.rs#L92).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1288)
┆Story Points: 5
┆Epic: Refactor Desktop FxA APIs to use Fxa-client & AccountMananger
┆Sprint: SYNC - end 2020-07-17

**Comment by rfk** [comment]
Cross-linking https://github.com/mozilla/application-services/issues/3086, which will also need the ability to encrypt things into a JWE (for different reasons, but the same basic operation).
