### ISSUE TITLE
[iOS] Send tab key failures reported from fxa_client::send_tab

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#3124]
We are now logging send tab errors in Sentry, and we are seeing key failures reported.

https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-v250/?query=is%3Aunresolved+send_tab

![image](https://user-images.githubusercontent.com/5495083/81959477-83d05100-95dd-11ea-8407-85dc56f44483.png)

iOS v25.1
a-s v0.58.3

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1289)
┆Sprint: Backlog

**Comment by rfk** [comment]
> https://sentry-fm.prod.mozaws.net/

This appears to be a different sentry instance than the one used for e.g. FxA or Fenix errors. How do I go about getting an account on this one?

**Comment by rfk** [comment]
Interestingly, there seems to have been a big spike around May 7th and then few instances of the errors since then. Perhaps the "diagnose, clear and re-upload" approach really has put these devices back into a useable state!

**Comment by garvankeeley** [comment]
Thanks for looking at that report on Sentry; I agree, one spike, and then it is largely resolved, which matches the behaviour you describe. The code to repair the situation is working as intended, I am ok with closing this.

**Comment by rfk** [comment]
We haven't seen any of these events in the last 5 days, so I'm going to close this out. Thanks for following up @garvankeeley!

**Comment by eoger** [comment]
FWIW Sentry reported at some point that 95% of these failures came from my own device... :)
