### ISSUE TITLE
[iOS] increased battery consumption, appears to be due to sqlite calls

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#3125]
EDIT: Happy to do a screenshare with an a-s team member to show what the tool reports in its entirety.

We are seeing increased battery consumption over recent app versions, mostly background consumption. We know by-design that background work is sync/storage related. I included the screenshot showing the issue over the various versions (for the 50% percentile, i.e. most common case, on iPhones).
We also have in Xcode's data reporting an *Energy* consumption view which shows a sampling of high-consuming functions. Nearly all these have `sqlite3` in the terminus, I will include some of these samples. There are many variants of stack traces, so it would be easiest to browse these in the reporting tool, so I can help someone get access to it if they want. An expert a-s person might by scrolling through reports get insights that I can't provide.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/5495083/81982639-2a2d4e00-9600-11ea-953a-c11d269807ae.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1290)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by garvankeeley** [comment]
![image](https://user-images.githubusercontent.com/5495083/81983435-6614e300-9601-11ea-8108-708aa815828f.png)

**Comment by garvankeeley** [comment]
![image](https://user-images.githubusercontent.com/5495083/81983475-762cc280-9601-11ea-9264-143b5bafdf25.png)

**Comment by garvankeeley** [comment]
I don't think we have enough data to state with any certainty there is a problem here, we don't know how accurate the energy consumption sampling tool is in terms of correlating with the battery consumption. To me, the energy consumption stack traces look like 99% percentile worst-case sampling (because there are so few, and the fact they are sampling operations that are 2 mins long seems extreme).

**Comment by rfk** [comment]
> We are seeing increased battery consumption over recent app versions, mostly background consumption.

Out of curiosity, what generates these reports?

**Comment by garvankeeley** [comment]
Xcode ‘organizer’ is a view within xcode that shows crash logs and this info for your app from users who have opted in to data collection. We can grant access to it somewhat freely within the company. We also use it to get app launch metrics and catch regressions there. Sometimes these energy reports are more actionable, and can be reproduced with local profiling tools and fixed.
