### ISSUE TITLE
Expose information needed for migration telemetry from webext migration

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3133]
In #3116 we landed support for migrating kinto data to the new webext database. However, it doesn't contain any information about the migration, and that was deferred until later.

In https://bugzilla.mozilla.org/show_bug.cgi?id=1628893#c6 I gave an overview of some of the things we might want to include for migration info as part of a "get data-reviewers on the same page" comment.

Currently, for migrations, it includes adding the following to the sync ping. 

```
        "migrations": [{
            "type": "webext-storage",
            // The number of records detected prior to migration.
            "numDetected": integer,
            // The number of records successfully migrated
            "numSucceeded": integer,
            // The number of records we failed to migrate.
            // `numFailed + numSucceeded` should equal `numDetected`.
            "numFailed": integer,
            // The amount of time the migration took in milliseconds
            "duration": integer,
            // True if any exceptions or `Result::Err`s were produced when
            // attempting to migrate.
            "anyFailures": boolean,
            // If migration failed, indicates why. Optional
            "failureReason": /* existing sync ping error instance */,
            // True if the existing table exceeded quotas (not an error
            // for migration)
            "quotasExceeded": boolean,
        }]
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1301)
┆Story Points: 3
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-06-05

**Comment by data-sync-user** [comment]
➤ Thom Chiovoloni commented:

Update: seems that there's further discussion needed here on what would make this acceptable. Do we not want migration telemetry? It's not clear to me.
