### ISSUE TITLE
Improve useability and monitoring of FxA server metrics around push notifications

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3135]
In recent debugging of send-tab failures, I was able to use the FxA server logs in bigquery to get a good sense of how many send-tab attempts failed to successfully deliver a push notification. Since this is a key aspect of the overall performance of the send-tab product experience, we shouldn't depend on "ryan trawls through logs in bigquery" for ongoing monitoring of these metrics.

Let's figure out how to get them on a dashboard somewhere, and maybe even set up some alerts.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1304)
┆Story Points: 5
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-06-19

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I filed https://github.com/mozilla/fxa/issues/5367 to discuss the specifics on the FxA side of things.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

The changes in the linked issue have landed, waiting for them to deploy before we can try making new graphs based on the results.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

This appears to be live in prod now! I'm digging in to see what we can tell from the new data.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I tried making a simple graph of attempts, failures, and successes in grafana here: https://earthangel-b40313e5.influxcloud.net/d/J81nRFfWz/auth-server?orgId=1&refresh=1m&from=1591834297257&to=1591855897258&var-environment=prod&panelId=56&fullscreen

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I've added a few more graphs to the above dashboard, under the "device push" panel. I think we can close this out.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Given the relatively high failure rates, I don't think there's value in trying to add any alerting on these metrics just yet.

**Comment by rfk** [comment]
Whoops, the above link is to one specific graph, here's the link to the whole dashboard (look for the "device push" section): https://earthangel-b40313e5.influxcloud.net/d/J81nRFfWz/auth-server?orgId=1&refresh=1m&from=1591834297257&to=1591855897258&var-environment=prod
