### ISSUE TITLE
Which version of Sqlite is being used on iOS?

### ISSUE THREAD

**Issue by chrmod** [mozilla/application-services#3139]
Was checking firefox-ios sources and cannot find any reference to sqlite version being used other than a fact it is now provided by application-services https://github.com/mozilla-mobile/firefox-ios/commit/9d853460e8667d690c344f2f4e0ce43cbb46c8fd#diff-7b2d70df6fb557246ecc29b745b6114d

SqlCipher version is 4.3.0 https://github.com/mozilla/application-services/blob/817ddf0b4c98656d551506d646d6156173e9b2cf/libs/build-all.sh#L5

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1313)
┆Sprint: Backlog

**Comment by lougeniaC64** [comment]
@chrmod this repo uses SQLCipher version 4.1.0 which is a fork of Sqlite version 3.27.2.

**Comment by lougeniaC64** [comment]
@chrmod Sorry, I provided you with the wrong info up there. The version of SQLCipher we're using at present is [4.3.0](https://github.com/mozilla/application-services/blob/d6f64c9a1e4978c668754d5fffc5e8d9c486fec4/libs/build-all.sh#L5) which forks [Sqlite version 3.30.1](https://www.zetetic.net/blog/2019/12/20/sqlcipher-430-release/). We have PR #3173 open which will bump our SQLCipher version to 4.4.0, and [Sqlite version 3.31.0](https://www.zetetic.net/blog/2020/05/12/sqlcipher-440-release/), when it's merged.

I'm going to close this issue, but feel free to join [Matrix](https://chat.mozilla.org/#/room/#sync:mozilla.org) or ping me with any other questions you have.

**Comment by chrmod** [comment]
@lougeniaC64 My impression was that SQLCipher is just a module for SQLite and thus I was confused. This aswers my question pefectly, thank you.

**Comment by lougeniaC64** [comment]
@chrmod No worries, I had to ask to get clarification on this myself. Glad I could assist! 😊
