### ISSUE TITLE
[Fenix][Bug] History/Bookmarks sometimes do not sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3149]
We've let this slip off our radar but should treat it as urgent

https://github.com/mozilla-mobile/fenix/issues/6713

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1334)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-03
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13349/screenshot-1.png">screenshot-1.png</a>

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

I can partially reproduce this. I can't think of a good reason these 2 shots should be different.

  * The containers page is showing twice on Fenix, once on desktop.
  * "Search results for container" doesn't appear on Fenix

It's not at all clear that this is the same problem, but it's also not at all clear why these discrepancies exist at all.

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

At least a couple of the issues I'm seeing are that Fenix is showing redirects where desktop is not. I opened https://github.com/mozilla/application-services/issues/3200 ( https://github.com/mozilla/application-services/issues/3200 ) for that and I'll dig a little more tomorrow for the others (but it looks like the only issues remaining are newer visits to accounts.firefox.com which reconnected the Fenix device - although it's not clear why they aren't being shown on the Fenix device!)

**Comment by mhammond** [comment]
This was closed because we can't reproduce the issue. We'd treat is as a priority if we could, so STR would be most welcome!
