### ISSUE TITLE
Add an API to expose usage information of various extensions in webext-storage

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3158]
This is required to revive the (previously removed) telemetry scalars.

Specifically, for each extension we need:

1. The number of items stored (e.g. the number of keys in the JSON objecT)
2. The number of bytes the JSON object occupies.

This doesn't require data-review, but the part of it on the mozilla-central side will.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1345)
┆Story Points: 3
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-06-05

**Comment by mhammond** [comment]
Is there a bugzilla bug for the consumer of this? Specifically, I'm a bit bothered by returning the extension IDs here - that can obviously never leave the machine, so whatever post-processing of this data will be done in mozilla-central is probably safer to do here?

**Comment by thomcc** [comment]
There's not yet a bugzilla bug for it, but it was collected previously and is described in the telemetry writeup (see the section on the scalars).

> that can obviously never leave the machine

Somewhat suprisingly, this doesn't seem to be true at all -- The old and current telemetry reports addon ids in a number of places.
