### ISSUE TITLE
Clarify what should go in automation/ build-scripts/ and tools/

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3172]
There's a bunch of scripts we have in these folders, but it's not quite clear to me what goes where. `build-carthage.sh` is also at the root of our repo and shouldn't be here imo.

Criteria for sorting scripts could be:

* Who's running it? Human? CI? Both?
* How frequently is it run?
* Which part of the "dev workflow" is this script helping with?
* Platform specific?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2503)
┆Epic: Important backlog

**Comment by rfk** [comment]
> Who's running it? Human? CI? Both?

This makes a ton of sense to me FWIW - `./tools` for things that should be run by humans, `./automation` for things that should be run by machines, and `./build-scripts`...well, maybe we don't need that one at all, or it could be moved under `./automation`.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1865178

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
