### ISSUE TITLE
Build a "device commands" success funnel from FxA server data

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3197]
Our [send-tab health dashboard](https://sql.telemetry.mozilla.org/dashboard/send-tab-new-version---bigquery-) is build around client-side metrics. Whenever a client sends a tab it logs  "command-sent" event with a unique identifier, and whenever a client receives a tab it logs a "comment-received" event with a matching identifier. By correlating "command-sent" and "command-received" events we can (in theory) get a sense of how many sent tabs are actually being delivered.

Using client-side telemetry for this will always be an imprecise science, since the telemetry pings are not necessarily submitted on a predictable schedule, users may opt-out of client-side telemetry, etc. Let's see if we can build as similar analysis using only server-side data from FxA.

**Key idea:** The FxA server queues sent tabs in pushbox, where they are assigned a unique numeric id. So we should be able to emit a "command sent" event when enqueueing a send-tab command, emit a "command received" event when deqeueuing a send-tab command, and use the unique id from pushbox to correlate them together.

**More specifically:**
* In the `/invoke_command` route, right where we [send the push notification to the receiving device](https://github.com/mozilla/fxa/blob/385692798dca63ab64471ecbb7cf111288643c2d/packages/fxa-auth-server/lib/routes/devices-and-sessions.js#L299), we could log a `command-send` event and tag it with :
    * The uid
    * The sending and receiving device ids
    * The pushbox index at which it was enqueued
    * The command identifier ("https://identity.mozilla.com/cmd/open-uri" in the case of send-tab)
* In the `/device/commands` route, where we [retrieve queued commands from pushbox](https://github.com/mozilla/fxa/blob/385692798dca63ab64471ecbb7cf111288643c2d/packages/fxa-auth-server/lib/routes/devices-and-sessions.js#L237), we could iterate over the list of commands being retrieved and, for each, log a `command-received` event tagged with:
    * The uid
    * The sending and receiving device ids
    * The pushbox index from which it was dequeued
    * The command identifier
* In analysis, we could use the tuple `(uid, receiving device id, pushbox index)` to uniquely identify a particular command and correlate sends to receives.

The `command-received` event here would not actually mean that the tab was successfully displayed to the server, e.g. a network error might occur before it's successfully sent back to the client. But measuring it this way would have a number of advantages:

* We can be sure we don't miss and events, both of these definitely have to happen on the server for a tab to be successfully sent.
* We don't have to rely on clients to include device identifiers, which they don't always do now that send-tab is decoupled from sync.
* We'll get accurate server-provided timestamps on the events, meaning we can get a an accurate measure of the latency between sending and receiving a tab.

IIUC we should be able to get these events from the FxA server logs into redash using daily export scripts [like this one](https://github.com/mozilla/bigquery-etl/blob/cec00f735fd2bb992a5226d4f4e01139fd0b84f9/sql/fxa_content_auth_events_v1.sql).

In an ideal world we'd be able to correlate these server-side events with client-side telemetry events, but that starts to stray into interesting ecosystem-telemetry user-privacy territory such as [Bug 1642855](https://bugzilla.mozilla.org/show_bug.cgi?id=1642855) which I don't think it's valuable to block on here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1366)
┆Story Points: 8
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-07-17

**Comment by rfk** [comment]
We could probably also log an intermediate event here indicating whether a specific push message succeeded or failed, to make for a finer-grained funnel.

**Comment by rfk** [comment]
I pushed a sketch for how this might work in https://github.com/mozilla/fxa/pull/5546

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

This is now up for review in https://github.com/mozilla/fxa/pull/5546. ( https://github.com/mozilla/fxa/pull/5546. ) New policy in FxA it to require a data-review for significant new metrics collection, which makes this an "8" rather than a "5".
