### ISSUE TITLE
Swift FxAccountDeviceConstellation should notify when push endpoint is expired

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3199]
The swift FxAccountDeviceConstellation currently [logs and ignores](https://github.com/mozilla/application-services/blob/9214e71f35ba8e1a04ed2c6f3753895544d55189/components/fxa-client/ios/FxAClient/FxAccountDeviceConstellation.swift#L39) the "your push endpoint has expired" flag set on its device record by the FxA server. It's important that the application be able to recovery from this state, otherwise send-tab will not work correctly.

@eoger what do you think about firing a notification event when we discover this, to allow the app to handle it?

As a first step, perhaps we can have the app log an error to sentry or submit telemetry when it receives this notification.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1370)
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-07-03

**Comment by eoger** [comment]
Yes I think it is a good idea, do we know how often we get a pushEndpointExpired on practice though?

**Comment by lougeniaC64** [comment]
@eoger @rfk Assuming this should stay in the backlog in the send tab epic?

**Comment by rfk** [comment]
> Assuming this should stay in the backlog in the send tab epic?

Yep, sounds good.

**Comment by mhammond** [comment]
> Yes I think it is a good idea, do we know how often we get a pushEndpointExpired on iOS in practice though?

I had the same question for desktop and Ryan said that, basically, it should never expire - except when it does :) We don't know what the mean time is for expiry, but there's no "expected" time.

**Comment by eoger** [comment]
We settled on: "let's log an error on Sentry"

**Comment by eoger** [comment]
> We settled on: "let's log an error on Sentry"

I ended up just re-registering when we see the flag, it was fairly easy actually.
