### ISSUE TITLE
Investigate the iOS sync engine metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3201]
The iOS sync engine metrics are all showing a 100% success rate ([https://sql.telemetry.mozilla.org/queries/71643#179856)](https://sql.telemetry.mozilla.org/queries/71643#179856)) which seems a bit suspicious.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1374)
┆Sprint: SYNC - end 2020-06-05

**Comment by rfk** [comment]
Ana and I discussed this a little today. My first theory was that iOS was only submitting sync pings for successful syncs, but that doesn't seem to be the case.

My next theory is that iOS is not reporting individual engine `"failureReason"` strings.

The linked query defines the following for counting successes and errors:

```
    COUNTIF(engine.failure_reason IS NOT NULL) AS count_errors,
    COUNTIF(engine.failure_reason IS NULL) AS count_success,
```

Where `engine` is an unnesting of the `sync.engines` JSON array from the ping payload:

```
  CROSS JOIN
    UNNEST(syncs.engines) AS engine
```

Grepping through the firefox-ios source, I see that it includes a "failureReason" field in top-level data dict for each sync (in what would be `syncs.failure_reason` in the linked query):

* https://github.com/mozilla-mobile/firefox-ios/blob/948bcf9905ecefb3b053d7ea9eeabb140b4d1776/Sync/SyncTelemetryUtils.swift#L314

But that's the only instance of the string `"failureReason"` I can find in the codebase. The struct that is used to populate each individual engine entry is defined here, and it doesn't seem to include a `"failureReason"` field:

* https://github.com/mozilla-mobile/firefox-ios/blob/948bcf9905ecefb3b053d7ea9eeabb140b4d1776/Sync/SyncTelemetryUtils.swift#L173

So, I think that firefox-ios is not reporting individual engine failures in the way that this analysis expects. We may be able to teach it to synthesize a `"failureReason"` field from that data that it does have available. Someone with more experience in the details of the sync ping may be able to turn this into an actionable bug for the firefox-ios team.

**Comment by thomcc** [comment]
Ah, right, I think this is actually a known issue that iOS isn't able to report individual sync pings.

I remember looking at it a long time ago and it being very painful to thread that data through, and it being wontfixed due to not having anybody to take it on: https://bugzilla.mozilla.org/show_bug.cgi?id=1415744

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

Closing it since we determined that iOS doesn't record engine failures the way that this query expects it to. Opening a new bug to identify how they record engine failures: https://jira.mozilla.com/browse/SYNC-1505
