### ISSUE TITLE
Protobuf decode error: failed to decode Protobuf message: unexpected end group tag

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3214]
Seems like there's a problem with "Protobuf decode error: failed to decode Protobuf message: unexpected end group tag" for Synced Tabs.

Synced tabs is behind a nightly flag, cant remove the flag with this crash

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1382)
┆Story Points: 8
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-03

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

From Fenix team, they mentioned Synced Tabs is important for release

**Comment by rfk** [comment]
> Synced tabs is behind a nightly flag, cant remove the flag with this crash

To clarify, is it default off in nightly (but you can enable it via a flag) or is it default on in nightly (but a flag ensures that it's default off on release)?

**Comment by thomcc** [comment]
Sadly this appears to still be happening :(

We should switch from protobufs to JSON here as a last resort.
