### ISSUE TITLE
Update fxaclient jcenter mirroring

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#323]
Now that we've renamed fxa_client => fxaclient.

Blocks https://github.com/mozilla-mobile/android-components/pull/1148

@ncalexan has to do this, I think.

**Comment by ncalexan** [comment]
"Your request to include your package /ncalexander/application-services/fxaclient in Bintray's JCenter has been approved."

**Comment by ncalexan** [comment]
https://bintray.com/ncalexander/application-services/fxaclient
