### ISSUE TITLE
Change our Bugzilla sync script to do a substring match on the whiteboard

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#3234]
@mnoorenberghe was asking if we do a strict or substring match for the `SACI` tag. I think [this](https://github.com/mozilla/application-services/blob/7b2ccb4501fba6da34d4c775d0698679741e0b92/tools/sync_bugzilla_to_github.py#L161) means it's an exact match, but, Googling around, we might be able to make it a substring match instead? ([This example](https://bluesock.org/~willkg/blog/mozilla/mentorable_bugs.html) shows `bug_mentor_type=contains&bug_mentor=`...can we do `whiteboard_type=contains&whiteboard=SACI`?)

This would help with bugs that we want to see in Jira, but that may already have whiteboard tags that other teams use.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1393)
┆Epic: papercuts
┆Sprint: Backlog

**Comment by linacambridge** [comment]
> can we do `whiteboard_type=contains&whiteboard=SACI`?

Answering my own question—yes 😅 See [these queries](https://bugzilla.mozilla.org/show_bug.cgi?id=731672#c31), for example.

There's also `whiteboard_type=regex`, fancy! I'm also wondering what the difference is between `substring` and `contains`. Searching for `regex` or `substring` in the [Bugzilla docs](https://bugzilla.readthedocs.io/en/latest/search.html) that [this page](https://wiki.mozilla.org/Bugzilla:REST_API) links to doesn't turn up anything 🤔

**Comment by linacambridge** [comment]
I think this is a good first bug! We need to do a couple of things:

1. Verify that `whiteboard_type=contains` does the right thing. You can do this by copy-pasting the Bugzilla URL that the `update_from_bugzilla` function in [this file](https://github.com/mozilla/application-services/blob/7b2ccb4501fba6da34d4c775d0698679741e0b92/tools/sync_bugzilla_to_github.py) into a browser, and checking that it fetches bugs in other components with the `SACI` whiteboard tag.
2. If it does, add the `whiteboard_type` param to [this block](https://github.com/mozilla/application-services/blob/7b2ccb4501fba6da34d4c775d0698679741e0b92/tools/sync_bugzilla_to_github.py#L160-L161).

**Comment by jad18** [comment]
From what I've found, it looks like the whiteboard search already does a substring match. For example, I looked up the whiteboard 'egr', and I got results for 'regression' and 'integration'. I also tested the differences between adding whiteboard_type=contains, whiteboard_type=substring, and no whiteboard_type at all, and I found no differences between the three (even for the 'SACI' tag). So you should already have what you want.

**Comment by sukriti1** [comment]
I am new to open source but I would love to work on this bug! It would be great if someone could help me understand the issue a bit better

**Comment by linacambridge** [comment]
Hi @sukriti1, welcome and thank you so much for your interest (and sorry for letting this issue slide for so long! 😬)

I think @jad18 is totally right, though—`whiteboard=` does a substring match by default, so this is already working correctly and there's nothing else to be done in this ticket. Thanks for digging into it and confirming, @jad18!
