### ISSUE TITLE
PlacesConnection#getBookmark crash when passing an invalid guid

### ISSUE THREAD

**Issue by person808** [mozilla/application-services#3252]
On Android the function PlacesConnection#getBookmark crashes when passed a guid for a bookmark that doesn't exist

Steps to reproduce (v60.0.0):

```
bookmarksStorage.getBookmark("this_does_not_exist")  // From PlacesBookmarkStorage in A-C

E/ffi_support::error: Caught a panic calling rust code: "called `Option::unwrap()` on a `None`
```

https://crash-stats.mozilla.org/report/index/fd41fd92-d43b-4af2-8fea-032be0200617

I believe null is supposed to be returned here. This is needed for mozilla-mobile/fenix#2165. When we sync from the bookmarks view we need to check if the bookmark node we are currently viewing still exists after the sync completes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1403)
┆Sprint: Backlog

**Comment by rfk** [comment]
Thanks for tracking this down. Tracing through the code I think we're triggering the `unwrap()` here:

  * https://github.com/mozilla/application-services/blob/25ca7fefeb02cb09ebe22abdfb924a57f99b4966/components/places/src/storage/bookmarks/public_node.rs#L101

This should instead check if the returned value is `None` and propagate it back to the caller if so.

How urgently do you need a fix for this? By default I expect we'll discuss it for prioritization in our next sprint planning (Friday next week).

**Comment by person808** [comment]
I can wait as I have a stop gap solution that I can use in Fenix until this is fixed. But having this fixed would definitely improve the UX of our bookmarks sync.
