### ISSUE TITLE
Don't log expected networking failures at "error" level

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3254]
Sentry has a nice collection of reports from viaduct about things that are expected, inevitable networking-related failures, such as these [network](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8681110/?query=is%3Aunresolved) [timeouts](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8678590/?query=is%3Aunresolved). It's reasonable for us to raise an error back to the application here, but I don't think we should be logging them to sentry.

Java has a log level above error (`FATAL`) and I've seen other languages have similar (e.g. `CRITICAL`) but I don't think rust has anything higher than `ERROR` level. Proposal: log things that are "we failed to do what you asked, for totally understandable reasons" at `WARNING` level, and keep `ERROR` level for things that are bad enough they should show up in sentry, in error logs from developers, etc.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1404)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-17

**Comment by rfk** [comment]
(I'm partly filing this bug to try out the process of reviewing sentry during triage rotation)

**Comment by thomcc** [comment]
An issue with this is that a lot of our error logging comes from automatically logging `Result::Err`s in the conversion. This isn't merely laziness, but rust makes it pretty unergonomic to log errors any other way, as you need to match on the error, and (apparently) filter out a specific subtype of error (which also Rust doesn't have good ergonomics for)...

So I don't think I disagree here, it's just easier said than done.

**Comment by eoger** [comment]
From meeting, we can:
- For network errors, add a `[NETWORK-ERROR]` or `[no-sentry]` token somewhere in the error message
Then either:
- In `RustLog` (preferable since it applies to iOS too), transform the error to a warn if we match the token.
- In a-c: if we match the token, don't send a sentry error.

**Comment by eoger** [comment]
Fixed by https://github.com/mozilla/application-services/pull/3273.
