### ISSUE TITLE
tabs ttl is not consistent with desktop

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#3258]
Indirectly via https://bugzilla.mozilla.org/show_bug.cgi?id=1646795, it seems that tabs as written by application-services has no TTL specified.

Desktop recently changed the TTL from weeks to a year. There's no reason for the rust component and desktop to have different values - one or the other should change to become consistent (and ISTM that the rust side might as well)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1407)
┆Story Points: 2
┆Epic: important not urgent
┆Sprint: SYNC - end 2020-07-03

**Comment by rfk** [comment]
So I had the idea that this might be a good-first-issue, and I went poking around in e.g. the clients engine to see how an existing engine sets the TTL on a record, and...well, it was kind of confusing and eventually led me to https://github.com/mozilla/application-services/issues/2712 which basically says it's a footgun.

I *think* it would suffice to add a `ttl` field on the `TabsRecord` struct [here](https://github.com/mozilla/application-services/blob/9521ee11ded194b443ed0df864960aa5be58bf88/components/tabs/src/sync/record.rs#L19) and then set it to some fixed value when converting the local tabs into a record [here](https://github.com/mozilla/application-services/blob/9521ee11ded194b443ed0df864960aa5be58bf88/components/tabs/src/sync/store.rs#L59). Does that sound about right?

**Comment by thomcc** [comment]
Yes, that's correct.

**Comment by rfk** [comment]
Thanks! I'll add a couple more notes for completeness then:

* An example of the `ttl` field to add to the `TabsRecord` struct, is the one on the `HistoryRecord` struct [here](https://github.com/mozilla/application-services/blob/04f2e0ee8ba94fc27509078381102a7b0f793ab6/components/places/src/history_sync/record.rs#L32).
* The appropriate value to set this to when making new records is `31622400`, which is the same value used by Desktop in [Bug 1573758](https://bugzilla.mozilla.org/show_bug.cgi?id=1573758).
