### ISSUE TITLE
Explore writing the fxa-pairing-channel in Rust

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3262]
For reverse pairing features we need the [https://github.com/mozilla/fxa-pairing-channel](https://github.com/mozilla/fxa-pairing-channel) library available via Rust.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1411)
┆Story Points: 8
┆Sprint: SYNC - end 2020-07-31

**Comment by tarikeshaq** [comment]
Status update here so it shows up in JIRA as well:
A functional (but long way to go) PR is here #3339

It implements the core logic of the TLS Pre-Shared Keys. There is still work to be done on docs, adding more tests, and also figuring out what the interface for consumers would look like

**Comment by data-sync-user** [comment]
➤ Vladislav Filippov commented:

Issue split into:

SYNC-1508Address rust pairing channel feedback
