### ISSUE TITLE
iOS: unexplained drop in sync telemetry by 1/3, Fx iOS v25 to v26

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#3270]
xref to https://github.com/mozilla-mobile/firefox-ios/issues/6816

From Ana:
Last week we noticed that there was a slight drop in Success Rate for our bookmarks sync engine, and we weren't exactly sure why this might be happening.
After some investigation, Vlad and I noticed that there was a steep drop in Total Sync Counts on iOS for all engines on May 29th, which coincided with the release of iOS V26. (https://sql.telemetry.mozilla.org/queries/71643#180397).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-1415)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by garvankeeley** [comment]
App-services lib changed from 0.58.0 (v25) to 0.59.0 (v26).

**Comment by garvankeeley** [comment]
cc @athomasmoz @hlsoto

**Comment by garvankeeley** [comment]
To recap from the x-ref bug on the iOS side:

 - FxA is not a problem (as per Ryan's investigation)
 - v25 to v26 is not the problem: v26 rolled out progressively at 1% on may 28th, and only reached significant uptake by June 3rd, peaking by June 7th. The problem graph shows a steep drop on May 26th, essentially a week early and the sharp drop is inconsistent with progressive app rollout.
- Ryan also investigated that there is not likely to be a problem with the client-to-syncservers communication based on user counts from the server logs.

All indications is there is a sync telemetry problem on the server side.

**Comment by thomcc** [comment]
https://sql.telemetry.mozilla.org/queries/71643#179856 shows 100% success rates for all sync pings received. I wonder if this isn't just a drop in the amount of telemetry sent, but is instead a drop in the amount of *successful* telemetry sent. E.g. it's an uptick in errors.

**Comment by garvankeeley** [comment]
Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1642386 is the problem? The format of sync pings became more strict, and the server side started rejecting FxiOS sync pings because one of the fields was sent as a single value, instead of an array (but in the FxiOS case it would always be a 1-element array).

**Comment by garvankeeley** [comment]
I'll fix the request from sync team:
```
Currently, Firefox for iOS is sending sync pings with the following payload:
"syncs":[...,"engines":[{...,"outgoing":{"sent":1,"failed":0}}],
while the expected format is outgoing being an array:
"syncs":[...,"engines":[{...,"outgoing":[{"sent":1,"failed":0}]}],
as specified in the sync v4 schema. This is causing a high number of validation exceptions and iOS sync pings getting written to payload_bytes_error.
```

**Comment by garvankeeley** [comment]
Closing as this is confirmed to be a sync telemetry issue. It would be ideal if sync telemetry changes were better communicated to a-s team.

Notably I don't recommend including the iOS team as a sync telemetry communication channel as I don't think that is sustainable since 
1) we have no existing communication channel with backend teams and spinning up another cross-team communication channel seems unrealistic to me when we would have no other meaningful comms with that backend team in the past 3 years (based on my past few years on this team).
2) the progression of our sync integration is reduce the amount of knowledge and work that happens in the iOS client side.
