### ISSUE TITLE
Figure out what the deal with network errors with no message is.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3276]
In #3274 @eoger determined the source of much of our network logging, as well as the source of the "Missing HTTP status" errors: the `Throwable` we catch in Kotlin happens to have a `null` message.

This seems like an upstream bug which should be fixed. Short of that, we should consider logging it's name instead in the future. You can do this via `e.getClass().getCanonicalName()` which would at least let us know what went wrong.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1420)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

1.5 yrs old. closing.
