### ISSUE TITLE
Renew logins and places metrics on Android

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3289]
The metrics for our "logins" and "places" Android components are due to expire soon, but we want to keep them in place for the release rollout of Fenix. Let's extend them from their original date of 2020-07-01 to 2021-03-01 (that's an extension of 8 months, but I don't want to have them expiring during the end-of-year holiday period or during the end-of-January all-hands event).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1431)
┆Story Points: 8
┆Sprint: SYNC - end 2020-07-03

**Comment by rfk** [comment]
(I also considered making these never expire, but I don't think we're quite at the point of declaring that we'll monitor all of them on an ongoing basis; their primary purpose right now is to help monitor for problems when Fenix hits release).

**Comment by rfk** [comment]
Data Review request will be at https://bugzilla.mozilla.org/show_bug.cgi?id=1649044

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

This is an `8`, because data-review.
