### ISSUE TITLE
Mergify seems broken after branch rename

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3301]
This is fallout from the default branch rename.

Essentially everything works except for the final operation of merging into the `main` branch. When that's attempted, it fails, and spits out a completely garbage error code that seems random each time. These searching for these error codes yields nothing.

I've spent a bit of time trying to debug this, without success, so I'm going to just file the issue about it and get back to working on other things. As it is all the CI works and you can still manually merge, just checkin-needed will fail until this is fixed.

My opinion is that we should fix this sooner rather than later, and it's probably something simple I've missed -- for example, I can't find if there's any config needed on the mergify side? (Is there really none?)

CC @eoger, since you set up mergify initially, although I'm happy to fix it if you know what's needed (as part of seeing the branch rename through to completion)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1438)
┆Epic: important not urgent
┆Sprint: Backlog

**Comment by eoger** [comment]
Are you still experiencing this? See https://github.com/mozilla/application-services/pull/3315 where it merged without any issues.

**Comment by tarikeshaq** [comment]
Had the same issue with https://github.com/mozilla/application-services/pull/3316

**Comment by eoger** [comment]
Ok next time please take a screenshot or something of the Mergify status page (it changes after a manual merge)
