### ISSUE TITLE
places' getVisitedUrlsInRange should allow omission of `end`

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#331]
The most common use of this function is going to be (likely) fetching history for last X weeks/days/months. Requiring `end` isn't necessary in that case, and might help avoid subtle issues with clock drift, etc. Query will also be slightly simplified for the common case, it'll be possible to just compare `start` with `last_visit_date_(remote/local)`.

**Comment by thomcc** [comment]
I think we'll just make it default to LONG_MAX or something in kotlin. If we want to optimize the query we'll do it inside the rust function. (Unless you just straight up don't need the range version, but in slack you indicated that it's still useful).
