### ISSUE TITLE
Validate requested scopes in authorize_code_using_session_token

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#3318]
As per the discussion in https://github.com/mozilla/application-services/pull/3264#discussion_r449359102

We need to add validating the scopes a client requests with the `FxA` server, so that we only sever the client the scoped keys they are allowed to request. This would be as follows:
- Do what the js client does and send a [scoped-key-data](https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsClient.jsm#314) request to the server, where it will respond with a subset of the requested scopes.
- Look internally into the state and do [what we currently do](https://github.com/mozilla/application-services/pull/3264/files#diff-a9e1165a3ac1c1602b346c00db33b006L174) on that subset, i.e:
  - Retrieve the scoped keys from the state matching the requested and validated scopes
  - Encrypt those keys using the current mechanism used in the function

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1453)
┆Story Points: 2
┆Epic: Refactor Desktop FxA APIs to use Fxa-client & AccountMananger
┆Sprint: SYNC - end 2020-07-17

**Comment by rfk** [comment]
> Do what the js client does and send a scoped-key-data request to the server, 

For completeness, I want to note that the js client *has* to make this request, in order to get the timestamps and salts and what-not that it needs to derive the scoped keys; it gets the extra security checks as a side-effect. We're doing it here entirely for the security-checking part.
