### ISSUE TITLE
Integrate history syncing with the reference browser

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#333]
Once we have history syncing, we need to integrate it in some way with the reference browser. We'll need to discuss this with the android-components team, but at a minimum, we should either perform a history sync at startup, or have a "sync now" button exposed in the browser.

**Comment by jdragojevic** [comment]
ref: https://github.com/mozilla-mobile/android-components/issues/1223 for "sync now" button issue.

**Comment by rfk** [comment]
There's a "sync now" button but it's not clear whether this has been plumbed in with the new history-syncing code.  Unassigning @mhammond since he's PTO, @linacambridge or @thomcc to investigate.

**Comment by mhammond** [comment]
"Sync Now" button works, so this is done.
