### ISSUE TITLE
Updating a manually created login throws malformed exception

### ISSUE THREAD

**Issue by eliserichards** [mozilla/application-services#3330]
While testing duplicate login error logic in Fenix, I came across an interesting case where a **manually created login** (using `about:logins`) that **has a potential dupe** cannot be updated. I'm not sure if the duplicates have anything to do with this, so I'm adding those details too.

### Steps to reproduce
In `about:logins`:
1. Create a new login: 
   Website address: `https://www.google.com`
   Username: `user1`
   Password: `lskdflsdkfjs`
2. Create a second login with the same web address:
   Website address: `https://www.google.com`
   Username: `user2`
   Password: `sdkjfhksd`
3. Sync to get logins on Fenix

In Fenix: 
1. Navigate to saved logins in the Settings menu
2. Open the newly created login and Edit the login
3. Change username or password
4. Save -> throw exception `logins::ffi: Invalid login: Login has illegal field: Origin is Malformed`

## Details 

Fenix is passing a `Login` type to AC's function:

```
               // must retrieve from storage to get the httpsRealm and formActionOrigin
                val oldLogin = activity.components.core.passwordsStorage.get(loginId)
                val origin: String = oldLogin?.origin!!
                
                // Update requires a Login type, which needs at least one of httpRealm or formActionOrigin
                val loginToSave = Login(
                    guid = loginId,
                    origin = origin,
                    username = usernameText, // new value
                    password = passwordText, // new value
                    httpRealm = oldLogin.httpRealm,
                    formActionOrigin = oldLogin.formActionOrigin
                )
...
                activity.components.core.passwordsStorage.update(loginToSave)
```

The values for `loginToSave`:
Guid: `{027da0af-46ac-f740-bd85-706c70ce7349}`,
Origin: `http://www.google.com`,
username: `user2`,
password: `sdkjfhksd`,
HttpRealm: `null`,
formActionOrigin: ``

We are receiving this in the logs: 
`logins::ffi: Invalid login: Login has illegal field: Origin is Malformed`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1464)
┆Story Points: 1
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-17

**Comment by grigoryk** [comment]
From a slack conversation, the problem here is the empty `formActionOrigin`:

```
it’s crashing here: https://searchfox.org/mozilla-mobile/source/application-services/components/logins/src/login.rs#505-510
and “origin” in this case isn’t actually origin, it’s form_submit_url: https://searchfox.org/mozilla-mobile/source/application-services/components/logins/src/login.rs#477
which is “” in your case
so Url.parse fails
```

ISTM that if desktop allowed creating/syncing this record, we shouldn't crash when trying to edit it.

Also, there's another bug here somewhere in here, as well. Just above, there is this check: 
```
        if self.form_submit_url.is_some() && self.http_realm.is_some() {
            get_fixed_or_throw!(InvalidLogin::BothTargets)?.http_realm = None;
        }
        if self.form_submit_url.is_none() && self.http_realm.is_none() {
            throw!(InvalidLogin::NoTarget);
        }
```
... which isn't catching an empty string `form_submit_url`, since it's not `None`. Granted, we probably shouldn't pass an empty string at all via the API, but in the calling Fenix code we're simply round-tripping `form_submit_url` value which we get back from the store.

**Comment by eliserichards** [comment]
Would it be at all possible to get a fix for this sprint/the coming sprint? We are hoping to have edit logins up and running in the next release of Fenix. CC: @liuche

**Comment by grigoryk** [comment]
... also it'll be nice to fix up that exception message to be more specific, e.g. it can easily point out that it was the `form_submit_url` that's invalid, not the `origin` as it implied.

**Comment by thomcc** [comment]
Form submit url is actually allowed to be "", which is distinct from None. Easy to fix I think
