### ISSUE TITLE
Implement simple history syncing

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#334]
We want to sync history in the simply and naively - we can "production-ize" this in a later issue. Roughly:

* Refactor the existing logins implementation so it can be reused by history.
* Implement a history store, which:
  * hard-codes a limit of 5000 items to download and apply.
  * hard-codes a limit of 5000 items to upload
* Exposes a function over the FFI to perform a sync

blocks #333

**Comment by grigoryk** [comment]
See also #399.
