### ISSUE TITLE
Prototype rapid experimenter component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3350]
A prototype based on [Mako (previously Fretboard)|[https://github.com/mozilla-mobile/android-components/tree/master/components/service/experiments](https://github.com/mozilla-mobile/android-components/tree/master/components/service/experiments)] to see how complex the transition from Kotlin into a cross-platform Rust library would be.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1485)
┆Story Points: 8
┆Epic: Nimbus Client SDK Exploration
┆Sprint: SYNC - end 2020-07-31

**Comment by tarikeshaq** [comment]
Vlad and I talked about what it would mean for the prototype to be done, and here's what we are hoping for:
- Having something that can run with glean on Andriod (done)
- Look at persistence and have basic persistence (probably with rkv) - In progress
- Have some benchmarks on the size of the Glean binary with the prototype in it - In progress
- Clean up the prototype and make it available for others to run natively with clear instructions - In progress

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

We wrapped up our prototyping, and here's what we have: https://github.com/a-s-dev/glean/tree/test-experiments-do-not-merge/glean-core/nimbus-experiments ( https://github.com/a-s-dev/glean/tree/test-experiments-do-not-merge/glean-core/nimbus-experiments )

It includes a README explaining the learning for the prototype and how to test it natively, also it describes the difference in the binary sizes (1MB).
