### ISSUE TITLE
Cut a-s version 61.0.9 for a-c next release.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3360]
Tracking for [https://github.com/mozilla-mobile/android-components/issues/7731](https://github.com/mozilla-mobile/android-components/issues/7731)

Include:

* Telemetry expiration extension: {color:#1d1c1d} {color}[https://github.com/mozilla/application-services/pull/3290](https://github.com/mozilla/application-services/pull/3290/files)
* Fix for logins: [https://github.com/mozilla/application-services/pull/3331](https://github.com/mozilla/application-services/pull/3331)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1489)
┆Story Points: 1
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-17

**Comment by jdragojevic** [comment]
https://github.com/mozilla/application-services/pull/3359

**Comment by thomcc** [comment]
Prev. release is stuck on code signing still: https://firefox-ci-tc.services.mozilla.com/tasks/groups/BR05fy81RSqmPjBcQUaN7Q

I'd rather not have to go through and cut a 61.0.10 if CI is just busted ATM, so I've reached out to the taskcluster team on https://chat.mozilla.org to a) notify them if the issue inj case they aren't aware, and b) determine if we should hold off briefly.

**Comment by data-sync-user** [comment]
➤ Thom Chiovoloni commented:

<jlund> @ tcsc: release automation has been suspended due to an ongoing infra issue with Taskcluster and our cloud provider. We are working on comms and hope to resolve within the next 24h.

**Comment by thomcc** [comment]
It looks like they'd rather us release this tomorrow, which is fine for the fenix team as well.

**Comment by thomcc** [comment]
Nevermind! Issue is fixed. Release v61.0.9 ended up getting flubbed as github's UI makes you go out of your way to cut a release against a branch other than the default, and I wasn't paying close enough attention, but v61.0.10 will be cut very soon.

After it builds I'll get an update PR up against AC

**Comment by thomcc** [comment]
https://github.com/mozilla-mobile/android-components/pull/7734
