### ISSUE TITLE
Feature Request: Federated Sync - Allow Anyone to create a Firefox Sync node

### ISSUE THREAD

**Issue by trymeouteh** [mozilla/application-services#3367]
Please allow anyone to be able to create a firefox sync node and allow users to signup and login to that node in all the firefox browsers. This is a good option for those who want to self host their data, those who do not trust Mozilla sync servers, and this can reduce the users on the Mozilla sync servers since there are more nodes to choose from.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1494)
┆Sprint: Backlog

**Comment by eoger** [comment]
The good news is that you can already do it: hosting an FxA and a Sync node yourself is not trivial, but with enough time and dedication [it is possible](https://mozilla-services.readthedocs.io/en/latest/howtos/run-fxa.html).

**Comment by trymeouteh** [comment]
how do you sign in to an account on a different server for syncing bookmarks and to manage your account (change email, etc)?

Can anyone host a FxA server and allow anyone to signup to that server or will the server be a private server?
