### ISSUE TITLE
[Tabs] Add a persistent storage for Synced Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#3373]
In Fenix, we want to pull the Synced Tabs feature up to the tabs tray to make it more visible and prominent to the user. A WIP screenshot of what this would look like:

<img width="300" alt="Screen Shot 2020-07-17 at 3 34 34 AM" src="https://user-images.githubusercontent.com/1370580/87816720-ca3c6900-c835-11ea-9538-d736acb7cd38.png">

On a cold boot, we always seem to be retrieving the tabs from the network, so there is a long pause where we have nothing showing up if you go to the tabs tray the first time. We're trying to optimize perceived performance over accuracy of correct tabs (so we're asynchronously requesting new tabs for changes as well), but we would like to show a cached version first.

The feature request/question I'd like to bring up is if it would be prudent to having a persistent storage within the native Rust layer to provide the caching mechanism or if it should live in the a-c layer.

Some thoughts:
 - Synchronizing a database within the a-c and a-s layer can be a bit odd. We would have two copies of the state in different layers that need to be kept up-to-date.
 - Would this caching benefit other Synced Tab consumers in the future?
 - What are the perf losses/gains?
 - This affects the perceived perf of the tabs tray so we can use some smoke and mirrors until we have a better solution since it happens on the cold boot only. That is to say, this might not be a release blocker.
 - What are the constraints of the team for prioritization? We could build something out in a-c if it's quicker but might end up being duplicate work. 

cc: @eoger

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2979)
┆epic: Tabs improvements
┆sprintEndDate: 2022-03-04

**Comment by eoger** [comment]
What's the timeline on this feature @jonalmeida ?

**Comment by jonalmeida** [comment]
@eoger we had already started the a-c and Fenix work to have this land by the end of the sprint, so I this isn't blocking it. I think having a solution landed by the end of August is the current timeline to avoid the (perceived) perf loss.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

closing this as a feature request we never acted on.  Please reopen or file a new request if this becomes an active request.

**Comment by jonalmeida** [comment]
@jdragojevic I think we need to re-consider this feature request again with the new H1 work for Synced Tabs in Fenix.

**Comment by grigoryk** [comment]
Another vote for doing this sooner rather than later. It'll certainly help with a variety of scenarios in Fenix.

**Comment by mhammond** [comment]
> This will have an effect on [FNXV2-19419](https://mozilla-hub.atlassian.net/browse/FNXV2-19419) for Fenix (and _might_ be an issue in the future).

Just to make sure expectations are set here: this will only impact things when starting Fenix *second and subsequent* times after closing desktop. The first time after starting, persistence will mean the *old* set of tabs is available - we will still need to sync to get the new fresh set.

So in some ways it might make the experience appear worse

Now: Fenix starts, shows *no* synced tabs, but is syncing. Tabs then get shown, but are always fresh
Then: Fenix starts, shows *stale* tabs from when Fenix was last run. Is syncing, tabs get updated.

IOW, it's either "no tabs, or only fresh tabs" vs "stale tabs which update to fresh tabs".

I'm not suggesting we shouldn't do this though, but it's not going to be a panacea and fresh tabs for "jump back in" will always be somewhat delayed.

**Comment by mhammond** [comment]
#4862 is merged so will be available in the next release, and https://github.com/mozilla-mobile/android-components/pull/11799 is a PR to leverage it, so I think we can call this done.
