### ISSUE TITLE
Only build megazords once in Taskcluster CI

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3389]
Apparently we're still doing this probably around 10x per push in taskcluster... Maybe more.

I remember from when I set up the megazords that this was avoidable, but a pain -- apparently we never got to doing it.

I just heard from @eoger how much Taskcluster CI costs us a month and... This is worth fixing, since it should reduce this number substantially (potentially around 10x -- there should also be a CI speedup as a result).

That said, tragically, I don't remember the details beyond that it requires adjusting how our android dependencies are set up, and possibly requires a patch or two in https://github.com/mozilla/rust-android-gradle.

So, perhaps step 1 would be investigation into how to do this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1512)
┆Story Points: 8
┆Epic: local development, ci and release (backlog)
┆Sprint: SYNC - 2021-06-25

**Comment by eoger** [comment]
FWIW the last time I tried to tackle this long-lived issue, I tried the simple solution of building all the android modules in the same run, but I cargo kept re-building archs it built before (never figured out why).

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I'm planning to spend a bit of quality time with our gradle scripts this sprint, optimistically pulling this in as part of that work.

**Comment by rfk** [comment]
> We could adjust the dependency in the gradle scripts so that running the tests depends on building full-megazord, but just
> building and publishing the android package does not.

I took a stab at this approach in #4188. Even if it does nothing for our CI costs, it's a nice improvement to the local test-running experience!

**Comment by rfk** [comment]
> But ideally we'd get it down to just 6, so I'm not calling this successful just yet.

In #4189 it's down to 7: 6 builds for the actual publication of the megazord on 6 platforms, and 1 build for running all the tests in a single TaskCluster task. I'm happy to stop there I think; it may be possible to invest significantly more energy and figure out how to test all the modules using the built megazord artifact, but that can be a problem for another day.
