### ISSUE TITLE
FFI errors

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#34]
We need to figure out how do we want to expose errors to callers (using an `out err` parameter), either a struct or simply an error code.

**Comment by thomcc** [comment]
exposing a C-compatible enum for an error code for some errors would work. Need to figure out what cases (if any) we need something richer though.

**Comment by eoger** [comment]
fxa-client side fixed by https://github.com/mozilla/application-services/commit/5c0ad7779c8356f4a3f4f182a4490b65fa3f7ed8, feel free to close if that issue is not necessary anymore.
