### ISSUE TITLE
[automation] Streamline .taskcluster.yml to reduce automation

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#340]
`.taskcluster.yml` uses JSON-E, which allows some conditionals and expansion.  This ticket tracks using that so we don't have so much duplication to invoke the task graph for `github-push` (release and code landing push to master) and `github-pull-request` (pull request changes) events from Github (after #313 has landed, that is).

**Comment by eoger** [comment]
We did this in https://github.com/mozilla/application-services/commit/b9f45401fa02cd5bb2df8e88af8e968b9a608d6d and https://github.com/mozilla/application-services/commit/42d387bbd178281d09caf8a8ec26250f34d9e66c, closing!
