### ISSUE TITLE
iOS is not mentioned in Connect Another Device pairing modal

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3415]
**Build**
Prod [Train 1.181.2]

**Affected platforms**
Windows 10
iOS 13.6

**Steps to reproduce**

1. Login on a desktop using a Firefox Account
1. Navigate to about:preferences?action=pair#sync.
1. Observe the second paragraph displayed in “Connect Another Device” modal.

**Expected results**
Both Android and iOS are mentioned as being able to scan the pairing code.

**Actual Results**
Only Android is specified in the following paragraph: “2. Then sign in to Sync, or on Android scan the pairing code from inside the Sync settings.”

![Screenshot](https://user-images.githubusercontent.com/18114210/88797889-b46f6200-d1ac-11ea-9217-5937ad85e5b2.png)UNITO-UNDERSCORE!27!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1546)
┆Sprint: SYNC - end 2020-09-25

**Comment by vladikoff** [comment]
@anamedinac Can we get a new string for this "Then sign in to Sync, or on Android scan the pairing code from inside the Sync settings.”"

should we just drop `Android` and say `mobile`? => Then sign in to Sync, or on mobile scan the pairing code from inside the Sync settings.”

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

The final copy proposal is on slide 4: https://docs.google.com/presentation/d/1IWwQtgGGiCPQ8VcKtOiPQ4FquFtVIjWZaNrHuqeqpnQ/edit?usp=sharing ( https://docs.google.com/presentation/d/1IWwQtgGGiCPQ8VcKtOiPQ4FquFtVIjWZaNrHuqeqpnQ/edit?usp=sharing )

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Implementation is at https://bugzilla.mozilla.org/show_bug.cgi?id=1664307

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Done as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1664307

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue was verified as fixed on Firefox 82.0a1 (2020-09-15) under Windows 10 64-bit. 

Screenshot!UNITO-UNDERSCORE!50 ( https://user-images.githubusercontent.com/18114210/93319016-0f6e1e80-f818-11ea-84dc-2a7b44fadef1.png )
