### ISSUE TITLE
First pass at FFI requirements for the Rust <-> Kotlin API

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3440]
[~teshaq@mozilla.com] had a draft for the list, we can review the list and document that somewhere

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1573)
┆Story Points: 3
┆Epic: Nimbus Fenix Client SDK
┆Sprint: SYNC - end 2020-08-14

**Comment by tarikeshaq** [comment]
For reference, here's the draft, It was posted on slack as well, I'll update it as we get more feedback:
```
namespace Experiments {};
dictionary ApplicationContext {
    optional string app_id;
    optional string app_version;
    optional string locale_language;
    optional string locale_country;
    optional string device_manufacturer;
    optional string device_model;
    optional string region;
    optional string debug_tag;
    # Might also include more/less things
    # But I'm expecting they'll be strings
};
dictionary Experiment {
    # Those seem like the only needed details for consumers
    # Full schema will be managed by the Rust crate
    string slug;
    string user_facing_name;
    string user_facing_description;
};
dictionary Config {
    # This may be missing some other values,
    # but they also will be strings
    optional string server_url;
    optional string uuid;
    optional string collection_name;
}
[Error]
enum ExperimentError {
   "NetworkError", "DbError"
   # Probably a few more errors here
};
interface Experiments {
    [Throws=ExperimentError]
    constructor(ApplicationContext app_ctx, string dbpath, optional Config config)
    # Gets the branch the user is in the experiment, otherwise null
    # we might need to add another function that looks similar but instead takes a `group` 
    string? get_experiment_branch(string experiment_slug);
    sequence<Experiment> get_active_experiments();
    void opt_in_with_branch(string experiment_slug, string branch)
    void opt_out(string experiment_slug);
    void opt_out_all();
     # for syncing with the server
    [Throws=ExperimentError]
    void update_experiments();
};
```

**Comment by rfk** [comment]
> dictionary ApplicationContext {
>    optional string app_id;

I don't think we've fully firmed up our story around `optional` record fields yet, may be worth making a specific issue to dig into what's required here.

**Comment by eoger** [comment]
ITSM that these fields should also be `nullable`?

**Comment by rfk** [comment]
Indeed. I wonder if the difference between "optional" and "nullable" is a webidl thing that's not really useful to us (like the difference between `null` and `undefined`) and we should get rid of one in favour of the other.

**Comment by linacambridge** [comment]
Hmm, yeah—I could see compiling `optional` to something like `optionalArg: T? = nil` in Swift and Kotlin, and a default value of `None` in Python so that callers can omit it for convenience...but it feels like there are stronger semantics we'll want to [enforce for optional arguments](https://heycam.github.io/webidl/#dfn-optional-argument-default-value) (and WebIDL defines dictionary properties as [`optional` by default](https://heycam.github.io/webidl/#idl-dictionaries)), and nullable is more explicit and closer to the behavior of `Option<T>` in Rust.

**Comment by rfk** [comment]
Right, yes, I guess the nice thing about `optional` args/fields is that you can provide a default value, and maybe that's the key thing we'd want to keep here.

**Comment by tarikeshaq** [comment]
Opened https://github.com/mozilla/uniffi-rs/issues/188 to track this conversation over there 😄

**Comment by tarikeshaq** [comment]
I think we are good for a "First Pass" so I'll close this, we have https://github.com/mozilla/uniffi-rs/pull/218 which will add the proposed nimbus API to a `uniffi` example. The API will also be probably revisited slightly as we progress to making it work, although I don't think we'll have any major changes.
