### ISSUE TITLE
Create Multi-Device Send Success Rate graph on Send tab dashboard

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3457]
Once we are receiving production release telemetry for send tab in Fenix and Mobile, we want to create a graph on the send tab dashboard that shows the [Multi-Device Send Success Rate.](https://docs.google.com/document/d/1v7O2Ih6YjYsZU_qlkLSDt_Nh8c9kKrEd5pysKs4xPt8/edit#heading=h.njv3e6derxvy)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2529)
┆Epic: Important backlog

**Comment by mhammond** [comment]
There's not much valuable here, so we can just create a new task if/when we decide to refocus on sendtab metrics.
