### ISSUE TITLE
Login Error Metrics on the Fenix Nightly Telemetry Dashboard are Rising

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3461]
Login errors in the [Fenix: Logins and Places Performance Metrics (Beta & Nightly Channels)](https://sql.telemetry.mozilla.org/dashboard/fenix-logins-and-places-performance-metrics?p_org_mozilla_fenix=org_mozilla_fenix_nightly) dashboard appear to be on the rise.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1611)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-08-14
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13774/Screen+Shot+2020-08-05+at+12.04.50+PM.png">Screen Shot 2020-08-05 at 12.04.50 PM.png</a>

**Comment by thomcc** [comment]
I think this is #3467, which is a known issue we've had for a while but has never been important enough to fix. Sadly, the nature of that issue makes it impossible to know for sure...
