### ISSUE TITLE
Consider moving ffi-support to dedicated repo

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3463]
Given that as of https://github.com/mozilla/application-services/pull/2894 we no longer use this as a `path` dependency (this change was required for vendoring in mozilla-central as we're not the only user of ffi-support there), it seems kind of tricky to make breaking changes to ffi-support — this is part of why I just deprecated things in #3462, rather than removing the old API.

Additionally, it's fairly confusing that we have this in our repo but are *not* using it as a `path` dependency. It also is a special case in that it uses a different license, and is the only piece that's published on crates.io...

Initially it was placed in this repo so that as we evolved our FFI story, we could easily add features, but this has firmed up a lot, so that reasoning doesn't seem to apply as much.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1612)
┆Story Points: 3
┆Epic: Nimbus: build Uniffi library to autogenerate ffi bindings
┆Sprint: SYNC - end 2020-08-14

**Comment by tarikeshaq** [comment]
FWIW I agree to make it a dedicated repo, I remember a while ago the "it's not a path" bit me when I was testing something and tried a local change to `ffi_support`.

Also, `glean` and now `uniffi` both use ffi_support.

**Comment by rfk** [comment]
+1

**Comment by thomcc** [comment]
This is in https://github.com/mozilla/ffi-support/, and once https://bugzilla.mozilla.org/show_bug.cgi?id=1657770 is resolved I'll file a PR removing it from this repo which will close this issue.

---

### How `ffi-support` was extracted while maintaining history

For future reference, these are the steps I used to extract `components/support/ffi` (and `testing/separated/ffi-support-extra-test`) into a separate repo while preserving history, rewriting commit messages referencing issues to refer to this repo, etc. I'm not sure where else to document this, but... It seems bad to not write it down anywhere, so an issue comment is arguably than nothing...

Anyway, the steps:

First, you need to install https://github.com/newren/git-filter-repo (which is what `git filter-branch` tells you to use if you invoke it now).

Move `testing/separated/ffi-support-extra-test` to `components/support/ffi/extra-tests` in commit history
```fish
$ git filter-repo --path-rename testing/separated/ffi-support-extra-test:components/support/ffi/extra-tests
```

Move `ffi-support` to the top level (preserving history).
```fish
$ git filter-repo --subdirectory-filter components/support/ffi
```

Delete tags (all of which are irrelevant now since we never tagged for ffi-support releases, since tags in mozilla/application-services kick off the release process).
```fish
$ git for-each-ref refs/tags --format="delete %(refname)" | git update-ref --stdin
```

Delete already-merged branches, including branches that don't have any content in them after the filter-branch operation.
```fish
$ git branch --merged | egrep -v "(^\*|main)" | xargs git branch -d
```

In commit messages, replace e.g. '#123' with 'mozilla/application-services#123', so that issue/pr links go to the right place.

I tried to also handle the case where we might have something like `foo#123` or something in a commit message (which clearly shouldn't be changed) but AFAICT it didn't come up. I suspect that if you try to reuse this in a meaningful way, this is a part you should think about the regex here more... and make sure that the output looks good for the commits.

Also note that the escaping might be a little different for you in bash/zsh. I used fish-shell here and have no idea how many backslashes would be right for anything else.
```fish
$ git filter-repo --message-callback 'return re.sub(b"(\\s|^)#(\\\\d+)\\B", b"\\\\1mozilla/application-services#\\\\2", message)'
```

And then some cleanup that was done manually (add .gitignore, CI, CoC, etc). See the commit messages starting at: https://github.com/mozilla/ffi-support/compare/efb2fd0209c4cc13023daa1d688b7d28b5d69da5...main for a more complete list.

P.S. Note that while we aren't using git-filter-branch, it's somewhat helpful to read https://manishearth.github.io/blog/2017/03/05/understanding-git-filter-branch/ for some understanding of what filter-branch/filter-repo do conceptually.
