### ISSUE TITLE
Replace SEC_OID_ANSIX962_EC_PRIME256V1 with SEC_OID_SECG_EC_SECP256R1

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3476]
From https://github.com/mozilla/application-services/pull/3465#discussion_r466586111 it should be a simple find and replace.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1630)
┆Sprint: Backlog

**Comment by Vishwa-Mozilla** [comment]
I will fix it

**Comment by eoger** [comment]
Closed by https://github.com/mozilla/application-services/pull/3477.
