### ISSUE TITLE
Implement a shared HTTP API abstraction

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#348]
We currently make network requests by taking a direct dependency on rust networking libraries like hyper.  Longer-term we would like all our components to use the native networking stack of the app into which they're bundled.  For example, if our components are incorporated into Fenix and Fenix is using the Gecko networking stack, then so should we.

There are some moving parts involved here that are still works in progress.  GeckoView is exposing a high-level `fetch` API here:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1405081

And android-components is working on a "networking" concept abstraction here:

  https://github.com/mozilla-mobile/android-components/issues/1012

While those are being resolved, we can take a step in the right direction by hiding our own networking calls behind an appropriately-shaped abstraction, while continuing to just use hyper et al initially.

From discussion with @ncalexan and @snorp, the appropriate shape is something akin to the `fetch` API:

  https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

So let's figure out how to hide all our networking details away behind a `fetch!()` macro that we can make extensible in the future.

**Comment by thomcc** [comment]
I strongly agree with the general idea, and suspect we might want something similar for crypto stuff (e.g. letting us use NSS). My issues are entirely with the details:

- Fetch is an asynchronous API, but the APIs we currently use for requests are all synchronous. This is a nontrivial change (rust's async/await support is still nightly-only), and one we can't safely make without the other (geckoview) piece of this -- we need to respond over the FFI synchronously (we can't call java from arbitrary native threads).
- I don't see why we'd use macros for it, it would probably just be a trait and set of types. Or even just a normal crate that offers a `#[cfg(feature = "necko")]`. (If we end up having to model something with macros that's probably fine, but it doesn't seem that likely that we'd need it to me)
- Given that fetch is an JS API, it's ownership requirements are not obvious, and so a direct port might lead to something awkward and unidiomatic.
- Calling into java currently has a great deal of overhead. We'll copy strings several times. It seems plausible to me that we could call functions in libxul if present, avoiding this issue, but I could be wrong.

The first of these is the only serious concern, and the others are nits (the macro thing) or constraints we have some flexibility with.

It seems to me like we could avoid some of this (the async part, and potential awkwardness in the mismatch between trying to use a JS-based API in rust) by using reqwest (the synchronous http lib which we already use) as the model, and planning on implementing something roughly equivalent to it on top of what we get from geckoview when it becomes available.

**Comment by rfk** [comment]
> suspect we might want something similar for crypto stuff (e.g. letting us use NSS)

Yes, strongly agreed.

**Comment by rfk** [comment]
> Fetch is an asynchronous API, but the APIs we currently use for requests are all synchronous.

Yes, definitely, let's make a synchronous one and we can figure out how to bridge to a future async geckoview-provided API when it comes time to do that integration.

> I don't see why we'd use macros for it

I don't feel strongly about using a macro for it; this was purely by analogy to @ncalexan's work on plumbing in the `log!()` macro to use the a-c logging infra.

> Or even just a normal crate that offers a #[cfg(feature = "necko")].

IIUC, having it as a feature-flag like this would mean another choice for the embedding application to make - it would have to explicitly pick the "gecko networking megazord build" or the "native-tls networking megazord build" or whatever.  I'm worried about a continuing combinatorial explosion of build configurations here.

@ncalexan, you have a mental model in mind for this from your work on `log!()` right, care to weigh in?

> It seems to me like we could avoid [a bunch of awkwardness] by using reqwest as the model,

This seems reasonable to me, if we're confident that we could build this API on top of what will eventually be exposed by GeckoView et al.

**Comment by thomcc** [comment]
> Yes, definitely, let's make a synchronous one and we can figure out how to bridge to a future async geckoview-provided API when it comes time to do that integration.

For future reference: The [source of reqwest itself](https://github.com/seanmonstar/reqwest) seems like a good starting place, since it makes the asynchronous `hyper` API into a synchronous one.

> IIUC, having it as a feature-flag like this would mean another choice for the embedding application to make - it would have to explicitly pick the "gecko networking megazord build" or the "native-tls networking megazord build" or whatever. I'm worried about a continuing combinatorial explosion of build configurations here.

The only way around this is going to be shipping code that some applications don't need. Which could be fine, but given that this is... possibly a fairly large amount of code (for an example, an entire rust-based networking stack in the case where we use necko), it could be a problem.

> This seems reasonable to me, if we're confident that we could build this API on top of what will eventually be exposed by GeckoView et al.

I guess I more mean "the subset of reqwest that we use", or something along those lines. My concern is mostly with starting with an API that's great for JS and ending up with one that's awkward in rust, which seems not entirely unlikely to me (a vaguely `fetch`-shaped synchronous thing is probably reasonably close to okay though, but there are certainly part of that API that would be a bit awkward).

I also expect that the rust libraries will have more constraints of the type 'we prevent <some sort of or perceived grossness> using the type system' (e.g. reqwest used to be quite opinionated about both headers and status codes in this way, not letting you use actual header strings or status code numbers -- admittedly, I think these requirements are relaxed now) than necko might, which could make things painful if we start with a API base without those requirements.

**Comment by rfk** [comment]
> Fetch is an asynchronous API, but the APIs we currently use for requests are all synchronous.

Our current plan is to plug this into the a-c `concept:fetch` implementation, which is documented as being synchronous:

  https://github.com/mozilla-mobile/android-components/tree/master/components/concept/fetch#asynchronous-requests

So that may simplify some things on our side here.

**Comment by thomcc** [comment]
Yeah, that does help. Still hard, though.

And hard even ignoring the FFI problems -- there's a lot of just normal work to do just wrapping things so that stuff can be made to work in our situation.

Note that we can't have a dependency on a-c (it would be cyclic), so we have to provide an equivalent interface/set of interfaces that their types implement as well... And then we also have to provide an equivalent set of types for Rust.

**Comment by rfk** [comment]
Right.  I imagine this looks like us implementing something along the lines of the `reqwest` types on the rust side, which gets serialized into a protobuf and sent over the FFI, which gets unpacked into objects that the `concept-fetch` implementation can accept, and then the reverse process to get the response back into rust...basically a whole bunch of data shuffling.

**Comment by rfk** [comment]
Note to self: even if this means we end up getting rid of `reqwest`, maybe we still end up using the objects from the [http crate](https://docs.rs/http/0.1.16/http/).

**Comment by rfk** [comment]
@grigoryk from your recent work on syncing etc, are there cases where we would want the appservices components to hit the network when we don't have GeckoView up and running and ready to perform the network requests? (Say, for syncing in a background task?)

**Comment by rfk** [comment]
Nominating this for April milestone, since we've received pretty clear instructions to consider it a blocker for beta.

**Comment by thomcc** [comment]
This is basically what we'll need to do.

1. We need to define a Kotlin interface/interfaces that mimics the set of types exposed by https://github.com/mozilla-mobile/android-components/tree/master/components/concept/fetch
2. We need to provide a Rust shared HTTP abstraction and replace all network usage we do with it.
3. We need to provide Kotlin FFI code that can be passed an instance of the interface from 1, and expose it to Rust.
4. We need to provide Rust FFI bindings for step 3, and make it implement the rust abstraction in step 2.
5. We need to change all networking code in our crates to use 4 on Android
    - Only in the megazords which can provide us with this via geckoview, e.g. not in the non-megazord variants (it fundamentally cannot work there) and not in the lockbox megazord.
    - Worth noting: getting this to work right given the limitations of cargo `feature` is going to be really tricky.
6. We need to provide an implementation of the Rust abstraction from 2 on platforms other than Android, or android users who don't have geckoview.
7. In A-C, we need to provide an implementation of our interface from step 1. which is backed by their fetch implementation, and allow it to get passed in to our library as described in step 3.


You'll notice that this is... actually several layers of HTTP abstractions.

**Comment by rfk** [comment]
> We need to provide an implementation of the Rust abstraction from 2 on platforms other than
> Android, or android users who don't have geckoview.

Let's continue to use `reqwest` for this in the first instance.

**Comment by thomcc** [comment]
> > We need to provide an implementation of the Rust abstraction from 2 on platforms other than
> > Android, or android users who don't have geckoview.
> 
> Let's continue to use `reqwest` for this in the first instance.

Right, I meant that we'd to wrap reqwest to match the abstraction.

**Comment by rfk** [comment]
Random thought, I wonder if this will prevent us from using `rust-hawk` or if it's generic enough to work with our new abstraction.

**Comment by thomcc** [comment]
Rust-hawk doesn't make requests directly, just produces a header for us. It doesn't depend on the rust network stack, only on some crypto components for hashing/mac and nonce generation
