### ISSUE TITLE
Lint errors should not prevent cutting a release on taskcluster.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3480]
CircleCI does the right thing here, and I believe Taskcluster used to as well. When cherry-picking things for hotfixes, it's okay if we don't fix warnings only present in newer versions of Rust (given that it's a cherry-pick, we can be reasonably confident that when the commits landed originally there were no lint errors).

I took a peek and didn't see an immediately obvious fix for this, so I'm just going to cut a v61.0.12 with the lint fixes cherry-picked in for now, but this will likely be a footgun at some point in the future if we don't fix it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1634)
┆Sprint: SYNC - end 2020-08-28

**Comment by tarikeshaq** [comment]
This makes me wonder if we should (if possible) fix the versions for the linters, and update them ourselves. We would need some way of ensuring we actually do update them though
