### ISSUE TITLE
Delete `master` branch

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3487]
We've been on `main` for a while, and it's easy to accidentally let muscle memory take over in the CLI and `git checkout master`, or to use a stale link to master branch that's still in your browser history. Getting an error (as we would if we delete the branch) would make it more obvious it's the wrong branch.

That said, marking as discuss since people should have some warning and such.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1636)
┆Sprint: SYNC - end 2020-08-28

**Comment by rfk** [comment]
Doing something close to this over in https://github.com/mozilla/application-services/pull/3509
