### ISSUE TITLE
Audit and support `targeting` fields of the Nimbus Schema

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3494]
Related to [https://jira.mozilla.com/projects/EXP/issues/EXP-32](https://jira.mozilla.com/projects/EXP/issues/EXP-32)

The schemas has a filter expression that needs to be supported in some ways. There should be some prior art for this. Need to check with the Glean / Nimbus teams before we proceed with one.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1659)
┆Story Points: 3
┆Epic: Nimbus Fenix Client SDK
┆Sprint: SYNC - end 2020-08-28

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

Since this relates directly to what application attributes we are looking at, see my comment in SYNC-1535 ( https://jira.mozilla.com/browse/SYNC-1535?focusedCommentId=152203&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-152203 ) for the fields/attributes that we should look at for initial targeting purposes.

**Comment by rfk** [comment]
As part of the "Audit" aspect of this, I'd like us to explicitly audit whether the targeting fields are included in the resulting telemetry pings (so that in analysis, we can check whether the users we're actually seeing in the experiment match the intended targeting).
