### ISSUE TITLE
Exclude download, redirects, reload, embed and framed link visit types from the get_top_frecent_site_infos query

### ISSUE THREAD

**Issue by gabrielluong** [mozilla/application-services#3503]
In implementing top frecent sites for Fenix https://github.com/mozilla-mobile/fenix/issues/10342 and https://github.com/mozilla-mobile/android-components/issues/7978, we encountered cases where we would get redirects as part of the results from `get_top_frecent_site_infos` https://github.com/mozilla/application-services/blob/673e700194cfa44ad3c8629f74a2b01844cea7c3/components/places/src/storage/history.rs#L1197

In order to avoid that, we can add a `exclude_types` similar to `get_visit_infos` in
https://github.com/mozilla/application-services/blob/673e700194cfa44ad3c8629f74a2b01844cea7c3/components/places/src/storage/history.rs#L1218

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1671)
┆Sprint: Backlog

**Comment by mhammond** [comment]
Do we really need it as a param? I don't really object to it being a param, but I can't see a use-case for the value of that param ever changing, and we could consider adding it as a param once we find the first use-case for needing it to be specified?

**Comment by gabrielluong** [comment]
> Do we really need it as a param? I don't really object to it being a param, but I can't see a use-case for the value of that param ever changing, and we could consider adding it as a param once we find the first use-case for needing it to be specified?

I think that sounds reasonable to hard code the exclusion type into the query. Right now, we're looking at the visited pages that are listed in the "History" screen in Fenix. This is the current exclusion types we're looking to pass in 
https://github.com/mozilla-mobile/fenix/blob/8d1bd10e6b00d270cfde13719fa91a8d8f6da7a3/app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt#L36.
