### ISSUE TITLE
sync status and change counter should be updated for reconciled bookmarks

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#3504]
It appears that [bug 1635859](https://bugzilla.mozilla.org/show_bug.cgi?id=1635859) also exists [here](https://github.com/mozilla/application-services/blob/cf46d7bdbf581ed84c8b646aaf7fab49454b9fab/components/places/src/bookmark_sync/engine.rs#L507)

* that `ON CONFLICT` clause should adjust `syncStatus`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1672)
┆Epic: a-s storage components (backlog)
┆Sprint: SYNC - 2021-04-16

**Comment by lougeniaC64** [comment]
@mhammond I'm going to add the on the `onboarding` label to this bug. So for clarity, should `syncStatus` be set to 2 or [Normal](https://github.com/mozilla/application-services/blob/4acf6b0cc05de18aa37ea9d519b671df4a7f334e/components/places/src/types.rs#L187) and `syncChangeCounter` be incremented by 1?

**Comment by mhammond** [comment]
I think my comment above was wrong re `syncChangeCounter` - the important thing is `syncStatus` set to `Normal` in that conflict clause.

**Comment by lougeniaC64** [comment]
@mhammond Actually I think this bug has been completed . . . [by you no less](https://github.com/mozilla/application-services/blame/cf46d7bdbf581ed84c8b646aaf7fab49454b9fab/components/places/src/bookmark_sync/engine.rs#L512) 😂. The filename change from `store.rs` to `engine.rs` hid that from me. Either way, I'm going to close this bug.
