### ISSUE TITLE
Add Incoming Sync Functionality to Forms

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#3524]
Add the incoming logic (staging and merging remote records) to Forms. The setup will be similar to [webext-storage](https://github.com/mozilla/application-services/tree/main/components/webext-storage/src/sync) (minus the bridge) with parity with [syncing on Desktop](https://searchfox.org/mozilla-central/source/browser/extensions/formautofill/FormAutofillSync.jsm).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1692)
┆Story Points: 8
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-02-26

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Implementing the FFI layer is a higher priority for the Android Components team than implementing sync, so I'm moving this ticket to the backlog.
