### ISSUE TITLE
Decide when we report experiment enrollment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3545]
This is one of the questions in the MANA doc.

Two proposed ideas:

* Report enrollment when the library is initialized 
* Report enrollment during the first call of the experiment branch

After we decide on this we should file a follow up bug to implement this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1713)
┆Story Points: 3
┆Epic: Nimbus Fenix Client SDK
┆Sprint: SYNC - end 2020-09-25

**Comment by rfk** [comment]
Possibly super-naive question, but, what would it look like if we tried to report both? (one of them would need a name other than "enrollment"..."elligibility" maybe?)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

The more I think about this, the more I think we should emit events for both. The broader set of events would be emitted as clients discover new experiments and process the targetting information therein, and help us validate that deployment and targeting are working correctly. The narrower set of events would be emitted when we hit code that actually wants to branch on the experiment variant, and would let us identify the subset of eligible users who actually participated in the experiment.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

It's not clear to me from the description in this bug, but are we expected to copy the same structure as the existing Normandy enrollment events documented here:

  * https://firefox-source-docs.mozilla.org/toolkit/components/normandy/normandy/data-collection.html#enrollment ( https://firefox-source-docs.mozilla.org/toolkit/components/normandy/normandy/data-collection.html#enrollment )

They seem to have a few details (like unique enrollment id) that I'm not sure are needed for the more limited nimbus use-case.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

I think the right thing to do here is:

  1. Send an enrollment event that includes the experiment slug, branch slug, and a unique enrollmentId (which should be a UUID generated and persisted and cached with the experiment definition). It's useful for diagnosing problems and could be useful later for reporting on previously enrolled experiments.
  2. Send an activation event when some code calls activateExperiment that includes the same information.

I don't think we need to include a type like Normandy / ExperimentManager on Desktop do, but i'll confirm this with tdsmith and marissa on Monday.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Documented here https://docs.google.com/document/d/1IGoq9eXG36TdsWEMYCdHjAedq-f7yDAQp788tkanitc/edit#heading=h.3wye5dmeb104 ( https://docs.google.com/document/d/1IGoq9eXG36TdsWEMYCdHjAedq-f7yDAQp788tkanitc/edit#heading=h.3wye5dmeb104 ) and added to the Nimbus Engineering Mana page

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Thank you! Since this bug is about deciding what to do, I'm going to call it resolved by the above-linked google doc. I've filed SYNC-1802 and SYNC-1803 for implementation of the two types of event.
