### ISSUE TITLE
Respond to "Build A-S and Glean as single binary"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3551]
Discussion happening in:

[https://bugzilla.mozilla.org/show_bug.cgi?id=1661539](https://bugzilla.mozilla.org/show_bug.cgi?id=1661539)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1734)
┆Story Points: 3
┆Sprint: SYNC - end 2020-09-11

**Comment by eoger** [comment]
There's a PR happening in https://github.com/mozilla/application-services/pull/3554.
