### ISSUE TITLE
Cut a new release with glean in the iOS megazord

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3564]
So that firefox-ios can get the changes from https://github.com/mozilla/application-services/pull/3554

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1757)
┆Story Points: 3
┆Sprint: SYNC - end 2020-09-11

**Comment by mhammond** [comment]
And also so Fenix can get #3537
