### ISSUE TITLE
firefox fenix nightly - bookmarks not syncing

### ISSUE THREAD

**Issue by axcadsd** [mozilla/application-services#3566]
`sync_manager::manager: engine "bookmarks" status: Err(Error(Store error: Error executing SQL: FOREIGN KEY constraint failed))`

[log.txt](https://github.com/mozilla/application-services/files/5199254/log.txt)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1758)
┆Sprint: SYNC - end 2020-09-11

**Comment by mhammond** [comment]
Ouch. That literally all the info that we log here which isn't too helpful. I'm not sure what I can recommend to get your going again - there's even a chance that reinstalling the app would still cause the same problem (although that would be very useful to know). If you have a desktop Firefox, it would also be interesting to know if the [about:sync](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) addon reported any validation errors.

**Comment by axcadsd** [comment]
@mhammond 

I don't see any errors through about:sync in desktop firefox.

> there's even a chance that reinstalling the app would still cause the same problem
  
Actually, this is the 2nd time I am having this problem. First time I got this issue, I cleared the data of the app, and it started working again. It worked for a few weeks, and then I got this problem again. I don't want to keep resetting the app, so hopefully the bug can be fixed.

**Comment by mhammond** [comment]
So the log has
> 09-09 21:51:35.234 28927 28987 D places::bookmark_sync::store: Flag frecencies for removed bookmark URLs as stale
> 09-09 21:51:35.237 28927 28987 D places::bookmark_sync::store: merge completed

The second line logs on error, so the problem must be [here](https://github.com/mozilla/application-services/blob/5046deba02fbb6f920d433957fa3d539cb32f7f6/components/places/src/bookmark_sync/store.rs#L340-L360) - now to try and work out *why* :)

**Comment by linacambridge** [comment]
Oooh, nice catch, @mhammond! I have a (totally untested, happened to see your GitHub email just before signing off for the night 😴) theory: is that query missing a `WHERE b.fk NOT NULL` clause? Could we be trying to insert a row into `moz_places_stale_frecencies` for something that isn’t a bookmark with a URL (like if we’re applying an incoming tombstone for a folder or a separator), and then choking because of [this constraint](https://github.com/mozilla/application-services/blob/5046deba02fbb6f920d433957fa3d539cb32f7f6/components/places/sql/create_shared_schema.sql#L56-L57)?

**Comment by mhammond** [comment]
right - or something we declined to bookmark for whatever reason! I'll see if I can get a test to repro

**Comment by mhammond** [comment]
> or something we declined to bookmark

I meant "declined to apply", but even that would be wrong, as then it would be flagged as a local deletion.

We also seem to have approx zero tombstomb tests

But as usual, lina was right on the money :)

**Comment by mhammond** [comment]
This was closed prematurely, but I'll leave it closed as #3567 will merge in the next hour or 2 and than it *will* be fixed :)
