### ISSUE TITLE
Update SDK to work with latest uniffi

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3583]
Had to rollback uniffi here: [https://github.com/mozilla/nimbus-sdk/pull/22](https://github.com/mozilla/nimbus-sdk/pull/22) due to RustBuffer changes

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1776)
┆Story Points: 3
┆Epic: Nimbus Fenix Client SDK
┆Sprint: SYNC - end 2020-10-08

**Comment by rfk** [comment]
Hrm, the changes there all look like they should be internal details of uniffi, I wonder if this was an issue with some out-of-date generated files. Is there some build caching or similar that might have caused issues in CircleCI here?

**Comment by rfk** [comment]
Oooh, I see, Circle is globally installing from github but the crate [depends on the version from crates.io](https://github.com/mozilla/nimbus-sdk/blob/23d929094abee5dce67d39a6502e4f5dbd18a228/experiments/Cargo.toml#L35). We should update the CircleCI config to also install the published version from crates.io.

**Comment by rfk** [comment]
This was fixed by https://github.com/mozilla/nimbus-sdk/pull/23
