### ISSUE TITLE
Unblock running unit tests for Nimbus Android component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3584]
Travis is blocked by issues with the current SDK setup where one cannot run unit tests on dev platforms. See https://github.com/mozilla/nimbus-sdk/pull/20

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1777)
┆Story Points: 5
┆Epic: Nimbus Fenix Client SDK
┆Sprint: SYNC - end 2020-09-25

**Comment by rfk** [comment]
Ref https://github.com/travis79/nimbus-sdk/pull/1 for a bit of additional progress
