### ISSUE TITLE
Investigate caching the profile data

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#36]
I'm still debating if it should live in the Rust crate or if it is the responsibility of the host app to do it. Thoughts?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-78)
┆Story Points: 8
┆Sprint: SYNC - 2019-07-19

**Comment by thomcc** [comment]
If it's an in-memory cache it should be in the rust app IMO. Don't force all users to implement a cache on their own.

**Comment by eoger** [comment]
Yes, I agree that the rust crate should maintain an in-memory cache and do some eTag magic with the server.
I'm still torn whether we should handle a persistent profile cache (e.g. Firefox Desktop has one so we can show the user's avatar/name ASAP) or let the app do it.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

dup of the other thing with `getProfile`
