### ISSUE TITLE
Update to JNA 5.5.0?

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#3617]
I'm currently trying to update AC and Fenix to Kotlin 1.4.10 and the latest Android Gradle plugin. Due to a dependency resolution error I noticed that the Kotlin Coroutines package depends on JNA 5.5.0 while we use 5.2.0 in Application Services and Glean. Explicitly using 5.5.0 in Fenix resolves the issue, but I wonder if using 5.5.0 has other side effects and whether we would want to make this change in the Application Services and Glean repositories?

```
+--- org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.9
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.9
|    |    +--- net.java.dev.jna:jna:5.5.0
|    |    +--- net.java.dev.jna:jna-platform:5.5.0
|    |    |    \--- net.java.dev.jna:jna:5.5.0
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1819)
┆Sprint: SYNC - end 2020-10-10

**Comment by eoger** [comment]
I skimmed through the JNA changelog and don't see any reason for us not to upgrade, I'll make a PR.
