### ISSUE TITLE
Configure the Sync Manager for Forms

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3631]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1828)
┆Story Points: 8
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-04-09

**Comment by rfk** [comment]
Just kind of wondering aloud here...I believe the SyncManager is one of least least-well-tested components, it may be worth thinking about whether there are incremental improvements we want to make on that front while we're in there adding a new datatype.
