### ISSUE TITLE
Update rusqlite to 0.24.1 and (including vendored version in mozilla-central)

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#3632]
Apparently one of rusqlite's dependencies causes crashes if you build Firefox with nightly Rust:

- https://github.com/rust-lang/rust/issues/77585
- https://github.com/rusqlite/rusqlite/issues/810
- https://bugzilla.mozilla.org/show_bug.cgi?id=1669722

I released v0.24.1 which avoids this dependency entirely: https://github.com/rusqlite/rusqlite/releases/tag/v0.24.1

It would be nice if someone updated rusqlite in m-c with this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1829)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-10-23

**Comment by mhammond** [comment]
Thanks heaps for this Thom - I think it's done (assuming that bugzilla patch sticks)
