### ISSUE TITLE
Specify the frecency threshold for fetching the top frecent sites

### ISSUE THREAD

**Issue by gabrielluong** [mozilla/application-services#3635]
In https://github.com/mozilla-mobile/fenix/issues/14302, we are looking at following iOS and Desktop's frecency threshold to determine which visited sites should be displayed as a visited top site (autogenerated). Currently, we don't expose frecency despite fetching it in the query:
https://github.com/mozilla/application-services/blob/66279818f65aa4398f3c57bd8d40b270f5ed0db4/components/places/src/storage/history.rs#L1211
https://github.com/mozilla/application-services/blob/673e700194cfa44ad3c8629f74a2b01844cea7c3/components/places/src/places_msg_types.proto#L200

This issue is to return the frecency value in the TopFrecentSiteInfo so that AC/Fenix can filter the returned top sites by a given frecency threshold.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1830)
┆Story Points: 5
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by mhammond** [comment]
One concern we've historically had with this is that the value for frecency isn't meaningful as an absolute value - it's only meaningful in its relationship to other values. It also means it will be much trickier to adjust the implementation (eg, see #610) How will you determine what frecency threshold to use? What will you do when there are too few or too many sites for a specific value?

IOW, I'm wondering if there is a better way to implement this than exposing an arbitrary value that we'd prefer to keep as an implementation detail?

**Comment by gabrielluong** [comment]
> One concern we've historically had with this is that the value for frecency isn't meaningful as an absolute value - it's only meaningful in its relationship to other values. It also means it will be much trickier to adjust the implementation (eg, see #610) How will you determine what frecency threshold to use? What will you do when there are too few or too many sites for a specific value?
> 

Ed (mardak) pointed me to the desktop threshold https://searchfox.org/mozilla-central/rev/919607a3610222099fbfb0113c98b77888ebcbfb/browser/components/newtab/lib/TopSitesFeed.jsm#79 with an added note: frecency of a typed in url gets a frecency score of… 2000 vs a link visit gets frecency score of 100 

I am still investigating what iOS is doing, but right now if Fenix wanted to conform to desktop. We would simply expose the frecency score and use the same threshold.

**Comment by gabrielluong** [comment]
Right now, our issue in Fenix is that any visited site is automatically considered a visited top site.

**Comment by gabrielluong** [comment]
I would be open to longer term options. I think the short term plan for Fenix that was conveyed to me was to emulate the iOS and desktop behaviour.

**Comment by eoger** [comment]
We could also keep the threshold/cut mechanism in the Rust layer so we don't leak the frequency values.

**Comment by gabrielluong** [comment]
> We could also keep the threshold/cut mechanism in the Rust layer so we don't leak the frequency values.

I am still digging around to see what everyone does. Right now, it might be easiest to expose it and let individual consumers decide the threshold and tweak it as appropriate since we're also offering this as a AC component feature (although that might be rare).

**Comment by mhammond** [comment]
Yeah, I actually think checking just the frecency is going to be wrong whoever does it TBH (maybe a threshold of visit counts would be better, with frecency just used for ordering?) but that's a bigger discussion, and it's hard to argue too hard against this given how desktop etc work, so 🤷‍♂️
