### ISSUE TITLE
Collect Form Sync Metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3676]
Collect metrics to submit to Glean (similar to sync ping).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1864)
┆Story Points: 8
┆Epic: a-s storage components (backlog)
┆Sprint: Backlog

**Comment by lougeniaC64** [comment]
This ticket is superseded by [this fenix ticket](https://github.com/mozilla-mobile/fenix/issues/18711).
