### ISSUE TITLE
邮箱设置正常，但账户验证时提示邮件被退回

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3685]
Created attachment 9184148
1603852210(1).png

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

Steps to reproduce:

登录Firefox账户，或者添加第二邮箱时，需要通过邮箱接受验证码。

Actual results:

web界面上提示邮件被退回，导致无法验证。此前能正常接收邮箱，并且已检查确保<accounts@firefox.com> 添加到通讯录。

Expected results:

向账户邮箱发送验证码

- - -
:beetle: Issue is synchronized with Bugzilla [Bug 1673783](https://bugzilla.mozilla.org/show_bug.cgi?id=1673783)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1871)
┆Sprint: Backlog

**Comment by eoger** [comment]
Fixed on bugzilla
