### ISSUE TITLE
Send tab to device not working

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3686]
I was trying to send [this page](https://www.reddit.com/r/shortcuts/comments/iwxqjt/shortcut_to_change_your_home_wallpaper_during_the/)

1. On my desktop from the URL bar I picked "..." 
1. then I picked "send tab to device" 
1. then the name of the device I wanted to send.
1. a little blue "sent" message appeared
1. I opened Firefox on my iPhone and did not see the tab.
1. I checked I was logged into my Firefox account on my phone and tapped the little refresh icon next to my email address in that menu, no change
1. I left Firefox iOS open on my phone and the screen on
1. I returned to my desktop and picked "send tab to device" and this time I picked "send to all devices" 
1. a little blue "sent" message appeared
1. Firefox iOS remained unchanged.
1. opened Firefox iOS on my iPad and also did not see the tab there

I don't know what I'm supposed to see? But I had 5 tabs open before this and the same 5 tabs open after this. I did not get any pop up notifications.

- - -
:beetle: Issue is synchronized with Bugzilla [Bug 1675079](https://bugzilla.mozilla.org/show_bug.cgi?id=1675079)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1870)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by eoger** [comment]
Fixed on bugzilla

**Comment by data-sync-user** [comment]
➤ App Services commented:

Upstream bug has been closed with the following resolution: DUPLICATE.
