### ISSUE TITLE
Protobuf decode error: failed to decode Protobuf message: PasswordInfo.times_used: invalid wire type: StartGroup (expected Varint)

### ISSUE THREAD

**Issue by ekager** [mozilla/application-services#3709]
Originally filed as https://github.com/mozilla-mobile/fenix/issues/13253

Crash report: [Socorro](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=mozilla.appservices.logins.LoginsStorageException%3A%20at%20mozilla.appservices.logins.rust.RustError.intoException%28RustError.kt%3A4%29&date=%3E%3D2020-07-28T11%3A58%3A00.000Z&date=%3C2020-11-09T11%3A58%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1)

This is one of our top Beta crashers, and from the looks of the Fenix ticket, happens possibly on update/fresh install, but inconsistently.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1891)
┆Epic: Sync Ecosystem (backlog)
┆Sprint: Backlog

**Comment by rfk** [comment]
> This is one of our top Beta crashers,

Is this new on Beta? (IOW, might be explained by a change in appservices library version?)

Some notes from brief click around:

* The error being thrown is a generic `LoginsStorageException`; could be a rust panic, or could be an error to which we haven't assigned a specific error code.
* The crash is coming from a variety of different methods, e.g. `add` and `update` and `potentialDupesIgnoringUsername`.
    * These all seem to be methods that take a `Login` struct as argument, meaning they decode an incoming protobuf message; I wonder if this could be the rust-side equivalent of the "zero length buffer" errors we've seen occasionally when decoding protobuf messages on the java side.
* I'm surprised we don't see these errors in [our logins dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-logins-and-places-performance-metrics?p_org_mozilla_fenix=org_mozilla_firefox_beta) and I wonder if that indicates a problem with the dashboard.

**Comment by ekager** [comment]
> Is this new on Beta?

Don't think so, looking at a longer window of time, seems to be a few hundred crashes in every release build

**Comment by mhammond** [comment]
Ryan and I had a bit of a chat in slack and noted:

* Our dashboards do show some errors - not quite as many as we'd expect, but still some.
* They also shown an `__other__` error that's happening *far* more frequently, which confuses us - we (a) can't see where they might come from in our code and (b) don't understand why they aren't showing up in socorro in some way as a much bigger problem than this one.
* Many rust errors end up with this catch-all `LoginsStorageError` - eg, corrupt sql databases, even invalid URLs (there was recently a bug where a user could type an invalid URL and hit the bookmark "star" and we'd crash! I wonder if something like that might be going on?)

Regardless, the one "easy" actionable thing we can do here in the short term is to expand the error types. Every [`ErrorKind`](https://github.com/mozilla/application-services/blob/2a10d289d01481fcc5cc40c737d28ccc62aec161/components/logins/src/error.rs#L14) should have its own [kotlin exception](https://github.com/mozilla/application-services/blob/2a10d289d01481fcc5cc40c737d28ccc62aec161/components/logins/android/src/main/java/mozilla/appservices/logins/LoginsStorageException.kt#L8), and panics should get their own special one too. Then hopefully the error reports would end up with a more specific error and offer some clues.

**Comment by grigoryk** [comment]
I just [filed this in a-c](https://github.com/mozilla-mobile/android-components/issues/9400), and then found this thread.

A bit more detail from the exception: `Protobuf decode error: failed to decode Protobuf message: PasswordInfo.times_used: invalid wire type: StartGroup (expected Varint) ` ( see https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8814203/?query=is%3Aunresolved%20RustErrorException )

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

no needed, we're uniffing
