### ISSUE TITLE
Decide an approach for emitting SDK events via Kotlin

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3723]
As noted in SDK-69, the Glean Rust bindings are not yet ready for our use, so we will instead need to emit SDK metrics events via the Kotlin wrapper. This issue is specifically to track the work of deciding on an approach, the actual adding of the events will be tracked in individual tickets.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1903)
┆Story Points: 3
┆Epic: Fenix Client SDK
┆Sprint: SYNC - end 2020-11-20

**Comment by rfk** [comment]
We've decided we're going to have `updateExperiments` return a list of the changes to experiment state and enrollment, and have the Kotlin wrapper walk that diff and emit appropriate metrics events. Ref https://jira.mozilla.com/browse/SDK-122 for implementation.
