### ISSUE TITLE
Need a new release of FxAClient

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#375]
We need to tag a new release for https://github.com/mozilla/application-services/commit/ac3be29e6b6731100c5684c57c9039c9aa53f144

Should the new release be 0.8.2 or 0.9.0 I see some changes in the commit history that might change the semver level. @ncalexan @mhammond ?

**Comment by ncalexan** [comment]
When in doubt, major bump, so 0.9.0.

All of our consumers should be pinning at this point anyway.

**Comment by vladikoff** [comment]
This was done!
