### ISSUE TITLE
Audit old bug tree for "fxa-client in desktop"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3754]
Over in https://jira.mozilla.com/browse/SYNC-1119 we have an old bug tree from our (indefinitely paused) attempt to replace the current Desktop FxA implementation with the fxa-client rust component. We should go through the bugs there and see which are still valuable and which can be closed. I think many of them are "execution milestone" type bugs which aren't useful to keep, and there's value in removing them to reduce future confusion for someone who takes a fresh go at this project.

[~eoger@mozilla.com] what do you think, worthwhile?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1937)
┆Epic: Sync Maintainability Focus
┆Sprint: Backlog

**Comment by mhammond** [comment]
Given our forthcoming resource changes, is it worth considering officially abandoning that project and removing it from desktop? It may be that when the time comes to revisit it, a uniffi-based (or some other approach entirely) might make more sense?

(I'm not necessarily advocating for it, but it's worth explicitly calling it out as an option)

**Comment by rfk** [comment]
Right, yes, @eoger and I chatted a little bit about that as well in a recent sync-up. I'm lightly in favour of removing the punt-based code in Desktop since I don't think we'll pursue that approach for other components.

**Comment by eoger** [comment]
Yes, let's kill the bug tree, I'll do it.
