### ISSUE TITLE
Remove FxA Punt from Desktop

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3756]
It's in services/fxaccounts/rust-bridge and RustFxAccounts.jsm. We should keep viaduct as it'll be used by nimbus.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1940)
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Tarik did this when removing fxa-client
