### ISSUE TITLE
Migrate fxa-pairing-channel to the fxa monorepo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3760]
The core communication protocol for the FxA pairing flow is currently implemented in a standalone repository at [https://github.com/mozilla/fxa-pairing-channel](https://github.com/mozilla/fxa-pairing-channel), from where it is imported both by fxa-content-server and the FxA desktop client code.

We should migrate this into the FxA monorepo at [https://github.com/mozilla/fxa](https://github.com/mozilla/fxa) so that it can be more easily maintained by the FxA team especially with respect to keeping dependencies up-to-date.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1945)
┆Story Points: 3
┆Epic: Sync Maintainability Focus
┆Sprint: SYNC - 2021-03-12

**Comment by rfk** [comment]
Looks like fxa-pairing-channel uses a different test runner than the rest of FxA ("karma", which executes the tests in an instrumented browser). Not sure how much of a problem that'll be, or whether we might be able to migrate away from it.

**Comment by rfk** [comment]
In discussion with the FxA team, we decided not to move this into the monorepo, it's kind of weird and different enough to other FxA things that it will be more annoying than valuable. Instead, I have kicked off a series of PRs to try to bring the repo up to a good maintainable state, and will work with the FxA team to get them reviewed and hopefully fold the fxa-pairing-channel repo into their regular triage:

* https://github.com/mozilla/fxa-pairing-channel/pull/54
* https://github.com/mozilla/fxa-pairing-channel/pull/55
* https://github.com/mozilla/fxa-pairing-channel/pull/56
* https://github.com/mozilla/fxa-pairing-channel/pull/57

I'm going to close the tracking issue here in favour of those PRs.
