### ISSUE TITLE
Review use of personal API tokens in build/deploy pipeline

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3771]
According to our [build pipeline docs](https://github.com/mozilla/application-services/blob/main/docs/build-and-publish-pipeline.md) we have at least two API access tokens that are currently tied to a personal account. Let's review whether that's still the case and what our path forward is if so. /cc @eoger

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1961)
┆Sprint: SYNC - end 2020-12-18

**Comment by eoger** [comment]
@MihaiTabara I believe [this secret](https://github.com/mozilla/application-services/blob/3fc42b212b12493e4113ed787cfa985b0b269a24/taskcluster/ci/module-build/kind.yml#L53-L61) is currently linked to my personal LDAP account (should finish with `6c`).
How would we proceed to update it to another token generated by @mhammond or @lougeniaC64? Or even better, a non-personal account?

**Comment by MihaiTabara** [comment]
I confirm the secret matches the suffix you mentioned.

I think given the short-term, we should probably move it to another LDAP account and find a automated-solution after the holidays? We would need a fake LDAP account in Socorro to be able to chain it to a non-employee account. Or maybe Soccorro team has another solution for things like this. So reading https://github.com/mozilla/application-services/blob/main/docs/build-and-publish-pipeline.md, specifically:
```
TaskCluster uploads symbols to Socorro.
    The access token for this is currently tied to @eoger's LDAP account.
```
I think it's just a matter of someone else from your team (who supposedly is having the same permissions as you in LDAP in terms of flags) generating another token that we can ingest in Taskcluster. I'm not too familiar with Socorro, but reading https://socorro.readthedocs.io/en/latest/localdevenvironment.html?highlight=token#adding-an-api-token I think it's just a matter of one of @mhammond or @lougeniaC64 hopping on https://crash-stats.mozilla.org/api/tokens/ and generate another token. Then updating the Taskcluster secret with that value. If they don't have enough permissions to access it, they can [wormhole](https://magic-wormhole.readthedocs.io/en/latest/welcome.html#example) it to me and I can update it. Or I can look into ways to grant them access to that secret 👍

**Comment by eoger** [comment]
Thanks Mihai, one correction: I got my token at https://symbols.mozilla.org/tokens
I'll let Mark or Lougenia coordinate with you to change the token.

**Comment by lougeniaC64** [comment]
@MihaiTabara I've generated a token that can be used however I don't think I have the rights to update the secret in TaskCluster. However, I can wormhole it to you whenever you like.

**Comment by MihaiTabara** [comment]
@lougeniaC64 just completed the transferred and I updated the [secret](https://firefox-ci-tc.services.mozilla.com/secrets/project%2Fapplication-services%2Fsymbols-token). All good here, it should just be picked by the next build. If it fails, we may need to force a all-change to rebuild the toolchain to ensure we invalidate the cache. But let's see how it goes without that first.
