### ISSUE TITLE
Add Incoming Sync Functionality for Credit Cards to Forms

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#3772]
Similar to #3524 

Add the incoming logic (staging and merging remote records) for Credit Cards to Forms. The setup will be similar to [webext-storage](https://github.com/mozilla/application-services/tree/main/components/webext-storage/src/sync) (minus the bridge) with parity with [syncing on Desktop](https://searchfox.org/mozilla-central/source/browser/extensions/formautofill/FormAutofillSync.jsm).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1957)
┆Story Points: 3
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-01-29

**Comment by jdragojevic** [comment]
Done as part of autofill work.  Looks like the link got broken.
