### ISSUE TITLE
firefox-ios uses a fork of a-s

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3777]
I've noticed that firefox-ios uses a release coming from a fork of a-s. @nbhasin2 do we know what's blocking Firefox iOS from using the upstream version of a-s?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1964)
┆Sprint: Backlog

**Comment by nbhasin2** [comment]
@eoger From what I recall there was a bug with History not showing up when I added one of the latest versions of A~S which led us to use a fork. I haven't tried v67.2.0 version of A~S though.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

This is resolved.
