### ISSUE TITLE
[automation] Publish generated Java/Kotlin documentation

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#378]
We would like to generate Java/Kotlin documentation for the a-s components, just like the Android Components team generates for the a-c components.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-717)

**Comment by rfk** [comment]
I think it's pretty clear we're not going to get back to this anytime soon, and it's easy to bring back if/when we do; purging from the backlog.
