### ISSUE TITLE
Extend cleaning up origin temp tables work to also singularly deleted bookmarks/history items

### ISSUE THREAD

**Issue by ekager** [mozilla/application-services#3784]
Previously work was done in #2693 to clean up origins on delete all but Fenix users are still seeing this behavior after singularly deleting bookmarks or history see: https://github.com/mozilla-mobile/fenix/issues/14782 and https://github.com/mozilla-mobile/fenix/issues/16157

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2589)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866333

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
