### ISSUE TITLE
Investigate erratic bookmark sync success rate on nightly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3827]
Investigate (and hopefully identify the source of) the irregularities in the bookmark sync success rate on nightly https://sql.telemetry.mozilla.org/queries/71638#179848

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2596)

**Comment by mhammond** [comment]
this seems much improved.
