### ISSUE TITLE
Coverage reports broken due to nightly bustage in a dependency

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3851]
Our coverage reports use ~`cargo-tarpaulin`~ `grcov`, which means they have to run on Nightly Rust. Nightly Rust recently [stabilized the `::BITS` associated constant on integer types](https://github.com/rust-lang/rust/issues/76904). One of our downstream dependencies had a conflicting trait implementation that also defined a `::BITS` constant, so now that dependency [fails to build on Nightly Rust](https://github.com/Alexhuszagh/rust-lexical/issues/55) and our [coverage reports don't run](https://app.circleci.com/pipelines/github/mozilla/application-services/24021/workflows/5abd928a-991e-4916-a07f-f595b2b1eaeb/jobs/93696).

I don't think there's much we can do here apart from wait for an updated release of [lexical-core](https://crates.io/crates/lexical-core), but I wanted to put it on file for completeness.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2032)
┆Sprint: Backlog

**Comment by HTG-YT** [comment]
It also affected my project so I just cloned the repository, made the fixes and using the `[patch]` section in Cargo.toml to use the lexical-core on my computer with my fix instead of the one on crates.io which is broken.

**Comment by rfk** [comment]
Thanks @HTG-YT, and thanks for your work to track down the underlying cause here in the linked bugs!
