### ISSUE TITLE
Disable ci integration for bugzilla -> jira sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3856]
The bugzilla-jira project is planning to start the production integration by Feb 16th.  We'll want to coordinate turning off our existing ci workaround to avoid duplicate issues flowing in.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2040)
┆Story Points: 1
┆Epic: Sync Maintainability Focus
┆Sprint: SYNC - 2021-03-12

**Comment by rfk** [comment]
Adding a bit of technical context, the current sync process is [driven from CircleCI](https://github.com/mozilla/application-services/blob/9ffdf88cdb269bf6f6769be67802f85983ae8d97/.circleci/config.yml#L329) as a [scheduled job](https://github.com/mozilla/application-services/blob/9ffdf88cdb269bf6f6769be67802f85983ae8d97/.circleci/config.yml#L510). Disabling in practice means deleting the entries from the CircleCI config, optionally also deleting the [underlying python script](https://github.com/mozilla/application-services/blob/main/tools/sync_bugzilla_to_github.py), and maybe even deleting the [github repo that hosts the synced issues](https://github.com/mozilla/application-services-bug-mirror).

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

1. IT ticket to turn off Unito sync with the mirrored repository is filed
  2. https://github.com/mozilla/application-services/pull/3927 ( https://github.com/mozilla/application-services/pull/3927 ) - ready to merge as soon as Bugzilla-to-Jira is on.
