### ISSUE TITLE
Do not return over-scoped OAuth Access Tokens

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#386]
If `FirefoxAccount::get_oauth_token` gets called requesting the `a` scope and we currently hold a cached OAuth token with the `a`, `b` and `c` scopes, that OAuth token will be returned.
It is security problem as a malicious server endpoint requesting the `a` scope could use the sent token and call a legitimate API on another server requesting the `b` scope behind the back of the user.

I believe we can kill two birds with one stone by simply not storing access tokens internally (as described in https://github.com/mozilla/application-services/issues/40) and requesting only the scopes the API consumer asked for.

**Comment by rfk** [comment]
We could "cache" them but not "store" them, if that distinction is useful.  That is, if you request a token with scope "XYZ" and we recently generated a token with that exact scope, then we could return the existing one.  But we wouldn't need to persist them to disk for longer-term storage.
