### ISSUE TITLE
Upload local autofill records without mirror records on sync

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#3861]
At present, in the incoming sync logic, remote autofill records with corresponding local records and no sync records are not re-uploaded to the server. The work to complete this ticket would correct that by doing the following:

  - Update sync incoming logic so that local autofill records without mirror records are always uploaded
  - Remove the setting of the `sync_change_counter` during `reset` calls (this won't be necessary if always upload when the above change is made)
    - Leave a comment specifying why the `sync_change_counter` is unnecessary within the `reset` function
  - Find and remove any other additional places in the sync logic where we are setting the `sync_change_counter` to 1 in order to force uploads on the next sync
 
See [this conversation](https://github.com/mozilla/application-services/pull/3845#discussion_r571789878) for details

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2044)
┆Story Points: 5
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-02-26

**Comment by jdragojevic** [comment]
Looks like this was done as part of autofill work but not closed via sync.
