### ISSUE TITLE
autofill: better errors when no record is found?

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#3868]
If you query for an address or credit-card using a GUID that doesn't exist, you get back a `SqlError(QueryReturnedNoRows)` - I wonder if it is worth a specific error for this case? My thinking is that most `SqlError`s are not a result of inputs to the API, but this one is.

(If we decide the status-quo isn't ideal, we then should work out whether we should return null or create a new specific error type.

cc @lougeniaC64 , WDYT?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2053)
┆Epic: a-s storage components (backlog)
┆Sprint: SYNC - 2021-04-16

**Comment by lougeniaC64** [comment]
@mhammond While the current handling of records not being found may not be ideal, I'm not sure if we should throw a custom error or return an `Option` [as Logins does](https://github.com/mozilla/application-services/blob/main/components/logins/src/db.rs#L467).

**Comment by lougeniaC64** [comment]
This is what needs to be done to finish this ticket:

- Create a custom error type (something like [NoSuchRecord](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/logins/src/error.rs#L25) in logins) in [errors.rs](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/autofill/src/error.rs).

- Update the [get_address](https://github.com/mozilla/application-services/blob/main/components/autofill/src/db/addresses.rs#L90) and [get_credit_card](https://github.com/mozilla/application-services/blob/e26940e5098ef6ca1106fb22564bff7250ba9ebc/components/autofill/src/db/credit_cards.rs#L84) functions to throw the new custom error type when the sql query doesn't return a record (something like [this](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/logins/src/db.rs#L963)).

- Add tests to cover the case where these functions are called and no record is found to ensure the error is thrown. Tests can be found at the end of `credit_cards.rs` and `addresses.rs` files. Also ensure that these changes haven't broken any other autofill tests.

- Add the custom error created to the `Error` enum in the [autofill.udl file](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/autofill/src/autofill.udl#L83).

- Great success!!
