### ISSUE TITLE
Tweak the generated bindings for the autofill library

### ISSUE THREAD

**Issue by gabrielluong** [mozilla/application-services#3874]
In AC, we currently have to do the following:
```
// Set the name of the native library so that we use
// the appservices megazord for compiled code.
System.setProperty(
    "uniffi.component.autofill.libraryOverride",
    System.getProperty("mozilla.appservices.megazord.library", "megazord")
)
```
similar to https://github.com/mozilla-mobile/android-components/blob/ad90b10a294353e5f963b8659fe22ffcd8c9ae2e/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt#L215-L218 in order to find the appropriate uniffi_autofill library. See https://mozilla.slack.com/archives/CKL0LGV9B/p1613585308101300 for further discussions.

Since autofill will never be published outside of the megazord, we should preconfigure the generated bindings for the autofill library so that they're always looking for `libmegazord.so`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2061)
┆Story Points: 3
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-02-26

**Comment by rfk** [comment]
To add a bit of context, the default `.so` name is set by the uniffi tool here: 

* https://github.com/mozilla/uniffi-rs/blob/4d61601bd46a2ae48858ada425c429273833fa90/uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt#L2

@lougeniaC64 I'm wondering if the simplest approach here is for uniffi to grow a config option to override the details library name, and for the autofill crate to set that to be `libmegazord.so`. WDYT?

**Comment by mhammond** [comment]
Ryan's proposal sounds fine to me, but as a general question - if our position is that autofill will never be published outside of the megazord, then is it also true that *none* of our components will ever be published outside the megazord, and thus we should remove/deprecate this "override" capability everywhere?

**Comment by rfk** [comment]
Honestly, I've been procrastinating on trying to commit to an answer to that general question, in the hope that additional information will shake out of the better-builds/libxul/etc discussions. For example, it sounds like there's at least one situation in which we'll want to load it from `libxul.so` rather than `libmegazord.so`.

**Comment by mhammond** [comment]
> For example, it sounds like there's at least one situation in which we'll want to load it from `libxul.so` rather than `libmegazord.so`.

Right - but .kt isn't going to be in play there. I guess I'm wondering if there's an even *more* general solution - something like <handwave>allowing custom templates. 

>  in the hope that additional information will shake out of the better-builds/libxul/etc discussions

Maybe that's an argument for doing nothing here at the moment - now the underlying issue has been identified, I imagine a-c will set the system property as a short-term workaround so they aren't blocked, making this non-urgent (although I agree it's important)

**Comment by mhammond** [comment]
(lol - github tricked me again and removed by \<handwave\> tag in the above comment :)

**Comment by rfk** [comment]
> Right - but .kt isn't going to be in play there.

I could easily be getting confused about all the moving parts, but I was expecting that the Kotlin code for the a-c autofill wrapper would need to load the autofill Rust code from libxul.so, at least in the case where the consumer also depends on GeckoView.

**Comment by rfk** [comment]
It occurred to me that I'm going to have a similar problem very soon with my uniffication of the fxa-client component, so I went ahead and pitched a feature in uniffi to support this: https://github.com/mozilla/uniffi-rs/pull/389

**Comment by rfk** [comment]
I've cut a `v0.7.1` release of uniffi with the new `cdylib_name` config option, so I think the next step here is to add it into the `uniffi.toml` for the autofill component. [Here](https://github.com/mozilla/application-services/pull/3876/files#diff-8513fbafa4bcfcdc05f39a379569fd77223f37fe4c16d760e05ae8d46e847a2b) is how I did it for the work-in-progress fxa-client component, for reference.

**Comment by rfk** [comment]
I believe that this is done as of v72.0.0 of application-services, and the `libraryOverride` workaround should no longer be required.

**Comment by rfk** [comment]
(I should add, I am working on a PR to push the new appservices version into a-c, and plan to have it up by end of day today)
