### ISSUE TITLE
Staple app-services Rust toolchain to 1.50.0 (or 1.50?)

### ISSUE THREAD

**Issue by dmose** [mozilla/application-services#3893]
We had weird inconsistencies figuring out why linking webext_storage was failing for some people and not others, until we pinned it down to different compiler versions.  We'd like to start by pinning the toolchain to 1.50.0 or 1.50 (which is the version currently in use in mozilla-central nightly) using a `rust-toolchain` file.  Ideally, we'd update our pin as the m-c version changes, but we don't need to implement that now.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2077)
┆Story Points: 2
┆Epic: Rust Components Releases
┆Sprint: SYNC - 2021-03-12

**Comment by data-sync-user** [comment]
➤ Daniel Mosedale commented:

This will consist of a few PRs.  The first is to enable auto-fixing clippy issues, and doing so in preparation for building correctly with 1.50, is https://github.com/mozilla/application-services/pull/3895
