### ISSUE TITLE
OpenSSL dependencies list

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#39]
I believe that to simplify and shrink our Rust libraries builds, we should move away from OpenSSL.
Instead, we should use the [ring](https://github.com/briansmith/ring) rust library which doesn't need to be linked against a static library.
However, `ring` is still incomplete and we are missing some important crypto primitives, so we should consider this issue more as a laundry list.

| User  | Primitives used | Solution |
| ------------- | ------------- | ------------- |
| [reqwest](https://github.com/seanmonstar/reqwest) | TLS (on linux/android, implemented with openssl) | Use the `rustls-tls` feature of `reqwest`. |
| [sync15-adapter](https://github.com/mozilla/application-services/tree/master/sync15-adapter) | AEAD(HMAC::sha256/AES-256-CBC) (encrypt/decrypt) | Depends on: https://github.com/briansmith/ring/issues/588. |

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-80)

**Comment by briansmith** [comment]
> sync15-adapter	AEAD(HMAC::sha256/AES-256-CBC) (encrypt/decrypt)	Depends on: briansmith/ring#588.

Is this some legacy thing that can't be changed to use a different AEAD?

Preliminary ECDSA signing support was just added in *ring* 0.13.0-alpha4, and the `ring::signature::sign()` API is "stable enough" for things to start using for ECDSA.

**Comment by eoger** [comment]
I'm currently trying to integrate [biscuit](https://github.com/lawliet89/biscuit/pull/95) (for JWKs) in order to drop the `cjose`/`jansson` dependencies.

However, I couldn't find an accessor for the `x` and `y` params of an ECDSA public key. I'm guessing something like `public_key::parse_uncompressed_point` in combination with `public_from_private` would probably do the trick, but not sure where to go from there. Toughts @briansmith? I'd be happy to write a PR if necessary.

**Comment by briansmith** [comment]
> However, I couldn't find an accessor for the x and y params of an ECDSA public key. I'm guessing something like public_key::parse_uncompressed_point in combination with public_from_private would probably do the trick, but not sure where to go from there. Toughts @briansmith? I'd be happy to write a PR if necessary.


Later on, we might expand *ring*'s API to be more accomodating to non-standard forms and other forms of keys, but looking at the backlog, that probably won't happen soon. The current design of *ring* is that we don't provide the X and Y coordinates intentionally. Instead we provide the entire public key in a long-ago-standardized form. In the case of JOSE they made a mistake and decided to make their own new format for public keys. So far, I've told JWT libraries that they should internally convert the standard form that *ring* provides into the form they need by parsing the standard form themselves. In the case of ECC public keys, the first byte is "0x04", the X coordinate is the first half of what's left, and the Y coordinate is the second half of what's left. So, I would submit a PR to biscuit to do that.

**Comment by vladikoff** [comment]
> ECDSA

Should be `ECDH`

**Comment by briansmith** [comment]
> ECDSA
> 
> Should be ECDH

The standard form of the public key is exactly the same for both.

**Comment by eoger** [comment]
Thanks to the efforts made in https://github.com/mozilla/application-services/pull/95 and https://github.com/mozilla/application-services/pull/98, we have eliminated the openssl dependency on select platforms for the `fxa-client` crate (only `reqwest` pulls it in now). 🎉
I have updated the first post laundry list in consequence.

**Comment by briansmith** [comment]
If you use the `rustls-tls` feature of `reqwest` (and disable default features?) then it will use Rustls instead of OpenSSL for TLS.

**Comment by thomcc** [comment]
We still need OpenSSL as part of SQLcipher (for logins, places) and for sync15-adapter, though. All our consumers of the FxA crate realistically still pull in OpenSSL.

**Comment by briansmith** [comment]
> We still need OpenSSL as part of SQLcipher (for logins, places) and for sync15-adapter, though. All our consumers of the FxA crate realistically still pull in OpenSSL.

Those can be dealt with too.

**Comment by eoger** [comment]
Our last OpenSSL dependant are:
- the`reqwest` crate (TLS stack) on Desktop Linux (Android has `viaduct` eliminating that dep).
- `rust-ece` (but we implement our custom crypto backend, therefore not really using the openssl primitives).
Closing in favor of individual issues.
