### ISSUE TITLE
Cannot compile rc_crypto bindings on Ubuntu 

### ISSUE THREAD

**Issue by leplatrem** [mozilla/application-services#3908]
I have a tiny project with:

```toml
[dependencies]
rc_crypto = { git = "https://github.com/mozilla/application-services", rev = "c1b6b592897661d28f8e8437503b7eb4c5e7d954"}
```
That I'm trying to compile on Ubuntu:
```
libnss3-dev:
  Installed: 2:3.49.1-1ubuntu1.5

rustc 1.50.0 (cb75ad5db 2021-02-10)
```

But it fails to link on missing parts.
 
```
$ NSS_DIR=/usr/include/nss cargo build
   ...
   Compiling rc_crypto-demo v0.1.0 (rc_crypto-demo)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh [...]

  [...]

  = note: /usr/bin/ld: cannot find -lnssckbi
          /usr/bin/ld: cannot find -lsoftokn3
          collect2: error: ld returned 1 exit status
```

Since it could be related to Ubuntu packaging, I compiled NSS locally.

```
hg clone https://hg.mozilla.org/projects/nspr
hg clone https://hg.mozilla.org/projects/nss
cd nss/
./mach build
```

And then compiled the project with ``NSS_DIR=`pwd`/nss/out/Debug cargo build`` instead. 

No luck, same error.

I can see `libsoftokn.a` and `libnssckfw.a`, but creating symlinks didn't seem to be enough.

Is there something obvious that I'm missing?
Thank you in advance :pray:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2093)
┆Sprint: Backlog

**Comment by mhammond** [comment]
I can repro this, but it works with `NSS_STATIC=1` - I only know this because https://github.com/mozilla/application-services/blob/main/libs/verify-desktop-environment.sh sets it :)

**Comment by leplatrem** [comment]
It worked :tada:

Thanks Mark!

**Comment by leplatrem** [comment]
Oh, I may have spoken too fast.

The following works (*using local checkout of `application-services`*):

```
$ cd /path/toapplications-services/libs/
$ ./build-all.sh desktop

$ cd /path/to/rc_crypto-demo/
$ export SQLCIPHER_LIB_DIR=/path/to/application-services/libs/desktop/linux-x86-64/sqlcipher/lib
$ export SQLCIPHER_INCLUDE_DIR=/path/to/application-services/libs/desktop/linux-x86-64/sqlcipher/include
$ export NSS_DIR=/path/to/application-services/libs/desktop/linux-x86-64/nss
$ export NSS_STATIC=1
$ cargo build
```

But If I just do (*using system package*):

```
$ cd /path/to/rc_crypto-demo/
$ NSS_DIR=/usr/include/nss NSS_STATIC=1 cargo build
```

I get the following error on `certdb`: 
```
error: could not find native static library `certdb`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `nss_sys`

Caused by:
  process didn't exit successfully: `rustc --crate-name nss_sys --edition=2018 /home/mathieu/.cargo/git/checkouts/application-services-99bb257f08384f94/c1b6b59/components/support/rc_crypto/nss/nss_sys/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=23bf3543a38abc59 -C extra-filename=-23bf3543a38abc59 --out-dir /home/mathieu/Code/Mozilla/rc_crypto-demo/target/debug/deps -L dependency=/home/mathieu/Code/Mozilla/rc_crypto-demo/target/debug/deps --extern libsqlite3_sys=/home/mathieu/Code/Mozilla/rc_crypto-demo/target/debug/deps/liblibsqlite3_sys-ad6354d51d166b8e.rmeta --cap-lints allow -L native=/usr/include/nss/lib -l static=certdb -l static=certhi -l static=cryptohi -l static=freebl_static -l static=nspr4 -l static=nss_static -l static=nssb -l static=nssdev -l static=nsspki -l static=nssutil -l static=pk11wrap_static -l static=plc4 -l static=plds4 -l static=softokn_static -l static=gcm-aes-x86_c_lib -l static=hw-acc-crypto-avx -l static=hw-acc-crypto-avx2 -l static=intel-gcm-wrap_c_lib -l static=intel-gcm-s_lib -L native=/home/mathieu/Code/Mozilla/rc_crypto-demo/target/debug/build/libsqlite3-sys-1bb481012a923449/out` (exit code: 1)
```

I tried to install `libnss-db`  etc. but no luck :shrug:

**Comment by mhammond** [comment]
Maybe you don't need `NSS_STATIC=1` in that case? The build script in app-services calls `nss/build.sh ... --static` and I guess the system one does not.

Also, why do you need to use the system lib at all? Once nimbus gets its permanent home in app-services I imagine you can just use that one?

**Comment by dmose** [comment]
@leplatrem If I understood correctly, this is no longer a problem for you?

**Comment by leplatrem** [comment]
Yes, you're right, I could install it following these steps more or less:
https://github.com/mozilla-services/remote-settings-client/blob/11e97c6006b31903e7ee05497e311a700b636de8/.circleci/config.yml#L25-L45

I wished there would be a way to leverage the packaged NSS in Ubuntu instead of this, but I can live with it ;)
Thanks for reminding me! Let's close it for now!
