### ISSUE TITLE
Flesh out a strategy for history to deal with sqlite locking/busy errors and avoiding blocking during long operations

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#394]
There are some cases where we expect sqlite to fail with SQLITE_BUSY. In the general case, we should be able to guard against and/or recover from these errors without dropping any data and without the app being aware.

Also, the ffi layer will ensure only 1 thread is in our rust code at once. Even without locking issues, we can't afford to block all threads while a sync is in progress as some may take many many seconds.

**Comment by mhammond** [comment]
> Also, the ffi layer will ensure only 1 thread is in our rust code at once.

hrm - that's not correct, is it? https://github.com/mozilla-mobile/reference-browser/issues/383 appears to demonstrate that fact too :)

**Comment by thomcc** [comment]
At the time that you wrote it, I believe it might have been true.

**Comment by mhammond** [comment]
Much of what I'm writing here isn't really news, although some of it will be for some people (eg, I only very recently discovered rusqlite sets a default timeout and I'd always assumed we used WAL)

Rusqlite sets a default timeout of 5 seconds. Regardless of what mode is used, we always end up waiting 5 seconds on contention.

We currently don't enable the [WAL](https://www.sqlite.org/wal.html). This means that currently both reads and writes have "contention" - either can fail with SQLITE_BUSY if there's both a read and write and either takes > 5 secs to complete.

If we enable WAL, reads and writes will never have contention - reads always work and never block. Only multiple writes have contention.

So moving to WAL means we really only need to protect against or otherwise handle multiple writes. In theory, this could probably be done by a mutex or ensuring there's a dedicated write thread. A mutex would still end up blocking a thread while it waits for the lock. While history writers generally don't need a response from the write, `sync()` calls do and it's almost certain bookmark writes will too (eg, the new bookmark's guid) - so a simple "put it in a queue serviced by a dedicated thread and forget about it" isn't really going to fly as a one-size-fits-all solution.

Looking at the reference browser issue, we see the stacks are all recording a visit or title. This implies there must either be a long-running read or write operation happening concurrently.

While "sync" is the obvious candidate, due to https://github.com/mozilla/application-services/issues/265, it's also possible that we have a number of long-running auto-complete queries running - they are never cancelled and probably haven't been extensively profiled. There are some reported issues on reference-browser about the performance of auto-complete which might also be explained by this.

So I think the directly actionable things we can do here are:

* unconditionally enable WAL - this is the only trivial thing here :(

* limit the number of concurrent auto-complete searches (ie, https://github.com/mozilla/application-services/issues/265) - this has threading concerns.

* work out how to avoid write contention. In practice, it's probably relatively easy to move the "observation" calls onto a single write thread, so it might be worth doing that, but as mentioned above, this isn't a general solution, and would still leave us to consider `sync()` today and bookmarks soon

These last 2 probably need to be considered holistically as each of them has threading implications and I'll open a PR for the first.

**Comment by thomcc** [comment]
> - limit the number of concurrent auto-complete searches (ie, #265) - this has threading concerns.

This branch could provide a framework for doing this (it exposes sqlite3_interrupt to kotlin): https://github.com/mozilla/application-services/blob/interrupt_handle_rough.

> it's probably relatively easy to move the "observation" calls onto a single write thread, so it might be worth doing that, but as mentioned above, this isn't a general solution, and would still leave us to consider sync() today and bookmarks soon.

It's not clear why we shouldn't just use a single thread for all writes. The thread could live in kotlin, and if it was already busy, new things could just be enqueued. This should not be too hard to implement, probably (much easier than putting the thread in rust and calling back into kotlin, at least).

If the writer thread never needs to call back into kotlin to signal completion, there's no major downside to putting it into rust (although I suspect things might still be simpler with it in kotlin).
