### ISSUE TITLE
Investigate suspiciously low "bookmarks" engine sync counts on Nightly

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3954]
Looking at the raw data for our [Sync Engine Success on Nightly Desktop](https://sql.telemetry.mozilla.org/queries/71638/) telemetry, it seems like there are suspiciously few sync attempts for "bookmarks" compared to the other engines (including a day in which there was only one single sync attempt for the "bookmarks" engine on Darwin!).

For example, going to the table of raw data and picking a random day in January, I see only 10s of syncs for the "bookmarks" engine versus many orders or magnitude more syncs for other engines such as "clients" and "rust-webext-storage".

Is this expected, perhaps because users edit their bookmarks a lot less frequently than they adjust other collections? Or is it a sign that something might be going wrong?

If I look at the same graphs for [beta](https://sql.telemetry.mozilla.org/queries/71640/source) and [release](https://sql.telemetry.mozilla.org/queries/71641/source) I do see a similar situation, with "bookmarks" syn volume a few orders of magnitude less than other engines.

(I also wonder if this low volume is why the success *rate* of the bookmarks engine always looks so erratic compare to the other engines, it's got a much smaller sample size so the day-to-date noise tends not to get smoothed out).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2112)
┆Sprint: Backlog

**Comment by mhammond** [comment]
Nice catch. The engine name should actually be `bookmarks-buffered` - so the 2 mysteries I see are (a) how 'bookmarks' is recording *any* syncs, and (b) why that other name isn't appearing?

**Comment by rfk** [comment]
> (b) why that other name isn't appearing?

The queries have an explicit ` AND engine.name IN ( ... list of names ... )` filter which would explain this. I don't think I have permission to try adding `bookmarks-buffered` to the queries though.

**Comment by mhammond** [comment]
Right, yes - I can change it locally and the numbers become sane. However, I don't seem able to save it either. @AnaMedinac seems to be the owner.

**Comment by AnaMedinac** [comment]
I've added everyone on the team to the queries - should be able to edit them now, let me know if not.
