### ISSUE TITLE
deleteAll methods for autofill component

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#3964]
Currently there are methods to delete individual addresses and credit cards, so it's impossible to perform a "wipe all credit cards/addresses" operation in a transactional way.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2114)
┆Sprint: Backlog

**Comment by grigoryk** [comment]
This came up in a review of a-c work that consumes `autofill` APIs - https://github.com/mozilla-mobile/android-components/pull/9875/files/3932be05f27b320489ae5d3d5a9a4d3f264d3f54#diff-60cf0297f508f172159540178543e196165b816514b8bb378be9e7391cea6c2a

**Comment by mhammond** [comment]
Apparently the only requirement is tests where we don't really care about transactions and we don't want to add an API that can be easily misused, so closing this.
