### ISSUE TITLE
Support syncing the tabs collection

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#397]
https://github.com/mozilla-mobile/reference-browser/issues/118 is asking for "synced tabs" support. We'll need a way sync tabs and expose an API so the reference browser can both query tabs from other devices and be told of currently open tabs in the browser.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-81)
┆Epic: Syncing Tabs

**Comment by grigoryk** [comment]
See also #399.

**Comment by davismtl** [comment]
This was just labeled as "a Must" for Fenix MVP.
https://github.com/mozilla-mobile/android-components/issues/1850

I will investigate.

**Comment by thomcc** [comment]
I think the hard part of this is that all existing sync engines will expect us to have a clients engine record if we have a tabs record.

Doing clients engine properly will be... kind of problematic given the highly separated architecture the component model enforces on us. It's possible we don't need to do it properly, however.

It's also possible we could come up with a new architecture for it. I think this was our plan, but it seems hard to do this on such a short timeframe given our other commitments.

Worth noting that read only access to this is probably a lot easier than read/write. I'm assuming they want read/write though.

**Comment by rfk** [comment]
> It's also possible we could come up with a new architecture for it. I think this was our plan,
> but it seems hard to do this on such a short timeframe given our other commitments.

Agreed, I think we can safely take that option off the table for Fenix.

What if the "synced tabs" datatype owned both the "tabs" and "clients" collections and was solely responsible for managing the data therein? Would that paint us into any corners with other uses of the "clients" collection we might want to make in future?

**Comment by mhammond** [comment]
I believe the main thing we use the clients collection for is the device name and formfactor. We can get the name from FxA, and it's probably not a huge deal to change desktop to gracefully handle the lack of a client record here - possibly iOS too (and it might be OK to not make the change to Fennic under the assumption people will not be using Fennic and Fenix?)

The formfactor is more problematic though - it's mainly used to decide what icon to show for the device, and this is probably going to come up in more contexts (eg, I could imagine the UI for send-tab probably want to know eventually the form factor of the target so it can choose a nice icon too)

**Comment by mhammond** [comment]
(hrmph - clients is also used for "stale device" detection - I'm not sure if we can deduce that from what we expose via FxA in rust?)

**Comment by eoger** [comment]
Continued in https://github.com/mozilla/application-services/issues/1174.
