### ISSUE TITLE
update the README to the docs directory that gives some pointers to what's in there.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3971]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2121)
┆Story Points: 5
┆Epic: Onboarding
┆Sprint: SYNC - 2021-04-16

**Comment by rfk** [comment]
We do already have https://github.com/mozilla/application-services/blob/main/docs/README.md but it's probably overdue for a bit of an audit and cleanup.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

From meeting: also it would be useful to link out to other sources of documentation from here, such as Mana pages.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

The right thing to do here is to steal the glean book.  For component specific information - make sure we link to the Rust docs.
