### ISSUE TITLE
"Global" refresh token

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#40]
From #15:
> I think it makes sense for the app to only ever have one refresh token. It might use that refresh token to grant multiple different access tokens with different combinations of scopes, but it'll be simpler both here and on the server if we can ensure it only has one refresh token that lists all the scopes granted to the application. But that can be for a follow-up issue.

**Comment by eoger** [comment]
Once we ship client instances metadata, we should try to get to that.
Here's a high-level breakdown on what need to be done:
- [ ] Support OAuth incremental authorization on the server.
- [ ] Use that API on FxA Client, and only store 1 refresh token.
- [ ] Drop the storage of OAuth access tokens. Always generate new ones.

cc @rfk

**Comment by shane-tomlinson** [comment]
Here's a nice shiny [IETF incremental OAuth spec for you](https://datatracker.ietf.org/doc/draft-ietf-oauth-incremental-authz/). Now is prime time to comment on where it can be improved.

**Comment by eoger** [comment]
We did this:
https://github.com/mozilla/application-services/blob/2685d001a5c01af3e08bccb82393e4ff7eee4361/components/fxa-client/src/oauth.rs#L206-L215
