### ISSUE TITLE
Expose signing primitives PKCS1 SHA384 with RSA encryption from NSS

### ISSUE THREAD

**Issue by leplatrem** [mozilla/application-services#4007]
In order to verify a certificate chain issued by Autograph, our remote-settings-client would require the equivalent of `ring`'s signing algorithms `RSA_PKCS1_2048_8192_SHA256` and `RSA_PKCS1_2048_8192_SHA384`.

I believe they are called `pkcs1SHA256WithRSAEncryption` and `pkcs1SHA384WithRSAEncryption` in NSS ([source](https://searchfox.org/mozilla-central/rev/4fa18c26fa907f38d56b599571b9846af1506f3c/security/nss/lib/util/secoid.c#215-218))

See also https://briansmith.org/rustdoc/ring/signature/static.RSA_PKCS1_2048_8192_SHA384.html
See https://github.com/mozilla-services/remote-settings-client/pull/94

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2151)
┆Epic: a-s supporting tools (backlog)
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

[~dmosedale@mozilla.com] or [~mleplatre@mozilla.com] - I'm not sure how this should be triaged. Is this a bug against rc_crypto to add functionality for remote settings client?

**Comment by dmose** [comment]
My understanding is that, yes, this is effectively a subset of the work described in the [Signature Verification doc that Ryan and Mathieu are working on](https://docs.google.com/document/d/1MOyx9sK_NWo6c9STN5O6P0dTCfIBc0ZOjhd7fZPtjuk/edit#). So I suspect it doesn't make sense to triage this until we see exactly where we end up on that doc.

**Comment by rfk** [comment]
It's my understanding that we no longer intend to expose these primitives, but will instead expose the higher-level `VerifyCodeSigningCertificateChain` function that was added to NSS in [Bug 1709291](https://bugzilla.mozilla.org/show_bug.cgi?id=1709291). @leplatrem does that sound right?

**Comment by rfk** [comment]
> It's my understanding that we no longer intend to expose these primitives,

Sorry, actually I think I misunderstood, and we actually *do* need to "check the signature" functions mentioned here in addition to the "check if the certificate chain is valid" function from the linked Bugzilla bug.

**Comment by leplatrem** [comment]
We don't need these primitives anymore. These RSA primitives could have been useful to verify the cert chain, but it will be covered by NSS. (note: The content signatures themselves are ECDSA)

The high level function of Bug 1709291 is (*was*) supposed to verify the content signature as well. I'll take care of following that up.

*closing*
