### ISSUE TITLE
[automation] Publish Javadoc

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#401]
This is simpler than #378 -- let's just publish Javadoc jars.  I noticed that `fxaclient` doesn't play along (and possibly other projects) due to fallout from the great package renaming to `mozilla.appservices.*`.  Should be easy to fix, just a bunch of renaming, which could be part of #213.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-707)

**Comment by thomcc** [comment]
It would be nice if we could publish docs using the kotlin documentation tool that android-components uses. Not sure if that's still "javadoc" for this conversation though.

**Comment by ncalexan** [comment]
> It would be nice if we could publish docs using the kotlin documentation tool that android-components uses. Not sure if that's still "javadoc" for this conversation though.

Yep -- that's #378.

**Comment by rfk** [comment]
I think it's pretty clear we're not going to get back to this.
