### ISSUE TITLE
autofill: Allow recovery from a bad or lost encryption key

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4015]
The app can probably detect a bad or lost encryption key, but it probably can't do anything to recover from that state (other than delete the entire DB, which seems sad and they'd lose addresses too)

@grigoryk and I thought that we could do something like:

* Add a new API that just nukes all encrypted values in the DB and resets sync
* Have Sync treat these empty values in a special way and always attempt to use the incoming record values.

This would also require us to change the sqlite CHECK constraint to allow a zero length string, or alternatively, we could use a regex to check that the encrypted value is valid (it will always be 5xbase64 encoded strings joined with a '.')

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2158)
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - 2021-04-30

**Comment by lougeniaC64** [comment]
@mhammond I'm starting to outline this work for Ben and this is what I have so far:
- Create an autofill [Store](https://github.com/mozilla/application-services/blob/6146895e0cfc2e519ac23c1dfba5f60097d4ca6d/components/autofill/src/db/store.rs#L39) function that:
  -  clears the `cc_number_enc` field for all credit cards in the [credit_cards_data database table](https://github.com/mozilla/application-services/blob/6146895e0cfc2e519ac23c1dfba5f60097d4ca6d/components/autofill/sql/create_shared_schema.sql#L47)
  - updates the [cc_number_enc](https://github.com/mozilla/application-services/blob/6146895e0cfc2e519ac23c1dfba5f60097d4ca6d/components/autofill/sql/create_shared_schema.sql#L54) constraint to allow empty values
  - [resets sync](https://github.com/mozilla/application-services/blob/6146895e0cfc2e519ac23c1dfba5f60097d4ca6d/components/autofill/src/sync/engine.rs#L198)
  
I do have questions regarding your second bullet point. Should sync treating these values in a special way just mean that there's an additional incoming state that represents this reset state? Also should credit cards fields be atomic? In other words if the encrypted field is nuked and a sync occurs, should all incoming record values be taken or should a merge occur?

**Comment by mhammond** [comment]
That all sounds correct to me. Re the last question: I don't think it matters TBH - a user would need to be extremely unlucky that the device loses the key after they made a local CC change to something other than the number and before that change was synced. So whatever is the least intrusive patch seems reasonable to me.

Feel free to chat with grisha too about nailing down requirements.

**Comment by lougeniaC64** [comment]
> That all sounds correct to me. Re the last question: I don't think it matters TBH - a user would need to be extremely unlucky that the device loses the key after they made a local CC change to something other than the number and before that change was synced. So whatever is the least intrusive patch seems reasonable to me.
> 
> Feel free to chat with grisha too about nailing down requirements.

Will do--thanks!

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

Seems good, my one question is how should we update the DB schema?  Should I write an update function like webext-storage has?

Related to this, does each component have its own database?  webext storage uses PRAGMA user_version, which seems like a fine system, but only if each component gets its own version number.

**Comment by mhammond** [comment]
You mean the schema for the constraint? I think we can probably get away with doing nothing at this point - it's never actually shipped anywhere, including to nightly. I think some parts might be in Nightly, but I don't think the actual initialization (and thus db creation) actually happens yet. @grigoryk probably knows better, so maybe check with him that not doing migrations yet is OK.

But more generally, yeah, what webext-storage does is what we tend to do, with the user_version. See the migrations in `places` for ones that are far more significant. Each component does get its own DB (which has its own set of pros and cons)

**Comment by grigoryk** [comment]
@mhammond we are currently shipping some UI which exposes credit card management in Nightly, which runs against a 74.* version of A-S. That UI is quite well hidden (only displayed in a developer mode, and then need to check an additional box buried someplace)...
But since we are shipping this already it's possible some nightly users started playing with it, which means we'll need a db migration if there are schema changes.

Which actually brings up a good question - where there any autofill schema changes between 74 and 75 that didn't have corresponding migrations? We'll need those.

**Comment by mhammond** [comment]
>  where there any autofill schema changes between 74 and 75 that didn't have corresponding migrations? We'll need those.

Yeah, the entire cc number encryption thing. We can't actually migrate that data, but we can migrate the schema and drop the CC numbers, which is probably better than nothing. I opened #4026

**Comment by lougeniaC64** [comment]
@mhammond @bendk This is my summary of sync changes required for this ticket. This is one of many ways this work can be completed. However, the steps below are a balance between making this change visible and extensible while (hopefully) reducing the pain of implementation. But having said that, changes, suggestions, and questions are welcome.
 
1. Create a new enum value for [LocalRecordInfo](https://github.com/mozilla/application-services/blob/e6983cbcc18409c51e03d8a30f410c3b1b82134e/components/autofill/src/sync/mod.rs#L187) representing the scrubbed state of the local credit card record after your newly-created function is called. It will be something like this:

```
Scrubbed: { record: T },
```
- Make sure to update the comment for this enum. Also, I'm not super in love with "Scrubbed" but I couldn't think of a more concise and meaningful name. Open to suggestions.

2. In this [Some](https://github.com/mozilla/application-services/blob/e6983cbcc18409c51e03d8a30f410c3b1b82134e/components/autofill/src/sync/credit_card/incoming.rs#L108) clause of the `fetch_incoming_states` function, check if the `cc_number_enc` field is an empty string. If the field is empty, return the new enum value you created. This check should be done before the `has_changes` check.
3. In the [plan_incoming function](https://github.com/mozilla/application-services/blob/e6983cbcc18409c51e03d8a30f410c3b1b82134e/components/autofill/src/sync/mod.rs#L281), add your new `LocalRecordInfo` enum value to the branch than handles `LocalRecordInfo::Unmodified`.

Something like this, although clippy may guide you on formatting.
```
LocalRecordInfo::Unmodified { record: local_record }  | LocalRecordInfo::Scrubbed { record: local_record }  => {
```
4. Finally ensure all existing tests pass and add tests to cover your changes in [test_mod](https://github.com/mozilla/application-services/blob/main/components/autofill/src/sync/tests/test_mod.rs).

**Comment by grigoryk** [comment]
@lougeniaC64 was this actually done, or did @data-sync-user close this by mistake?

**Comment by grigoryk** [comment]
Aha, I see that there's a `scrub_encrypted_data` that got added in https://github.com/mozilla/application-services/commit/e67c3aab466ac833a14a5113e88bc4e720976371
