### ISSUE TITLE
Organize dependency versioning in gradle files.

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#4037]
Currently we have a disorganized management of dependency versions in our gradle files.

e.g.

```groovy
     testImplementation 'androidx.test:core-ktx:1.2.0'
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
     testImplementation "org.mozilla.telemetry:glean-forUnitTests:$project.ext.glean_version"
```

Here we have:

* a bare version string
* a variable referencing an `ext` variable containing the version string.
* an unnecessarily complicated version of the same.

This issue requires a motivated Android engineer to bring order to this chaos of versioning.

For example, Fenix and Android Components use kotlin files for Dependency strings and Version strings.

```groovy
    testImplementation Dependencies.androidx_test_core
```

In `Dependencies.kt`

```kotlin
const val androidx_test_core = "androidx.test:core-ktx:${Versions.AndroidX.test}"
```

Then in `Versions.kt`:

```kotlin
  object AndroidX {
        // …
        const val test = "1.3.0"
  }
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2625)

**Comment by lucastosetto** [comment]
Working in this one!

**Comment by nox1134** [comment]
Hi @mhammond! Is this fixed? If not I'd like to work on this issue. Also where do i need to make this changes to? All the gradle files and then just have a common `Dependencies.kt` and `Versions.kt` for it?

**Comment by mhammond** [comment]
This is still open. If there's something you don't understand in the initial description, please be specific about what it is.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866337

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
