### ISSUE TITLE
Return SyncKeysC/AccessTokenInfoC/ProfileC by value

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#405]
It should be safer to return these results by value instead of returning a pointer:

https://github.com/mozilla/application-services/blob/b12ede6ac0e925db492fbe53401a6e0f72151044/fxa-client/src/ffi.rs#L161-L178

cc @thomcc

**Comment by thomcc** [comment]
See: https://github.com/mozilla/application-services/blob/b12ede6ac0e925db492fbe53401a6e0f72151044/components/support/ffi/src/into_ffi.rs#L108-L140, which is an example of how we might do it.

Note that there are some kotlin changes required too.

**Comment by eoger** [comment]
We use protobufs now :)
