### ISSUE TITLE
Uniffi tabs component

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4056]
Uniffication guide - https://mozilla.github.io/application-services/book/howtos/converting-a-component-to-uniffi.html

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2629)
┆Story Points: 8
┆Epic: Uniffi-cation of logins, tabs and history metadata
┆Fix Versions: Release 92
┆Sprint End Date: 2021-08-06

**Comment by grigoryk** [comment]
This doesn't seem like it's blocking anything, and I'd like to poke around w/ uniffi a bit.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Linking in the PR here to make it easier to track.  [~gkruglov@mozilla.com] are you blocked on anything here?
