### ISSUE TITLE
Add encryption to logins sync logic

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#4065]
* Implement [EncryptorDecryptor](https://github.com/mozilla/application-services/blob/main/components/autofill/src/encryption.rs#L40) logins sync logic so the encrypted fields in the new per-field encrypted database can be read
  * ~Keep in mind that we need to support both encryption approaches during the migration period~
* Update the sync manager logic to register the logins store
* Add tests and make sure existing tests still pass

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2632)
┆Epic: Logins update and sqlcipher migration
┆Fix Versions: Release 92
┆Sprint End Date: 2021-07-23

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

This is done.
