### ISSUE TITLE
Add additional events to listen to changes to the available experiments in Nimbus

### ISSUE THREAD

**Issue by boek** [mozilla/application-services#4077]
Currently the only event we're getting from Nimbus is here: https://github.com/mozilla/application-services/blob/main/components/nimbus/ios/Nimbus/Nimbus.swift#L76

This is making it hard to write UI that responds well when setting or resetting the experiments using client QA/Development tools.

I would like to know whenever `NimbusApi::setExperimentsLocally` is finished on it's background queue so I can update the UI to show the new set of experiments.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2191)
┆Sprint: Backlog

**Comment by jhugman** [comment]
`setExperimentsLocally` and `applyPendingExperiments` both happen on the same thread, so IIUC you should be able to 

1. call them `setExperimentsLocally` and `applyPendingExperiments`.
2. listen for the `.nimbusExperimentsApplied` notification.

**Comment by jhugman** [comment]
The fix for this could be as simple as always call the `NotificationCenter` notify. Speaking to @boek , he's suggesting that even when we enroll into an experiment (via `opt_in_with_branch`), the change events are empty. This is another avenue of investigation.
