### ISSUE TITLE
Review timePasswordChanged handling

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4088]
Now that the password field is encrypted, updating timePasswordChanged becomes more tricky.  The main issue if you encrypt the same string twice you'll get two different encrypted values.  So we have this potential edge case:

* Consumer fetches a login
* The user uses the password from that login, but a different username
* The consumer code sets usernameEnc to the new encrypted value and also sets passwordEnc (maybe because they have 1 function that always updates both)
* Consumer code calls update()
* logins code sees that the password string is different, so it updates timePasswordChanged, even though the decrypted value didn't change.

I think there's a few ways to handle this:

* If that case doesn't come up in practice, maybe we can ignore it
* When a login is fetched, store the original encrypted password in the struct, then implement `password_changed(self, encryption_key)` to check if the password actually changed or not
* Add a set_password(self, new_password, encryption_key) method.  This one would check if the decrypted value was the same and keep the encrypted value the same in that case.  Maybe this could be part of a general system where that password_enc only changes if the decrypted value changed.

Github Issue: https://github.com/mozilla/application-services/issues/4088

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2197)
┆Story Points: 3
┆Epic: Migrate away from SQLCipher
┆Sprint: SYNC - 2021-06-11

**Comment by mhammond** [comment]
This is a great point, thanks for raising it. I haven't thought much about it, but the app must certainly know the old and new passwords - so even though we might not be able to tell if it is the same or not, they know. Having an API, say `set_new_password(encrypted_password)` and a note saying "don't call this if the password hasn't changed as it updates the time_last_changed value" seems perfectly reasonable on both sides of the fence?

(I don't have a strong opinion though)

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

I think that one could be good.  It seems like an improvement on the "let's just ignore it" solution.  The logic is basically the same, but if the method is named well than it seems unlikely that the calling code will do the wrong thing.

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

Talked with Lougenia about this one and we are wondering if maybe we could just get rid of the timePasswordChanged field.  It seems like it's only use in in the two_way_merge logic  from update_plan.  Could we use the system that three_way_merge() uses instead which compares local_modified to the server timestamp?

https://github.com/mozilla/application-services/blob/main/components/logins/src/update_plan.rs#L25

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

So fun fact, just did some repo diving and found that almost a year ago a Firefox Monitor feature ( https://github.com/mozilla-mobile/firefox-ios/pull/7136 ) was introduced to Firefox iOS that collects logins that have been involved in a breach by comparing the timePasswordChanged field to the breach date (see here ( https://github.com/mozilla-mobile/firefox-ios/blob/041c85483b1aa4a4e357d8bd9419550e4f20347a/Client/Frontend/Login%20Management/BreachAlertsManager.swift#L166 ) for details).

**Comment by lougeniaC64** [comment]
I'm assuming what I've proposed is okay and will close this issue and include that proposal in [the architectural design](#4101).
