### ISSUE TITLE
How to handle unset username fields?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4089]
Once username fields are stored encrypted, we need to decide how to handle unset values.  I think there's a couple possibilities:

* Null
* Raw Empty string
* Encrypted Empty string

On a related note, there's this line: [https://github.com/mozilla/application-services/blob/72e9e82e22239b5410c78a43dfc85ad2599845c7/components/logins/src/login.rs#L524.](https://github.com/mozilla/application-services/blob/72e9e82e22239b5410c78a43dfc85ad2599845c7/components/logins/src/login.rs#L524.)  I believe the `string_or_default` call is to there to translate NULL values to empty strings.  I think that's to handle exceptional cases,.  Do we want to continue to support NULL values in the database?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2198)
┆Story Points: 3
┆Epic: Migrate away from SQLCipher
┆Sprint: SYNC - 2021-06-11

**Comment by mhammond** [comment]
> Do we want to continue to support NULL values in the database?

Is there a distinction between them? Recently we've tended to avoid supporting both if they are identical in practice - it just makes the code more complex and error prone.

**Comment by mhammond** [comment]
and I guess from a security POV, if we assume that leaking a username is bad, I guess we should also assume leaking the fact the username is blank is also bad? This kinda leads me to think we should have a `NOT NULL` field that stores the encrypted empty string?

**Comment by mhammond** [comment]
> I guess we should also assume leaking the fact the username is blank is also bad?

OTOH, all we are leaking here is that the user declined/forgot/whatever to *save* the username - it's not an assertion that the username is in-fact blank. So if there's a good reason to store an empty string as an empty string we should keep that on the table. (I don't see one though, but one might exist)

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

> > Do we want to continue to support NULL values in the database?

> Is there a distinction between them? Recently we've tended to avoid supporting both if they are identical in practice - it just makes the code more complex and error prone.

I don't think there's a distinction.  We convert NULL to "" in the from_row method.  Login.username is not an option, so either consumers can't set a null value, or it's getting converted before it gets to the rust code.

**Comment by mhammond** [comment]
that sounds great.

**Comment by bendk** [comment]
I think this is all set:
  - For scrubbed data, the plan is to use use the autofill work, which uses the unencrypted empty string
  - For normal records, the logins code currently assumes they're the encrypted empty string.  I'll add a note to the API refactor issue to make sure consumer codes follows this.
  - In `logins-per-field-encryption`, we currently set deleted data to the unencrypted empty string
