### ISSUE TITLE
Make sync-pass example work again

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4090]
I don't think the sync-pass example is going to work after the encryption changes.  I think we could fix it without too much work.  I think the main issue is how to input the encryption key.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2291)
┆Epic: Logins update and sqlcipher migration
┆Fix Versions: Release 92

**Comment by mhammond** [comment]
> I think the main issue is how to input the encryption key.

probably the same way as the autofill example - we just store it as a meta value in the DB? Obviously this isn't secure, but it doesn't matter in this case.
