### ISSUE TITLE
Create proposal for logins api changes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4101]
* Investigate the impact of not exposing the migration function
* See if we can refactor/optimize the handling of empty usernames in a way that makes `potential_dupes_ignoring_usernames` obsolete
* Identify where add/update is used and see if it can be replaced by save/update

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-2206)
┆Story Points: 8
┆Epic: Update logins api
┆Sprint: SYNC - 2021-06-25

**Comment by bendk** [comment]
Note from #4089: Let's make sure consumer code handles unset usernames by storing the *encrypted* empty string, instead of the plaintext one.
