### ISSUE TITLE
Create tests for sqlcipher migration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4148]
This is a ticket to represent whatever work is required for increasing our confidence in the sqlcipher migration code and (hopefully) preventing the loss of user data. Some of the work required here may be done in [SYNC-2223](https://jira.mozilla.com/browse/SYNC-2223).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2227)
┆Story Points: 3
┆Epic: Migrate logins away from SQLCipher
┆Sprint: SYNC - 2021-06-25

**Comment by bendk** [comment]
Currently the sqlcipher code has unittests and it's been tested with the `sync-pass` code.  I think this is as much testing as we're going to do for this one.
