### ISSUE TITLE
create a manual build of a-s 77.0.2 but using xcode 12.5 (and maybe Nish's branch) to provide to iOS for testing.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4149]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2228)
┆Sprint: SYNC - 2021-06-11

**Comment by rfk** [comment]
The mac artifacts for v77.0.2 failed to build in CI, so I've manually uploaded a build that was build using XCode 12.5, and noted it in the #firefox-ios channel for visibility. We can continue work on moving CI to the new version in https://github.com/mozilla/application-services/pull/4052.
