### ISSUE TITLE
Make it clearer that ffi-support lives in its own repo

### ISSUE THREAD

**Issue by badboy** [mozilla/application-services#4152]
I see that there was a [ffi-support release](https://crates.io/crates/ffi-support/0.4.3) yesterday: v0.4.3.
It seems that release was done from the https://github.com/mozilla/ffi-support repository.

However the `repository` still points here.
Can you clarify where ffi-support's canonical repository lives now?
If its in the external repository, why does the internal code at `components/support/ffi` remains?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2230)
┆Sprint: Backlog

**Comment by rfk** [comment]
Oh, good catch thanks. The separate repo is the canonical one, ref https://github.com/mozilla/application-services/issues/3463. I'll adjust this issue to be about making that more obvious, and take on the cleanup work.

**Comment by rfk** [comment]
Also, seems like we should entirely remove it from this repo now that the code is maintained elsewhere.
