### ISSUE TITLE
Have clean.py try and clean with xcode, and/or clean other iOS specific stuff

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4169]
clean.py (landed via #4094) doesn't make any attempt to clean anything for iOS, but it should. Ryan points it's possible in theory to clean an xcode project from the command-line using `xcodebuild`, see e.g. [here](https://stackoverflow.com/questions/19091769/clean-ios-xcode-target-in-command-line).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2270)
┆Epic: Important backlog

**Comment by venkateshprabhu2** [comment]
Hi. Is this still open? Can I work on it and if yes, how do I get started?

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866338

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
