### ISSUE TITLE
[automation] Push application-services symbols to Socorro from Taskcluster

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#418]
This ticket tracks uploading symbols for our various FFI libraries (and megazord libraries) to Socorro, so that Apps that use a-s and GeckoView (at least) can symbolicate native code crashes. 

It looks like there's great prior art for this in Firefox Reality: https://github.com/MozillaReality/FirefoxReality/blob/master/tools/taskcluster/upload_symbols.sh.

One thing that might be a hiccup here is that we're publishing libraries that are not associated to a specific App.  I'm not sure that Socorro handles this situation -- it seemed rather App-centric last I looked.

**Comment by ncalexan** [comment]
This is a piece of #134.

@pocmo this is relevant to today's Mobile Tech Leads discussion.

**Comment by rfk** [comment]
This is in progress, re-labelling appropriately. I'm surprised it didn't get moved automatically when the corresponding PR was opened.

**Comment by pocmo** [comment]
Is there a way how we can test the whole chain now? E.g. crash application services code in RB and have that show up as a native code crash in our [crash-stats bucket](https://crash-stats.mozilla.com/home/product/ReferenceBrowser).

**Comment by eoger** [comment]
Note for readers: I've reached out to Sebastian and currently trying it out

**Comment by eoger** [comment]
Crash reporting works, however symbolication is not working so it's pretty much useless. I have opened [Bug 1538029](https://bugzilla.mozilla.org/show_bug.cgi?id=1538029).

**Comment by eoger** [comment]
Forgot to update @pocmo, crash reporting is [now working](https://crash-stats.mozilla.com/report/index/364ec566-33cf-41db-8aaf-9656d0190326).
