### ISSUE TITLE
v0.10.1 and v0.10.2 are not compatible with v0.10.0

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#419]
There was a mix-up publishing v0.10.1; it needed to be retagged and https://github.com/mozilla/application-services/commit/ef31660192e252d3e94d0a2abe517f994ca405c6 snuck in between the taggings.  This was my error.  Unfortunately the API around FxA OAuth changed, so 0.10.{1,2} are not compatible with 0.10.0.

I'm not particularly concerned about this: I think we should publish a v0.11.0 and roll Android Components to it ASAP to address this, and just leave the bad versions.  (Bad versions happen; deleting packages is unsavoury.)

@thomcc @eoger thoughts?

**Comment by rfk** [comment]
from mtg: we saw some chatter about tags in slack between @ncalexan and @eoger, assigning to you for now but please update as appropriate.

**Comment by thomcc** [comment]
We're on 0.11.3 now so its safe to close this.
