### ISSUE TITLE
Implement the database corruption strategy from #4201

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4214]
I think we've basically committed to a decision regarding database corruption and it's spelled out in the MADR doc in #4201.  Let's implement it.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2260)
┆Epic: a-s supporting tools (backlog)

**Comment by mhammond** [comment]
I believe we've implemented what that MADR records - that we check for corruption when opening the DB - so I'm closing this and I'll open another for corruption while being used.
