### ISSUE TITLE
Kotlin Multiplatform support

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4241]
Heya, i'm looking at uniffi's support for Kotlin, and i'm seeing quite a few imports which make me wonder if it's possible to support KMP, Kotlin Multiplatform, to be able to bind variants of the same code onto multiple platforms.

Are there any plans for this, or would this even be remotely possible?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2312)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Hi @ShadowJonathan, thanks for reaching out! We don't have any particular plans to support KMP at the moment, but also I don't see any particular reason why we couldn't support it. I'm not very familiar with it though - if you know your way around using KMP a little bit, I'd welcome you trying out one of the small examples from this repo, seeing whether you can successfully integrate it into a KMP project, and letting us know how it works (and/or how it fails).

**Comment by ShadowJonathan** [comment]
@jdragojevic sync oopsie?

**Comment by rfk** [comment]
@ShadowJonathan yeah, sorry, there's some automation running amok on these repos at the moment, we're working on it :-/

**Comment by ShadowJonathan** [comment]
nw nw, i was just curious
