### ISSUE TITLE
[automation] Produce Android x86_64 binaries

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#426]
I noticed that we're not producing x86_64 binaries in automation.  It might be a little difficult; see https://stackoverflow.com/questions/26779531/openssl-for-android-x86-64-and-mips64.

**Comment by rfk** [comment]
@ncalexan triaging this to backlog, please raise urgency as you see fit.

**Comment by rfk** [comment]
From slack conversation, it sounds like this may be required on or before August first due to:

https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html?m=1

**Comment by rfk** [comment]
I'm putting this back into "triage" for discussion based on the above.

**Comment by rfk** [comment]
> I'm going to set a calendar reminder to revisit this in March for further discussion.

It's March, we should discuss this again.
