### ISSUE TITLE
Move from JCenter to Maven Central or another repository?

### ISSUE THREAD

**Issue by mcamou** [mozilla/application-services#4295]
Lately JCenter has been quite unstable, we are often having problems downloading from it.

Would it be possible to migrate all the `org.mozilla.appservices` packages to Maven Central or some other repository?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2671)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866339

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
