### ISSUE TITLE
Add a doc describing sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4301]
Write the document that I've been meaning to create that describes how we implement syncing including:

* Local vs mirror vs incoming data
* The fetch_data ~~> reconcile~~ > execute_plan ->  fetch_outgoing pattern used by a lot of our components
* Document some of the ways individual components diverge

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2673)
┆Epic: Sync Ecosystem (backlog)
┆Sprint End Date: 2021-07-09

**Comment by bendk** [comment]
Maybe this is still useful, but I don't have plans to write this at this point.  Let's close this issue.
