### ISSUE TITLE
Make Nimbus (optionally) consume Glean as a Swift Package dependency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4308]
The Nimbus swift bindings currently use various functions exposed by Glean, and broadly assume that they will be built together with Glean in a single combined Swift module. When we move to Swift Packages that’s no longer going to work, since consumers will want to depend on Glean as its own separate Swift package.

Swift as a neat `#if canImport()` feature that I hope to use to help with this, described [here](https://www.hackingwithswift.com/example-code/language/how-to-check-whether-a-module-is-available-using-canimport). Broadly:

* If `#if canImport(Glean)` to check whether Glean is available for import; if it is then we’re consuming Glean via an external package, if it isn’t then we’re building together with glean in a megazord bundle.
* If we’re using Glean as an external package, add `import Glean` in the relevant places.

This is a little complicated by the fact that Nimbus currently uses several Glean APIs that are not part of its official public API, such as the `Sysctl` and `Logger` helpers. We’ll need to either ask the Glean team to expose them as public APIs, or replace them with something else (perhaps by copying the relevant bits of code directly from Glean).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2677)
┆Story Points: 8
┆Epic: Unified a-s swift packages for iOS
┆Sprint End Date: 2021-08-06

**Comment by rfk** [comment]
I have a sketch of the required changes up in https://github.com/mozilla/application-services/pull/4368
