### ISSUE TITLE
Factor out and/or publish `rc_crypto` as its own crate/repo

### ISSUE THREAD

**Issue by msirringhaus** [mozilla/application-services#4331]
I am currently adding CTAP2/FIDO2 support to Firefox via [authenticator-rs](https://github.com/mozilla/authenticator-rs). See [here](https://github.com/mozilla/authenticator-rs/issues/33) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1530373).

For the crate itself, multiple crypto-backends are planned, but to add it to Firefox, it should be NSS.
Therefore, NSS<->Rust bindings are needed. `rc_crypto` (as well as `nss` and `nss_sys`) seems to work well.
But they are hard to add as dependencies and vendor, given that they are embedded into `application-services`.

To properly use it, it would be great if at least one of two things (or possibly both) could be done:
1. Publish `rc_crypto`, `nss`, `nss_sys` and `nss_build_common` on crates.io
2. Create a new repository (or repositories, see below) for it/them and copy the sources over.

Number 1 would be the least amount of inital work and preserve commit history, but would mean repeated releases and publications for updates and bugfixes to those crates.

For 2., it could be done with either 4 new repos, or with only one for `rc_crypto` in it, and the `nss*`-crates as sub-crates inside, as they are now. But then, they would need to be publicly exposed inside `rc_crypto` in order to access the lower-level functions as well (e.g. `use rc_crypto::nss::nss_sys::SECItem`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2685)

**Comment by msirringhaus** [comment]
Addendum: 
1. I missed that the embedded crate `error_support` needs to be published/copied as well.
2. For testing purposes, I created a new repo ([here](https://github.com/msirringhaus/rc_crypto_test)) and copied all the sub-crates + `support_error` in there and exposed them (see [here](https://github.com/msirringhaus/rc_crypto_test/commit/09d0e99390f3dd49df5a62e5eb5bff33da29eb16)). This seems to work fine!

**Comment by msirringhaus** [comment]
Addendum 2:
As it turns out, there is no pressing need for the publication, after all. I did not realize that
```
rc_crypto = { git = "https://github.com/mozilla/application-services", rev="8a576fbe79199fa8664f64285524017f74ebcc5f", feature="gecko"}
nss = { git = "https://github.com/mozilla/application-services", rev="8a576fbe79199fa8664f64285524017f74ebcc5f", feature="gecko"}
nss_sys = { git = "https://github.com/mozilla/application-services", rev="8a576fbe79199fa8664f64285524017f74ebcc5f",  feature="gecko"}
```
works. But it does! So its possible to specify `rc_crypto` and friends as a dependency and vendor them individually. 
For some reason, I thought this wouldn't work, but it does.

Feel free to close this issue.

**Comment by mhammond** [comment]
Yeah, we already vendor a couple of crates from app-services into mozilla-central using this technique and at this stage have no plans to split everything into its own repo, so I'm going to close this.

**Comment by rfk** [comment]
> at this stage have no plans to split everything into its own repo

@mhammond just a heads-up that Tarik and I put this on the agenda for a discussion at the upcoming Kitchen Sync; we can re-open it if we decide it's a good idea from that discussion.
