### ISSUE TITLE
Investigate and filter out which errors need to be reported to the crash reporters

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#4333]
After landing https://github.com/mozilla-mobile/fenix/pull/20049, we're seeing large upticks of errors reported as infos in our Sentry service.

Some are genuine issues that we need to be acted on by the Nimbus team (https://github.com/mozilla-mobile/fenix/issues/20268, https://github.com/mozilla-mobile/fenix/issues/20269), some are warnings that we have no control over (RequestError, ResponseError, etc.).

Part of this issue should be to investigate which ones are not needed to be reported to the consumer's crash reporter.

Another part is to upstream the fixes from https://github.com/mozilla-mobile/fenix/issues/20267.

Why is this reported here?
Unlike other app services components, all dependencies and delegates are forwarded directly through to the Nimbus component in this project. So we have no control to filter this out at the android components layer (e.g. [push](https://github.com/mozilla-mobile/android-components/blob/2f1ec9101a0d618da6681eb1fa12e15bff4dfe03/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L362-L377))

cc: @jhugman

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SDK-330)
┆Epic: early startup (placeholder bucket)
┆Sprint End Date: 2021-07-23

**Comment by mhammond** [comment]
app-services has grown better error-handling and error-reporting capabilities - I'm not sure if they are actually being used by Nimbus, but I'll flag this for them anyway.
