### ISSUE TITLE
SQLite 3.36 changes the output of `EXPLAIN QUERY PLAN`, breaking the code in `sql_support::query_plan`.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#4342]
In the next version of SQLite, the format of the output of `EXPLAIN QUERY PLAN` changed: https://www.sqlite.org/releaselog/3_36_0.html

In the past, I wrote a parser for the output of this format here: https://github.com/mozilla/application-services/blob/main/components/support/sql/src/query_plan.rs, which I believe is used in test code. This code will likely panic, or return Err, under the new format, depending on how different it is.

This is just a heads up that a future version of rusqlite will change the bundled version of SQLite (which, IIRC, is also used in test/CI configurations), and so could cause some breakage when you update.

I think the best option would either be for you to remove this code, or rewrite it for the new format. It was useful to have in the past, but SQLite doesn't guarantee the format of the response is stable.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2693)

**Comment by mhammond** [comment]
Thanks Thom, we'll work out what to do here.
