### ISSUE TITLE
Build NSS and SQLCipher release artifacts for Apple M1 Silicon

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4352]
Our scripts for building NSS and SQLCipher for iOS targets currently only support arm64 hardware and x86_64 simulator. We'll need to update them to also build for aarch64 simulator, similar to what we're doing at the Rust level over in [https://github.com/mozilla/application-services/pull/4225](https://github.com/mozilla/application-services/pull/4225).

If we're really very lucky, this will be a simple matter of updating the list of `TARGET_ARCHS` in the `./libs/build-all-ios.sh` script. We're probably not going to be that lucky.

The script currently combines the two architectures into universal libraries under ./libs/ios/universal/. However, we know that universal libraries don't work correctly with M1 simulator builds, and that's why we're doing to work to ship our Rust code as an XCFramework. So...maybe we will actually need to update these scripts to build NSS and SQLCipher as an XCFramework as well?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2706)
┆Epic: Unified a-s swift packages for iOS
┆Sprint End Date: 2021-10-01

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

{quote}The script currently combines the two architectures into universal libraries under ./libs/ios/universal/{quote}

Hrm, actually, I don’t think we use this universal lib even though we build it. If you look in build-scripts/xc-universal-binary.sh you’ll see that when building for iOS, we directly link against the specific architecture builds under ./libs/ios/*/.

**Comment by rfk** [comment]
I did a quick experiment with this on Friday, and it might be easier than I feared. Rust will happily link against the existing `aarch64` libs when building for both the arm64 hardware and the arm64 simulator. But I don't know whether the resulting binaries will actually *run* on an M1, going to need @skhamis's help for that :-)

**Comment by rfk** [comment]
> Rust will happily link against the existing aarch64 libs when building for both the arm64 hardware and the arm64 simulator.
> But I don't know whether the resulting binaries will actually run on an M1.

The resulting binaries do not work; Stefan tried and got the following link-time error:

```
ld: in /Users/stefan/Library/Developer/Xcode/DerivedData/Blockzilla-epioezkoelhffafeakxexqbearav/Build/Products/FocusDebug-iphonesimulator/MozillaRustComponents.framework/MozillaRustComponents(sqlite3.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So, we're going to need to add an explicit third build target for NSS and SQLCipher. The desired outcome will be creation of a new sub-directory under `./libs/ios/` along the lines of:

* `./libs/ios/arm64-sim/nss` <- NSS built for the iPhone simulator
* `./libs/ios/arm64-sim/sqlcipher` <-- SQLCipher built for the iPhone simulator

This will involve figuring out the right build flags for each library, then updating `./libs/build-[nss|sqlcipher]-ios.sh` to add the new target architecture, then updating `./libs/build-all-ios.sh` to build it.

**Comment by skhamis** [comment]
> > Rust will happily link against the existing aarch64 libs when building for both the arm64 hardware and the arm64 simulator.
> > But I don't know whether the resulting binaries will actually run on an M1.
> 
> The resulting binaries do not work; Stefan tried and got the following link-time error:
> 
> ```
> ld: in /Users/stefan/Library/Developer/Xcode/DerivedData/Blockzilla-epioezkoelhffafeakxexqbearav/Build/Products/FocusDebug-iphonesimulator/MozillaRustComponents.framework/MozillaRustComponents(sqlite3.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> So, we're going to need to add an explicit third build target for NSS and SQLCipher. The desired outcome will be creation of a new sub-directory under `./libs/ios/` along the lines of:
> 
>     * `./libs/ios/arm64-sim/nss` <- NSS built for the iPhone simulator
> 
>     * `./libs/ios/arm64-sim/sqlcipher` <-- SQLCipher built for the iPhone simulator
> 
> 
> This will involve figuring out the right build flags for each library, then updating `./libs/build-[nss|sqlcipher]-ios.sh` to add the new target architecture, then updating `./libs/build-all-ios.sh` to build it.

SQLCipher is going away fairly soon with the new logins refactor, wonder how much effort we should put into that basket before the upcoming removal but yes for the NSS I remember doing some stuff for building NSS for M1 on desktop with the TARGET_ARCH here https://github.com/mozilla/application-services/blob/main/libs/build-nss-desktop.sh#L112

**Comment by rfk** [comment]
> SQLCipher is going away fairly soon with the new logins refactor

IIUC we'll need to keep it around for some amount of time in order to migrate data, but it's not clear to me the timeframe there.
