### ISSUE TITLE
Xcode build warnings due to expired Glean metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#4355]
**Edit**: in my initial testing I seemed able to consistently reproduce a build failure due to these warnings, but now I no longer can, so perhaps there was something else at play. I think it's still worth updating Glean to remove the build warnings.

---

Attempting to build our latest `main` via `./build-carthage.sh` produces some Glean warnings:

```
warning: Sorry, Glean found some glinter nits:
warning: WARNING: EXPIRED: glean.time.invalid_timezone_offset: Metric has expired. Please consider removing it.

warning: Please fix the above nits to continue.
warning: To disable a check, add a `no_lint` parameter with a list of check names to disable.
warning: This parameter can appear with each individual metric, or at the top-level to affect the entire file.
```

~~These say they're warnings, but AFAICT they fail the build, and if I apply the fix from https://github.com/mozilla/glean/pull/1697 manually then the build succeeds.~~

~~I wasn't able to find a way to ignore this lint at build time, and the above fix is not yet in a release of Glean. I'm going to try pinning out submodule to that specific commit in order to unbreak the build, but I think we'll need some help from the Glean team on a "proper" fix here.~~

Let's update to a version of Glean that doesn't produce these warnings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2708)

**Comment by rfk** [comment]
So, some questions about how to proceed here:

* Short-term, could we please get a `v39.0.4` or similar release of Glean that includes the fix from mozilla/glean#1697?
* Is it expected that these "expired metrics" warnings should fail the build? Is there something that we should be doing or changing in the setup here to make things more robust against similar issues in future?

**Comment by rfk** [comment]
> Is it expected that these "expired metrics" warnings should fail the build?

Actually, I don't have a full mental model of exactly what's failing here. My local attempts to build fail without mozilla/glean#1697 applied, but builds do not seem to be failing in CI. Perhaps I'm mis-attributing the source of the failure?

**Comment by badboy** [comment]
Looking into it. Will probably get you the release within the day.

**Comment by badboy** [comment]
[v39.0.4](https://github.com/mozilla/glean/releases/tag/v39.0.4) has been cut.

> Is it expected that these "expired metrics" warnings should fail the build? Is there something that we should be doing or changing in the setup here to make things more robust against similar issues in future?

I think these warnings are hard errors right now (I admit it seems to not be perfectly clear from the output). It's intentionally that way, because expired metrics should be removed instead.
It's _usually_ no problem, because these are checked at build time of Glean (for internal metrics like that), but due to the a-s megazord of course the "build time" differs from Glean's "release time".
I don't think in the current setup there's an easy way to ignore those warnings however.

**Comment by rfk** [comment]
@badboy thank you!
