### ISSUE TITLE
Investigate failed build task in v82.0.0 release

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#4367]
The [release commit for v82.0.0](https://github.com/mozilla/application-services/commit/b5d0bc37091f7f418e54283842e7ff2aa5c18c88) had [one failed build task](https://github.com/mozilla/application-services/runs/3187749759) for `module-build-full-megazord`, which errorred out [with the log](https://firefox-ci-tc.services.mozilla.com/tasks/clNP-4JXRjegbZj-RraYgw/runs/0/logs/public/logs/live.log):

```
[task 2021-07-29T02:10:06.939Z] BUILD SUCCESSFUL in 6m 58s
[task 2021-07-29T02:10:06.939Z] 44 actionable tasks: 44 executed
[resource_monitor 2021-07-29T02:10:07.256Z] terminating
[fetches 2021-07-29T02:10:07.301Z] removing /builds/worker/fetches
[fetches 2021-07-29T02:10:07.334Z] finished
[taskcluster 2021-07-29 02:10:07.792Z] === Task Finished ===
[taskcluster:error] Error uploading "public/build/full-megazord-82.0.0-sources.jar" artifact. Artifact already exists with different properties, and none of the allowed exceptions apply: {
  "storageType": "s3",
  "contentType": "application/java-archive",
  "expires": "2022-07-29T01:56:55.152Z"
}
---
* method:     createArtifact
* errorCode:  RequestConflict
* statusCode: 409
* time:       2021-07-29T02:10:09.001Z
[taskcluster:error] Error: Error calling 'stopped' for artifactHandler : Error: Encountered error when uploading artifact(s)
    at Artifacts.stopped (/home/ubuntu/docker-worker/src/lib/features/artifacts.js:218:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at Task.run (/home/ubuntu/docker-worker/src/lib/task.js:973:7)
    at Task.start (/home/ubuntu/docker-worker/src/lib/task.js:700:17)
    at TaskListener.runTaskset (/home/ubuntu/docker-worker/src/lib/task_listener.js:524:9)
    at async Promise.all (index 0)
[taskcluster 2021-07-29 02:10:10.472Z] Unsuccessful task run with exit code: -1 completed in 687.347 seconds
```

This is weird because I don't think this task should be uploading any artifacts, there is a separate `beetmover-full-megazord` task that does that. *That* task claims to have succeeded, and indeed there is a [plausible-looking full-megazord-82.0.0.aar](https://maven.mozilla.org/?prefix=maven2/org/mozilla/appservices/full-megazord/82.0.0/) published to Maven. But I guess "artifacts" here could be referring to "taskcluster artifacts" rather than "maven artifacts".

Trying to build android-components against the new release works OK, so I think the release actually got published successfully.

Probably this is some fallout from my recent refactor of the android gradle scripts, but I'm not entirely sure what.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/SYNC-2710)

**Comment by rfk** [comment]
Notably, this failure did not reappear in the [v82.1.0 release](https://github.com/mozilla/application-services/commit/b0e7775ab12eeb4251f09cdfaab9ddaea22b4438).

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Closing - we can reopen or file new if future builds have issues.
