### ISSUE TITLE
Add security to scripts in the taskcluster Dockerfile

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4369]
Based on the codecov incident, the code in this Dockerfile scares me: https://github.com/mozilla/application-services/blob/main/taskcluster/docker/linux/Dockerfile.  It downloads and runs 3 scripts via curl which seems to open the door for someone to slip in malicious code.  Probably the simplest method would be to verify the checksums of those files, maybe we should rework how that file works in general though.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/SYNC-2711)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866341

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
