### ISSUE TITLE
InternalPanic: sorry, no upgrades yet - delete your db!

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#437]
I just got this after updating the libraries in the reference browser:
> InternalPanic: sorry, no upgrades yet - delete your db!

Full stacktrace: https://pastebin.com/r6dWbn1N

I fully understand that we do not want to write tedious migration code for our development versions. I only wonder how we should deal with that in the reference browser, that interested testers can download (soon from Google Play [internal channel])?

* The library could delete the database itself as long as it doesn't do migrations (instead of the panic).
* Or: We catch `InternalPanic` in `RustPlacesConnection` and just assume this means we should drop the database (until you tell us to stop doing that)

Do you prefer any option? Are there other/better options?

**Comment by pocmo** [comment]
CC @grigoryk

**Comment by grigoryk** [comment]
Work-around in https://github.com/mozilla/application-services/pull/439.
