### ISSUE TITLE
Create state diagrams for push component

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4373]
After chatting with @rfk  (also ref: https://github.com/mozilla/application-services/pull/4347#discussion_r674406962) , it's important for us to create a better understanding of how the different parts of the push system interact. We can get closer to that with state diagrams and how they interact:

* [ ] A state diagram for the states the consumer is in (e.g Fenix), those could be things like "connected", "subscribed to channels", "reconnecting", etc
* [ ] A state diagram for the states the server is in, those could be things like: "UAID Created", "No UAID", "Subscriptions Created", etc
* [ ] (possibly if it's different enough from the consumer) a state diagram for our component!

The examples I put above are in no way complete or completely accurate (which signals that we(well, me!) need a better complete understanding here!)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2714)
┆Story Points: 8
┆Epic: Important backlog
┆Sprint End Date: 2021-09-17

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Mark Hammond I know you are doing a but of send-tab / push expiration investigation for Fenix.  Question for both you & Tarik Eshaq should we consider this as part of the uniffi push epic - so that the uniffi work comes with better docs/understanding.  (don’t want to overload the epic, so push back if I am wrong here)

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Closing as this has gone stale and we’ve done a decent bit of documentation of push, including client state machines in https://firefox-source-docs.mozilla.org/dom/push/index.html ( https://firefox-source-docs.mozilla.org/dom/push/index.html|smart-link )
