### ISSUE TITLE
Schema migrations for places

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#438]
We're starting to publish the reference browser to internal consumers. https://github.com/mozilla/application-services/issues/437 will introduce a quick hack-around to avoid app crashes (if migration was necessary and we panicked, drop db file on the floor and try again), but we'll need to pick a point where writing migrations is worth the effort.

**Comment by thomcc** [comment]
This got done in https://github.com/mozilla/application-services/pull/590
