### ISSUE TITLE
Update logins enum in android-components to use the new complex structure

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4390]
Due to a previous limitation in Uniffi we had to use the message as the enum given that errors were flat structures at the time. Now with the latest version of uniffi we can actually pass the rich errors down.

The area in question is here: https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/DefaultLoginValidationDelegate.kt#L85-L88

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2733)
┆Story Points: 2
┆Epic: a-s storage components (backlog)
┆Fix Versions: Release 94
┆Sprint End Date: 2021-10-29

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866507

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
