### ISSUE TITLE
Resolve Andriod Components breaking changes with push uniffied

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4425]
Once the uniffication of push is done, we should have a PR up in android components that resolves any breaking changes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2764)
┆Story Points: 5
┆Epic: Uniffi Push Component
┆Fix Versions: Release 94
┆Sprint End Date: 2021-09-17

**Comment by tarikeshaq** [comment]
This is done with https://github.com/mozilla-mobile/android-components/pull/10953 🎉 🎉
