### ISSUE TITLE
autofill doesn't use WAL mode

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4435]
I noticed `PRAGMA journal_mode=WAL;` doesn't appear to be set for autofill. Assuming I'm not dreaming, I believe that's probably an oversight.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2771)

**Comment by lougeniaC64** [comment]
@mhammond Are there any other pragmas that  should be initialized? Looking at [places](https://github.com/mozilla/application-services/blob/03f8418f3856dd0470fb36664dd0dfef30ab1f5a/components/places/src/db/db.rs#L49) and [webext](https://github.com/mozilla/application-services/blob/6fa7bad7f176ddf5da74ca10edbe873f2d7416b9/components/webext-storage/src/schema.rs#L22), I was wondering about `cache_size`, `page_size`, `temp_store`, `wal_autocheckpoint`\`wal_checkpoint`.

**Comment by mhammond** [comment]
> Are there any other pragmas that should be initialized?

Probably :) Many of the places one came from desktop places which has been extensively tuned - but it's not clear how many params are tuned specifically to the places workload, or whether they make sense generally. It would be great to document some of these (ie, summarize which ones we use in a single place which cross-references the sqlite documentation) so we can be more deliberate here.
