### ISSUE TITLE
Create separate build repo for more flexible releases

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4456]
We should create a separate repo to build the application services for consumption by android-components with the following features:

  - It should support specifying different versions for each component.  This would help with the following scenario: 
    - Android-components is currently using version 100 of all a-s components.
    - Application-services is currently working on version 101 in main, but it's not ready to be released. 
    - However, version 101 of logins is ready to be released and it contains a fix that android-components wants now
    - In this situation we would want to create a build where all components are on v100, except logins which is v101
  - It should run the unit tests to verify that everything is compatible when mixing versions.  For example things could break in the above scenario if logins v101 had a dependency on sync15-traits v101.
  - We should make this compatible with our goal of potentially getting a-s components into mozilla central / libxul.so (this would allow us to use glean).
  - We should allow firefox-ios and other consumers to also use the same system, although I don't think we need implement that on the first pass.
  - Allow for testing with this repo.  For example this week I would have loved to taken the v82 release, changed the logins  to `logins-per-field-encryption` and tested that with android-components/fenix.

I think this repo could be fairly simple:
  - An INI file that specifies a git tag/branch/commit  for each component
  - A python script that checks out the required a-s commits, then assembles a build based of the INI file.
  - Each branch specifies a particular megazord:
     - One branch would be for the version currently used an a-c
     - We would create a branch for testing the next version to be used for a-c
     - We could create a branch for testing the next version of a specific component.
     - We could have branches for other consumers.  Maybe we would have a firefox-ios branch that only specified the components they needed.  I'm not sure how this would integrate with the current swift packaging work though.
  - We would also need to update the release process to use this repo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2780)

**Comment by bendk** [comment]
@mhammond Does this seem like it would work for what we want?  We also definitely need to run it past the people implementing sharing-rust-libraries and the a-c team, but I think the first question is if it would address our needs.

**Comment by mhammond** [comment]
I think it would work, but it seems like we are closer than ever to working with geckoview and glean, so wouldn't we be better spending effort in that direction? Best I can tell, there's nothing actually blocking us from starting that work today?

**Comment by bendk** [comment]
My idea is that this would work together with that.  Maybe the output of this repo is what gets vendored into into moz-central.

However, I'm realizing that it's more complicated because what happens when we make a breaking change?  If we just push that into moz-central, then that's going to break things until a-c pushes their update.  I'll try to follow up to see how Glean handles this, but my worry is that they handle it by having a deprecation schedule which seems like overkill for us.

**Comment by mhammond** [comment]
>  Maybe the output of this repo is what gets vendored into into moz-central.

Whoa - that sounds complicated!

Re breaking changes: It might just mean more formal coordination between the teams. For example, we will still be able to commit breaking changes into our repo whenever we like, it's just that vendoring into m-c that will need to be coordinated with the thing that "unbreaks" it.

ISTM that the general problem must exist for Geckoview too - breaking changes in gecko need to be handled in some way and seems like the exact same problem? I see you started a convo in slack about this, which is great, thanks!

**Comment by bendk** [comment]
> Whoa - that sounds complicated!

It does.  But, from what I understand, the way that the Glean code gets into moz-central is they just copy it all in as part of their release process.  If we wanted to support a cherry-picking different versions of each component, then this seems like one of the simpler ways to do it.  OTOH, it also makes me reconsider the branch-based approach.  We could have a `production` branch, which holds the code that's currently in moz-central.  If we wanted to backport an update for a particular component, then we could either cherry-pick or use git checkout to copy the entire directory from main.

**Comment by mhammond** [comment]
> If we wanted to support a cherry-picking different versions of each component, then this seems like one of the simpler ways to do it.

mozilla-central tooling already has support for `mach vendor rust` - so what you describe sounds like the same thing but with extra steps. Maybe it's worth bumping the few components we do have already vendored so that the process is better understood?

**Comment by bendk** [comment]
This is feeling pretty complicated to me too and I'm going to close it.
