### ISSUE TITLE
Data review for logins component migration

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4467]
In #4064, #4102 and others, we want to record metrics to track the reliability of the migration process.  [The glean yaml can be found here](https://github.com/mozilla/application-services/blob/logins-per-field-encryption/components/logins/android/metrics.yaml#L118)

1) What questions will you answer with this data?

**How successful (or otherwise) the migration from sqlcipher to sqlite is for logins on mobile.**

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

**Establish baselines or measure changes in product or platform quality or performance.**

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

**No alternatives were identified**

4) Can current instrumentation answer these questions?

**no**

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>The number of login records we processed, including counts for success and failure of that processing</td>
    <td>interaction and technical </td>
    <td>https://github.com/mozilla/application-services/issues/4064</td>
  </tr>
  <tr>
    <td>The first 20 errors seen during the migration. These will not have PII</td>
    <td>technical </td>
    <td>https://github.com/mozilla/application-services/issues/4064 </td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

**This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/"**

7) How long will this data be collected?  Choose one of the following:

**This is scoped to a time-limited experiment/project until date 2022-06-30**

8) What populations will you measure?

**All channels in all countries in all locales, for Android and iOS**

9) If this data collection is default on, what is the opt-out mechanism for users?

**Standard Firefox telemetry controls**

10) Please provide a general description of how you will analyze this data.

**Look at success and error rates and determine if any corrective action needs to be taken**

11) Where do you intend to share the results of your analysis?

**With the Firefox for Android and iOS teams**

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If 

**No**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2784)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-09-17

**Comment by travis79** [comment]
@mhammond I believe you grabbed the wrong template for the request...  you actually grabbed the one that I'm supposed to fill out. I'd feel a little awkward trying to fill it out for you, but your review looks spot on! ;)

Try this template instead, and then I'm happy to take care of this ASAP:
https://github.com/mozilla/data-review/blob/main/request.md

**Comment by mhammond** [comment]
> @mhammond I believe you grabbed the wrong template for the request.

oops :) Thanks - I updated the comment above.

**Comment by travis79** [comment]
> In #4064, #4102 and others, we want to record metrics to track the reliability of the migration process. [The glean yaml can be found here](https://github.com/mozilla/application-services/blob/logins-per-field-encryption/components/logins/android/metrics.yaml?rgh-link-date=2021-09-15T06%3A38%3A10Z#L118)
> 
>     1. What questions will you answer with this data?
> 
> 
> **How successful (or otherwise) the migration from sqlcipher to sqlite is for logins on mobile.**
> 
>     1. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
> **Establish baselines or measure changes in product or platform quality or performance.**
> 
>     1. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> **No alternatives were identified**
> 
>     1. Can current instrumentation answer these questions?
> 
> 
> **no**
> 
>     1. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> The number of login records we processed, including counts for success and failure of that processing 	interaction and technical 	https://github.com/[/issues/4064](https://github.com/mozilla/application-services/issues/4064)
> The first 20 errors seen during the migration. These will not have PII 	technical 	https://github.com/[/issues/4064](https://github.com/mozilla/application-services/issues/4064)
> 
>     1. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> **This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)"**
> 
>     1. How long will this data be collected?  Choose one of the following:
> 
> 
> **This is scoped to a time-limited experiment/project until date 2022-06-30**
> 
>     1. What populations will you measure?
> 
> 
> **All channels in all countries in all locales, for Android and iOS**
> 
>     1. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> **Standard Firefox telemetry controls**
> 
>     1. Please provide a general description of how you will analyze this data.
> 
> 
> **Look at success and error rates and determine if any corrective action needs to be taken**
> 
>     1. Where do you intend to share the results of your analysis?
> 
> 
> **With the Firefox for Android and iOS teams**
> 
>     1. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If
> 
> 
> **No**
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2784)
> ┆Epic: Logins update and sqlcipher migration
> ┆Sprint End Date: 2021-10-01

# Data Review 

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the Glean Dictionary

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the control mechanisms provided by the consuming applications

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection to end or be renewed by 2022-06-30

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1 & 2

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+
