### ISSUE TITLE
Figure our startup cases with the sqlcipher migration

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4470]
We need to figure out how to handle a handful of cases when doing the sqlcipher migration

- Who decides when we need to migrate?`  Does the app always call the migration function or only when the old DB file exists?
- What happens on migration errors?
  - Do we delete the old file or move it somewhere?
  - Do we log/report the error?  How?
  - Does "we" mean a-s or the consumer code?
- What happens if the app crashes in the middle of the migration?  I think this means that on startup both the old and new files will be present.  Does a-s or the consumer code detect this case?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2785)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-09-30

**Comment by mhammond** [comment]
Thoughts off the top of my head:

* I was thinking the app can try to load its sqlcipher key and if it exists, migrate then delete the encryption key.
* We should delete the file after migration.
* Both files existing is a failure case - the app still has a key, so tries to migrate, we silently fail to migrate, app then deletes its key, so considers that success (although user probably has lost data)

**Comment by mhammond** [comment]
(the above kinda implies we should delete the sqlcipher database in all migration paths, even failure)
