### ISSUE TITLE
Implement canary logic for the encryption key

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4471]
Pulled from [this comment ](https://github.com/mozilla/application-services/blob/501c31ba2d460adddbaeba6efc7313b5dab0c228/components/logins/src/logins.udl#L30)in the UDL file:

we still need some way to have a "canary" for the encryption_key - eg, to ensure a given key is the correct key for the DB. `autofill` consumers do this by just encrypting some arbitrary string and storing the ciphertext, and as the app starts and the ciphertext is loaded, it checks the string decrypts. However, we don't otherwise need encryption and decryption of arbitrary strings. An alternative is we expose a specific `check_canary` or similar function, and we manage storage of the strings etc in our meta table?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2786)
┆Story Points: 5
┆Epic: Logins update and sqlcipher migration
┆Fix Versions: Release 95
┆Sprint End Date: 2021-09-30

**Comment by skhamis** [comment]
Hmm I'm trying to make sense of this in the logins context, since either we can decrypt the login or it'll fail and we'll bubble the appropriate error? Is this comment still valid & need to be implemented @mhammond?

**Comment by mhammond** [comment]
The canary idea came from autofill's idea - the main point of that is to know when it is invalid. Another alternative is to have exception handlers at every place we do encryption/decryption and make sure it does the recovery, but that seems error prone? I think what autofill does is check the canary immediately after obtaining the encryption key from the OS.

Totally open to any solution that notices and handles the key failure though, but I think that strategy is on us to decide and implement - eg, we can't just handwave that the app should handle it.

**Comment by mhammond** [comment]
(for more context, [here is how the canary for autofill is done in a-c](https://github.com/mozilla-mobile/android-components/blob/823681c77194b0a87e64484b43d14d7d9c889ccf/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCrypto.kt#L100)

**Comment by skhamis** [comment]
Ah okay appreciate the context, this makes more sense the body of work this entails -- thanks!

**Comment by mhammond** [comment]
(and to be clear, I haven't thought this through in any meaningful way other than "I think we need this in some shape or form" - eg, a canary in our DB probably *does not* make sense, as otherwise they would need to pass the key when opening the DB to have it work like autofill. What *might* work is an explicit `check_key()` or similar function on the store? I've no real opinion on how this is best spelt)

**Comment by mhammond** [comment]
It was @grigoryk who advocated for this capability in autofill, so he may have thoughts.
