### ISSUE TITLE
Update firefox-ios to use the new swift packages instead of binary files

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4477]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2790)
┆epic: local development, ci and release (backlog)
┆sprintEndDate: 2021-11-24

**Comment by skhamis** [comment]
(Posted above to keep a history of the failures that went into this)

Library not loaded issues fixed explained here: https://github.com/mozilla-mobile/firefox-ios/pull/9263#issuecomment-940611130

**Comment by data-sync-user** [comment]
➤ Sammy Khamis commented:

Based on a team meeting with the FxiOS team. We got them a good distance to the goal line here but there will be some cleanup and rethinking of certain structure in the app before they push this over the line. Application Services will move into a supporting capacity as they work to remove Carthage. However as for what’s required from a-s at this time is complete and will be marked as so.
