### ISSUE TITLE
Replace lipo command with xcodebuild

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4478]
Right now, we essentially custom build our XCFramework zip file using the lipo command. While this is not an issue per say, The “standard” command to build XCFramreworks is `xcodebuild` as done by glean [https://github.com/mozilla/glean/blob/0104274b9f9080b8e6af132bbe2d0a5d645fd38f/bin/build-xcframework.sh#L21](https://github.com/mozilla/glean/blob/0104274b9f9080b8e6af132bbe2d0a5d645fd38f/bin/build-xcframework.sh#L21|smart-link) 

Note: This is more of a research task in if we can prevent as much manual builds as possible – we might need to keep lipo around for combining uniffi builds before we XCFramework but worth to poke around and investigate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2792)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866340

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
