### ISSUE TITLE
Update webext storage on moz-central

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4495]
Vendor in the newest version of webext storage into moz-central.  This will be nice since it has the new database corruption handling, but the real reason to do it is so I can get some experience in using `mach vendor rust`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2797)
┆Story Points: 1
┆Sprint End Date: 2021-09-30

**Comment by mhammond** [comment]
I think I worked out roughly what's going on here, so opened bug 1734538.

**Comment by bendk** [comment]
webext storage has been updated fairly recently (https://hg.mozilla.org/mozilla-central/rev/12ee41f70894e7a9ee03458bb554aecd9d0016ea), so I think we can close this.
