### ISSUE TITLE
Investigate a new uniffi command that can spit out all the generated headers for a uniffi-ed crate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4508]
From the file build-xcframework.sh:
https://github.com/mozilla/application-services/blob/e1abe5ad61983f00a8abf1b477afa5470876e484/megazords/ios-rust/build-xcframework.sh#L136-L139

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2803)
┆Epic: Unified a-s swift packages for iOS

**Comment by skhamis** [comment]
Created this in the wrong repo (via jira)
