### ISSUE TITLE
Issues when running fxa-client + sync-logins on Android 6

### ISSUE THREAD

**Issue by sashei** [mozilla/application-services#451]
Disclaimer: I don't have a physical device to test this on, but we've had other reported issues with Android 6.0 devices running Lockbox (see issue https://github.com/mozilla-lockbox/lockbox-android/issues/243).

I'm getting a 500 error whenever attempting to login on an Android 6 emulator, both in Lockbox and using the `sync-logins` sample app from android components. I found y'all's issue #197 and wanted to let y'all know that the issue hasn't been resolved for us, or in the android components samples :(

**Comment by sashei** [comment]
To surface the logcat from our build a little more, the relevant error that @bsurd is experiencing has the following log:
```
11-28 11:04:18.028 16889 16889 E AndroidRuntime: Caused by: mozilla.appservices.logins.LoginsStorageException: Error executing SQL: unable to open database file

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:47)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at mozilla.appservices.logins.DatabaseLoginsStorage.unlock(DatabaseLoginsStorage.kt:191)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at mozilla.lockbox.store.DataStore.unlock(DataStore.kt:106)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at mozilla.lockbox.store.DataStore$2.accept(DataStore.kt:69)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at mozilla.lockbox.store.DataStore$2.accept(DataStore.kt:22)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)

11-28 11:04:18.028 16889 16889 E AndroidRuntime: 	... 22 more
```

**Comment by vladikoff** [comment]
@grigoryk is this the same error as ref browser?

**Comment by ncalexan** [comment]
This log doesn't suggest the same issue from #197: there's nothing about being unable to find or open the library `.so`.  But it does look like the issue that @grigoryk saw around file locations: 
```
11-28 11:04:18.028 16889 16889 E AndroidRuntime: Caused by: mozilla.appservices.logins.LoginsStorageException: Error executing SQL: unable to open database file
```
That looks like we're loading SQL/SQLcipher but actually unable to read the DB file.  I've seen that if we fail to make the parent directories locally, but doubtless there are other ways to hit that.

**Comment by mhammond** [comment]
I believe the change in question is https://github.com/mozilla-mobile/android-components/commit/5a35bedd530111d9d2da57672c64b8aa59555a5a - @grigoryk changed from using `context.getDatabasePath()` to `context.filesDir`. Maybe this same change needs to be made at https://github.com/mozilla-lockbox/lockbox-android/blob/master/app/src/main/java/mozilla/lockbox/support/FxASyncDataStoreSupport.kt#L62?

**Comment by rfk** [comment]
From triage: needs feedback from lockbox team on whether this is still happening; /cc @sashei

**Comment by rfk** [comment]
From lockbox sync-up: we believe the issue here is lockbox passing a non-existent path, nothing for us to do on the a-s side. Closing out here.
