### ISSUE TITLE
Delete history metadata by search term

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4515]
In order to better support removal of search term groups, it'll be nice to have a "delete all metadata that matches searchTerm" API.

For now, we'll do this in A-C for the sake of expediency, but it's much better suited for A-S.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2805)
┆Epic: History Metadata Storage & Sync

**Comment by grigoryk** [comment]
API we landed in A-C - https://github.com/mozilla-mobile/android-components/pull/11058

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866342

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
