### ISSUE TITLE
Build and publish places as a swift package

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4518]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2806)
┆Epic: Unified a-s swift packages for iOS
┆Sprint End Date: 2021-10-15

**Comment by skhamis** [comment]
Places wasn't able to be easily converted into a swift package likely due to the existing FFI functions that still exist and will need to include some kind of protobuf for it to build correctly.
