### ISSUE TITLE
sync_manager::manager: engine "passwords" status: Err(Error(Store error: local encryption key not set))

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4523]
Testing during logins feset: 

sync_manager::manager: engine "passwords" status: Err(Error(Store error: local encryption key not set))

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2808)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-10-15

**Comment by bendk** [comment]
The issue here is we weren't setting the encryption key properly on fenix/android components.  I updated both of those branches to do this and the error is fixed for me.
