### ISSUE TITLE
Error syncing on android: Store error: Error executing SQL: no such column: username)

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4524]
I'm seeing this issue when I try to sync in my emulator:

```
sync_manager::manager: engine "passwords" status: Err(Error(Store error: Error executing SQL: no such column: username)) 
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2809)
┆Epic: Logins update and sqlcipher migration
┆Sprint End Date: 2021-10-15

**Comment by bendk** [comment]
My guess is that it's happening because of this line, which refers to the old username column:  https://github.com/mozilla/application-services/blob/logins-per-field-encryption/components/logins/src/sync/engine.rs#L388-L395

To further speculate, I think that function is called when we get a completely new sync record.  Something that's not currently in the mirror or local tables.

**Comment by skhamis** [comment]
On iOS

```
2021-10-04 13:00:30.947 [Warning] [Profile.swift:311] init(localName:syncDelegate:clear:) > [RUST][sync15::sync_multiple] Sync of passwords failed! Error(Store error: Error executing SQL: no such column: username)
```
