### ISSUE TITLE
Publsh glean as a swift package using rust-components-swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4550]
Currently, Glean is exposed only as a dependency of Nimbus, which means consumers of our packages can only get glean if they also include Nimbus. This ticket is to expose glean as an independent library. In practice, this means replacing what the glean-swift repository does: https://github.com/mozilla/glean-swift

One thing to keep in mind is how versioning will work, every time glean releases a new release, we should update our release of `rust-components-swift`, but this means that `rust-components-swift` can't follow the release versions of application services. A couple of options I'm thinking about:

* Don't automate glean releases independently, instead, whenever an Application Services release happens, we make sure to _also_ pick up the latest glean. This doesn't seem very reasonable to me, I'm sure there will be cases where we would want to **only** update glean, and we don't want to be forced to cut an application services release just for that
* Don't couple the release versions of `rust-components-swift` with application services, so whenever glean makes a release, we bump our version of `rust-components-swift` and do the same thing when application services cut a release.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2822)
┆Story Points: 3
┆Epic: Unified a-s swift packages for iOS
┆Sprint End Date: 2021-10-15

**Comment by tarikeshaq** [comment]
This was cancelled on Jira, closing
