### ISSUE TITLE
Intermittent services/sync/tests/unit/test_extension_storage_engine.js | test_engine - [test_engine : 253] {} deepEqual {"foo":"bar"} | xpcshell return code: 0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4553]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2824)

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}modified by:	csabou@mozilla.com
 resolution:	
 status:	REOPENED
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-10-18 23:15:22
 user:	{'id': 600699, 'login': 'csabou@mozilla.com', 'real_name': 'Cosmin Sabou [:CosminS]'}
 changes:	[{'field': 'status', 'removed': 'RESOLVED', 'added': 'REOPENED'}, {'field': 'resolution', 'removed': 'INCOMPLETE', 'added': ''}]
 target:	bug
 routing_key:	bug.modify:status,resolution
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(releasemgmtaccount-bot@mozilla.tld) commented: 
{quote}https://wiki.mozilla.org/Bug_Triage#Intermittent_Test_Failure_Cleanup
For more information, please visit [auto_nag documentation](https://wiki.mozilla.org/Release_Management/autonag#close_intermittents.py).{quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}modified by:	release-mgmt-account-bot@mozilla.tld
 resolution:	INCOMPLETE
 status:	RESOLVED
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}modified by:	release-mgmt-account-bot@mozilla.tld
 resolution:	INCOMPLETE
 status:	RESOLVED
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-11-16 17:05:09
 user:	{'id': 575867, 'login': 'release-mgmt-account-bot@mozilla.tld', 'real_name': 'Release mgmt bot [:sylvestre / :calixte / :marco for bugbug]'}
 changes:	[{'field': 'status', 'removed': 'REOPENED', 'added': 'RESOLVED'}, {'field': 'resolution', 'removed': '', 'added': 'INCOMPLETE'}]
 target:	bug
 routing_key:	bug.modify:status,resolution
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}modified by:	smolnar@mozilla.com
 resolution:	
 status:	REOPENED
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(smolnar@mozilla.com) commented: 
{quote}Recent failure log: https://treeherder.mozilla.org/logviewer?job_id=360782001&repo=autoland&lineNumber=2978{quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}modified by:	smolnar@mozilla.com
 resolution:	
 status:	REOPENED
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-12-10 11:51:18
 user:	{'id': 670045, 'login': 'smolnar@mozilla.com', 'real_name': 'Sandor Molnar'}
 changes:	[{'field': 'status', 'removed': 'RESOLVED', 'added': 'REOPENED'}, {'field': 'resolution', 'removed': 'INCOMPLETE', 'added': ''}]
 target:	bug
 routing_key:	bug.modify:status,resolution
 {quote}

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866343

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(orangefactor@bots.tld) commented: 
{quote}1 failures in 3319 pushes (0.0 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 1

Platform and build breakdown:

  * linux1804-64-qr: 1
  * debug: 1

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1657038&startday=2021-12-06&endday=2021-12-12&tree=all{quote}
