### ISSUE TITLE
Rename the states in the FxA State Machine

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#456]
The FxA state machine [state names](https://github.com/mozilla/application-services/blob/98831d336c5a2a9f1b3d583d179a831d8876e857/fxa-client/src/login_sm.rs#L159-L181) are somewhere between idiosyncratic and problematic (during this all-hands I heard someone refer to them as 'misogynistic' which is further than I'd go, but it's really just not a great look).

Anyway, they don't describe anything particularly well, and we should just come up with a better set of names.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-87)

**Comment by eoger** [comment]
Agree, note however that the state machine is not being used at the moment (it's behind the `browserid` feature).

**Comment by thomcc** [comment]
Sure, it's still in our repo and worth fixing though.

**Comment by ncalexan** [comment]
I introduced the names (for Firefox for Android), and I personally think they describe things pretty well (i.e., you're engaged before you're married), but clearly they bother some folks, which is reason enough to change them early.  In addition, we have more states now than reasonable names!

**Comment by eoger** [comment]
We killed the state machine recently.
