### ISSUE TITLE
Visual glitch observed when accessing a saved login

### ISSUE THREAD

**Issue by delia-pop** [mozilla/application-services#4564]
Prerequisites
Use an older account and have multiple logins saved.

Steps to reproduce
1. Install and launch the Firefox Preview build 1.0.2142 AC 0.0.1, GV 95.0a1-20211007091917, AS: 85.4.0 debug build.
2. Login with the old account.
3. Access Settings > Logins and Passwords > Saved logins.
4. Unlock your device.  
5. Tap on any saved login and observe the page content.

Expected behavior
After tapping on any saved login, the page content is displayed without any glitches.

Actual behavior
After tapping on any saved login, a visual glitch can be observed, as the page content flickers for a split second.

Device information
Android device: Huawei P9 Lite (Android 8), Google Pixel (Android 10).
Fenix version: 1.0.2142 AC 0.0.1, GV 95.0a1-20211007091917, AS: 85.4.0 debug build.

https://user-images.githubusercontent.com/89388888/137161268-13ddfaeb-224b-455d-82d6-65db4d0ed0be.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2830)

**Comment by mhammond** [comment]
Can you still repro this? If so, do you mind opening a bug in https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix&component=Logins
