### ISSUE TITLE
Grey saved logins icons displayed on Huawei devices for a few seconds

### ISSUE THREAD

**Issue by delia-pop** [mozilla/application-services#4566]
Prerequisites
Make sure to use an old account and have multiple logins saved.

Steps to reproduce
1. Install and launch the latest Firefox Preview build from 10/13 1.0.2142 AC 0.0.1, GV 95.0a1-20211007091917, AS: 85.4.0 debug build.
2. Login with an old account with multiple logins saved.
3. Access Settings > Logins and Passwords > Saved logins.
4. Unlock your device (unlock using pin/pattern).
5. Observe the saved logins icons.

Expected behavior
The saved logins icons are loaded and displayed without issues at all times.

Actual behavior
The saved logins icons display a grey square for several second before completely loading on Huawei devices.
Grey squares icons are displayed after sorting the losings, after returning to the "Saved logins screen" and when scrolling the page.

Android device: Huawei P9 Lite (Android 8), Huawei P20 (Android 10).
The issue is not present on other devices.

Fenix version: latest debug build from 10/13 1.0.2142 AC 0.0.1, GV 95.0a1-20211007091917, AS: 85.4.0 debug build.

https://user-images.githubusercontent.com/89388888/137311087-7bdeb1ec-52bd-4f69-ab09-73e7aa675351.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2831)

**Comment by mhammond** [comment]
Can you still repro this? If so, do you mind opening a bug in https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix&component=Logins
