### ISSUE TITLE
(Nimbus) Organize tests into their own files

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#4572]
We are getting to the point where the test code is far bigger than the code itself. This is a good thing!

However, it is making navigating the code itself hard.

This issue is to split of tests which are testing public API or objects with public API into their own files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2837)

**Comment by venkateshprabhu2** [comment]
Hi. Is this still open? @jhugman

**Comment by eliserichards** [comment]
Sorry @venkateshprabhu2, I am working on this one! 😅

**Comment by tarikeshaq** [comment]
This was done! Thanks Elise!
