### ISSUE TITLE
Clear out form_action_origin and http_realm when deleting logins

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4573]
[In the `LoginsDb.delete()` method, we clear our all sensitive fields.](https://github.com/mozilla/application-services/blob/main/components/logins/src/db.rs#L722-L733).

Origin is considered one of the sensitive fields, I think that should mean that `form_action_origin` and `http_realm` should also be sensitive, since both could be used to identify the site the login was saved for.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2838)
┆Sprint End Date: 2021-10-29

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866509

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
