### ISSUE TITLE
CI doesn't correctly build arm64 binaries for swift packages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4585]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2847)
┆Story Points: 4
┆Epic: Unified a-s swift packages for iOS
┆Sprint End Date: 2021-10-29

**Comment by skhamis** [comment]
Issue discovered here: https://github.com/mozilla-mobile/focus-ios/issues/2600
