### ISSUE TITLE
Build iOS framework with our own sqlcipher/openssl

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#459]
We currently rely on sqlcipher being provided by brew and macos's openssl:
https://github.com/mozilla/application-services/blob/88dc09a0de60ef51ee17553bd6b904e5cf14cfca/.travis.yml#L5
Which means we have no control over the versions of these libraries that get served.
The good thing is, these libs are not being bundled with our framework because we only package fxa-client and it does not currently rely on any of these 2 libraries.
However, logins for iOS is coming and fxa-client's send-tab will also use openssl.
We should use `build-all-ios.sh` instead (should be added by https://github.com/mozilla/application-services/pull/448).

Bonus objective: move the iOS Carthage release workflow to CircleCI.

Blocks https://github.com/mozilla-lockbox/lockbox-ios/issues/580

Requires #567

**Comment by eoger** [comment]
I've pushed the [ios-releases-on-circle](https://github.com/mozilla/application-services/tree/ios-releases-on-circle) branch but have no way to test it: work is currently blocked on getting some macOS machines on CircleCI (@jbuck just sent an email to make it happen).

**Comment by eoger** [comment]
@eoger to test if macos machines are available now

**Comment by ncalexan** [comment]
> I missed this, but that was just to run the tests on darwin.
> 
> I think we're already doing what this issue is filed for, @ncalexan would be more certain though.
> 
> EDIT: this comment is probably very dated, but I don't think we ever used sqlcipher/openssl for the ios frameworks.

To the best of my knowledge we're not cross-compiling from Linux to iOS in automation, which means that whatever we're doing for iOS Frameworks is sub-optimal:
- at best, we link statically against whatever version (of OpenSSL, `Crypto.framework` or whatever it's called, etc) is/are on the build machine
- at worst, we link dynamically against whatever version is/are on the iOS device at runtime

My preference is that we try to cross-compile from Linux to iOS using our existing setup.  It can be very difficult to arrange: if it's too difficult, then we explore alternatives.  This has the advantage of being consistent(-ish) across our targets and providing a lot of control over versions, symbol linkage, etc.  It is, of course, fiddly work that can be hard to roll forward.
