### ISSUE TITLE
Remove cargo audit ignores once chrono advisory is resolved

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4590]
With https://github.com/mozilla/application-services/pull/4589, we added `cargo audit` ignores for two security advisories. This ticket is to remove the ignores

This means one of two things:

* Either remove chrono all together and use `time` directly
* If `chrono` resolves the issue and releases a fixed version, upgrade to that

We should do this once enough time has passed and/or:

* https://github.com/chronotope/chrono/pull/578 is merged
* https://github.com/chronotope/chrono/issues/602 is fixed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2849)
┆Epic: Important backlog

**Comment by jhpratt** [comment]
Note that chrono itself has the same issue, not just transitively via time. Chrono updating to time 0.3 by itself is not sufficient.
