### ISSUE TITLE
Frequent Linux64 asan fuzzing noopt gmake[4]: *** [/builds/worker/checkouts/gecko/config/makefiles/rust.mk:404: force-cargo-library-build] Error 101  | error: could not compile `gkrust`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4594]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2853)

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-10-20 03:41:47
 user:	{'id': 672219, 'login': 'jira-integration@bots.tld', 'real_name': 'Jira Integation Bot'}
 changes:	[{'field': 'see_also', 'removed': '', 'added': 'https://mozilla-hub.atlassian.net/browse/SYNC-2853'}]
 target:	bug
 routing_key:	bug.modify:see_also
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-10-20 03:41:30
 user:	{'id': 75935, 'login': 'ryanvm@gmail.com', 'real_name': 'Ryan VanderMeulen [:RyanVM]'}
 changes:	[{'field': 'cc', 'removed': '', 'added': 'mh+mozilla@glandium.org'}, {'field': 'flag.needinfo', 'removed': '', 'added': '? (mh+mozilla@glandium.org)'}]
 target:	bug
 routing_key:	bug.modify:cc,flag.needinfo
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(orangefactor@bots.tld) commented: 
{quote}5 failures in 2845 pushes (0.002 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * autoland: 4
  * mozilla-central: 1

Platform and build breakdown:

  * linux64-noopt: 5
  * asan: 5

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1710972&startday=2021-10-25&endday=2021-10-31&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(orangefactor@bots.tld) commented: 
{quote}1 failures in 3030 pushes (0.0 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-esr91: 1

Platform and build breakdown:

  * linux64-noopt: 1
  * asan: 1

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1710972&startday=2021-11-01&endday=2021-11-07&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(orangefactor@bots.tld) commented: 
{quote}1 failures in 3259 pushes (0.0 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-release: 1

Platform and build breakdown:

  * linux64-noopt: 1
  * asan: 1

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1710972&startday=2021-11-15&endday=2021-11-21&tree=all{quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

<JBI - Activity Log> 
{quote}action:	modify
 time:	2021-11-22 12:39:17
 user:	{'id': 258347, 'login': 'aryx.bugmail@gmx-topmail.de', 'real_name': 'Sebastian Hengst [:aryx] (needinfo on intermittent or backout)'}
 changes:	[{'field': 'cc', 'removed': 'aryx.bugmail@gmx-topmail.de', 'added': ''}]
 target:	bug
 routing_key:	bug.modify:cc
 {quote}

**Comment by data-sync-user** [comment]
➤ Jira Automation commented:

(orangefactor@bots.tld) commented: 
{quote}3 failures in 2819 pushes (0.001 failures/push) were associated with this bug in the last 7 days.

Repository breakdown:

  * mozilla-esr91: 3

Platform and build breakdown:

  * linux64-noopt: 3
  * asan: 3

For more details, see:
https://treeherder.mozilla.org/intermittent-failures/bugdetails?bug=1710972&startday=2021-11-22&endday=2021-11-28&tree=all{quote}

**Comment by mhammond** [comment]
Haven't seen this for a while.
