### ISSUE TITLE
[fxa client] Add missing profile API fields

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#461]
match all these fields https://github.com/mozilla/fxa-profile-server/blob/master/docs/API.md#response with https://github.com/mozilla/application-services/blob/9438dcd2fd76794ffc717f811c036f71d839b701/fxa-client/sdks/android/library/src/main/java/org/mozilla/fxaclient/internal/Profile.kt#L16

**Comment by eoger** [comment]
We should also detect the empty avatar url (https://firefoxusercontent.com/00000000000000000000000000000000) in https://github.com/mozilla/application-services/blob/9d026ce5fda2d913456c3790671f8d5b428f9da4/fxa-client/sdks/android/library/src/main/java/org/mozilla/fxaclient/internal/Profile.kt#L22

**Comment by mhammond** [comment]
Vlad, is this blocking anyone? ie, can you please triage this :)

**Comment by mhammond** [comment]
@vladikoff , is this blocking anyone? ie, can you please triage this :)

**Comment by linuxwolf** [comment]
FWIW, it would be very helpful to Lockbox to know `defaultAvatar`.  The others might be useful in the future to Lockbox, but are not in the current 12-month plan.

**Comment by rfk** [comment]
From triage: maybe this landed....? @eoger @vladikoff?

**Comment by eoger** [comment]
Yes this landed
