### ISSUE TITLE
Places: switch to using `registerWithSyncManager` on iOS

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4636]
The #4617 PR is approved, but before we merge it, let's make sure that there's at least a PR for iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2881)
┆Epic: Uniffi Places
┆Sprint End Date: 2021-11-11

**Comment by mhammond** [comment]
As @lougeniaC64 pointed out in slack, iOS doesn't (yet!) use it!
