### ISSUE TITLE
Improve the local dev flow for SPM to firefox-ios

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4638]
With the new move to Swift Package Manager. It's very easy to change the URL to point to a PR artifact or new release, however given that firefox-ios has many targets, it's actually a little painful to change all of them to a local copy since it changes to pointing to the file system...

However, all we would really need is some kind of local environment variable to define pointing to the right location and have that consumed by Xcode and thus allowing changing it in one place.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2883)
┆Epic: Important backlog

**Comment by skhamis** [comment]
I know @tarikeshaq and I talked about this but didn't see an official task so wanted to make one to be able to track getting this potentially done
