### ISSUE TITLE
`LoginStore.add_or_update()` can return DuplicateLoginError

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4648]
Fenix beta users are seeing this occasionally (several crashers a day): https://github.com/mozilla-mobile/android-components/issues/11251

It seems to me that add_or_update should never be able to return DuplicateLoginError.  I can think of a couple ways that it might and we should fix those:
  - `update()` can return `DuplicateLoginError` if you're trying to update a login that's already a dupe of another login ([code](https://github.com/mozilla/application-services/blob/main/components/logins/src/db.rs#L516-L519)).  I think we should change that to log a warning and update the login with the GUID that was passed in.
  - `add()` can return `DuplicateLoginError` by design.  Maybe we should change `add_or_update()` to open a transaction and pass that to `add()` to avoid any chance of a login being inserted by another thread between the check and the insert.  I doubt this is happening in practice though, since `LoginStore` has a lock around the entire DB.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2890)
┆Sprint End Date: 2021-11-24

**Comment by mhammond** [comment]
>     * `update()` can return `DuplicateLoginError` if you're trying to update a login that's already a dupe of another login

Yeah, I suspect this is the most likely problem - the user is manually editing a login unaware the future-duplicate exists.

**Comment by mhammond** [comment]
> Yeah, I suspect this is the most likely problem - the user is manually editing a login unaware the future-duplicate exists.

FTR, in #4655 I see that I misunderstood this. I was assuming there was an issue in that there was no duplicate before editing, but the edit made one a dupe - but this case appears to be handled correctly. I think Ben's hypothesis is that there was a dupe before for reasons we don't understand but try very hard to avoid.
