### ISSUE TITLE
Consider updating protobuf version to 3.18+

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4657]
In https://github.com/mozilla-mobile/fenix/issues/22321 we're running into a build issue on M1 macs, which is resolved by upgrading protobuf to a [version higher than 3.18
](https://github.com/protocolbuffers/protobuf/issues/8062#issuecomment-953284983). I think we need to keep protobuf version we depend on in-sync between Fenix and A-S, hence this issue. However, going from 3.11.4 to 3.18.0 is a good year+ worth of releases with lots of changes, so who knows what new and exciting things will go wrong!

(In the short-term, we could rely on the workarounds suggested in https://github.com/mozilla-mobile/fenix/issues/22321).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2898)

**Comment by mhammond** [comment]
I think this makes sense if it gets you out of a pickle in the short term, but once we finish uniffi-ing places we can drop that dep entirely!

**Comment by grigoryk** [comment]
I'll be happy to see it go away :)

**Comment by mhammond** [comment]
Looks like this was done by https://github.com/mozilla-mobile/fenix/pull/22466
