### ISSUE TITLE
Connect shared HTTP abstraction to GeckoView's Necko

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#466]
This is follow-on to #348.  That issue tracks abstracting HTTP access behind a facade; this ticket tracks making one of the facade implementations use the JVM to access GeckoView's lifecycle management and Necko API (introduced in [Bug 1405081](https://bugzilla.mozilla.org/show_bug.cgi?id=1405081)).

This is a "facade sibling" to #205.

**Comment by rfk** [comment]
From meeting just now, it sounds like we may want to connect it to the android-components "fetch" facade rather than directly to GeckView's Necko.  So from our perspective we'd end up calling:

`[a-s fetch facade] -->  [a-c fetch facade] -> [GeckoView fetch]`

**Comment by thomcc** [comment]
Not a huge fan of going through java/a-c here. It adds a *lot* of overhead, complicates the lifetime management in ways we can't statically check, etc.

It's certainly doable, but the other option would be to call necko more directly, which takes a bit of legwork but is probably doable too. It would also have the benefit of being much closer to how we'd do things in a future implementation targeting desktop.

Additionally it would give us a path forward for avoiding the overhead in the current cases where we go from geckoview => java => rust (for example, when geckoview would like to find out which of a list of URLs have been visited before, there's at least 10 *completely redundant conversions*).

**Comment by rfk** [comment]
> It's certainly doable, but the other option would be to call necko more directly

I wonder if we would run into any of the issues of memory-management across different shared libs, that we were worried about for the fxa/send-tab case.

Or I guess we could try to megazord GeckoView :-)

**Comment by thomcc** [comment]
> I wonder if we would run into any of the issues of memory-management across different shared libs, that we were worried about for the fxa/send-tab case.

Probably not. The issue isn't calling across different shared libraries, it's having them free objects that were allocated in one library's heap in the other's heap. Given that the gecko objects are completely foreign to Rust, even if we were a single library it would be completely broken for us to try to free them without calling the proper destructor.

E.g. with fxa/send-tab, there were two copies of the 'proper destructor', one in each lib. Making rust call the right one is possible, but not trivial without re-implementing part of something like `Box<T>`, and carrying the pointer to the dtor around. In this case there's only one copy of the destructors in question.

**Comment by rfk** [comment]
> Not a huge fan of going through java/a-c here. It adds a _lot_ of overhead,
> complicates the lifetime management in ways we can't statically check, etc.

To ensure I'm caught up on the latest context here, @ncalexan is it still your position that we need to route out through the JVM to get to what's exposed in GeckoView, rather than trying to talk directly to the GeckoView native code?

**Comment by ncalexan** [comment]
> > Not a huge fan of going through java/a-c here. It adds a _lot_ of overhead,
> > complicates the lifetime management in ways we can't statically check, etc.
> 
> To ensure I'm caught up on the latest context here, @ncalexan is it still your position that we need to route out through the JVM to get to what's exposed in GeckoView, rather than trying to talk directly to the GeckoView native code?

Yes.  This is my position, but only because @snorp convinced me so.

If we try to drive Necko/Gecko from Rust, we end up duplicating a huge amount of stuff that GeckoView's `GeckoThread` does: preparing libraries, initializing environments, process management, coordinating Android event loops... there's a lot of things here.  Fine, suppose we do that.  Somebody has to do that first: if it's GeckoView, how do we coordinate with a _running_ Gecko?  If it's us, how do we _upgrade_ so that GeckoView can take over the running Gecko?  It's a nightmare: better to piggy-back on the existing startup process, which already accepts delayed/queued calls to Gecko until the initialization is in a good state, etc.

**Comment by thomcc** [comment]
FWIW I agree even though I wrote that. Even though I'm not a fan of it, it's likely too much work to consider going about this a different route than calling through a-c (given that we're not in mozilla-central / part of libxul, at least).

Still a lot of headaches though.

**Comment by rfk** [comment]
Nominating this for April milestone, since we've received pretty clear instructions to consider it a blocker for beta.

If it turns out to be a can of worms, our Plan B should be to connect it to the system networking stack (via javax.net.ssl.HttpsURLConnection or similar) which is still preferable to the current setup.
