### ISSUE TITLE
Logins poison errors since per-field encryption landed.

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4661]
as reported by @grigoryk eg, https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14927128 and https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14011601

Sadly, both of these are just a symptom of some other, as yet unknown error, which will be a panic while our mutex is held. Once that happens, all future attempts to use our APIs will result in a PoisonError like the links above - but it's not the code causing the PoisonError that we need to solve, it's the underlying panic.

Only 16 users so far, but we should try and nail this down.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-2901)
┆sprintEndDate: 2022-02-04

**Comment by mhammond** [comment]
I wonder if the panics are actually making it to sentry - eg, https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=device.family%3A%22IN2013%22+logins

This is all events for a fairly obscure device - 8 events in total, 3 of which are these poison errors, and none of the others look like they should poison the mutex.

**Comment by mhammond** [comment]
ah ha - [this report](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12635627/) is pointing at [this sync code](https://github.com/mozilla/application-services/blob/249e718decb6c5db82fd792f5c9f5968d4235612/components/logins/src/sync/merge.rs#L164-L169)

**Comment by bendk** [comment]
I made #4667 for that particular piece of code.

**Comment by Amejia481** [comment]
@mhammond and @bendk 👋🏽 
Just to make you aware that we have some new reports of this issue:
https://github.com/mozilla-mobile/fenix/issues/22910

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

We believe this is fixed with a-s 86.2.2 - the main source of panics which cause poison errors.

a-s 87.1.0  will have the “parking-lot” change which will fix the remainder of the errors - is in nightly.
