### ISSUE TITLE
Sync manager panic: index out of bounds

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4662]
[this report](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12007622) says `ffi_support::error - Caught a panic calling rust code: "index out of bounds: the len is 2 but the index is 2"` - calling `SyncManager::sync` but no further info.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2902)

**Comment by bendk** [comment]
It's really hard to tell how often this is happening because it's getting grouped with other issues in Sentry.  It seems like switching sync manager to uniffi might fix this error or at least make it easier to debug.  Once we do that, I don't think there will be any `ffi_support` dependency.

**Comment by mhammond** [comment]
We haven't seen this recently, sync manager has since moved to uniffi and parking_lot, so I think we can close it.
