### ISSUE TITLE
Add a  proguard-rules-consumer rule to never strip appservices code

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#4664]
When debugging https://github.com/mozilla-mobile/focus-android/issues/5879, we realized that all consumers of app services need to know to add these proguard rules to avoid unnecessary stripping of bytecode which the Android optimizer thinks is unused:

```
-keep class mozilla.appservices.** { *; }
```

Instead of requiring each app to know this, we could add it into the `consumer-proguard-rules.pro` so that clients of app services get this rule for free.

cc: @jhugman

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2903)

**Comment by tarikeshaq** [comment]
Moved to bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1889968
