### ISSUE TITLE
Rework `fetch_login_data()`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4668]
This function seems unnecessarily complex and we should simplify it.  Some issues to address:
  - Do we need a macro to set the local/remote logins?
  - Can we create an SQL query that's less fragile and doesn't have the possibility of errors like #4667?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2906)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866345

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
