### ISSUE TITLE
Leave sentry "breadcrumbs" when we sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4672]
It would be good to see if we are syncing when a particular event occurs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2909)
┆sprintEndDate: 2022-05-27

**Comment by bendk** [comment]
#4979 has code to do this.  It reports a breadcrumb when we start and stop syncing and also sends the engine list when we calculate it.
