### ISSUE TITLE
Bring application services docs up to date

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4676]
A bunch of our docs are outdated, and when placed on the website they point to dead links.

This is a task to audit the docs and bring them up to date.

To be specific, this is only for the docs that live on https://mozilla.github.io/application-services/book/index.html, and to be even more specific, I am setting the intended audience as someone new to the team/wants to contribute to the project.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2913)
┆Story Points: 5
┆epic: FxA Ecosystem (backlog)
┆sprintEndDate: 2021-12-10

**Comment by tarikeshaq** [comment]
#4671 is a first pass at this, I'll go back, rebase and cover more docs

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Closing - we did a nice pass to update some docs and I’ve moved on to other things.. There’s one more piece I’d like to go back to, which is creating consumer-facing docs (i.e Kotlin/Swift docs) I’ll file a follow up for that and get back to it when I have more capacity
