### ISSUE TITLE
Track missing scoped keys in fxa-client

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4678]
Let's try to detect one theory for mozilla-mobile/android-components#8527: The server is returning a response with missing scoped keys.  In `fxa-client`.  If we request the `https://identity.mozilla.com/apps/oldsync` scope, we should get a corresponding scoped key.  If not, then let's call `log:error!` which will result in a sentry report.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2914)
┆sprintEndDate: 2021-11-24

**Comment by mhammond** [comment]
> The server is returning a response with missing scoped keys

I'm quite skeptical of that, as IIUC, desktop uses the same mechanism. (I don't object to the check though as it can't hurt)

**Comment by bendk** [comment]
Yeah that's probably true, but we can hope at least and eliminate one of the possibilities. 

BTW, @tarikeshaq pointed out that the code isn't actually checking the scoped keys against the requested scopes.  It's checking them against the scopes in the response.  So if this doesn't result in any sentry hits, there's still one more possibility: we're requesting the sync scope, but the scope is missing from the response along with the scoped key.

**Comment by mhammond** [comment]
well, that patch did have sentry hits!

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16167956 and a few others have "Sync scope granted, but keys_jwe is None". I can't see hits for the log of "Sync scope granted, but no sync scoped key ..." though. Not sure what that actually means yet though!
