### ISSUE TITLE
Overhaul readme.md

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#469]
It's a bit out-of-date, @vladikoff suggested during the all hands to have something similar to what's on the android-components repo.

**Comment by vladikoff** [comment]
👍 👍 👍

**Comment by vladikoff** [comment]
> Overhault

Overholt readme.

**Comment by eoger** [comment]
We need more Andrew in there.

**Comment by eoger** [comment]
The README is in a good state now.
