### ISSUE TITLE
Analyze logic around `connUseAfterApiClosed` error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4690]
The [connUseAfterApiClosed error](https://github.com/mozilla/application-services/blob/places-uniffication/components/places/ios/Places/Places.swift#L20) is declared in our swift code but may not be necessary. On the kotlin side, we let the null-pointer error bubble up instead of throwing a custom error, which may be the approach we want to take in the swift code. Ultimately we want to uniformly handle attempts to use a closed or missing connection for both consumers while also reducing the logic in our swift and kotlin wrapper code where possible. This ticket represents the work required to analyze how the places consumer code handles these connection errors and define an approach for refactoring it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2926)
┆Epic: Places Follow-on Work

**Comment by remote007** [comment]
Hey @data-sync-user is this still open to MR ?

**Comment by data-sync-user** [comment]
➤ Sammy Khamis commented:

We should wait on this until the places sqlite issue on iOS is resolved since that’ll only muddy-up the research on this https://github.com/mozilla-mobile/firefox-ios/pull/17031 ( https://github.com/mozilla-mobile/firefox-ios/pull/17031|smart-link )

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866512

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
