### ISSUE TITLE
Audit non-fatal errors for push

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4716]
We recently encountered a bug (see https://github.com/mozilla/application-services/issues/4691) where web push was broken, and the only reason we caught it was because a user reported it. The reason it didn't hit sentry is that there is a list of `non-fatal` errors defined in Android components (see https://github.com/mozilla-mobile/android-components/blob/main/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L364-L373)

This task is to audit those vs the Rust layer and make sure that the errors classified as non-fatal there are safe to ignore, and haven't evolved to include more errors

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2945)
┆Story Points: 3

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Dropping this to the backlog and out of this epic. This ticket doesn’t have the potential to improve our understanding of push, but it’s good to do

**Comment by tarikeshaq** [comment]
This has largely been done when we refactored push before we integrated it into iOS.
