### ISSUE TITLE
Investigate and remove unused Sync APIs and related implementations

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4719]
Investigate the potential removal of these three methods since they don’t seem to be actually used by either consumer. Which also might have something to do with this: [https://github.com/mozilla-mobile/fenix/issues/7227](https://github.com/mozilla-mobile/fenix/issues/7227|smart-link) 

* wipe_local_history
* prune_destructively

May be that we should remove these and discuss a better API that addresses what the consumers need.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2947)
┆Epic: Places Follow-on Work

**Comment by Grubba27** [comment]
That mozilla mobile issue is no showing, can i do this issue ? just remove these methods ?

**Comment by data-sync-user** [comment]
➤ Sammy Khamis commented:

delete_everything_history is used by both iOS and Android and also used under-the-hood for wipe which is also used. I have removed that API from the task but kept the rest! https://github.com/mozilla/application-services/pull/5894 ( https://github.com/mozilla/application-services/pull/5894|smart-link )
