### ISSUE TITLE
Make SyncManager consistent about "logins" vs "passwords"

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4728]
Most SyncManager methods (wipe, reset, etc) use `logins` to specify the logins, but the `sync()` method uses `SyncEngineSelection` which uses `passwords` instead.  Let's pick one and use it consistently.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2955)
┆sprintEndDate: 2021-12-24

**Comment by bendk** [comment]
@mhammond Was there a decision to switch to using "logins" or did it just kind of happen?  I'm thinking that we should just use "passwords", since it's what Fenix uses for `sync()` and I don't think anything is currently calling the `reset()`, `wipe()`, or other methods.

**Comment by bendk** [comment]
I hope that is correct because I went ahead and implemented that in my #4727 PR.  I can back it out though if I'm missing something here.

**Comment by mhammond** [comment]
For years, "passwords" as used in the UI of the browsers - eg "save this pasword" etc. A few years ago, there was a product decision to start calling it logins. "passwords" remains the correct name for the sync engine - the collection on the server is called "passwords", the desktop engine of the engine is in passwords.js, etc. So sadly I'm inclined to thin that PR went the wrong way - as far as sync is concerned, the engine is called "passwords".

**Comment by mhammond** [comment]
> So sadly I'm inclined to thin that PR went the wrong way

Actually, now I look at that PR in more detail, I probably got that wrong. We already had `LOGINS_ENGINE: &str = "passwords";` which is confusing :) I'll comment more in that PR.
