### ISSUE TITLE
[auto-publication] clean up old builds from the local maven repository

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4738]
A mirror of the same issue in A-C: https://github.com/mozilla-mobile/android-components/issues/11413

The patch for A-C simply removes contents of `~/.m2/repository/org/mozilla/components` before publishing. Perhaps the same approach could work here as well (but for `~/.m2/repository/org/mozilla/appservices`)? Need to double-check if every local publication publishes all of the necessary artifacts (in which case, we should be able to just blow away `repository/org/mozilla/appservices`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2969)

**Comment by mhammond** [comment]
SGTM - I rm that dir manually as a matter of course anyway.
