### ISSUE TITLE
After syncing, for all inserted places records visit_count_remote are 0; frecency is 0

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#476]
After I sync, for all records in moz_places I see the following visit_count_remote=0, frecency=0. I do have records in moz_historyvisits, and their visit_types aren't of the excluded sort.

The incorrect frecency could just be a side-effect of a zero visit_count (since we gate frecency computation on the count being greater than 0).

visit_count_remote is supposed to be updated via a trigger, which shoudl fire on insertions into moz_historyvisits.

cc @thomcc @mhammond

**Comment by grigoryk** [comment]
`last_visit_date_remote` is also zero for all synced records (it's supposed to be updated as part of the same trigger which updates `visit_count_remote`).

**Comment by grigoryk** [comment]
Autocomplete suggestions are filtered by `frecency>0`, so this in turn results in only local visits being included in the autocomplete results.

**Comment by thomcc** [comment]
Ugh, sorry about the churn here, `git checkout -b` failed and i didnt notice
