### ISSUE TITLE
[Spike] Compare iOS tabs api and Tabs component

### ISSUE THREAD

**Issue by eliserichards** [mozilla/application-services#4765]
Document the current state of the iOS tabs api(s) and compare it to the AS tabs component.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2988)
┆epic: Tabs component on iOS
┆sprintEndDate: 2022-01-21

**Comment by tarikeshaq** [comment]
iOS now uses our tabs component! closing
