### ISSUE TITLE
Unexpected error: SqlError(InvalidColumnType(0, "score", Null))

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4771]
~https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16154192/~

New Sentry instance link: https://sentry.io/organizations/mozilla/issues/3150733599/

via placesGetHistoryHighlights

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-3000)

**Comment by jonalmeida** [comment]
This is now reproducible as a crash when navigating to a page and adding/removing a bookmark. See video in https://github.com/mozilla-mobile/android-components/issues/12099.
