### ISSUE TITLE
IPv6 loopback in viaduct

### ISSUE THREAD

**Issue by martinthomson** [mozilla/application-services#4775]
https://github.com/mozilla/application-services/blob/74c9db387bce7f6cc142393fd3ad3a985b119259/components/viaduct/src/backend.rs#L47-L49

This could probably use an additional value of "::1" (and maybe variations on that, but that's the obvious one to allowlist here).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3011)

**Comment by Grubba27** [comment]
It would be like this the exemple here is on C# ?
```C#
IPAddress address = IPAddress.Parse("::1");
```

in Rust is ::1 or is 0:0:0:0:0:0:0:1?
```rust
request.url.host_str() != Some("::1");
```

**Comment by martinthomson** [comment]
So the code here is imprecise.  You could do a string comparison and that is probably good enough for many cases.  Or, you could parse the string as an IP address (rust has classes for that) and then compare the result of that.  Your call.

**Comment by Grubba27** [comment]
I would like to make the second one but i would do something like this ? 
```rust
let ipv6_addr = "::1".parse::<IpAddr>();

```

**Comment by martinthomson** [comment]
I think that you can use the IpAddr constructor more directly.  If only for performance reasons.  I think that takes `[u8; 16]`, which you can populate with all zeros, except for a 1 in the last.

**Comment by Grubba27** [comment]
i think i missed some point here 'ive created the first option as this one:
```rust
pub fn validate_request(request: &crate::Request) -> Result<(), crate::Error> {
    if request.url.scheme() != "https"
        && request.url.host_str() != Some("localhost")
        && request.url.host_str() != Some("127.0.0.1")
        && request.url.host_str() != Some("[::1]")
    {
        return Err(crate::Error::NonTlsUrl);
    }
    Ok(())
}

// the test

  let localhost_request_shorthand_ipv6 = crate::Request::new(
            crate::Method::Get,
            url::Url::parse("http://[::1]").unwrap(),
        );
        assert!(validate_request(&localhost_request_shorthand_ipv6).is_ok());
```
the second one that is one the i'm not getting the point:, i should be parsing too the request url ? 
```rust

pub fn validate_request(request: &crate::Request) -> Result<(), crate::Error> {
    let localhost_v6 = IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1));
    if request.url.scheme() != "https"
        && request.url.host_str() != Some("localhost")
        && request.url.host_str() != Some("127.0.0.1")
        && request.url.host_str() != Some(localhost_v6.to_string())
    {

```

**Comment by martinthomson** [comment]
what you have in the first is fine, but it will fail if people use a variant of the spelling of localhost.  "https://[::1]/" is just one spelling that gets you the same answer.  To be clear, this is probably OK as we don't do the same for IPv4, but you won't catch "https://[0::1]", "https://[::0001]", or any of the alternative ways of spelling the same. 

A better options might be to use `request.url.host_str()` (https://docs.rs/url/latest/url/enum.Host.html) and look for the IP address variants.  I think that those have an [is_loopback](https://doc.rust-lang.org/nightly/std/net/struct.Ipv4Addr.html#method.is_loopback) method you can use.

**Comment by Grubba27** [comment]
Created pull request without the second validation that you said :( sorry, it is  almost 01:00 of the night here on Brazil, I'm really sleepy now. Don't know if I will have more time to work on this in this week. thx for all the help you are a great person Martin 👍

**Comment by tarikeshaq** [comment]
fixed in https://github.com/mozilla/application-services/pull/4798 thanks @Grubba27!
