### ISSUE TITLE
Expose is_local for history visits

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4779]
In Fenix, we will be looking at splitting history view into Local vs Synced history.
For that, we will need to expose is_local flag we store alongside our visits.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3019)

**Comment by grigoryk** [comment]
We should aim to do this sometime soon, the A-C/Fenix work is coming up in ~Q1.

**Comment by grigoryk** [comment]
Ideally do this after https://github.com/mozilla/application-services/pull/4770

**Comment by mhammond** [comment]
So we want this in [`HistoryVisitInfo`](https://github.com/mozilla/application-services/blob/2e88010e730a0bec18739ab1be272ad8cd3bbd96/components/places/src/places.udl#L274-L280), meaning `get_visit_infos`, `get_visit_page` and `get_visit_page_with_bound` will expose it. Anywhere else?
