### ISSUE TITLE
Add a function that would delete page visits from timestamp to timestamp

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla/application-services#4781]
On Fenix side, history will squash same urls into a single item in certain time frames.

Let's say, we have a group '30 days'. Every google.com record will be combined into one view item in the list. 

There is also a delete action available for the user. Usually, Fenix would provide a url and a timestamp to delete a record. But because of pagination it might prove to be difficult.

Thus, there is a need for a new method that would delete all the recordings about a specific urls in certain time frame.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3020)

**Comment by grigoryk** [comment]
@mavduevskiy is going to take a stab at this, I'll help him out with code/reviews.

**Comment by grigoryk** [comment]
We'll do this after https://github.com/mozilla/application-services/pull/4770 lands, assuming that's going to land soon-ish? cc @tarikeshaq

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866348

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
