### ISSUE TITLE
Formally define our expectations for X-Weave-Timestamp

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#480]
In conversation with @bbangert about the precise semantics of the sync storage server, we uncovered some under-specified behaviour around the handling of `X-Weave-Timestamp`.  Let's specify it explicitly.

IIUC, the intention of client code is to treat `X-Weave-Timestamp` as a kind of high-water-mark for server changes, so that it can do something like this when its syncing:

```
last_seen = GET_LAST_SEEN_X_WEAVE_TIMESTAMP_VALUE()
r = server.get("/storage/some_collection?newer=" + last_seen)
APPLY_NEW_ITEMS(r.body)
UPDATE_LAST_SEEN_X_WAVE_TIMESTAMP_VALUE(r.headers['X-Weave-Timestamp'])
```

Is this accurate?

If so, ISTM that this is depending on a consistency guarantee that's not actually provided by the server.  It's assuming something like "if I see a value of X-Weave-Timestamp=T, then all items modified on or before timestamp T will be included in the result of this query.  Any changes that weren't included in the result of this query will have a modified timestamp strictly great than T.".

**Comment by rfk** [comment]
Here's the specific scenario I'm concerned about:

* At time `T1=12345.001`, client 1 does a read of a collection.  It observes `X-Last-Modified=12300.00` and `X-Weave-Timestamp=12345.00` for that collection, and updates its current "pointer" to the last-seen change to be `12345.00`.
* At time `T2=12345.009`, client 2 does a write to that same collection.  The server writes it through to the db and the state of the collection is now `X-Last-Modified=X-Weave-Timestamp=12345.00`
* At time `T3=12400.000` client 1 syncs again.  It queries `/storage/collection?newer=12345.00` because this was its last observed value of `X-Weave-Timestamp`.  Since `newer` is a strict filter, this query will not include the changes written by client 2.

Note that if the client were using `X-Last-Modified` as its "pointer" rather than `X-Weave-Timestamp` then we wouldn't have this problem, because the server enforces that every change generates a new `X-Last-Modified` timestamp.

**Comment by bbangert** [comment]
If the server treats newer as newer_eq, wouldn't that fix this issue?

**Comment by rfk** [comment]
> Is this accurate?

From slack, @linacambridge says this is not accurate, and we use `X-Last-Modified` rather than `X-Weave-Timestamp` for downloads.

**Comment by bbangert** [comment]
I'd be fine then dropping X-W-T entirely. That would avoid returning unused values when it isn't needed.

**Comment by mhammond** [comment]
Desktop uses X-W-T as "informational" - eg, it's used to calculate the age of a remote bookmark/client for the purposes of reconciliation, used by the (almost dead) repair process, etc. We don't need formal guarantees relating to the state of a collection, but it's a nice way for us to have it as a monotonic timestamp we can trust more than the local clock.

**Comment by rfk** [comment]
Quick summary from slack discussion:

* The intended behavior is that clients do not use `X-Weave-Timestamp` for tracking their location in the change stream, and use `X-Last-Modified` for this in all cases.
* Clients may use `X-Weave-Timestamp` for informational purposes, such as trying to calculate the wall-time "age" of a record.
* The only guarantees we'll make about `X-Weave-Timestamp` are:
  * For all requests, `X-Weave-Timestamp >= X-Last-Modified`.
  * For all requests that modify an item, `X-Weave-Timestamp == X-Last-Modified`.
  * But it can otherwise drift due to e.g. clock skew on servers.

Action item for myself to ensure this is accurately reflected in the syncserver API docs.

**Comment by thomcc** [comment]
I had always thought that X-Weave-Timestamp is what the server believes the current actual time to be. If it only changes when the server is written to, I think sync will probably make some incorrect decisions about age in some cases. (I'll have to think about it more later, head kind of foggy at the moment...)
