### ISSUE TITLE
Split MZKeychainWrapper out of FxA Crate

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#4802]
To get SPM working, we needed to bundle SwiftKeychainWrapper with FxA to get it working on iOS. This is really hacky and not an ideal situation.

>Summary of problem: Since it’s a library we need as a depedency and so does FxiOS there ends up being two copies since SPM can’t correctly make the dep graph. 

Potential solutions:

1. Remove all SwiftKeychain files and put them in iOS
  - Since they are the only consumer, the consumer-specific files should be in iOS
2. Create a script to split out SwiftKeychainWrapper in iOS during archiving

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3035)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866510

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
