### ISSUE TITLE
Enable SQLITE_DBCONFIG_DEFENSIVE

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#481]
I only discovered this flag exists via bug 1514683, but it sounds like something we should be doing?

**Comment by thomcc** [comment]
Not opposed to adding it, but my understanding is it's only really needed if an attacker controls the SQL (particularly, I think they need to be able to craft CREATE TABLE statements), which hopefully we don't have.

**Comment by thomcc** [comment]
Not opposed to adding it, but my understanding is it's only really needed if an attacker controls the SQL (particularly, I think they need to be able to craft CREATE TABLE statements), which hopefully we don't have.

**Comment by mhammond** [comment]
rusqlite doesn't appear to expose `sqlite3_db_config`

**Comment by bug-mirror** [comment]
from mtg: rusqlite exposes a way to set this config option
