### ISSUE TITLE
rust-components-swift includes all components in the same namespace

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4820]
This is a follow up to #4815

With the [v91.0.1](https://github.com/mozilla/rust-components-swift/releases/tag/91.0.1) release of `rust-components-swift` all the component's swift code is released as one target. Meaning that name conflicts **across** components will fail to compile.

**For now, that's okay, we don't have any name conflicts in the components we ship to iOS and focus**. But, there are name conflicts in `tabs` and `autofill`. It's not a hard problem to workaround, we just rename whatever is conflicting, but we might want a better story for this

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3044)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866349

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
