### ISSUE TITLE
Document how to locally test against Firefox iOS

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4825]
With Carthage gone (🎉 🎉) we have a new approach of shipping our components. This means that the old way of testing local changes in application services against Firefox iOS no longer works, and we currently don't have any documentation explaining how one would do that.

An output of this issue should be a doc, under [docs/howtos](https://github.com/mozilla/application-services/tree/main/docs/howtos) with step by step guide for an application-services developer, a Firefox iOS developer, or a contributor to integrate a local change in Rust code and have it built with Firefox iOS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3049)
┆Story Points: 3
┆epic: Rust Components on iOS developer experience
┆sprintEndDate: 2022-05-27

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

App services PR: https://github.com/mozilla/application-services/pull/4959 ( https://github.com/mozilla/application-services/pull/4959|smart-link )

Rust components PR: https://github.com/mozilla/rust-components-swift/pull/59 ( https://github.com/mozilla/rust-components-swift/pull/59|smart-link )
