### ISSUE TITLE
Create a new smoke test for Firefox iOS

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4826]
With Carthage gone (🎉 🎉) our old smoke test won't work. We should consider writing a new one

I don't think the old smoke test even ran properly but creating this issue so that we can discuss if a smoke test is something we want to add

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3048)

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

🚩 Flag added

qweij;eklja sdf;lkajs f;alksdjf ;adlsk
