### ISSUE TITLE
App-services crate / UDL file

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4832]
Let's create an app-services crate for code that is shared between multiple components.  This has a couple benefits:
  - We have several small crates that we want to expose via UniFFI (crashtest, shutdown, rc_log).  If we have an app-services crate, we can add them there instead of having to create a new UDL file, integrate it into the Android and iOS build systems, etc.  Maybe the encryption code also fits into this category.
  - We have several types that are shared between components (`DeviceType` and other types from sync15 and sync15-traits, `SqlInterruptHandle`, etc).  If these existed in a shared UDL file, then we could define them as external types in the UDL file and not have to repeat the definitions.  ([prior work](https://github.com/mozilla/application-services/pull/4397))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3059)

**Comment by mhammond** [comment]
I don't think there's a great use-case here, and a couple of the examples above have already been done, by creating a UDL file in the "owning" crate (eg, sync15 has a UDL).
