### ISSUE TITLE
Fail fast in string substitution when field_name is not in  context

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#4838]
In the context of string substituion in GleanPlumb string helper, where a template variable is used in the template, but isn't in the context.

* we should just not display the messages that error! This would guarantee that the user did not launch a malformed action. However: 
  - this would mean messages just won't show up, potentially causing error reports against Nimbus/GleanPlumb. This is especially true when the system is new.
  - it increases the amount of work that needs to be done *before the message is displayed*, when time is more critical.
  - the consequences of a malformed action is low.
  - this would be difficult to detect and debug when QAing a message, 
  - if an action actually needed braces, this would prevent it working

But: we could declare this message malformed, we can see it in the field.

This is a followup improvement after we've gained trust in the system as a whole.

_Originally posted by @jhugman in https://github.com/mozilla/application-services/pull/4831#discussion_r804633880_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2214)
┆Epic: FML follow-up work

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

Closing this here and moving it to the Nimbus board for better tracking

**Comment by data-sync-user** [comment]
➤ James Hugman commented:

{quote}This is a followup improvement after we've gained trust in the system as a whole.{quote}

This isn’t ready for engineering yet.

Moving this out of this sprint.

**Comment by jhugman** [comment]
Closing in favour of the linked Jira issue.
