### ISSUE TITLE
UAID not recognized sentry error

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4844]
I realized we don't have a bug on file for this. It's by far the largest sentry error, ref: https://sentry.prod.mozaws.net/operations/firefox/issues/15553358/?query=is%3Aunresolved

The fix here is most likely in android-components, but filing it here in case it involves any changes to the Rust code

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3068)
┆epic: Triage

**Comment by mhammond** [comment]
Last I looked on Nightly, I couldn't find any events with current AS versions - https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13116764 - so it seems possible Tarik's most recent push fix on Fenix did actually fix this?

**Comment by tarikeshaq** [comment]
Nice! Yes I just double-checked, and you're correct - in fact the daily rate is going down gradually (I'm guessing as users upgrade). And now that 97 hit release (which is the first version with the push fix) the numbers on release are going down too. I'll keep this ticket open and assign it to myself. I'll close it once I feel confident the event counts are low

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

It’s safe to close this now. Release is now using as 87.1.0, and all reported sentry pings are reporting 86 or under. Coupled with the continuous decline of the reported pings (almost halved in 30 days) I’m confident this will continue declining.
