### ISSUE TITLE
Data Review: Record more errors for Places

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4848]
1. What questions will you answer with this data?

**What is the error type breakdown of the errors emitted by the Places component in Fenix**

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

**To understand the underlying reasons why the places component fails. There has been a recent increase in read errors, and the majority is classified as `other`

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?

**Reporting to sentry is already in use, however, it only shows counts of new errors, it's however not sufficient to answer the question of the error breakdowns as it only gives us counts of new errors when they appear**

4. Can current instrumentation answer these questions?

**No**

5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Increase the number of places error types recorded in telemetry. The new errors recorded (as will be shown in telemetry) are:

- json_parse_failed: When a parsing a JSON failed
- places_connection_busy: When the database was busy as another API call occurred
- operation_interrupted: When the operation was interrupted
- unexpected_places_exception: An unexpected error, we do not record any more data about it.
- bookmarks_corruption: Bookmarks were corrupted</td>
    <td>technical data</td>
    <td>#4847</td>
  </tr>
</table>
 
6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

**This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/**

7. How long will this data be collected?

** Similar to the already existing reporting of the other error types, it will never expire, see https://bugzilla.mozilla.org/show_bug.cgi?id=1694316 for original data review. @mhammond email is already linked in the `metrics.yaml`**

8. What populations will you measure?

**All channels in all countries in all locales, for Android**

9. If this data collection is default on, what is the opt-out mechanism for users?

**Standard Firefox telemetry controls**

10. Please provide a general description of how you will analyze this data.

**Observe the breakdown of the error as error rates increase and decrease over time. It is a part of our usual weekly triage rotation.**

11. Where do you intend to share the results of your analysis?

**The SACI and Android teams**

12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

**No**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3071)

**Comment by tarikeshaq** [comment]
PR to add it is in #4847

**Comment by eliserichards** [comment]
@tarikeshaq in #5 can you list each of the new error types you are planning to collect?

**Comment by tarikeshaq** [comment]
Thanks @eliserichards! Added them to the fifth question 😄

**Comment by eliserichards** [comment]
> 1. What questions will you answer with this data?
> 
> 
> **What is the error type breakdown of the errors emitted by the Places component in Fenix**
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
> **To understand the underlying reasons why the places component fails. There has been a recent increase in read errors, and the majority is classified as `other`
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> **Reporting to sentry is already in use, however, it only shows counts of new errors, it's however not sufficient to answer the question of the error breakdowns as it only gives us counts of new errors when they appear**
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> **No**
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Increase the number of places error types recorded in telemetry. The new errors recorded (as will be shown in telemetry) are:
> 
>     * json_parse_failed: When a parsing a JSON failed
> 
>     * places_connection_busy: When the database was busy as another API call occurred
> 
>     * operation_interrupted: When the operation was interrupted
> 
>     * unexpected_places_exception: An unexpected error, we do not record any more data about it.
> 
>     * bookmarks_corruption: Bookmarks were corrupted
> 
> 
> 	technical data 	#4847
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> **This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/**
> 
>     7. How long will this data be collected?
> 
> 
> ** Similar to the already existing reporting of the other error types, it will never expire, see https://bugzilla.mozilla.org/show_bug.cgi?id=1694316 for original data review. @mhammond email is already linked in the `metrics.yaml`**
> 
>     8. What populations will you measure?
> 
> 
> **All channels in all countries in all locales, for Android**
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> **Standard Firefox telemetry controls**
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> **Observe the breakdown of the error as error rates increase and decrease over time. It is a part of our usual weekly triage rotation.**
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> **The SACI and Android teams**
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
> **No**
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3071)


# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

   * Yes, through the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

   *  Yes, through the "Send Usage Data" preference in Fenix app settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

   * Yes, the sync team (synced-client-integrations@mozilla.com) and mhammond@mozilla.com will be added as owners in `metrics.yaml`.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

   * Category 1 - technical data

5) Is the data collection request for default-on or default-off?

   * Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

   * No

7) Is the data collection covered by the existing Firefox privacy notice? 

   * Yes

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

   * No

## Result

data-review+

**Comment by tarikeshaq** [comment]
Thanks @eliserichards!!!
