### ISSUE TITLE
Expose "Get send tab devices" API in FxA client

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4853]
I've been looking around in the apps, (mostly iOS) and since we only provide a `get_devices` API, [they end up not even looking at the `DeviceCapabilities` at all (at least in iOS)](https://github.com/mozilla-mobile/firefox-ios/blob/69f2accf4619093f7df2ead803e76e08a0374006/Providers/Profile.swift#L977)

This means it's possible devices show up in the "send link to devices menu" that don't support send tab.

Additionally, with https://bugzilla.mozilla.org/show_bug.cgi?id=1756024 desktop might now filter on the `pushCallback` as well. We want to keep all this away from the apps, so either:
- Create a new `get_send_tab_devices` API
- Change our `get_devices` API to allow one to query specific capabilities

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3080)
┆Epic: Tabs improvements

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866350

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
