### ISSUE TITLE
Analyze our sqlite pragma usage for potential improvements/best practices

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#4877]
Can we create a set of standard [sqlite pragmas](https://www.sqlite.org/pragma.html) for our components that could be set in `sql-support` by default based on our current pragma usage (see [here](https://github.com/mozilla/application-services/issues/4872#issuecomment-1066813381) for context)? Or can we document best practices around pragmas? 

This ticket is a spike to answer those questions which could result in additional tickets to perform any resulting optimizations.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3108)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866354

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
