### ISSUE TITLE
Taskcluster updates

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4879]
There are a couple updates that I'd like to make to our taskcluster code:
  - Combine [all these ENV setting statements](https://github.com/mozilla/application-services/blob/main/taskcluster/docker/linux/Dockerfile#L23-L41) into 1 line.  That way we aren't creating so many docker layers.
  - Switch away from our slightly weird `rsync` usage to copy fetched files ([one of many examples](https://github.com/mozilla/application-services/blob/main/taskcluster/ci/module-build/kind.yml#L36)).  I think the reason we use rsync is to merge the fetched files with any existing files.  For example, I just added an artifact that contains the files to add to the `.m2` directory, but there may be other files already there.  To fix this, I think we just need to update our code to not extract the tarballs into the fetches directory, and instead we can extract them directly into the directory we want to install to.  I think the way to avoid extracting the tarballs is to use the longer-form schema for fetches ([specified here](https://hg.mozilla.org/ci/taskgraph/file/tip/src/taskgraph/transforms/job/__init__.py#l83))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3111)

**Comment by mhammond** [comment]
Assigning to Ben, to either action or close.

**Comment by bendk** [comment]
Let's close.

I don't think the `ENV` commands are an issue anymore.  According to SO: `In Docker 1.10 and higher, only RUN, COPY, and ADD instructions create layers. `

The `rsync` usage still feels weird to me, but that's what other taskcluster systems use as well.  I don't think it's important to change.
