### ISSUE TITLE
Data Review: Renew Logins Encryption Key Regeneration

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4899]
## 1.   Provide a link to the initial Data Collection Review Request for this collection.

#4582

## 2.  When will this collection now expire?

3 months (2022-07-18)

## 3. Why was the initial period of collection insufficient?

We wish to continue to collect data in case there is an issue with the logins key storage.  Having the metrics available would help us identify the error case.

However, it's not totally clear to the team that this data is valuable.  So we're asking for a 3 month extension to give us time to come up with a metrics policy for our team and also discuss it with a data scientist.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3125)

**Comment by travis79** [comment]
> ## 1. Provide a link to the initial Data Collection Review Request for this collection.
> 
> #4582
> ## 2. When will this collection now expire?
> 
> 3 months (2022-07-18)
> ## 3. Why was the initial period of collection insufficient?
> 
> We wish to continue to collect data in case there is an issue with the logins key storage. Having the metrics available would help us identify the error case.
> 
> However, it's not totally clear to the team that this data is valuable. So we're asking for a 3 month extension to give us time to come up with a metrics policy for our team and also discuss it with a data scientist.
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3125)

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Comment by bendk** [comment]
Closing this one, since we already renewed the metrics.  #5051 is for the second renewal.
