### ISSUE TITLE
Expose deleteVisitsFor in our swift wrappers

### ISSUE THREAD

**Issue by electricRGB** [mozilla/application-services#4908]
AS gives us `deleteHistoryMetadata(key...` which is great, but has an issue: It requires matching a full key (ie, the url, the search term and the referrer url) to delete something. So if we want to delete something from the history (where on Firefox-iOS we might not have the search term and the referrer url) we have to do what Android is currently doing.
 
<img width="913" alt="Screen Shot 2022-03-30 at 12 04 49 PM" src="https://user-images.githubusercontent.com/11182210/164046124-b36a2207-27db-4e9c-9193-9f05bd28e4f5.png">

The problem is that this code ends up being very messy, and, especially with how many operations we're doing on the homepage, we want to really lessen the performance hit as much as possible.

The request: given that URLs are unique when it comes to metadata, we'd like a API that allows us to pass in a URL (or a set of URLs), without the need for a search term or a referral url to easily delete metadata items.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3142)
┆Story Points: 1
┆sprintEndDate: 2022-05-13

**Comment by mhammond** [comment]
Can you please explain a little more about how you are using this? Not that I want to push back too hard here, but the history-metadata stuff started out as an experiment, has diverged from desktop's similar API, and I fear it is a future footgun, and I'm wondering if it is still fit for purpose?

In particular, are you looking to delete all history about that URL, or just stuff in history_metadata but leave all visits alone? If the latter, I'm trying to work out what the use-case is specifically?

**Comment by electricRGB** [comment]
Sure. 

So, essentially, we have two flows for deleting a history item from a user's perspective:
1. deleting from our Recently Visited section (which is a list of history highlights that we get from AS)
2. deleting from the history panel

Because on iOS we have our own local history, regardless of flow, the url the user is deleting needs to be deleted simultaneously from both data sources so that the url doesn't get deleted from history, but still shows up in our history highlights. Deleting an item from Recently Visited and having it be deleted from History is easy as we already have URLs to do that.

However, deleting an item from History means we only have a url. The current API to delete a metadata item requires a `HistoryMetadataKey` to be passed in and it needs to match fully before an item can be deleted, according to the unit tests I wrote.

For example, if my key in AS is `HistoryMetadataKey(url: "www.example.com", searchTerm: "example", referrerURL: nil)` and from history I just have the URL so I can only create `HistoryMetadataKey(url: "www.example.com", searchTerm: nil, referrerURL: nil)`, the item in AS won't get deleted. The current solution is to fetch all history highlights from AS, iterate through them till we match on the url, extract the key from there, and then delete. This works, but is inelegant and computationally expensive given that we're performing a bunch of other operations. However, given that all AS urls are unique when it comes to metadata, it should easily match, and be easily deletable.

And yeah, as far as I understand, we want to get rid of all the data associated with that url. So it's the same operation as the current `deleteHistoryMetadata`. A separate function that instead of accepting just a `HistoryMetadataKey` it would ideally accept a set of urls that it would iterate over and delete the data associated with those unique urls.

**Comment by mhammond** [comment]
Thanks for the update! So the good news is that this capability already exists (with one edge-case). Specifically, you can call the [connection.delete_visits_for()](https://github.com/mozilla/application-services/blob/1f01918d43ba2eba4bac921724f2be26e09ab249/components/places/src/places.udl#L119) function and it will "do the right thing" - it will delete all history metadata.

A couple of important notes though:

* This function also deletes "regular" history - and although iOS does not use "regular" history from this crate yet, this function is still available to be called and will delete the metadata. As we move iOS to using this for "regular" history, it will also delete those regular visits - but until then, you still need to call your own history delete implementation.
* This function *does not work* if the Url is bookmarked! I've fixed this in #4918, so will be in a future release, but hopefully this edge-case doesn't really block your use-case.

If this all sounds good and does meet your immediate needs, please close this!

**Comment by electricRGB** [comment]
That sounds great. 

I'm going to keep this ticket open because it seems like I don't have access to that function in the `MozillaRustComponentsSwift` package which means an update will be required. See screenshot:

<img width="1075" alt="Screen Shot 2022-04-21 at 8 17 25 AM" src="https://user-images.githubusercontent.com/11182210/164456557-94abd17b-3d6c-4f99-8000-002951a62846.png">

**Comment by mhammond** [comment]
It should be on the exact same object that `metadataDelete` is called on - probably just `connection.deleteVisitsFor()`, or with a quick grep of the ios source, maybe `places.deleteVisitsFor()`?

**Comment by electricRGB** [comment]
Unless I'm doing something extremely wrong, it is not there. As you can see in the screenshot in my previous comment, it's not available on `connection` and as you can see in the screenshot below, it's not available on `places`

<img width="776" alt="Screen Shot 2022-04-21 at 8 23 43 PM" src="https://user-images.githubusercontent.com/11182210/164571380-78d60168-c959-463e-aaf1-5743a1288ec5.png">
.

**Comment by mhammond** [comment]
doh! Sorry about that - we need to expose that via https://github.com/mozilla/application-services/tree/main/components/places/ios/Places - I'll turn this issue into doing that!

**Comment by electricRGB** [comment]
Heya. Any update on this? It's a blocker on some work in the sprint and I want to know how to manage my time around that.

**Comment by mhammond** [comment]
It will take me a little time to setup a mac environment, so I doubt I'll get to it this week - there's also a chicken-and-egg situation - it will be tricky to make sure that it works when there are no consumers. Obviously we'd take a PR though, and this would touch just swift code, so maybe you could add it, then you'd be able to test it at the same time as adding it?
