### ISSUE TITLE
UrlParseFailed errors in noteHistoryMetadataObservation()

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4909]
We're currently getting about [100-150 of these errors a day in sentry](https://sentry.prod.mozaws.net/operations/firefox/issues/19455994/?query=is%3Aunresolved).  That's not a huge amount, but it seems like we should do something about it.

- If these issues are expected, then I think we should update `noteHistoryMetadataObservation()` to not report them
- If they're unexpected, then we should fix the code somehow.
   - Maybe update places to handle these URLs? 
   - Maybe update the Fenix code to not try to record these URLs?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3143)

**Comment by mhammond** [comment]
> * If these issues are expected, then I think we should update `noteHistoryMetadataObservation()` to not report them

The intention is that it already does - [here](https://github.com/mozilla-mobile/android-components/blob/01012c16f9e3aab667aaa1ad9065d87bf1bad9ce/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L275-L288) it checks for an invalid Url before calling our component. `canAddUri` is at the end of that same file, and while it relies on a different parser than we do, I believe most of those sentry errors should have been filtered. So I'm not sure what is going on there.

> * If they're unexpected, then we should fix the code somehow.

We had the same issue with the regular history items - I think that they are "expected" in so far as some code assumed that whatever text is in the address bar in some cases is valid, but mistyping a URL in some way would trigger this.

IOW, the fact that `noteHistoryMetadataObservation()` in a-c might be called with an invalid URL is expected, but it's unexpected that they should end up making it to the rust code.

**Comment by mhammond** [comment]
#5304 has made this redundant.
