### ISSUE TITLE
XCFramework not building Sqlite correctly for M1 simulators

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#4921]
Right now there is currently a problem where our XCFramework is not building arm64 simulator (M1) SQLite. However, everything else is being built correctly.

Summary of what I think is going on:
We use a slightly hacky approach to create xcframeworks -- instead of using the `xcodebuild` scenario we essentially custom-build the xcframework with this script https://github.com/mozilla/application-services/blob/main/megazords/ios-rust/build-xcframework.sh

Each target (x86_64 simulator, aarch64 ios hardware, and now aarch ios simulator) gets built and passed in the variables to build the binaries for those respective targets https://github.com/mozilla/application-services/blob/main/megazords/ios-rust/build-xcframework.sh#L88-L96

This has been working very well for us on firefox for iOS and M1's are able to build fx ios quite successfully. Unfortunately, there is a hidden bug where sqlite.o is not being built for aarch64-ios-sim correctly.

checking the binaries for the simulator portion of the build:
`/application-services/megazords/ios-rust/MozillaRustComponents.xcframework/ios-arm64_x86_64-simulator/MozillaRustComponents.framework`

running `otool -fahl MozillaRustComponents | grep -E 'cmd |platform |\.o'` and parsing some of the values shows:

sqlite3.o - Not being built correctly
```
../ios-arm64_x86_64-simulator/MozillaRustComponents.framework/MozillaRustComponents(sqlite3.o) (architecture x86_64):
      cmd LC_VERSION_MIN_IPHONEOS

```
```
../ios-arm64_x86_64-simulator/MozillaRustComponents.framework/MozillaRustComponents(sqlite3.o) (architecture arm64):
      cmd LC_VERSION_MIN_IPHONEOS
```
LC_VERSION_MIN_IPHONEOS is the older way to build the binaries for xcframeworks. A correct binary build looks like:
```
../ios-arm64_x86_64-simulator/MozillaRustComponents.framework/MozillaRustComponents(megazord_ios-fb888d3d9510ccdf.libsqlite3_sys-8d6c76a729212ba1.libsqlite3_sys.1af7b0bf-cgu.0.rcgu.o.rcgu.o)
 (architecture arm64):
      cmd LC_BUILD_VERSION
 platform 7
```
Where LC_BUILD_VERSION is defined (instead of LC_VERSION...) and platform 7 corresponds to IOSSIMULATOR in the llvm https://github.com/llvm/llvm-project/blob/09c2b7c35af8c4bad39f03e9f60df8bd07323028/llvm/include/llvm/BinaryFormat/MachO.h#L500

AFAIK, we don't build our own sqlite and instead use the packaged version via Rusqlite. More investigation will need to be done to identify if we're not passing the right variables or if Rusqlite will need to support passing in ios-sim target archs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3144)

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Obviated by SQLCipher removal (https://mozilla-hub.atlassian.net/browse/SYNC-3838 ( https://mozilla-hub.atlassian.net/browse/SYNC-3838|smart-link ))
