### ISSUE TITLE
Investigate dependency summary script possibly checking unneeded dependencies

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4936]
in #4933, the dependency summary was checking for licenses for `windows_sys`, `windows_x86_64_gnu`, etc

I'm not exactly sure if it should or shouldn't look at those, but filing this ticket for someone to do quick look at the script to verify

_Originally posted by @emilio in https://github.com/mozilla/application-services/pull/4933#issuecomment-1115268920_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3164)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866513

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
