### ISSUE TITLE
Intermittent logins sql test failure

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4948]
```
thread 'db::tests::test_touch' panicked at 'assertion failed: login2.record.time_last_used > login.record.time_last_used', components/logins/src/db.rs:1339:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://app.circleci.com/pipelines/github/mozilla/application-services/30481/workflows/822e3c39-6dd5-4dd0-b1ec-29538d630bd9/jobs/133577 for more details on the job that failed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3171)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866514

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
