### ISSUE TITLE
When failing to load libraries with JNA, fail with `System.loadLibrary` exception instead

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#496]
Over in https://github.com/mozilla-mobile/reference-browser/issues/353, it would have helped to have the underlying `System.loadLibrary` exception.  What happens is that on Android:

- JNA tries to preload using `System.loadLibrary`
- that fails in the case of malformed libraries
- JNA falls back to searching the Java resource path
- that fails 'cuz that's not how Java library loading works
- JNA complains about resource paths

The real error is the `System.loadLibrary` failure.  This ticket tracks catching the JNA error and either replacing or augmenting it with the real `System.loadLibrary` failure.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-255)

**Comment by ncalexan** [comment]
It's possible that #320 would improve this error case, but I don't know.

**Comment by vladikoff** [comment]
@thomcc do we need this?

**Comment by ncalexan** [comment]
> @thomcc do we need this?

Need is strong, but it's still worth considering.

**Comment by thomcc** [comment]
Related: #1426
