### ISSUE TITLE
Update Android sync error dashboards

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4967]
From what we can tell, our android sync errors dashboard is not using the correct data.  We're generating the dashboards from the old telemetry pipeline, but Fenix is using Glean.  It seems that the data we're getting is from very old Fennec versions.  Let's double check that this is correct and if so update the dashboards to use the correct data source

Here's a query that counts sync pings by app name, os name, and version.   The first row that I see with `os_name=Android` is way down the last and it's app name/version is 'Fennic/68.7.0`.  https://sql.telemetry.mozilla.org/queries/85530/source?p_channel=nightly&p_engine_name=all-engines

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3185)
┆sprintEndDate: 2022-06-24

**Comment by skhamis** [comment]
I know this dashboard uses the newer glean telemetry: https://sql.telemetry.mozilla.org/dashboard/fenix-logins-and-places-performance-metrics?p_org_mozilla_fenix=org_mozilla_fenix

But that would explain why the fenix on our main dashboard has super low counts.

**Comment by bendk** [comment]
Just updated the dashboard to use the Glean metrics.  Thanks for the link @skhamis!
