### ISSUE TITLE
Extend deleteHistory of PlacesHistoryStorage

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla/application-services#4973]
Relates to jira ticket [..FNXV2-19087](https://mozilla-hub.atlassian.net/browse/FNXV2-19087)

**Background:**
We are adding a new [synced history](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=879%3A41209) screen in the android app. After coming to the history screen, users will see only local history, having a synced history button. Clicking it will lead to another history screen, with the synced from other devices items.
Both screens have a "remove all" button, and we would like them to behave differently. Currently, `deleteEverything` method  does what it says, but we need a way to delete everything that appeared on the synced history screen.

**Requirements:**
PlacesHistoryStorage has a method `deleteEverything()`. We would like to extend it to accept `is_remote` parameter, so we could have control over what `HistoryVisitInfo` would be deleted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3187)
┆epic: MR2 History Metadata Sync support

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866355

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
