### ISSUE TITLE
Update error code to use the new reporting system

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4981]
Once  #4930 and  #4980 are merged, the next step is to switch away from `log::error!()` to `report_error!()` and `breadcrumb()!` from the `error_support` crate.  This means giving some thought to how we want to group our errors and iterating on it as we see the results in Sentry.

Let's not tackle this one until we're sure the system from #4930 is going to work for us.  I think the test is if it helps us track down #4856.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3191)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866356

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
