### ISSUE TITLE
FML: Add a configuration file to configure branches and paths

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#4991]
Relates to #4976.

We identified several areas that needs are fixed by allowing a configuration file to be passed into the file loader.

These are: 

 * allowing the branch `master` branch to be used instead of the default `main`.
 * allowing repeatable builds once the app has been released.
 * allowing local development of multi-repositories.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2572)
┆Story Points: 3
┆epic: FML files importing FML files
┆sprintEndDate: 2022-07-22

**Comment by data-sync-user** [comment]
➤ James Hugman commented:

The command line args for specifying the file is at https://mozilla-hub.atlassian.net/browse/EXP-2560 ( https://mozilla-hub.atlassian.net/browse/EXP-2560|smart-link ).

This issue should also look after the creation of the  cache directory, the construction of the FileLoader, passing it to the Parser creating the first FilePath and re-enable SUPPORTS_REMOTE_LOADING
