### ISSUE TITLE
Analyze and potentially update our `DispatchQueue` Usage

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/application-services#4996]
Within the swift layer of most of our appservices components we are creating Dispatch Queues (like [this](https://github.com/mozilla/application-services/blob/d33c6e2c813b7318a3b3f52a86feaad2deae5f89/components/logins/ios/Logins/LoginsStorage.swift#L18)) and scheduling our API calls on those queues synchronously. But in iOS our API calls are being scheduled (sometimes asynchronously) in [separate Dispatch Queues](https://github.com/mozilla-mobile/firefox-ios/blob/f00aeaa0fa4fda3eb51f496f76ab68c96bef9974/Storage/Rust/RustLogins.swift#L415) created there. 

Judging from [this comment](https://github.com/mozilla/application-services/blob/d33c6e2c813b7318a3b3f52a86feaad2deae5f89/components/logins/ios/Logins/LoginsStorage.swift#L12) this is an anti-pattern that developed over time, and will most likely be resolved by removing Dispatch Queue usage in appservices entirely, but we need to test this to be sure.

The work to complete this ticket will involve analyzing whether we can remove this code entirely, adding tests to ensure that is the case, and potentially creating some sort of documentation for best practices around this.

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/SYNC-3203)
┆Fix Versions: 104
┆Sprint End Date: 2022-06-10

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Status: On-track
Completed this week: N/A
Sprint goal: Complete analysis and remove DispatchQueue logic from logins
Blockers: N/A
Notes: The analysis of our DispatchQueue usage is nearly complete. Thereafter a small PR to remove that logic from the logins component will be created. Once those changes are merged and released, and we are sure that no adverse impact resulted, we will remove the logic from the tabs and places components.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

(2022-06-23) Status: On-track
Completed this week: N/A
Sprint goal: Complete analysis and remove DispatchQueue logic from logins
Blockers: N/A
Notes: A work in progress PR has been created which includes the removal of DispatchQueue usage from the logins component. A doc to explain these changes is being created and will be completed before the end of the sprint.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Status: On-track
Completed this week: Analysis work and removal of DispatchQueue usage from logins
Sprint goal: Merge PR
Blockers: N/A
Notes: The PR which includes the DispatchQueue usage removal and a doc explaining the decision is in review. The remaining ticket will be blocked until the logins changes are deemed safe.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Status: On-track
Completed this week: N/A
Sprint goal: N/A
Blockers: N/A
Notes: There is disagreement on the iOS side on how we should proceed with these changes. We plan to use the work week to reach consensus. If we are unable to agree on a course of action or if these changes are deemed unnecessary we will deprioritize this work in favor of the sync manager integration.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

Status: On-track
Completed this week: N/A
Sprint goal: N/A
Blockers: N/A
Notes: After discussing this with the iOS engineers during the work week, we've decided that we're going to table these changes and allow the iOS team to prioritize their work and holistically analyze our current DispatchQueue usage across both the a-s and iOS repos and make any necessary improvements.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866358

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
