### ISSUE TITLE
FxA - Document which methods throw if there is no network

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/application-services#500]
None of the methods note whether a network connection is required; some (many) throw if one is not present.  Documenting which ones throw would be very helpful.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-91)

**Comment by vladikoff** [comment]
Sibling bug: https://github.com/mozilla/application-services/issues/479

**Comment by thomcc** [comment]
(My bad, this is about fxa not logins, I’m on mobile for the next bit min and... can’t find the delete/edit button. Will fix when I get back)

**Comment by bbangert** [comment]
Related bug: #629.

**Comment by vladikoff** [comment]
Let us know if you someone still needs this
