### ISSUE TITLE
Audit the `iter_` methods in `nimbus-fml`

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#5003]
a pass by thought about the return types, a "good first bug" could be to turn the `Vec`s into iterators in any `iter_*` functions 🤔 (I know this isn't the only one, so not requesting changes on it here)

_Originally posted by @tarikeshaq in https://github.com/mozilla/application-services/pull/4999#discussion_r899742398_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3211)

**Comment by mateiidavid** [comment]
@jhugman is this still an issue that can be picked up? :) I see that there are still some `iter_` functions whose return types are `Vec`s. e.g

* https://github.com/mozilla/application-services/blob/a074bf651bf3bec56bc0b78ac876888904be1392/components/support/nimbus-fml/src/backends/swift/gen_structs/mod.rs#L62-L64

* https://github.com/mozilla/application-services/blob/3fcfc240253634ac66a37a9551e04191a8c4c0b4/components/support/nimbus-fml/src/intermediate_representation.rs#L528-L538

**Comment by jhugman** [comment]
@mateiidavid I'm sorry I missed this comment!

I think the `iter_imported_files` still needs doing, and the `iter_feature_defs` in both `gen_swift` and `gen_kotlin` is now redundant. If you're still interested in contributing, then please open a PR, and mark me as a reviewer!

As part of a migration away from Github Issues, I'm closing this in favour of the linked Jira ticket.
