### ISSUE TITLE
Add pruning to places `run_maintenance()`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5011]
Places has a `run_maintenance()` function, but it doesn't currently do all [the things that desktop does](https://searchfox.org/mozilla-central/rev/a55ac39a6e01c342d3befacc875a6e2959f6111f/toolkit/components/places/nsPlacesExpiration.js#171).  We should consider adding more functionality to it.
 
I think the starting point should be deleting older visits when over the page limit (see  `QUERY_FIND_EXOTIC_VISITS_TO_EXPIRE` and `QUERY_FIND_VISITS_TO_EXPIRE`).  I'm not sure how to set a page limit, maybe the app can pass in a size limit and we can calculate a page limit based on that.
 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3216)
┆sprintEndDate: 2022-07-22

**Comment by mhammond** [comment]
There's also https://searchfox.org/mozilla-central/source/toolkit/components/places/PlacesExpiration.jsm, which is probably what we ultimately want to do to stop the db growing without bounds. I haven't really thought too much about how much of that we should do or when though, but maybe getting the core infrastructure in place and one of the expiration strategies would be a good start? Eg, "Finds visits to be expired when history is over the unique pages limit" seems useful, and/or the `DATABASE_DISK_CONSTRAINED_THRESHOLD` handling?

**Comment by bendk** [comment]
(Updated the description now that I know more about what's going on in desktop).

Another thing that desktop does is delete orphaned pages.  But I think we have [some code that already does this](https://github.com/mozilla/application-services/blob/main/components/places/src/storage/history.rs#L670-L696), that executes right when the pages are deleted from the app.  Is my reading correct?  Is there any value in still trying to delete orphans in case that code missed them somehow?
