### ISSUE TITLE
Stop recording migration metrics

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5017]
The glean metrics are about to expire, we haven't been checking them recently, and it's very doubtful that we're ever going to update the migration code based on those metrics in the future.  So lets stop recording them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3221)
┆sprintEndDate: 2022-07-08

**Comment by mhammond** [comment]
Closed by #5019
