### ISSUE TITLE
addresses/creditcards: Store error: JSON Error: missing field `entry`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5020]
We currently have about 2000 of these failures a day for both addresses and credit cards.  I think it's a 100% failure rate.  We should investigate this and fix it.  AFAICT, this is only happening on nightly, we don't try to sync either on beta or release (although we just switched to a new nightly cycle, so maybe we'll start seeing them on beta.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3225)
┆sprintEndDate: 2022-07-08

**Comment by mhammond** [comment]
Hey @bendk, in what dashboard did you see these errors? I've worked out the problem isn't incoming tombstones, but can see an error when tombstones are stored in the mirror - but this makes it very unlikely that many users are impacted, so I'm interested to try and dig into the actual failure rate.

**Comment by mhammond** [comment]
> Hey @bendk, in what dashboard did you see these errors?

Please ignore this, Sammy put me on to the new dashboard!
