### ISSUE TITLE
Circle CI jobs running on mac runners are failing

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5025]
ref: https://app.circleci.com/pipelines/github/mozilla/application-services/30850/workflows/064285e4-46d2-44fe-a92f-8fef5ecf9265/jobs/136667

Looks like our circle ci jobs that run on mac runners are timing out when pulling the git submodules, this started last night/this morning as far as I can tell, and nothing relevant landed in that timeline, it could be intermittent but we should get it fixed to unblock incoming PRs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3226)

**Comment by mhammond** [comment]
This looks like a now resolved Circle incident - https://status.circleci.com/incidents/1npgsqnt64j3

**Comment by mhammond** [comment]
https://github.com/mozilla/application-services/pull/5026 appears to show this isn't happening - tests are failing now for obscure *different* reasons 😅
