### ISSUE TITLE
Data Review: Remove Expiration From Logins Encryption Key Regeneration Metrics

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5051]
## 1.   Provide a link to the initial Data Collection Review Request for this collection.

- Initial Review: #4582
- First Renewal: #4899

## 2.  When will this collection now expire?

Never

## 3. Why was the initial period of collection insufficient?

These metrics are potentially useful for debugging logins encryption key issues.  If there is a future issue where many users need to regenerate their encryption keys, being able to see some data about the reason why could help us fix the issue.  This is fairly unlikely, but we believe it's worth it since the amount of metrics collected is very low (about 10/day for all Fenix releases) and the user impact is very high (regenerating a logins key means losing all of your saved logins).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3241)

**Comment by travis79** [comment]
> ## 1. Provide a link to the initial Data Collection Review Request for this collection.
> 
>     * Initial Review: [Data Review: Logins Encryption Key Regeneration #4582](https://github.com/mozilla/application-services/issues/4582)
> 
>     * First Renewal: [Data Review: Renew Logins Encryption Key Regeneration #4899](https://github.com/mozilla/application-services/issues/4899)
> 
> 
> ## 2. When will this collection now expire?
> 
> Never
> ## 3. Why was the initial period of collection insufficient?
> 
> These metrics are potentially useful for debugging logins encryption key issues. If there is a future issue where many users need to regenerate their encryption keys, being able to see some data about the reason why could help us fix the issue. This is fairly unlikely, but we believe it's worth it since the amount of metrics collected is very low (about 10/day for all Fenix releases) and the user impact is very high (regenerating a logins key means losing all of your saved logins).
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3241)

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+
