### ISSUE TITLE
Sync Error: Invalid login: Login has illegal field: Origin is Malformed

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5059]
When reviewing the logins sentry data, I saw a lot of events like [this one](https://sentry.io/organizations/mozilla/discover/fenix-beta:dfe36319caae4859a7d8b023d00b4060/?field=issue&field=title&field=project&field=user.display&field=timestamp&name=All+Events&project=6295551&query=logins&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29) with this error.

We should investigate this and either fix the code or stop reporting so many errors.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3246)

**Comment by bendk** [comment]
My first try is to log a breadcrumb with the `url::Parse` error when we see it.  I don't think it should leak any PII (https://docs.rs/url/latest/url/enum.ParseError.html).

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866369

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
