### ISSUE TITLE
Duplicate login in update

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5060]
A few months ago we had a [Fenix Crasher](https://github.com/mozilla-mobile/android-components/issues/11251) when it was trying to update a login when there was a duplicate in the database.  We addressed this by preventing the crash and logging instead on app-services side (#4648).

Looking through the sentry today I saw multiple reports of the duplicate login error which makes me think we should fix the underlying issue.  Looking through the report data I saw:
  - Multiple users affected
  - Each time `has_mirror` was true, so it seems like this stems from the sync code being able to produce a duplicate login.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3245)

**Comment by bendk** [comment]
My first attempt to narrow this down is checking if the login has `form_action_origin` or `http_realm` set.  My hunch is that it's one kind or another that generates the duplicates.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866372

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
