### ISSUE TITLE
Rust Tabs engine should allow the possibility of "quickWrite"

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5074]
Tabs engine is unique in terms of not needing to do reconciliation and dealing with merging with other clients because each client has exactly one record of all the tabs they sync. 

[On desktop, @mhammond wrote a patch to help with Task Continuity to allow cheap writes to the server without the overhead of going through the sync managers (1 request vs 4 requests per sync)](https://searchfox.org/mozilla-central/source/services/sync/modules/engines/tabs.js#182)

We should have this feature written in rust and able to be used by both Android and iOS (and will be needed once we get the tabs engine on desktop) since it'll help reduce server load on all platforms.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3252)
┆Epic: Vendoring Tabs component into Desktop

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866361

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
