### ISSUE TITLE
Settings the `FxNimbus.api` is still required for initializing Nimbus

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#5075]
In the [Fenix TCP experiment](https://github.com/mozilla-mobile/fenix/issues/26041), we've run into a bug where the value of the `FxNimbus.api` is null if an experiment queries a feature before `FxNimbus.initialize` is done.

STR:
1. Have an app with Nimbus setup.
2. Setup a feature with a different value from the default.
3. Query a feature. e.g. `FxNimbus.features.engineSettings.value().totalCookieProtectionEnabled`
4. Call `FxNimbus.initialize { }`
5. Query the result of feature again.

Expected:
1. At step 5, the value should be that of what experimenter provides in it's database.

Actual:
1. At step 5, we get the same default value as step 3.

A temporary fix for Fenix (to unblock the TCP experiment) can be found here: https://github.com/mozilla-mobile/fenix/pull/26228

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3251)

**Comment by jhugman** [comment]
This is fixed as part of [#4999][0], available in release [v93.6.0][1].

[0]: https://github.com/mozilla/application-services/pull/4999/files#diff-9d1a8732c406d65ddc906cbe95ec0055b621a8eea2323e8511d0f29a7ec75572R60
[1]: https://github.com/mozilla/application-services/compare/v93.5.0...v93.6.0
