### ISSUE TITLE
places: Visit timestamps aren't roundtripable by sync

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#508]
Split from #498 (which doesn't introduce this problem)

We truncate them to the nearest millisecond. Unfortunately, firefox-ios and fennec both consider these to be distinct. Desktop, correctly, does not (although desktop will not produce the behavior that rust does currently).

The issue here is as follows:

- Server has a history record with some visits that have microsecond precision and are not aligned to the nearest millisecond (for concreteness, `date: xxxx123411234`). This record is present on fennec or firefox-ios as well. 
- Rust downloads the record, and inserts it, truncating the visit to the nearest millisecond (e.g. `date: xxxx12341000`). Next time rust uploads this record, it will upload the truncated version.
- Fennec or iOS later downloads the record rust just uploaded (with `date: xxxx12341000`), and, since it didn't happen at the same microsecond as the one it already knows about, it considers it distinct, and inserts it, even though it's not a real visit.

This ends up duplicating this record.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-92)
┆Story Points: 3
┆Sprint: SYNC - 2019-07-19

**Comment by jdragojevic** [comment]
1st step is to verify whether or not this work is necessary.

**Comment by mhammond** [comment]
Thom and I had a quick chat in slack and best we can tell, desktop and us do exactly the same thing. This means that

* We will interop perfectly well with desktop.

* The issues discussed above about our mobile platforms already exist today for desktop and no one has noticed.

* Fennec is going to die. Eventually FxiOS will use our impl.

All of which means we should probably do nothing at all here. I'll re-add the "discuss" label so we can chat about it in triage.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

estimate 3, needs investigation
