### ISSUE TITLE
Stop forwarding rc_log to Sentry on Android

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5093]
The `rc_log` component forwards `log::error!` calls to our consumers so they can report them to Sentry, but it's in the process of being replaced with the new error reporting code in `error-support`.  Once that code has been fully rolled out, we should remove the parts of `rc_log` that forward `log::error` entries to Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3268)
┆Epic: Error handling
┆Sprint End Date: 2022-10-28

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

don’t want to drop rc_log completely as it enables debug view on android - we should make that better.  Maybe evolve this ticket to define how we do that.

**Comment by mhammond** [comment]
[Here](https://github.com/mozilla-mobile/android-components/blob/f081b6e3f07f9f40a9160056774b4b7b6c95063f/components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt#L69) is where it's possible to adjust the log level to get debug logs. I don't think this is called anywhere, but IMO a good option would be to add simple UI to the debug menu that calls this to adjust to debug (or even trace?)

**Comment by mhammond** [comment]
So I think the task here is more like an a-c task described as something like "decouple rc-log from the error reporter"
