### ISSUE TITLE
Should we derive less traits?

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5133]
Updating Rust for #5128 revealed that we have a handful of derived `PartialEq` impls that we don't use and many more that we only use in tests.  As part of that issue, I fixed the clippy warnings by also deriving `Eq`.  This leads to a question: if these derived impls are not used, does the linker remove the dead code or do they cause binary size to increase and if so how much.  At some point we should check this out and consider not deriving some traits if there is some real-world cost.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3322)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866362

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
