### ISSUE TITLE
Make `logins::import_multiple` not return a string

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5134]
The current API has it returning a JSON-encoded string, but we never actually use it.  We should try to change this code to not return anything.  It seems that android-components and fenix don't actually look at the return and I don't think firefox-ios does either.  I believe the only "consumer" of this value is our own wrapper code that used to use it to return metrics.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3321)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866515

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
