### ISSUE TITLE
https://github.com/mozilla/application-services/blob/main/docs/building.md

### ISSUE THREAD

**Issue by Karembit** [mozilla/application-services#5138]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3332)

**Comment by mhammond** [comment]
Hi @Karembit, were you trying to report an issue with that doc, or was this opened by mistake?

**Comment by tarikeshaq** [comment]
Closing this for now, @Karembit feel free to reopen it if you were trying to report an issue 😄
