### ISSUE TITLE
Copy over source sets during a dependency substitution builds

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#5140]
While debugging, there are times in an application when you desire to add break points in the dependency library to step through the change.

Unfortunately, it seems that when using dependency substitution, the library is replaced without the source sets, so when clicking through a method/class from Android Studio, you are only able to see the public APIs and therefore there is no option to add break points.

The workaround now is to go back to the manual way of consuming app services:

```bash
# in the appservices project
$ ./gradlew publishToMavenLocal
# in the android components project..
$ ./gradlew publishToMavenLocal
# in the fenix project (optional)
$ ./gradlew --refresh-dependencies
```

cc: @jeddai @jhugman @Amejia481

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3333)

**Comment by tarikeshaq** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1889980
