### ISSUE TITLE
Migrate tabs to using the new error system

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5168]
We recently started using the new error handling system from support::error for logins and it seems to be working okay. The next step is to switch the other components to also use this system.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3347)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866516

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
