### ISSUE TITLE
Remove unneeded libraryOveride from Nimbus.kt

### ISSUE THREAD

**Issue by csadilek** [mozilla/application-services#5179]
Transferring this over from: https://github.com/mozilla-mobile/android-components/issues/9969

[dmose](https://github.com/dmose) commented [on Mar 24, 2021](https://github.com/mozilla-mobile/android-components/issues/9969#issue-840072024)
"Once the next version of application-services lands, [this libraryOverride](https://github.com/mozilla-mobile/android-components/blob/0bc7edf4a84a437c3819bd11f212d47998ba02e3/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt#L240-L245) should no longer be needed, as https://github.com/mozilla/application-services/pull/3963 will have made the default be correct."

The relevant code now lives in this repo: https://github.com/mozilla/application-services/blob/main/components/nimbus/android/src/main/java/org/mozilla/experiments/nimbus/Nimbus.kt#L384

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2848)

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

I’m moving this to the Nimbus board as I think that’s more appropriate. If it isn’t, please let me know.

**Comment by jhugman** [comment]
This is now an implementation detail of the Nimbus object, rather than part of the android-components codebase. Closing.
