### ISSUE TITLE
Consider using 'org.mozilla.apilint' to enforce JVM-level API consistency

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#521]
Agi Sferro built a nice plugin to keep a JVM-level API consistent: https://plugins.gradle.org/plugin/org.mozilla.apilint.

We might pick it up for the Application Services stack.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-93)

**Comment by vladikoff** [comment]
Closing this for now, we can add it in the future if needed
