### ISSUE TITLE
[Tabs] Add support for lastModified in ClientRemoteTabs

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5230]
We had to [manually add a lastModified](https://bugzilla.mozilla.org/show_bug.cgi?id=1800026) field manually on desktop due to [SyncedTabs needing it to display the "Last Synced" ](https://searchfox.org/mozilla-central/source/services/sync/modules/SyncedTabs.jsm#81). We should implement this in rust, which would help simplify the parts of the code on desktop that juggle that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3476)
┆Epic: Tabs on desktop follow-up work

**Comment by mhammond** [comment]
(that branch is on top of #5139, so I'll put a PR up one that lands)
