### ISSUE TITLE
autofill-crypto-error

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5232]
We've getting a relatively high volume of these on Sentry ([link](https://sentry.io/organizations/mozilla/issues/3727832765/events/eb69f5a839094c78850277b529d3a1b4/?project=6295546)).  We should track down the cause and either fix it or decide that it's expected and we shouldn't be reporting the errors to sentry.

One weird part about all of this is we have a canary check, but somehow it didn't identify this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3488)
┆Sprint End Date: 2022-11-25

**Comment by lougeniaC64** [comment]
@bendk I was seeing decryption errors but not deserialization errors (although you are getting better logging data on Android). Unfortunately the errors I was investigating involved a spike of login decryption errors for firefox iOS v98.0 through v99.3 and we couldn't find a root cause because we caught wind of it after the fact.

There are still a few login decryption errors being reported (see [here](https://sentry.io/organizations/mozilla/issues/?project=6176941&query=Error+while+decrypting+login&referrer=issue-list&statsPeriod=14d)), but I can't be sure that the current errors are related to the spike.

**Comment by bendk** [comment]
Error reports from 96.0.1 indicate that this is happening with the empty string as a key.

**Comment by bendk** [comment]
Actually, I realize now that the JWE data is not the key, but the CC number.  I'm pretty sure this is caused by us scrubbing the encrypted CC data, which sets those values to the empty string, then trying to decrypt it.

I was able to reproduce by hacking a-c to always scrub the data on startup.  After that, I saw the error whenever I went into the saved cards settings page, then clicked on a card.  Note that the list display was fine, since it only displays the last 4 digits.

Based on the Sentry errors, I think this also happens during Sync, although I couldn't reproduce that.  Actually, what's weird is that when I sync the data doesn't get repaired like I thought it should.  I'll try to check that out as well.

**Comment by bendk** [comment]
Checked out this one a bit more and found that:
  - I couldn't reproduce the error during sync, and when I looked again at the Sentry data I couldn't find reports of it.  I'm pretty sure Sync just works with encrypted CC numbers.
  - Fenix has code to handle this about as well as it possibly can.  It skips the card for autofill and on the edit card page, it fills in all other fields and just leaves the number field blank.

**Comment by bendk** [comment]
Looks like the changes worked.  I checked the Sentry events for `v96.1.1` and the volume is way down.  There are reports for a single user `Crypto Error: Crypto error: NSS error: NSS error: -8190`, which is described as `Security library: received bad data`.  I'm guessing the got their DB corrupted in some way.  In any case, this seems fine for now and I'm going to move this to the icebox.

**Comment by bendk** [comment]
I'm going to close this one now.

We still have reports of this, but it's consistently lower volume and I'm pretty sure it's a differenc cause (#5670).
