### ISSUE TITLE
logins-deserialize-error

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5233]
We've getting a relatively high volume of these on Sentry ([link](https://sentry.io/organizations/mozilla/issues/3472192276/?project=6295546)).  Almost all of the volume has the message `Login has illegal field: Origin is Malformed` and is accompanied by a breadcrumb that mentions `RelativeUrlWithoutBase`.  We should track down the cause and either fix it or decide that it's expected and we shouldn't be reporting the errors to sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3487)

**Comment by bendk** [comment]
Sentry reports from 96.0.1 indicate that the issue is no scheme, which is what @mhammond guessed the issue was.

**Comment by mhammond** [comment]
Thanks Ben! So I guess the action here is to have these reports make less noise (ie, no sentry and a log::warn)?

**Comment by bendk** [comment]
I think most of these errors are at the point where we've done about as much as we can and the next step would involve another team.  I don't see any of these issues as important enough to try to get some cross-team taskforce together, so what should be the next step?  I think it's some combination of these things, which ones make sense to you?

  - Replacing the Sentry reports with `log::warn`
     - Is it worth it to keep the Sentry reports for nightly?  The volume isn't very high and it could be useful if we get around to trying to fix them later.  OTOH, I think we've gotten enough information already so maybe it's not useful.  I think this would require some extra work at the android-components/fenix level as well.
  - #5253
  - Creating a good paper trail.  I think we should add a summary to our issues and move them to the icebox. 
    - Does it make sense to open Desktop/Android issues as well?

**Comment by mhammond** [comment]
Changing Sentry to log::warn makes pefect sense. I don't think it's worth keeping on Nightly as we believe we have a good understanding of what is causing it, so we don't expect Sentry to tell us anything we already know. Obviously, comments in the code would be super helpful and if they point at this issue (and/or any others :) then I think that's enough of a paper trail, especially given that there are no user reports around this issue (ie, there's no evidence users perceive anything as broken here - they probably don't really know the login exists and it probably isn't usable on desktop either)

I don't think we need special telemetry support here - our existing sync telemetry should already be recording this as a "failed" record (but we should check that!) and I think that's probably enough.

I'm also not too bothered by having a desktop issue - the desktop logins team is aware of the issue, so I doubt opening a bug will cause anything to change there. OTOH, I also don't object to it. Serg on #credentials-management said he was going to open one, but I haven't seen one swing by yet.

**Comment by bendk** [comment]
Sounds good to me.  So to summarize:
 - These errors happen with URLs without a scheme (no `:` char in them).  This is based on sampling of the Sentry reports and only seeing those errors.
 - We know that Desktop can save URLs like this through the JS API, although both the normal logins UI and the import UI prevent them.
 - The next step would be to do some Desktop work, but it doesn't seem important enough to do that so we're putting it on hold for now.

**Comment by mhammond** [comment]
Let's call this done.
