### ISSUE TITLE
places-url-parse-error

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5235]
This is our number 2 issue by number of events.    A quick scan of the events shows that they are happening in `noteHistoryMetadataObservation()` and the message reads `relative URL without a base` (similar to #5233)`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3490)
┆Epic: Error handling
┆Sprint End Date: 2023-01-06

**Comment by mhammond** [comment]
See also #4909

**Comment by bendk** [comment]
Sentry errors from `96.0.1` indicate the issue is an "invalid scheme" -- based on this definition:

```
alpha *( alpha | digit | "+" | "-" | "." )
```

No clue why it doesn't, maybe we could check in with the android team and see if they have any guesses?  We could also log the invalid char, but I would want data review to be sure that doesn't constitute a PII leak.

**Comment by bendk** [comment]
Looks like we've figured this out as well as we can, the next step would probably be add code in android-components to figure out where the invalid schemes are coming from (maybe [here](https://github.com/mozilla-mobile/firefox-android/blob/9a41f9e49ccab08075a0dd067550804f6bf0f4c7/android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L403-L429)?)

However, it doesn't seem that this issue is worth investing more effort in at this point, so the app-services team is going to put it on hold.

**Comment by bendk** [comment]
Checked the sentry logs after this and the volume is down, but there are still many reports.   A quick scan showed `invalid IPv4 address`, ` invalid domain character`, and  `invalid international domain name` as the top errors.

I sent a message to the android team asking what to do.  IMO we should either investigate more, or stop reporting all invalid URL errors from `note_history_metadata_observation`

**Comment by bendk** [comment]
I asked on Sentry and didn't get any takers to fix this one, so let's just accept that we're going to get invalid URLs sometimes and stop reporting Sentry errors for them.  Made #5304 to do that.

**Comment by bendk** [comment]
#5304 got merged a couple days ago, closing this one.
