### ISSUE TITLE
Places connection busy errors

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5237]
We have 2 Sentry issues from places `database is locked` errors:

* [places-no-registered-sync-engine](https://sentry.io/organizations/mozilla/issues/3727665329/events/04cf5d068461440da3bbe0fc6cc61e99/?project=6295546&query=is%3Aunresolved+rusterrors&referrer=next-event&sort=freq&statsPeriod=14d) happens when we get a `database is locked` error when trying to open a sync connection (at least I think that's the only codepath for this)
* [places-connection-busy](https://sentry.io/organizations/mozilla/issues/3727379779/events/9642444643484fbe9f6fea47ee510e7a/?project=6295546) happens when trying to execute a places DB operation.  Based on a quick scan, it seems to always happen when we're in the middle of syncing.

We should either update our code to avoid these errors or decide that they're expected and we shouldn't be generating Sentry reports for them.  The volume is fairly high, so I think we should update the code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3492)
┆Epic: Prioritized from backlog
┆Sprint End Date: 2023-02-24

**Comment by bendk** [comment]
A side issue here is that we now have proof that Sentry breadcrumbs can come in the wrong order: https://sentry.io/organizations/mozilla/issues/3727379779/events/9642444643484fbe9f6fea47ee510e7a/.

The `(X)` number at the end of the breadcrumb is generated from an atomic counter in the Rust code.  If we trust that -- and I think we should -- then it means that the breadcrumb entries are duplicated and out of order.  It also seems like the `(1)` entry was filtered out by Sentry.

**Comment by mhammond** [comment]
I'm guessing we also can't trust the timestamps - everything there happening in the same second is suspect.

If a [cooperative transaction](https://github.com/mozilla/application-services/blob/main/components/places/src/db/tx/coop_transaction.rs) takes longer than 5 seconds, these errors are "expected" - it's just that it taking 5 seconds is not.

I've no ideas off the top of my head how to push further here.

**Comment by bendk** [comment]
I did some testing with the `places-no-registered-sync-engine` error by using `places-utils` and adding a second thread that opened a ReadWrite transaction, then slept.  I observed errors when the sleep was over 5 seconds and no errors when it was under.  Using the #5251 code I was able to reproduce the same result with different busy timeouts.

So I'm thinking that this is just expected and we should not log this as an error.

**Comment by bendk** [comment]
It seems like we can accept this error, given that it happens to a small percentage of the population, likely on outdated devices.  Let's put this on hold and stop reporting these errors to Sentry.

**Comment by bendk** [comment]
Talked to @mhammond a bit more about this one and we think it's worth it to take one more pass on this one.  At the start of the next nightly cycle, let's try to increase the busy timeout to 10 seconds and see how that affects the sentry issues coming in.

**Comment by bendk** [comment]
Github closed this one me, but there's still work to be done.  App-services `96.3.0` was merged about two weeks ago, and contained the timeout change.  So far, it doesn't seem to affect the error rates:
 - [places-connection-busy before 96.3.0](https://sentry.io/organizations/mozilla/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=places-connection-busy%3A+Error+executing+SQL%3A+database+is+locked&project=6295546&query=issue%3AFENIX-NIGHTLY-32H+%21ac.as.build_version%3A96.3.0&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)
 - [places-connection-busy after 96.3.0](https://sentry.io/organizations/mozilla/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=places-connection-busy%3A+Error+executing+SQL%3A+database+is+locked&project=6295546&query=issue%3AFENIX-NIGHTLY-32H+ac.as.build_version%3A96.3.0&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29) 
 - [places-no-registered-sync-engines before 96.3.0](https://sentry.io/organizations/mozilla/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=places-no-registered-sync-engine%3A+places%3A+get_registered_sync_engine%3A+Error+opening+database%3A+Error+executing+SQL%3A+database+is+locked&project=6295546&query=issue%3AFENIX-NIGHTLY-32P+%21ac.as.build_version%3A96.3.0&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)
  - [places-no-registered-sync-engines after 96.3.0](https://sentry.io/organizations/mozilla/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=places-no-registered-sync-engine%3A+places%3A+get_registered_sync_engine%3A+Error+opening+database%3A+Error+executing+SQL%3A+database+is+locked&project=6295546&query=issue%3AFENIX-NIGHTLY-32P+ac.as.build_version%3A96.3.0&sort=-timestamp&statsPeriod=90d&yAxis=count())
 
Let's continue monitoring, but it looks like it's not going to be this simple.  Note that 96.4.0 was merged in today, which means we'll need to update the queries to look at future data.

**Comment by bendk** [comment]
Checked again today and the error rates are the same to my eyes.  Let's revert the timeout change and stop reporting errors to sentry.
