### ISSUE TITLE
Expose telemetry data to glean on android

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#524]
In #490 we added support for collecting telemetry data, but currently this data is discarded very close to the FFI layer. We need to expose this to consumers so LockBox etc can get telemetry data - however, this would be a breaking change, so we need to proceed carefully.

cc @linuxwolf, @irrationalagent

**Comment by vladikoff** [comment]
from mtg: 

* what kind of telemetry do we need?
* meeting tomorrow

**Comment by irrationalagent** [comment]
We met about this today, and @linacambridge will be working on sending the sync metrics via glean, one ping per engine sync.

**Comment by linacambridge** [comment]
Here are the [docs for Desktop's sync ping](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/sync-ping.html).
