### ISSUE TITLE
Data review: Fine-grained places maintenance timing metrics

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5247]
> 1) What questions will you answer with this data?

- Which part(s) of the places maintenance operation is taking the bulk of the time
 
> 2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

- The operation locks the database, so if it's running for too long it will impact any other operation that accesses the places DB.

> 3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

We started by timing the entire operation (#5122) and the initial results suggest that it's potentially too slow for a portion of our users (the 95th percentile was about 5 seconds).

> 4) Can current instrumentation answer these questions?

Not that we know of.

> 5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.

- Measurement Description: Time spent on the `prune_older_visits()` function.
  Data Collection Category: Category 1 “Technical data”
  Tracking bug: https://github.com/mozilla/application-services/issues/5246

- Measurement Description: Time spent on the `VACCUM` operation.
  Data Collection Category: Category 1 “Technical data”
  Tracking bug: https://github.com/mozilla/application-services/issues/5246

- Measurement Description: Time spent on the `PRAGMA optimize` operation
  Data Collection Category: Category 1 “Technical data”
  Tracking bug: https://github.com/mozilla/application-services/issues/5246

- Measurement Description: Time spent on the `PRAGMA wal_checkpoint` operation
  Data Collection Category: Category 1 “Technical data”
  Tracking bug: https://github.com/mozilla/application-services/issues/5246

> 6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/

> 7) How long will this data be collected?  Choose one of the following:

This is scoped to a time-limited experiment/project until date 04-01-2023

> 8) What populations will you measure?

All channels in all countries in all locales, for Android

> 9) If this data collection is default on, what is the opt-out mechanism for users?

Standard Firefox telemetry controls

> 10) Please provide a general description of how you will analyze this data.

We will examine a histogram of the time taken for each operation and compare them to determine which operation(s) are taking the majority of the time.  Based on that we may decide to tune the `run_maintenance()` function.

> 11) Where do you intend to share the results of your analysis?

The SACI and Android teams

> 12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:

No

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3496)

**Comment by eliserichards** [comment]
> > 1. What questions will you answer with this data?
> 
>     * Which part(s) of the places maintenance operation is taking the bulk of the time
> 
> 
> > 2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
>     * The operation locks the database, so if it's running for too long it will impact any other operation that accesses the places DB.
> 
> 
> > 3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> We started by timing the entire operation (#5122) and the initial results suggest that it's potentially too slow for a portion of our users (the 95th percentile was about 5 seconds).
> 
> > 4. Can current instrumentation answer these questions?
> 
> Not that we know of.
> 
> > 5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
>     * Measurement Description: Time spent on the `prune_older_visits()` function.
>       Data Collection Category: Category 1 “Technical data”
>       Tracking bug: [More fine-grained run_maintenance metrics #5246](https://github.com/mozilla/application-services/issues/5246)
> 
>     * Measurement Description: Time spent on the `VACCUM` operation.
>       Data Collection Category: Category 1 “Technical data”
>       Tracking bug: [More fine-grained run_maintenance metrics #5246](https://github.com/mozilla/application-services/issues/5246)
> 
>     * Measurement Description: Time spent on the `PRAGMA optimize` operation
>       Data Collection Category: Category 1 “Technical data”
>       Tracking bug: [More fine-grained run_maintenance metrics #5246](https://github.com/mozilla/application-services/issues/5246)
> 
>     * Measurement Description: Time spent on the `PRAGMA wal_checkpoint` operation
>       Data Collection Category: Category 1 “Technical data”
>       Tracking bug: [More fine-grained run_maintenance metrics #5246](https://github.com/mozilla/application-services/issues/5246)
> 
> 
> > 6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> >    This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/
> 
> > 7. How long will this data be collected?  Choose one of the following:
> 
> This is scoped to a time-limited experiment/project until date 04-01-2023
> 
> > 8. What populations will you measure?
> 
> All channels in all countries in all locales, for Android
> 
> > 9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> Standard Firefox telemetry controls
> 
> > 10. Please provide a general description of how you will analyze this data.
> 
> We will examine a histogram of the time taken for each operation and compare them to determine which operation(s) are taking the majority of the time. Based on that we may decide to tune the `run_maintenance()` function.
> 
> > 11. Where do you intend to share the results of your analysis?
> 
> The SACI and Android teams
> 
> > 12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
> 
> No

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

    * Yes, through the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

    * Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

    * No, the data will be collected for a fixed amount of time (until April 1, 2023) with the option to remove/renew at that point.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

    * Category 1 - technical data

5) Is the data collection request for default-on or default-off?

    * Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

    * No

7) Is the data collection covered by the existing Firefox privacy notice? 

    * Yes

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

    * No

## Result

data-review+

**Comment by eliserichards** [comment]
I think you should be able to see some trends just by collecting it this way. If the data doesn't seem to be telling us anything after a few months, we can try to correlate it then.
