### ISSUE TITLE
Add telemetry support to error handling

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5253]
We're at the point where we have expected errors that we don't think are really worth reporting to Sentry, but seem like they would be worth tracking in telemetry (#5237).  I think we should add a system like this to handle them:

- Add a new `ApplicationErrorMetrics` callback interface with a `void count_error(string type_name)` method to [errorsupport.udl](https://github.com/mozilla/application-services/blob/main/components/support/error/src/errorsupport.udl)
- Add a `support/error/metrics.yaml`  file with a single labeled counter metric.
- In our android wrapper code, we implement `ApplicationErrorMetrics` by incrementing the Glean counter with the error type, and add a method that Fenix can call to hook it up.

It would be way nicer to do all this in Rust, but I don't think we should wait for that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3499)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866543

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
