### ISSUE TITLE
[fxa-client] differentiate the types of errors

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/application-services#528]
Currently all errors from fxa-client are of a single type (`FxaException`), requiring an API user to parse the message to determine if the failure is network-related, authentication/authorization failures, or some other reason.

Instead, errors should be differentiated by type, at a minimum:

* network-related errors (offline, socket errors, TLS errors, etc)
* authentication/authorization errors (revoked tokens, invalid/deleted account, etc)
* Everything else

**Comment by eoger** [comment]
Yup, that's pretty much https://github.com/mozilla/application-services/issues/479.
Auth errors should be already differentiated with `FxaException.Unauthorized`

**Comment by eoger** [comment]
We now have 4 different classes of exception for FxA:
https://github.com/mozilla/application-services/blob/ab27bb1a66fca0bb4770215d710308de8710d9d2/components/fxa-client/android/src/main/java/org/mozilla/fxaclient/internal/FxaException.kt#L12-L15

Shall we close this issue @linuxwolf ?
