### ISSUE TITLE
Create `requirements.txt` for the automation directory

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5281]
@jeddai was recently cutting a released and noticed that they had to install `pyyaml` manually. Lets add a `requirements.txt` file and include a `pip3 install` step in our docs in https://mozilla.github.io/application-services/book/howtos/cut-a-new-release.html?highlight=release#make-a-new-release-from-latest-main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3518)

**Comment by ylogx** [comment]
Created a PR for this: https://github.com/mozilla/application-services/pull/5855.
