### ISSUE TITLE
Error parsing JSON data: missing field `last_modified`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5284]
We're seeing a good deal of [Sentry events](https://sentry.io/organizations/mozilla/issues/3745938472/?project=6295546&referrer=issue-stream&sort=freq&statsPeriod=14d) for this, starting today after `96.1.2` was taken by a-c.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3519)

**Comment by mhammond** [comment]
For more context: after upgrading to a version with this regression, the apps will fail to get any remote tabs until the next tabs sync happens. So for most users, the breakage will be relatively short and self-repair, but there's a v96.1.3 a-s release with the fix which consumers should probably take.

**Comment by mhammond** [comment]
Done!
