### ISSUE TITLE
Consider checking in Cargo.lock

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#529]
Cargo.lock lists the versions of dependencies we're building with. In general, the recommendation for rust code is to check it in for executables, and not for libraries, and since we aren't producing executables, we don't check it in.

However, we don't (generally) produce libs that are intended for use outside of this repo, and while we don't produce executables, we still produce native binaries (shared libraries).

This should be a fairly trivial change.

**Comment by vladikoff** [comment]
How come we didn't do this before?  Was it because rust libs are not supposed to do that?

anyway, i am +1 to this

**Comment by thomcc** [comment]
Yes, that's the reason. When we started this repo it wasn't clear exactly how this would take shape.

And worth noting, doing this would have prevented the issue in #530.
