### ISSUE TITLE
Create a Rust component for a Merino client

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#5345]
As part of bringing Desktop's Firefox Suggest Online experience to Firefox for Android and iOS, we'd like to add a new Rust component that fetches search suggestions from the Merino server. The API surface of this component will be pretty small—make an HTTP request, parse the response with Serde, and expose it via UniFFI to Kotlin and Swift—and feels like a great way for our team to learn how we ship cross-platform components on mobile!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2219)
┆Epic: Merino on Mobile Experiment
┆Sprint End Date: 2023-02-07

**Comment by tarikeshaq** [comment]
WOHOO I'm super excited to see more cross-platform components, so please feel free to let me know if there is any way the sync team can support here (doubt you'll need much of it 😛) 

Happy to provide reviews, an extra pair of eyes wherever needed, or any type of admin work on the repo

**Comment by linabutler** [comment]
Yep, it is!
