### ISSUE TITLE
Explore adding support for interrupting in-flight requests to Viaduct

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#5356]
The DOM `fetch` API lets a caller [interrupt an ongoing request](https://developer.chrome.com/blog/abortable-fetch/) by passing an `AbortSignal` in the `signal` option. Desktop's Merino client [uses this feature](https://searchfox.org/mozilla-central/rev/7a9e3bbab8f81c2cbc72a394047f948da9cfef9a/browser/components/urlbar/MerinoClient.sys.mjs#229,236,254) to cancel pending requests for suggestions from the Merino server as the user keeps typing into the awesomebar.

Viaduct doesn't currently support interrupting requests, so all requests will run to completion, and block the calling thread until they're done. Even when the request is made from a background thread (or Kotlin coroutine / dispatch queue), the caller can't make a new request on that thread until the old request is done.

Viaduct does have a `timeout` option, but this is slightly different: we want to interrupt a request in response to some condition (the user typing more input), rather than after a fixed amount of time.

There are lots of tricky parts to doing this, so it might not be worth all the extra complexity in the end—but I wanted to capture the issue for discussion, anyway!

* On iOS, we use the `reqwest::blocking` backend, which doesn't support interruption. It spawns a background thread to run the request, and blocks the calling thread. I think we'd need to either reimplement the blocking `reqwest` client using the async client, or ask `reqwest` to support this upstream.
* On Android, we route requests through Android Components, which eventually sends them to GeckoView. GeckoView's fetch client doesn't support interruption, so we'd have to plumb it through the GeckoView C++ (`WebExecutorSupport`) and Java (`GeckoWebExecutor`) layers, and then figure out how to surface that in Android Components (`concept-fetch`, `engine-gecko`, plus the other concrete `concept-fetch` backends).
* On Desktop, we can add abort plumbing to `ViaductRequest`. This feels a lot more doable than iOS and Android, but there are still devilishly detailed things (like what kind of API do we provide in Viaduct, and how do we signal that a request was interrupted to the backend?) that we'll need to figure out.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3578)

**Comment by bendk** [comment]
I have no clue how to handle this on the platforms, but on the UniFFI side it seems like you need to a way to pass an opaque foreign object around.  The caller would pass in some sort of cancellation object, UniFFI boxes it up, then `viaduct` would pass it back to the backend.  This gives the caller a way to signal to the backend that they want to cancel the request.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866366

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
