### ISSUE TITLE
Remove or update run-beta-tests-periodically

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5357]
These tests run our CI with the beta Rust version every so often (I think daily).  If we run the CI with a newer rust version, then we should expect trybuild failures since the error messages will change ([example](https://app.circleci.com/pipelines/github/mozilla/application-services/32622/workflows/6ea29e70-339a-4911-a937-685134db6bdb))

We should either remove these tests or update them to not run trybuild tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3580)

**Comment by tarikeshaq** [comment]
Hmmm what's the value of these tests? We enforce a specific rust minimum version and don't suggest that we support any other versions. So unless there is a specific type of test that only beta Rust can run (even then, we should optimize so it only runs those!) I say we kill the jobs. Should be as easy and deleting a bit of yaml
