### ISSUE TITLE
Provide control for Client over FxALogs

### ISSUE THREAD

**Issue by lmarceau** [mozilla/application-services#5358]
On Firefox for iOS we are seeing logs from [FxALogs](https://github.com/mozilla/application-services/blob/main/components/fxa-client/ios/FxAClient/FxAccountLogging.swift) in our console. I was wondering if there would be any way to pipe those logs through our own logger. In other words, surface them back like [RustLog](https://github.com/mozilla-mobile/firefox-ios/blob/8fd13bc41cd1e70873c5b5d0b4a49e98c21d9811/Providers/Profile.swift#L259) is doing. Having control over when/what log level is showing would be great.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3584)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866367

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
