### ISSUE TITLE
Document our current release process

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#536]
With appologies if this already exists, but I couldn't find it by poking around in the wiki or docs.

There have been a couple of conversation threads recently around our release process and how we might improve the experience for our consumers and ourselves.  One good starting point could be to clearly document the steps involved in making a new release of app-services, including any steps that need to be taken outside of this repo to allow end-consumers like lockbox to start using it.

In an ideal world there would be only a single step, and the documentation would just read "Run this command: <...>", but I infer from discussions that it's currently more involved than that.

**Comment by thomcc** [comment]
I don't mind doing this, and can probably find time tomorrow. Is putting a page on the wiki acceptable?

**Comment by rfk** [comment]
Thanks @thomcc!

> Is putting a page on the wiki acceptable?

Per slack discussion, let's put it somewhere inside the repo itself ("docs" folder?) and we can move it around later as part of a broader docs refactor.
