### ISSUE TITLE
Remove `rc-log`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5363]
#5362 adds the `rustlogs` component intended to replace `rc-log`.  Once our consumer apps switch over to using this, let's remove `rc-log`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3589)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866368

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
