### ISSUE TITLE
Switch fxa_client from using mockiato to using mockall

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5368]
mockiato is a trait mocking library for unit tests used throughout fxa_client. Mockiato hasn't been updated in 4 or so years, and [mockall](https://crates.io/crates/mockall) seems like what the Rust community is adopting for trait mocking.

This ticket will be a great start for someone new to fxa_client to get around the component

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3599)

**Comment by tarikeshaq** [comment]
Adding more context as we believe this could be a good first/second bug.

This ticket would mean:

1. updating the `Cargo.toml` in `fxa_client` in: https://github.com/mozilla/application-services/blob/70bebedbec9245ff6802bbaae26698dff6ce9b5a/components/fxa-client/Cargo.toml#L34
with
```toml
mockall = "0.11"
```

2. We would replace the `mockiato` proc-macro attribute on `FxAClient`, with the `mockall::automock` attribute in:
https://github.com/mozilla/application-services/blob/70bebedbec9245ff6802bbaae26698dff6ce9b5a/components/fxa-client/src/internal/http_client.rs#L55

3. We would replaces uses of `FxAClientMock` with the new `MockFxAClient` that `mockall` defines. For example, in the migration tests in: https://github.com/mozilla/application-services/blob/70bebedbec9245ff6802bbaae26698dff6ce9b5a/components/fxa-client/src/internal/migrator.rs#L225-L235

would become:

```rs
        let mut client = MockFxAClient::new();
        client
            .expect_duplicate_session_token()
            .with(always(), eq("session"))
            .times(1)
            .returning(|_, _| Ok(DuplicateTokenResponse {
                uid: "userid".to_string(),
                session_token: "dup_session".to_string(),
                verified: true,
                auth_at: 12345,
            }));
```

4. Rinse and repeat with every use of mocking the `FxAClient`.  The documentation in https://docs.rs/mockall/latest/mockall/ will be useful as you go through this. Any ambiguity or uncertainty I'll be happy to help!

**Comment by edgerunnergit** [comment]
Hello, could you please assign me to the issue? I would like to work on it.

**Comment by nox1134** [comment]
Hi @tarikeshaq ! If no one is working on this issue, I'd like to take up this issue and work on it.
Could you please assign the issue to me?

**Comment by mhammond** [comment]
Thanks @nox1134!
