### ISSUE TITLE
[RUST][places::error] Unexpected error: SqlError(InvalidColumnType(0, "score", Null)) is the top error for iOS on Sentry

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5372]
The top iOS error for rust-related issues is https://sentry.io/organizations/mozilla/issues/3047954317/?project=6176941&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d

Error Message from the link above: 
~~`[RUST][uniffi::ffi::rustcalls] Caught a panic calling rust code: "called `Result::unwrap()` on an `Err` value: Error(Error executing SQL: no such table: fennec.bookmarks)"`~~

1. `[RUST][logins::error] Crypto error`
2. [RUST][places::error] Unexpected error: OpenDatabaseError(SqlError(SqliteFailure(Error { code: SystemIOFailure, extended_code: 4874 }, Some("disk I/O error"))))

We should see if we can (1) Fix this issue, or if it's a non-issue/unavoidable (2) stop logging it to sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3602)

**Comment by skhamis** [comment]
Hmm sentry link seemed to have changed on me...now it's saying it's actually a places error -- going to rename this...

**Comment by tarikeshaq** [comment]
@skhamis the sentry error is a catch-all for all `log::error` 😭 The new error-reporter should fix this and separate them into separate issues

**Comment by skhamis** [comment]
Ah that makes sense why the errors keep changing. I'll close this for now (and we'll have reference in case this pops up again)
