### ISSUE TITLE
Decide on a new high-level FxA API

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5395]
We want to expand the functionality of our FxA client code so that consumers can use it without needing so much wrapper code. In order to do that, we need to decide what the API should be.

Some guidelines:

* The API should be roughly comparable to the [High level FxAAccountAManager API](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/service/firefox-accounts/README.md#high-level-apis-recommended-for-most-applications) from android-components.
* The API should be relatively easy to integrate on iOS and Android (hopefully Desktop as well, but that's secondary).
* The API should be compatible with UniFFI

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3627)
┆Epic: Wrapper-less FxA

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866521

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
