### ISSUE TITLE
Switch Android to using the new high-level FxA API

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5396]
Switch firefox-android to using the new high-level FxA API (#5395).  This will mostly be moving Kotlin code from firefox-android into the application-services Kotlin wrapper, without changing the underlying Rust code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3626)
┆Epic: FxA 2023 H1 component work

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866522

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
