### ISSUE TITLE
Switch iOS to using the new high-level FxA API

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5397]
Switch firefox-ios to using the new high-level FxA API (https://github.com/mozilla/application-services/issues/5395). This will mostly be moving Swift code from firefox-ios into the application-services Swift wrapper, without changing the underlying Rust code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3625)
┆Epic: FxA 2023 H1 component work

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866523

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
