### ISSUE TITLE
Implement the high-level FxA API with UniFFI

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5398]
Implement the high-level FxA API in Rust and expose it with UniFFI.  Let's do this last, after deciding on the API (#5395) and updating the consumer code to use it (#5386, #5397).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3624)
┆Epic: FxA 2023 H1 component work

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866524

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
