### ISSUE TITLE
Investigate using the high-level FxA API on Desktop.

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5399]
Once we've decided on a high-level FxA API (#5395), and moved Android and iOS to use it (#5396, #5397), let's investigate how much of it could be used on Desktop as well.

At minimum, we should be able to use it for OAuth ([https://mozilla-hub.atlassian.net/browse/SYNC-3759](https://mozilla-hub.atlassian.net/browse/SYNC-3759|smart-link) )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3623)
┆Epic: Wrapper-less FxA

**Comment by mhammond** [comment]
I'm not sure there's value transferring this to bugzilla.
