### ISSUE TITLE
[push] Generate Crypto sub-component

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#541]
Module performs all cryptographic processing functions. 

Required by:
* subscriber
* notifier
* storage (Requires `Key` structure as part of `PushRecord`)

+ [x] code
+ [x] tests

**Comment by pjenvey** [comment]
Marking this closed as of #565 (already marked done here too https://github.com/orgs/mozilla/projects/59)

We can reopen it if further crypto needs crop up
