### ISSUE TITLE
Help building on Fedora

### ISSUE THREAD

**Issue by jo** [mozilla/application-services#5414]
I'm trying to build the project - at least running the test suite - on Fedora. I followed [the steps](https://github.com/mozilla/application-services/blob/main/docs/building.md#linux) and I get a `NoNssDir` error:

```sh
$ RUST_BACKTRACE=1 cargo test
   Compiling this and that...
   Compiling num-traits v0.2.15
error: failed to run custom build command for `nss_sys v0.1.0 (/home/jo/git/application-services/components/support/rc_crypto/nss/nss_sys)`

Caused by:
  process didn't exit successfully: `/home/jo/git/application-services/target/debug/build/nss_sys-eddc484f54a37c61/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NSS_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoNssDir', components/support/rc_crypto/nss/nss_sys/build.rs:6:34
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
     2: core::result::unwrap_failed
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
     4: build_script_build::main
               at ./build.rs:6:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have searched through the NSS docs but was not able to find any hint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3634)

**Comment by jo** [comment]
Hi @tarikeshaq thank you very much, this helped me coming way further!

One thing we could maybe note in the prerequisites doc: one has to execute `./libs/verify-desktop-environment.sh` twice. First time it will inform about the required environment variables, and the second time it will compile the libs. Ping me if you like me to send a pr.

Now it stopped with
```
$ cargo test
   Compiling this and that...
error: linking with `cc` failed: exit status: 1
  |
 = note: "cc" [long list of object files] "-Wl,-Bdynamic" "-lxcb" "-lxcb-render" "-lxcb-shape" "-lxcb-xfixes" "-lstdc++" "-lstdc++" "-lsqlcipher" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/jo/.rustup/toolchains/1.66.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/jo/git/application-services/target/debug/examples/tabs_sync-ff3a99ec0f4ddf6f" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
 = note: /usr/bin/ld: cannot find -lxcb: No such file or directory
          /usr/bin/ld: cannot find -lxcb-render: No such file or directory
          /usr/bin/ld: cannot find -lxcb-shape: No such file or directory
          /usr/bin/ld: cannot find -lxcb-xfixes: No such file or directory
          collect2: error: ld returned 1 exit status
          
error: could not compile `example-tabs-sync` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by tarikeshaq** [comment]
Hmmm that seems like missing native packages, I don't have a linux box (and I don't quite remember if I ran into this). From a quick google search, I imagine `libxcb-devel` or similar needs to be installed?

@bendk You have a linux machine, do you happen to remember if we need any other packages not listed in the docs? The docs currently only list:
>  
    Install the system dependencies required for building NSS
        Install gyp: apt install gyp (required for NSS)
        Install ninja-build: apt install ninja-build
        Install python3 (at least 3.6): apt install python3
        Install zlib: apt install zlib1g-dev
    Install the system dependencies required for SQLcipher
        Install tcl: apt install tclsh (required for SQLcipher)

If there are any more required packages we should add to the docs

Thanks @jo this is very helpful for us too! Once you're up and running and I'll put up a patch with all your pain points and get your review on it 🙏

**Comment by tarikeshaq** [comment]
It also looks like it's only needed by that example? I can't imagine we need X11 for our actual libraries 🤔 I think it's only needed by `clipboard`? TBH i'd prefer cleaning up that dependency vs adding installing more native libraries...

**Comment by jo** [comment]
Cool, thanks, installing `libxcb-devel` worked and let me run the tests. I'll search through my history and list some additional packages I also needed to install here.

**Comment by jo** [comment]
There are two additional packages I needed to install:
* `perl` (needed to [build openssl](https://github.com/openssl/openssl/issues/13761))
* `patch` (to build the libs, needed during `./libs/verify-desktop-environment.sh`)

**Comment by mhammond** [comment]
> It also looks like it's only needed by that example? I can't imagine we need X11 for our actual libraries 🤔 I think it's only needed by `clipboard`

Yeah, I keep hitting that. The clipboard thing is behind a feature, but it's a default feature - so `--no-default-features` works, but really that shouldn't be necessary - it would be fairly simple to replace use of the clipboard with just specifying a filename or similar, but it's never annoyed me enough to actually get around to it.
