### ISSUE TITLE
Synced history does not contain device information

### ISSUE THREAD

**Issue by josephcourtney** [mozilla/application-services#5420]
I might be missing something, but when pulling synced history data I don't see any way to find out what device was used to visit a given page. Is there a reason that the device id isn't or shouldn't be included when syncing?

Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3637)

**Comment by mhammond** [comment]
The main problem is that we don't have a "stable" device ID to use - ie, people replace their phones etc. https://bugzilla.mozilla.org/show_bug.cgi?id=1302797 and other linked bugs has a bit more context.
