### ISSUE TITLE
Fixup swiftformat build failures

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#5424]
Recently swiftformat has begun to show multiple errors in Swift files that previously did not. [For example](https://circleci.com/api/v1.1/project/github/mozilla/application-services/153464/output/106/0?file=true&allocation-id=6406477872793a211166e9ac-0-build%2F9DOUFPS5).

On a local machine:
```
$ ./automation/tests.py swiftformat

Running swiftformat
swiftformat megazords 'components/*/ios' --exclude '**/Generated' --exclude components/nimbus/ios/Nimbus/Utils --lint --swiftversion 5
Running SwiftFormat...
(lint mode - no files will be changed.)
SwiftFormat completed in 0.09s.
0/50 files require formatting, 9 files skipped.
```

This issue is to either fix the errant files, or investigate how the build has changed (e.g. a swiftformat upgrade/change), and make the errors go away.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3640)

**Comment by tarikeshaq** [comment]
Was this the same errors? fixed in #5257, have you tried rebasing?
