### ISSUE TITLE
Upgrade to Rust 1.68

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5435]
We're on the FX113 nightly, so based on our [Rust update policy](https://github.com/mozilla/application-services/blob/main/docs/design/rust-versions.md) we should update to Rust 1.68 to match [Desktop](https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3651)
┆Sprint End Date: 2023-04-07

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

I’m going to pass this one to Mark, since he made the Rust 1.68 PR.
