### ISSUE TITLE
Invalid incoming T: invalid type: null, expected a string

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5457]
This is a frequent [sentry issue](https://mozilla.sentry.io/issues/3796658061/?project=6295546) and is pinging our `sync-bots` channel.  We should investigate and fix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3677)
┆Epic: Investigate & fix rising error rates for sync engines
┆Sprint End Date: 2023-07-27

**Comment by bendk** [comment]
The above PR is the first step in dealing with this.  Let's try to get some more details from Sentry about the errors.

**Comment by bendk** [comment]
Looks like this issue is from the `title` field based on the [new reports](https://mozilla.sentry.io/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=invalid-incoming-content%3A+title%3A+invalid+type%3A+null%2C+expected+a+string&project=6295546&query=issue%3AFENIX-NIGHTLY-3DM&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)

**Comment by bendk** [comment]
@skhamis AFAICT, it seems like the `TabsRecordTab.title` field can be `null` in the wild, but I don't know how it can happen.  Should we fall back to an empty string or something?

**Comment by skhamis** [comment]
Ah interesting, yeah it shouldn't be null and we should probably de-serialize to empty anyways if it is null, however I'm not seeing in the reports the linkage back to tabs specifically?

**Comment by skhamis** [comment]
now I see some of the reports having:
```sync_manager::manager[213]: Checking engines requested (Some { engines: ["tabs"] }) vs local engines (["tabs"]) (40)```

so it's definitely related to tabs, yeah seems like ensuring we de-serialize null into empty string should drastically reduce this error! Hooray for better breadcrumbs!

**Comment by mhammond** [comment]
> invalid-incoming-content: tabs::sync::record::TabsRecord.tabs[0].lastUsed: invalid type: string "1683797411.98", expected i64

Fantastic - before now I don't think we knew exactly what this was! I wonder how that's happening though - maybe Fennec or old iOS versions did that and are still hanging around (I don't think it's likely they are old records as tabs have a relatively short ttl)

> sync15::clients_engine::record::ClientRecord.commands[3].args[2]: invalid type: null, expected a string

this makes zero sense to me at all!

**Comment by bendk** [comment]
> > invalid-incoming-content: tabs::sync::record::TabsRecord.tabs[0].lastUsed: invalid type: string "1683797411.98", expected i64
> 
> Fantastic - before now I don't think we knew exactly what this was! I wonder how that's happening though - maybe Fennec or old iOS versions did that and are still hanging around (I don't think it's likely they are old records as tabs have a relatively short ttl)

I think the next step would be to stop tracking this with sentry and start tracking it with telemetry somehow.  Maybe we could have a labeled counter that tracks weird sync errors by reason.  We could display this as a stacked graph on our dashboard.

> 
> > sync15::clients_engine::record::ClientRecord.commands[3].args[2]: invalid type: null, expected a string
> 
> this makes zero sense to me at all!

Looks like it's a single user for all events.  I believe the `clients_engine` code skip over client records that are malformed.  Maybe we should add a fixup function for this?

**Comment by bendk** [comment]
I took another look at this one today and it doesn't seem worth putting more effort into.  The errors are rare, only on nightly, and affecting a handful of users.
