### ISSUE TITLE
Cleanup the swift nightly build task 

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5492]
I was able to get the `swift-build` task to run, but there are a couple issues with it that we should fix as a follow up:
  - The ios tests don't run
  - It should be split up more, maybe into:
    - Rust toolchain task
    - Toolchain task that builds the `libs/ios` directory
    - Task that builds/tests MozillaRustComponents
    - Task that builds FocusRustComponents
      - We should consider also running tests here, but the current CircleCI task doesn't.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3693)
┆Epic: Automate build system for mobile consumption

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

This was implemented in https://github.com/mozilla/application-services/pull/5563 ( https://github.com/mozilla/application-services/pull/5563|smart-link )
