### ISSUE TITLE
Async-ify the Swift API

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#55]
Currently we call the rust crate code synchronously, which is very problematic since we make network requests.
I don't really know the Swift conventions, but I assume a callback function has to be passed as the last argument of an asynchronous function.

**Comment by mhammond** [comment]
This is also true for the sync code. One alternative @thomcc and I discussed was to have the FFI boundary (or close to it) arrange for a worker thread to do the actual work, but even this implies some degress of async. We should try and get a single consistent story here.

@thomcc, what are your thoughts?

**Comment by eoger** [comment]
Closed by https://github.com/mozilla/application-services/commit/404e290013b8d8cd2100017fe5978d5ba7e357c6
