### ISSUE TITLE
Refine error model for Remote Settings

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla/application-services#5566]
The Remote Settings component exposes more error types to application level consumers than is really necessary. Shrink that list down to a more realistic model of errors that an application might actually respond to.

[Original context](https://github.com/mozilla/application-services/pull/5423#discussion_r1183806814(

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3718)

**Comment by linabutler** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1874031

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
