### ISSUE TITLE
rust-components-swift nightly bump failing

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5573]
https://github.com/mozilla/rust-components-swift/actions/runs/4973018286

It looks like a permission problem to push - I imagine we need to get a token that has write permission instead of using the default one the Github action gets

cc @bendk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3721)
┆Epic: Automate build system for mobile consumption
┆Sprint End Date: 2023-06-02

**Comment by bendk** [comment]
https://github.com/mozilla/rust-components-swift/pull/112
