### ISSUE TITLE
Support streaming request and response bodies in Viaduct

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#5578]
Today, Viaduct takes the full request body as a `Vec<u8>` when making a `Request`, and buffers the full response body into memory before returning a `Response`. Over in https://github.com/mozilla/application-services/pull/5423#discussion_r1128729358, we were talking about how attachments downloaded from Remote Settings don't have fixed bounds on their size, which got me thinking about streaming large payloads in both directions.

I don't think this is a super high priority—we aren't uploading large files, and the Remote Settings attachments we're expecting to download are all < 200 KB—and it would be an unknown amount of work to implement in all the different backends. But I wanted to get an issue on file for it, even if we do punt it 'til later!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3723)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866529

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
