### ISSUE TITLE
Build and publish nimbus-cli

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5581]
`nimbus-cli` is a tool used by devs/testers to configure nimbus so it can be tested.  We should publish versions of `nimbus-cli` for this:

- Let's build this alongside the nightlies.  This seems like a reasonable balance between pushing out updates and not using too many worker resources
- This should be considered separate from the normal nightly build.  Users will generally want the latest `nimbus-cli` rather than using the same version as the rest of the app-services components.
- We can skip the windows binary for now
- The nightly build should publish a JSON file containing:
   - A link to binaries for each target
   - The git commit
   - The cargo version of `nimbus-cli`
   - build date

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3724)
┆Epic: Automate build system for mobile consumption
┆Sprint End Date: 2023-06-02

**Comment by bendk** [comment]
Fixed by https://github.com/mozilla/application-services/pull/5599

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

https://github.com/mozilla/application-services/pull/5599 ( https://github.com/mozilla/application-services/pull/5599|smart-link )
