### ISSUE TITLE
New branch build system

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5582]
I think we should adjust what branch builds do:
  - The android unittests are currently [intermittently failing](https://firefox-ci-tc.services.mozilla.com/tasks/groups/YnTP20u2QBqgv5E1NQtQOw).  Let's stop trying to run them
  - The code uses a system that's similar to the local autopublish, but slightly different.  Let's use autopublish directly
  - Let's add support for firefox-ios as well, using a local autopublish flow.

Basically, I think we can get better results if we lower our goals slightly.  Instead of trying to run all the unit tests, let's focus on seeing if we can build the app, which gives us most of the benefit but is simpler to implement.

The main goal of branch builds is to help a dev from the Android or iOS team review a PR in their repo to resolve a breaking app-services change.  Seeing that the app builds successfully is often all they need to know.

Another goal is testing tooling updates, for example an Android SDK update.  Again, knowing that the app builds is very important here.  Also we publish the app packages as artifacts, so you could run them in an emulator for a manual smoke test.

It would be nice to run the unit tests, but I think it's okay to give it up for now.  If we need to run the tests, we can still do it using a local autopublish flow.  If we figure out how to make the tests run reliably in the future, we can add them back in.

Finally this means we can remove the branch build gradle code and only have to maintain the autopublish code.  It also means the autopublish code will be run whenever we do a branch build, so we will see errors faster.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3727)

**Comment by bendk** [comment]
@rvandermeulen I think you've been the main user of this feature lately.  Do you think this will work okay for you?

**Comment by rvandermeulen** [comment]
I agree that my main concern when I utilize this is making sure that I'm not going to break downstream builds, yes. For the types of changes I'm making, introducing new test failures seems pretty unlikely.

**Comment by tarikeshaq** [comment]
I believe this system as stated landed so this is safe to close right @bendk ?
