### ISSUE TITLE
Doesn't open new url with "Open previous windows and tabs" set to on

### ISSUE THREAD

**Issue by kshah00** [mozilla/application-services#5625]
I have the setting "Open previous windows and tabs" set to on. When another app tries to open firefox with a link, firefox opens but doesn't show the new window, just the old ones...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3747)

**Comment by mhammond** [comment]
Sorry, this is the wrong place to report Firefox bugs.
