### ISSUE TITLE
Run a linter/code formatter over our python code

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5628]
We should create a task that runs some combination of linters / code format checkers over our python code -- especially the code in the `taskcluster` directory.  I'm not sure exactly what combination we should run, maybe `black` + `ruff`?  There should also be a script that devs can run that tries to fix any issues.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3748)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866530

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
