### ISSUE TITLE
Building/testing rust on circleci tend to run out of memory.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#567]
I suspect this is because we do everything in parallel, but don't have much data to back it up.

Edit: It has nothing to do with the parallelism of our tests.

**Comment by thomcc** [comment]
Oh, really? Is it seriously using more than 4GB?

**Comment by eoger** [comment]
Note for the people not in the loop: I've sent an email recently to the ops team to get bigger circleci machines

**Comment by thomcc** [comment]
I wonder if this is worse now because rust updated to 1.32... It's almost every build.
