### ISSUE TITLE
autofill-crypto-error: Crypto Error: EmptyCyphertext (single string field)

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5670]
We're getting a few hundred of these a day from firefox-android ([sentry](https://github.com/mozilla/application-services/issues/5232)).  I believe this means that Android is sending us empty strings to decrypt, likely because they credit card data was scrubbed.

Maybe the best fix is to update the android code not to do this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3769)

**Comment by mhammond** [comment]
> Maybe the best fix is to update the android code not to do this.

I believe that would just change the description of the error to something like "failed to decrypt due to invalid ciphertext" right? I think we need to dig more into how and why we are losing that ciphertext in the first place.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866531

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
