### ISSUE TITLE
Can't sign in to FxA using the pairing flow

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5675]
Potentially related context:

* Over the weekend my Firefox Android stopped working, so I reinstalled it
* I tried to connect my FxA account.  I successfully logged in, but didn't have access to my desktop so I wasn't able to enter the confirmation code.

This morning I tried to connect using the pairing flow.  Everything seemed to be working, but it seems like I never got to the `redirect_uri` (or firefox-android didn't recognize it).  I ended up on the account settings page and Firefox Android was not connected:

![Screenshot!UNITO-UNDERSCORE!20230620-104513](https://github.com/mozilla/application-services/assets/1012809/f1b93c2a-d017-4a36-85c8-f58201a764a7)

Afterwards, I believe I went through these steps:

* Tried the pairing flow a second time, without success.
* Logged out and tried the paring flow again, without success.  (I'm pretty sure I did this, but I could be misremembering).
* Logged out and tried the email flow, with success.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3775)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866532

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
