### ISSUE TITLE
Allow external error types

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5679]
It's not currently possible to use an error as an external type because of errors like:
```
thread 'main' panicked at 'unsupported type for error: External { name: "UniffiOneError", crate_name: "uniffi_one", kind: DataClass }', uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs:238:18
```

I think we should add support for this type and assume that it's an enum in the external crate.

**Comment by mhammond** [comment]
Did you open this in the correct repo? https://github.com/mozilla/uniffi-rs/issues/1605 reports a different symptom of what seems to be the same problem. This problem is also going to get worse if we start allowing interfaces as types :(

**Comment by bendk** [comment]
Yup, wrong repo.
