### ISSUE TITLE
when you open something in the separate "manage history" window there should be an option where it doesnt bring you to the top of it every time

### ISSUE THREAD

**Issue by RustoMCSpit** [mozilla/application-services#5732]
not even sure if this is the right repo for the firefox brower history but when i am going deep into my history and open something i dont want the history to bring me to the top, there should be an option where it doesnt bring you to the top after it updates with a new log

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3812)

**Comment by mhammond** [comment]
bugzilla.mozilla.org is the right place, but I think you are describing https://bugzilla.mozilla.org/show_bug.cgi?id=892485?

**Comment by RustoMCSpit** [comment]
> bugzilla.mozilla.org is the right place, but I think you are describing https://bugzilla.mozilla.org/show_bug.cgi?id=892485?

this bug is a decade old woah

**Comment by RustoMCSpit** [comment]
> bugzilla.mozilla.org is the right place, but I think you are describing https://bugzilla.mozilla.org/show_bug.cgi?id=892485?

what does this mean:
Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3812)
