### ISSUE TITLE
nimbus python bindings non-default argument follows default argument

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/application-services#5738]
Building the python bindings for nimbus I ran into this error.
```
File "/application-services/components/nimbus/src/nimbus_rust.py", line 989
E       def __init__(self, app_ctx: "AppContext",coenrolling_feature_ids: "typing.Union[object, typing.List[str]]" = DEFAULT,dbpath: "str",remote_settings_config: "typing.Optional[RemoteSettingsConfig]",available_randomization_units: "AvailableRandomizationUnits"):
E                                                                                                                            ^^^^^^^^^^^^^
E   SyntaxError: non-default argument follows default argument

![image](https://github.com/mozilla/application-services/assets/5751892/9e6a19ab-4150-4262-b7d0-85ffbd23faab)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3823)

**Comment by jrbenny35** [comment]
<img width="1640" alt="Screenshot 2023-07-21 150400" src="https://github.com/mozilla/application-services/assets/5751892/bd950f48-3ec9-4314-8945-ca2d69f3e91a">

**Comment by jeddai** [comment]
This specific issue has to do with how UniFFI generates Python bindings. UniFFI writes all arguments as positional arguments, unless that argument has a default value. As a result of this, we hit scenarios where it will write named arguments in the middle of a list of positional arguments, and Python doesn't like that. 

A reference for this on an existing PR https://github.com/mozilla/application-services/pull/5475#discussion_r1161607448

The solution should be something along the lines of adjusting the `coenrolling_feature_ids` argument such that it is the last argument in the NimbusClient's `new` method. Lots of tests are going to break from this, and we might need to make sure the Kotlin/Swift code that creates the clients makes the right adjustments as well. I'm not _sure_ they'll need to be adjusted though, they might be using named args for the constructor already.

**Comment by jhugman** [comment]
Closing in favour of https://github.com/mozilla/uniffi-rs/issues/1658
