### ISSUE TITLE
Support binary response bodies in Viaduct

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#5744]
@0c0w3 discovered that the Desktop Viaduct backend is [truncating response bodies](https://searchfox.org/mozilla-central/rev/3c7b40d1d74c26a82486f38b5828c3f3a43e05da/toolkit/components/viaduct/ViaductRequest.cpp#293) to the first null byte while integrating the Suggest component into Desktop. Viaduct's docstring for `Response::body` also says:

https://github.com/mozilla/application-services/blob/0912e3c81ca854e4223c4dbe3ba76a2a3a7de404/components/viaduct/src/lib.rs#L239-L241

Oops! 😅 Let's figure out what we'll need to change, and where, to support binary response bodies.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3831)

**Comment by tarikeshaq** [comment]
@0c0w3 is correct, doing some git digging looks like the a-s comment was left there from a time when the body was represented with a string type

going to close this ticket with https://github.com/mozilla/application-services/pull/5847 to remove the comment
