### ISSUE TITLE
Find alternate way to upload Android symbols

### ISSUE THREAD

**Issue by ahal** [mozilla/application-services#5762]
Since we are no longer using Github Releases to release app-services, we're removing all of the automation that previously got triggered there. Though one thing I noticed is that the `module-build` tasks invoke [automation/upload_android_symbols.sh](https://github.com/mozilla/application-services/blob/25972c388a4cf3a6d8256504f3a09b711db2fc6a/taskcluster/app_services_taskgraph/transforms/module_build.py#L30) if `tasks_for == github-release`. As of now, this condition will no longer ever be true, so we'll never run that script.

Also since the `module-build` tasks are no long part of the release graph (by design), we won't be able to tell at task creation time whether the build will be one that is released or not. So likely we'll need to create a new task that handles this and is run as part of the `ship` graph.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3844)

**Comment by tarikeshaq** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1889982
