### ISSUE TITLE
Potentially update roundtripping unknown fields in Places to match desktop

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5768]
When doing sync payload (roundtripping unknown fields) for desktop. @mak from the Places team had a great comment: https://phabricator.services.mozilla.com/D183224#6058831
relevant snippet from comment:
> Second thing, a question. I expect this unknown_fields field will only be populated for a subset of visits and only when there's a set of unknown fields. That means only a small subset of records will have a not null value. In the best case that's 2 bytes per record, that means in normally large db cases something around 300KiB-500KiB.
> I'm mostly wondering if it would make sense to split these into a separate moz_syncHistoryVisitsExtraFields table with just (vid, fields) and a Foreign Key on moz_historyvisits.id.
> While that may be a tiny bit more expensive on visits removal, it would provide a nice separation of concerns, I think.

We ended up going this route on desktop and it was much easier and cleaner overall. However, desktop was a bit more complex and there were more access points to the API so it's not quite clear we should do this on application services side as well. I created this issue to at least foster discussion in case we decide to pursue this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3848)

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866534

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
