### ISSUE TITLE
Add a Places API to recursively count the number of descendants in a folder

### ISSUE THREAD

**Issue by linabutler** [mozilla/application-services#5789]
[Fenix's `HomeActivity.onPause` fetches the entire bookmarks tree](https://github.com/mozilla-mobile/firefox-android/blob/a415402dcdaf57c6d71889d696e7a9de496f2850/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L560-L570), but it's only interested in the descendant count.

Fetching and building the tree does a fair bit of work behind the scenes, and creates lots of extra objects on both the Rust and Kotlin sides. I'm a little nervous about Fenix doing that in `onPause`, too; [the Android docs warn](https://developer.android.com/reference/android/app/Activity#onPause()) not to do anything lengthy in that method.

Let's make things a little easier for Fenix, and add an API to count descendants. The new API can use a more efficient SQL query, and pass just a single number over the FFI, instead of fully-formed `BookmarkNode` objects for every bookmark in the library. I think this would especially help users with large bookmark libraries.

Split out from #5773.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3887)

**Comment by MattLichtenstein** [comment]
hey @linabutler @mhammond, since the functionality already exists, would it be possible to expose the same API to swift?
