### ISSUE TITLE
FxA: getSessionToken() and friends can block

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5819]
In the FxA Kotlin wrapper, we have a lot of doc strings saying "this method performs network requests and should not be called on the main thread".  We also have methods like [getSessionToken](https://github.com/mozilla/application-services/blob/main/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/PersistedFirefoxAccount.kt#L250-L257) that leave that note off.

Those methods don't make network requests, however they can still block.  The Rust client has a single lock around all operations, so if another thread is making a network request, it will block the thread calling getSessionToken.  We should rework things so these methods can are truely non-blocking.  By that I mean they won't block on network requests, a shared mutex that just protects data should be okay.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3912)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866535

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
