### ISSUE TITLE
Data Review: Renew Places Maintenance Metrics

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5830]
# 1. Provide a link to the initial Data Collection Review Request for this collection.
* https://github.com/mozilla/application-services/issues/5122
* https://github.com/mozilla/application-services/issues/5247
* https://github.com/mozilla/application-services/issues/5387 (first renewal)

# 2.  When will this collection now expire?
Never. 

# 3.  was the initial period of collection insufficient?
After reviewing the metrics, especially [db size after maintenance](https://glam.telemetry.mozilla.org/fenix/probe/places_manager_db_size_after_maintenance/explore?aggType=avg&app_id=release&currentPage=1&timeHorizon=ALL), we determined that we want to do more to decrease user's DB sizes and that this will require continuing to monitor these metrics.

Since this is technical data with little risk of exposing PII, and it's something we will likely want to monitor for a long period of time, we thought an indefinite expiration was appropriate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3920)
┆Epic: Prioritized from backlog

**Comment by bendk** [comment]
@eliserichards Can you review this one?

**Comment by eliserichards** [comment]
> # 1. Provide a link to the initial Data Collection Review Request for this collection.
> 
>     * [Data review: Places maintenance metrics #5122](https://github.com/mozilla/application-services/issues/5122)
> 
>     * [Data review: Fine-grained places maintenance timing metrics #5247](https://github.com/mozilla/application-services/issues/5247)
> 
>     * [Data Review: Renew Places Maintenance Metrics #5387](https://github.com/mozilla/application-services/issues/5387) (first renewal)
> 
> 
> # 2. When will this collection now expire?
> 
> Never.
> # 3. was the initial period of collection insufficient?
> 
> After reviewing the metrics, especially [db size after maintenance](https://glam.telemetry.mozilla.org/fenix/probe/places_manager_db_size_after_maintenance/explore?aggType=avg&app_id=release&currentPage=1&timeHorizon=ALL), we determined that we want to do more to decrease user's DB sizes and that this will require continuing to monitor these metrics.
> 
> Since this is technical data with little risk of exposing PII, and it's something we will likely want to monitor for a long period of time, we thought an indefinite expiration was appropriate.
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes

---- 
data-review+

**Comment by eliserichards** [comment]
@bendk make sure that you put yourself as the code owner in the `notification_emails` of each of these metrics since they will not be expiring now :)
