### ISSUE TITLE
Fenix megazord

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#585]
Now that Fenix is starting to consume app-services libraries, it'll be good to define a megazord for it and consume that instead of dependencies piece-meal.

Fenix issue for this: https://github.com/mozilla-mobile/fenix/issues/309.

**Comment by vladikoff** [comment]
<img src=https://user-images.githubusercontent.com/128755/52004558-5f5a6f00-2495-11e9-82a5-234b1d747b46.jpg width=250 />
