### ISSUE TITLE
Invalid incoming ClientRecord

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5861]
We've been seeing a decent amount of Sentry reports for `invalid-incoming-content`, with the description `sync15::clients_engine::record::ClientRecord.commands[0].args[2]: invalid type: null, expected a string`.  Based on the [Sentry issue](https://mozilla.sentry.io/issues/3796658061/?project=6295546), there's been a few hundred events a day for the last few weeks.  About 90% of the events come from 2 users.

From a quick reading of the code, it doesn't seem like any command in the `sync15` crate uses more than a single argument so I'm not sure why there would be a command with the 3rd argument `null`.  Any ideas what could be causing this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3956)

**Comment by mhammond** [comment]
FTR, prior to bug 1587228 (Firefox 92), desktop used to be capable of sending tabs via commands. The send-tab command took 3 args, `[uri, clientId, title]`. But even then, it *preferred* to use push and checked the device registration - so the only way this can be explained by send-tab is that a Firefox version years older than that is trying to send a tab to Fenix! I'm mildly surprised null would end up in the title arg, but even today, send-tab on desktop handles an incoming null. Given the user count seems so low, I guess this is still a possible explanation.
