### ISSUE TITLE
suggest: Pocket suggestions don't include description and full_keyword

### ISSUE THREAD

**Issue by 0c0w3** [mozilla/application-services#5878]
Pocket suggestions from the `suggest` component need to include a `description` and `full_keyword`. The description is shown in the desktop UI for top picks (i.e., when a high-confidence keyword is matched), and the full keyword is shown for both high and low matches.

That said, Pocket suggestions have been put on hold for now, so I'm mainly creating this issue so we don't lose track of it if we do enable them again in the future.

cc @linabutler , @tiftran

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3968)

**Comment by ncloudioj** [comment]
Close this as we're moving issue tracking to BMO. Also tracked via https://mozilla-hub.atlassian.net/browse/DISCO-2713.

**Comment by linabutler** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1874028

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
