### ISSUE TITLE
Fxa: detect account deleted and raise a special exception for it

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5881]
We should handle the HTTP error response `102` and return a new error case for it.  This way applications can catch this error and respond accordingly.

If my current FxA work gets merged, we should consider adding something like  `FxaAuthState.AccountDeleted`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3970)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866536

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
