### ISSUE TITLE
Intermittent ios-test failures

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5902]
There's been an uptick in ios-test intermittent -- Example: failures: https://app.circleci.com/pipelines/github/mozilla/application-services/35740/workflows/41ab9956-c4bc-4a02-848e-05e5e367c14c/jobs/177795

Excerpt from link above:
```
MozillaTestServicesTests.PlacesTests
  testHistoryMetadataBasics, XCTAssertEqual failed: ("1") is not equal to ("2")
  /Users/distiller/project/megazords/ios-rust/MozillaTestServices/MozillaTestServicesTests/PlacesTests.swift:312

        XCTAssertEqual(1, try! db.getHistoryMetadataSince(since: afterLastMeta1Update).count)
        XCTAssertEqual(2, try! db.getHistoryMetadataSince(since: beginning).count)

  testHistoryMetadataBasics, XCTAssertEqual failed: ("1") is not equal to ("2")
  /Users/distiller/project/megazords/ios-rust/MozillaTestServices/MozillaTestServicesTests/PlacesTests.swift:339

        XCTAssertEqual(2, try! db.getHistoryMetadataBetween(start: beginning, end: afterLastMeta2Update).count)
        XCTAssertEqual(1, try! db.getHistoryMetadataBetween(start: afterLastMeta1Update, end: afterLastMeta2Update).count)
```

It also seems slightly tangential to https://github.com/mozilla-mobile/firefox-android/pull/3703 which also disabled tests due to intermittent issues and is also using `getHistoryMetadataBetween`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3991)

**Comment by mhammond** [comment]
I see 2 main possibilities here:
* it's using timestamps, so it's possible not enough care is being taken with them (eg, using `now()` immediately after writing history might *usually* work, but sometimes the value returned by `now()` will be different than what `now()` was at write time, etc.
* is it possible these tests are running in parallel?

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866537

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
