### ISSUE TITLE
MergedJsonWithErrors doesn't work with UniFFI `0.25.x`

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5913]
I'm trying to upgrade the application-services UniFFI version, but it's complaining about [MergedJsonWithErrors](https://github.com/mozilla/application-services/blob/64033afcbc4ba55e7ae96960eb4cd6880e6c7a24/components/support/nimbus-fml/src/fml.udl#L18-L21).

The issue is that the `FMLError` type is a "flat error" -- one defined in the UDL using the enum syntax (i.e with no fields).  Flat enums can only be sent in one direction from Rust -> the foreign bindings.  This is because the actual Rust enum may have fields (which `FMLError` indeed does) so there's no way to pass it from the foreign side back to Rust.

Using a flat error in a dictionary means that the dictionary is also one-way.  We've never officially supported this, but I guess it didn't error out in `0.24.x`.

I don't think you can easily define the fields in UDL for `FMLError` since many of the variants wrap errors from other crates.

Maybe the simplest way around this would be to define a enum called `FMLErrorKind`.  It would contain the same variants as `FMLError`, but no associated data.  Then `MergedJsonWithErrors` could store this instead of `FMLError` and I think everything would work.  BTW, enums don't have the same historical baggage as errors and there's no special handling for a "flat enum".  A flat enum is just an enum without fields.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4008)

**Comment by bendk** [comment]
Thinking more about that enum idea, there would be a couple naming issues:
- We don't do the "Error" -> "Exception" replacement for enum variant names
- In any case, I think the variant names would have to change to avoid name conflicts with `FMLError`

**Comment by mhammond** [comment]
> We don't do the "Error" -> "Exception" replacement for enum variant names

That should be fixed in #1842.

>  I think the variant names might have to change to avoid name conflicts with FMLError

Quite possibly - I hit a Kotlin issue in that PR where things fall apart if the variant name is the same as another type name.

**Comment by bendk** [comment]
Talked with @mhammond about this one and I think we can make a couple changes for `0.25.2` that fix this issue for you.

**Comment by mhammond** [comment]
We landed that in 0.25.2 and main.
