### ISSUE TITLE
fetchAllDevices: Invalid parameter in request body 

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5919]
We're currently seeing a handful of [these errors a day on Fenix nightly](https://mozilla.sentry.io/discover/results/?cursor=0%3A50%3A0&field=title&field=release&field=environment&field=user.display&field=timestamp&name=fxa-client-other-error%3A+No+stored+session+token&project=6295546&query=issue%3AFENIX-NIGHTLY-7BZ+400&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29).  They all seem to be invalid parameters when fetching the device list.

Is there any way to get more detail or these, like which parameter was invalid?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4012)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866538

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
