### ISSUE TITLE
Remote Settings UDL generates invalid Python

### ISSUE THREAD

**Issue by brennie** [mozilla/application-services#5927]
The [UDL for Remote settings](https://github.com/mozilla/application-services/blob/56bcdac6610ea99c704821efbb14ef94989f586b/components/remote_settings/src/remote_settings.udl) has the following bits:

```
dictionary RemoteSettingsConfig {
    string? server_url = null;
    string? bucket_name = null;
    string collection_name;
};

# ...

interface RemoteSettings {
    // Construct a new Remote Settings client with the given configuration.
    [Throws=RemoteSettingsError]
    constructor(RemoteSettingsConfig remote_settings_config);

    # ...
}
```

However, this results in a Python RemoteSettings type that looks like

```python

class RemoteSettings
    def __init__(server_url = DEFAULT, bucket_name = DEFAULT, collection_name):
        # ...
```

which is invalid, because defaulted arguments cannot precede non-defaulted arguments.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4018)

**Comment by mhammond** [comment]
See also https://github.com/mozilla/uniffi-rs/issues/1658 and https://github.com/mozilla/uniffi-rs/pull/1840

**Comment by linabutler** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1874030

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
