### ISSUE TITLE
Write an overview doc for building a new rust component

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#598]
(I'm doing a refresh of the docs setup in this repo and filing issues for things that I can't find, but want).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-688)

**Comment by vladikoff** [comment]
Good idea, we can use the push component as an example maybe

**Comment by rfk** [comment]
From discussion earlier today, the current content of the page here:

  https://github.com/mozilla/application-services/blob/master/docs/howtos/building-a-rust-component.md

Contains older blog post examples that are not to-to-date with our current best practices.  A good first step might be to find a more recent example to link to.

**Comment by cse-test-sync** [comment]
➤ Lina Cambridge commented:

Let's collect our thoughts in this doc as we build Synced Tabs: https://docs.google.com/document/d/1s9ld2F4e83eQ944kN6QXXTRlqrX74w2AJS6W2fDyAJ8/edit?usp=sharing ( https://docs.google.com/document/d/1s9ld2F4e83eQ944kN6QXXTRlqrX74w2AJS6W2fDyAJ8/edit?usp=sharing )

We can write down anything that's vague or weird, and use that to both improve our library, and figure out what our docs should focus on.
