### ISSUE TITLE
Write an overview doc for exposing a Rust Component to Kotlin

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#599]
(I'm doing a refresh of the docs setup in this repo and filing issues for things that I can't find, but want).

Ben got the ball rolling here:

https://docs.google.com/document/d/1CMgprsrbfWmEpHtY5htL0oVOoirmwhykaEqRc-0nTVA/edit#

I'm going to copy the contents of that doc into a findable home in this repo, but we need to flesh it out a good deal more.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-689)

**Comment by thomcc** [comment]
Worth noting: Some (I would have said all, but am probably mistaken) of that doc made it into https://github.com/mozilla/application-services/blob/master/docs/howtos/exposing-rust-components-to-kotlin.md and sibling `.md`s.

**Comment by Lonami** [comment]
New link (`master` -> `main`): https://github.com/mozilla/application-services/blob/main/docs/howtos/exposing-rust-components-to-kotlin.md.

**Comment by rfk** [comment]
Thanks @Lonami! By the way, we've also been working on a tool to automate some of that which you may find interesting: https://github.com/mozilla/uniffi-rs/
