### ISSUE TITLE
Write a guide to consuming rust components on iOS

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#600]
I'm doing a refresh of the docs setup in this repo and filing issues for things that I can't find, but want. Kinda hoping we can lean on @justindarc to help with this as a result of his explorations with Firefox for iOS 😁.

**Comment by justindarc** [comment]
Do you have a template or example I can follow? I can certainly help fill in some things as I go along.

**Comment by rfk** [comment]
> Do you have a template or example I can follow? 

Sadly no; but if you'd be happy to start a google doc with a braindump of your notes on integrating into Firefox for iOS, I'd be very happy to help massage into a guide we can land in this repo.

**Comment by garvankeeley** [comment]
I'll update this now with notes on consuming the library based on the current publishing strategy.

**Comment by garvankeeley** [comment]
Maybe we also need a doc for exposing Rust components to Swift.

Some key points, using MozillaAppServices as the example project:
- add the new FFI header include to MozillaAppServices.h. Optionally, one can add the new FFI header to the files in the project, but don't add it to the build target.
- add the search path to the HEADER_SEARCH_PATHS in the base.xcconfig for the project to the location of the new FFI header
- todo: notes about updating Cargo.toml, lib.rs, etc

**Comment by rfk** [comment]
Adding @garvankeeley as an assignee on this issue, as I'm going to wait for #688 to land before doing any shuffling of the docs.

> Maybe we also need a doc for exposing Rust components to Swift.

This sound great!  Even pushing those bullet points in a `.md` doc would be an excellent place to start.
