### ISSUE TITLE
nimbus-fml.sh is failing in iOS with a local a-s

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#6029]
STR:
* Follow [these instructions](https://github.com/mozilla/application-services/blob/main/docs/howtos/locally-published-components-in-firefox-ios.md)
* Run `./bootstrap.sh` in the local ios checkout
* Attempt to build

The build fails with output that looks roughly like:
```
Using bin/nimbus-fml-configuration.sh as config
Modifying with bin/nimbus-fml-configuration.local.sh
+ shift 1
+ ((  0  ))
+ '[' -z nimbus.fml.yaml ']'
+ '[' -n '' ']'
+ '[' -z '' ']'
+ find_as_version
++ grep -A 3 https://github.com/mozilla/rust-components-swift /Users/skip/src/moz/firefox-ios/firefox-ios/Client.xcodeproj/project.pbxproj
++ grep -E -o '\d+\.\d+\.\d+'
+ number_string=
```

After throwing a few things at a wall to see what sticks, I got a local build by:

* changing [this grep line](https://github.com/mozilla/application-services/blob/33af2ee7e7906a7e0849bcdf27236aacaa5551d2/components/nimbus/ios/scripts/nimbus-fml.sh#L97) to end with `|| true` - I think the script stopped here because grep didn't find the string so exited with a non-zero code, which aborted the entire script.
* removing the first `$` in [this line](https://github.com/mozilla/application-services/blob/33af2ee7e7906a7e0849bcdf27236aacaa5551d2/components/nimbus/ios/scripts/nimbus-fml.sh#L103) but that might have been a local artifact of the shell I was using so may not be strictly necessary.

No idea why this is breaking recently, but cc @jhugman @brennie - it should be easy to repro locally.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4056)

**Comment by tarikeshaq** [comment]
Moved to the Nimbus Jira tracker: https://mozilla-hub.atlassian.net/browse/EXP-4458
