### ISSUE TITLE
Run iOS tests in CI

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#607]
We started testing the iOS code in #606, but the tests aren't run as part of the CI process.

I don't know if its easier to do this using circleci or taskcluster. Probably circle, but doing that is (probably) blocked on us being able to use Macs in CI (no issue, but will probably be fixed as part of https://github.com/mozilla/application-services/issues/459).

**Comment by rfk** [comment]
IIUC this is now unblocked because we've got access to bigger/faster/better iOS machines on CircleCI.
