### ISSUE TITLE
Update ring to 0.14.x or remove dep

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#613]
Author has a policy of yanking previous versions of their crates (https://github.com/briansmith/ring/issues/774), and plans to yank 0.13.5 (which we depend on) soon. Annoying. Not sure how much work an update is, I know we only have the dep for parts of FxA, but I'm not sure how critical they are.

**Comment by rfk** [comment]
From triage: this sounds potentially urgent, as the previous version may be yanked at any time; @eoger let's discuss how to move forward here in our upcoming 1:1.

**Comment by thomcc** [comment]
More generally, removing this makes it a little easier to make sure all our security deps are up to date (we keep track of our OpenSSL dep, but have little insight into what's going on in the version of BoringSSL that ring brings in).

That said, in the short term just updating it is fine. Also @eoger might have convincing reasons to keep it's dep.

**Comment by eoger** [comment]
Depends on https://github.com/taskcluster/rust-hawk/pull/14.
