### ISSUE TITLE
firefox update bug

### ISSUE THREAD

**Issue by itmehr** [mozilla/application-services#6175]
firefox doesn't start after latest update
![2024-03-24_090704](https://github.com/mozilla/application-services/assets/24986586/fd9e4a88-bd39-40e3-953f-ffc562ad1350)
![2024-03-24_090646](https://github.com/mozilla/application-services/assets/24986586/751469e4-c081-40bc-bf4b-ab5c977f9694)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4202)

**Comment by mhammond** [comment]
I think you are looking for bugzilla.mozilla.org or support.mozilla.org
