### ISSUE TITLE
rc_log bindings for swift

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#618]
Considered a blocker for bookmarks, apparently. Initial work is present here: https://github.com/mozilla/application-services/tree/swift-rc-log

This ultimately requires figuring out how to megazord swift code, hence half of the work there being about producing a ios megazord (which is only half the story, since it ignores how to do the swift side of it)

**Comment by rfk** [comment]
From triage: @linacambridge to make a milestone and add this issue to it?
