### ISSUE TITLE
Add/enrich PlacesAPI#"recent history"

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#619]
Currently we have `places_get_visited_urls_in_range`, which returns a list of visited URLs.

For a History UI, we also need - at the very least - a page title for each URL, when it's available, and a timestamp of the visit. It's possible that in the future we'd need more information. This could be modelled as a "fat api", or perhaps we could have a "meta API" that will provide additional information about visited URLs. The former seems less troublesome.

This is required to power upcoming Fenix history UI.

**Comment by thomcc** [comment]
I think this will look like

```
fun getVisitInfos(startTime, endTime): List<VisitInfo>
```
with some
```
data class VisitInfo(url: String, title: String, timestamp: Long, type: VisitTransition, isLocal: Boolean)
```

Note that isLocal == false doesn't mean it's definitely remote, just that we aren't positive it's local.
