### ISSUE TITLE
Consider annotating API methods with I/O information

### ISSUE THREAD

**Issue by bbangert** [mozilla/application-services#629]
When calling into API methods from Kotlin, especially as one goes up the stack, it can become more important for the caller to know whether the API method is likely to hit disk or the network. Or possibly an extremely computationally expensive method. Mobile devices can easily lose network access, disk writes on SSD's can become extremely expensive depending on NAND state (requiring multiple block re-writes), etc.

To make it easier, we can annotate our API method documentation with some emoji to hint what kind of tasks this API method involves, perhaps:
🖴 - disk access
🖧 - network access

Then if we wanted to be more helpful in the case that there's multiple or possibly unknown quantities:
3🖴 - 3 disk accesses of some nature
0?🖴 - 0 or more possible disk access
1?🖴 - 1 or more possible disk access

Care would need to be taken to avoid adding so many descriptors that this information becomes less useful. Knowing some of these, the Kotlin/iOS callers can make better use of API calls to avoid multiplying disk/network accesses, or to give us feedback where they would want a new API method that can avoid excessive disk/network access.

**Edit**: After testing in Android Studio, emoji don't show up well as doc strings which is where this would be most useful. Using a bold doc string comment does have fairly good visibility. Screen-shot is attached farther down.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-106)

**Comment by thomcc** [comment]
These don't render on the default github font on my fully updated macbook in firefox nightly. I suspect things only get worse from there...

More generally I'd prefer this be explicit in comments.

**Comment by bbangert** [comment]
Using explicit comments is good as well, seeing at a glance that its going to hit network or disk seems handy so it'd be nice if there was some emoji/short-string that worked better in those cases. Even something as simple as (N+D) to indicate it hits Network and Disk.

**Comment by thomcc** [comment]
N+D seems like you'd have to be in the know to know what it means. (Net+Disk) is still short but might avoid that issue.

In either case, I don't care that much.

**Comment by grigoryk** [comment]
These would mostly be viewed from within editors, right? How well does something like Android Studio work with emojis in method docstrings?

+1 from me for being very explicit about what an API call might do. Simple "May perform network access" annotations in the docstrings are perfectly fine, too.

**Comment by bbangert** [comment]
I tested the emoji in Android Studio, while they show up fine, they're definitely not immediately obvious and are given pretty low visual weight. Using a doc string bold shows up much better, here's an example that should be representative (in this case rust, but its the same editor):

![image](https://user-images.githubusercontent.com/100193/52435764-74ec1c00-2ac7-11e9-9083-9c920c903299.png)

**Comment by thomcc** [comment]
One thing of note is that this message would be on every places/logins API call (well, not network, but they all hit the disk). Not that that's a huge issue to add annotations or anything.

Also, your image shows it in rust, I would push back against adding it to every pub rust function, just because that's a lot of tedium for little-to-no benefit.

**Comment by bbangert** [comment]
Yea, that was mainly just an example from an Intellij window I had open at the time to see whether emoji showed ok (they didn't). The intention is that its only on the Kotlin side API docs that A-C would use.

**Comment by vladikoff** [comment]
Closing until we decide we need to do something about this...
