### ISSUE TITLE
history: Places should normalize URLs better

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#635]
We are relying on rust-url to do this, but I'm not sure if it does at all.

While testing #590 I saw cases in my own history where we had both "http://www.foo.com/test" and "http://www.foo.com/test/".

Haven't dug into this really, but seems not great for frecency reasons and others.

**Comment by thomcc** [comment]
example of the problem: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f48de4027eb0e7231e41fa461a38fa45

**Comment by thomcc** [comment]
Nevermind, this is actually consistent with how desktop places does things.

**Comment by mhammond** [comment]
I've wondered about this

> Nevermind, this is actually consistent with how desktop places does things.

But does that make it correct? Is that intentional? I wouldn't be too surprised to find it's an implementation detail rather than a conscious decision.

**Comment by thomcc** [comment]
My understanding is that yes it's deliberate, as "http://www.foo.com/test" and "http://www.foo.com/test/" are different URLs.

Which does make sense to me, but also... ugh.
