### ISSUE TITLE
history: Expose `accept_result` over FFI

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#638]
This is used to remember that the user has chosen the result from autocomplete. It will show up in future results more heavily.

Perhaps we could also snag this from `VisitTransition::Typed`?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-108)

**Comment by lyuyuan92** [comment]
Hi! I couldn't get access to see the Jira user story. Could you please give me a bit more background on this issue? Thanks!

**Comment by thomcc** [comment]
The jira stories are exact duplicates of the issues, and there's a bot that keeps them in sync. There's nothing there that isn't here, you're free to ignore them.

Specifically this issue is about exposing [this function](https://github.com/mozilla/application-services/blob/d308e8f35c8fc1782274ad8060f3cac172692617/components/places/src/api/matcher.rs#L119-L136) over the FFI to android (the iOS bindings don't support history, so there would be no purpose).

### Implementation

This a number of changes across several files, but none of them are very hard. A function to model it after might be `places_delete_place`, since they're both methods on connections that take a string and return nothing (beyond that they're completely different of course.

To expose it to android it will need:

- A FFI function in [the ffi/src/lib.rs file](https://github.com/mozilla/application-services/blob/d308e8f35c8fc1782274ad8060f3cac172692617/components/places/ffi/src/lib.rs#L254-L271)  (obviously the body inside the `CONNECTIONS.call_with_result` bit would be completely different, but it still might help some).
- A stub in [the LibPlacesFFI.kt file](https://github.com/mozilla/application-services/blob/d308e8f35c8fc1782274ad8060f3cac172692617/components/places/android/src/main/java/mozilla/appservices/places/LibPlacesFFI.kt#L121-L125) (used to call the FFI function)
- Declaration on [WritableHistoryConnection](https://github.com/mozilla/application-services/blob/d308e8f35c8fc1782274ad8060f3cac172692617/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L713-L722) (mostly so that this can be mocked by consumers)
- And finally, the concrete implementation that calls the stub on [PlacesWriterConnection](https://github.com/mozilla/application-services/blob/d308e8f35c8fc1782274ad8060f3cac172692617/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L384-L389).

### Setup

This is the kind of annoying part.

To setup an android build environment you do the following: https://github.com/mozilla/application-services/blob/master/docs/howtos/setup-android-build-environment.md#prepare-your-build-environment. You can ignore anything about maven and publishing for now, I think.

You basically want to set up the NDK toolchains and rust targets. You can also install android studio if you want, which is what most of us use when we work on the android bindings. Once that's all done, the following should work:

- Running `./gradlew :places-library:testDebug` will run debug tests (caveat: the build is rather slow)
- Running `./gradlew ktlint detekt` will run the linters (`./gradlew ktlintFormat` can auto-fix some of the issues too).

FWIW this is kind of tedious, requires a whole lot of setup, and is about half kotlin, half rust. So if you'd rather work on something else that's fine too.

If you do decide to do it, feel free to reach out if you get stuck. A lot of our documentation here is lacking or stale, so that would be completely understandable.

**Comment by lyuyuan92** [comment]
Thanks for the detailed explanation! Honestly, I have zero knowledge about Kotlin...but I will have a try and see how far I can get.
