### ISSUE TITLE
logins should support SyncStatus::Unknown

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#648]
Currently it just supports `SyncStatus::{Synced, Changed, New}`. These were taken from iOS. It would be nice to add `unknown`, which would be better behaved in the case of resets and such.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2647)

**Comment by rfk** [comment]
This feels a bit like a (small) missing feature, so labelling it for consideration in v1.0. But I'd also happily take a WONTFIX.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864932

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
