### ISSUE TITLE
Un-deprecate logins reset

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#649]
This was deprecated because it's API was confusing and it didn't seem useful. This was only because of viewing it through the lens of Lockbox. It's certainly useful for things like browsers, where signing out of sync doesn't mean we should delete local state.

The API is still confusing, so perhaps it needs renaming and better docs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2648)
┆Epic: Logins update and sqlcipher migration
┆Fix Versions: Release 92
┆Sprint End Date: 2021-07-09

**Comment by thomcc** [comment]
Concretely this wasn't just deprecated, it was taken out of the a-c wrapper, so it should be re-added. The documentation around the differences between the various wipe methods should be clarified as well.

**Comment by rfk** [comment]
Let's either close this as WONTFIX, or put it in the v1.0 milestone; @thomcc which would you prefer?

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Mark will decide if this is truly wontfix

**Comment by mhammond** [comment]
logins does have reset support but our longer term plan is actually to stop exposing it, so only the sync-manager does sync-specific things. That can't happen yet though as iOS doesn't use the sync manager. So this is WONTFIX and a future task will actually be to stop exposing it entirely.
