### ISSUE TITLE
Logins hostname queries

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#650]
There are some queries that firefox-ios implement as grabbing the list and filtering. They'd like it if we implemented it natively.

@justindarc expressed interest in being the one who implements this.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-269)
┆Story Points: 1
┆Sprint: SYNC - end 2019-11-22

**Comment by vladikoff** [comment]
We need it for Fenix too now, let's re-prioritize it

**Comment by thomcc** [comment]
FWIW Justin no longer works at Mozilla so I would rate the likelihood that he implements this as extraordinarily low!

**Comment by vladikoff** [comment]
> FWIW Justin no longer works at Mozilla so I would rate the likelihood that he implements this as extraordinarily low!

We need one of us to implement this now, I guess

**Comment by thomcc** [comment]
Yes, it should be easy. I was just mentioning it because of the comment.

**Comment by vladikoff** [comment]
search by `hostname` & `formSubmitUrl`

**Comment by rfk** [comment]
I don't understand how this issue differs from #1675, was there some Jira shenanigans that created a dupe?

I'm going to go ahead and assign this to @vladikoff

**Comment by rfk** [comment]
@vladikoff was this done as part of https://github.com/mozilla/application-services/issues/1675 or is there more work to do here?

**Comment by vladikoff** [comment]
ah yes, I also added the Swift bit for this, we can close this yeap.
