### ISSUE TITLE
iOS Megazord fails on travis-ci

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#663]
From the build log https://api.travis-ci.org/v3/job/492434789/log.txt,
this is the error when linking the MozillaAppServices static lib:
```
error: Build input files cannot be found: '/Users/travis/build/mozilla/application-services/target/universal/release/libmegazord_ios.a', 
'/Users/travis/build/mozilla/application-services/libs/ios/universal/sqlcipher/lib/libsqlcipher.a'
```
Yet earlier in the log this lib is built without an error:
```
+ CMD='lipo -arch x86_64 ios/x86_64/sqlcipher/lib/libsqlcipher.a -arch arm64 ios/arm64/sqlcipher/lib/libsqlcipher.a'
+ CMD='lipo -arch x86_64 ios/x86_64/sqlcipher/lib/libsqlcipher.a -arch arm64 ios/arm64/sqlcipher/lib/libsqlcipher.a -output ios/universal/sqlcipher/lib/libsqlcipher.a -create'
+ lipo -arch x86_64 ios/x86_64/sqlcipher/lib/libsqlcipher.a -arch arm64 ios/arm64/sqlcipher/lib/libsqlcipher.a -output ios/universal/sqlcipher/lib/libsqlcipher.a -create
```

**Comment by garvankeeley** [comment]
Some users report setting Xcode to 'Legacy Build System' helped with similar errors, trying that here
https://github.com/mozilla/application-services/pull/659/commits/d0a96cc16ca7580502c4386acd6852809973c980

**Comment by garvankeeley** [comment]
The non-legacy build system is more parallelized, and it does appear that the Swift component is finished building prior to the non-Swift static libs.

**Comment by eoger** [comment]
We fixed it!
