### ISSUE TITLE
Consider using frecency stats to bound autocomplete queries

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#689]
In #429 I landed support for updating frecency stats (`origin_frecency_count`, `origin_frecency_sum`, `origin_frecency_sum_of_squares`), but don't use them to bound autocomplete queries.

The reason for this is that:

1. They necessarily cause us to have worse search query results (they cause us never to return results with a frecency lower than a cutoff)
1. They're an optimization, and our autocomplete performance seems acceptable currently.

At the moment, I don't think we should use them (hence this bug getting marked as "Backlog" and not "History Polish"), however in the future this could change.

This bug largely exists to document the fact that we don't use them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2650)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864936

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
