### ISSUE TITLE
Rename fxa-client crate errors.rs to error.rs

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#703]
Let's bring fxa-client in line with the rest of our crates.

**Comment by championshuttler** [comment]
Hi @eoger I would like to work on it.

Thanks

**Comment by eoger** [comment]
Sure please do! Let me know how I can help you along the way.

**Comment by thomcc** [comment]
If you aren't sure how to get started, see https://github.com/mozilla/application-services/blob/master/docs/contributing.md

**Comment by lyuyuan92** [comment]
@eoger Perhaps consider close this issue?
