### ISSUE TITLE
Allow FxAClient to bootstrap an account from a sessionToken

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#717]
We need this for Fennec to Fenix migration. The account object should use an existing sessionToken to obtain oauth tokens

Related: https://github.com/mozilla/fxa-auth-server/pull/2932

**Comment by rfk** [comment]
> The account object should use an existing sessionToken to obtain oauth tokens

It should also hang on to the `sessionToken` so that we can eventually give it back to web content via `fxa_status` webchannel message or similar mechanism.

**Comment by vladikoff** [comment]
Closing for now until there are better product requirements
