### ISSUE TITLE
Formalize our story around third-party dependencies

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#721]
This came up in email and slack - what's our policy around managing third-party dependencies and ensuring that we're not vulnerable to supply-chain security issues?  We have some good thoughts on this but they're not written down anywhere, which makes them hard to audit or enforce.  Let's be explicit about this, and lean on existing best-practices from around Mozilla rather than re-inventing any wheels.

**Comment by rfk** [comment]
Also, how to get audits/alerts for security issues in dependencies.

**Comment by thomcc** [comment]
See also https://github.com/mozilla/application-services/issues/144

**Comment by rfk** [comment]
Also, "dependencies" vs "dev-dependencies", are there meaningful differences in practice?

**Comment by ckarlof** [comment]
This [dev-platform thread](https://groups.google.com/d/msg/mozilla.dev.platform/4rT-ka0uhgM/GKvXQfb4BQAJ) on duplicate Rust dependencies in m-c is triggering similar governance questions about external Rust code in m-c. We absolutely need to get our vendoring governance story around 3rd party Rust code straightened out soon and have that policy reviewed by folks outside this team to ensure it's aligned with our broader policies around vendoring.

**Comment by rfk** [comment]
I started writing up some notes on this [here](https://github.com/mozilla/application-services/pull/827/files#diff-42f232494bad9c0935a0b5f08f2c19fb) ([rendered](https://github.com/mozilla/application-services/blob/dependency-management-v1/docs/dependency-management.md)), based on slack conversations and some initial notes from @thomcc.

As written, these guidelines make adding a dependency sound like a Big Deal and a bit of a PITA. That's on purpose. But they're also just a starting point for conversation, so please let me know what you think and we can iterate from there.

**Comment by rfk** [comment]
Initial version committed in https://github.com/mozilla/application-services/pull/827 and we'll evolve as needed
