### ISSUE TITLE
places: Delete database on upgrade failure

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#730]
We can still fail to upgrade the database in cases where the schema version is initially 1.

We should just delete the database (from rust) in this case. This is a follow up from #718.

We shouldn't backlog this, as failing to do this will likely be a permacrash for users on update! But I don't think I'll have time to do it before landing 718.

**Comment by thomcc** [comment]
We're going to backlog this actually until we get reports. The outcome of this could be quite bad (permacrash at startup), but it also might never happen, and should show up in sentry if it does.

**Comment by mhammond** [comment]
Just updating this based on @grigoryk's comment in slack:

> not worried about old upgrades; i think changing that panic message to be a little more explicit (as opposed to "upgrades not supported") is all we need here
