### ISSUE TITLE
Shorten PRs Taskcluster build time

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#745]
In the past week I've seen PRs merged before TC had completed. It is understandable as our task set currently takes more than a full hour 😱 
It also makes developing new infra stuff (#744, #741) very painful as pushing a small change takes ages to verify.

Some ideas:
- Parallelize builds, e.g. 1 task per arch then 1 task that "combines" the results. (trick is the archs to build are hardcoded in .gradle files). EDIT: I think I have an idea on how to read gradle target archs from env.
- Make the pull-request tasks build for less architectures (same gradle issue).
- Cache the rust `target/` dir.
- Run on beefier machines (not sure what we have at the moment).

**Comment by eoger** [comment]
Yup we already do

**Comment by eoger** [comment]
https://github.com/mozilla/application-services/pull/764 and https://github.com/mozilla/application-services/pull/785 have cut down our pull-request builds time from 1h20 to 15-20 minutes which is more reasonable.

**Comment by rfk** [comment]
> 1h20 to 15-20 minutes which is more reasonable.

Impressive!!  Great work @eoger!
