### ISSUE TITLE
Add a method for signing out, which calls /account/device/destroy

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#746]
When the user signs out of the application, we should call [/account/device/destroy](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-accountdevicedestroy) to ensure that all tokens associated with our device record are destroyed.

This is similar to what desktop does (calling /device/destroy rather than /session/destroy) and for similar reasons - a single server API call to tear down all authentication/authorization state owned by the application.

**Comment by eoger** [comment]
I believe we don't even have a "signout" method at all in the FxA client (which is kinda suprising) that destroys refresh tokens.

**Comment by rfk** [comment]
Ah, well, I'm going to morph this but into "add a method for signing out" then ;-)

**Comment by vladikoff** [comment]
in fxa rust client
