### ISSUE TITLE
PlacesAPIs are never removed from the global hash map of them (they're leaked)

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#749]
This is a known issue, and in practice we don't expect it to be a huge deal (real applications should only have one of these), but I needed to link the issue number, and couldn't find it (e.g. if this is a dupe, dupe me).

**Comment by thomcc** [comment]
The iOS team indicated that them failing to close the logins DB when backgrounding was a problem, so it seems likely that this would be a problem as well...

**Comment by thomcc** [comment]
@justindarc this bug effectively means requests to close a PlacesApi will be ignored (although calls to open it again will return the first one that we didn't actually close, so usage won't grow, just it won't shrink when might be expected).

Is this likely to be a problem for y'all?

CC @grigoryk also, to make sure it won't be a problem for android either.

**Comment by thomcc** [comment]
Apparently iOS hard kills your process if you leave these things open. un-backlogging

**Comment by thomcc** [comment]
This also means we can't leak these in the sync manager design in #714.

**Comment by justindarc** [comment]
Yes, to confirm, in Firefox for iOS when the app is backgrounded we currently do a sync (if the user is signed in) and then close all the DB connections when done. If we run out of time, iOS kills our process and we get a crash reported.
