### ISSUE TITLE
Implement shared NSS-powered crypto crate

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#752]
Similar to the networking issue in https://github.com/mozilla/application-services/issues/348, we currently have a variety of different ways of doing crypto operations in our components - some using OpenSSL, some using ring, and all implemented independently.

I expect we'll want to end up in a world where this is all done using functionality provided by NSS, at least for apps that are already bundling NSS for other reasons (and perhaps always, for policy reasons).

As a starting point, we can provide a peer to the `rc_log` crate that consolidates the crypto bits needed by FxA, Sync, Push and send-tab behind a hard-to-misuse shared API.  This will make it easier to audit in the short-term, and easier to migrate to NSS in the medium-term.

Strawman: an `rc_crypto` crate that exposes helpers for hashing, the encryption methods needed for sync and for FxA's use of JWKs, and the P-256 bits needed for push. We could also add an `rc_crypto` backend to [rust-ece](https://github.com/mozilla/rust-ece) so that push can consume them easily via that dependency, rather than having to make its own bindings to NSS.

**Comment by rfk** [comment]
@eoger @thomcc gut reaction to this proposal?  I'm not strongly wedded to any particular details.

**Comment by rfk** [comment]
@thomcc points out in slack that one of the big "crypto" things we use is sqlcipher, which is probably a lot of work to make a custom backend for.

**Comment by thomcc** [comment]
So, I just took a look through sync15, and providing this for the crypto it needs is basically laughably easy.


For sync15, it would look like this:

```rust

// It's too painful to try to avoid boxing these if we want to be able
// to swap them out.
pub type CryptoError = Box<dyn std::error::Error + Send + Sync>;
pub type CryptoResult<T> = Result<T, CryptoError>;

pub trait Cryptographer {
    fn encrypt_aes256_cbc(&self, key: &[u8], iv: &[u8], cleartext: &[u8]) -> CryptoResult<Vec<u8>>;
    fn decrypt_aes256_cbc(&self, key: &[u8], iv: &[u8], ciphertext: &[u8]) -> CryptoResult<Vec<u8>>;
    fn verify_hmac_sha256(&self, hmac_key: &[u8], ciphertext: &[u8], expected_hmac: &[u8]) -> CryptoResult<bool>;
    // If this proves to be a problem for some reason, we could also use a CSPRNG from
    // `rand`, which is at least vendored in m-c.
    fn random_bytes(&self, len: usize) -> CryptoResult<Vec<u8>>;
}
```

And then the OpenSSL version would basically be.

```rust
use super::*;
use openssl::{hash::MessageDigest, pkey::PKey, sign::Signer, symm};

pub struct OpensslCryptographer;

impl Cryptographer for OpensslCryptographer {
    fn encrypt_aes256_cbc(&self, key: &[u8], iv: &[u8], cleartext: &[u8]) -> CryptoResult<Vec<u8>> {
        Ok(symm::encrypt(
            symm::Cipher::aes_256_cbc(),
            key,
            Some(iv),
            cleartext,
        )?)
    }

    fn decrypt_aes256_cbc(&self, key: &[u8], iv: &[u8], ciphertext: &[u8]) -> CryptoResult<Vec<u8>> {
        Ok(symm::decrypt(
            symm::Cipher::aes_256_cbc(),
            key,
            Some(iv),
            ciphertext,
        )?)
    }

    fn verify_hmac_sha256(&self, hmac_key: &[u8], ciphertext: &[u8], expected_hmac: &[u8]) -> CryptoResult<bool> {
        let mut computed_hmac = [0u8; 32];
        let key = PKey::hmac(hmac_key)?;
        let mut signer = Signer::new(MessageDigest::sha256(), &key)?;
        signer.update(ciphertext)?;
        let size = signer.sign(&mut computed_hmac)?;
        assert_eq!(size, 32, "sha256 didn't produce 256 bytes?");

        Ok(openssl::memcmp::eq(&expected_hmac, &computed_hmac))
    }

    fn random_bytes(&self, len: usize) -> CryptoResult<Vec<u8>> {
        let mut bytes = vec![0u8; len];
        openssl::rand::rand_bytes(&mut bytes)?;
        Ok(bytes)
    }
}
```

Presumably the NSS version would carry around a pointer returned from dlopen, as well as a bunch of function pointers. I'm pretty confident the needs of `fxa-client`, `ece`, etc. are more involved, however.

**Comment by rfk** [comment]
FWIW, I have some rough notes on how we could change the `sync15` crypto interfaces to be harder to use incorrectly (e.g. treating encrypt+hmac as a single AEAD primitive rather than two separate operations) but if anything I think they'd make the proposed API even smaller.

**Comment by thomcc** [comment]
It looks like `rust-ece` has https://github.com/mozilla/rust-ece/blob/master/src/crypto_backend.rs. There are some issues we'd need to fix with that (mainly, it's not an object-safe trait (You can't have e.g. `Box<dyn Crypto>`, the `LocalKeyPair` `RemotePublicKey` associated types prevent this). It also would need to take &self, if we want to support an implementation from dlopen with function pointers)

That said it's still pretty reasonable.

I said this in slack, but for posterity: I think it might be a pain to keep rust-ece outside of this repo. We'd rather not implement NSS bindings in multiple places, and I'd much rather they live in this repo than outside of it. `rust-ece` could, ofc, depend on application-services, but that requires us publish our NSS bindings on crates.io, which given that we really only want to implement the minimum subset that we need, seems less than ideal.

That said, it could be made to work if we need to, it just takes more work.

**Comment by rfk** [comment]
From slack, it looks like we also depend and ring and/or openssl via rust-hawk (and I don't really understand why it might be an "and" rather than an "or"...)

**Comment by rfk** [comment]
> I think it might be a pain to keep rust-ece outside of this repo.

I tend to agree with this, at least in the sort term.  We could consider temporarily vendoring a copy of it into our repo until we get to a state where the crypto layers seem stable.

**Comment by rfk** [comment]
@eoger does it make sense to close this in favour of the more fine-grained issues you just filed?

**Comment by eoger** [comment]
Yup I believe so!

**Comment by rfk** [comment]
Great, thank you!. For completeness, we'll need to nominate some subset of them for the April and May milestones and the `ship-ready` label.
