### ISSUE TITLE
Hook up shared crypto abstraction to NSS backend

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#753]
Requires https://github.com/mozilla/application-services/issues/752.

Assuming we do find a nice way to encapsulate the crypto operations we need behind an interface, we should then take a look at implementing an NSS backend.

**Comment by eoger** [comment]
I think we should just do this as part of #752

**Comment by rfk** [comment]
Agreed; we should make a new bug tree that reflects our latest plans.
