### ISSUE TITLE
We shouldn't store the sync keys in database

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#761]
Both places and logins do this, and in places the db is not encrypted. The sync manager is likely to address it, but we might want to fix this before then.

**Comment by thomcc** [comment]
This is quite possibly just adding `#[serde(skip)]` to https://github.com/mozilla/application-services/blob/940d94558bce5783eb946ccdbd6dff95f45dc9f5/components/sync15/src/state.rs#L58

**Comment by rfk** [comment]
Nominating this for March milestone because it sounds like something that would be easy to overlook if it goes into the backlog.

**Comment by linacambridge** [comment]
This should be fine! The state machine will fetch and keep them in memory, in `GlobalState`, but they don't need to be persisted to disk.

**Comment by vladikoff** [comment]
one line patch!

**Comment by mhammond** [comment]
Fixed via #892
