### ISSUE TITLE
Consider moving iOS tests into the megazord

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#762]
It's painful not having log access in the iOS test code, but the only way to get it is as part of the megazord. Unlike on android, there's no easy fix for us to log directly to something visible, AFAIK.

That said, this would probably simplify setup of new iOS components, as they could just add another test file instead of having to set up testing for their project.

**Comment by eoger** [comment]
Tests live in `MozillaAppServicesTests` nowadays, @thomcc can we close?

**Comment by thomcc** [comment]
Yep.
