### ISSUE TITLE
Add integration tests for places sync

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#767]
sync_test still has a few cases where it hardcodes logins stuff, so this isn't trivial, but it's definitely worth doing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-687)
┆Epic: local development, ci and release (backlog)
┆Sprint: Backlog

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

from mtg: let's start working on the sync manager instead

**Comment by jdragojevic** [comment]
closing d/t a lack of action.
