### ISSUE TITLE
Confirm that we can extract logs from Fenix, and document how

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#771]
We're going to want to get logs at some point once Fenix is in the wild.  Before then, let's confirm that we can in fact obtain logs from our rust components in a running Fenix app, and write some instructions for doing so.

**Comment by thomcc** [comment]
I think this will require assistance from the Fenix team.

In https://github.com/mozilla-mobile/fenix/blob/9dc0b4781a364f886bb7d5201734cd741629d282/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L61-L71 they only set up a log sink that outputs to logcat. Our logs will go to that, but there's no way to obtain logs that are output to log cat (typically).

If they add a new log sink that allows us to collect logs, e.g. by writing to a file, we could obtain logs, but that's sort of on them to provide.

**Comment by rfk** [comment]
> they only set up a log sink that outputs to logcat. Our logs will go to that,
> but there's no way to obtain logs that are output to log cat (typically).

To clarify, do you mean "obtain after the fact" here?  I assume the connecting adb or similar would obtain the live logs via logcat in this sencario, but wouldn't give us e.g. `about:sync-log`-style functionality.

> If they add a new log sink that allows us to collect logs, e.g. by writing to a file,
> we could obtain logs, but that's sort of on them to provide.

Agreed.

**Comment by rfk** [comment]
From mtg: @thomcc can confirm that this works, assigning to him for further triage.  Perhaps the right framing for this issue is to produce a Fenix version of https://wiki.mozilla.org/CloudServices/Sync/File_a_desktop_bug

**Comment by vladikoff** [comment]
from mtg: missing documentation
