### ISSUE TITLE
Connect sync telemetry ping to Glean somehow, so Fenix can submit it

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#772]
Telemetry is important, and I glean that Fenix can't submit ours right now for infrastructural reasons.  We'll need to resolve this before Fenix MVP general release.

**Comment by mhammond** [comment]
See also [bug 1536133](https://bugzilla.mozilla.org/show_bug.cgi?id=1536133)

**Comment by linacambridge** [comment]
Rolling this up into #524.
