### ISSUE TITLE
[push] Use temp directory for testing.

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#780]
Per suggestion by tcsc, push should create a temporary directory (see places/login) to use for testing.

**Comment by thomcc** [comment]
Just for refence: this is an example of the setup: https://github.com/mozilla/application-services/blob/454228d6fa2453a4cf92e5f9744969aef9ffb29e/components/places/android/src/test/java/mozilla/appservices/places/PlacesConnectionTest.kt#L21-L38
