### ISSUE TITLE
Consider using FxHash as the hash function in our HashMap

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#797]
By default rust uses SipHash. This is slow, especially for small keys, and our keys are all small. 
There are some minor security benefits to SipHash for network exposed services (it might provide some protection against HashDOS, however how much protection this actually provides is a very contentious subject among the Rust community). 

The recommendation is generally that [FxHash](https://github.com/cbreeden/fxhash/) (which was extracted from firefox and modified) is a better choice for things that aren't concerned with HashDOS (we're client software, so we aren't).

Given that Firefox uses FxHash, I think its probably completely safe for us to as well, and should improve performance during Sync.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-124)

**Comment by eoger** [comment]
Rust 1.36.0 released with `hashbrown` impl, should we close this?

**Comment by vladikoff** [comment]
@thomcc reopen this if still needed or if `hashbrown` is okay
