### ISSUE TITLE
Consider using jemalloc

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#798]
We're rather allocation heavy during syncing, so a faster allocator would likely be helpful. This is relatively easy for us to arrange, but would increase code size

My recollection is that jemalloc was only around 300kB of our 10MBish build. This (unless I've flubbed the math completely) is about 3%, and so if it actually does speed us up, it's likely to be worth using.

It's not too hard to plug jemalloc into SQLite as well, which we'd probably want to do as well. Firefox does this, and I have a branch somewhere that does it for us that I could dig up, although I can't find it at the moment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-671)
┆Sprint: Backlog

**Comment by rfk** [comment]
I consider this considered, and I don't see it getting to the top of our stack anytime soon. Thanks for recording this for reference though Thom!
