### ISSUE TITLE
Confirm whether and how we can link against NSS for Fenix

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#803]
We want to [use routines from NSS](https://github.com/mozilla/application-services/issues/753) for cryptographic operations in Fenix, rather than the current mixture of rust-openssl and ring.  From conversations with the GeckoView team, they suggest it should be possible for us to just dlopen and load the NSS symbols from GeckoView, which sounds excellent but there's probably some devil in the details.

What's the least amount of work we could do to confirm whether this is going to be a viable path forward?  For example, would it make sense to build a little stub component that just tries to dynamically load and call [NSS_IsInitialized](https://dxr.mozilla.org/mozilla-central/rev/891a30b8eee20648df8b62217304fb0a0636349d/security/nss.symbols#240) in order to try things out?

@thomcc @eoger thoughts?

**Comment by rfk** [comment]
As a first step: the geckoview AAR does appear to include a "libnss3.so", which is a good start :-)

**Comment by thomcc** [comment]
> For example, would it make sense to build a little stub component that just tries to dynamically load and call NSS_IsInitialized in order to try things out?

Honestly the easiest thing to do would be to modify one of the existing components to do this, and hack calling it into either the reference-browser or fenix (use substitutions so that your local/unpublished code is usable). This avoids needing to set up a stub android project that pulls in our code and geckoview, etc.

**Comment by rfk** [comment]
(from conversation earlier today, @eoger has picked up the thread here)

**Comment by rfk** [comment]
Based on @eoger's experiments, the plan is to use `dlopen` rather than linking directly against it; should we close this out as "confirmed enough to enable future work"?
