### ISSUE TITLE
`fetch_bookmark` does more queries than we'd like when `get_direct_children` is true

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#806]
One option is to modify `fetch_tree` so that it's usable in this case. Follow-up from #743

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-128)

**Comment by lyuyuan92** [comment]
I'd like to have a try on this issue.

**Comment by cse-test-sync** [comment]
Transition made by Unito

**Comment by thomcc** [comment]
Hmm, @jdragojevic was this intentionally reopened or was it a casualty in some jira operation?
