### ISSUE TITLE
fetch_tree should return position and parentGUID information

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#808]
As it is `fetch_public_tree` has to fix it up afterwards, which both takes additional query and is a pain.

Worth keeping in mind https://github.com/mozilla/application-services/issues/807 also, since the main reason this is difficult is that it does not return a type that can store parentGUID / position.

Follow up from #743.

**Comment by lyuyuan92** [comment]
I am looking into this issue. May need a little guidance from you later if I cannot figure out a solution for it :)
