### ISSUE TITLE
`run_maintenance` should fix up bookmark tree corruption.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#809]
As described on the tin. Follow-up from #743.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2659)
┆Epic: Important backlog

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864937

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
