### ISSUE TITLE
`update_bookmark_from_message` does more queries than we'd like

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#810]
Well, it does 1 more query than we'd like. We should change it to pass a raw bookmark into `update_bookmark_in_tx` (which should be changed / another function added to accept an already-queried raw bookmark)

Follow-up from #743

**Comment by lyuyuan92** [comment]
Hi Thom, is this issue about modifying `update_bookmark_in_tx` to accept `RawBookmark` which already describes `bookmark_type`, so that we can avoid the query that returns `node_type` in `update_bookmark_from_message`? Please let me know if I have misunderstood this, thanks!

**Comment by thomcc** [comment]
Yes.

Basically, we do a query for `node_type` in `update_bookmark_from_message`, in addition to the `get_raw_bookmark` call, in `update_bookmark_in_tx`.

There are a few ways you can solve this, and one of them is absolutely adding a `RawBookmark` argument to `update_bookmark_in_tx`, as you describe.
