### ISSUE TITLE
Store an integer in sync15::ServerTimestamp instead of f64

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#815]
Storing these as floats makes various things in rust code mad, as they don't implement PartialEq, and clippy in particular dislikes comparing with them.

In practice this is seconds with a resolution of the hundreds place, we could just store integer milliseconds and be done with it. There's already a comment about this here, but it never had an issue filed https://github.com/mozilla/application-services/blob/master/components/sync15/src/util.rs#L20-L24

**Comment by lyuyuan92** [comment]
May I have a try on this issue?

**Comment by lyuyuan92** [comment]
@thomcc Hi, thanks for guiding me on my pull requests! Please close this one if no more changes are needed.

**Comment by thomcc** [comment]
Thanks for reminding me to!
