### ISSUE TITLE
Require signed commits?

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#825]
I thought we'd already set the "require signed commits" bit in this repo, but apparently not. Doing so is a [security recommendation](https://wiki.mozilla.org/GitHub/Repository_Security#Repository) from secops, and seems like it will become more valuable as our work makes it into more products. Any objections to enabling this requirement in repo config?

**Comment by thomcc** [comment]
Didn't we do this already?

**Comment by rfk** [comment]
I went ahead and did this.
