### ISSUE TITLE
Check licensing on `text_io` crate, or remove it

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#828]
Over in https://github.com/mozilla/application-services/pull/827 I'm poking at an automated license-compatibility check for our rust dependencies. It highlighted the `text_io` crate as having a non-standard license, which if you dig in describes itself as [The MIT non-military non-spy License (MIT)](https://github.com/oli-obk/rust-si/blob/master/LICENSE).

Laudible goals perhaps, but I don't know how our legal team feels about these kinds of vague do-no-evil licenses.  `Cargo.lock` says that we pull this in as a dev dependency of fxa-client.  Is it providing sufficient value that we should further investigate the licensing situation here?

Blocks #827

**Comment by vladikoff** [comment]
they are fixing it here it seems : https://github.com/oli-obk/rust-si/issues/17

**Comment by thomcc** [comment]
This is only used for the fxa example code, which AFAIK didn't even work until recently (it compiled, but would print `()` prior to clippy warning us about that being a very strange thing to do.

Also in our components/support/cli crate we have tools to do the same thing that text_io provides.

**Comment by rfk** [comment]
> Also in our components/support/cli crate we have tools to do the same thing that text_io provides.

In that case, I have a mild preference for removing this dependency.

**Comment by rfk** [comment]
Going to do this as an exercise in making sure my build toolchain is up-to-date...
