### ISSUE TITLE
Document naming conventions used in various source files

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#831]
CC @jrconlin 

Roughly:

* all rust code: snake_case.
  * ffi/src/lib.rs: snake_case and with a prefix based on the library
* LibBlahFFI.kt, RustBlahFFI.h: snake_case because it must match rust code
* kotlin and swift code: match conventions of the language unless otherwise specified.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-698)

**Comment by eoger** [comment]
Closed by https://github.com/mozilla/application-services/pull/3044.
