### ISSUE TITLE
Find way to test network abstraction when backed by geckoview.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#834]
Part of network work. See #348. Can be done after landing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-682)
┆Epic: Docs & tools for local, integration and release builds
┆Sprint: Backlog

**Comment by jdragojevic** [comment]
moving to backlog, manually testing done, automation hard.

**Comment by jdragojevic** [comment]
closed d/t lack of action.
