### ISSUE TITLE
Run rust unit tests on other platforms

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#836]
At least in ffi_support it would be convenient to be able to have a test that asserts that the size of something is what we think. If this doesn't run on the architectures we actually target, it wouldn't be valuable.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-686)
┆Sprint: Backlog

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Pulling this into out "integration testing" epic, since knowing that our code works on the platforms we actually ship on seems like an important part of integrating into downstream apps.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Even if it's too expensive to run these on every PR, we should try to run them on release-candidate PRs for completeness.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

[~tchiovoloni@mozilla.com] are you able to pitch a concrete example of the sort of test you can in mind here? I'm picturing a kind of `assert sizeof(foo) == bar`-shaped thing but I don't know what use-case was originally motivating this bug.
