### ISSUE TITLE
Rust SwiftLint on CI

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#842]
Just like https://github.com/mozilla/application-services/pull/841 for Kotlin code, we should run [SwiftLint](https://github.com/realm/SwiftLint) over our Swift code.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-135)

**Comment by thomcc** [comment]
See also https://github.com/mozilla/application-services/issues/607

**Comment by eoger** [comment]
Closed by https://github.com/mozilla/application-services/pull/1077.
