### ISSUE TITLE
Explore replacing `SyncGuid` with `dogear::Guid`

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#848]
See https://github.com/mozilla/application-services/pull/723#discussion_r268012700. Dogear has an optimized `Guid` type (mozilla/dogear#10) that uses 12-byte stack allocated arrays for valid GUIDs. Might be worth exploring if we can use it.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-136)

**Comment by thomcc** [comment]
I also wrote https://github.com/mozilla/application-services/tree/sync-guid at one point which performs a similar optimizaiton, but is more general and would be acceptable for using as the guid returned in sync15 as well. I just never got around to actually writing the code to replace it.

See also #268

**Comment by lyuyuan92** [comment]
Hi, may I have a try on this one? Should I use `dogear::Guid` or the `Guid` in branch `sync-guid`?

**Comment by thomcc** [comment]
Yeah, I'm a bit busy today but what I think we want here is a bit complex, and I'll write it up tomorrow.

**Comment by rfk** [comment]
IMHO #268 is the way to go here (perhaps via the "move it into a shared crate which is depended on (and it's types reexported by) sync15-adapter and dogear" route described therein).

**Comment by thomcc** [comment]
I agree, #268 is the right approach. Dogear's guid is somewhat pessimized for some cases that would be important for a general sync-guid type, however

**Comment by lyuyuan92** [comment]
Thanks for the notes. I will look into the commit in branch `sync-guid` first then.

**Comment by thomcc** [comment]
See also https://github.com/mozilla/application-services/tree/guid-support which was... me forgetting that I had pushed the sync-guid branch up before getting another computer.
