### ISSUE TITLE
Store the history and bookmarks sync IDs in `moz_meta`

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#851]
So we can tie the database to `meta/global`, like we do on Desktop. If there's a mismatch, we should call `BookmarksStore::reset` to drop all Sync state, and start over as if it's a first sync.

**Comment by linacambridge** [comment]
Related to #850, too.

**Comment by linacambridge** [comment]
Likely fixed by #892?

**Comment by mhammond** [comment]
Fixed by #892
