### ISSUE TITLE
Error messages not coming through on iOS

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#853]
We're seeing reports of this error on Sentry in the latest Firefox for iOS Beta:

```
The operation couldn’t be completed. (MozillaAppServices.LoginsStoreError error 0.)
```

and

```
The operation couldn’t be completed. (MozillaAppServices.LoginsStoreError error 7.)
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-138)

**Comment by thomcc** [comment]
From discussion in Slack: 7 is network error, 0 should have a message, and we should investigate why the message is dropped on the floor.

**Comment by thomcc** [comment]
Also: The link you had earlier showed this happening in the sync method and not the state_new method, which is right? I'd be extremely surprised if we're getting network errors in sync15_passwords_state_new

**Comment by justindarc** [comment]
Yes, my bad. Copy/paste error. Fixed the title.

**Comment by bug-mirror** [comment]
from mtg: iOS is not getting error messages from Swift stuff, need help figuring this out from @justindarc

**Comment by cse-test-sync** [comment]
Transition made by Unito

**Comment by thomcc** [comment]
This is done, not sure if it was reopened intetionally
