### ISSUE TITLE
Expose method in places for setting secure_delete SQLite option

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#862]
We have turned off `secure_delete` by default in the iOS SQLite build for performance reasons. However, we should at least expose an API for turning it on as-needed:

https://www.sqlite.org/pragma.html#pragma_secure_delete

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2662)
┆Epic: Important backlog

**Comment by thomcc** [comment]
We turned it on for logins storage, since this is a per-connection attribute that seems fine to me. I guess maybe we want a way to enable it for places.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1864942

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
