### ISSUE TITLE
Come up with a strategy around panics

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#863]
Currently we return these as exceptions to the caller, however we don't reallydocument the recovery process (in general: close and reopen to drop and reconstruct the poisoned mutices)

Now that we have crash symbols, we could consider crashing on panics. In practice these never happen and indicate a programming error.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-684)
┆Sprint: Backlog

**Comment by mhammond** [comment]
While I agree that in-theory a crash is fine (and arguably preferred), I'm concerned about in-practice - that some bizarre state would cause the embedding apps to crash every time we are used (eg, on every startup), whereas throwing exceptions every time we are used might mean the browser kinda-works even if nothing from our components does.

What would be involved in having the FFI do the recovery while still allowing us to get crash symbols? ie, how hard would it be to have our cake and eat it too courtesy of the ffi layer? (I'm guessing "very")

**Comment by thomcc** [comment]
We'd need to fix #441, which since then I've heard is harder than it seems.

**Comment by jdragojevic** [comment]
Closing as something we've never acted on, and I believe we have more current conversations around poison.
