### ISSUE TITLE
Compile SQLCipher with arm64 instruction set

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#872]
We use the arm one:
https://github.com/mozilla/application-services/blob/3bb9f542d232ceb2f5fd420211630d89db6334be/libs/build-sqlcipher-ios.sh#L37
Which works on iPhones running arm64 processors, but we might as well build the 64 bits version since we don't support the old architecture anymore.

I believe the correct value is `aarch64-apple-darwin`

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-142)
┆Story Points: 2

**Comment by thomcc** [comment]
Might want to do #816 at the same time since both are easy and will cause people to have to rebuild things.

**Comment by thomcc** [comment]
The `config.sub` (and config.guess, although IDK if that one gets mad) that `sqlite` and `sqlcipher` use is from an old version of autotools, which doesn't support arm64.

We could update it using https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html, and I believe things would work, however we do pass -arch arm64 here: https://github.com/mozilla/application-services/blob/3bb9f542d232ceb2f5fd420211630d89db6334be/libs/build-sqlcipher-ios.sh#L57, so I think it might actually be generating arm64 code anyway. 

However, this issue may exist on android: https://github.com/mozilla/application-services/blob/77f7686eed5116f675aa0115016abeb0f7d262fe/libs/build-sqlcipher-android.sh#L47

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

waiting for response on the PR
