### ISSUE TITLE
Stop supporting non-megazord builds.

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#876]
As documented [here](https://github.com/mozilla/application-services/blob/master/gradle-plugin/README.md), we currently maintain two very different varieties of built artifact.

For development use, we compile each individual component's rust code into its own `.so` file, and bundle that up with the compiled Kotlin code into a standalone `.aar`.  This makes it easy to swap out individual components during development and testing, because you only have to rebuild that one component.  But it leads to a lot of duplication because each `.so` file has its own copy of the rust standard library and of any shared dependencies.

For production use, we compile all the rust code for all our components into a single shared `.so` called a "megazord", which allows us produce a nice optimized build without duplicate copies of things.  We then publish a special "-withoutLibs" version of the `.aar` for each individual component, which contains just the compiled Kotlin code without any `.so`.

This system worked well to get us up and running, but we're starting to run into some pain-points.  The individual-component builds do not play nicely with globally-configurable state, such as pluming in to Android's logging facility, or plumbing into a shared networking abstraction.  And they can make us jump through awkward memory-management hoops to ensure that objects allocated from one `.so` are not freed by rust code in another `.so`. There may be other pain-points here as well, please comment below.

Do the benefits we get from supporting non-megazord build configurations still outweigh the costs of the complexity required to support both varieties of build artifact?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-143)
┆Story Points: 8
┆Sprint: SYNC - 2019-07-19

**Comment by thomcc** [comment]
They're making the network, err, work more difficult, as they're a difficult to handle special case in the build configuration. They're an android build that needs to behave how all our non-android builds behave, and they require awkward cargo feature propagation through multiple crates. This may end up being true for the crypto work as well, and other work in the future.

**Comment by thomcc** [comment]
Additionally, we maintain (or, try to) a gradle plugin to support migration to the megazord use case from the non-megazord case, but it's unclear how much this helps versus hurts. For example, I suspect it would be easier getting unit testing workable again (#652) without this.

That said, it's unclear how we could move to a non-megazord world given the android-components model.

**Comment by rfk** [comment]
> it's unclear how we could move to a non-megazord world given the android-components model.

Right. My naive high-level interpretation is that we'd basically only support the current megazord-style build where:

* We publish a manage-code-only `.aar` for each of our components, which all depend on
* Some sort of general-purpose megazord `.aar` containing the megazorded `.so` and maybe some initialization support APIs for calling from Kotlin, and
* Provide the ability for product builds to swap out the general-purpose megazord for one that's built specifically for their needs, with only the code they want.

IIUC the big downsides of this would be:

* Large download size, as developers who only want the fxaclient component have to take a dependency on the entire megazord.
* Long compile times if you want to make a change to any of the rust code, because you need to rebuild the entire megazord.

I think we'll need folks like @grigoryk to provide feedback on how the current developer experience is working out, and on what the costs would be of trying to change it.

**Comment by thomcc** [comment]
> Large download size, as developers who only want the fxaclient component have to take a dependency on the entire megazord.

It turns out this is actually not very significant due to reasons nobody fully understands, see the listing in https://github.com/mozilla/application-services/issues/558 (which is dated, but to our knowledge still accurate).

**Comment by fzzzy** [comment]
Can a megazord build be configured to contain only one component? This would have the advantages of a megazord build (one build path) and still allow only recompiling one module or only including one module if required.

**Comment by thomcc** [comment]
It needs to contain logging (and, moving forward networking). It also has an awkward initialization process, and you can only have one in your app at a time. So yes, but you’d lose the component model still.

**Comment by thomcc** [comment]
One way we could do this is if we had a 'everything' megazord which is used in place of the current non-megazord cases. E.g. we'd no longer distribute separate `org.mozilla.appservices:places` and `org.mozilla.appservices:logins`, etc, we'd just ship `org.mozilla.appservices:everything` (name to be bikeshed).

Then, A-C would depend on this. If you needed both places and logins, you'd still only need one copy of this, since gradle knows not to include multiple copies of a library if two dependencies depend on it.

We'd still distribute the megazords, and the megazord plugin, instead of swapping N:1 megazords, would only swap out 1:1, the `everything` megazord for a more specifically targetted megazord which only has the dependencies you need.

Pros: 
- This would remove all the complexity we have around non-megazord cases
- Logging, Networking, Etc would work as expected in 'non-megazord' case (there is no non-megazord anymore).
- Non-megazords still small.
- If someone ends up shipping with a non-megazord, it's not the worst thing in the world (They just have more code than they need)
- Megazord-only things like networking and crypto become a lot easier to test.

Cons:
- Complete opposite of how things are set up now
- Slower builds in substitution mode.
- Potentially larger builds in the cases where you only need one component (but perhaps not, #558). However, we still wouldn't want you using the non-megazord in this case (It would use the wrong network stack), so, this isn't really a realistic concern

Probably other pros/cons.

**Comment by rfk** [comment]
Since github issues can make large proposals hard, I've tried to capture our current thinking in a google doc here:

  https://docs.google.com/document/d/16VdoUMgp3MSVq8ZZRqxRMOKmWA3sQZ3WTS6xbx9ViIM/

All commends and feedback welcome!

**Comment by rfk** [comment]
If we do go this route, I'd like to understand how the application initialization code would change.  For example, the current Fenix initialization code is here:

  https://github.com/mozilla-mobile/fenix/blob/9dc0b4781a364f886bb7d5201734cd741629d282/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L34

And here:

  https://github.com/mozilla-mobile/fenix/blob/9dc0b4781a364f886bb7d5201734cd741629d282/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L119

How would this code look different under an "always megazord" approach? How will this code change once it has to set up networking as a depdendency?  For example, would the class "mozilla.appservices.FenixMegazord" disappear in favour of a generic "mozilla.appservices.Megazord" class that is always present regardless of build type.

**Comment by rfk** [comment]
(I also wonder if we may be able to remove the term "megazord" from our consumer-facing vocabulary in this case; you could imagine replacing `mozilla.appservices.FenixMegazord` with a more prosaicly-named `mozilla.appservices.RustSupportModule` class of some kind, which would be simultaneously less fun and less confusing).

**Comment by thomcc** [comment]
On friday I experimented with this in https://github.com/mozilla/application-services/tree/only-megazords. Some unexpected issues:

- We'd like all `-library` packages to depend on `full-megazord`, but `full-megazord` wants to be able to take a `Lazy<Client>` in it's initialization function. I worked around this with reflection, but that kind of sucks.
- For some reason, the `-library` packages don't want to recompile the `full-megazord`. 
- For some reason, even if I hack around the above by manually adding the task dependency, we fail to copy the .so into the right place in the end.

The last two points are probably an issue with my implementation.

Some notes:

- If all megazords have the same package / classname, there's no need for a weird reflection hack in consumers. they just use `mozilla.appservices.Megazord`, which may be swapped out with a different version of the exact same class.

**Comment by bug-mirror** [comment]
from mtg: after iOS stuff

**Comment by rfk** [comment]
I think it's useful to consider our plans through the lens of "what does the final consumer experience feel like", so I tried to adapt @ncalexan's https://github.com/mozilla-mobile/fenix/pull/1787 to the world envisaged by this issue.  The result is thus:

  https://github.com/ncalexan/fenix/pull/1/files

That doesn't feel too bad to me, although it might be nice to further simplify the gradle dependency-substitution stuff. It also makes me feel like we may be better served by using a class name like `org.mozilla.appservices.RustCore` or similar, rather than the inscrutable-to-the-uninitiated `Megazord`. But those are minor details.
