### ISSUE TITLE
Push Component should return None instead of blank strings

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#877]
for `components/push/ffi/src/lib.rs`

`push_verify_connection` and `push_dispatch_for_chid` should return None values.
This may require changing to `Result<Option<String>>` as well as tweaking the `rustCall`  functions in `PushManager.kt`.

Need to ping @thomcc for help on this one.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-144)

**Comment by eoger** [comment]
@jrconlin: I've chatted with @jonalmeida today who told me they don't use this method at all in android-components. Would there be any use for this method in a DOM Push context or in other platforms such as Desktop or iOS? Or should we just kill this method?

**Comment by jrconlin** [comment]
If push doesn't have to worry about sending push messages to recipient processes, then yes, `push_dispatch_for_chid` can be killed.
