### ISSUE TITLE
FxA dependency build scripts shouldn't rebuild the world every time

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#88]
We should be able to do incremental builds. All three libs use autotools, so I think this would probably work out of the box if we just used normal [vpath builds](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html#VPATH-Builds) (e.g. when you invoke configure from a different directory than the directory where it lives).

I think this would look like:

```sh
mkdir -p build-$ARCH-$HOST
cd build-$ARCH-$HOST
../configure --host="$HOST" --with-openssl="$OPENSSL_DIR" --with-jansson="$JANSSON_DIR" && 
cd -
```

around https://github.com/mozilla/application-services/blob/master/libs/build-cjose-ios.sh#L40 or so, (and in the other build scripts ofc) as long as we also update the parts that grab the build artifacts out of the folders so that they look in the right place.

There shouldn't be any need to have a `make clean` also, because we wouldn't have the build artifacts for the wrong build lying around. In fact, keeping `make clean` would defeat the whole point. There might be a use case for it so it's possible that we either want to keep a script that does it, maybe.

Sorry in advance if there's a reason we aren't doing this already.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-145)

**Comment by eoger** [comment]
From the [docs](https://wiki.openssl.org/index.php/Compilation_and_Installation), apparently openssl doesn't use autotools and I haven't been able to find something similar to the vpaths feature (however thank you for making me aware of it!).

On the parallelization front, I've been experimenting this afternoon with the `j` parameter and always got a faster build without specifying it, which is pretty surprising.

**Comment by eoger** [comment]
I believe we got better at this.
