### ISSUE TITLE
Consider linting bash scripts

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#893]
We can do it using [shellcheck](https://github.com/koalaman/shellcheck):
`for file in $(find libs -name '*.sh' -type f); do shellcheck --format=gcc $file; done;`

While I'm at it, I wonder if we should convert some part of this libs/ code in python and only keep the actual bash `export`, `configure`/`make` calls in small bash scripts.

**Comment by thomcc** [comment]
My python env is a disaster zone so I have a soft wish against this.

Really though, I think the libs/ code would be a lot simpler and efficient as makefiles (which automatically support the notion of 'only do this if the file has changed'. I had a version of this at one point but I decided it was too big of a change.

**Comment by vladikoff** [comment]
from mtg:

* let's lint bash!
