### ISSUE TITLE
Prevent reqwest from being compiled into the megazords

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#897]
We're compiling reqwest into the megazords, even though it's never used. This is done because of limitations of cargo features. The best known way of preventing this seems to be to use #[cfg(target_os="android")] to avoid using the reqwest in android builds. This isn't workable because we need reqwest for non-megazord builds as well.

We plan on killing non-megazords soon (later comments in #876 describe a path forward here), and after we do so, we can prevent reqwest from being compiled in, which should reduce compile size by a decent amount, and have other benefits.

This is a follow-up of #835, but is blocked on #876.

**Comment by bug-mirror** [comment]
from mtg: should be closed!
