### ISSUE TITLE
Add a workspace hack to prevent unnecessary recompilations

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#903]
This seemed pointless due to non-megazord builds, but actually should be worth it again if we kill them. An example of what I mean by 'workspace hack' is https://searchfox.org/mozilla-central/source/build/workspace-hack/Cargo.toml.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-711)
┆Sprint: Backlog

**Comment by eoger** [comment]
@thomcc Still worth doing with the new megazord?

**Comment by jdragojevic** [comment]
closing as something we didn't do.
