### ISSUE TITLE
Use `parking_lot`, and `crossbeam-channel` for concurrency primitives

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#904]
The ones offered by the stdlib are fine, but slower, and have notable drawbacks. Now that the maintainer of `parking_lot` and `crossbeam` is a maintainer of these sections of the rust stdlib, over enough time, we would expect these to move to be the standard implementations.

That said, that may take an arbitrarily long amount of time, and in the meantime, we could get a perf boost if we switched over globally to these implementations. They're pretty light on dependencies so I don't expect code size to be a problem (Especially if we switch globally, and can omit the `std::sync::Blah` code. These are also already in our dependency graph.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-147)
┆Story Points: 2

**Comment by jdragojevic** [comment]
Would fix: https://github.com/mozilla-mobile/reference-browser/issues/710

ref: https://sentry.prod.mozaws.net/operations/fenix/issues/5499719/events/ - keep monitoring event to see how common it is and decide if we should escalate and balance against risk.

**Comment by lyuyuan92** [comment]
I would like to work on this issue. Do you still plan to land this before 2019-06-14?

**Comment by thomcc** [comment]
It's unclear if we're going to do this at all, actually. I think we're concerned about the fact that we might be relying on the poisoning. You should find another issue to work on until we make this decision.

**Comment by lyuyuan92** [comment]
OK, thanks!

**Comment by rfk** [comment]
From mtg: this is a sufficiently small micro-optimization, with sufficient uncertainly around poisoning behaviour, that it's not worth pursuing for now.
