### ISSUE TITLE
Confirm security review outcomes for Crypto code

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#910]
Confirm security review outcomes for Crypto code
- [ ] generation of random numbers for initialization vectors
- [ ] sync1.5
- [ ] fxa
- [ ] push
- [ ] rust ece

**Comment by bug-mirror** [comment]
from mtg: follow up issues coming soon!

**Comment by rfk** [comment]
The important outcomes here so far are:

* Martin's feedback on cleaning up the rust-ece API over in https://github.com/mozilla/application-services/issues/1068#issuecomment-486073712
* Moving the verify-hmac-and-decrypt step for Sync into a single operation, along the lines discussed in https://github.com/mozilla/application-services/issues/955#issuecomment-483949735

**Comment by rfk** [comment]
I'm going to close this in favour of the two items above, plus the ongoing NSS work in which we will loop in the experts for review.
