### ISSUE TITLE
Consider stripping megazord builds by default

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#913]
Fenix is shipping an unstripped `libfenix.so`, as described in https://github.com/mozilla-mobile/fenix/issues/1374.

I took a quick look at Lockbox and it's also shipping an unstripped `liblockbox.so`.  Worse, it's shipping unstripped `.so`'s for multiple platforms in a single `.apk`:

```rfk@pomelo:lockbox$ ls  -lR --block-size=M lib/*/
lib/arm64-v8a/:
total 45M
-rwxrwxrwx 1 rfk rfk  1M Dec 31  1979 libjnidispatch.so
-rwxrwxrwx 1 rfk rfk 45M Dec 31  1979 liblockbox.so

lib/armeabi-v7a/:
total 40M
-rwxrwxrwx 1 rfk rfk  1M Dec 31  1979 libjnidispatch.so
-rwxrwxrwx 1 rfk rfk 40M Dec 31  1979 liblockbox.so

lib/armeabi/:
total 1M
-rwxrwxrwx 1 rfk rfk 1M Dec 31  1979 libjnidispatch.so

lib/mips/:
total 1M
-rwxrwxrwx 1 rfk rfk 1M Dec 31  1979 libjnidispatch.so

lib/mips64/:
total 1M
-rwxrwxrwx 1 rfk rfk 1M Dec 31  1979 libjnidispatch.so

lib/x86/:
total 40M
-rwxrwxrwx 1 rfk rfk  1M Dec 31  1979 libjnidispatch.so
-rwxrwxrwx 1 rfk rfk 40M Dec 31  1979 liblockbox.so

lib/x86_64/:
total 1M
-rwxrwxrwx 1 rfk rfk 1M Dec 31  1979 libjnidispatch.so
rfk@pomelo:lockbox$
rfk@pomelo:lockbox$
rfk@pomelo:lockbox$ du -hs lib/
125M    lib/
rfk@pomelo:lockbox$
```

Perhaps we should reconsider our choice not to strip by default, at least for the megazord builds, as documented here:

  https://github.com/mozilla/application-services/blob/42d387bbd178281d09caf8a8ec26250f34d9e66c/megazords/fenix/android/build.gradle#L28-L33

**Comment by thomcc** [comment]
Debugging native libraries already requires messing with several things, I don't actually think it's too unreasonable to just strip everything and require us add `packagingOptions { doNotStrip: "**/*.so" }` to debug native code (This does mean we probaly just want to comment it out, and document that you should do uncomment these when trying to use a native code debugger).

**Comment by rfk** [comment]
> (This does mean we probaly just want to comment it out, and document that
> you should do uncomment these when trying to use a native code debugger).

This makes sense to me; given that our two main consumers have both shipped without stripping, leaving unstripped as the default seems like it's just going to be an ongoing footgun.

**Comment by ncalexan** [comment]
> > (This does mean we probaly just want to comment it out, and document that
> > you should do uncomment these when trying to use a native code debugger).
> 
> This makes sense to me; given that our two main consumers have both shipped without stripping, leaving unstripped as the default seems like it's just going to be an ongoing footgun.

I guess this is a footgun, but it's really just behaviour changing out from underneath us (and nobody deeply integrated into the consuming teams working through this).

However, the _real_ story is that now that Edouard is pushing symbols for megazords to Mozilla's crash symbol endpoint, we can support downstream consumers debugging with a standard external symbol file flow.  I have an action item to write a document for this, which I will track with [this issue](https://github.com/mozilla/geckoview/issues/50).
