### ISSUE TITLE
Consider using separate files for changelog and unreleased changes

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#919]
It's pretty easy to end up with changelog entries in the wrong place due to git automerge not understanding that we should never add something to the released portion of a changelog after the release.

**Comment by thomcc** [comment]
I'm un-backlogging this, since it got messed up twice this week (#984, #676).

Who knows how many times in the past it's gotten messed up that we didnt' catch.

**Comment by bug-mirror** [comment]
from mtg: 

PENDING.md for unreleased changes or something.

**Comment by thomcc** [comment]
For clarity: I think I'm going to do this next time we cut a release, since then I can make sure that the steps that get written down in the 'how to cut a release' doc aren't missing anything.
