### ISSUE TITLE
places_get_visit_infos should allow filtering by visit type

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#920]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/1332

Currently we're just filtering by date ranges. In the history UI, it doesn't make sense to show redirects, and likely some of the other visit types.

I think a "visit type whitelist" would make sense and allow for some flexibility here. Applications will then specify what types they specifically care about.

For reference, list of visit types we currently have:
```
LINK(1),
TYPED(2),
BOOKMARK(3),
EMBED(4),
REDIRECT_PERMANENT(5),
REDIRECT_TEMPORARY(6),
DOWNLOAD(7),
FRAMED_LINK(8),
RELOAD(9)
```

**Comment by thomcc** [comment]
Priority?

**Comment by thomcc** [comment]
Some initial thought for whoever implements it (if it's not me): We should send the whitelist over as a bit mask rather than a list to avoid unnecessary allocations / packing / unpacking. Possibly even send it into the query that way if SQL can do shifts (I imagine it can).

**Comment by grigoryk** [comment]
@thomcc I'd say pretty soon, since that makes our History UI quite cluttered - it's a very visible kind of a problem.

**Comment by grigoryk** [comment]
We could do this at the application level, but that means unnecessarily moving a lot of bits.

**Comment by thomcc** [comment]
Marking as a perf issue then.
