### ISSUE TITLE
Consider how to handle cases where server data is invalid

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#922]
A missing field will cause us to fail to deserialize, which will fail the whole sync. This seems suboptimal.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-150)

**Comment by lyuyuan** [comment]
https://github.com/mozilla/application-services/blob/ec1bf2835c0a288377415f2ec07b6184016b1f95/components/sync15/src/sync.rs#L82
Hi! @thomcc  Is this where the failure would happen?

**Comment by thomcc** [comment]
There are a few cases.

1. The encrypted record could not be valid JSON, and we'd fail here: https://github.com/mozilla/application-services/blob/c2b7f97ab43bfcf7b66b9745c4b072efc0317cbd/components/sync15/src/bso_record.rs#L342 (The `payload` property is actually a string, so we have a custom serializer that automatically deserializes it at the same time, but the 2nd part of this could fail).
2. After decryption, we could get invalid JSON, in which case we'd fail: here https://github.com/mozilla/application-services/blob/c2b7f97ab43bfcf7b66b9745c4b072efc0317cbd/components/sync15/src/bso_record.rs#L375
3. The record might be semantically invalid we already handle this for logins now, as of https://github.com/mozilla/application-services/pull/1262. Places does not handle it, I believe, so that would be something to add.

I think I meant #3 here, since I don't know that we have any evidence of #1 or #2 happening in practice. Sync would probably never recover if they did happen, though.
