### ISSUE TITLE
Increase statement cache size in places

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#925]
Rusqlite's default size is 16. Desktop, AFAICT, has an effectively infinitely large cache. We probably can afford to increase it to 128 or 256 -- something 'large but bounded'.

**Comment by lyuyuan92** [comment]
Hi Thom, could you point me to the code for this issue? Thanks!

**Comment by thomcc** [comment]
Sure. This is mostly just about adding a call to https://docs.rs/rusqlite/0.18.0/rusqlite/struct.Connection.html#method.set_prepared_statement_cache_capacity where we set up the connection, somehwere around https://github.com/mozilla/application-services/blob/master/components/places/src/db/db.rs#L72
