### ISSUE TITLE
Document our policy for managing third-party Kotlin code

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#933]
In https://github.com/mozilla/application-services/pull/827 we landed some documentation and tooling around how we handle dependencies on third-party rust code.

IIUC we also take some dependencies on third-party Kotlin code, both at build time (e.g. detekt) and at runtime (e.g. protocolbuffers). We should expand that documentation and tooling to also cover Kotlin dependencies.

I'm not entirely sure where to start here. Is there a good way to get a list of the Kotlin dependencies we current have?  `./gradlew dependencies` seems to work but doesn't print many things, while `./gradlew fenix-megazord:dependencies` prints quite a few more.

Is there a standard approach in the gradle ecosystem for detecting dependencies with known security issues, similar to [cargo-audit](https://github.com/RustSec/cargo-audit) or [npm audit](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities)?

**Comment by rfk** [comment]
It probably makes sense to just copy whatever best-practices the android-components team are using here, since they'll have substantially more expertise on this front than we do.

**Comment by thomcc** [comment]
I think we probably want to be pretty strict here, and try and reorganize things such that the dep can be pushed into the rust side in cases where we want to add a new kotlin dep. At least for runtime deps.

**Comment by bug-mirror** [comment]
from mtg: write down that only have protobufs in this, and no other dependency is allowed.
