### ISSUE TITLE
Document our policy for managing third-party Swift code

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#934]
In https://github.com/mozilla/application-services/pull/827 we landed some documentation and tooling around how we handle dependencies on third-party rust code.

IIUC we also take some dependencies on third-party Swift code, e.g. for deserializing protobuf messages. We should expand that documentation and tooling to also cover Swift dependencies.

I'm not entirely sure where to start here to be honest. Is there a good way to get a list of the Swift dependencies we current have? Is there a standard approach in the Carthage ecosystem for detecting dependencies with known security issues, similar to [cargo-audit](https://github.com/RustSec/cargo-audit) or [npm audit](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities)?

It probably makes sense to just try to copy whatever https://github.com/mozilla-mobile/firefox-ios has in place in the first instance, since they're our primary consumer of Swift.  /cc @justindarc @garvankeeley if you have any guidance to share.

**Comment by thomcc** [comment]
We probably don’t want to take any more swift deps, since they aren’t transparent for our end users.

**Comment by rfk** [comment]
> since they aren’t transparent for our end users.

Can you say more about this? I interpret it to mean "our consumers need to know about and manually configure each Swift library on which we depend".

**Comment by thomcc** [comment]
I believe that is the case, yes. It is for swift-protobuf at least.

**Comment by garvankeeley** [comment]
Consumers will need to know the dylibs used. This is accepted practice for iOS, and in my experience poses no problems, but does create documentation overhead for the producer and build config overhead for the consumer, but these are minimal. Library producers for iOS typically keep their deps to a minimum (as in zero to one). The app services lib is rather specialized, and I think it can be lower on ease-of-use than commonly used Swift libs. 

There are no auditing tools for Swift deps.

**Comment by garvankeeley** [comment]
Q:Is there a good way to get a list of the Swift dependencies we current have?

The ‘Cartfile’ in the source root lists these, consumers would know to look there in the absence of documentation, but it is expected to also document these in the usage doc for the lib.

**Comment by bug-mirror** [comment]
from mtg: only protobufs! also.
