### ISSUE TITLE
Document how to handle Taskcluster failures for releases

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#943]
Twice in the past we've had to ask a TC administrator to re-run (instead of re-trigger) a job that failed because of a transient network error which was blocking the entire release process.
Possible solutions:
- Get for some people in our team the right to re-run tasks without having to ask TC admins. I understand that re-running tasks is a deprecated feature and it is probably for a good reason.
- Simply delete the Github tag and re-do a release (people watching the repo might get multiple "github release" emails though).

@djmitche what's the best practice for this kind of issue?

**Comment by djmitche** [comment]
Either one is OK.  The main reason we don't like rerun is that it's hard to make it specific to a particular project.  We're working on that, but it's not done yet.

So, we could give you permission to rerun everything (not just your tasks).

**Comment by imbstack** [comment]
I think just giving them rerun permissions makes sense for now so long as it exists. @eoger can you file a bug in taskcluster :: operations and service requests asking for the scopes and linking to this bug? If there's a mozilla ldap group that shold have the rights, all the better.

**Comment by eoger** [comment]
Tracking issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1546212

**Comment by eoger** [comment]
We now have the rights to re-run tasks, thanks @imbstack @djmitche.
