### ISSUE TITLE
Don't allow creating an encrypted Places database

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#950]
Currently we allow this. In #760, we'll be taking it out of fenix (although in principal, IDK, reference browser could use it or something).

This is a big performance footgun (because of weird issues in sqlcipher). It also isn't clear that it's actually valuable.

It's also doesn't fit well with how PlacesApi works, and is in general kind of an afterthought.

I'm filing this as a discussion since actually removing it is quite easy, but I don't know what the feelings of people besides myself are.

CC @mhammond @grigoryk @linacambridge

**Comment by rfk** [comment]
It's my understanding that we want to migrate away from SQLCipher for other reasons anyway, even for logins. If that is the case then I'm a strong +1 on removing the possibility of future migration work in other stores.

**Comment by mhammond** [comment]
+1 from me - I assume you mean simply dropping support for the encryption-key param?

**Comment by thomcc** [comment]
Yep!

**Comment by linacambridge** [comment]
I agree, for all the reasons you mentioned!

**Comment by grigoryk** [comment]
+1 from me; AFAIK we don't have product requirements dictating a need for this for Fenix.

**Comment by thomcc** [comment]
Fixed in #996
