### ISSUE TITLE
Add a brief README for viaduct

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#951]
In [this comment thread](https://docs.google.com/a/mozilla.com/document/d/10I8MD_narf3D7w1F0rciye-cRpwKO6ItE_UdCtFKTmA/edit?disco=AAAAC5Ut7R4) on the program review, :mt tried to do a bit of a review of viaduct but had trouble following what it was up to. I think a brief readme motivating the what and the how could help make this easier to review in future.

**Comment by thomcc** [comment]
I can do this tomorrow. Just to check, should it be a policy going forward that all new crates need a brief readme at their root?

**Comment by rfk** [comment]
> Just to check, should it be a policy going forward that all new crates need a brief readme at their root?

This seems worthwhile to me, but I'm open to pushback if it doesn't seem valuable in the general case.

**Comment by thomcc** [comment]
Github didn't close this when it should have https://github.com/mozilla/application-services/pull/964
