### ISSUE TITLE
Expose a getBookmarksWithKeyword() API

### ISSUE THREAD

**Issue by justindarc** [mozilla/application-services#953]
Firefox for iOS previously had support for bookmarks keyword searches in the AwesomeBar. To continue to support this, we will need the following API:

```
getBookmarksWithKeyword(keyword: String) -> [BookmarkItem]
```

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-153)

**Comment by thomcc** [comment]
We don't support keywords really, although maybe we should. (We have support for syncing them, so it's not like we're completely oblivious to them)

CC @linacambridge @mhammond

**Comment by mhammond** [comment]
I think the main reason we haven't supported them is that desktop plans on moving away from keywords - although I can't find a bug to back that up. I believe @linacambridge knows more about this so hopefully she'll chime in.

**Comment by justindarc** [comment]
We're gonna have like 3(?) users on iOS that are gonna be sad to hear that.

In all seriousness, this isn't the most important thing for us right now. I've simply just disabled that code for the time being. If desktop removes support for it, we'll just drop it.

**Comment by thomcc** [comment]
I think @davismtl has indicated that the rumors about bookmark keywords going away in desktop had been exaggerated

**Comment by davismtl** [comment]
Correct. I don't think they are going anywhere soon. (per what I heard from other product managers)
And... Dcamp said "over his dead body". So... lots' of uncertainty for now.

**Comment by rfk** [comment]
> Dcamp said "over his dead body". So... lots' of uncertainty for now.

I dunno, that sounds like the opposite of uncertainty to me ;-)
