### ISSUE TITLE
Merge NSS source patches upstream

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#954]
We have a bunch of patches for NSS in [patch-nss-src.sh](https://github.com/mozilla/application-services/blob/a560ea124355c7a845b92c244eed66544f708274/libs/patch-nss-src.sh) that should be easy to get accepted upstream.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-154)
┆Story Points: 1
┆Epic: Trusted Crypto

**Comment by rfk** [comment]
Just noting for passers-by that these are build-related patches, we haven't gone in and patched the crypto routines or anything "clever" like that...

**Comment by eoger** [comment]
List of patches (will update the list as we go):

- [X] https://bugzilla.mozilla.org/show_bug.cgi?id=1540205
- [X] https://bugzilla.mozilla.org/show_bug.cgi?id=1549413
- [X] https://bugzilla.mozilla.org/show_bug.cgi?id=1549416
- [X] https://bugzilla.mozilla.org/show_bug.cgi?id=1549608
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1549847
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1549848

**Comment by eoger** [comment]
Done!
