### ISSUE TITLE
Link to NSS statically

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#956]
> On some platforms like iOS, loading a dynamic library incurs a performance overhead. It also drives the binary size up. Static linking might help this a little, even if the PKCS#11 interface will force certain symbols to be present even when they aren't used.

Depends on [bug 1543545](https://bugzilla.mozilla.org/show_bug.cgi?id=1543545).

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-156)
┆Sprint: SYNC - 2019-07-19
┆Epic: Trusted Crypto

**Comment by thomcc** [comment]
NSS also bundles it's own SQLite, which will prevent us from using it even if the work is done to make it workable as a static library. We'd either have to make it use our SQLite, or change it to allow compiling NSS without SDB support. I think both of these require patches to NSS to fix.

**Comment by rfk** [comment]
@martinthomson mentioned that he has successfully built and used NSS as a static lib for another project, although this required building via gyp rather than the Makefiles. Martin, could you please prodive details/links to how you got this up and running?

**Comment by martinthomson** [comment]
The build that I have for neqo [uses private build outputs](https://github.com/mozilla/neqo/blob/f897bb1292dcd793620c017c7f2cef6c771c4686/neqo-crypto/build.rs#L78) and some [custom flags](https://github.com/mozilla/neqo/blob/f897bb1292dcd793620c017c7f2cef6c771c4686/neqo-crypto/build.rs#L155) on the build to disable dynamic loading at one point.

For us to formalize static library output, we would need to fix [bug 1543545](https://bugzilla.mozilla.org/show_bug.cgi?id=1543545).  I'll comment there about what might need to happen for that to work.

@thomcc is right in identifying one of the worst bits.  Firefox tells NSS not to build against sqlite.  That's the `use_system_sqlite` define passed to gyp.  I think that's that part sorted out, provided that you have some other way to get sqlite. I don't think that you want to build NSS without sqlite support at all.  But I don't understand that piece of NSS at all.

**Comment by thomcc** [comment]
> I don't think that you want to build NSS without sqlite support at all

Why not?

**Comment by martinthomson** [comment]
NSS used to use a different database, and it still supports that in some ways, but I don't think that it's possible to build NSS without at least referencing sqlite.  The build explicitly depends on `sqlite3.h`, with no way to disable that, so I'm guessing things would go badly if you didn't have sqlite at all.  But you can link to the system version (or statically link to an existing version if that was what you prefer).

**Comment by eoger** [comment]
Right, what @thomcc proposes is putting the SQLite symbols (and `sdb.c` by extension) behind a flag, a bit like https://github.com/eoger/nss/commit/209b4b709f56f88a2d310837bb82d699d5474259.

**Comment by thomcc** [comment]
Actually, there might not be a huge reason to do this. If we're statically linked, it will find the one we're statically linked with, and if we're dynamically linked it can bring it's own. It's not ideal that it's bringing it's own in the dynamically linked case, but it doesn't really matter (beyond file size).

**Comment by martinthomson** [comment]
I have no idea how eoger/nss@209b4b7 would work without a lot of work.  I suspect that it needs more than just cutting sdb.c from the build.  You would need to excise all use of databases as well, I think.

I'm sure that the extra bits sqlite adds to the build are less critical than things like S/MIME, which you clearly don't want.

**Comment by martinthomson** [comment]
An unrelated item I discovered: NSPR can't be statically linked because the three libraries all contain a copy of the same symbol as part of the NSPR "version protocol".  If we want static linking there, we'll need to excise that symbol, which should be easy enough to do post-facto, but we might want to tweak NSPR.

**Comment by thomcc** [comment]
> I'm sure that the extra bits sqlite adds to the build are less critical than things like S/MIME, which you clearly don't want.

The main concern is that we both use SQLite, and provide our bundled version of SQLite for use by iOS consumers. We don't want to end up accidentally using/providing NSS's older version.

**Comment by martinthomson** [comment]
Anyone looking to get a head start on this can pull in the patch at https://phabricator.services.mozilla.com/D29303
