### ISSUE TITLE
Use rust-hawk with an NSS crypto backend

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#959]
We might need to fork it in our repo, thoughts @rfk @thomcc?

**Comment by thomcc** [comment]
I had been thinking we'd modify it to allow it to take a trait that implements the crypto bits it needs, but that would be more painful, and would muck up the rust-hawk API and it would not be easy to make it work only behind a feature...

So, I'm not sure.

CC @djmitche

**Comment by djmitche** [comment]
It's just HMAC that would need to be exposed, right?  We already make people specify the algorithm by exposing the SHA256, etc. values from the underlying crypto library.  We could potentially get rid of that requirement and just ask that users provide an object implementing the desired HMAC algo. Then provide examples of how to do that with a few libraries, including NSS.  The tricky bit is that the algos take different key lengths, but that's probably solvable.

I think app-services is just about the only user of this crate, so I'd prefer a breaking change to just require NSS over forking the crate (which would leave upstream with zero users).

**Comment by thomcc** [comment]
Also random number generation, at least.

**Comment by thomcc** [comment]
But that makes sense and is probably doable. Thanks.

**Comment by vladikoff** [comment]
There's a PR!

**Comment by bug-mirror** [comment]
from mtg: waiting for rust-hawk to cut a new release

**Comment by jdragojevic** [comment]
closing since they are part of the big pr
