### ISSUE TITLE
Build NSS using gyp and ninja

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#963]
NSS still can be built by invoking `make` directly but it seems that they consider this way legacy now and want to move away from it. We should use their new gyp/ninja based build system once we figure out how to properly cross-compile on all the libraries we care about. @martinthomson might have ideas on how to do that.

**Comment by eoger** [comment]
In order to try to statically link NSS with https://github.com/mozilla/application-services/issues/956#issuecomment-487795412, we need to be able to cross-compile the libs using gyp/ninja:

| From        | To | Current implementation
| ------------- |:-------------:| -----:|
| *     | Android |  [Link](https://github.com/mozilla/application-services/blob/master/libs/build-nss-android.sh)
| macOS      | iOS  | [Link](https://github.com/mozilla/application-services/blob/master/libs/build-nss-ios.sh)
| Linux | Win32 | [Link](https://github.com/mozilla/application-services/blob/ed6c563c272124e1cce1143672e7d1f0a59d2606/libs/build-nss-desktop.sh#L75-L87)
| Linux | macOS | [Link](https://github.com/mozilla/application-services/blob/ed6c563c272124e1cce1143672e7d1f0a59d2606/libs/build-nss-desktop.sh#L52-L73)

**Comment by eoger** [comment]
Note that the Linux -> Win32/macOS cross-compilations are (at the moment) only used for unit tests, so we could be swayed to just download them from a TC build.

**Comment by martinthomson** [comment]
The gyp builds should support cross compilation.  The `-t` argument to `build.sh` sets the target architecture, and you can pass overrides for gyp variables with `-Dxxx=yyy` to set things like `cc`.  I know that Firefox uses that, at least for Android.  I haven't got any instructions on how to enable that though, and no spare cycles in the next few weeks for an investigation.

**Comment by eoger** [comment]
Update on this week investigations:
- It is currently too hard to cross-compile linux->macOS as `gyp` isn't really helping and keeps getting in the way.
- I'm investigating how we could compile natively NSS on mac machines: I've been able to run Taskcluster tasks on a local mac mini.
- `chainOfTrust` is not supported by generic-worker on Mac, see https://github.com/taskcluster/generic-worker/pull/202, which is a blocker.
- Once the last point is resolved, we could potentially ask the NSS team to let us run tasks on their servers or provision the machines ourselves.

**Comment by jdragojevic** [comment]
closing since they are part of the big pr

**Comment by jdragojevic** [comment]
closing since they are part of the big pr

**Comment by scoutzeng** [comment]
Hi all, can NSS support cross compile from windows x64 to windows arm64 ? 
And how to cross compile from Linux x64 to windows arm64 ?
Is there any introducation about that, i am working on this for several weekends, thanks for your reply.

**Comment by mhammond** [comment]
Our cross-compilation support doesn't extend that far - https://github.com/mozilla/application-services/blob/main/libs/build-all-ios.sh and https://github.com/mozilla/application-services/blob/main/taskcluster/scripts/toolchain/cross-compile-setup.sh shows some of the support we have. Note that we are working on moving this repo into the main Firefox repo, so everything build related will be changing soon to use the tooling support in that main repo.
