### ISSUE TITLE
Gradle warning when building megazords: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#967]
We use a `compile` dependency on viaduct in the megazords in addition to the `api` dependency. It's required to make things compile (neither `api` nor `implementation` work), I don't know how to get rid of it nor do I fully understand it.

In order to fix the issue in request, we landed it as is, since manual testing shows it not to be a problem. We should fix it though

CC @ncalexan who might have insight.

Example of the badness: https://github.com/mozilla/application-services/blob/278dcf5cd53c4e47c1d1f32af38c3cd757db5b36/megazords/fenix/android/build.gradle#L87-L88

**Comment by ncalexan** [comment]
This makes no sense to me.  I would like to see complete logs of whatever failure you are seeing without this.  Presumably we are tickling some `api` detail with our special `configuration:` logic.

**Comment by thomcc** [comment]
If I comment that line out, I get
```
e: /Users/thom/application-services/megazords/fenix/android/src/main/java/mozilla/appservices/FenixMegazord.kt: (7, 28): Unresolved reference: httpconfig
e: /Users/thom/application-services/megazords/fenix/android/src/main/java/mozilla/appservices/FenixMegazord.kt: (19, 13): Unresolved reference: RustHttpConfig

> Task :fenix-megazord:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by ncalexan** [comment]
I theorize that this is an Android-Gradle bug, one that we might potentially see resolve itself as we upgrade a-s to newer and newer Android-Gradle plugin versions.  In the interim, Thom appears to have found a setup that is working, so we'll just let this be.

**Comment by jonalmeida** [comment]
The full warning shows that this affects multiple megazords and not only the fenix one:
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: fenix-megazord, lockbox-megazord, reference-browser-megazord
```

**Comment by ncalexan** [comment]
I can confirm that I've seen this locally, and that when I (briefly) dug in it made no sense to me.  Hopefully upgrading smooths things over, and of course Thom's megazord rewrite could get rid of this issue too.

**Comment by thomcc** [comment]
>Thom's megazord rewrite could get rid of this issue too.
Yeah, it does.

**Comment by rfk** [comment]
> Yeah, it does.

I'm going to close this in favor of #876 then.
