### ISSUE TITLE
Do not return duplicates in queryAutocomplete

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#970]
Currently it's possible that we will see the same URL multiple times in a set of suggestions coming out of `queryAutocomplete`. We use the `url` as a unique identifier at the app level, which makes this problematic. At the UI level, we need to be able to generate unique, stable IDs for the suggestions that are considered "the same" (to optimize how they're painted).

Currently we work around this by de-duping by URLs, picking the one with the highest frecency value. Doing this at the library level should result in less total work.

I think either of these scenarios will work:
- we get back a list that doesn't contain any duplicated URLs, or...
- we get back an opaque identifier for each suggestion that is unique per-suggestion and is stable across API calls

We're going to perform de-duplication at the top level anyway, so I think I'd just prefer to not have any duplicates coming out of the API.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-159)

**Comment by thomcc** [comment]
Worth noting that (url, reason) is currently unique.

I also am unsure I buy that this will make much of a perf difference (in the current impl, in practice this will mean we should only save sending over at most 1 record).

That said I agree sending duplicates back is probably not expected.

**Comment by tinoism** [comment]
I will take on this issue.

**Comment by thomcc** [comment]
👍 Feel free to reach out if you get stuck or have any confusion about where to get started.
