### ISSUE TITLE
Reading history paged / in chunks

### ISSUE THREAD

**Issue by pocmo** [mozilla/application-services#992]
AC issue: https://github.com/mozilla-mobile/android-components/issues/2644

In order to display history in the UI in an efficient way we need to query a subset of history (chunks).

We already have `getVisitedUrlsInRange()` - but since that requires a start and end timestamp we can't really control the amount of data we are going to read.

At the highest level an app developer may prefer to use the pagination library:
* https://developer.android.com/topic/libraries/architecture/paging
* Custom data source: https://developer.android.com/topic/libraries/architecture/paging/data#custom-data-source
* `DataSource` (See subclasses: `ItemKeyedDataSource`, `PageKeyedDataSource`, `PositionalDataSource`): https://developer.android.com/reference/androidx/paging/DataSource.html

I think we could implement the higher-level `DataSource` API in Android Components. However we would need a lower-level API to load ranges of data. Looking at [PositionalDataSource](https://developer.android.com/reference/android/arch/paging/PositionalDataSource) we'd need at least the total count and be able query a range (-> `LIMIT x,y`). [This simple version wouldn't address invalidating the data source yet; e.g. when the data changes while its being displayed.]

Also see [Paging beyond Room](https://commonsware.com/AndroidArch/previews/paging-beyond-room).

**Comment by vladikoff** [comment]
This is marked as `blocked` in https://github.com/mozilla-mobile/android-components/issues/2644 

@pocmo when do you need this by?

@thomcc @mhammond we might need to re-prioritize this if this is needed ASAP

**Comment by vladikoff** [comment]
oh just noticed, from that issue:

> @boek Regarding priorities: This is needed for MVP, right?

**Comment by thomcc** [comment]
@pocmo, @grigoryk: would an api that gets visits with a start timestamp and count solve this for you?

**Comment by pocmo** [comment]
I think for a simple first implementation we'd need something like:
* count(): SELECT COUNT(*) FROM .. ORDERED BY .. DESC
* range(offset, limit): SELECT * FROM .. ORDERED BY DESC LIMIT :limit OFFSET :offset

With that we should be able to implement a [PositionalDataSource](https://developer.android.com/reference/android/arch/paging/PositionalDataSource) that the app team can use to dynamically fill a `RecyclerView` as needed.

There's also a feature to automatically invalidate a `DataSource` if the underlying data has changed. But we could ignore that in the first iteration.

**Comment by thomcc** [comment]
> - count(): SELECT COUNT(*) FROM .. ORDERED BY .. DESC

Is this the total number of pages?
